### ISSUE TITLE
Desktop app menu cmd+q shortcut not works after packaged

### ISSUE THREAD

**Issue by linonetwo** [toeverything/AFFiNE#1003]

**Comment by pengx17** [comment]
It looks like CMD+Q on my machine and cannot reproduce this issue, but I will watch for other shortcut issues.

**Comment by linonetwo** [comment]
I have fixed this, forget to close.

**Comment by pengx17** [comment]
Fixed by https://github.com/toeverything/AFFiNE/pull/1207, right? @linonetwo

**Comment by linonetwo** [comment]
Yes, and the key is

https://github.com/toeverything/AFFiNE/pull/1207/files#diff-4f9daa24b0dd0fa063e30d819ae8db46b263353c01de9ceb117a2e994233c715R106

If use `=> ()`, the `cmd+q` will be discarded. Or if no providing this basic menu, the `cmd+q` will not work too.
