### ISSUE TITLE
incorrect sidebar UI

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#1011]

**Comment by Svaney-ssman** [comment]
The account info area missing the hover status, and the wrong font colour
check figma link here: https://www.figma.com/file/DGWHxU8cZHGT1pksAbRZlZ/virgo-2-1.0-editor-area(AFFiNE)?node-id=10426%3A15593&t=rgz2cgRceUzmYr7z-4

![Image](https://user-images.githubusercontent.com/110808979/218919581-bd528a5d-b6ae-4478-bac6-a4c7105da8f6.png)

**Comment by doodlewind** [comment]
Closed by https://github.com/toeverything/AFFiNE/pull/1059
