### ISSUE TITLE
The avatar of the  workspace setting  is not as same as the public workspace

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#1021]

**Comment by tzhangchi** [comment]
Public workspace 


![Image](https://user-images.githubusercontent.com/5910926/218956649-15568478-9ca4-4576-9761-ed50fd271792.png)

Workspace setting



![Image](https://user-images.githubusercontent.com/5910926/218956716-ed310be2-d1a6-495e-b48c-e3f49cd30212.png)

**Comment by tzhangchi** [comment]
@zuoxiaodong0815 do we have limitation for the request api?

**Comment by doodlewind** [comment]
Closed in OctoBase by @zuoxiaodong0815 (PR before #161)
