### ISSUE TITLE
The description text in the pop-up window when logging out of the account is confusing

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#1043]
Change "Retain local cached data" to "Retain cached cloud data"

![Image](https://user-images.githubusercontent.com/22443345/219261417-d384198c-490d-42bd-8da0-d11c83b675e8.png)

**Comment by joebeijing** [comment]
CC @ShortCipher5

**Comment by doodlewind** [comment]
Closed by https://github.com/toeverything/AFFiNE/pull/1059
