### ISSUE TITLE
No active style in setting tab when first time in setting page

### ISSUE THREAD

**Issue by QiShaoXuan** [toeverything/AFFiNE#1065]
![image](https://user-images.githubusercontent.com/22772830/219350799-0fabe164-8728-4e6b-bf56-9269e2a4eda7.png)

**Comment by doodlewind** [comment]
@QiShaoXuan I couldn't find the PR for d4f095871f18fbc7e6f29deaa686b4e2c3255e6f, any idea? Please consider using PR description to link your commits to issues, thanks!

**Comment by doodlewind** [comment]
Landed in current master (6fa0462), closing.
