### ISSUE TITLE
UI bugs feedback for Downhills preview version

### ISSUE THREAD

**Issue by enamulhasanabid** [toeverything/AFFiNE#1066]
### Here's in following PDF file, I demonstrated and explained all the bugs I found on AFFiNE Alpha "Downhills".

[AFFiNE_Downhills_BUGS_rbEH.pdf](https://github.com/toeverything/AFFiNE/files/10755501/AFFiNE_Downhills_BUGS_rbEH.pdf)

_Please take some time and patience to look all the bugs, in my opinion some of them are **major** bugs..._

**Comment by doodlewind** [comment]
Thanks for your feedback, we are actively working on them!

**Comment by enamulhasanabid** [comment]
> Thanks for your feedback, we are actively working on them!

Let me know if it's needed any explanation or example, of any bug I mentioned in this report... Also mention the bug number when asking... Best of luck AFFiNE team

**Comment by doodlewind** [comment]
Closing this during housekeeping sine we've released Downhills, thanks for the detailed feedback!
