### ISSUE TITLE
[bug]:  '/' doesn't work after create some new group

### ISSUE THREAD

**Issue by cosmic-flood** [toeverything/AFFiNE#108]
### Describe the bug

 '/' doesn't work after create some new group

### To Reproduce

1. 添加 "NODE_ENV=development" 至 env.local
2. 在本地运行环境
3. 添加一个新的Group，/ 为 Code块
4. 添加一个新的Group，/ 为看板，在看板中添加几个todo
5. 添加新组，/ 没有任何像第3、4步的选择出来了

可第二张截图，即使我打了 /  但并没有出选择group类型的那个面板

我是windows 11， edge浏览器，跑在localhost:4200

### Screenshots

![image](https://user-images.githubusercontent.com/68597908/183073136-9e1b6253-5150-4359-af83-c0c937e4aeae.png)

![image](https://user-images.githubusercontent.com/68597908/183073075-8da8f44d-019e-43be-a951-35c09bce5c3e.png)

### Platform

Windows11

### Browser

Edge

**Comment by aarhusgregersen** [comment]
Heya. I would like to take a look at this, but looking over the steps to reproduce I find it hard to figure out exactly what to do.

There's a lot of non-standard english characters that confuses me and makes it unclear what each step suggests.
Would it be possible to clean that up?

Also I notice you are referencing a `env.local` file, which I don't have (just installed fresh repo). I just have a `.env` which contains the `NODE_ENV` variable you mention, and I have a `.env.local-dev`. Neither matches the filename you mention. Are you referring to the `.env` file?

**Comment by darkskygit** [comment]
> Also I notice you are referencing a `env.local` file, which I don't have (just installed fresh repo). I just have a `.env` which contains the `NODE_ENV` variable you mention, and I have a `.env.local-dev`. Neither matches the filename you mention. Are you referring to the `.env` file?
.env.local is a file created by you, it will not be included in version management

**Comment by cosmic-flood** [comment]
> Heya. I would like to take a look at this, but looking over the steps to reproduce I find it hard to figure out exactly what to do.
> 
> There's a lot of non-standard english characters that confuses me and makes it unclear what each step suggests. Would it be possible to clean that up?
> 
> Also I notice you are referencing a `env.local` file, which I don't have (just installed fresh repo). I just have a `.env` which contains the `NODE_ENV` variable you mention, and I have a `.env.local-dev`. Neither matches the filename you mention. Are you referring to the `.env` file?

I just follow this link "https://affine.gitbook.io/affine/basic-documentation/contribute-to-affine/quick-start" to run application in localhost. 

My steps:

1. add "NODE_ENV=development" into file env.local (this file existed in main branch)
2. run application in localhost by following the tutorial link above
3. add new group, and a code block in this group
4. add a new group and a kanban inside
5.  add new group, and also create a block with '/'. but nothing happend

**Comment by Austaras** [comment]
fixed in #171
