### ISSUE TITLE
The local development environment cannot log in

### ISSUE THREAD

**Issue by zqran** [toeverything/AFFiNE#1093]
Steps to reproduce:

1. `pnpm dev`
2. open url: http://localhost:8080
3. click the login button

Then nothing happens~

**Comment by doodlewind** [comment]
This will require some private environment variable setup in AFFiNE cloud, which is not a public-maintainable state.

We will improve the DX in the future, having a better local environment for self-host developer. But at the moment this should be the expected behavior.

/cc @darkskygit @tzhangchi
