### ISSUE TITLE
change hover actions to click

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#1098]
Please change the **hover** to turn on drop-down menu to **click** to turn on in the following scenarios

![Image](https://user-images.githubusercontent.com/110808979/219606766-21dacbfc-4863-45ca-b36a-ae61614724cc.png)

![Image](https://user-images.githubusercontent.com/110808979/219606764-652de1e9-652d-4d44-a845-976a0f572b5e.png)

![Image](https://user-images.githubusercontent.com/110808979/219606765-584535f0-69f7-404a-84e0-7f806357625d.png)

**Comment by Svaney-ssman** [comment]
Additions

![Image](https://user-images.githubusercontent.com/110808979/220007462-6464c9f4-f2b3-44f2-8c2a-489d55f12346.jpeg)



![Image](https://user-images.githubusercontent.com/110808979/220007483-545191f9-34a3-4850-ad7f-858f2edd392f.jpeg)
