### ISSUE TITLE
Page title become "undefined" and is unable to interact

### ISSUE THREAD

**Issue by AlessioGr** [toeverything/AFFiNE#1104]
https://user-images.githubusercontent.com/70709113/219682065-5dfc4126-cf29-4f33-a41d-a7b79b590564.mov

This video showcases the bug. I have no idea whatsoever how it happened or how to reproduce it. Maybe you can find the issue based on the error message – if not, feel free to close the issue.

Thank you!!

**Comment by himself65** [comment]
Could please dump the data?

**Comment by himself65** [comment]
Could you please run this command and send the data to us?

```js
dc.workspaces[0].blocksuiteWorkspace.exportYDoc()
```

**Comment by himself65** [comment]
We have find the broken data, which happened when you read the old workspace

**Comment by AlessioGr** [comment]
Ah seems you figured it out, thank you! And sorry for the late reply. I tried to find the page again but somehow lost it
