### ISSUE TITLE
Need to change "Settings" to "Workspace Settings" 

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#1129]
According to the feedback, "Settings" is easily mistaken for the settings of the AFFiNE web app, and the name needs to be changed. CC @ShortCipher5 

At the same time, the two first letters of Quick search need to be capitalized.  

<img width="986" alt="image" src="https://user-images.githubusercontent.com/22443345/220035652-7ce38c9e-f815-400b-a24e-ded3d2657e1e.png">

**Comment by ShortCipher5** [comment]
`Quick Search`, so also `All Pages`

**Comment by zqran** [comment]
`Settings ` -> `Workspace Settings`?

**Comment by doodlewind** [comment]
@zqran yes, would you like to give it a try?

**Comment by zqran** [comment]
yeah, i'll try it

**Comment by joebeijing** [comment]
And a friendly reminder that all page names should be displayed in the Quick Search pop-up window, with consistency.

**Comment by zqran** [comment]
```json
{
  "Quick search": "Quick Search",
}
```

Do the `key` and `value` need to be consistent? @doodlewind

**Comment by ShortCipher5** [comment]
> ```json
> {
>   "Quick search": "Quick Search",
> }
> ```
> 
> Do the `key` and `value` need to be consistent? @doodlewind

This is a good question, because new keys reset the translation progress (acts as a new translation) on our external platform.
