### ISSUE TITLE
wrong space between avatar and email in invitation page

### ISSUE THREAD

**Issue by QiShaoXuan** [toeverything/AFFiNE#1133]
![Image](https://user-images.githubusercontent.com/110808979/220035835-edd9f17d-9947-4902-b368-b83d76100e8d.jpeg)

figma link: https://www.figma.com/file/DGWHxU8cZHGT1pksAbRZlZ/virgo-2-1.0-editor-area(AFFiNE)?node-id=10210%3A18395&t=Fjm5o0CcUogXw68G-4

**Comment by Svaney-ssman** [comment]
The dropdown menu wouldn't pop up now

![Image](https://user-images.githubusercontent.com/110808979/223304488-40058037-f84c-4b41-b472-a4847afe9f8a.png)
