### ISSUE TITLE
Crash after click search button at public workspace

### ISSUE THREAD

**Issue by lawvs** [toeverything/AFFiNE#1134]
https://app.affine.pro/public-workspace/MTjEmB7Chv-qxl_Yx-Syt/1f93d7efbc654dee9b0fae108d555554

```
TypeError: Cannot read properties of null (reading 'loadPublicWorkspace')
```

https://user-images.githubusercontent.com/18554747/220045139-ad9fce1a-9adb-44e1-b68d-427e7a61d8c0.mov

**Comment by himself65** [comment]
cannot be reproduced

**Comment by himself65** [comment]
maybe this could fix the bug

https://github.com/toeverything/AFFiNE/pull/1144

**Comment by himself65** [comment]
I believe this bug has disappeared in the latest, closing
