### ISSUE TITLE
Incomplete workspace list title in Russian

### ISSUE THREAD

**Issue by Heroboria** [toeverything/AFFiNE#1137]
**All text in long titles is not visible. Section "My Workspaces", Russian language.**

![Text-Wrap](https://user-images.githubusercontent.com/118163226/220053403-b480aa50-9dd5-4fb3-ad1c-93daa2d52f5b.jpg)

**I suggest setting up text wrapping.**

**Comment by zqran** [comment]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/15389209/220058077-ed1a21a7-8eeb-4eb7-97fc-e5e4969332fd.png">

Here is the full title when the mouse hovers.

**Comment by joebeijing** [comment]
> <img alt="image" width="491" src="https://user-images.githubusercontent.com/15389209/220058077-ed1a21a7-8eeb-4eb7-97fc-e5e4969332fd.png">
> 
> Here is the full title when the mouse hovers. And the workspace card's title has no title. @joebeijing

I think this is not the title of the card, this should be the specific type name displayed when the mouse hovers over the Workspace type.
For now, we will simply process it and all incomplete Titles need to be added with a mouse hover mechanism to display the full title. CC @QiShaoXuan 
In subsequent UI design, we will see if there is a better solution.

**Comment by QiShaoXuan** [comment]
Tip uses the title property in html to indicate that text is not fully displayed, and have confirmed that there are no objections
