### ISSUE TITLE
[feature]: 有没有可能在一个大的Group中的子group也可以布局

### ISSUE THREAD

**Issue by cosmic-flood** [toeverything/AFFiNE#114]
### 1~3 main use cases of the proposed feature

有没有可能在一个大的Group中的子group也可以布局。
如下图所示，"Affine简介"大Group中的两个子group也可以自由布局。
下面的图片的布局，实际上是跌了两个大group在一起的效果

![image](https://user-images.githubusercontent.com/68597908/183232488-30776f08-f7ae-4953-bf2f-1d8f73fa9834.png)

### what types of users can benefit from using your proposed feature

用affine做dashborad类文档的情况

### Additional context

只是我的一个灵感，但不一定有实际场景

**Comment by DiamondThree** [comment]
you can use grid，We currently do not support group nesting

**Comment by cosmic-flood** [comment]
> you can use grid，We currently do not support group nesting

what is grid? do you have some introduction for that?

**Comment by lawvs** [comment]
Hey @cosmic-flood, you can create a grid by drag a block to the head of another block, see the example

https://user-images.githubusercontent.com/18554747/183333045-bc9526e3-9ac5-4b55-915d-4fac0179eee6.mov

**Comment by cosmic-flood** [comment]
> Hey @cosmic-flood, you can create a grid by dragging a block to the head of another block, see this example
> 
>  Screen.Recording.2022-08-08.at.11.32.01.AM.mov

that is fantastic

**Comment by SaikaSakura** [comment]
> > Hey @cosmic-flood, you can create a grid by dragging a block to the head of another block, see this example
> > Screen.Recording.2022-08-08.at.11.32.01.AM.mov
> 
> that is fantastic
Any idea about grid, feel free to contact us.
