### ISSUE TITLE
Support better i18n best practice

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#1140]
Currently the implementation for the i18n can be improved and more standardised.

We can see the current language file: https://github.com/toeverything/AFFiNE/blob/master/packages/i18n/src/resources/en.json

We should define a set of rules for defining keys to be used.

Some issues:
- Capitalisation - some keys are capitalised such as `New Keyword Page` while others are not `Add to favourites`.
- Some keys exactly match their values `"Ooops!": "Ooops!"` while others do not `"mobile device": "Looks like you are browsing on a mobile device."`
- It impacts contributions, such as here: #1138
- If the key is changed, then it impacts the translation project - and creates a new entry - meaning any translation progress is lost.

**Comment by doodlewind** [comment]
Related: https://github.com/toeverything/blocksuite/issues/1296

**Comment by doodlewind** [comment]
I think this one seems to be on hold at the moment.
