### ISSUE TITLE
[bug]: Same head size (H1) but different size in real display... （都是h1的Head，但显示出来不一样大.. ）

### ISSUE THREAD

**Issue by cosmic-flood** [toeverything/AFFiNE#115]
### To Reproduce

如图所示，正常写..

![image](https://user-images.githubusercontent.com/68597908/183232818-08a7ac27-b9fa-4253-b34f-8887311892bd.png)

### Screenshots

![image](https://user-images.githubusercontent.com/68597908/183232832-548eec2c-53ef-4aa4-b108-f83177d881e3.png)

![image](https://user-images.githubusercontent.com/68597908/183232866-90daa56a-048c-465d-8e32-30fcb5db57bd.png)

### Platform

Windows11

### Browser

Edge

**Comment by mitsuhatu** [comment]
Adjustment in progress, thx

**Comment by Svaney-ssman** [comment]
Could you plz describe the issue in more detail?

**Comment by cosmic-flood** [comment]
> Could you plz describe the issue in more detail?

look at my screen shot, see the different between characters “Affine间接” and "所以啊啊”
