### ISSUE TITLE
Support self-hosting

### ISSUE THREAD

**Issue by zuoxiaodong0815** [toeverything/AFFiNE#1150]
- [x] #1174
- [ ] #1173

**Comment by davidhotar** [comment]
Yes pleasee!

**Comment by tzhangchi** [comment]
The new feature will be supported in the upcoming stable version.

**Comment by douglasparker** [comment]
@tzhangchi why was this closed as not planned?

See issue #1173 and discussion #2015.

I was super excited for AFFiNE until I noticed the docker image for self hosted was 5 months out of date and that AFFiNE Cloud was way ahead. Plenty of bugs in the self hosted version as well without all the latest updates and fixes.

**Comment by tzhangchi** [comment]
Hi @douglasparker , thank you for your support and love for AFFiNE! We understand your concern about the self-hosted Docker version being out of date. We want to assure you that in the upcoming stable release, we are excited to announce a brand new self-hosted Docker version of AFFiNE. This version will incorporate all the latest updates, fixes, and improvements. Thank you for bringing this to our attention, and your feedback is invaluable to us. Please stay tuned for the new release!
