### ISSUE TITLE
next.js hydration error in other language

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#1156]

**Comment by itsmegood** [comment]
I am not sure but are these connected https://stackoverflow.com/questions/73714388/nextjs-hydration-error-when-i-change-language

**Comment by himself65** [comment]
> I am not sure but are these connected https://stackoverflow.com/questions/73714388/nextjs-hydration-error-when-i-change-language

Thanks for the response, we have fixed this

**Comment by itsmegood** [comment]
Happy to help.
