### ISSUE TITLE
[bug]: Props format with errors are shown in the console

### ISSUE THREAD

**Issue by FedericoLeiva12** [toeverything/AFFiNE#117]
### Describe the bug

There are two props errors shown in the console before opening the app.

### To Reproduce

1. Add `NODE_ENV=development` in your `.env.local`
2. Run the app
3. Open the app in a browser and open the inspector / console.

### Screenshots

<img width="912" alt="Captura de Pantalla 2022-08-06 a la(s) 01 24 23" src="https://user-images.githubusercontent.com/49959270/183233636-f510ac4b-376c-4661-8387-be9a3a72e3ec.png">
<img width="554" alt="Captura de Pantalla 2022-08-06 a la(s) 01 24 56" src="https://user-images.githubusercontent.com/49959270/183233651-9df1e286-dadc-45de-84f8-d7272f6adb49.png">
![Uploading Captura de Pantalla 2022-08-06 a la(s) 01.25.14.png…]()

### Expected behavior

The console shouldn't show any error

### Platform

MacOS

### Browser

Chrome

**Comment by lawvs** [comment]
See https://github.com/toeverything/AFFiNE/pull/118

Thank for @FedericoLeiva12
