### ISSUE TITLE
Launch self-hosted version, mention user to set firebase

### ISSUE THREAD

**Issue by zuoxiaodong0815** [toeverything/AFFiNE#1173]

**Comment by SimonBiggs** [comment]
So that we can potentially have a completely self-hosted solution might you be interested in swapping firebase out for supabase? (https://supabase.com/)

**Comment by SolarDesalination** [comment]
Here is a good breakdown of some of the majors in the market: https://blog.hyperknot.com/p/comparing-auth-providers

**Comment by himself65** [comment]
We don't need firebase now
