### ISSUE TITLE
No Google Translate chrome extension support

### ISSUE THREAD

**Issue by qq15725** [toeverything/AFFiNE#1179]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/19576382/220814256-9d0c89b9-63c5-41b1-af25-536060b2b10d.png">

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/19576382/220814311-77fe165e-3a84-4a0a-9863-07e46176e25a.png">

Please close if this is not a problem 😄

**Comment by fourdim** [comment]
I'm sorry but could you please check it now?
For me, it works properly.
<img width="1152" alt="image" src="https://github.com/toeverything/AFFiNE/assets/59462000/f3d74e9d-69c5-4536-b13e-ce6efcfffa55">
It could be your network connection issue to google which blocks you from translation.

Feel free to reopen this issue if you are still having this problem.
