### ISSUE TITLE
After sign out, and then sign in again, and the doc is lost

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/AFFiNE#1181]
After log in firstly, and create a doc and store to the cloud
and wait for 1 min(needs a icon for uploading and needs to mention whether the doc has been synced to cloud or not)
and then sign out
and then log in to the same account
and the doc is lost
and the workspace name is also changed
<img width="1416" alt="截屏2023-02-23 15 26 26" src="https://user-images.githubusercontent.com/79373028/220843102-6f622cc7-a608-4a6a-8939-1f6abe14f7f6.png">

**Comment by Yipei-Operation** [comment]
updating:
after refresh the same link, it has shown to the latest workspace:
<img width="1242" alt="截屏2023-02-23 15 34 29" src="https://user-images.githubusercontent.com/79373028/220844482-0f0b7a23-10c6-4b64-83b4-a6904bcd1655.png">
while I am wondering why I can not find it in my local workspace:
<img width="1368" alt="截屏2023-02-23 15 35 00" src="https://user-images.githubusercontent.com/79373028/220844574-73d4a0b6-296e-4d17-a561-d9f837d51a6a.png">
it makes me feel a bit confused
(and another issue is why I open the AFFiNE cloud, it creates 2 cloud workspaces at one time)

**Comment by himself65** [comment]
## Conclusion

- [ ] Transition animation UI when syncing data
- [ ] workspace transform between `local` and `affine` need reasonable behavior
