### ISSUE TITLE
[improvement]: Pasting a link creates a new line - instead of inserting inline

### ISSUE THREAD

**Issue by cosmic-flood** [toeverything/AFFiNE#119]
### 1~3 main use cases of the proposed improvement

It's difficult to reproduce the probleme so i make a video, and there are also some other bugs in it...

Uploading 20220806_123931.mp4…

### Ideas for solution

idea is in the video

**Comment by FedericoLeiva12** [comment]
The video didnt't upload, please check it

**Comment by cosmic-flood** [comment]
> Video isn't uploaded, please check it

https://user-images.githubusercontent.com/68597908/183329163-be1c0b57-692f-4f16-8221-18495f81f468.mp4

here you are
