### ISSUE TITLE
Add Terms and Privacy for AFFiNE

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#1192]
AFFiNE privacy policy: https://affine.pro/privacy
AFFiNE Terms of service: https://affine.pro/terms

1. On the page of Google account authentication
Text to be added:  Before using app, you can review AFFiNE's **privacy policy** and **terms of service**
![CleanShot 2023-02-24 at 2 32 17@2x](https://user-images.githubusercontent.com/22443345/221108790-c732d4b8-2efa-4f08-9617-40cc4921f058.png)

2. On the popup windows of Contact US
@Svaney-ssman will provide the details of design.
![CleanShot 2023-02-24 at 2 37 26@2x](https://user-images.githubusercontent.com/22443345/221109481-dde7eb22-c14a-4149-8db0-1c2b4f2ceb96.png)

CC @ShortCipher5

**Comment by darkskygit** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/25152247/222450377-1b9e5467-03bd-4748-bb20-a78a856a6535.png">

is recommand add to here, google is a third-party login
in the future, we can also add login methods such as github/email+password, and we can't add links to the login provider's page.

**Comment by joebeijing** [comment]
> <img alt="image" width="679" src="https://user-images.githubusercontent.com/25152247/222450377-1b9e5467-03bd-4748-bb20-a78a856a6535.png">
> 
> is recommand add to here, google is a third-party login in the future, we can also add login methods such as github/email+password, and we can't add links to the login provider's page.

We will provide a new design of login page, this is a temporary solution.

**Comment by tzhangchi** [comment]
thanks to the design of @joebeijing , this important issue should be followed by  @darkskygit

**Comment by tzhangchi** [comment]
0.6.0 We will have a new registration page, and this task will be rescheduled
