### ISSUE TITLE
Add a logout mechanism for accounts so that local data is preserved even when the Token expires

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#1193]
When token is expired, a Toast message with the text "Session expired, please log in again." will be displayed and clicking on "Login" will bring up the login window.
The toast do not auto-close, need to be closed manually.

**Comment by QiShaoXuan** [comment]
The temproary solution now is show a toast display: 'Automatic login fail, please login self later'， and then jump to the local workspace
