### ISSUE TITLE
An `Unhandled Runtime Error` has been raised when run the master branch

### ISSUE THREAD

**Issue by Zheaoli** [toeverything/AFFiNE#1198]
<img width="960" alt="CleanShot 2023-02-25 at 14 47 26@2x" src="https://user-images.githubusercontent.com/7054676/221343077-a6408837-d86b-457b-9b43-4fac87f1efa5.png">

Run the code in the master branch by using `pnpm dev`, and access 127.0.0.1:8080 in browser

**Comment by himself65** [comment]
Same as https://github.com/toeverything/AFFiNE/issues/1156

**Comment by himself65** [comment]
This will be fixed in https://github.com/toeverything/AFFiNE/issues/1197

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/commit/e0481d29ad24a5fa843a6841e44d0507e7fe7b77
