### ISSUE TITLE
[improvement]: New group in Edgeless Mode is inserted too far away from main content

### ISSUE THREAD

**Issue by cosmic-flood** [toeverything/AFFiNE#120]
### 1~3 main use cases of the proposed improvement

Please check video

https://user-images.githubusercontent.com/68597908/183234314-0605d14d-1a54-4667-960e-b88c0519e890.mp4

### Ideas for solution

Please check video

**Comment by tzhangchi** [comment]
Thanks for your feedback, I will discuss it with our designers
