### ISSUE TITLE
Enabling AFFiNE Cloud breaks the page

### ISSUE THREAD

**Issue by AlessioGr** [toeverything/AFFiNE#1200]
This is what I did:
1. Clicked on enable affine cloud on app.affine.pro
2. It kept loading infinitely instead of enabling affine cloud (the loading bar on the blue button to enable cloud)
3. Since it kept loading infinitely, I reloaded the page
4. This happened:

https://user-images.githubusercontent.com/70709113/221416843-e3e60d40-3221-4276-9797-ac270db30065.mp4

After waiting 5 minutes, I opened the page and everything worked fine - including enabling AFFiNE Cloud. I'm not sure why it happened or how to reproduce it

**Comment by ShortCipher5** [comment]
Thanks for your report, we think this has been fixed now. However, we are keeping an eye on this incase it crops back up.

**Comment by himself65** [comment]
I believe this wont happen again, closing
