### ISSUE TITLE
Cannot view shared workspace

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#1201]
Sometimes when inviting a user they will become a "member" (invitation accepted) but still not have permission to view the workspace. The workspace will not show in their workspace list.

When going to the workspace url it will show a generic 404 error.

No console errors are shown.

**Comment by ShortCipher5** [comment]
Some extra images:

![Screenshot 2023-02-27 at 10 57 10](https://user-images.githubusercontent.com/4605025/221462630-f02bb116-ecbe-48ae-b16f-760ab48b6a87.png)

![image](https://user-images.githubusercontent.com/4605025/221462380-a54ceddb-7a81-4fee-af2c-01b7a2e48241.png)

![Screenshot 2023-02-27 at 10 55 45](https://user-images.githubusercontent.com/4605025/221462642-a78c75dc-4a3a-4ef0-93a6-eb66f73b18e8.png)

**Comment by zuoxiaodong0815** [comment]
I have fixed this problem (The workspace will not show in their workspace list).
Another, which is a 404 error, may be ok after publishing new affine version of Alex Yang.
