### ISSUE TITLE
[bug]: Edgeless mode runs into errors with undo operations

### ISSUE THREAD

**Issue by JimmFly** [toeverything/AFFiNE#121]
### Describe the bug

The whiteboard reports an error after performing the undo operation multiple times

### To Reproduce

Frist I added a few lines of text to the whiteboard，then I got this error by pressing ALT+Z multiple times while using the whiteboard function. Now I can't get into the whiteboard anymore. Please tell me how to fix this problem.

### Screenshots

![image](https://user-images.githubusercontent.com/102217452/183236357-206d5d30-9258-450e-bc09-88404928bf79.png)

### Expected behavior

I just want to undo the previous action

### Platform

win 11

### Browser

edge

**Comment by tzhangchi** [comment]
> ### Describe the bug
> The whiteboard reports an error after performing the undo operation multiple times
> 
> ### To Reproduce
> Frist I added a few lines of text to the whiteboard，then I got this error by pressing ALT+Z multiple times while using the whiteboard function. Now I can't get into the whiteboard anymore. Please tell me how to fix this problem.
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/102217452/183236357-206d5d30-9258-450e-bc09-88404928bf79.png)
> 
> ### Expected behavior
> I just want to undo the previous action
> 
> ### Platform
> win 11
> 
> ### Browser
> edge
> 
> ### Additional context
> _No response_

Thank you for your feedback. We are currently reproducing this problem. Can you upload a video of the problem

**Comment by JimmFly** [comment]
https://user-images.githubusercontent.com/102217452/183555742-4f3e24b8-23d9-4eaf-bf8c-325932c59468.mp4

**Comment by JimmFly** [comment]
https://user-images.githubusercontent.com/102217452/183556110-b2b42b91-6b74-4fba-8faa-98c5269b5a98.mp4

**Comment by JimmFly** [comment]
https://user-images.githubusercontent.com/102217452/183559052-8f518c67-e3d6-44e2-a423-f3c2771c3b76.mp4
