### ISSUE TITLE
incorrect affine cloud status and icons

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#1210]
here is the design: @joebeijing plz check if the design is ready
https://www.figma.com/file/DGWHxU8cZHGT1pksAbRZlZ/virgo-2-1.0-editor-area(AFFiNE)?node-id=10453%3A15747&t=eo5GsfnnWM1L56iu-4

![Image](https://user-images.githubusercontent.com/110808979/221770330-80084e08-afca-4138-bfc6-9826243d2e52.png)

**Comment by joebeijing** [comment]
So far, all above is OK @Svaney-ssman

**Comment by QiShaoXuan** [comment]
The UI issue is fixed in https://github.com/toeverything/AFFiNE/pull/1371, but still last some function not support, so tag this issue to feat

**Comment by Svaney-ssman** [comment]
close as the design upgraded

**Comment by houjoe0829** [comment]
Correted this issue's status.
