### ISSUE TITLE
adjusted ui design of deleting workpsace

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#1211]
https://www.figma.com/file/DGWHxU8cZHGT1pksAbRZlZ/virgo-2-1.0-editor-area(AFFiNE)?node-id=10210%3A16980&t=X1rs3hEbyPUka5k1-4

solved the bugs in deleting interactive layout caused by language differences
need @joebeijing to comfirm

![Image](https://user-images.githubusercontent.com/110808979/221772929-36f21146-a20c-411b-b8df-dd0add9b06f1.png)

**Comment by joebeijing** [comment]
Agree with that, thank you @Svaney-ssman
