### ISSUE TITLE
image syncing sometimes incorrect

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#1223]
![img_v2_2f8c9c95-9d6e-406a-9e48-10cd767a7a3g](https://user-images.githubusercontent.com/14026360/222079957-0e28a1eb-5528-4416-b9f4-c00b407af61d.jpg)

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/commit/f34a64a82a6edbf9d8b4903e688148011f4d63ce
