### ISSUE TITLE
Unhandled Runtime Error `Error: startModel or endModel does not have text`

### ISSUE THREAD

**Issue by Zheaoli** [toeverything/AFFiNE#1271]
Reproduce steps:

1. Create a new page
2. Input some text in the title bar
3. Delete the text by using keyword

I have recorded a video to help you guys figure out the root cause.

https://user-images.githubusercontent.com/7054676/222519467-9c843b9c-eb7d-4bf5-a50b-7f7520016c9c.mov

**Comment by Zheaoli** [comment]
Another reproduce procedure

1. create a new page
2. input some text in title bar
3. select some text and delete by using keyboard

**Comment by Himself65** [comment]
Have you cleanup the local storage data?

**Comment by daochouwangu** [comment]
same issue, but show in another way.
1. focus on title bar.
2. press LeftArrow and RightArrow
3. alert error
