### ISSUE TITLE
[improvement]: provide docs in AFFiNE or a demo

### ISSUE THREAD

**Issue by JK-Wang** [toeverything/AFFiNE#129]
### 1~3 main use cases of the proposed improvement

AFFiNE is really amazing!!
Here is some proposes in my view:
1. gitbook is good, but not perfect
2. maybe there should be a demo for refer

### Ideas for solution

we can write introduce or manual docs in AFFiNE to show many feature and usage

### what types of users can benefit from using your proposed improvement

AFFiNE beginner

**Comment by DiamondThree** [comment]
thanks， The online demo will be available by August 12

**Comment by HeJiachen-PM** [comment]
Hello! Intros are airways welcomed. You may find us for support in discord or telegram channel and the link can be found in our readme.

**Comment by tzhangchi** [comment]
The #AFFiNE live demo is here：https://affine.pro/ 
More details to know how to play with it: https://blog.affine.pro/posts/the-affine-live-demo-is-here-with-15-reasons-from-the-team-why-you-should-try
Any issue welcome to submit on Github: https://github.com/toeverything/AFFiNE 
Welcome to contact us for any suggestions & feedback for using our live demo✨
