### ISSUE TITLE
Edgeless does not support dark mode

### ISSUE THREAD

**Issue by m1911star** [toeverything/AFFiNE#1293]
<img width="1734" alt="image" src="https://user-images.githubusercontent.com/4948120/222745552-49fc5ea2-0fe7-4f9f-bcd1-97b92701572d.png">

**Comment by himself65** [comment]
I think this is not a bug, the design team haven't give it a theme

**Comment by doodlewind** [comment]
Closing as we don't intend to add dark mode support for edgeless canvas. The edgeless toolbar has supported dark mode, though.
