### ISSUE TITLE
datacenter support React 18 suspense mode

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#1300]
There still need to be some issues with the data center loading logic.

For example, the UI will always have no workspaces on the first rendered screen.

And when the user switch workspace, the avatar and name may will flickering.

## Related

- https://github.com/toeverything/AFFiNE/pull/1296
- https://github.com/toeverything/AFFiNE/issues/1257

**Comment by himself65** [comment]
Blocking until https://github.com/pmndrs/jotai/issues/1813
