### ISSUE TITLE
[bug]:  In Edgeless Mode connectors don't anchor to objects as expected

### ISSUE THREAD

**Issue by KierPrev** [toeverything/AFFiNE#134]
### Describe the bug

Connectors doesn't anchor to any object, in the board

### To Reproduce

1. Create two objects
2. Use the connector tool to linked them
3. Move one object
4. The connector doesn't move with the object

### Platform

Windows 11

### Additional context

Affine Client

**Comment by alt1o** [comment]
yes, it does have some problem...Working on it. Maybe next week will fixed it.
