### ISSUE TITLE
Button "jumps" between tabs (workplace settings)

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#1345]
Collaboration <-> Publish tabs

The button jumps between switching tabs.

![jump](https://user-images.githubusercontent.com/4605025/223056795-de321b2c-1020-46c2-9c17-8f4c6bc2121e.gif)

**Comment by himself65** [comment]
I think the behavior here is exactly the same as the old app.affine.pro, but I will fix this
