### ISSUE TITLE
Publish to web requires refresh

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#1347]
Publish to web does not seem to give the appropriate feedback.

![p2w](https://user-images.githubusercontent.com/4605025/223058518-596df32c-9082-47b0-bf06-588be5e2d347.gif)

Refresh is required to see the public link.

**Comment by ShortCipher5** [comment]
This also applies to `Stop publishing`.

**Comment by himself65** [comment]
This is a bug that the state didn't updated
