### ISSUE TITLE
Enable AFFiNE Cloud - cannot enable

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#1349]
The button that says `Enable AFFiNE Cloud` reports that it cannot be enabled until you `Enable AFFiNE Cloud`.

![p2w](https://user-images.githubusercontent.com/4605025/223059578-45c77fab-0605-42cb-a097-286c2bf4788c.gif)

**Comment by himself65** [comment]
Here's a regression

https://github.com/toeverything/AFFiNE/blob/50ff9b0c5cafd74d0e022e4fa376767828e6230d/apps/web/src/components/affine/workspace-setting-detail/panel/publish/index.tsx#L130-L131
