### ISSUE TITLE
[bug]: In board, zoom scroll jumps too fast from 10% 70% 250%

### ISSUE THREAD

**Issue by KierPrev** [toeverything/AFFiNE#135]
### Describe the bug

I am using the affine client, I don't know if it is a problem with the client, or Affine itself.  Tried on different computers with different scroll settings, but the result is the same.  Vertical scrolling works at the correct speed. 

### To Reproduce

1. Go into board mode
2. Press Ctrl + Mouse scroll to change the zoom level
3. The level jumps too quickly, and you end up with a miniature board or giant letters

### Platform

Windows 11

### Additional context

Affine client

**Comment by mitsuhatu** [comment]
It may be related to the system settings. We are following up, thx💐

**Comment by JimmFly** [comment]
Can I work on this issue?
