### ISSUE TITLE
Deleting workspace not refreshing page

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#1354]
Sometimes when deleting a workspace it will be deleted, but the process of removing it and refreshing the page will not trigger.

![p2w](https://user-images.githubusercontent.com/4605025/223062532-d7191098-b653-4171-94eb-fd0d7bd50bed.gif)

**Comment by himself65** [comment]
If it does happen “sometimes”, it might be related with https://github.com/pmndrs/jotai/issues/1813

**Comment by himself65** [comment]
I think the reason is API failed
