### ISSUE TITLE
feat: add new translation (Spanish - Spain)

### ISSUE THREAD

**Issue by albertodlc** [toeverything/AFFiNE#1359]
Add new language to the project:

- Spanish (Spain)

**Comment by albertodlc** [comment]
@doodlewind  I can help with this issue, could you please assign it to me?

**Comment by himself65** [comment]
Thanks for contributing on i18n!

**Comment by albertodlc** [comment]
@Himself65 I need access to i18n platform, Could you please send an invitation?

**Comment by himself65** [comment]
ok

**Comment by himself65** [comment]
Could you please give me your email to developer@toeverything.info

**Comment by albertodlc** [comment]
@Himself65 Done

**Comment by ShortCipher5** [comment]
I will mark this as closed, as the invitation has been sent.

If others are looking for more info, you can check out the i18n project home: https://community.affine.pro/c/i18n-general/

Once a substantial percentage of translations have been completed the language will be added to the available list.
