### ISSUE TITLE
  The tooltip for the sync status button after setting up AFFiNE Cloud synchronization needs to be modified

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#1368]
<img width="396" alt="CleanShot 2023-03-07 at 2 37 39@2x" src="https://user-images.githubusercontent.com/22443345/223341938-f73e18be-30aa-4a66-9097-4a50afe122ef.png">

Expected effect：
Hovertips “Synced with AFFINE Cloud”
<img width="294" alt="CleanShot 2023-03-07 at 2 38 32@2x" src="https://user-images.githubusercontent.com/22443345/223342309-12d5ce42-d479-4851-a118-f1da58fabdda.png">

**Comment by akhil27styles** [comment]
is this issue resolved?

**Comment by joebeijing** [comment]
> is this issue resolved?

We are currently refactoring our AFFiNE Cloud and it has not been officially launched yet. We will validate this issue again when it is launched.

**Comment by EYHN** [comment]
fixed
