### ISSUE TITLE
`document.title` not sync when viewing shared links.

### ISSUE THREAD

**Issue by LeuisKen** [toeverything/AFFiNE#1369]
Hello guys, AFFiNE is amazing and I'm trying to migrate from the notion, and I find that the `document.title` adaptation is not that well when I view pages in shared workspaces which could be a trouble when viewing browser history like follows:

![image](https://user-images.githubusercontent.com/7701575/223350655-33a4fea1-85d0-49f0-ad7c-880a3f851b66.png)

Here is an example link to reproduce: https://app.affine.pro/public-workspace/MTjEmB7Chv-qxl_Yx-Syt/7deccc98a5a9448fbfc3ca73e660149d

And you can find it works as expected when not using shared workspaces.

![image](https://user-images.githubusercontent.com/7701575/223351149-d1415226-582c-4de0-9753-2ab6c6e198ab.png)

There might be some consistency problem with the code behavior, and if you appreciate it, I'd like to dive into this issue and make a pull request for it.

Waiting for your reply.

: )

**Comment by himself65** [comment]
I believe that the latest code has fixed this problem, could please try https://affine-preview.vercel.app and give us a response?
