### ISSUE TITLE
[feature]: Support for ctrl+z to operate undo

### ISSUE THREAD

**Issue by cosmic-flood** [toeverything/AFFiNE#137]
### 1~3 main use cases of the proposed feature

Ctrl-z for step-back operations.

### Ideas for solution

Ctrl-z for step-back operations

### what types of users can benefit from using your proposed feature

everyone

**Comment by lawvs** [comment]
Thank you for your review. We will fix this as soon as possible.

**Comment by chriseikrem** [comment]
And may I add - ctrl-shift-z to redo.
