### ISSUE TITLE
There's infinite loading as well as enabling AFFiNE cloud within the workspace setting

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#1380]
![image](https://user-images.githubusercontent.com/121489905/223398860-aebea655-97c3-43d2-b302-f665b6957d34.png)

**Comment by joebeijing** [comment]
@doodlewind Who could be the assignee of this issue? Maybe some technical guys

**Comment by doodlewind** [comment]
Should be mostly related to stale local data, requires verifying before shipping to app.affine.pro @Himself65 @joebeijing

**Comment by vandenberghev** [comment]
I'm experiencing the same issue with a brand new docker container & volume, in a clean, new Firefox container.
A Chromium browser does seem to load successfully though. So this seems to be more of a Firefox related issue.

![image](https://user-images.githubusercontent.com/26387795/227772310-eb1a79b5-49fc-4de4-b918-4799adcc4e60.png)

**Comment by himself65** [comment]
See our latest affine cloud
