### ISSUE TITLE
Those workspaces already synced should've not appeared as I signed out

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#1381]
![image](https://user-images.githubusercontent.com/121489905/223401080-bd0d0081-e19b-4f97-908f-2e22f52ef91c.png)

>

**Comment by himself65** [comment]
The current logic didn't deal with clean-up data

https://github.com/toeverything/AFFiNE/blob/061ceaa9fefa4e932366164996e82fecf58a6cd8/apps/web/src/providers/ModalProvider.tsx#L68-L71
