### ISSUE TITLE
Should've not been found within trash if it says delete is the permanent delete

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#1382]
![image](https://user-images.githubusercontent.com/121489905/223404262-547a20c1-7066-4186-9a20-8419e1b36e98.png)

**Comment by himself65** [comment]
Duplacated https://github.com/toeverything/AFFiNE/issues/1373

Landed in https://github.com/toeverything/AFFiNE/commit/b7b946f0026c0f6241b499b630e91c4e656b7a4d
