### ISSUE TITLE
Fulltext search in /slash menu

### ISSUE THREAD

**Issue by pegak** [toeverything/AFFiNE#1387]
I am not able to do full text search in /slash menu.
1. Write slash
2. Menu appears
3. Write "cb"
4. You don't see anything, because search is not fulltext

**Where:**
https://stage.affine.pro

**Browser:**
Edge - Version 112.0.1717.0 (Official build) canary (64-bit)

**Comment by tzhangchi** [comment]
hi, @pegak , It had be supported by @
