### ISSUE TITLE
Workspace has lost name

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#1400]
Workspace has lost its name.

![Screenshot 2023-03-08 at 09 42 50](https://user-images.githubusercontent.com/4605025/223598152-eccbb936-4456-4b61-8285-2f4454edabd4.png)

**Comment by ShortCipher5** [comment]
This was a local workspace - title was lost on an update.

**Comment by himself65** [comment]
I believe this is related to https://github.com/toeverything/blocksuite/pull/1536, And the bug should have been fixed.

Please reopen this if you see the issue again
