### ISSUE TITLE
Delete workflow incorrect

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#1402]
The page name (title) is missing from delete prompt.

![Screenshot 2023-03-08 at 09 50 35](https://user-images.githubusercontent.com/4605025/223598772-a0e02411-34e8-49f8-ae25-1a937304caf1.png)

Expected:
![Screenshot 2023-03-08 at 09 52 25](https://user-images.githubusercontent.com/4605025/223598815-f9b40b46-6cfe-4ea7-9553-7bd7892e4154.png)

**Comment by ShortCipher5** [comment]
Also the page should be move to trash first - the prompt and notification are incorrect.

**Comment by xell** [comment]
Closed as fixed.
