### ISSUE TITLE
Indentation issue with tab and delete key in editor

### ISSUE THREAD

**Issue by VictorNanka** [toeverything/AFFiNE#1420]
I am using AFFiNE's editor to create documents and notes. However, I found that when creating and editing lists, using the tab key and delete key does not indent and delete hierarchical structures as expected. 

For example, when writing a nested list and pressing the tab key, it should indent one level, but instead, it stuck and nothing happened. Conversely, when using the delete key, it only deletes the list structure instead of outdenting.

Expectation: 

- [ ] When press the tab key, it should indent one level.
- [ ] When press the delete key, it should outdent one level unless no space left of cursor.

**Comment by doodlewind** [comment]
Hi, thanks for your feedback! Can you reproduce it at the https://blocksuite-toeverything.vercel.app/?init playground? If so I think this is an editor issue. I guess indenting should work, since we should have implemented the tab-to-indent support for nested lists.

**Comment by VictorNanka** [comment]
> Hi, thanks for your feedback! Can you reproduce it at the https://blocksuite-toeverything.vercel.app/?init playground? If so I think this is an editor issue. I guess indenting should work, since we should have implemented the tab-to-indent support for nested lists.

Thanks for your reply, I find it woking properly in playground.

After some further exploration, I have come to the realization that I was mistaken in my initial assessment. 

I would like to kindly request that you close this issue as it is no longer an issue. Thank you for your time and attention to this matter, and I apologize for any inconvenience I may have caused.
