### ISSUE TITLE
Downhills upgrade feedback triaging 0309

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#1429]
Tracked with highest priority

* toeverything/AFFiNE#1419
* toeverything/AFFiNE#1416
* toeverything/AFFiNE#1381 toeverything/AFFiNE#1323
* toeverything/AFFiNE#1380
* toeverything/AFFiNE#1379
* toeverything/AFFiNE#1351
* toeverything/AFFiNE#1284
* toeverything/AFFiNE#1277
* toeverything/AFFiNE#1274 
* toeverything/AFFiNE#1222

P1

* toeverything/AFFiNE#1418 
* toeverything/AFFiNE#1415
* Server 404 fallback: toeverything/AFFiNE#1380 toeverything/AFFiNE#1354
* toeverything/AFFiNE#1295
* toeverything/AFFiNE#1270
* toeverything/blocksuite#1589

Next round feedback after stage updated:

- [ ] #1458
- [ ] 2. Missing sync tab <img width="600" src="https://user-images.githubusercontent.com/7312949/223976696-3f395edd-8d68-46eb-ad99-63bb5f29efe3.png">
- [ ] 3. Missing quick search entry <img width="600" src="https://user-images.githubusercontent.com/7312949/223977204-5ed9b68e-d861-4f60-868a-806614fb5741.png">
- [x] 4. Wrong toast hint , fixed in https://github.com/toeverything/AFFiNE/pull/1460
    <img width="600" src="https://user-images.githubusercontent.com/7312949/223977422-42604845-cb7a-4761-8813-bdb080cc354b.png">
- [ ] 5. Error opening default page using local workspace https://user-images.githubusercontent.com/7312949/223978905-7d40884a-d7cc-440f-82b6-0abe6f356cac.mp4
- [ ] 6. Should not display "Recent" hint when there are no recent pages <img width="600" src="https://user-images.githubusercontent.com/7312949/223978978-e96e5e84-0074-4e5c-9deb-09f3e399d09d.png">
- [x] 7. Opening setting raises error <img width="600" src="https://user-images.githubusercontent.com/7312949/223978015-9e2ea0ea-acfc-41c1-9442-69fad8cfb613.png">
- [x] 8. Unable to switch to edgeless mode when there is no title <img width="600" src="https://user-images.githubusercontent.com/7312949/223978372-5042c98a-b6d0-46df-bad9-35e382b98d1a.gif">
- [ ] 9. Infinite loading on exiting cloud account <img width="600" src="https://user-images.githubusercontent.com/7312949/223979099-96f8b300-f853-48d3-a343-e9d59e3d85c5.jpg">
- [x] 10. Unable to respond after signing in cloud <img width="600" src="https://user-images.githubusercontent.com/7312949/223978699-25d3cd2e-176c-4af3-8341-29ac64cc3fe2.jpg">

**Comment by joebeijing** [comment]
11. Missing toast prompts while switching between Page and Edgeless modes, when switching to Page mode, display the Toast "Page mode", when switching to Edgeless mode, display "Edgeless mode". @QiShaoXuan

**Comment by joebeijing** [comment]
12. Can not use Slash Commands to insert Date and time.  @lawvs @JackiePengp

**Comment by JackiePengp** [comment]
13. avatar automatically changes as I edit the name
![avatar automatically changed](https://user-images.githubusercontent.com/121489905/223985554-3203180e-51a9-4beb-a71b-01bce5e49fab.gif)

**Comment by JackiePengp** [comment]
[]14. unable to enable the affine cloud within the working space
![Unable to enable the affine cloud within the workspace](https://user-images.githubusercontent.com/121489905/223987171-58367672-c92e-47eb-bae1-c591a849f793.gif)

**Comment by QiShaoXuan** [comment]
> 

fixed in https://github.com/toeverything/AFFiNE/pull/1460

**Comment by Yipei-Operation** [comment]
<img width="741" alt="截屏2023-03-09 19 45 21" src="https://user-images.githubusercontent.com/79373028/224013787-fbd4e365-9ae9-4364-a4ff-5fe9e32a1e01.png">
when enabling the affine cloud, the icon of the cloud workspace looks wired

**Comment by doodlewind** [comment]
Closing since we have migrated to https://github.com/orgs/toeverything/projects/13. Thanks for the feedback!
