### ISSUE TITLE
[improvement]: KanBan  Add Field menu

### ISSUE THREAD

**Issue by fanjing22** [toeverything/AFFiNE#143]
### 1~3 main use cases of the proposed improvement

<img width="620" alt="截屏2022-08-08 下午5 21 08" src="https://user-images.githubusercontent.com/109729699/183385076-83df8579-8552-4170-8c01-4489de3bdf3f.png">

**Comment by lawvs** [comment]
I can't reproduce, can you add the detailed reproduction steps?

**Comment by fanjing22** [comment]
![Image](https://user-images.githubusercontent.com/109729699/183840623-30257356-3d9e-423e-94b6-e6c7097d06d6.png)

**Comment by alt1o** [comment]
click trigger
