### ISSUE TITLE
Empty collaboration member tab

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#1458]
<img width="1688" alt="img_v2_ec156d4b-652e-42a9-bfef-2375d42a3eag" src="https://user-images.githubusercontent.com/7312949/223980268-23b2b212-92cd-4489-b5c1-dc433065d3d2.png">

**Comment by himself65** [comment]
I believe this is because server error. Need add a error boundary

**Comment by doodlewind** [comment]
Related to #1354, requires unified error boundary

**Comment by pengx17** [comment]
I can reproduce this issue by blocking the `permissions` API, and it will show the following error "get memebers failed".
I think later we can add a "get members failed" art in the page for better UX, but I recommend we can ignore this issue for now. @doodlewind 

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/584378/224240508-8627a60b-df5e-42be-b998-98000e62773e.png">

**Comment by doodlewind** [comment]
Agree, cc @joebeijing
