### ISSUE TITLE
There is no "Workspace Settings" option in the pop-up window of "My Workspaces"

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#1469]
@Svaney-ssman I didn't find the design file about this, could you send it to @QiShaoXuan 

<img width="794" alt="CleanShot 2023-03-09 at 11 12 27@2x" src="https://user-images.githubusercontent.com/22443345/224067540-fd48b352-4e8b-40ec-b835-31fd7bd7d51e.png">

**Comment by Svaney-ssman** [comment]
https://www.figma.com/file/DGWHxU8cZHGT1pksAbRZlZ/virgo-2-1.0-editor-area(AFFiNE)?node-id=11702%3A15578&t=izdfrHov1TOIrqEE-4
