### ISSUE TITLE
[improvement]: left toolbar hover style

### ISSUE THREAD

**Issue by fanjing22** [toeverything/AFFiNE#148]
### 1~3 main use cases of the proposed improvement

<img width="364" alt="截屏2022-08-08 下午6 29 23" src="https://user-images.githubusercontent.com/109729699/183398382-a352c2b6-9465-42cc-b7b4-7b2f22a0e3ce.png">

<img width="511" alt="截屏2022-08-08 下午6 31 48" src="https://user-images.githubusercontent.com/109729699/183398765-e20c63c4-6303-4c33-a12e-43c25aadab89.png">

**Comment by fyZheng07** [comment]
* hover status
* Indentation of child list
![image](https://user-images.githubusercontent.com/63830919/183591868-d5ccab96-a39b-4180-809b-1b9cdb793b8b.png)
