### ISSUE TITLE
Unable to load cloud workspace icon

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#1484]
Upstream: https://github.com/toeverything/AFFiNE/issues/1429#issuecomment-1461879644

![Image](https://user-images.githubusercontent.com/7312949/224068256-10400b47-3469-4d75-af51-d727c4aa10ce.png)

**Comment by thorseraq** [comment]
When affine cloud is enabled and neither the uploading nor loading ever fails, the avatar works fine. So no worries, we just add  a retry mechanism when the api fails

![Image](https://user-images.githubusercontent.com/20554850/224247417-2c18b8d8-9fc0-4b2b-8438-b0597d878232.png)

![Image](https://user-images.githubusercontent.com/20554850/224246056-c3f72a4e-834e-4d00-a531-6363b51e1d64.png)
