### ISSUE TITLE
Local storage bloat on every page refresh

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#1488]
![Image](https://user-images.githubusercontent.com/7312949/224214234-8dfd9772-7665-4751-a595-bf11f4826696.png)

**Comment by himself65** [comment]
This is a expected behavior in yjs-indexeddb 

https://github.com/yjs/y-indexeddb/blob/217fd6da1ed12b300eba647db247af4ac1257cf2/src/y-indexeddb.js#L34

**Comment by doodlewind** [comment]
Closed by #1651 as a workaround.
