### ISSUE TITLE
cannot enable AFFiNE Cloud within the workspace settings-collaboration

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#1492]
cannot enable AFFiNE Cloud within the workspace settings-collaboration
![cannot enable AFFiNE Cloud within the workspace settings-collaboration](https://user-images.githubusercontent.com/121489905/224220859-8a1e0722-e886-433d-8572-02a0385e3a1d.gif)

**Comment by doodlewind** [comment]
I tried and found AFFiNE cloud should be logged in (by checking out the top left modal), but whenever logged in or not, the `Enable AFFiNE Cloud` button is always there.

**Comment by doodlewind** [comment]
Duplicate of #1517
