### ISSUE TITLE
[feature]: Maybe new language support can be added

### ISSUE THREAD

**Issue by nvdkzyp** [toeverything/AFFiNE#151]
### 1~3 main use cases of the proposed feature

This is a good project, but my English is not good. I hope that new language support can be added in future versions, and I hope that it can have simplified Chinese.

### Ideas for solution

I don't know exactly how to do it, but please let me know if it's possible to translate it in a local file.

### what types of users can benefit from using your proposed feature

users with poor english

**Comment by tzhangchi** [comment]
> ### 1~3 main use cases of the proposed feature
> This is a good project, but my English is not good. I hope that new language support can be added in future versions, and I hope that it can have simplified Chinese.
> 
> ### Ideas for solution
> I don't know exactly how to do it, but please let me know if it's possible to translate it in a local file.
> 
> ### what types of users can benefit from using your proposed feature
> users with poor english
> 
> ### Additional context
> _No response_

Thank you for your suggestions. Supporting more languages is already in our plan

**Comment by jidenanian** [comment]
这个项目的本地、协作、开源、隐私第一的理念是我理想中的笔记软件应用，希望本土化（**中文简体**）也能做好，添加多语言支持，更希望有中文社区交流

**Comment by HeJiachen-PM** [comment]
> 这个项目的本地、协作、开源、隐私第一的理念是我理想中的笔记软件应用，希望本土化（**中文简体**）也能做好，添加多语言支持，更希望有中文文档和中文社区交流。

当然。中国区的运营会有更特别的法律法规要求。我们还在探索合适的，合规，且保障AFFiNE使用体验的途径。
