### ISSUE TITLE
Sub-menu displays as blank and options are only visible when the mouse hovers over it

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#1520]
<img width="334" alt="CleanShot 2023-03-10 at 10 45 54@2x" src="https://user-images.githubusercontent.com/22443345/224346907-69982102-bc91-476b-9ccf-ae86568c8f90.png">

**Comment by QiShaoXuan** [comment]
Fixed in https://github.com/toeverything/AFFiNE/pull/1543
