### ISSUE TITLE
AFFiNE editor shortcuts conflicting on macOS

### ISSUE THREAD

**Issue by xuzuodong** [toeverything/AFFiNE#1534]
Hi,

When I use text editor on a Mac, I am used to using [macOS native Emacs key shortcuts](https://jblevins.org/log/kbd). But AFFiNE doesn't support it. For example, if I want to move my cursor to left (equivalent to `←` keydown event), I prefer to use `control + B`. But this shortcut is occupied by “Setting text bold”, which should be only triggered by `Cmd + B` on macOS.

Same issue occurred when I use  `control + A`, `control + E`, and `control + P`.

Can it be fixed?

**Comment by kanweiwei** [comment]
It looks like it's been repaired
