### ISSUE TITLE
The display effect of the top bar in Public Workspace does not match the expected effect after opening a single page

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#1537]
<img width="878" alt="CleanShot 2023-03-11 at 6 03 01@2x" src="https://user-images.githubusercontent.com/22443345/224478194-556b8cf3-4817-45eb-acb2-e25690efbe2a.png">

For example：https://app.affine.pro/public-workspace/MTjEmB7Chv-qxl_Yx-Syt/7deccc98a5a9448fbfc3ca73e660149d cc @Himself65

**Comment by EYHN** [comment]
The part of the product that was causing this issue has been removed or significantly reworked since it was created.
