### ISSUE TITLE
The Local Workspace should also display a Sync tab in the Workspace Settings

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#1547]
This is mainly to facilitate users to check the current synchronization method and enable the AFFiNE Cloud service.
![CleanShot 2023-03-13 at 2 08 01@2x](https://user-images.githubusercontent.com/22443345/224620892-3416f3d3-21fb-49bf-98ac-c56fb4359647.png)

Expected effect：
<img width="683" alt="CleanShot 2023-03-13 at 2 08 46@2x" src="https://user-images.githubusercontent.com/22443345/224620999-e3a244c8-d706-419f-a399-3710e7450e0b.png">

**Comment by JimmFly** [comment]
A new design has been adopted, close this issue.
