### ISSUE TITLE
The title in the main body and the title in the top bar are inconsistent

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#1548]
![CleanShot 2023-03-13 at 2 14 35@2x](https://user-images.githubusercontent.com/22443345/224622475-cb80aca3-79e9-405b-a409-89c4f4ff6b86.png)

**Comment by doodlewind** [comment]
Seems the the `pageMeta.title` can be out of sync with `pageBlock.title`. Need to be addressed.

**Comment by tzhangchi** [comment]
It has been fixed
