### ISSUE TITLE
Would it be better to remove the icon from the link?

### ISSUE THREAD

**Issue by zzj3720** [toeverything/AFFiNE#1555]
![Kapture 2023-03-13 at 21 56 48](https://user-images.githubusercontent.com/17165520/224723588-c151debb-5f2e-4877-ad9b-4076fee9d0f8.gif)
When I set text that contains multiple attributes as a link, I end up with multiple link icons.

**Comment by tzhangchi** [comment]
The new feature will be supported in the upcoming stable version.
