### ISSUE TITLE
Support Table of contents

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#1557]
Feel difficult to make to structure my content using AFFiNE when the content is bigger and longer without the categories
![image](https://user-images.githubusercontent.com/121489905/224872513-1ce226cf-b014-4455-9017-df395f8ede74.png)

**Comment by JackiePengp** [comment]
![image](https://user-images.githubusercontent.com/121489905/224872662-ec970f66-b163-4215-bcc3-5998300c9129.png)
This issue is proposed by this user and will continue to follow up as this issue is being solved

**Comment by xell** [comment]
As we have a tasklist https://github.com/toeverything/AFFiNE/issues/3295 and a specific issue https://github.com/toeverything/blocksuite/issues/4159 for the topic, this issue is closed.

**Comment by xell** [comment]
As we have a tasklist https://github.com/toeverything/AFFiNE/issues/3295 and a specific issue https://github.com/toeverything/blocksuite/issues/4159 for the topic, this issue is closed.
