### ISSUE TITLE
Client app updater

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#1572]
- update checker
- in update update
- "new version available" notification

May need to think about db migration.

As this issue has been requested multiple times. Maybe we shall increase its priority.

**Comment by ShortCipher5** [comment]
1) Should we consider a "back up your data first" option - auto or manual - before performing the update?

2) I would suggest having some sort of brief update intro with an update notification. That could be a simple change log (general user friendly) that outlines any new features/updates and fixes.
