### ISSUE TITLE
Support image viewer on double click

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#1582]
Support expanding a full screen image viewer on double click image block. Similar with following:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/7312949/225043037-eb93f2cc-7eb1-411c-95e7-0ea31bc0bf91.png">

This is not assigned yet. We may reassign according to our progress.

**Comment by joebeijing** [comment]
list some features below.
- Image preview in full screen
- Close image preview
- Support zoom in/out using trackpad (P1)
- Support zoom in/out using mouse wheels while pressing ⌘/ctrl  (P1)
- Download images
- If the current page has multiple images, you can click on "previous" or "next" to scroll through and view them. (P1)

P1 means "nice to have".

**Comment by lokeswaran-aj** [comment]
Hii @doodlewind I would like to contribute to this issue. I came across this npm pack called [react-simple-image-viewer](https://www.npmjs.com/package/react-simple-image-viewer). Can I work on this issue?

**Comment by doodlewind** [comment]
Hi @lokeswaran-aj thanks for your interest! Though simple as it seems, the best practice of adding image viewer may involve more effort than reusing an image viewer package, since the BlockSuite editor itself is not using React, and there requires more refactoring to make the editor pluggable for these features. I think @Saul-Mirone will be working on it, and we will expose more APIs for community when the extensibility in BlockSuite become more mature. By this approach, we can reduce the ad-hoc implementation and make the editor more suitable for third-party customization. Hope this makes sense to you!

**Comment by hwangdev97** [comment]
The  new design of image viewer 

https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?node-id=1071%3A36731&t=onfYuB0CWF01TWhz-1

and add the P1 feature

- Support switching to the previous and next images with left⬅️ and right➡️ buttons.

**Comment by himself65** [comment]
I'm working on this now. Hope we can have it this week

**Comment by himself65** [comment]
We have the initial support for image preview. Since it just supports basic features, this is a nice start.

If someone wants to continue to work on this, let me know.
