### ISSUE TITLE
Could not export as markdown​

### ISSUE THREAD

**Issue by lzlme** [toeverything/AFFiNE#1588]
### What happened?

as in the title

https://user-images.githubusercontent.com/117659326/225352895-1dd0f48e-99fc-4909-a281-dedcc26f718a.mov

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'contentParser')
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/pull/1590

**Comment by lzlme** [comment]
@Himself65 When will you deploy to app.affine.pro ? It seems that the changes have not taken effect yet.

**Comment by himself65** [comment]
> @Himself65 When will you deploy to app.affine.pro ? It seems that the changes have not taken effect yet.

Our deployment schedule is per two weeks. So it will be landed in next week

**Comment by lzlme** [comment]
> > @Himself65 When will you deploy to app.affine.pro ? It seems that the changes have not taken effect yet.
> 
> Our deployment schedule is per two weeks. So it will be landed in next week

@Himself65 Still not working...

**Comment by himself65** [comment]
![image](https://user-images.githubusercontent.com/14026360/233467943-1e23b033-49b3-40c4-8cc4-97111d42e758.png)

**Comment by himself65** [comment]
We delay releasing to the production.
