### ISSUE TITLE
[Electron] Adapt UI layout for desktop app

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#1601]
May need design team's input here @joebeijing

**Comment by joebeijing** [comment]
It is suggested to first handle the position adaptation of the Window Controls in the AFFiNE client on Mac to avoid a separate top bar.
<img width="1299" alt="CleanShot 2023-03-17 at 2 09 35@2x" src="https://user-images.githubusercontent.com/22443345/225826227-25a8215a-827b-47c9-91a1-85b315eeebb2.png">

Expected effect, just like Notion.  CC @xell 
![CleanShot 2023-03-17 at 2 10 29@2x](https://user-images.githubusercontent.com/22443345/225826400-e366ebd4-2f33-40f6-a6d6-962e4ad85172.png)
