### ISSUE TITLE
In dark mode, the font colour of the code block is not visible. ​

### ISSUE THREAD

**Issue by lokeswaran-aj** [toeverything/AFFiNE#1616]
### What happened?

When I typed a hello world statement in python or javascript while in dark mode, the font color is still dark and the code is not visible.

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Chrome

### Anything else?

<img width="697" alt="Screenshot 2023-03-20 at 7 46 35 AM" src="https://user-images.githubusercontent.com/74011196/226231356-fa76973f-7ace-44ad-af5c-849429d984c6.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xell** [comment]
Closed as fixed by an untraceable commit.
