### ISSUE TITLE
[improvement]: Styling suggestion (color change) for paper/edgeless toggle

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#162]
### 1~3 main use cases of the proposed improvement

<img width="465" alt="截屏2022-08-09 下午5 11 29" src="https://user-images.githubusercontent.com/110808979/183611503-405ce0cb-a4d2-4be3-aade-b6225c50c34d.png">

**Comment by lawvs** [comment]
Related to https://github.com/toeverything/AFFiNE/issues/160

**Comment by ArunGovil** [comment]
Can I work on this issue?

**Comment by lawvs** [comment]
@ArunGovil Thanks for your support, we appreciate it. But there are many design details still undecided, It still need to wait a bit before start develop.

**Comment by ArunGovil** [comment]
@lawvs  Alright, no problem. May I know if the design details will be updated here under the issue itself or somewhere else?

**Comment by alt1o** [comment]
2 opacity
