### ISSUE TITLE
Add storage capacity limit for AFFiNE Cloud

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#1633]
10MB for a single file
10GB for whole account.

**Comment by himself65** [comment]
Related https://github.com/toeverything/AFFiNE/commit/127e9bdba273ed923bfd57889ff6bf404e3d3401

**Comment by houjoe0829** [comment]
We're still missing an interface design that displays the account capacity in Settings, and already we've added special text for Early access with capacity limits.  @Svaney-ssman 
Special text: [Internal link](https://toeverything.feishu.cn/docx/YSE1d7ecOoHzFPx3FNacVH3rnVb#LIfmdr1NYogolxxoI8tcZJgCnlc)

**Comment by darkskygit** [comment]
> We're still missing an interface design that displays the account capacity in Settings, and already we've added special text for Early access with capacity limits. @Svaney-ssman Special text: [Internal link](https://toeverything.feishu.cn/docx/YSE1d7ecOoHzFPx3FNacVH3rnVb#LIfmdr1NYogolxxoI8tcZJgCnlc)

api is ready, i will merge it when i finish adding the test.

**Comment by Svaney-ssman** [comment]
Check [storage design in figma](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=13691-181013&mode=design&t=wxcvd3b9RfXI6itj-4) @QiShaoXuan

**Comment by QiShaoXuan** [comment]
All down in https://github.com/toeverything/AFFiNE/pull/4069
