### ISSUE TITLE
When the token is invalid, refreshing will display a large number of error Toast prompts.

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#1635]
Even though logging out and logging in cloud solve that, there shouldn't be so many error messages. Just pop up a prompt and login box, or maybe refreshing can automatically solve the problem? 

https://user-images.githubusercontent.com/22443345/226557010-d72a4b04-3b30-48ea-bfe0-4c561eb71095.mp4

**Comment by himself65** [comment]
I landed a hotfix that enforces you re-login when the token expired.

A better approach need after the code refactor

Refs: https://github.com/toeverything/AFFiNE/pull/1661
