### ISSUE TITLE
The tooltip within toolbar of edgeless mode has a weired acronym bug

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#1655]
![tooltip的缩写是有意设置的吗？](https://user-images.githubusercontent.com/121489905/226815581-7eb71c56-9890-42eb-b4f2-b27d9fb33759.gif)

**Comment by JackiePengp** [comment]
like the "pen" is "pen p", the "hand" becomes "hand h"

**Comment by joebeijing** [comment]
Actually this is not a bug, but a design that warrants optimization just like it in Miro which has better UI for hotkeys. @Svaney-ssman @xell Could you take a look at this?
<img width="184" alt="CleanShot 2023-03-22 at 4 29 47@2x" src="https://user-images.githubusercontent.com/22443345/226843744-2cbb9ad0-0bc9-4b44-b579-93f658c51b3a.png">

**Comment by xell** [comment]
They are indeed the single letter shortcut(hotkeys). We'll improve the visual style to indicate the function.

**Comment by Svaney-ssman** [comment]
Actually there are little differences in color and font between the body text and shortcuts, Should I make the "visual difference" bigger? @joebeijing @xell 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/110808979/228516595-05a1e812-2eab-416e-95f8-da29643a5874.png">

**Comment by xell** [comment]
> Actually there are little differences in color and font between the body text and shortcuts, Should I make the "visual difference" bigger? @joebeijing @xell 
> 
> <img width="845" alt="image" src="https://user-images.githubusercontent.com/110808979/228516595-05a1e812-2eab-416e-95f8-da29643a5874.png">
> 
> 

yes, please 🙏
