### ISSUE TITLE
​Can't delete page with long title

### ISSUE THREAD

**Issue by dmytrodubinin** [toeverything/AFFiNE#1666]
### What happened?

If the document have long title, I can't delete this page because "delete" button is not showed

Here is the demo:
[Screencast from 2023-03-23 08-46-20.webm](https://user-images.githubusercontent.com/8066458/227125026-8562515e-0977-4e68-923f-03bbc3e142bc.webm)

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
@Himself65 see here

<img width="689" alt="image" src="https://user-images.githubusercontent.com/7312949/227141711-b947a0e5-3384-493c-ad8c-7811e4c9ce45.png">

**Comment by himself65** [comment]
im working on this
