### ISSUE TITLE
can not go to stage.affine.pro​

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/AFFiNE#1669]
### What happened?

when go fo stage.affine.pro, show loading all the time

### Version

stage.affine.pro

### What browsers are you seeing the problem on?

Chrome

### Anything else?

<img width="1264" alt="xdbKzTrnqF" src="https://user-images.githubusercontent.com/79373028/227175909-042a7d4f-2ff5-4814-ae8c-d7e6bd8ec913.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/commit/3e299b97c3cb87466cecd25daeaf69336015761e
