### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by i-iooi-i** [toeverything/AFFiNE#167]
### Describe the bug

Login failed

### To Reproduce

I learned to install affine on this website.
https://mariushosting.com/how-to-install-affine-on-your-synology-nas/

After the installation is completed, click login and an error will be prompted.

![image](https://user-images.githubusercontent.com/1827701/183686008-843c32fa-16c3-44df-9b93-6fc7170a6c6a.png)
I thought it was my personal problem, but it seems that other people have also encountered it.

### Screenshots

![image](https://user-images.githubusercontent.com/1827701/183684745-d9e7e9c8-5710-4e0b-b581-b2c289f42248.png)

### Platform

Synology dsm7.1

### Browser

chrome

**Comment by tzhangchi** [comment]
> https://mariushosting.com/how-to-install-affine-on-your-synology-nas/
maybe you can try this scripts
```
docker pull ghcr.io/toeverything/affine:nightly-latest 
docker run -d -p 4200:3000 --name affine -d ghcr.io/toeverything/affine:nightly-latest  
open http://localhost:4200
```

**Comment by i-iooi-i** [comment]
> > https://mariushosting.com/how-to-install-affine-on-your-synology-nas/
> > maybe you can try this scripts
> 
> ```
> docker pull ghcr.io/toeverything/affine:nightly-latest 
> docker run -d -p 4200:3000 --name affine -d ghcr.io/toeverything/affine:nightly-latest  
> open http://localhost:4200
> ```

![image](https://user-images.githubusercontent.com/1827701/183695542-3cf7867b-5aa3-4350-a292-5291d8599914.png)
![image](https://user-images.githubusercontent.com/1827701/183695774-63e3bd96-4bc0-4538-8b43-65d13cbf1f49.png)

Thank you for your help. I installed this. The problem still exists.🥲🥲

**Comment by ad56583964** [comment]
l met this problem too

**Comment by ad56583964** [comment]
maybe, because l have to use proxy software to access google??

**Comment by i-iooi-i** [comment]
> maybe, because l have to use proxy software to access google??

换了几个不同的梯子，问题是相同的。
若是因为梯子的缘故，那真的无法使用了。😢

**Comment by darkskygit** [comment]
fixed, please re-pull the image
