### ISSUE TITLE
[improvement]: Interactive navbar - add hovering effect on links

### ISSUE THREAD

**Issue by PritamSarbajna** [toeverything/AFFiNE#168]
### 1~3 main use cases of the proposed improvement

So while visiting [affine.pro](https://affine.pro/) I saw that the navbar is not changing colors or adding effects when I'm hovering over them. So it is not looking good.

### Ideas for solution

Just use any hovering effect like changing colors or animations that'd be great

### what types of users can benefit from using your proposed improvement

All type of users

**Comment by alt1o** [comment]
Good suggestion! We are working on it.
