### ISSUE TITLE
The creation of a new page cannot be found by other members within the All pages in the collaboration mode

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#1680]
the page called What's new - AFFiNE 0324-v2 cannot be found by other members when they check the all pages
![img_v2_6aed23e5-8a7f-4aba-a7aa-3a9b54f54e6g](https://user-images.githubusercontent.com/121489905/227420936-7aada991-c6f9-455f-9e1c-ee0a0b3b82e2.jpg)
![image](https://user-images.githubusercontent.com/121489905/227420972-616abf95-f71b-4211-b4b6-94e2d6e5d4c4.png)

**Comment by himself65** [comment]
Issue on websocket provider, fixed now
