### ISSUE TITLE
Can the title be changed to a 6-level title 

### ISSUE THREAD

**Issue by Angel0726** [toeverything/AFFiNE#1685]
### Description

因为markdown、word等都是6级标题。所以affine是不是可以改成6级标题，这样便于其他文件的导入

### Use case

将markdown导入affine

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Himself65** [comment]
需要产品确认 @joebeijing

**Comment by himself65** [comment]
i think we already have h6 title

**Comment by himself65** [comment]
![image](https://user-images.githubusercontent.com/14026360/228731747-1fa78011-4419-4ecd-a2ec-90a1e61a4246.png)

**Comment by Angel0726** [comment]
pre alpha是没有的

**Comment by himself65** [comment]
sorry about that but pre-alpha won't update anymore

**Comment by Angel0726** [comment]
thanks

**Comment by Angel0726** [comment]
when you publish your roadmap

**Comment by himself65** [comment]
the roadmap is here https://github.com/orgs/toeverything/projects/10
