### ISSUE TITLE
[improvement]: Click on the link in the file, and the link should open on a new page.

### ISSUE THREAD

**Issue by PritamSarbajna** [toeverything/AFFiNE#169]
### 1~3 main use cases of the proposed improvement

When clicking on the links of navbar the github and blog's links should open in a new tab because they are different pages if they belonged to the same page it would not be a concern.

### Ideas for solution

If it uses `<a> </a>` for the links then just adding `target= "_blank"` inside the tag should resolve the problem

### what types of users can benefit from using your proposed improvement

All type of users

**Comment by alt1o** [comment]
yeah, it's really not good right now, we will fix it.

**Comment by RohitYandigeri** [comment]
Can I work on this issue ?

**Comment by darkskygit** [comment]
> Can I work on this issue ?

welcome pr!

**Comment by darkskygit** [comment]
fixed
