### ISSUE TITLE
Add option to disable merging of editors when moving from edgeless ⇒ normal mode​

### ISSUE THREAD

**Issue by AlessioGr** [toeverything/AFFiNE#1690]
### Description

Currently, if you have 2 text editors in edgeless mode, and switch back to normal mode, they are merged into one monolith text editor.

There should be an option to disable that behavior – both globally and locally. That way, I'd be able to use edgeless mode as an "extension" to my normal text instead of having it merged in a weird way.

### Use case

I, personally, don't want a lot of stuff to be merged. I've designed many things in edgeless mode in a way where it only makes sense in edgeless mode.
When switching back to normal mode, I expect to just be able to read the "Main" text editor.

When stuff from edgeless mode is merged, it often breaks my structure and doesn't make sense anymore when viewing it in normal mode.

### Anything else?

If there is stuff in edgeless mode and you are in normal mode, there should be a visual indicator showcasing that _stuff_ is in edgeless mode / that there is "more". Otherwise, it's easy to miss that there is more stuff hidden in edgeless mode.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
In the future, we will implement two points to solve this issue:
1. In Edgeless, we will distinguish between Text and Note, and only Note will be displayed in Page mode.
2. Even for Note, you can choose to hide it and not show it in Page mode.
In addition, regarding the suggestion of indicating that there is more content in Edgeless in Page mode, we will seriously consider it. Thank you very much.

**Comment by EYHN** [comment]
The part of the product that was causing this issue has been removed or significantly reworked since it was created.
