### ISSUE TITLE
SSR/SEO for public workspace​

### ISSUE THREAD

**Issue by lawvs** [toeverything/AFFiNE#1691]
### Description

Now open graph will always show the AFFiNE intro even on a public page.

<img width="644" alt="Screenshot 2023-03-26 at 12 45 52 AM" src="https://user-images.githubusercontent.com/18554747/227730570-ec64b37f-2a26-49cb-b3f9-9c02a29aa42a.png">

<img width="236" alt="Screenshot 2023-03-26 at 12 49 20 AM" src="https://user-images.githubusercontent.com/18554747/227730717-41f6c877-ec8c-4f89-b6e5-48c25b5e9fd0.png">

### Use case

I think the public page should show the page title and related description

https://app.affine.pro/public-workspace/H6vffRmJbCfA-r3kq_36_/LOk_Yw0IS0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
We need SSR support.

**Comment by tzhangchi** [comment]
> We need SSR support.

We are delighted to see that everyone has mentioned the support for SSR. We will incorporate it into our plans for the next version and allocate resources for its development.

**Comment by EYHN** [comment]
The SSR feature is on our long-term roadmap and has not yet been implemented. I will close this issue first, and when we start working on ssr, we will open another issue to track the progress.
