### ISSUE TITLE
App.affine.pro has data lost problem as the page is refreshed.

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#1739]
![image](https://user-images.githubusercontent.com/121489905/228466530-0246fc0b-5e38-4998-bf01-34bdb80659ea.jpeg)
![image](https://user-images.githubusercontent.com/121489905/228466572-e5c1866c-a461-4dbe-8b6f-d2a71ca0ae1d.jpeg)

**Comment by JackiePengp** [comment]
on the way uploading pictures, failed a few times ..

**Comment by himself65** [comment]
I'm woking on this

**Comment by himself65** [comment]
I think this might be because the current user is not the owner?

**Comment by himself65** [comment]
We have fixed two issues that might cause data to be lost when refreshed, but not sure.

https://github.com/toeverything/AFFiNE/commit/4dd1490eefec3d1d077bdd484d906c75670c9ed7

https://github.com/toeverything/AFFiNE/commit/14f073c8eabfae6088a859bc289db1b051cce436
