### ISSUE TITLE
Cannot paste in app.affine.pro​

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#1745]
### What happened?

Cannot paste

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
https://user-images.githubusercontent.com/14026360/228675227-969e6526-0686-4054-b2a4-f5e80c461c3c.mp4

**Comment by doodlewind** [comment]
Hope @QiShaoXuan can take a look, thanks!
