### ISSUE TITLE
​Sort by `create date` or `update date` or `a-z` by click on the top column

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#1752]
### Description

![image](https://user-images.githubusercontent.com/14026360/228727660-298e7222-9723-49e2-8d81-0fa87026db72.png)

should have button to sort the page list

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
reassigned to @lawvs

**Comment by tzhangchi** [comment]
Key feature
