### ISSUE TITLE
UI suggestion: amplify the scope of quick search, not only embody the title but the content incorporating the searched word within page

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#1758]
For example, can showcase the searched word within the page/content, not just the title. it helps precisely find the info users look for
![image](https://user-images.githubusercontent.com/121489905/228797710-f57be3fa-659e-4449-8b08-67c107c8d47a.png)

**Comment by TinsFox** [comment]
It would be even better if you can highlight the content in the results and match the keywords!

**Comment by houjoe0829** [comment]
Duplicated with https://github.com/toeverything/AFFiNE/issues/3294

**Comment by JackiePengp** [comment]
您好，先生（女士），您的邮件我已收到，我会尽快拜读。谢谢您。
