### ISSUE TITLE
How to create a demo workspace with cloud synchronization enabled by default

### ISSUE THREAD

**Issue by chenmins** [toeverything/AFFiNE#1766]
### Description
在用户已经登录的前提下：

是否可以在创建demo workspace是启用云同步
如果不能，请问在哪里修改
谢谢

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Himself65** [comment]
你的意思是默认开始cloud功能吗？

**Comment by joebeijing** [comment]
Thank you for your feedback.
Actually, we have a plan to add an option that lets users choose whether to enable AFFiNE Cloud for a new workspace after its creation, similar to the option shown in the attached screenshot. 
<img width="428" alt="CleanShot 2023-04-03 at 11 10 23@2x" src="https://user-images.githubusercontent.com/22443345/229402805-cf9b59be-602e-464b-b701-b635828f9d52.png">

**Comment by joebeijing** [comment]
Related to https://github.com/toeverything/AFFiNE/issues/1766

**Comment by QiShaoXuan** [comment]
This function will be supported in this iteration, please look forward to our new version
