### ISSUE TITLE
Affine fails to build on Arch Linux

### ISSUE THREAD

**Issue by Bad3r** [toeverything/AFFiNE#1768]
### What happened?

I am trying to package Affine for the Arch Linux user repository. I am currently attempting to build Affine following the instructions provided at https://github.com/toeverything/AFFiNE/blob/master/docs/building-desktop-client-app.md.

Affine fails to build for multiple reasons:

- Module not found: The 'encoding' module cannot be found in the specified path. This might be due to a missing dependency or incorrect import path.
- TypeError: There is an attempt to destructure 'publicRuntimeConfig' property of an undefined object. This might be caused by a misconfigured or missing Next.js configuration.
- Error: NEXT_PUBLIC_FIREBASE_API_KEY not found: It seems like setting it is required?
- Invalid next.config.mjs options: The Next.js configuration file contains the property 'sentry', which is not set

### Version

app.affine.pro

### Relevant log output

https://gist.github.com/Bad3r/7cb7da9a59ac3ce1326e61fa32ec4629

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Fixes: https://github.com/toeverything/AFFiNE/commit/676a5793e233de2b35317691bdd9a6df00b988bd

**Comment by himself65** [comment]
Please set your node.js version to `18` LTS

**Comment by Bad3r** [comment]
@Himself65 I am using Node.JS `v18.15.0`
The build still fails due to the missing keys:
```zsh
❯ yarn build:app
     Running beforeBuildCommand `yarn build:preload && yarn build:affine`

  public/preload/index.js  226b 

⚡ Done in 1ms
$ cd /git/AFFiNE
$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @blocksuite/blocks@npm:0.5.0-20230324040005-14417c2 [03998] doesn't provide nanoid (pa9dde), requested by @blocksuite/phasor
➤ YN0002: │ @blocksuite/blocks@npm:0.5.0-20230324040005-14417c2 [03998] doesn't provide yjs (p0c52d), requested by @blocksuite/phasor
➤ YN0002: │ @blocksuite/blocks@npm:0.5.0-20230324040005-14417c2 [03998] doesn't provide yjs (p91588), requested by @blocksuite/virgo
➤ YN0002: │ @blocksuite/store@npm:0.5.0-20230324040005-14417c2 [03998] doesn't provide lit (p596c3), requested by @blocksuite/virgo
➤ YN0002: │ @firebase/analytics-compat@npm:0.2.4 [02b1b] doesn't provide @firebase/app (pfb3ea), requested by @firebase/analytics
➤ YN0002: │ @firebase/app-check-compat@npm:0.3.4 [02b1b] doesn't provide @firebase/app (p9d611), requested by @firebase/app-check
➤ YN0002: │ @firebase/auth-compat@npm:0.3.5 [02b1b] doesn't provide @firebase/app (p241f4), requested by @firebase/auth
➤ YN0002: │ @firebase/auth-compat@npm:0.3.5 [02b1b] doesn't provide @firebase/app-types (pa5621), requested by @firebase/auth-types
➤ YN0002: │ @firebase/firestore-compat@npm:0.3.5 [02b1b] doesn't provide @firebase/app (pe1692), requested by @firebase/firestore
➤ YN0002: │ @firebase/firestore-compat@npm:0.3.5 [02b1b] doesn't provide @firebase/app-types (p4ed65), requested by @firebase/firestore-types
➤ YN0002: │ @firebase/functions-compat@npm:0.3.4 [02b1b] doesn't provide @firebase/app (pda7bb), requested by @firebase/functions
➤ YN0002: │ @firebase/installations-compat@npm:0.2.4 [02b1b] doesn't provide @firebase/app-types (p2ce31), requested by @firebase/installations-types
➤ YN0002: │ @firebase/messaging-compat@npm:0.2.4 [02b1b] doesn't provide @firebase/app (p2ed9f), requested by @firebase/messaging
➤ YN0002: │ @firebase/performance-compat@npm:0.2.4 [02b1b] doesn't provide @firebase/app (p9d158), requested by @firebase/performance
➤ YN0002: │ @firebase/remote-config-compat@npm:0.2.4 [02b1b] doesn't provide @firebase/app (p3e73e), requested by @firebase/remote-config
➤ YN0002: │ @firebase/storage-compat@npm:0.3.2 [02b1b] doesn't provide @firebase/app (p98e3d), requested by @firebase/storage
➤ YN0002: │ @firebase/storage-compat@npm:0.3.2 [02b1b] doesn't provide @firebase/app-types (pae6c2), requested by @firebase/storage-types
➤ YN0002: │ @storybook/instrumenter@npm:6.5.16 doesn't provide react (p00f73), requested by @storybook/addons
➤ YN0002: │ @storybook/instrumenter@npm:6.5.16 doesn't provide react-dom (p410d1), requested by @storybook/addons
➤ YN0002: │ @types/react-dnd@npm:3.0.2 doesn't provide react (pa40be), requested by react-dnd
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 294ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 436ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 556ms
➤ YN0000: Done with warnings in 1s 390ms
$ yarn build
Runtime Preset {
  enableIndexedDBProvider: true,
  enableBroadCastChannelProvider: true,
  prefetchWorkspace: true,
  exposeInternal: true,
  enableDebugPage: false,
  enableSubpage: false
}
NEXT_PUBLIC_FIREBASE_API_KEY not found, affine cloud feature will be disabled.
SENTRY_AUTH_TOKEN not found, Sentry monitoring feature will be disabled.
warn  - You have enabled experimental feature (swcPlugins) in next.config.mjs.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

API request proxy to [dev Server]: 100.84.105.99:11001
info  - Linting and checking validity of types...
info  - Creating an optimized production build...
warn  - Compiled with warnings

../../packages/workspace/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/git/AFFiNE/packages/workspace/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib'

Import trace for requested module:
../../packages/workspace/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js
../../packages/workspace/node_modules/.pnpm/@firebase+auth@0.21.5_@firebase+app@0.9.5/node_modules/@firebase/auth/dist/node-esm/index.js
../../packages/workspace/node_modules/.pnpm/firebase@9.18.0/node_modules/firebase/auth/dist/index.mjs
../../packages/workspace/src/affine/login.ts

info  - Collecting page data...
unhandledRejection TypeError: Cannot destructure property 'publicRuntimeConfig' of 'next_config__WEBPACK_IMPORTED_MODULE_0___default(...)(...)' as it is undefined.
    at 78556 (/git/AFFiNE/apps/web/.next/server/chunks/8556.js:143:30)
    at __webpack_require__ (/git/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at 26281 (/git/AFFiNE/apps/web/.next/server/pages/_document.js:156:69)
    at __webpack_require__ (/git/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at 72211 (/git/AFFiNE/apps/web/.next/server/pages/_document.js:29:28)
    at __webpack_require__ (/git/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at __webpack_exec__ (/git/AFFiNE/apps/web/.next/server/pages/_document.js:253:39)
    at /git/AFFiNE/apps/web/.next/server/pages/_document.js:254:80
    at __webpack_require__.X (/git/AFFiNE/apps/web/.next/server/webpack-runtime.js:219:21)
    at /git/AFFiNE/apps/web/.next/server/pages/_document.js:254:47 {
  type: 'TypeError'
}
Error: NEXT_PUBLIC_FIREBASE_API_KEY not found, affine cloud feature will be disabled.
warn  - You have enabled experimental feature (swcPlugins) in next.config.mjs.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

warn  - Compiled with warnings

../../packages/workspace/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/git/AFFiNE/packages/workspace/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib'

Import trace for requested module:
../../packages/workspace/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js
../../packages/workspace/node_modules/.pnpm/@firebase+auth@0.21.5_@firebase+app@0.9.5/node_modules/@firebase/auth/dist/node-esm/index.js
../../packages/workspace/node_modules/.pnpm/firebase@9.18.0/node_modules/firebase/auth/dist/index.mjs
../../packages/workspace/src/affine/login.ts

unhandledRejection TypeError: Cannot destructure property 'publicRuntimeConfig' of 'next_config__WEBPACK_IMPORTED_MODULE_0___default(...)(...)' as it is undefined.
    at 78556 (/git/AFFiNE/apps/web/.next/server/chunks/8556.js:143:30)
    at __webpack_require__ (/git/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at 26281 (/git/AFFiNE/apps/web/.next/server/pages/_document.js:156:69)
    at __webpack_require__ (/git/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at 72211 (/git/AFFiNE/apps/web/.next/server/pages/_document.js:29:28)
    at __webpack_require__ (/git/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at __webpack_exec__ (/git/AFFiNE/apps/web/.next/server/pages/_document.js:253:39)
    at /git/AFFiNE/apps/web/.next/server/pages/_document.js:254:80
    at __webpack_require__.X (/git/AFFiNE/apps/web/.next/server/webpack-runtime.js:219:21)
    at /git/AFFiNE/apps/web/.next/server/pages/_document.js:254:47 {
  type: 'TypeError'
}
    at file:///git/AFFiNE/apps/desktop/scripts/buildAffine.mjs:18:8
    exit code: 1
       Error beforeBuildCommand `yarn build:preload && yarn build:affine` failed with exit code 1
yarn build:app  47.15s user 2.56s system 160% cpu 31.046 total
```

**Comment by himself65** [comment]
can you manually run `yarn build` in `apps/web`?

**Comment by himself65** [comment]
This is weird because I didn't see the error on CI and my machine

**Comment by Bad3r** [comment]
I navigated to apps/web and ran the following commands:
```sh
$ yarn install
...
$ yarn build
❯ yarn build
Runtime Preset {
  enableIndexedDBProvider: true,
  enableBroadCastChannelProvider: true,
  prefetchWorkspace: true,
  exposeInternal: true,
  enableDebugPage: false,
  enableSubpage: false
}
NEXT_PUBLIC_FIREBASE_API_KEY not found, affine cloud feature will be disabled.
SENTRY_AUTH_TOKEN not found, Sentry monitoring feature will be disabled.
warn  - You have enabled experimental feature (swcPlugins) in next.config.mjs.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

API request proxy to [dev Server]: 100.84.105.99:11001
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
warn  - Compiled with warnings

../../packages/workspace/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/AFFiNE/packages/workspace/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib'

Import trace for requested module:
../../packages/workspace/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js
../../packages/workspace/node_modules/.pnpm/@firebase+auth@0.21.5_@firebase+app@0.9.5/node_modules/@firebase/auth/dist/node-esm/index.js
../../packages/workspace/node_modules/.pnpm/firebase@9.18.0/node_modules/firebase/auth/dist/index.mjs
../../packages/workspace/src/affine/login.ts

unhandledRejection TypeError: Cannot destructure property 'publicRuntimeConfig' of 'next_config__WEBPACK_IMPORTED_MODULE_0___default(...)(...)' as it is undefined.
    at 78556 (/AFFiNE/apps/web/.next/server/chunks/8556.js:143:30)
    at __webpack_require__ (/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at 26281 (/AFFiNE/apps/web/.next/server/pages/_document.js:156:69)
    at __webpack_require__ (/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at 72211 (/AFFiNE/apps/web/.next/server/pages/_document.js:29:28)
    at __webpack_require__ (/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at __webpack_exec__ (/AFFiNE/apps/web/.next/server/pages/_document.js:253:39)
    at /AFFiNE/apps/web/.next/server/pages/_document.js:254:80
    at __webpack_require__.X (/AFFiNE/apps/web/.next/server/webpack-runtime.js:219:21)
    at /AFFiNE/apps/web/.next/server/pages/_document.js:254:47 {
  type: 'TypeError'
}
```

It seems like it can't resolve the module `encoding`?.

**Comment by Bad3r** [comment]
I fixed the missing module issue by navigating to `AFFiNE/packages/workspace`
and:
```zsh
❯ rm -v -rf node_modules pnpm-lock.yaml
❯ yarn install
```

now running `yarn build` in `AFFiNE/apps/web` only outputs a type error:
```zsh
AFFiNE/apps/web  master*​ via  v18.15.0 
❯ yarn build                            
Runtime Preset {
  enableIndexedDBProvider: true,
  enableBroadCastChannelProvider: true,
  prefetchWorkspace: true,
  exposeInternal: true,
  enableDebugPage: false,
  enableSubpage: false
}
NEXT_PUBLIC_FIREBASE_API_KEY not found, affine cloud feature will be disabled.
SENTRY_AUTH_TOKEN not found, Sentry monitoring feature will be disabled.
warn  - You have enabled experimental feature (swcPlugins) in next.config.mjs.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

API request proxy to [dev Server]: 100.84.105.99:11001
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
unhandledRejection TypeError: Cannot destructure property 'publicRuntimeConfig' of 'next_config__WEBPACK_IMPORTED_MODULE_0___default(...)(...)' as it is undefined.
    at 78556 (/AFFiNE/apps/web/.next/server/chunks/8556.js:143:30)
    at __webpack_require__ (/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at 26281 (/AFFiNE/apps/web/.next/server/pages/_document.js:156:69)
    at __webpack_require__ (/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at 72211 (/AFFiNE/apps/web/.next/server/pages/_document.js:29:28)
    at __webpack_require__ (/AFFiNE/apps/web/.next/server/webpack-runtime.js:25:43)
    at __webpack_exec__ (/AFFiNE/apps/web/.next/server/pages/_document.js:253:39)
    at /AFFiNE/apps/web/.next/server/pages/_document.js:254:80
    at __webpack_require__.X (/AFFiNE/apps/web/.next/server/webpack-runtime.js:207:21)
    at /AFFiNE/apps/web/.next/server/pages/_document.js:254:47 {
  type: 'TypeError'
}
```

**Comment by himself65** [comment]
Try to delete `apps/web/.next`, `.yarn/cache` cache

We are using yarn 3 now. Are you using the codespace from the very old version? Or you can try to cleanup the whole directory and re-clone it.

**Comment by himself65** [comment]
Related: https://github.com/vercel/next.js/issues/15568

**Comment by himself65** [comment]
I will try to build the project in WSL later

**Comment by himself65** [comment]
This might be because `next/config` has some incorrect implementation. I will remove the usage of it in the next few days

**Comment by himself65** [comment]
You can download our desktop preview here.

https://github.com/toeverything/AFFiNE/actions/runs/4590286392

![image](https://user-images.githubusercontent.com/14026360/229373665-d18ecfeb-86d8-40ae-848b-77897e0be89d.png)

**Comment by Bad3r** [comment]
> You can download our desktop preview here.
> 
> https://github.com/toeverything/AFFiNE/actions/runs/4590286392
> 
> ![image](https://user-images.githubusercontent.com/14026360/229373665-d18ecfeb-86d8-40ae-848b-77897e0be89d.png)

seems to be windows and macOS only.

**Comment by Bad3r** [comment]
> Try to delete `apps/web/.next`, `.yarn/cache` cache
> 
> We are using yarn 3 now. Are you using the codespace from the very old version? Or you can try to cleanup the whole directory and re-clone it.

Good call; that fixed the issue. Now building seems to work fine except that there is an error in the appimage bundling script:
```sh
...
Bundling affine_0.1.0_amd64.AppImage (/AFFiNE/apps/desktop/src-tauri/target/release/bundle/appimage/affine_0.1.0_amd64.AppImage)
       Error failed to bundle project: error running appimage.sh: error running appimage.sh: `failed to run /AFFiNE/apps/desktop/src-tauri/target/release/bundle/appimage/build_appimage.sh`
```

**Comment by himself65** [comment]
> > Try to delete `apps/web/.next`, `.yarn/cache` cache
> > We are using yarn 3 now. Are you using the codespace from the very old version? Or you can try to cleanup the whole directory and re-clone it.
> 
> Good call; that fixed the issue. Now building seems to work fine except that there is an error in the appimage bundling script:
> 
> ```shell
> ...
> Bundling affine_0.1.0_amd64.AppImage (/AFFiNE/apps/desktop/src-tauri/target/release/bundle/appimage/affine_0.1.0_amd64.AppImage)
>        Error failed to bundle project: error running appimage.sh: error running appimage.sh: `failed to run /AFFiNE/apps/desktop/src-tauri/target/release/bundle/appimage/build_appimage.sh`
> ```

I think we have move the desktop project to https://github.com/toeverything/AFFiNE/tree/master/apps/electron

can you try that again?

**Comment by himself65** [comment]
I will handle the issue to @pengx17 since I'm not working on desktop part

**Comment by pengx17** [comment]
Hi @Bad3r . The tauri app in `apps/desktop` is not being maintained any longer. We feel that a small team like us would not be able to ship features fast enough on top of Tauri, so that we are now building with Electron instead.
The docs on building is not being updated accordingly right now. Here is the way to build the Electron app locally:

```
# under project roots
yarn
yarn build

# under /apps/electron
yarn
yarn before-make
yarn make
```

I am not sure if this will work on Linux yet though. Also, you can ignore `NEXT_PUBLIC_FIREBASE_API_KEY ` is missing error for now.

**Comment by himself65** [comment]
I will close this issue since it's look good

**Comment by Bad3r** [comment]
Hey, @pengx17 thank you for the explanation! I followed your instructions and I was able to successfully build AFFiNE.

**Comment by Bad3r** [comment]
unfortunately now there is a run time error :upside_down_face: 
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@affine/octobase-node-linux-x64-gnu'
Require stack:
- /AFFiNE/apps/electron/out/make/zip/linux/x64/AFFiNE-linux-x64/resources/app/dist/layers/main/index.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:1002:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109797)
    at Module._load (node:internal/modules/cjs/loader:848:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at ../../packages/octobase-node/index.js (/AFFiNE/apps/electron/out/make/zip/linux/x64/AFFiNE-linux-x64/resources/app/dist/layers/main/index.js:218:35)
    at __require (/AFFiNE/apps/electron/out/make/zip/linux/x64/AFFiNE-linux-x64/resources/app/dist/layers/main/index.js:9:50)
    at Object.<anonymous> (/AFFiNE/apps/electron/out/make/zip/linux/x64/AFFiNE-linux-x64/resources/app/dist/layers/main/index.js:3058:36)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)

```

**Comment by pengx17** [comment]
Oh okay! Sorry I missed the step to build the octobase-node package. You can run `yarn build:octobase-node` in `apps/electron` to fix this issue

**Comment by himself65** [comment]
Please update the document by the way

**Comment by Bad3r** [comment]
> Oh okay! Sorry I missed the step to build the octobase-node package. You can run `yarn build:octobase-node` in `apps/electron` to fix this issue. BTW you need rust toolchains to run it.

I re-cloned the repo and followed the steps in order:
```sh
# under project roots
yarn
yarn build

# under /apps/electron
yarn
yarn before-make
yarn build:octobase-node
yarn make
```

Running AFFiNE still returns the same runtime error :/

```sh
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@affine/octobase-node-linux-x64-gnu'
Require stack:
- /AFFiNE/apps/electron/out/AFFiNE-linux-x64/resources/app/dist/layers/main/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1002:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109797)
    at Module._load (node:internal/modules/cjs/loader:848:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at ../../packages/octobase-node/index.js (/AFFiNE/apps/electron/out/AFFiNE-linux-x64/resources/app/dist/layers/main/index.js:218:35)
    at __require (/AFFiNE/apps/electron/out/AFFiNE-linux-x64/resources/app/dist/layers/main/index.js:9:50)
    at Object.<anonymous> (/AFFiNE/apps/electron/out/AFFiNE-linux-x64/resources/app/dist/layers/main/index.js:3058:36)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
```

**Comment by pengx17** [comment]
Can you check:
- run `yarn why @affine/octobase-node` under `/apps/electron` and see what is the result
- check if there is `packages/octobase-node/octobase-node-linux-x64-gnu.node` in the repo

**Comment by Bad3r** [comment]
```sh
AFFiNE/apps/electron  master*​ via  v18.15.0 
❯ yarn why @affine/octobase-node
└─ @affine/electron@workspace:.
   └─ @affine/octobase-node@workspace:../../packages/octobase-node (via workspace:*)
```

```sh
❯ ll packages/octobase-node/octobase.linux-x64-gnu.node 
Permissions Size User  Group Date Modified Git Name
.rwxr-xr-x   29M user users  3 Apr 22:26   -I  packages/octobase-node/octobase.linux-x64-gnu.node*

```

seems like both are fine

**Comment by pengx17** [comment]
@Bad3r thanks for the additional info. I think you may also need to run `cp ./packages/octobase-node/octobase.*.node ./apps/electron/dist/layers/main/` in repo root and then run `yarn make`. I will update the build script & doc to clear it up.

**Comment by pengx17** [comment]
Docs will be updated in https://github.com/toeverything/AFFiNE/pull/1813

**Comment by Bad3r** [comment]
@pengx17 thank you. Should I run `yarn make` in the repo root or in `apps/electron`?

**Comment by pengx17** [comment]
If you are using the latest code, you can try make the build according to https://github.com/toeverything/AFFiNE/blob/master/docs/building-desktop-client-app.md#build.

**Comment by Bad3r** [comment]
@pengx17 the instructions do not mention running `yarn install` under `apps/electron` is it not needed?  
  
to build the binary I followed the steps:  
\`\`\`  
\# Under project roots  
yarn install  
 

\# under /apps/electron  
yarn install  
yarn generate-assets  
yarn make  
\`\`\`  
  
This allowed me to build and run AFFiNE! 🎉  
  
While AFFiNE is running the error:  
\`\`\`sh  
Error occurred in handler for 'ui:sidebar-visibility-change': TypeError: w.setWindowButtonVisibility is not a function

at /AFFiNE/apps/electron/out/make/zip/linux/x64/AFFiNE-linux-x64/resources/app/dist/layers/main/index.js:3068:9

at Array.forEach (\<anonymous>)

at /AFFiNE/apps/electron/out/make/zip/linux/x64/AFFiNE-linux-x64/resources/app/dist/layers/main/index.js:3067:13

at node:electron/js2c/browser\_init:2:97909

at EventEmitter.\<anonymous> (node:electron/js2c/browser\_init:2:81422)

at EventEmitter.emit (node:events:513:28)  
\`\`\`  
  
is spammed repeatedly in the terminal. Any idea what is causing the issue?

**Comment by pengx17** [comment]
Thanks! This is because `setWindowButtonVisibility` is only available to MacOS. I will move this function call in a condition check.
The ticket should be safe to be closed. Besides PR is welcome :D.

**Comment by mirtaqi07** [comment]
@Bad3r Hi, I've been following your steps. But at yarn generate-assets`, it gives this error. Kindly help me, I've been trying for days to build desktop version, but still no success.

PS F:\AFFiNE\packages\frontend\electron> yarn generate-assets
(node:14816) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm/transpile-only", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
build with following variables {
  repoRootDir: 'F:\\AFFiNE',
  electronRootDir: 'F:\\AFFiNE\\packages\\frontend\\electron',
  publicDistDir: 'F:\\AFFiNE\\packages\\frontend\\electron\\resources',
  affineSrcDir: 'F:\\AFFiNE\\packages\\frontend\\electron\\renderer',
  affineSrcOutDir: 'F:\\AFFiNE\\packages\\frontend\\electron\\renderer\\dist',
  publicAffineOutDir: 'F:\\AFFiNE\\packages\\frontend\\electron\\resources\\web-static',
  releaseVersionEnv: ''
}
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

[Error: ENOENT: no such file or directory, lstat 'F:\AFFiNE\packages\frontend\electron\renderer\dist'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'F:\\AFFiNE\\packages\\frontend\\electron\\renderer\\dist'
}

Node.js v20.10.0
PS F:\AFFiNE\packages\frontend\electron>


### Update

`dist directory` was created in `packages\frontend\electron` when I did `yarn run dev:electron`, but still got the same error on running `yarn generate-assets`. So I manually replaced the `dist directory` into `packages\frontend\electron\renderer`, then `yarn generate-assets` works.

After that, `yarn make` was also success. But on opening `AFFiNE-canary.exe` , the app doesnt open. It gives following error.

![image](https://github.com/toeverything/AFFiNE/assets/88597955/b0461727-8450-4b08-a5c9-188945e920be)
