### ISSUE TITLE
download public workspace API changes

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#1789]
### What happened?

https://github.com/toeverything/AFFiNE/actions/runs/4594493330/jobs/8113636470

### Version

stage.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by darkskygit** [comment]
now the public workspace/page apis normalized to `/api/public/workspace/{workspaceId}[/{spaceId}]`
