### ISSUE TITLE
Toast messages are not working on the latest sources

### ISSUE THREAD

**Issue by adityash1** [toeverything/AFFiNE#1824]
### What happened?

On app.affine.pro it shows toast like Edgeless mode and Page mode when switching. but not in the latest sources

https://user-images.githubusercontent.com/65771169/230062718-0f8255a3-2a25-45fa-9122-41b463b762a2.mp4

https://user-images.githubusercontent.com/65771169/230063570-6015fbf3-f8d3-40d1-b651-122c522e60f4.mp4

### Version

stage.affine.pro

### What browsers are you seeing the problem on?

Microsoft Edge

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
I didn't see the issue on http://affine-preview.vercel.app/

**Comment by doodlewind** [comment]
I guess if is the latest non-toast effect matches our expectation? @joebeijing

**Comment by joebeijing** [comment]
Currently, toast messages are required while switching between Page and Edgeless Mode. @doodlewind

**Comment by himself65** [comment]
I didn't see the issue on Edge, Chrome, Safari
