### ISSUE TITLE
[improvement]: Add arm64 Support to the Docker Images

### ISSUE THREAD

**Issue by DrMxrcy** [toeverything/AFFiNE#185]
### 1~3 main use cases of the proposed improvement

- Add a ARM64 Image to the Docker Build, so people with devices like RaspberryPis can run this at home

### Ideas for solution

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
https://docs.docker.com/desktop/extensions-sdk/extensions/multi-arch/

### what types of users can benefit from using your proposed improvement

Home Hosters

**Comment by darkskygit** [comment]
the latest image includes arm64 support now, please re-pull
