### ISSUE TITLE
Could not export as markdown​

### ISSUE THREAD

**Issue by lzlme** [toeverything/AFFiNE#1861]
### What happened?

https://user-images.githubusercontent.com/117659326/230933608-60cbefa1-37ba-476f-b473-9bd1e293f85d.mov

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Could you please try stage.affine.pro?

**Comment by doodlewind** [comment]
Reproduced on stage and I think this is a regression since exporting in BlockSuite playground works, should be low hanging fruit to fix 👀
