### ISSUE TITLE
New toast design​

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#1870]
### Description

<img width="784" alt="shot-2023-04-11-13 51 55@2x" src="https://user-images.githubusercontent.com/24713927/231068393-c87fb3cd-4750-409e-a6c0-102e98567aa1.png">

Requirements for Toast component:

- Supports three color modes/styles   

- Optional action button (undo)

- Optional countdown timer for auto-dismissal

- Optional close button: show or hidden 

- Optional icon support: show or hidden \  support different icons

- Supports stacking of multiple messages, with display of 1, 2, 3, or more messages when hovered over

    - Supports basic expansion animation.
    
![shot-2023-04-11-13 15 14](https://user-images.githubusercontent.com/24713927/231067408-ade715f7-a49b-4aa5-b4db-32532c695d5c.gif)

---

🖌️ [ figma link ](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/Design-System?node-id=274%3A955&t=TsBiHTGMRk3fkxEK-1)

🎬 [ basic animation](https://www.figma.com/proto/UTTtfVCcStw1dKUg0gCSPo/Design-System?page-id=274%3A955&node-id=662-5780&viewport=525%2C577%2C0.16&scaling=min-zoom&starting-point-node-id=662%3A5780&show-proto-sidebar=1) 

ps. The animation accuracy is not high, and the animation concept can be used as a reference for implementation. Further adjustments will be made later.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kob11angel** [comment]
Supports three color modes/styles

**Comment by himself65** [comment]
We will implement this stable version in v0.6.
