### ISSUE TITLE
Improve UX of dropdown - it disappears too quickly​

### ISSUE THREAD

**Issue by AlessioGr** [toeverything/AFFiNE#1898]
### Description

https://user-images.githubusercontent.com/70709113/231476896-6dbf917b-02d0-4723-9359-8a8bf53afafa.mp4

Check out the video. The dropdown disappears too quickly when trying to reach the dropdown options with the mouse.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Like a bug

**Comment by gyuannn** [comment]
I tried to solve it, but it may not be the best solution. Can I submit a PR for this?

**Comment by himself65** [comment]
> I tried to solve it, but it may not be the best solution. Can I submit a PR for this?

Of course

**Comment by QiShaoXuan** [comment]
Sorry I didn't see this pr was already merged, after mouse leave the trigger button, the operation menu expected be closed, but not click the other area again
