### ISSUE TITLE
This Suspense boundary received an update before it finished hydrating.

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#1906]
https://toeverything.sentry.io/issues/4082176988/?project=4504917599125504&query=is%3Aunresolved&referrer=issue-stream&stream_index=1

![image](https://user-images.githubusercontent.com/14026360/231588287-3b2fd6e0-3827-423d-acc6-55c09a83f9e6.png)

**Comment by himself65** [comment]
I think the issue is two times navigation?

**Comment by himself65** [comment]
Bug source: https://github.com/toeverything/AFFiNE/pull/1901
