### ISSUE TITLE
Support editing single markdown file

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#1923]
This feature will allow users to open and edit a single markdown file from the file system. Related points:

- Users should be able to open a local markdown file, similar to opening a text file in Notepad or using VSCode's restricted mode.
- The editor should be under single window without sidebar, neither will this file be added into existing workspace by default.
- Users should be able to save their edits as markdown and update the original file.

To be confirmed:

If the edited content exceeds the capabilities of markdown, there are several options:
- Save the file as our custom format extension (front matter extension, JSX or other meta files in the same directory). This may require all blocks to be serializable (without losing props) into a markdown superset, and also should be loadable when opened again.
- Not to save the file into markdown anymore. Instead, save it into one current workspace (or create a new one). This may require a hint to user that current content exceeds the markdown capability.
- Let the user to choose whether to save a limited markdown file or an AFFiNE page (in the workspace).

This may require:

- OS-specific file extension registration support
- Persistence support from OctoBase side
- A new app lifecycle for opening file-based page (content not coming from IndexedDB or WebSocket)
- Capability to detect whether current page exceeds the markdown features
- Better markdown exporting and importing support from BlockSuite

Further technical design for implementing this will be prepared. The corresponding issue link will be attached here.

/cc @pengx17 @Himself65 @Brooooooklyn @joebeijing

**Comment by himself65** [comment]
import from multiple places should be supported first

**Comment by lqhuang** [comment]
Not only the ability to edit local markdown files, but also could AFFiNE support a pure markdown mode or fast markdown render (without block mode)?

**Comment by doodlewind** [comment]
> Not only the ability to edit local markdown files, but also could AFFiNE support a pure markdown mode or fast markdown render (without block mode)?

A pure markdown mode should be a non-goal. But it's possible to build a markdown editor UI based on the block tree (https://blocksuite.affine.pro/framework-integration.html), though.

**Comment by jackdiy** [comment]
Actually, the function of importing MD files as new pages is very important, as it facilitates users to completely migrate documents from various Notion-like cloud note-taking products.
For instance, I previously used a product, and now I have exported about 10GB of MD documents from cloud to my local device.
When considering migration work, each MD file is associated with a large number of images, videos, and tables.

**Comment by jackdiy** [comment]
Thank you to the development team for their continuous efforts.
I experienced the function of importing MD files in the new version, but it seems to have some compatibility issues with this format. For example, many image files that were displayed correctly in Typora are shown in the following form in the latest version of AFFiNE, indicating that the attachments are not being read from the "assets" directory. This seems to affect almost all attachment formats. I hope this can be addressed in future updates to ensure compatibility.
![111](https://github.com/toeverything/AFFiNE/assets/23490822/f956aa2b-c7db-42d7-a788-5b59cce0f469)

**Comment by doodlewind** [comment]
> Thank you to the development team for their continuous efforts.
> 
> I experienced the function of importing MD files in the new version, but it seems to have some compatibility issues with this format.
> 
> For example, many image files that were displayed correctly in Typora are shown in the following form in the latest version of AFFiNE, indicating that the attachments are not being read from the "assets" directory.
> 
> This seems to affect almost all attachment formats. I hope this can be addressed in future updates to ensure compatibility.
> 
> ![111](https://github.com/toeverything/AFFiNE/assets/23490822/f956aa2b-c7db-42d7-a788-5b59cce0f469)
> 
> 

Thanks for the feedback! We have plan in https://github.com/toeverything/blocksuite/issues/3654 to support archive format with attachment bundled, the attachment in markdown and other formats is planned afterwards.
