### ISSUE TITLE
macOS Emacs-like​ keybindings overridden by shortcuts

### ISSUE THREAD

**Issue by jpaquim** [toeverything/AFFiNE#1924]
### What happened?

In macOS we can use Emacs/Readline-like shortcuts such as Ctrl+A, Ctrl+E, Ctrl+P, Ctrl+N, Ctrl+F, Ctr+B, etc., in any text field by default (I'm using them to edit this right now). It seems like most of these are being overridden by Affine at the application level, where both Ctrl and Cmd seem to work. My suggestion would be to have the application shortcuts using only the Cmd key, leaving the Ctrl key free for the default text navigation/editing keys.

I'm willing to dig through the issue and submit a PR, at first glance it seems related to using `event.metaKey || event.ctrlKey` in this switch statement's cases: https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/database-block/components/column-type/rich-text.ts#L132

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Chrome, Firefox, Other

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lawvs** [comment]
Fixed in https://github.com/toeverything/blocksuite/pull/2045
