### ISSUE TITLE
Websocket keeps reconnecting

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#1929]
![image](https://user-images.githubusercontent.com/584378/231820541-a80765d8-e829-400b-a0e7-e680d7e35201.png)

**Comment by pengx17** [comment]
This issue is caused that we are using production API at app.affine.pro. The token for connecting websocket has changed and shall be fixed next week when the new octobase api is released.

**Comment by himself65** [comment]
The reason is that Ocotbase API changes but has not landed in production yet.
