### ISSUE TITLE
Window Desktop cannot start​

### ISSUE THREAD

**Issue by Lohartte** [toeverything/AFFiNE#1939]
### What happened?

APP版本：桌面版0.5.2，win64
系统版本：win11 22H2
出现问题：无法正常启动
ps. bug反馈中是否可以新增pc端的的选择？

![1681440971282](https://user-images.githubusercontent.com/91640363/231929972-d557fb2d-15ea-494b-8adb-5378893c0e79.jpg)

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Other

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
> ps. bug反馈中是否可以新增pc端的的选择？

Landed in https://github.com/toeverything/AFFiNE/commit/d58f9db2895fc814201f8d2db3bf714ab5216995

> 无法正常启动

I also see the issue on my Windows; this is a conformed-issue /cc @m1911star

**Comment by skgiter** [comment]
![image](https://user-images.githubusercontent.com/19297199/232028161-cc1a2739-75b6-47b8-8f2b-2e0175c6d7e6.png)
同样的情况，且点击页面会穿透到后面的窗口

**Comment by himself65** [comment]
We are releasing v0.5.3 with this fixed

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/releases/tag/v0.5.3

**Comment by sven-eliasen** [comment]
Thanks for the fix !
