### ISSUE TITLE
flaly e2e test

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#1952]

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/actions/runs/4703304889/jobs/8341670864?pr=1953

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/actions/runs/4703304889/jobs/8341671326

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/pull/1951

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/pull/1955
