### ISSUE TITLE
​Create "Table View" lead to error in browser

### ISSUE THREAD

**Issue by Ding-Fan** [toeverything/AFFiNE#1958]
### What happened?

- Create a new page.
- Type "/" to open the menu and select "Table View."
- The table does not appear, and errors are displayed in the console.

<img width="334" alt="image" src="https://user-images.githubusercontent.com/26438549/232201158-54420ee6-1778-4538-89db-c11a733d0dc3.png">
 

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Other

### Relevant log output

```shell
pp-9f09f51c92cdc816.js:392 Uncaught (in promise) Error: database is not enabled
    at eM.addBlock (_app-9f09f51c92cdc816.js:392:11273)
    at n.value (_app-9f09f51c92cdc816.js:392:217)
    at action (233.bad21aa9cacfd2b2.js:2838:1949)
    at oB._handleClickItem (233.bad21aa9cacfd2b2.js:2947:3592)
    at oB.<anonymous> (233.bad21aa9cacfd2b2.js:2968:30)
    at L.handleEvent (_app-9f09f51c92cdc816.js:1697:37953)
addBlock @ _app-9f09f51c92cdc816.js:392
n.value @ _app-9f09f51c92cdc816.js:392
action @ 233.bad21aa9cacfd2b2.js:2838
_handleClickItem @ 233.bad21aa9cacfd2b2.js:2947
(anonymous) @ 233.bad21aa9cacfd2b2.js:2968
handleEvent @ _app-9f09f51c92cdc816.js:1697
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Himself65** [comment]
We forgot to enable this feature in runtime

**Comment by himself65** [comment]
App.affine.pro doesn’t have such feature enabled for now. 

We will enable database view in next stable release 

you can try stage.affine.pro to try the feature for now
