### ISSUE TITLE
​Sign in and Enable button not working

### ISSUE THREAD

**Issue by Ding-Fan** [toeverything/AFFiNE#1992]
### What happened?

Version: 0.5.3

Steps to reproduce:

- Click the desktop icon at the top right corner.
- In `EnableAffineCloudModal` , click the "Sign in and Enable" button.
- Expected behavior: The sign-in process should start.
- Actual behavior: Nothing happens, and an error occurs in the console.

The issue may be related to the [onTransferWorkspace](https://github.com/toeverything/AFFiNE/blob/54a30bbf20a8e07da754a5b956e6c24cd2a5e2d7/apps/web/src/components/affine/workspace-setting-detail/panel/publish/index.tsx#L139) function

### Version

Windows x64

### What browsers are you seeing the problem on?

Other

### Relevant log output

```shell
login.ts:170 Uncaught (in promise) Error: Failed to initialize firebase
    at Object.generateToken (login.ts:170:15)
    at onConform (SyncUser.tsx:119:38)
    at onClick (index.tsx:47:17)
    at Object.eU (react-dom.production.min.js:54:315)
    at eH (react-dom.production.min.js:54:468)
    at react-dom.production.min.js:55:32
    at re (react-dom.production.min.js:55:119)
    at rn (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at oP (react-dom.production.min.js:274:35)
```

### Anything else?

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/26438549/232527962-6e2c7a29-540d-4fde-bba5-7123a8a9bda7.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Thanks fro the report. The connection between the desktop app and cloud API is **unstable**. You can try local feature for now
