### ISSUE TITLE
New default avatar​ components

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#1999]
### Description

Default avatar with gradient effect, showing a simple animation on hover.

![image](https://user-images.githubusercontent.com/24713927/232664885-0f2357d3-b3cf-4156-8cfa-ff0465e7a3f1.png)

[ 🖌️ figma link ](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/Design-System?node-id=488%3A5388&t=cMB2pRjhctrgx08P-1)
[ 🎬 figma preview link](https://www.figma.com/proto/UTTtfVCcStw1dKUg0gCSPo/Design-System?page-id=488%3A5388&node-id=910-6763&viewport=-863%2C882%2C1.89&scaling=min-zoom&starting-point-node-id=910%3A6763)

### File Attachment

[svg_shape.zip](https://github.com/toeverything/AFFiNE/files/11257640/svg_shape.zip)

### colors
``` json
{
 "avatarBlueOne" : "#35B7E0",
 "avatarBlueTwo" : "#5076FF",
 "avatarBlueThree" : "#77FFCE",
}

```

### Animation

<p>Mid</p>

keyframe | shape | rotation | x postion | y postion
-- | -- | -- | -- | --
0 | Mid | 118.87° | 11.82 | 92.54
1 | Mid | 148.87° | 34.03 | 80.44
2 | Mid | 178.87° | 70.88 | 72.51
3 | Mid | -151.13° | 95.17 | 62.51

<p>Low</p>

keyframe | shape | rotation | x postion | y postion
-- | -- | -- | -- | --
0 | Low | 106.75° | 17.31 | 84.68
1 | Low | 136.75° | 53.74 | 91.77
2 | Low | 166.75° | 88.84 | 79.71
3 | Low | -163.25° | 113.2 | 51.71

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Does the animation always run in the whole page lifecycle?

**Comment by hwangdev97** [comment]
Just show the animation when hovering, I think @QiShaoXuan  has been working on this issue.

**Comment by himself65** [comment]
@QiShaoXuan please rewrite the code in https://github.com/toeverything/AFFiNE/blob/master/packages/component/src/components/workspace-avatar/index.tsx, don't create a new one
