### ISSUE TITLE
The first-level item in the sidebar should not have a drag-and-drop event.​

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#2003]
### What happened?

Please handle the drag-and-drop event, and the items such as workspace settings, all pages, and trash should not have the drag-and-drop event.

https://user-images.githubusercontent.com/24713927/232681114-c401476d-44b2-4ad8-bd93-199ea9a99b97.mp4

### Version

macOS ARM 64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/commit/94063352f5f4ef105ccaed790fde06005bea5c37
