### ISSUE TITLE
AFFiNE Client - Copy & Paste Issues

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2012]
When pasting content outside of the AFFiNE Client there is duplicated data. 

Appears to be one copy of the text, one copy of the schema.

![CopyBug](https://user-images.githubusercontent.com/4605025/232714854-cc32284a-2341-4868-8027-da39cd105c36.gif)

**Comment by QiShaoXuan** [comment]
Fixed in https://github.com/toeverything/blocksuite/pull/2276
