### ISSUE TITLE
[9ffe451] electron app on macos arm64 @ v0.5.4-canary.2​

### ISSUE THREAD

**Issue by ZoneTwelve** [toeverything/AFFiNE#2020]
### What happened?

After I click the Enable AFFiNE Cloud, then everything becomes weird.
The title can not be edited normally, every letter will be put on the front.
Note: 
- like RLE writing. (right to left) 

Input: Hello world
Output: dlrow olleH

<img width="1112" alt="Local build electron app" src="https://user-images.githubusercontent.com/20425883/232884847-5ec4a7da-7052-4ef2-b615-bc820f6fd1ba.png">

### Version

macOS ARM 64 (self-build app)

### What browsers are you seeing the problem on?

Other

### Relevant log output

```shell=
t-html.js:6 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at Z.k (lit-html.js:6:4557)
    at Z.$ (lit-html.js:6:4616)
    at Z.g (lit-html.js:6:5021)
    at Z._$AI (lit-html.js:6:4350)
    at Z.T (lit-html.js:6:5205)
    at Z._$AI (lit-html.js:6:4350)
    at D.v (lit-html.js:6:3723)
    at Z.g (lit-html.js:6:4903)
    at Z._$AI (lit-html.js:6:4350)
    at H (lit-html.js:6:7837)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
Thank you for your feedback. Will this bug still appear in the latest version?

**Comment by ZoneTwelve** [comment]
Hi, thank you for letting me know the newest info about AFFiNE Desktop App, after the AFFiNE has been closed, this issue can not be recurring anymore.
The issue can be closed now, if that is still possible to be the issue, I will reopen this issue or open a new one.

Close or keep it open is up to you.
Note: because it's the AFFiNE Cloud problem.

**Comment by himself65** [comment]
This should be fixed in our next cloud version.
Please pay attention on the next 2 weeks update
