### ISSUE TITLE
[improvement]: Slow build speed

### ISSUE THREAD

**Issue by Proful** [toeverything/AFFiNE#203]
### 1~3 main use cases of the proposed improvement

Build is very slow.

### Ideas for solution

Instead of using webpack-dev-middleware better to explore esbuild, swc or turbo.

**Comment by tzhangchi** [comment]
We are considering using swc to improve build speed, but we need community help, would you like to contribute some relevant pr @Proful

**Comment by alt1o** [comment]
Maybe you can follow this pr #239
