### ISSUE TITLE
Add Onboarding carousel

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2039]
（1）Hyper merged whiteboard and docs
Description：Easily switch between Page mode for structured document creation and Whiteboard mode for freeform visual expression of creative ideas.

（2）Intuitive & robust block-based editing
Description：Create structured documents with ease, using a modular interface to drag and drop blocks of text, images, and other content.

**Comment by xell** [comment]
Add slide left/right effects to the carousel, taking the three components, i.e. the heading/title, the image/video, and the description, as a whole to slide by a same speed.
