### ISSUE TITLE
Dialog component asjusetment​

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#2043]
### Description

https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/Design-System?node-id=832-6645
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/110808979/233263324-cee6c4c3-eea8-4a36-8b07-9896b675b106.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
The part of the product that was causing this issue has been removed or significantly reworked since it was created.
