### ISSUE TITLE
‘Cannot read properties of undefined (reading 'onExportMarkdown')’ when I clicked Export

### ISSUE THREAD

**Issue by DiamondThree** [toeverything/AFFiNE#2050]
### What happened?

<img width="590" alt="image" src="https://user-images.githubusercontent.com/24630517/233358759-ff02fac1-f048-48e4-b2e0-544e2e4291cb.png">
Cannot read properties of undefined (reading 'onExportMarkdown')

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by tzhangchi** [comment]
@zuoxiaodong0815

**Comment by himself65** [comment]
Duplicated https://github.com/toeverything/AFFiNE/issues/1588
