### ISSUE TITLE
​support folder structure (not just page)

### ISSUE THREAD

**Issue by avelino** [toeverything/AFFiNE#2051]
### Description

give the option to create folders, making it possible to segment the knowledge base

### Use case

my company has 300 employees and N business area, I would create a "folder" for each business area:

* customer success
* operation
* engineering
* data

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LIHAQI** [comment]
确实，有文件夹功能会更方便

**Comment by joebeijing** [comment]
Thank you very much for your feedback. Currently, we do not have this plan, but we will carefully consider it.

**Comment by himself65** [comment]
We already have collections in the latest Canary version.

Closing via https://github.com/toeverything/AFFiNE/pull/2988
