### ISSUE TITLE
Copylink in Pinboard is completely broken.

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#2072]
The copy link is always currently opened page href

![f411440e-ef3e-4aeb-973f-89b1f1c7a9e4](https://user-images.githubusercontent.com/5910926/233754531-5a16f232-9011-4774-b909-4e6923a034f5.jpeg)
<img width="900" alt="image" src="https://user-images.githubusercontent.com/5910926/233754549-4be2d6cc-c280-418c-9243-b327745764c3.png">

**Comment by himself65** [comment]
This is whether it should be disabled because in the electron app, there's no HTTP link. I think we should support `jump to app` link first then it will be fixed

**Comment by himself65** [comment]
@pengx17

**Comment by pengx17** [comment]
I think this issue is more related to handling link copy/paste. I will reassign it to @pengx17

**Comment by tzhangchi** [comment]
The function was not included in the latest sprint due to the pinboard redesign.
