### ISSUE TITLE
[feature]: How to configure docker to map data outside of docker

### ISSUE THREAD

**Issue by WangShuXian6** [toeverything/AFFiNE#209]
### 1~3 main use cases of the proposed feature

Storing data outside of docker

### Ideas for solution

Storing data outside of docker,use docker compose config file

### what types of users can benefit from using your proposed feature

Team, Private Deployment

**Comment by HeJiachen-PM** [comment]
Hello, we will have file system support in the coming releases as the current version is meant for demo uses. Please keep an eye on us.
