### ISSUE TITLE
Add preset pages for Pinboard

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2091]
Here are some key points: 
1. Help users quickly understand what Pinboard is. 
2. Explain the difference between Pinboard and Favorites. 
3. Describe how to use Pinboard. 
4. Clarify the differences between Pinboard and common Page Trees. 
5. Include at least 2-3 documents that demonstrate the Page Tree effect of Pinboard. 
6. Each document does not have to be too detailed, focusing on quickly introducing the value of Pinboard and answering potential questions. 
7. Any other possible problems is welcomed to be added to the common FAQ.

**Comment by Yipei-Operation** [comment]
I think we will change the name for pinboard, right? CC @joebeijing will this kind of job has been changed?
