### ISSUE TITLE
The button border of the confirmation pop-up for deleting a page is not visible

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2095]
![CleanShot 2023-04-23 at 8 51 14@2x](https://user-images.githubusercontent.com/22443345/233840875-03bc292b-8eaf-4bbf-917d-7a159221fa70.png)

**Comment by JimmFly** [comment]
<img width="775" alt="image" src="https://github.com/toeverything/AFFiNE/assets/102217452/89cabfa4-d755-400e-9be2-f1b6fa365cbd">
Fixed in latest version.
