### ISSUE TITLE
Client version: Design system mistakes in terms of icon clolor/ menu color/ shadow/ border color/ grid color

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#2099]
1. all menu background is missing.   **color name: light/background/ **
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/110808979/233890292-b891eb46-15d0-4a4b-8e40-cec1c47cb681.png">

2. palette colors are all missing
<img width="676" alt="image" src="https://user-images.githubusercontent.com/110808979/233892638-456ffb53-17dd-4bd0-88c5-4fb295cee4b1.png">

3， some icon colors are incorrect.  color name: light/detailColor/iconColor
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/110808979/233892765-01d19097-ff92-477b-990e-17d66dffd8e7.png">

4. menu shadows are incorrect, **shadow name: box-shadow: 0px 0px 12px 0px hsla(248, 6%, 27%, 0.14);

box-shadow: 0px 0px 0px 0.5px hsla(240, 2%, 89%, 1) inset;**
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/110808979/233893418-47e1743d-76b8-44cf-ad0e-b471cde7dc93.png">

**Comment by JimmFly** [comment]
close with https://github.com/toeverything/blocksuite/pull/2446
