### ISSUE TITLE
Banner for Online Demo ​

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#2103]
### Description

 design here: https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?node-id=1874-43699&t=weQrrr9iTTWnTdtL-4
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/110808979/233900732-06c7c8b6-83d9-4884-9350-7d9d7736984e.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Please implemnet this in storybook!
@JimmFly
