### ISSUE TITLE
Write api types manualy in `package/env`

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#2104]
After discussion, I think we should manually declare the APIs in `@packages/env` instead of auto-generated types.

https://github.com/toeverything/AFFiNE/blob/master/apps/electron/layers/preload/preload.d.ts should be removed in the future

**Comment by pengx17** [comment]
It appears the solution is pretty simple. We do not need a 3rd party library at all - just export the types of apis in preload.d.ts, then our work is done, magic!
