### ISSUE TITLE
Left sidebar menu item click area is smaller than visual

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#2116]
![Image](https://user-images.githubusercontent.com/584378/234167813-357f4c6f-ca56-4b4c-859a-b0be956d96e8.png)

**Comment by himself65** [comment]
I believe we need to rewrite this component and move to storybook to make it easy to debug

**Comment by xell** [comment]
No need for this because of new sidebar is being designed.

**Comment by pengx17** [comment]
Seems still an issue after refactor
