### ISSUE TITLE
throw Errow “val does not exist”  when I drag block to the editor,

### ISSUE THREAD

**Issue by rottenpen** [toeverything/AFFiNE#2125]
### What happened?

I don't know if this bug or feature
> be like ⬇️：

https://user-images.githubusercontent.com/12029924/234237389-692a9cd2-71cc-4225-8e1c-9921da447f1d.mp4

### Version

macOS ARM 64

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by rottenpen** [comment]
@doodlewind I don't know if this is a bug or a feature. If this is a bug I'd be happy to help out

**Comment by thorseraq** [comment]
I think it's a bug, the error message indicates that `getEdgelessPage()` is called in default page mode

**Comment by rottenpen** [comment]
> I think it's a bug, the error message indicates that `getEdgelessPage()` is called in default page mode. Thanks for pointing out! PR is welcomed for sure 😄

I have fixed it. Now, when the block is dragged to a blank area, it will be added to the end without any errors. Although my code runs without errors, I don't believe it follows best practices. I would appreciate any suggestions you may have for improvement.
