### ISSUE TITLE
[improvement]: support the table

### ISSUE THREAD

**Issue by ZermZhang** [toeverything/AFFiNE#213]
### 1~3 main use cases of the proposed improvement

hope to support the table in affine

**Comment by tzhangchi** [comment]
> ### 1~3 main use cases of the proposed improvement
> hope to support the table in affine
> 
> ### Ideas for solution
> _No response_
> 
> ### what types of users can benefit from using your proposed improvement
> _No response_
> 
> ### Additional context
> _No response_

Thank you for your suggestions. We are planning more views, and we will provide a different table view

**Comment by HeJiachen-PM** [comment]
A table view for groups is planned but a table as a block element is not something we are doing right now
