### ISSUE TITLE
​Text Justified

### ISSUE THREAD

**Issue by TachonFoucaut** [toeverything/AFFiNE#2132]
### Description

After discussion with friends that are using Notion. They are really annoyed that Notion can not set the text as justified for reading notes and text.

I guess that enabling text Justify option would be an asset for AFFiNE.

### Use case

Everyone who wants to read long notes and text

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
@joebeijing

**Comment by joebeijing** [comment]
Hello, thank you for your feedback. This is a feature that we plan to offer in the future - the ability to customize page display settings. However, it is not currently on our short-term roadmap as we are focusing resources on developing core features. We will add it to our backlog.
