### ISSUE TITLE
Favourites icon will adjust position

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2138]
Favourites icon should be stationary position and not to adjust placement based on title length.

![favourites](https://user-images.githubusercontent.com/4605025/234455804-054b584c-f3d1-48ca-afa2-ebe4861e5dc8.gif)

**Comment by hwangdev97** [comment]
I think we have fixed this issue. cc @xell 

![shot-2023-05-24-12 58 33](https://github.com/toeverything/AFFiNE/assets/24713927/589bca2c-244d-4ca9-b038-ecbdaf95eb77)

**Comment by xell** [comment]
Related to #2379 and fixed by #2453 .
