### ISSUE TITLE
Standardised language

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2139]
All language should be standardised.

Not just in terms of spelling (British vs American) but also in terms of branding guidelines (Edgeless vs whiteboard).

For spelling it is recommended to enforce British spelling e.g. "Favourites" over "Favorites"

**Comment by xell** [comment]
I close it because it's a generalization. Please feel free to add comment and reopen it when there's specific issues  about the standardisation of language.
