### ISSUE TITLE
Edgeless colours do not work immediately

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2141]
Drawing the first time is black, but switching modes and drawings will update the colours.

![draw](https://user-images.githubusercontent.com/4605025/234457803-9ae49773-1fd5-4a45-9728-af0749c6df46.gif)

**Comment by donglixiaoche** [comment]
i'm currently working on this, leave this comment in case other may also interest in this issue, to avoid duplicate works
