### ISSUE TITLE
Daily note with New homepage

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#2152]
This feature highlights a new environment in AFFiNE called Daily Note, which will be the main entrance in app. It allows users create contents conveniently, and offers a dedicated calendar view.

- [ ] A calendar view as the new home page, dedicated to the display, rearrangement and creation of daily notes.
- [ ] Users can create daily note anywhere without interrupting current workflow.

A feature related to the last: user should be able to create new page in any place where she can operate files. For example:

- Inline, linked page
- Sidebar, a stand-alone button (Ref: #2153 )
- All Pages, a stand-alone button (Ref: #2153 )

**Comment by joebeijing** [comment]
[Internal product doc](https://toeverything.feishu.cn/wiki/CVxFwuuzKi6NqHkZgAycI0M1n2d)

**Comment by tzhangchi** [comment]
> [Internal product doc](https://toeverything.feishu.cn/wiki/CVxFwuuzKi6NqHkZgAycI0M1n2d)

Look forward to the feature
