### ISSUE TITLE
Add a dedicated Settings page / modal windowset

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#2155]
Merge all the system-wise and app-wise settings into one place.

**Comment by joebeijing** [comment]
All options could be found in [internal doc](https://toeverything.feishu.cn/wiki/Q6xowrPanibKnSkEp35cQ1Ygnzg)

**Comment by QiShaoXuan** [comment]
Internal desigin https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=4712-129519&t=xltpQYfgs67UGq6V-0

**Comment by QiShaoXuan** [comment]
```[tasklist]
### Tasks
- [ ] test
```

**Comment by QiShaoXuan** [comment]
- [ ] reletate to https://github.com/toeverything/AFFiNE/issues/2649

**Comment by xell** [comment]
- [ ] #2795
