### ISSUE TITLE
Consider adding a workspace description

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2163]
![image](https://user-images.githubusercontent.com/4605025/234762495-00262fe5-24ec-4e2b-afda-2d2d8618e662.png)

**Comment by himself65** [comment]
This is easy to add but we need have a UI in figma first

**Comment by xell** [comment]
Okay, so I'll add this as a planned feature in current milestone.

**Comment by joebeijing** [comment]
@Svaney-ssman 
1. This is a feature we will definitely add in the future, which can be reflected in the UI.
2. Description is optional, which means it is not required, but name is required.
3. A Placeholder text "What is this Workspace used for?" needs to be added.
4. The added description should be editable in the Workspace Settings, just like the name.
5. It could also be considered whether it can be displayed in the My Workspaces list.
6. In the future, the description will also be added to the email template when inviting collaborators.

**Comment by Svaney-ssman** [comment]
Description UI added: [figma link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=3854-86579&t=Ej6mdZMSNi4rLLTP-4)
<img width="1019" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/83c3f1e1-421e-486b-9def-a1b45fe2e7b1">
@Himself65

**Comment by xell** [comment]
@Svaney-ssman @joebeijing it seems need to be indicated as "Optional" or something like that.

**Comment by joebeijing** [comment]
Yes, it need to be indicated as "Optional".

**Comment by Svaney-ssman** [comment]
<img width="1011" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/efb0b65c-cccc-4844-96d3-aaa8b4f6bf6f">
indicator here↑。 shall we make it more obvious?  fiil or not won't disrupt users to create workspaces
