### ISSUE TITLE
Ability to move pages between workspaces

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2164]
![image](https://user-images.githubusercontent.com/4605025/234762764-6e5dd705-3176-4809-9306-f07d12e5ddb4.png)

**Comment by himself65** [comment]
What do you mean by `between workspaces`? Does this mean crossing the workspace?

**Comment by xell** [comment]
@ShortCipher5 please contact the user who originally proposed this, or simply ask she/he to come here to follow up.

**Comment by ShortCipher5** [comment]
> What do you mean by `between workspaces`? Does this mean crossing the workspace?

Yes, ability to move a page from `Workspace A` to `Workspace B`.

**Comment by himself65** [comment]
> > What do you mean by `between workspaces`? Does this mean crossing the workspace?
> 
> Yes, ability to move a page from `Workspace A` to `Workspace B`.

This should be implemented in blocksuite side first

/cc @doodlewind

**Comment by EYHN** [comment]
This feature is not in our short-term plan. I will close this issue first. Currently, you can transfer pages between workspaces by copying and pasting.
