### ISSUE TITLE
Add tags for filtering/sorting all pages

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2165]
![image](https://user-images.githubusercontent.com/4605025/234762862-f0ba81c3-3289-44f0-8d78-ea72b32707bb.png)

**Comment by xell** [comment]
Duplicate with #2153

**Comment by xell** [comment]
It is reopened and will be completed in milestone 0.7 .

**Comment by joebeijing** [comment]
Product Doc is ready, please refer to [internal doc](https://toeverything.feishu.cn/wiki/JUeSwlJkvilZh8kyqwccym0kngQ)
