### ISSUE TITLE
Exporting of images is not currently supported

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2166]
![image](https://user-images.githubusercontent.com/4605025/234763141-12ee4622-4b46-4749-9234-7f223bacc888.png)

**Comment by xell** [comment]
Close as this function will be fully realized in https://github.com/toeverything/blocksuite/issues/2618 , which in turn is tracked by https://github.com/toeverything/blocksuite/issues/2307 .
