### ISSUE TITLE
The "Help" menu item on the macOS desktop Affine is currently empty. 

### ISSUE THREAD

**Issue by VictorNanka** [toeverything/AFFiNE#2172]
### What happened?

To improve its functionality, we could consider adding a link to our documentation.

Version: 0.5.4-canary.13

### Version

macOS x64

### Anything else?

<img width="723" alt="Screenshot 2023-04-27 at 18 23 20" src="https://user-images.githubusercontent.com/30154366/234821280-004dc810-ec9a-40dd-bcae-92f619d2a7de.png">

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Vivek7038** [comment]
Yes I'd like to help by submitting a PR!

**Comment by Vivek7038** [comment]
in which file this exist can you share 
and also what should  be the button field name to redirect to docs

**Comment by joebeijing** [comment]
Currently, we don't have a comprehensive help center yet. We are still in the process of preparing it. Once it is ready, we will provide a link that you can easily navigate to. / CC @ShortCipher5

**Comment by debadityasingh8972** [comment]
Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/14026360/a4c0cc13-c233-427d-a92a-7f25a139c321)
