### ISSUE TITLE
​Paper|Edgeless button has a visual bug

### ISSUE THREAD

**Issue by rgkirch** [toeverything/AFFiNE#2201]
### What happened?

![image](https://user-images.githubusercontent.com/6143833/235308619-860ec460-a6e9-4f0c-8ba7-c57b0c6669e5.png)
When I mouse over the button directly in the middle then it's stuck rapidly toggling between Paperless and Edgeless. I think it's because it has some spring to it and it'll spring enough to toggle to the other option which has enough spring to toggle to the other option which has some spring...

https://user-images.githubusercontent.com/6143833/235308645-b4091ad5-50b6-4586-8aac-93b3a82045a4.mp4

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
![image](https://user-images.githubusercontent.com/14026360/236957787-fd699eef-fdfa-4ae7-994f-0ba7ecdd021a.png)

I think now we don't have such UI on the latest code

**Comment by rgkirch** [comment]
Cool, thanks!
