### ISSUE TITLE
​tool bar out page when the  cursor is at the beginning of the line

### ISSUE THREAD

**Issue by aiyou9** [toeverything/AFFiNE#2205]
### What happened?

![image](https://user-images.githubusercontent.com/15712822/235361319-0e79e933-b617-4def-8111-15b9b1702bb2.png)

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
looks like zIndex incorrect
