### ISSUE TITLE
​Image can not load on a public page

### ISSUE THREAD

**Issue by lawvs** [toeverything/AFFiNE#2217]
### What happened?

For example https://app.affine.pro/public-workspace/H6vffRmJbCfA-r3kq_36_/57c46e98034b458e8513eecc0c2a7763

<img width="829" alt="Screenshot 2023-05-04 at 2 21 16 AM" src="https://user-images.githubusercontent.com/18554747/236008868-a6b205e6-1827-4fc7-a6cd-98e470528f40.png">

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
caught (in promise) Error: Login token is not set
```

**Comment by himself65** [comment]
Blob API has changed since the major update.
