### ISSUE TITLE
Sidebar: incorrect background color in dark mode after startup​

### ISSUE THREAD

**Issue by AlessioGr** [toeverything/AFFiNE#2220]
### What happened?

https://user-images.githubusercontent.com/70709113/236084122-0a3b4a57-c0f1-4b34-9511-221fec750b2a.mp4

See the video. The colors of the sidebar are incorrect until I toggle the 3-dot menu on the top right. Image:

![AFFiNE-canary 2023-05-04 at 03 06 06@2x](https://user-images.githubusercontent.com/70709113/236084162-a34c3586-cbe3-477c-a518-4eafddd5500a.jpg)

### Version

0.5.4-canary.21 

macOS ARM 64

Running on MacOS Ventura 13.3.1 (22E261)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
what is the version

**Comment by AlessioGr** [comment]
> what is the version

 0.5.4-canary.21

**Comment by himself65** [comment]
What is the macOS version?

**Comment by AlessioGr** [comment]
> What is the macOS version?

MacOS Ventura 13.3.1 (22E261)

**Comment by himself65** [comment]
Thanks for the reporting. I've conform the bug. I will try to fix the issue today

**Comment by himself65** [comment]
If you want to fix the theme in the current version, please click right top item

![image](https://user-images.githubusercontent.com/14026360/236356906-077c03d9-2987-4075-8217-665b699db09c.png)

**Comment by AlessioGr** [comment]
@Himself65 the issue still happens in 0.5.4-canary.24
