### ISSUE TITLE
​编辑页面会闪烁

### ISSUE THREAD

**Issue by ChenhWu** [toeverything/AFFiNE#2232]
### What happened?

https://user-images.githubusercontent.com/45909066/236360707-fc712692-5a48-4d10-86da-88b021016178.mov

1. 打开文档1，
2. 点击 全部页面，
3. 点击文档2
问题： 编辑页面会**快速闪烁**文档1，再显示文档2.

### Version

macOS ARM 64

### Anything else?

canary 7版本的 pin 功能挺好的，怎么去掉了。
收藏夹下的文档列表向右缩进会更符合直觉吧。

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Thanks for the reporting.

**Comment by himself65** [comment]
> canary 7版本的 pin 功能挺好的，怎么去掉了。

We are redesigning this feature. And in 0.6.0, we will support the full file system instead of pinboard

Here is a figma demo

![img_v2_990ccf6c-379c-4e5f-971c-49fc096e1a2g](https://user-images.githubusercontent.com/14026360/236368535-eef4233a-4145-42f4-9ff1-518e17c34c83.jpg)
