### ISSUE TITLE
​On startup, font colors for pages and settings in the sidebar are too similar to the sidebar background-color

### ISSUE THREAD

**Issue by IntelliJinceTech** [toeverything/AFFiNE#2247]
### What happened?

When starting up the mac app, the sidebar color is a light gray color. I have set the default light/dark setting to dark. The `Demo Workspace`, `Quick Search`, `Workspace Settings`, along with all of my pages are still white, making it hard to see clearly what I have in my sidebar. 

![image](https://user-images.githubusercontent.com/52391491/236521360-8fa40f5b-2c9a-457a-91a0-c279e22f0513.png)

This is happening on Version 0.5.4-canary.20 (0.5.4-canary.20).

Workaround is to click the 3 dots on the top-right. Otherwise, the sidebar continues to stay light gray. 

### Version

macOS ARM 64

### What browsers are you seeing the problem on?

Other

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Thanks for reporting. I'm investigating on this

**Comment by himself65** [comment]
Fixed on latest version
