### ISSUE TITLE
Rest UI issues​

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#2265]
### What happened?

1. both black and white sections in the palette panel need 0.5px borders, color:border-color
<img width="1590" alt="image" src="https://user-images.githubusercontent.com/110808979/236780335-2f3a709b-b0c6-4378-8e51-04b3583a38d4.png">

2. tips on spelling details. Some tips have only the first letter of the first word capitalized, while others have the first letter of every word capitalized. A uniform rule is needed. @ShortCipher5 can give a suggestion.
<img width="282" alt="image" src="https://user-images.githubusercontent.com/110808979/236781255-d6f9a2bf-d794-4510-aa96-465a3891ccb7.png">
<img width="212" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/aebba5df-3dc1-4fe2-8753-f8ee1418767d">

3. image toolbar icons are not lastest version
<img width="538" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/af208e97-a768-4be7-b6ad-7d062b7529ce">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
app.affine.pro has 1-month delay commits. I'm not sure whether this is a bug

**Comment by Svaney-ssman** [comment]
> 

these are client version bugs. don't know why it appears as app.affine.pro version

**Comment by JimmFly** [comment]
close by https://github.com/toeverything/blocksuite/pull/2496 https://github.com/toeverything/AFFiNE/pull/2281
