### ISSUE TITLE
File naming convention

### ISSUE THREAD

**Issue by Brooooooklyn** [toeverything/AFFiNE#2266]
We are using both camelCase style and kebab-case style filename in AFFiNE project; I'd like to unify them to dash style only and add a lint rule for it.

x-ref: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/filename-case.md

**Comment by himself65** [comment]
Yep. I was using camelCase because of my habit. But I think we should all use kebab-case style to keep same with blocksuite
