### ISSUE TITLE
[bug]: Can't link page - will delete current block content

### ISSUE THREAD

**Issue by ens100** [toeverything/AFFiNE#228]
### Describe the bug

When trying to create a link using [[ and clicking on an existing page, the text disappears

### To Reproduce

See gif
![Linking](https://user-images.githubusercontent.com/67863060/184353541-2c60d6f0-3526-42ab-8faa-9a0f794a7145.gif)

### Expected behavior

Link to be created and text to remain

### Platform

Windows 11

### Browser

Chrome

**Comment by alt1o** [comment]
Working on it. We will fix it this sprint.
