### ISSUE TITLE
[improvement]: like a slider

### ISSUE THREAD

**Issue by dxiaoqi** [toeverything/AFFiNE#229]
### 1~3 main use cases of the proposed improvement

Maybe make the mouse hover prompt more friendly

### Additional context

After the mouse is put up, it appears like a slider, I try to slide it
![5a8f790b2cd2443e0ca63ac14f0f961](https://user-images.githubusercontent.com/17349750/184373833-3f7c91ae-d615-440d-a5ea-4d210a02154c.png)

**Comment by HeJiachen-PM** [comment]
Indeed.... The current "loading bar" for tag-apps is a temporary solution. We will redo it very soon.
