### ISSUE TITLE
Button in workspace settings disappears when the width of window shrinks, and other UI glitches

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#2290]
When the width of window approaches to a certain break point, the button in workspace name of workspace settings disappears. By the way, the positions and widths of two rounded rects in Storage Folder should be improved. 

https://github.com/toeverything/AFFiNE/assets/132558/899092de-1fed-49fa-adbc-2e62670eaff4

![CleanShot 2023-05-10 at 10 00 50@2x](https://github.com/toeverything/AFFiNE/assets/132558/9d0b959e-de9c-46ef-a909-33be645518fa)

**Comment by pengx17** [comment]
I bet we need to have a basic resonsive design for this page. Let me have a try

**Comment by pengx17** [comment]
https://github.com/toeverything/AFFiNE/assets/584378/8f227a6b-70a2-4907-a1b8-e1c5bb4c00ca
