### ISSUE TITLE
​Crash on pressing `cmd-Q`

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#2298]
### What happened?

<img width="1000" alt="image" src="https://github.com/toeverything/AFFiNE/assets/7312949/51ba3a6a-ca46-47c1-9382-6144330d3252">

### Version

0.5.4-canary.30

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Fixed
