### ISSUE TITLE
[improvement]: The add field popup will change the view of the main window

### ISSUE THREAD

**Issue by dxiaoqi** [toeverything/AFFiNE#230]
### 1~3 main use cases of the proposed improvement

I hope to make the view more stable and not be pushed away

### Additional context

![bb](https://user-images.githubusercontent.com/17349750/184375708-2436c654-9cf0-4e83-b243-a839a24dd6ad.gif)

**Comment by tzhangchi** [comment]
Thanks for the feedback, we will have a very stable release early next year

**Comment by QiShaoXuan** [comment]
This is a very old and deprecated version
