### ISSUE TITLE
​Distinguish the content of the demo in different languages

### ISSUE THREAD

**Issue by suyanhanx** [toeverything/AFFiNE#2304]
### Description

I found that the current demo, although it will automatically switch the language of the system interface according to the region, the content is still uniform English. This is a bit strange. 

How about just keeping all the English, or redirecting to different demos by some kind of detecting & redirecting method?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
This is a good idea. /cc @joebeijing

**Comment by joebeijing** [comment]
Indeed, this looks like it would be more user-friendly. If the operations team is ready, we can consider doing this. CC @ShortCipher5
