### ISSUE TITLE
The list pages, such as all pages and trash, need to support batch operations

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#2305]
(from Azure)

**Comment by houjoe0829** [comment]
Batch operations on different pages will include different options.

In All pages and Collections
- Move to Trash
- Add Tag

In Trash
- Restore
- Delete permanently

**Comment by hwangdev97** [comment]
We need to add functions such as “group by” to all pages, so this task will be designed together with that part of the content (it will take some time )

**Comment by JimmFly** [comment]
Consider implementing this feature in the next iteration, removing it from the 0.9 milestone.

**Comment by JimmFly** [comment]
Close as completed
