### ISSUE TITLE
Move folder reports "success" without action

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2311]
When trying to `Move Folder` after the first time, it reports "success" without giving any options to move.

![MoveBug](https://github.com/toeverything/AFFiNE/assets/4605025/9e142ef0-7fe3-45ec-984f-1987656cf527)

**Comment by pengx17** [comment]
Strange. May I see your log files?

**Comment by ShortCipher5** [comment]
> Strange. May I see your log files?

Console log didn't show anything.

**Comment by pengx17** [comment]
Can you run this in console? You will see the electron app log file there

```
apis.debug.revealLogFile()
```

**Comment by ShortCipher5** [comment]
I found the `success` toast pops up even if you cancel or it didn't really succeeded.

```
[2023-05-11 09:29:00.149] [error] moveDBFile Error: ENOENT: no such file or directory, stat '/Users/toeverything/Library/Application Support/AFFiNE-canary/workspaces/2aRySPPQG5/storage.db'
[2023-05-11 09:29:00.150] [info]  [ipc-api] dialog:moveDBFile [ '2aRySPPQG5' ] - 1.99 ms
[2023-05-11 09:29:00.943] [error] moveDBFile Error: ENOENT: no such file or directory, stat '/Users/toeverything/Library/Application Support/AFFiNE-canary/workspaces/2aRySPPQG5/storage.db'
[2023-05-11 09:29:00.944] [info]  [ipc-api] dialog:moveDBFile [ '2aRySPPQG5' ] - 2.85 ms
[2023-05-11 09:29:01.124] [error] moveDBFile Error: ENOENT: no such file or directory, stat '/Users/toeverything/Library/Application Support/AFFiNE-canary/workspaces/2aRySPPQG5/storage.db'
```

**Comment by pengx17** [comment]
It looks like the DB file is missing somehow so that you are seeing the error. Let me take a look what I can do

**Comment by ShortCipher5** [comment]
Can we enforce a limit on the popup too - as currently I can create infinite.

![LimitPopup](https://github.com/toeverything/AFFiNE/assets/4605025/be5eddf3-b160-435d-bb53-4943e8d545a2)

**Comment by pengx17** [comment]
> I found the `success` toast pops up even if you cancel or it didn't really succeeded.
> 
> ```
> [2023-05-11 09:29:00.149] [error] moveDBFile Error: ENOENT: no such file or directory, stat '/Users/toeverything/Library/Application Support/AFFiNE-canary/workspaces/2aRySPPQG5/storage.db'
> [2023-05-11 09:29:00.150] [info]  [ipc-api] dialog:moveDBFile [ '2aRySPPQG5' ] - 1.99 ms
> [2023-05-11 09:29:00.943] [error] moveDBFile Error: ENOENT: no such file or directory, stat '/Users/toeverything/Library/Application Support/AFFiNE-canary/workspaces/2aRySPPQG5/storage.db'
> [2023-05-11 09:29:00.944] [info]  [ipc-api] dialog:moveDBFile [ '2aRySPPQG5' ] - 2.85 ms
> [2023-05-11 09:29:01.124] [error] moveDBFile Error: ENOENT: no such file or directory, stat '/Users/toeverything/Library/Application Support/AFFiNE-canary/workspaces/2aRySPPQG5/storage.db'
> ```

hmm ... I cannot reproduce this issue.
In the implementation, even if the db file does not exist, it will try to re-create it first.
BTW, what is the app version you are using? Can you please try if moving db works for another workspace?

Anyway in my new fix I will report an error instead of saying success instead.
