### ISSUE TITLE
Favourites UI/UX

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2315]
Many of these issues may be fixed with the new sidebar design, but are found in app currently.

1) Favourites
2) Favourite pages blend in with other options (such as all pages and trash) - should there be a slight indent or other modification to show that these are not "options" like the other sidebar settings.
3) It's not obvious that the favourite group extends - there is no scrollbar.
4) The favourites will automatically pop back down to the selected page when trying to scroll up through the list.

![favourites](https://github.com/toeverything/AFFiNE/assets/4605025/295aa7c7-d0e2-4c7a-a1b4-129b7fbe698b)

**Comment by pengx17** [comment]
Will be fixed in the new sidebar implementation
