### ISSUE TITLE
back / forward button should be grayed out while there's no action.

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2316]
These two icons appear to have no functionality

<img width="312" alt="Screenshot 2023-05-11 at 09 56 03" src="https://github.com/toeverything/AFFiNE/assets/4605025/cc01f4d3-a02e-4faf-a76e-27b2e5cac5e1">

**Comment by ShortCipher5** [comment]
Grey out / disable when no actions to perform.

**Comment by pengx17** [comment]
It sorta like a feature request. I did attempt to find a solution before, but there was no good solution to detect the history stack in the Nextjs case. I think we can revisit this issue later.

**Comment by pengx17** [comment]
Fixed by https://github.com/toeverything/AFFiNE/pull/2336
