### ISSUE TITLE
​部分使用问题和交互疑惑

### ISSUE THREAD

**Issue by huangzx618** [toeverything/AFFiNE#2319]
### What happened?

**问题：**
1.  md 的细节也有问题，连续编号中只要有其他内容，好像就不能连续
<img width="776" alt="image" src="https://github.com/toeverything/AFFiNE/assets/70992596/8e225703-9c7e-4756-bf51-5a5abac2356e">

2. 画板中控件背景色选择任何颜色后都是黑色

**疑惑：**
1. 菜单侧的分类有点莫名其妙
2. 快速搜索下是工作区设置，这个两个完全不是维度的事吧，个人觉得工作区设置是不是放在 Demo workspace 这个空间名称下面比较合适
3. 只能进全部页面才能查看全部页面，这个就很难受了
4. 然后全部页面和收藏夹还用一条线来分割，这个分割的逻辑是否有，还是随意割一刀而已

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by huangzx618** [comment]
另外能请教一下 pinboard 的定位吗？
是一个工作空间只有一个 pinboard？
然后这个 pinboard 又是一个特殊页面，但是从页面交互上来看这个没有什么特殊性，只是页面默认名字上带了 workspace Pinboard 的字样，不过页面名称又支持用户修改，如果我修改成 abc 那就完全不知道了，然后下面只能 link 到 abc，这个就让人很费解这个 pinboard 的定位了
<img width="1440" alt="image" src="https://github.com/toeverything/AFFiNE/assets/70992596/963488c5-c454-4a5c-a471-fa1c14749ac8">
<img width="1429" alt="image" src="https://github.com/toeverything/AFFiNE/assets/70992596/e7a0a5c3-38eb-4963-a03f-9a283132f4f9">

**Comment by joebeijing** [comment]
Apologies for the delayed response to your message. We've recently released a beta version which addresses some of the issues you've reported concerning the sidebar. You may obtain it by clicking on this link: https://affine.pro/download.

Also, we're aware of the issue with the sidebar and have decided against temporarily expanding the "All Pages" feature to prevent overloading the sidebar with excessive information.

And, the problem of continuous numbering in numbered lists has been verified and we're working on optimizing it in future updates.

Lastly, we're confident that we've resolved the color selection issue in the whiteboard. However, if the issue occurs again, please capture a screenshot and send it to us for additional investigation.
