### ISSUE TITLE
​Add  open-source spaced repetition algorithms to roadmap

### ISSUE THREAD

**Issue by gapore** [toeverything/AFFiNE#2339]
### Description

https://github.com/open-spaced-repetition
Open Spaced Repetition
We are developing open-source spaced repetition algorithms for any spaced repetition software/system

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by darkskygit** [comment]
can you explain what functionality in affine you hope to use this algorithm for?
