### ISSUE TITLE
Dark mode sidebar UI issues

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2345]
Latest release - sidebar selected item is not readable

<img width="238" alt="Screenshot 2023-05-12 at 15 52 49" src="https://github.com/toeverything/AFFiNE/assets/4605025/502fe0ed-7ed4-464b-af96-cba641e59d5b">

**Comment by hwangdev97** [comment]
we have already discussed the relevant design details and will handle the updates in the future.  cc @pengx17
