### ISSUE TITLE
The user jouney of initiating a new workspace incorporates too many steps(7-8)

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#2347]
![20230512-155635](https://github.com/toeverything/AFFiNE/assets/121489905/5cd8faad-10b5-4118-b442-7e534d244afe)

**Comment by ShortCipher5** [comment]
Should import be part of `New workspace`?
Why not have `Import` along the top - such as next to the close `x` icon.
And `Create` directly goes to creating not adding/importing.

**Comment by xell** [comment]
Closed as being covered by https://github.com/toeverything/AFFiNE/issues/2488 .
