### ISSUE TITLE
Button overflow when width is the mininum​

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#2351]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/14026360/53100508-09dc-46ef-befa-b820f4e65434)

### Version

macOS ARM 64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
Oh, this one should have been fixed in https://github.com/toeverything/AFFiNE/pull/2348
