### ISSUE TITLE
​Less padding around window controls

### ISSUE THREAD

**Issue by adityash1** [toeverything/AFFiNE#2353]
### What happened?

they are harder to click when we want to navigate fast. It should span the whole top right corner
![AFFiNE-canary_qREuzQDLDm](https://github.com/toeverything/AFFiNE/assets/65771169/c01e5b40-eb0e-4508-ad66-f31690a2db53)

### Version

Windows x64

### What browsers are you seeing the problem on?

Other

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hwangdev97** [comment]
<img width="1056" alt="shot-2023-05-14-15 25 11@2x" src="https://github.com/toeverything/AFFiNE/assets/24713927/52798a61-bfc9-4bc5-b075-00eefdde8d5f">

I think it looks good this way and @pengx17  might be responsible for the development.
