### ISSUE TITLE
After opening the image preview, clicking the close button does not work

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2362]
https://github.com/toeverything/AFFiNE/assets/22443345/131742c0-937e-4f68-9f9f-54479ff755d6

It is suggested to make the close button easier to activate and enable the preview to be closed directly by clicking outside the image area.

**Comment by xell** [comment]
And using Esc to exit the preview mode might be worthy of consideration.

**Comment by joebeijing** [comment]
> And using Esc to exit the preview mode might be worthy of consideration.

Agree with that.

**Comment by pengx17** [comment]
Hide this feature behind a feature flag

**Comment by danielchim** [comment]
Attempting to fix it by moving the close button lil bit below by the UI design file in #2807, please let me know if the issues still persists

**Comment by danielchim** [comment]
Fixed in [0.7.0-canary.19](https://github.com/toeverything/AFFiNE/releases/tag/v0.7.0-canary.19), please let me know if it does not working again.
