### ISSUE TITLE
When previewing a image, the default display should be fit to the window size

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2369]
![CleanShot 2023-05-15 at 5 54 07@2x](https://github.com/toeverything/AFFiNE/assets/22443345/4e9e223e-8595-4c18-a036-2a1db159448e)
Regardless of the size of the image, it needs to be displayed completely by default.

**Comment by xell** [comment]
Please refer to [internal link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=1071-36700&t=qvBDzhCnO83U0kUj-4) as the design guide.

**Comment by danielchim** [comment]
Will be available in the following PR with the button for "Fit to screen"
