### ISSUE TITLE
[bug]: Undo will clear all pre-loaded content in Edgeless Mode and sometimes return a blank screen

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#237]
### To Reproduce

1. Enter endless mode
2. Add a shape
3. Undo

The page content disappears. Keeps on undoing will lead to an all-page white screen.

### Screenshots

before undo:
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/7312949/184460512-4abf743d-9f0f-4a05-9273-fc972a1f351e.png">

after undo:
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/7312949/184459653-14e788e1-53e7-4e66-aea5-be668e43fde5.png">

undo twice:

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/7312949/184461333-a382a1eb-d152-44d3-bbcf-22110d94d6f4.png">

### Platform

macOS

### Browser

Chrome

**Comment by CJSS** [comment]
Recreated.

Directly in the demo - undo led to all preloaded content being removed.
When opening a saved doc - from SYNC TO DISK - the whole page turned white - with the toolbar also disappearing.

**Comment by CJSS** [comment]
Looks like a similar issue to @121

**Comment by ShortCipher5** [comment]
Undo & redo functionality, as well as history of operations have been significantly improved in the latest release.
