### ISSUE TITLE
The shortcut key to expand the sidebar is not working

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2370]
1. The shortcut key needs to be functional.
2. Hovertips need to be displayed when expanding and collapsing. Currently, they are only displayed when collapsed.

![image](https://github.com/toeverything/AFFiNE/assets/22443345/c6c6af6c-852d-463b-8c77-cc7cf62eb6ac)

**Comment by pengx17** [comment]
I cannot reproduce. What's your app version?

**Comment by xell** [comment]
The shortcut is okay. But as aforementioned, the hover tip should be applied to the button while the sidebar is expanded.
