### ISSUE TITLE
The toolbar in edgeless mode requires an active state​

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#2376]
### What happened?

![Uploading shot-2023-05-15-22.45.35@2x.png…]()

### Version

macOS ARM 64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
no image

**Comment by joebeijing** [comment]
Duplicated with https://github.com/toeverything/blocksuite/issues/2650
