### ISSUE TITLE
The popup window of My Workspaces doesn't perform as expected in narrow mode

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2384]
<img width="656" alt="CleanShot 2023-05-16 at 11 30 41@2x" src="https://github.com/toeverything/AFFiNE/assets/22443345/484d1b2b-972c-45db-a663-1a9eb6159033">

**Comment by joebeijing** [comment]
CC @xell

**Comment by xell** [comment]
It should realize the design in [internal link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=449-13137&t=S7AqlPdjhWRBXdzm-4).
