### ISSUE TITLE
Use `affine` as default filename extension instead of `db`

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#2397]
### Description

Use `affine` as default filename extension instead of `db`, like `my-workspace.affine`.

### Use case

A better solution in exporting, storage, and importing workspace database file, visible to all users.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
Closed by https://github.com/toeverything/AFFiNE/pull/2491
