### ISSUE TITLE
[feature]: Add dark mode

### ISSUE THREAD

**Issue by PritamSarbajna** [toeverything/AFFiNE#240]
### 1~3 main use cases of the proposed feature

This will be a amazing for the people who don't like light mode.

### Ideas for solution

Just make a toggle button for dark and light and just make changes in css.

### what types of users can benefit from using your proposed feature

All type of users

**Comment by darkskygit** [comment]
dark mode definitely an important feature, but simply adding a dark background is not a dark mode, the color matching of various components, text and code blocks also needs to be considered
we won't start developing until the design is ready, but dark mode is definitely on our roadmap
the roadmap is expected to be released next week, please stay tuned

**Comment by ShortCipher5** [comment]
Dark mode has been added to the latest version.
