### ISSUE TITLE
Cannot delete last workspace - no prompt for user

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2402]
When trying to delete the last workspace it will not be deleted - but the user is not informed of the reason.

If the user cannot delete the last workspace - they should receive a notification or message telling them so.

![LastDelete](https://github.com/toeverything/AFFiNE/assets/4605025/d2ce1c18-aed5-4b60-a10a-0f6ce3c560d8)

**Comment by xell** [comment]
In fact there is a warning tip:



![Image](https://github.com/toeverything/AFFiNE/assets/132558/930c4fdc-2bb3-4d26-ba22-f82053b2b296)

However, I think the procedure can be optimized to not bother the user so much. If it's the only one workspace, the Delete button in the Delete Workspace should be disabled at all. And the "You cannot delete the last workspace" annotation should be highlighted somewhere in the description area.  CC @Svaney-ssman to offer a design plan.

**Comment by Svaney-ssman** [comment]
[Internal figma link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=3334-82419&t=HGRqutOBhGxB2hB6-4l)
<img width="675" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/71a7783c-4243-45cc-ac54-fccb170847f1">

**Comment by himself65** [comment]
The reason is AFFiNE needs one workspace so that we can display the correct UI. And When it's 0 workspaces, the code will crash. I think it needs a discussion by @joebeijing whether redirect the page to a create workspace page or prohibit deleting the last one

**Comment by joebeijing** [comment]
@Himself65
Based on the current implementation, the last workspace cannot be deleted and a Toast message will appear. According to the original design, the expected effect was that the last workspace could be deleted, but the My Workspaces page would then pop up and cannot be closed unless a new workspace is created.

<img width="735" alt="CleanShot 2023-05-29 at 5 13 43@2x" src="https://github.com/toeverything/AFFiNE/assets/22443345/076895b5-2b49-4c6e-b1d4-322abedef342">
