### ISSUE TITLE
Update pre-loading content

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#2403]
Source content: https://app.affine.pro/public-workspace/uvhXnx4KIY2ODua3s1DGT/JUOBw1drd8

- Images will need to be updated in the future.

**Comment by ShortCipher5** [comment]
Direct export.

[Preload Page Content.md](https://github.com/toeverything/AFFiNE/files/11495388/Preload.Page.Content.md)

**Comment by JimmFly** [comment]
> Direct export.
> 
> [Preload Page Content.md](https://github.com/toeverything/AFFiNE/files/11495388/Preload.Page.Content.md)

Could you please give me a copy of the image link in this file? Maybe @darkskygit can help you.

**Comment by ShortCipher5** [comment]
Images:
1. https://cdn.affine.pro/94d27d73c5767986d26b81a0ced25ac6ab16686971734ba0d9c0987c.gif
2. https://cdn.affine.pro/1326bc48553a572c6756d9ee1b30a0dfdda26222fc2d2c872b14e609.gif
3. https://cdn.affine.pro/5fa80ab814f052d259ed6863a336a719eef746ed1bdd9b973750ce0c.gif
4. https://cdn.affine.pro/cf5d44d36ec3167519e6d6518914d28acaf426f001da717c1e98e760.gif
5. https://cdn.affine.pro/eb9832e551551d480f38b70145b28b7552e2a9f899ddfa6d813049a9.gif
