### ISSUE TITLE
Revise texts all over the UI​

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#2406]
Texts in Figma ([internal link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=1874-42550&t=I1vTNaJETj6HnQiy-4)) which have been approved by @ShortCipher5 are not reflected in the app.

![CleanShot 2023-05-17 at 14 07 43@2x](https://github.com/toeverything/AFFiNE/assets/132558/306508dd-0288-4391-94f2-fb7c2813ec4f)

**Comment by JimmFly** [comment]
I think the text is as expected now, the section about AFFiNE Cloud will be updated in the next version.

**Comment by aiyou9** [comment]
![Image](https://github.com/toeverything/AFFiNE/assets/15712822/95fd54db-48e8-41b0-9f86-dbf6a99a7d16)

**Comment by mon-jai** [comment]
Related: #2529

The wrong font face was rendered in @aiyou9 's screenshot too.

**Comment by xell** [comment]
> Related: #2529
> 
> The wrong font face was rendered in @aiyou9 's screenshot too.

Thanks for pointing out this.

**Comment by JimmFly** [comment]
I think the main problem of this issue has been fixed in the latest version, and I will open another issue for the problem raised later.
