### ISSUE TITLE
[feature]: Persisted data and dedicated users with OpenID Connect support

### ISSUE THREAD

**Issue by alexanderadam** [toeverything/AFFiNE#244]
### 1~3 main use cases of the proposed feature

- users might want to switch browsers but still keep the data
- people who're selfhosting software are probably already having an OpenID provider (i.e. [Nextcloud](https://apps.nextcloud.com/apps/oidc), [GitLab](https://docs.gitlab.com/ee/integration/openid_connect_provider.html), [Authelia](https://www.authelia.com/) or [Authentik](https://goauthentik.io/))

### Ideas for solution

1. having server side persistence
2. using an OIDC library (i.e. one for [TypeScript](https://www.npmjs.com/package/oidc-client-ts), [JS](https://www.npmjs.com/package/oidc-provider) or [Rust](https://docs.rs/openidconnect/latest/openidconnect/)) to authenticate users — the settings for the server could be given via `ENV` variables to the AFFiNE Container

### what types of users can benefit from using your proposed feature

selfhosting users

**Comment by darkskygit** [comment]
1. if you use our latest container(https://github.com/toeverything/AFFiNE/pkgs/container/affine) or livedemo(https://livedemo.affine.pro), you can use "Sync to Disk" to save you while workspace data and sync or backup it with gdrive/onedrive/icloud to any other machine or browser, this feature does not need a server
![image](https://user-images.githubusercontent.com/25152247/184530900-fcad70fb-7092-44a3-ac51-c9282ce5121c.png)
2. the server-side storage in jwt (the code name of our data sync backend) has been theoretically supported from the beginning of the design. now we rewrite jwt with rust, fter the rewrite is completed, the code implementation of the server-side storage will also be merged into this repository.
p.s. at present, you can build and run our synchronization backend without data landing (https://github.com.com/toeverything/AFFiNE/blob/develop/.github/deployment/Dockerfile-keck), it allows you to sync data between multiple clients, but the backend will only keep synced data in memory, you still need to use the "Sync to Disk" function to save the data on the local hard disk, but as long as the server is not offline, your data can be merged into another client without conflict after offline editing like this:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/25152247/184531777-1d581a50-e073-42b3-9d32-4c3b73bdeda6.png">
3. our recent development goal is to make the AFFiNE more stable and reliable, and oidc is a relatively enterprise-level function with complicated configuration. i don't quite understand what role it plays with personal users, so our roadmap currently no development schedule for this function. if you want to promote the development of this function, please describe your usage scenarios in detail or explain why many users would like to have this function.

**Comment by Asher9971** [comment]
Hi,
I think a server-side storage option is a must have.
Everyone who can setup a docker-container also have the abilities to setup a persistent storage.
Server-side Storage has a simple and important advantage -> I can access my data **everywhere** and **always** whenever i need them.

It would be a KO criteria for me (and also many people i know) if this will not be supported to use affine :(

Thumbs up if you agree.

Thanks!

Cheers

**Comment by darkskygit** [comment]
> Hi, I think a server-side storage option is a must have. Everyone who can setup a docker-container also have the abilities to setup a persistent storage. Server-side Storage has a simple and important advantage -> I can access my data **everywhere** and **always** whenever i need them.
> 
> It would be a KO criteria for me (and also many people i know) if this will not be supported to use affine :(
> 
> Thanks!
> 
> Cheers

Currently the AFFiNE app is more of a client. The app is designed that it can be run either online, or offline, and your data is stored local-first.

Because your data is stored locally first, there are some ways you can utilize cloud storage. For example, if you have a folder that syncs to a cloud storage (for examples OneDrive on Windows). This will allow you to have local storage of data, that is also available on the cloud.

If you are interested in unlocking more features and possibilities through a central server, we are sure you'd love to learn more about the upcoming AFFiNE Cloud.

If this is something you'd be interested in, please let us know and we'll make sure you are kept updated and are one of the first to find out.

**Comment by Asher9971** [comment]
> > Currently the AFFiNE app is more of a client. The app is designed that it can be run either online, or offline, and your data is stored local-first.
> 
> Because your data is stored local-first, there are some ways you can utilize cloud storage. For example, if you have a folder that syncs to a cloud storage (for examples OneDrive on Windows). This will allow you to have local storage of data, that is also available on the cloud.
> 
> If you are interested in unlocking more features and possibilities through a central server, we are sure you'd love to learn more about the upcoming AFFiNE Cloud.
> 
> If this is something you'd be interested in, please let us know and we'll make sure you are kept updated and are one of the first to find out.

Ok, i understand that data should be available offline and online but this can also be achieved by using the sync to disk feature parallel to server-storage or am i missing something?
Affine Cloud seems interesting for me. Do you have some more information for me? I hope it will be available as private selfhosting cloud - that would be the privacy we are all looking for.

If the Cloud version will be selfhostable then i fully understand your approach to build a „client-solution“ too

Cheers ;)

**Comment by alexanderadam** [comment]
> our recent development goal is to make the AFFiNE more stable and reliable, and oidc is a relatively enterprise-level function with complicated configuration. i don't quite understand what role it plays with personal users, so our roadmap currently no development schedule for this function. if you want to promote the development of this function, please describe your usage scenarios in detail or explain why many users would like to have this function.

Sure, I guess that's just very easy to explain:
If you are selfhosting things, you don't want to have ten different different logins for ten different apps.
It doesn't have anything to do with being 'enterprise-level'.

That's why you can always find threads about [Authelia](https://www.reddit.com/r/selfhosted/search/?q=authelia&restrict_sr=1&sr_nsfw=), [SSO](https://www.reddit.com/r/selfhosted/search/?q=sso&restrict_sr=1&sr_nsfw=) or [Keycloak](https://www.reddit.com/r/selfhosted/search/?q=keycloak&restrict_sr=1&sr_nsfw=), [Authentik](https://www.reddit.com/r/selfhosted/search/?q=authentik&restrict_sr=1&sr_nsfw=) in the Reddit selfhosters community.

That's also one of the reasons why basically every popular open source projects has SSO functionality or has people wanting it.
You want to selfhost a password manager like Vaultwarden? It's getting [OpenID Connect support](https://www.reddit.com/r/selfhosted/search/?q=sso&restrict_sr=1&sr_nsfw=).
You want to host a wiki like wiki.js? It already has [OIDC support](https://docs.requarks.io/auth).
Nextcloud? Can use OIDC [as a client](https://apps.nextcloud.com/apps/oidc_login) and [it can also be used as a provider](https://apps.nextcloud.com/apps/oidc).
You want to use a media server like Jellyfin? Well [it also has support for it](https://github.com/9p4/jellyfin-plugin-sso#openid-1).
You want to host a selfhosted AdBlock filter management like LetsBlockIt? [It also has SSO support](https://github.com/letsblockit/letsblockit/tree/main/cmd/server#oauth2-authentication-with-oauth2-proxy).

Making authentication simpler and more secure is not something that's just relevant for 'enterprise environments'.
I'm not even sure why somebody would _not_ like to have it when hosting more than one application.

**Comment by Rid** [comment]
@darkskygit Please could you clarify if AFFiNE Cloud will be FOSS?

**Comment by darkskygit** [comment]
> @darkskygit Please could you clarify if AFFiNE Cloud will be FOSS?

the core of affine cloud is contained in this repo, that means the core of affine cloud is open source, and developers can build self-hosted versions of affine based on them. affine cloud is designed to provide users with an out-of-the-box experience.
since the last reply, we launched "Sync to Disk" and "import/output workspace" feature, but users reported to us that they were confused by these local-first features, so we transform that two feature into a self-hosted server storage, which allows you to run the central server as a synchronization node.

**Comment by Rid** [comment]
> > @darkskygit Please could you clarify if AFFiNE Cloud will be FOSS?
> 
> The core of AFFiNE Cloud is contained in this repo and is open source. Developers can build self-hosted versions of AFFiNE based on this code. AFFiNE Cloud is designed to provide users with an out-of-the-box experience, the exact details of which are still under discussion and will be released when confirmed.
> 
> Since the last reply, we have launched "Sync to Disk" and "Import/Export Workspace" features, but users reported to us that they were confused by these local-first features. So, with our latest release we now allow users to run a central server as a synchronization node, so we transform these two features into a self-hosted server storage solution.

That's great! We really appreciate your efforts, and massive thanks for open sourcing the project.

We will try to assign the project some engineering effort when we can!

**Comment by Avey777** [comment]
> > @darkskygit Please could you clarify if AFFiNE Cloud will be FOSS?
> 
> The core of AFFiNE Cloud is contained in this repo and is open source. Developers can build self-hosted versions of AFFiNE based on this code. AFFiNE Cloud is designed to provide users with an out-of-the-box experience, the exact details of which are still under discussion and will be released when confirmed.
> 
> Since the last reply, we have launched "Sync to Disk" and "Import/Export Workspace" features, but users reported to us that they were confused by these local-first features. So, with our latest release we now allow users to run a central server as a synchronization node, so we transform these two features into a self-hosted server storage solution.

Does the current latest docker version already allow the server to act as a sync disk? how can i use it without https
