### ISSUE TITLE
Found typo?

### ISSUE THREAD

**Issue by err931** [toeverything/AFFiNE#2446]
### What happened?

https://github.com/toeverything/AFFiNE/blob/c1ca578f7dfa100a3d06b14ba02f3f3310babc92/packages/i18n/src/resources/en.json#L111

Maybe a misspelling of `Oops!`? Please close if this is intentional.

Best Regard,

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
Thank you so much for pointing out the typo! We strive for accuracy and clarity in all of our documentation, and we appreciate your help in spotting this error.
We will fix this issue as soon as possible. If you notice anything else in the future, please feel free to let us know.
