### ISSUE TITLE
Icons in readme should be updated

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#2450]
1. Update the AFFiNE logo to the latest.
2. Update the community logo, which can reuse the upper one because it seems they share the same web url.

![CleanShot 2023-05-19 at 09 34 13@2x](https://github.com/toeverything/AFFiNE/assets/132558/867b05bd-049c-42a0-8714-f4b9906f644a)

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/commit/9bee6bd5cce4b198a730e1161a23ae25dccbab1d

**Comment by xell** [comment]
it seems these two are not correct @Himself65 

![CleanShot 2023-05-31 at 17 19 46@2x](https://github.com/toeverything/AFFiNE/assets/132558/2cdc2976-11da-4bc1-9c6f-374a9724cf9f)

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/commit/b6188f4b1155c4b689ee41c35c7e1ca3d0bd7103

and the bottom one doesn't have such a logo
