### ISSUE TITLE
​I can't customize the path when create my workspace

### ISSUE THREAD

**Issue by Megnate** [toeverything/AFFiNE#2455]
### What happened?

- when i creating my workspace, i want to custmize the save path, but after i clicked the "select" button, it happened nothing.
- Should i have to create a new db file at my path before i create the workspace?
![image](https://github.com/toeverything/AFFiNE/assets/72927199/c0ca4250-a28b-4ca0-acdd-4211aa2072a9)
- It can't create the new db file after i choose the custmize path.

### Version

Windows x64

### What browsers are you seeing the problem on?

Other

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
The client app goes with a refactor with the folder selection. Is it still an issue in the latest version?
