### ISSUE TITLE
[improvement]: Support for exporting files e.g. pdf, doc

### ISSUE THREAD

**Issue by hayasec** [toeverything/AFFiNE#246]
### 1~3 main use cases of the proposed improvement

AFFiNE is amazing!
I want to export pdf to my friends.
But how to export the articles like pdf or doc?

**Comment by tzhangchi** [comment]
@hayasec Thank you for your continuous attention to AFFiNE. In the latest https://github.com/toeverything/AFFiNE/releases/tag/v0.7.0-canary.8 version, we have started internal testing of the PDF export function, and hope you can experience it and give us feedback
