### ISSUE TITLE
When copy pasting a URL into the text area, after pushing space or pushing enter the URL does not convert into a hyperlink​

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/AFFiNE#2460]
### What happened?

If I past a link into Affine, the expected result is after pushing the space bar or pushing enter, the URL is converted into a Hyperlink. This isn't the case with Affine currently.

Using latest Affine.Pro beta version on Linux.

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Other

### Anything else?

Just to note I'm using the Linux version of Affine.Pro. The "Version" option above doesn't give an option for linux app.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Noothan-am** [comment]
hey @SolarDesalination, i am not able to recreate this issue is this still happening or already fixed?

**Comment by himself65** [comment]
Could you please give us a video? And the version of the AFFiNE.

**Comment by SolarDesalination** [comment]
This was fixed in one of the recent versions. Tried in 0.8 beta and can't replicate the previous bug. Thanks.
