### ISSUE TITLE
AFFiNE Does not load in firefox nor LibreWolf​

### ISSUE THREAD

**Issue by purpleden** [toeverything/AFFiNE#2464]
### What happened?

Visit https://app.affine.pro/workspace/

Wait for the page to load, the logo with "Page is loading" constantly shown

![image](https://github.com/toeverything/AFFiNE/assets/33729019/47a4fccb-002f-45a3-a41e-c954e0445616)

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Other

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Thanks for reporting. For a better experience, please use Chrome or download our desktop app. And we will investigate this bug and make Firefox the same user experience

**Comment by jerptrs** [comment]
Any news on this? Not going to install a desktop app or Chrome...

**Comment by hhelibeb** [comment]
It seems Firefox doesn't support indexedDB.databases(), which causes this issue.

**Comment by fourdim** [comment]
Fixed by #3417, https://github.com/toeverything/blocksuite/pull/3795, https://github.com/toeverything/blocksuite/pull/3738.
Please wait for the deployment.

**Comment by fourdim** [comment]
https://github.com/toeverything/AFFiNE/releases/tag/v0.8.0

**Comment by DieserMerlin** [comment]
I just installed Affine myself and noticed it still (or again?) won't oeprate in Firefox. In Chrome it works just fine.

Console shows this error:
`Uncaught (in promise) TypeError: indexedDB.databases is not a function`

**Comment by fourdim** [comment]
Hi, are you currently using self-hosted docker to deploy AFFiNE? That is the outdated one.
A new self hosted docker will be released after #5069. Please trace it there.
Alternatively, you can go to AFFiNE cloud to have a free trial of the latest version in https://app.affine.pro/.
