### ISSUE TITLE
AFFiNE Desktop Client Workspace Export Error​

### ISSUE THREAD

**Issue by purpleden** [toeverything/AFFiNE#2467]
### What happened?

Press Export and a file requester should pop up, instead receive an error

![image](https://github.com/toeverything/AFFiNE/assets/33729019/16c9f904-d4a0-4e47-9181-5c2855fe22c6)

### Version

Windows x64

### What browsers are you seeing the problem on?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
I think we don't support export from web? 

@pengx17

**Comment by pengx17** [comment]
Yes, I think this button should be disabled on web. Are you seeing this button enabled on Chrome?
If you are on desktop client, what is the version you are using?
@purpleden

**Comment by m1911star** [comment]
@purpleden  is there any more info you can provide? Maybe you can try our latest version?
