### ISSUE TITLE
Ability to change note page width​

### ISSUE THREAD

**Issue by SaifEl-Deen** [toeverything/AFFiNE#2474]
### Description

Add the ability to change the maximum text length on pages

### Use case

With the list block feature, it's hard to navigate wide tables, you have to scroll horizontally

### Anything else?

No

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Duplicated with https://github.com/toeverything/blocksuite/issues/2685

However, we are developing this feature and you should be able to see it soon.
