### ISSUE TITLE
Moving Folder should not be implemented as "Save As".

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2479]
The expected behavior should be that the user can only select the destination location for the folder, rather than editing the name of a "Save As" file.
<img width="450" alt="CleanShot 2023-05-22 at 1 43 46@2x" src="https://github.com/toeverything/AFFiNE/assets/22443345/f4b833c1-88c2-4d94-b104-9de3865cc8fc">

**Comment by pengx17** [comment]
Done in new version
