### ISSUE TITLE
[feature]: Add keyboard shortcuts in edgeless mode.

### ISSUE THREAD

**Issue by UlyssesZh** [toeverything/AFFiNE#248]
### 1~3 main use cases of the proposed feature

I uses drawing tablet to draw and write things on my computer. Currently I use [StylusLabs Write](https://styluslabs.com/) because it supports pen pressure and has many keyboard shortcuts. I want similar experience in whiteboard mode of AFFiNE.

### Ideas for solution

- Hold <kbd>Shift</kbd> for eraser;
- Hold <kbd>Ctrl</kbd> for selection (better if it is lasso selection);
- Hold <kbd>Spacebar</kbd> for panning (already implemented);
- Use number keys (<kbd>1</kbd>, <kbd>2</kbd>, etc.) to switch to different colors;
- Use letters (<kbd>Q</kbd>, <kbd>W</kbd>, etc.) to switch to different stroke types (highlighter, pencil, etc.).

### what types of users can benefit from using your proposed feature

People with keyboard and drawing tablet

**Comment by tzhangchi** [comment]
Thanks for your feedback, I will discuss it with our engineers
