### ISSUE TITLE
Please change `--affine-editor-width` to 800px​

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#2486]
### Description

Please change this variable ( `--affine-editor-width` ) to 800px.

With the existing 24px padding included, the content size would be 752px.

<img width="422" alt="shot-2023-05-22-16 59 24@2x" src="https://github.com/toeverything/AFFiNE/assets/24713927/b219005b-8bcf-450a-894e-d1813a246d73">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xell** [comment]
I second this proposal and see no conflict with the original responsive design [internal link](https://toeverything.feishu.cn/wiki/wikcnHv8944ZsglP1JnU27wGPBc?table=tblDTFpdJv1LYE67&view=vewpZkdl8d), which can continue to be the base of the new width by simply changing the original 686 to 800.

**Comment by zqran** [comment]
`Affine` and `BlockSuite` should have the same width on both sides, so the same css variable should be used.

Related to: https://github.com/toeverything/design/pull/11
