### ISSUE TITLE
Optimize the process of creating and importing Workspaces

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#2488]
The main change is the merging of the entry points for adding and importing Workspaces.
Please refer to [internal doc](https://toeverything.feishu.cn/wiki/S7HKwiuSMiVVCJk0BcrcXdd0noe)

**Comment by xell** [comment]
Note: https://github.com/toeverything/AFFiNE/issues/2347 will be largely covered here.

**Comment by joebeijing** [comment]
Related with https://github.com/toeverything/OctoBase/issues/173
