### ISSUE TITLE
Cannot build client in local env​

### ISSUE THREAD

**Issue by m1911star** [toeverything/AFFiNE#2501]
### What happened?

<img width="1202" alt="image" src="https://github.com/toeverything/AFFiNE/assets/4948120/173b96dc-3774-430a-952d-e3c015aef832">

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
@m1911star is it still an issue?

**Comment by m1911star** [comment]
sorry，need to add full disk access to webstorm or terminal, will close it
