### ISSUE TITLE
Poor contrast over "actionables" labels and icons in darkmode​​

### ISSUE THREAD

**Issue by callmehanu** [toeverything/AFFiNE#2505]
### Description

In some situations (maybe color spaces and monitor calibrations) that tone of **purple/violet** is really hard to read. 

![Screenshot from 2023-05-22 12-37-29](https://github.com/toeverything/AFFiNE/assets/13230502/92b54bf3-fe75-4fdd-b466-a2c6698c4fc5)
![Screenshot from 2023-05-22 12-35-14](https://github.com/toeverything/AFFiNE/assets/13230502/6cdbf31c-d3b2-4ded-a5f2-e241781113c6)
![Screenshot from 2023-05-22 12-35-36](https://github.com/toeverything/AFFiNE/assets/13230502/9e6e1ce1-1dd0-42fe-8045-3589e5e6c9b8)
![Screenshot from 2023-05-24 01-26-21](https://github.com/toeverything/AFFiNE/assets/13230502/8fa3fa40-d22f-45d6-a37f-0e804cc91fb5)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xell** [comment]
Thanks for pointing out this. We are planning to have an overhaul of color theme in the next milestone, so I just closed this issue for now and will link the progress here if it's available.
