### ISSUE TITLE
[feature]: Mobile browser support.

### ISSUE THREAD

**Issue by bbigras** [toeverything/AFFiNE#251]
### 1~3 main use cases of the proposed feature

As someone with a phone, I want to access affine on mobile.

### what types of users can benefit from using your proposed feature

mobile users

### Additional context

It seems the UI is not optimized for mobile yet. 

I can't figure out how to close the left sidebar and the top menu is showing multiple stuff on top of each other.

![Screenshot_20220814-192722](https://user-images.githubusercontent.com/24027/184558842-24006f51-083d-402e-b3a2-15c96620f47e.png)

**Comment by tzhangchi** [comment]
Thank you for your suggestions, multi device adaptation improvement in our near future

**Comment by himself65** [comment]
new alpha have fixed this kind of issue

**Comment by psudo123** [comment]
Please reopen, it is still an issue, text goes off screen and everything is crammed
