### ISSUE TITLE
Windows is recognizing Affine as unrecognized app.

### ISSUE THREAD

**Issue by rounaksingh557** [toeverything/AFFiNE#2514]
<h2>When I try to install affine beta, Windows suggest me not to install this app.</h2>

![image](https://github.com/toeverything/AFFiNE/assets/75790404/e2b71230-12ba-4cc1-97d5-268d1f9fc70a)

<h3>Please chech this out 👇</h3>

1. [SmartScreen® Application Reputation – Building Reputation](https://learn.microsoft.com/en-us/archive/blogs/ie/smartscreen-application-reputation-building-reputation)

2. [Everything you need to know about Authenticode Code Signing](https://learn.microsoft.com/en-us/archive/blogs/ieinternals/everything-you-need-to-know-about-authenticode-code-signing)

**Comment by xell** [comment]
Closed as duplicated with former https://github.com/toeverything/AFFiNE/issues/1658 .
