### ISSUE TITLE
Missing authentication information in self-hosting blog post 

### ISSUE THREAD

**Issue by kbzowski** [toeverything/AFFiNE#2520]
### What happened?

I came across a post about Affine on your blog and became interested in the project: https://affine.pro/blog/a-new-docker-image-with-the-server-side-is-coming but apparently `docker pull ghcr.io/toeverything/affine:nightly-server-latest` requires authentication. There is no mention of this in the post content. I got: 

```
Error response from daemon: Head "https://ghcr.io/v2/toeverything/affine/manifests/nightly-server-latest": unauthorized
```

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ShortCipher5** [comment]
Please refer to the opening sentence of the article:

This article refers to a previously released version which is now out-dated, you may want to refer to the latest [AFFiNE Docker guide](https://affine.pro/blog/self-host-affine-with-docker).

We will look to archive this post.
