### ISSUE TITLE
syncUpdates error in workspace provider

### ISSUE THREAD

**Issue by m1911star** [toeverything/AFFiNE#2524]
### What happened?

<img width="976" alt="image" src="https://github.com/toeverything/AFFiNE/assets/4948120/18696853-d312-4fd7-af63-b3efd621b114">

maybe need some history data migration?

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by tzhangchi** [comment]
The bug had been fixed in the latest stable version.
