### ISSUE TITLE
AFFiNE Desktop Canary 0.6.0-canary.8​ (Custom Database Location)

### ISSUE THREAD

**Issue by purpleden** [toeverything/AFFiNE#2526]
### What happened?

Clicked "Customize" to choose workspace folder, and app errored. "Default" location works fine.

![image](https://github.com/toeverything/AFFiNE/assets/33729019/8670aadd-7271-4e04-a2de-a1b270288c7d)

Copied default location workspace files in to custom directory, Desktop client , error accessing custom location:
![image](https://github.com/toeverything/AFFiNE/assets/33729019/83daf705-bf7d-4879-a9ce-c3052426d2f4)

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
Should be fixed in #2491
