### ISSUE TITLE
Ugly fonts on Windows​

### ISSUE THREAD

**Issue by mon-jai** [toeverything/AFFiNE#2529]
### What happened?

The font stack Affine currently using is something like below:

```
Avenir Next,Poppins,apple-system,BlinkMacSystemFont,Helvetica Neue,Tahoma,PingFang SC,Microsoft Yahei,Arial,Hiragino Sans GB,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji
```

`Avenir Next` and `Poppins` isn't included as web font. `apple-system`, `BlinkMacSystemFont` and `Helvetica Neue` are not available on Windows. Therefore Chrome fallback to `Tahoma` when rendering English text, which is ugly.

It would be better if you either load `Poppins` as web font, or pick another fallback font (like Segoe UI, Arial etc.).

![image](https://github.com/toeverything/AFFiNE/assets/91261297/2237768f-6574-4973-a4d2-0e022301b043)

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Could you please share your windows and chrome version?

**Comment by mon-jai** [comment]
Windows 11 (Version 10.0.22000 Build 22000)

Chrome 115.0.5790.3

---

Seems that someone else encountered the bug too: #2530

The attached screenshot in the issue have `Tahoma` font rendered instead of `Avenir Next` or `Poppins`.

**Comment by mon-jai** [comment]
@Himself65 Any update on the matter?

**Comment by hwangdev97** [comment]
@mon-jai The next version iteration, we will optimize the style of the body text (including fonts, etc.) to enhance user experience.

**Comment by xell** [comment]
Closed as duplicated with https://github.com/toeverything/AFFiNE/issues/2134 .

**Comment by mon-jai** [comment]
@xell Tried the latest beta and canary. The issue still persists.

**Comment by xell** [comment]
> @xell Tried the latest beta (and canary). The issue still persists.

Hi mon-jai, please wait for https://github.com/toeverything/AFFiNE/issues/2134 to be completed in the current milestone before the first week of July.
