### ISSUE TITLE
AFFiNE Desktop Canary 0.6.0-canary.8​ (Move Folder)​

### ISSUE THREAD

**Issue by purpleden** [toeverything/AFFiNE#2530]
### What happened?

Under general, storage folder, pressing "Move Folder" and selecting a new folder throws up an error

![image](https://github.com/toeverything/AFFiNE/assets/33729019/e063bcde-2435-4694-a213-a74edf297a07)

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
Should be fixed in https://github.com/toeverything/AFFiNE/pull/2491
