### ISSUE TITLE
​AFFiNE Desktop Canary 0.6.0-canary.8​ (Delete Workspace)

### ISSUE THREAD

**Issue by purpleden** [toeverything/AFFiNE#2531]
### What happened?

Selecting "Delete" Under "Delete Workspace" Isn't deleting the workspace

![image](https://github.com/toeverything/AFFiNE/assets/33729019/732b008c-b3a8-4e39-8720-3bf068fac15e)

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
it might be a UI issue

**Comment by himself65** [comment]
related https://github.com/toeverything/AFFiNE/issues/2402

**Comment by tzhangchi** [comment]
The bug had been fixed in the latest stable version.
