### ISSUE TITLE
[bug]: pnpm install error

### ISSUE THREAD

**Issue by Gatsbyoo** [toeverything/AFFiNE#254]
### To Reproduce

pnpm install

### Screenshots

**I tried several times, but nothing worked.**

![image](https://user-images.githubusercontent.com/63992837/184585092-88a30820-04f5-4bd9-b9a1-37defca489c3.png)

PS E:\workspace\GitClone\AFFiNE> pnpm install
Scope: all 30 workspace projects
 WARN  GET https://registry.npmjs.org/lib0/-/lib0-0.2.52.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/ws/-/ws-8.8.1.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left. WARN  GET https://registry.npmjs.org/@mui/x-date-pickers-pro/-/x-date-pickers-pro-5.0.0-alpha.7.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.: 2.72 MB/5.95 MB
 WARN  GET https://registry.npmjs.org/@types/diff/-/diff-5.0.2.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left. registry.npmjs.org/firebase/9.9.2: 2.72 MB/5.95 MB
 WARN  GET https://registry.npmjs.org/@mui/x-date-pickers/-/x-date-pickers-5.0.0-alpha.7.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.se/9.9.2: 2.8 MB/5.95 MB
 WARN  GET https://registry.npmjs.org/@swc/core/-/core-1.2.210.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left. registry.npmjs.org/firebase/9.9.2: 4.09 MB/5.95 MB
 WARN  GET https://registry.npmjs.org/@types/react-dom/-/react-dom-18.0.6.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.pmjs.org/firebase/9.9.2: 4.35 MB/5.95 MB
 WARN  GET https://registry.npmjs.org/@types/react/-/react-18.0.14.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.gistry.npmjs.org/firebase/9.9.2: 4.61 MB/5.95 MB
 WARN  GET https://registry.npmjs.org/cz-customizable/-/cz-customizable-5.10.0.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.org/firebase/9.9.2: 4.87 MB/5.95 MBMB
 WARN  GET https://registry.npmjs.org/sql.js/-/sql.js-1.7.0.tgz error (ERR_STREAM_PREMATURE_CLOSE). Will retry in 10 seconds. 2 retries left.js.org/firebase/9.9.2: 5.86 MB/5.95 MB
apps/keck                                |  WARN  deprecated axios@0.19.2
Downloading registry.npmjs.org/firebase/9.9.2: 5.95 MB/5.95 MB, done
Downloading registry.npmjs.org/sql.js/1.7.0: 7.38 MB/7.38 MB, done
Downloading registry.npmjs.org/next/12.2.0: 6.4 MB/6.4 MB, done
Downloading registry.npmjs.org/typescript/4.7.4: 11.7 MB/11.7 MB, done
 WARN  GET https://registry.npmjs.org/@babel/helper-module-imports/-/helper-module-imports-7.18.6.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.0: 2.07 MB/9.28 MB
 WARN  GET https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.g/aws-sdk/2.1189.0: 2.07 MB/9.28 MB
apps/venus                               |  WARN  deprecated uuid@3.4.0
libs/components/editor-blocks            |  WARN  deprecated @codemirror/next@0.16.0
Downloading registry.npmjs.org/antd/4.21.5: 8.69 MB/8.69 MB, done
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
libs/components/editor-blocks            |  WARN  deprecated lezer@0.13.5
libs/components/editor-blocks            |  WARN  deprecated lezer-css@0.13.1
libs/components/editor-blocks            |  WARN  deprecated lezer-cpp@0.13.2
libs/components/editor-blocks            |  WARN  deprecated lezer-java@0.13.2
libs/components/editor-blocks            |  WARN  deprecated lezer-json@0.13.2
libs/components/editor-blocks            |  WARN  deprecated lezer-markdown@0.13.0
libs/components/editor-blocks            |  WARN  deprecated lezer-xml@0.13.4
libs/components/editor-blocks            |  WARN  deprecated lezer-python@0.13.7
libs/components/editor-blocks            |  WARN  deprecated lezer-tree@0.13.2
libs/components/editor-blocks            |  WARN  deprecated lezer-javascript@0.13.4
libs/components/editor-blocks            |  WARN  deprecated lezer-rust@0.13.1
 WARN  GET https://registry.npmjs.org/cssnano/-/cssnano-5.1.12.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left. registry.npmjs.org/aws-sdk/2.1189.0: 2.07 MB/9.28 MB
 WARN  GET https://registry.npmjs.org/semver/-/semver-7.3.7.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.ing registry.npmjs.org/aws-sdk/2.1189.0: 2.07 MB/9.28 MB
 WARN  GET https://registry.npmjs.org/react-universal-interface/-/react-universal-interface-0.6.2.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.0: 2.07 MB/9.28 MB
 WARN  GET https://registry.npmjs.org/throttle-debounce/-/throttle-debounce-3.0.1.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left./aws-sdk/2.1189.0: 2.07 MB/9.28 MB
 WARN  GET https://registry.npmjs.org/screenfull/-/screenfull-5.2.0.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.istry.npmjs.org/aws-sdk/2.1189.0: 2.07 MB/9.28 MB
 WARN  GET https://registry.npmjs.org/rc-textarea/-/rc-textarea-0.3.7.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.ry.npmjs.org/aws-sdk/2.1189.0: 2.07 MB/9.28 MB
Downloading registry.npmjs.org/@swc/core-win32-x64-msvc/1.2.210: 26.2 MB/26.2 MB, done
 WARN  GET https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.1189.0.tgz error (ERR_STREAM_PREMATURE_CLOSE). Will retry in 10 seconds. 2 retries left.g/aws-sdk/2.1189.0: 2.07 MB/9.28 MB
 WARN  GET https://registry.npmjs.org/jest-worker/-/jest-worker-27.5.1.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.org/aws-sdk/2.1189.0: 2.07 MB/9.28 MB
 WARN  GET https://registry.npmjs.org/commander/-/commander-2.20.3.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.gistry.npmjs.org/aws-sdk/2.1189.0: 2.07 MB/9.28 MB
 WARN  GET https://registry.npmjs.org/css-mediaquery/-/css-mediaquery-0.1.2.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.mjs.org/aws-sdk/2.1189.0: 2.07 MB/9.28 MB
 WARN  GET https://registry.npmjs.org/slice-ansi/-/slice-ansi-5.0.0.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.istry.npmjs.org/aws-sdk/2.1189.0: 2.07 MB/9.28 MB
apps/ligo-virgo                          |  WARN  deprecated core-js@3.6.5
libs/datasource/remote-kv                |  WARN  deprecated querystring@0.2.0
 WARN  GET https://registry.npmjs.org/gaxios/-/gaxios-4.3.3.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.ing registry.npmjs.org/aws-sdk/2.1189.0: 7.09 MB/9.28 MB
 WARN  GET https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.ws-sdk/2.1189.0: 7.09 MB/9.28 MB
Downloading registry.npmjs.org/@next/swc-win32-x64-msvc/12.2.0: 16.2 MB/16.2 MB, done
Downloading registry.npmjs.org/aws-sdk/2.1189.0: 9.28 MB/9.28 MB, done
 WARN  GET https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
 WARN  deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
 WARN  GET https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
libs/components/editor-blocks            |  WARN  deprecated lezer-html@0.13.6
 WARN  GET https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.2.0.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/estraverse/-/estraverse-5.3.0.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/get-stream/-/get-stream-4.1.0.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.0.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/cross-spawn/-/cross-spawn-6.0.5.tgz error (ETIMEDOUT). Will retry in 10 seconds WARN  GET https://registry.npmjs.org/responselike/-/responselike-1.0.2.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/defaults/-/defaults-1.0.3.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/range-parser/-/range-parser-1.2.1.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@jest/expect/-/expect-28.1.2.tgz error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/detect-newline/-/detect-newline-3.1.0.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/range-parser/-/range-parser-1.2.1.tgz error (ECONNRESET). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@jest/expect/-/expect-28.1.2.tgz error (ECONNRESET). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz error (ECONNRESET). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/clone/-/clone-1.0.4.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
Progress: resolved 2058, reused 0, downloaded 2033, added 0
TypeError: Cannot set property name of  which has only a getter
    at err (C:\snapshot\dist\pnpm.cjs)
    at runPnpm (C:\snapshot\dist\pnpm.cjs)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async C:\snapshot\dist\pnpm.cjs
PS E:\workspace\GitClone\AFFiNE> pnpm install
Scope: all 30 workspace projects
 WARN  GET https://registry.npmjs.org/@google-cloud%2Fstorage error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@google-cloud%2Ffirestore error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
libs/components/editor-blocks            |  WARN  deprecated @codemirror/next@0.16.0
apps/keck                                |  WARN  deprecated axios@0.19.2
libs/components/editor-blocks            |  WARN  deprecated lezer-cpp@0.13.2
libs/components/editor-blocks            |  WARN  deprecated lezer@0.13.5
libs/components/editor-blocks            |  WARN  deprecated lezer-css@0.13.1
libs/components/editor-blocks            |  WARN  deprecated lezer-html@0.13.6
libs/components/editor-blocks            |  WARN  deprecated lezer-javascript@0.13.4
libs/components/editor-blocks            |  WARN  deprecated lezer-json@0.13.2
libs/components/editor-blocks            |  WARN  deprecated lezer-python@0.13.7
libs/components/editor-blocks            |  WARN  deprecated lezer-markdown@0.13.0
libs/components/editor-blocks            |  WARN  deprecated lezer-java@0.13.2
libs/components/editor-blocks            |  WARN  deprecated lezer-rust@0.13.1
libs/components/editor-blocks            |  WARN  deprecated lezer-tree@0.13.2
libs/components/editor-blocks            |  WARN  deprecated lezer-xml@0.13.4
libs/datasource/remote-kv                |  WARN  deprecated querystring@0.2.0
 WARN  GET https://registry.npmjs.org/graceful-fs error (ENOTFOUND). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@types%2Fyauzl error (ENOTFOUND). Will retry in 10 seconds. 2 retries left.
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
 WARN  GET https://registry.npmjs.org/fsevents error (ENOTFOUND). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/errno error (ENOTFOUND). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/image-size error (ENOTFOUND). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/make-dir error (ENOTFOUND). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/mime error (ENOTFOUND). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/native-request error (ENOTFOUND). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/source-map error (ENOTFOUND). Will retry in 10 seconds. 2 retries left.
apps/ligo-virgo                          |  WARN  deprecated core-js@3.6.5
apps/venus                               |  WARN  deprecated uuid@3.4.0
 WARN  deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
 WARN  GET https://registry.npmjs.org/@lezer%2Fcommon error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/fsevents error (ECONNRESET). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/@types%2Fyauzl error (ECONNRESET). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/make-dir error (ETIMEDOUT). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.1.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.1.tgz error (ECONNRESET). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/fsevents: request to https://registry.npmjs.org/fsevents failed, reason: Client network socket disconnected before secure TLS connection was established
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/fsevents: request to https://registry.npmjs.org/fsevents failed, reason: Client network socket disconnected before secure TLS connection was established
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/fsevents: request to https://registry.npmjs.org/fsevents failed, reason: Client network socket disconnected before secure TLS connection was established
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/fsevents: request to https://registry.npmjs.org/fsevents failed, reason: Client network socket disconnected before secure TLS connection was established
Packages: +2077
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: E:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 2067, reused 2033, downloaded 9, added 2077, done
 WARN  Local dependency not found at E:/workspace/GitClone/AFFiNE/libs/components/editor-blocks/@codemirror/next/keymap
node_modules/.pnpm/core-js-pure@3.23.3/node_modules/core-js-pure: Running postinstall script, done in 307ms
node_modules/.pnpm/core-js@3.23.3/node_modules/core-js: Running postinstall script, done in 250ms
node_modules/.pnpm/core-js@3.6.5/node_modules/core-js: Running postinstall script, done in 201ms
node_modules/.pnpm/@parcel+watcher@2.0.4/node_modules/@parcel/watcher: Running install script, done in 556ms
node_modules/.pnpm/classic-level@1.2.0/node_modules/classic-level: Running install script, done in 811ms
node_modules/.pnpm/optipng-bin@7.0.1/node_modules/optipng-bin: Running postinstall script, failed in 11.3s
.../node_modules/optipng-bin postinstall$ node lib/install.js
│ getaddrinfo ENOENT raw.githubusercontent.com
│ compiling from source
│ optipng pre-build test failed
│ Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "./configure --with-system-zlib --prefix="E:\workspace\G
│ '.' is not recognized as an internal or external command,
│ operable program or batch file.
│     at E:\workspace\GitClone\AFFiNE\node_modules\.pnpm\execa@0.7.0\node_modules\execa\index.js:231:11
│     at runMicrotasks (<anonymous>)
│     at processTicksAndRejections (node:internal/process/task_queues:96:5)
│     at async Promise.all (index 0)
└─ Failed in 11.3s
node_modules/.pnpm/protobufjs@6.11.3/node_modules/protobufjs: Running postinstall script, done in 564ms
 ELIFECYCLE  Command failed with exit code 1.
PS E:\workspace\GitClone\AFFiNE> pnpm install
Scope: all 30 workspace projects
libs/components/editor-blocks            |  WARN  deprecated @codemirror/next@0.16.0
apps/keck                                |  WARN  deprecated axios@0.19.2
libs/components/editor-blocks            |  WARN  deprecated lezer-cpp@0.13.2
libs/components/editor-blocks            |  WARN  deprecated lezer-css@0.13.1
libs/components/editor-blocks            |  WARN  deprecated lezer-html@0.13.6
libs/components/editor-blocks            |  WARN  deprecated lezer@0.13.5
libs/components/editor-blocks            |  WARN  deprecated lezer-java@0.13.2
libs/components/editor-blocks            |  WARN  deprecated lezer-javascript@0.13.4
libs/components/editor-blocks            |  WARN  deprecated lezer-json@0.13.2
libs/components/editor-blocks            |  WARN  deprecated lezer-markdown@0.13.0
libs/components/editor-blocks            |  WARN  deprecated lezer-rust@0.13.1
libs/components/editor-blocks            |  WARN  deprecated lezer-xml@0.13.4
libs/components/editor-blocks            |  WARN  deprecated lezer-python@0.13.7
libs/components/editor-blocks            |  WARN  deprecated lezer-tree@0.13.2
libs/datasource/remote-kv                |  WARN  deprecated querystring@0.2.0
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
apps/ligo-virgo                          |  WARN  deprecated core-js@3.6.5
apps/venus                               |  WARN  deprecated uuid@3.4.0
 WARN  deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
 WARN  GET https://registry.npmjs.org/@google-cloud%2Ffirestore error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
Packages: +2077
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2067, reused 2042, downloaded 0, added 0, done
 WARN  Local dependency not found at E:/workspace/GitClone/AFFiNE/libs/components/editor-blocks/@codemirror/next/keymap
node_modules/.pnpm/optipng-bin@7.0.1/node_modules/optipng-bin: Running postinstall script, failed in 10.1s
.../node_modules/optipng-bin postinstall$ node lib/install.js
│ getaddrinfo ENOENT raw.githubusercontent.com
│ compiling from source
│ optipng pre-build test failed
│ Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "./configure --with-system-zlib --prefix="E:\workspace\G
│ '.' is not recognized as an internal or external command,
│ operable program or batch file.
│     at E:\workspace\GitClone\AFFiNE\node_modules\.pnpm\execa@0.7.0\node_modules\execa\index.js:231:11
│     at runMicrotasks (<anonymous>)
│     at processTicksAndRejections (node:internal/process/task_queues:96:5)
│     at async Promise.all (index 0)
└─ Failed in 10.1s
 ELIFECYCLE  Command failed with exit code 1.
PS E:\workspace\GitClone\AFFiNE>

### Platform

win10 64

**Comment by lawvs** [comment]
The dependency of `imagemin-optipng` requires to build, considering changing to other image minimizer implementation? @darkskygit

**Comment by darkskygit** [comment]
at present, some dependencies only support installation on unix like systems, please try to use it under wsl, please ensure that the network is smooth
