### ISSUE TITLE
AFFiNE Desktop 0.7.0-canary.0​ (Show Version Somewhere​)

### ISSUE THREAD

**Issue by purpleden** [toeverything/AFFiNE#2552]
### What happened?

Is it possible the desktop client can show the version number on either of these screens?

![image](https://github.com/toeverything/AFFiNE/assets/33729019/118f3021-3222-49a9-ae2f-6e7923f5125f)

![image](https://github.com/toeverything/AFFiNE/assets/33729019/86fe5432-8796-44d6-bf3a-97883623fc6b)

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
We will add a separate Settings Page and include specific version number explanations. Progress on this can be tracked in this issue https://github.com/toeverything/AFFiNE/issues/2155
Will it solve your problem? @purpleden

**Comment by houjoe0829** [comment]
> > We will add a separate Settings Page and include specific version number explanations. Progress on this can be tracked in this issue #2155 Will it solve your problem? @purpleden
> 
> That will work great - is there any chance we could see the log file in the settings page too?

Sorry, I missed your message. Currently, there is no entry for log files. We have taken note of it and will consider this product requirement in the future.
