### ISSUE TITLE
Allow linking to other pages​

### ISSUE THREAD

**Issue by andersmmg** [toeverything/AFFiNE#2556]
### Description

A command for creating links to other AFFiNE pages within my workspace.

### Use case

For documents referencing others

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SolarDesalination** [comment]
You should be able to do this by type "[[" - it will create an @ symbol and you can type a related page, or create a new page.

**Comment by andersmmg** [comment]
Are you saying this is a current feature or is that a suggestion for how it should work? I've tried that but it didn't work so I made this post

**Comment by SolarDesalination** [comment]
It works for me in the latest beta version. What version are you using?

**Comment by andersmmg** [comment]
Ah okay I was using stable at the time, it does seem to work in beta though it's extremely laggy for me atm
