### ISSUE TITLE
Font color problem in demo page​

### ISSUE THREAD

**Issue by Ross249** [toeverything/AFFiNE#2564]
### Description

I think the colour of the feedback button text when I hover my cursor on it could be better in black. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by xell** [comment]
Thank you for the suggestion. Could you append a screenshot for more precise explanation?

**Comment by Ross249** [comment]
[![p9jCQBR.jpg](https://s1.ax1x.com/2023/05/30/p9jCQBR.jpg)](https://imgse.com/i/p9jCQBR)

The feedback button has the same problem as the above picture

**Comment by xell** [comment]
Oh. It seems you're using web version of AFFiNE. Could you tell me the link (or links, because we have several online versions)? Thank you.

**Comment by Ross249** [comment]
https://app.affine.pro/workspace/themN9te9T/all

I find this issue when I click try demo online and switch to dark mode.

**Comment by xell** [comment]
Thank you very much for helping us locating the bug. We'll fix it in the next major version which will offer full experience of cloud service.

**Comment by JimmFly** [comment]
This issue has been resolved in the latest version of AFFiNE, thank you for your feedback.
