### ISSUE TITLE
[feature]: Add PWA function

### ISSUE THREAD

**Issue by mst8222** [toeverything/AFFiNE#257]
### 1~3 main use cases of the proposed feature

Make it more like a desktop application.
Send shortcut to desktop, and open it in a browser container.

### Ideas for solution

PWA(Progressive Web App)

### what types of users can benefit from using your proposed feature

more like open the shotcut than type a url to open a product users

**Comment by tzhangchi** [comment]
If some contributor can work it，we will be appreciate it
