### ISSUE TITLE
​Monitor the Obsidian vault, unidirectionally sync MD files to Affine in real-time.

### ISSUE THREAD

**Issue by aiyou9** [toeverything/AFFiNE#2584]
### Description

Alternatively, support user-defined monitoring of specific pages, such as diary entries and task lists, in MD files, develop filters to read special formats such as task and callout.

### Use case

Users who use md format, they might enjoy using a whiteboard with pen drawing support in Affine. in obsidian and logseq, a plugin named samepage, which is sync pages between them

### Anything else?

https://samepage.network

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xell** [comment]
Thank you for this suggestion. We agree that auto sync with main stream note-taking / pkm apps is very valuable. However, due to the situation of development, this will not be available in the near future. So I closed this issue for now and will reopen it if the time comes.
