### ISSUE TITLE
Unable to click on the title to open the content in All Pages

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2595]
Unable to open documents in All Pages by clicking on them, as it triggers drag and drop instead. It is recommended to disable drag and drop.

https://github.com/toeverything/AFFiNE/assets/22443345/13b0d52f-2ce8-4d8c-aa76-41aae19ed13a

**Comment by himself65** [comment]
Fixed in https://github.com/toeverything/AFFiNE/pull/2621
