### ISSUE TITLE
​The top border of the window needs to be able to be dragged and moved

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#2634]
### What happened?

The current drag and drop area only includes the top bar but not the border. The expected result is that both the top bar and border should be included for dragging and moving.

![shot-2023-06-01-09 36 36](https://github.com/toeverything/AFFiNE/assets/24713927/25944ca9-54e0-4ecf-a55c-ca73ca3452fd)

### Version

macOS ARM 64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
Should already been fixed.
