### ISSUE TITLE
​All pages: some UI issues need to be fixed.

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#2635]
### What happened?

# Button Style
- [x] Filter button: show this color when the mouse hover/activate, and normal "white" ( when there's no hover

Currently, it is not correct: 
<img width="415" alt="shot-2023-06-01-09 51 03@2x" src="https://github.com/toeverything/AFFiNE/assets/24713927/8c70c8a8-4c82-4f3c-bffa-37620708b7ce">

The correct one should look like 👇 
<img width="314" alt="shot-2023-06-01-09 50 39@2x" src="https://github.com/toeverything/AFFiNE/assets/24713927/4e29c44b-2f45-4f61-821a-db7c58aeb0a1">

# List Item

- [x] list item: for subtitle, use `textSecondaryColor`

<img width="565" alt="shot-2023-06-01-09 56 06@2x" src="https://github.com/toeverything/AFFiNE/assets/24713927/c5f253e2-29c0-4857-bf60-bd55b004aa3a">

# Filter Item
- [x] the filter rule cell, as we have discussed before, there is still a lot of work to be done.

<img width="631" alt="shot-2023-06-01-09 56 30@2x" src="https://github.com/toeverything/AFFiNE/assets/24713927/6c560bae-11af-4ab9-825c-a91db2086ca9">

### Version

macOS ARM 64

**Comment by xell** [comment]
Due to the lack of a proper date picker component, I put this issue into next milestone.

**Comment by JimmFly** [comment]
Completed on  https://github.com/toeverything/AFFiNE/pull/2644
