### ISSUE TITLE
Support editing the title directly in the top bar

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#2645]

**Comment by danielchim** [comment]
![chrome_8KmEi6EMaK](https://github.com/toeverything/AFFiNE/assets/12156547/a9776e89-3189-482f-a454-37c4d3cd7222)

This is the initial implementation, if there's a design coming up later feel free to let me know.

**Comment by hwangdev97** [comment]
updated the design:

![shot-2023-08-07-16 29 36@2x](https://github.com/toeverything/AFFiNE/assets/24713927/ab1d1b7a-4ca4-44d9-94f1-43788a051cf9)

I think there is no need to display the save icon and other interfering icons.

**Comment by xell** [comment]
Supplementary design layout as shown in the new titlebar:

![shot-2023-08-07-16 29 36@2x](https://github.com/toeverything/AFFiNE/assets/24713927/3f0e43d2-c97d-41cb-ace0-0d11cebadd43)

**Comment by hwangdev97** [comment]
And automatically confirm the renaming status after losing focus

**Comment by QiShaoXuan** [comment]
Fixed in https://github.com/toeverything/AFFiNE/pull/3755
