### ISSUE TITLE
Optimize the display of shortcut key instructions

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2649]
Refer to [internal doc](https://toeverything.feishu.cn/wiki/Aop6wmBAyiVLSzkkyRXc6UT0nfd)

- Use the same style, but show different shortcut key contents in Page, Edgeless, and non-editing areas(General).
- Add a quick display mechanism: holding down ⌘/Ctrl for 2 seconds will show a shortcut menu on the right side, and releasing it will automatically collapse the menu.

**Comment by QiShaoXuan** [comment]
fixed in #2834
