### ISSUE TITLE
New design of deleted page

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#2669]
The Trash page design has been optimized: 
The critical differences: 
1. page or edgeless should not be editable (read-only). blockhub and edgeless toolbar should be invisible.
2. move the "restore button" and "delete permanently" buttons from top to bottom
3. deleted page and edgeless bookmark added
[figma link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=4552-115347&t=CUwRd6eDnoaZ8IV7-4)

**Comment by xell** [comment]
In technical sense this issue is preceded by https://github.com/toeverything/blocksuite/issues/3597 .
