### ISSUE TITLE
[bug]: throw error when undo after removing link.

### ISSUE THREAD

**Issue by chenmoonmo** [toeverything/AFFiNE#267]
### Describe the bug

throw error when undo after removing link

### To Reproduce

1. paste a link
2. remove link url
3. undo

### Screenshots

<img width="892" alt="image" src="https://user-images.githubusercontent.com/36295999/184811619-7c7761b6-8fd0-4477-ae03-d9a59e57455d.png">

### Platform

macOS M1

### Browser

Chrome cancary 106.0.5225.0

**Comment by tzhangchi** [comment]
@DiamondThree

**Comment by tzhangchi** [comment]
Thank you for your feedback ,we have fixed it, you can  try it
