### ISSUE TITLE
add workspace may not be able to load DB correctly​

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#2671]
### What happened?

When adding a exported workspace db file, the db contents are not being loaded. Sometimes there will only be the default "preload" page. 

### Version

macOS ARM 64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SolarDesalination** [comment]
I also have this issue. When I load my old storage.db file into the Affine.pro stable version on Linux, it doesn't show the underlying data. It only shows the default page. I know that the data is there because the DB is 7mb and the default DB is less.
