### ISSUE TITLE
Style - easy fix: ​Headings are too similar - I cannot discern them

### ISSUE THREAD

**Issue by AlessioGr** [toeverything/AFFiNE#2676]
### Description

![Screenshot 2023-06-03 at 17 07 07@2x](https://github.com/toeverything/AFFiNE/assets/70709113/1800af8e-909d-4c60-a3c3-96884a76a53b)

Especially for Heading 2 and 3 - I see barely any difference visually.

Another example:
![Screenshot 2023-06-03 at 17 10 31@2x](https://github.com/toeverything/AFFiNE/assets/70709113/a91b6afe-874f-4bc5-8e02-e746b1dbd1bb)

You wouldn't know "Headset" is a H3 and "Plans" a H2.

They should optimally be so visually different, that you really notice Heading 3 being _part_ of / _lower level_ than Heading 2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Thank you for your feedback, we do have a plan to improve the font settings. CC @xell you can take a look.

**Comment by xell** [comment]
Thank you for pointing out this, which will be part of our plan of improvement of fonts and typesetting in Milestone 0.7.  Please stay tuned.

**Comment by xell** [comment]
Closed as duplicated with https://github.com/toeverything/AFFiNE/issues/2134 .

**Comment by xell** [comment]
We will keep on adjusting these in milestone 0.8 https://github.com/toeverything/blocksuite/issues/3400

**Comment by xell** [comment]
It's done in https://github.com/toeverything/blocksuite/issues/3495
