### ISSUE TITLE
Support exporting `.affine` file in app.affine.pro

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#2684]
### Description

Allow exporting (and importing) the `.affine` workspace file in https://app.affine.pro would be a great step towards the local-first pattern. This is similar to what excalidraw and tldraw supports in their main site.

This was considered to be added into the 0.7 scope but the priority depends.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
There is a gist to automate the workflow, but the output is not yet a db file.
https://gist.github.com/pengx17/6e51885d892b0ce2a29e5f5c0e2d84fe

**Comment by doodlewind** [comment]
This issue can be closed since we've shipped `.affine` in 0.6.0.
