### ISSUE TITLE
[bug]: Use the Chinese input method to enter in the input box to reproduce.

### ISSUE THREAD

**Issue by ralphsun73221** [toeverything/AFFiNE#269]
### Describe the bug

Core Token Desktop Scale Mobile Scale font-size-50 11 px 13 px font-size-75 12 px 15 px font-size-100 14 px 17 px font-size-200 16 px 19 px font-size-300 18 px 22 px font-size-400 20 px 24 px font-size-500 22 px 27 px font-size-600 25 px 31 px font-size-700 28 px 34 px font-size-800 32 px 39 px font-size-900 36 px 44 px font-size-1000 40 px 49 px

### To Reproduce

Use the Chinese input method to enter in the input box to reproduce.

### Screenshots

![CleanShot 2022-08-16 at 17 34 05](https://user-images.githubusercontent.com/26322077/184847976-00c5a083-f9f2-4a14-af43-36ac6d3b7973.gif)

### Platform

macOS 12.5

**Comment by alt1o** [comment]
Please visit livedemo: https://livedemo.affine.pro/ , and try if can reproduce this bug? i couldnot reproduce this bug. Maybe fix it in livedemo.

**Comment by Austaras** [comment]
Three requirements to trigger this issue:
1. On Firefox
2. At the start of an empty block
3. Use Chinese IME
