### ISSUE TITLE
All Pages | add top-right button UI

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#2695]
Please add this UI component in order to align with the requirements on the product side:

- layout button
- sort button

![shot-2023-06-06-16 17 58@2x](https://github.com/toeverything/AFFiNE/assets/24713927/d980cc60-1c2e-4733-8a02-59400905c8f2)

![shot-2023-06-06-16 19 51@2x](https://github.com/toeverything/AFFiNE/assets/24713927/0e403ed6-ad81-43a9-bcdc-f357d5ab1b9e)

Card view is not available at the moment, so when you click, a toast message will pop up at the bottom saying "coming soon"：

 
![image](https://github.com/toeverything/AFFiNE/assets/24713927/9b7d536d-7321-48b0-a95a-1bac28c3a2d7)

**Comment by akhil27styles** [comment]
is this issue open? can I work on

**Comment by himself65** [comment]
> is this issue open? can I work on

Yes, you are welcome on this
