### ISSUE TITLE
typeform url malformed​

### ISSUE THREAD

**Issue by cmpscabral** [toeverything/AFFiNE#2701]
### What happened?

After signing up for cloud/copilot/... notification the link to download point to https//affine.pro/download (there's a missing colon)

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Are you referring to a notification or message similar to this? If so, we have checked and confirmed that the link is correct. If possible, could you please provide a screenshot of the issue you are seeing? Thank you.
![CleanShot 2023-06-07 at 22 24 41@2x](https://github.com/toeverything/AFFiNE/assets/22443345/c22a4b3d-cf9c-4ea5-8c0e-4500e785c847)
