### ISSUE TITLE
Popup tooltip text color in light mode is unreadable​

### ISSUE THREAD

**Issue by Nikko-Adrian-Pacleb** [toeverything/AFFiNE#2702]
### What happened?

When the button for enabling affine cloud is hovered, the popup's text color blended with the background

Image:
![image](https://github.com/toeverything/AFFiNE/assets/93676412/d2f0ef5b-d992-4692-b5eb-e087bd7c5436)

### Version

app.affine.pro

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Nikko-Adrian-Pacleb** [comment]
Hi! I just started using affine today and so far its been great. I am currently new in open source but if in any way I could help, I would like to help contribute. Thank you

**Comment by himself65** [comment]
Could you please try our desktop version? app.affine.pro has delayed for 2 months, we are going to use latest version in next month after we refactor the server code

**Comment by Nikko-Adrian-Pacleb** [comment]
Got it will try canary
