### ISSUE TITLE
​文档中看不到目录结构

### ISSUE THREAD

**Issue by GuuoJuun** [toeverything/AFFiNE#2729]
### Description

在文档中，希望自动按heading生成目录，方便点击定位跳转，这个目录希望可以固定，notion有，但是它不固定，腾讯文档就很好

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Duplicated with https://github.com/toeverything/AFFiNE/issues/2728
