### ISSUE TITLE
[bug]: Problems with whiteboard operation（Twitter user submit）

### ISSUE THREAD

**Issue by fyZheng07** [toeverything/AFFiNE#274]
### To Reproduce

Steps：
1. change from paper to edgeless
2. use a pencil  and make some lines
3. use the eraser to delete these lines
4. mouse click the group block
5. then appear error

### Screenshots

Uploading 屏幕录制2022-08-17 11.34.03.mov…
![Uploading twitter bug.png…]()

**Comment by lawvs** [comment]
Using the eraser to erase a group is an expected behavior, but we will optimize the mouse display style.
