### ISSUE TITLE
Reduce step to link back .​

### ISSUE THREAD

**Issue by AltairOA** [toeverything/AFFiNE#2751]
### Description

Wish could add feature that when there is only one page to link back, just straight link back instead of clicking the page after we click the linkback button.

### Use case

Who don't wanna more step to link back may need the feature.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
I need to confirm that you mean it's better to display a page directly if there are only a few pages referenced, such as only one, in this specific case you're referring to, right?

![CleanShot 2023-06-11 at 20 44 34@2x](https://github.com/toeverything/AFFiNE/assets/22443345/17b4bb5b-9598-4856-b74f-1ae894717613)

**Comment by AltairOA** [comment]
That's what I mean. Here you go, bro.

**Comment by joebeijing** [comment]
Thank you for your response. This will ultimately be evaluated by our design team.  CC @xell

**Comment by xell** [comment]
Thanks for the suggestion. However, it's not a must-have feature so we'll realize it in the future and polish the UI of this part.
