### ISSUE TITLE
Subdoc support

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#2763]
Blocksuite has upgraded to the next version for sub-doc support. We need to port our providers to the latest API

**Comment by LIHAQI** [comment]
同求此功能

**Comment by himself65** [comment]
We have supported the subdoc feature on the latest code, indexeddb, and broadcast channel providers.

Closing

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/pull/2774
https://github.com/toeverything/AFFiNE/pull/2816
https://github.com/toeverything/AFFiNE/pull/2881
