### ISSUE TITLE
Add loading process for upgrading data structure

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2771]
1. Only available during data structure upgrade or migration.
2. No other oactions can be performed on the client during the loading process.
3. Display the prompt "We are upgrading your data and it may take some time ……"
4. It appears between opening the client and being able to see the content in the Workspace.

It is possible to consider adjusting the current loading animation of the client to achieve a similar effect while maintaining consistency.

**Comment by xell** [comment]
There's no need for the prompt for this process, which is invisible to the end users.
