### ISSUE TITLE
The area for triggering the exit button in the upper right corner during image preview mode is very small

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2782]
https://github.com/toeverything/AFFiNE/assets/22443345/ec53ff19-5c53-4d5a-a7a1-e21739da8f12

**Comment by danielchim** [comment]
On my device I can close the button without any issues regardless of the area. Is it possible to let me know what device you're running when encounter this bug?

**Comment by joebeijing** [comment]
AFFiNE internal version
<img width="300" alt="CleanShot 2023-06-15 at 13 11 35@2x" src="https://github.com/toeverything/AFFiNE/assets/22443345/c63d04e5-d2c1-42a2-9965-b76087447276">

Info of computer
![CleanShot 2023-06-15 at 13 12 11@2x](https://github.com/toeverything/AFFiNE/assets/22443345/bc3a31c3-72ed-402c-a323-03792b4a2eda)

**Comment by danielchim** [comment]
A PR was made in an attempt to fix this issue. Please let me know if the bug still persist after this PR.
