### ISSUE TITLE
In image preview mode, hope to support the ability to automatically set the image scaling to 100% after clicking on the scale value

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2791]
It can be based on the current effect on the Edgeless whiteboard to maintain consistency.

**Comment by danielchim** [comment]
Will be available in the next PR.

**Comment by danielchim** [comment]
![chrome_EEzWYOZ8c1](https://github.com/toeverything/AFFiNE/assets/12156547/50512a15-2cb1-457f-a05c-c453030c0085)

When click on the scale value, it will be set to 100%

Also fixed the issue on #2369
