### ISSUE TITLE
Image preview requires some attention to detail in order to improve 

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#2807]
The user interface for the image preview requires some attention to detail in order to improve:

- [x] Move the close button to the top right corner with a margin of top 38px  and  right 38px  .
- [x] Do not show caption in the preview mode and ensure the image is always centered.
- [x] Toolbar height is 44px.
- [x] Make the toolbar always visible on the bottom .
- [x] Implement the hover effect on toolbar buttons by changing their background color with `hoverColor`.
- [x] Add transition with easy-in-out when open / close preview mode.

**Comment by danielchim** [comment]
![chrome_e5wUgoz8vt](https://github.com/toeverything/AFFiNE/assets/12156547/da793695-a046-4166-85f7-c38b9bb74dc4)

**Comment by danielchim** [comment]
Available in [0.7.0-canary.19](https://github.com/toeverything/AFFiNE/releases/tag/v0.7.0-canary.19)
