### ISSUE TITLE
​Subpage Rating

### ISSUE THREAD

**Issue by LIHAQI** [toeverything/AFFiNE#2827]
### Description

  现在canary版本可以支持子页面功能，但是如果子页面加入过多，就很容易和父页面混淆，能不能像notion一样做个分级，把子页面放在父页面下。如图。
AFFiNE：
   ![image](https://github.com/toeverything/AFFiNE/assets/57976650/947e6009-4cfc-4745-b1e0-ed9f20f47e22)

Notion：
   ![image](https://github.com/toeverything/AFFiNE/assets/57976650/00f3aeb0-f78b-4011-828f-75bd278fe02b)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
非常感谢。
目前在 All pages 页面暂时还没有这个计划，我们会后期考虑一下并留意类似的反馈。不过，在侧边栏中，如果加入了 Favorites 之后，会在侧边栏显示页面的 Linked Page，可以看看。
<img width="256" alt="CleanShot 2023-07-03 at 11 12 11@2x" src="https://github.com/toeverything/AFFiNE/assets/22443345/b9a8e3b4-efeb-422d-aa42-6e01eecb3c9e">

**Comment by est7** [comment]
我们需要它

**Comment by houjoe0829** [comment]
Currently, there is no plan to support subpages, only linked pages. We will temporarily close this issue. If there are any further questions or changes, please feel free to reopen it.
