### ISSUE TITLE
It takes a long time to open AFFiNE and start operations

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#2829]
<img width="1228" alt="CleanShot 2023-06-20 at 14 44 09@2x" src="https://github.com/toeverything/AFFiNE/assets/22443345/0d3decb1-3072-4617-9a00-0a31677e0f8e">

**Comment by himself65** [comment]
Seems like y-indexeddb also make lack the performance. I'm thinking to move the DB operation into web worker

**Comment by himself65** [comment]
I think I found the issue, open a pr later
