### ISSUE TITLE
AFFiNE data & logic & UI regression

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#2841]
Since https://github.com/toeverything/AFFiNE/pull/2833, we upgrade blocksuite to subdocument support.

```[tasklist]
### Desktop
- [ ] #2798
- [x] Blob syncing
- [x] Export/Import
```

```[tasklist]
### AFFiNE Cloud
- [x] WebSocket provider
- [x] UI
```

```[tasklist]
### Web
- [x] Data migration
- [ ] https://github.com/toeverything/AFFiNE/issues/3029
```

**Comment by mon-jai** [comment]
The "Noise background on the sidebar" isn't working on Windows because of #2303.

The `environment.isMacOs` condition should be dropped.

https://github.com/toeverything/AFFiNE/blob/fe895905bdba44ff6858d835864fc2f33c799088/packages/component/src/components/workspace/index.tsx#L20-21

**Comment by himself65** [comment]
> The "Noise background on the sidebar" option isn't working on Windows because of #2303.
> 
> The `environment.isMacOs` condition should be dropped.
> 
> https://github.com/toeverything/AFFiNE/blob/fe895905bdba44ff6858d835864fc2f33c799088/packages/component/src/components/workspace/index.tsx#L20-L21

could you please open a pr?

**Comment by mon-jai** [comment]
Here you are: #3107

**Comment by himself65** [comment]
most of the features have been implemented, closing
