### ISSUE TITLE
Cannot paste URL   to bookmark

### ISSUE THREAD

**Issue by wuqi** [toeverything/AFFiNE#2845]
### What happened?

ctrl+v or middle mouse button no use when open a bookmark

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by QiShaoXuan** [comment]
Do this issue want convert url to bookmark block automaticly after pasted?

**Comment by joebeijing** [comment]
Just to confirm, are you looking to copy the original link of this bookmark? @wuqi

**Comment by wuqi** [comment]
> 

![image](https://github.com/toeverything/AFFiNE/assets/1532967/dd09efa1-b046-4928-90b3-99715429effd)
I want to paste some link to the bookmark's input box,like in the picture,but this seems only accecpt keyboard input

And sometimes paste html link looks wired in text box,it sometimes only paste the link title ,not the link,
![image](https://github.com/toeverything/AFFiNE/assets/1532967/8c70a342-3e80-46d4-b69d-7e30875f93d0)

**Comment by joebeijing** [comment]
Sorry, we have not been able to reproduce this issue on the AFFiNE Mac and Windows clients. Could you please download the latest version from this website and see if the issue still persists? @wuqi

**Comment by wuqi** [comment]
> Sorry, we have not been able to reproduce this issue on the AFFiNE Mac and Windows clients. Could you please download the latest version from this website and see if the issue still persists? @wuqi

![image](https://github.com/toeverything/AFFiNE/assets/1532967/65699335-6a86-423e-b7ee-31d2d52bbbd1)
This maybe the Edge's problem,I changed to firefox and this disappear

But the latest version I test the bookmark can't paste url still exists,on windows 10,edge and firefox both tested,can't paste into bookmart's inputbox.like the gif below
![1](https://github.com/toeverything/AFFiNE/assets/1532967/e274bc0b-6d01-4d01-a25a-bf0905fa17dc)

**Comment by joebeijing** [comment]
I can now reproduce this issue. After adding a Bookmark Block to the Note component in Edgeless mode, it is not possible to copy and paste any content in the pop-up window. CC @QiShaoXuan

**Comment by QiShaoXuan** [comment]
fixed in https://github.com/toeverything/blocksuite/pull/3399
