### ISSUE TITLE
No hover state in the new scrollbar

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#2857]
design:

![6Y58WeO0Or](https://github.com/toeverything/AFFiNE/assets/132558/77e31db6-9d78-4d63-bd8c-45c396605dc9)

related with https://github.com/toeverything/AFFiNE/issues/2793

**Comment by doodlewind** [comment]
Auto hidden scrollbar is not the native behavior on windows, and adjusting this may affect BlockSuite viewport. If this requires non-trivial CSS tweaking, I don't think we should support non-native scrollbar in BlockSuite for the moment.

**Comment by xell** [comment]
It seems automatic scrollbar hiding in Windows is a standard function both for 10 and 11, c.f. https://www.itechtics.com/show-hide-scrollbars/?expand_article=1
