### ISSUE TITLE
[bug]:  Edgeless bug in iPad

### ISSUE THREAD

**Issue by fyZheng07** [toeverything/AFFiNE#291]
### To Reproduce

Steps：
1. open AFFiNE on your iPad
2. transform to edgeless mode
3. the bug appears: the mouse status is always in "HandDraw"

### Screenshots

![image](https://user-images.githubusercontent.com/63830919/185364395-e8200add-0c9f-4872-b860-43a858428249.png)

**Comment by Austaras** [comment]
Fixed in #290
