### ISSUE TITLE
[improvement]: Dependency on chrome(ium)?

### ISSUE THREAD

**Issue by natrius** [toeverything/AFFiNE#292]
### 1~3 main use cases of the proposed improvement

Why is there a (heavy?) dependency for chrom(ium?). I get that probably a lot of users are Chrome users anyway but there are still pretty much people out there using firefox.
What functions am i missing when using firefox?

### what types of users can benefit from using your proposed improvement

Firefox users

### Additional context

It feels like we are back in the early 2000 with all the "Website optimized for Internet Explorer" or "Netscape" or whatever.

**Comment by darkskygit** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API

**Comment by natrius** [comment]
Why not using https://nodejs.org/en/ for writing files? Or does that not work as well? Could not open the Mozilla Firefox Bugtracker right now - but is there a feature request for that already? (Will look up later)

**Comment by darkskygit** [comment]
nodejs focus on backend, AFFiNE now is a frontend software, you can learn the difference between these concepts from here: https://en.wikipedia.org/wiki/Frontend_and_backend
