### ISSUE TITLE
[improvement]: Question about svgOptimize

### ISSUE THREAD

**Issue by wangyu-1999** [toeverything/AFFiNE#295]
### 1~3 main use cases of the proposed improvement

I find ./tools/executors/svgOptimize is not be used by other funcs or modules. Should it be removed?

### Ideas for solution

remove this module

### what types of users can benefit from using your proposed improvement

developers

**Comment by alt1o** [comment]
Ok, i see... Indeed not in use, can you submit a pr, help us to fix it?

**Comment by wangyu-1999** [comment]
> Ok, i see... Indeed not in use, can you submit a pr, help us to fix it?

👌
