### ISSUE TITLE
Feature Request: doc outline support

### ISSUE THREAD

**Issue by hongquW** [toeverything/AFFiNE#2955]
### Description

Page mode, Is there a way to display the doc outline?​

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Currently, we don't have such support, but I think it's possible to add it to a plugin that displays the outline on the left panel

**Comment by himself65** [comment]
Just copied an outline screenshot from google docs.

![image](https://github.com/toeverything/AFFiNE/assets/14026360/d948fa2d-3b98-4779-b0b0-a8e4096d7425)

**Comment by joebeijing** [comment]
Duplicated with https://github.com/toeverything/AFFiNE/issues/1557
