### ISSUE TITLE
Flagged as a virus in both (Windows),(Virustotal)

### ISSUE THREAD

**Issue by DaEpicR** [toeverything/AFFiNE#2958]
### What happened?

**Describe the maybe a bug**
After downloading the stable version for windows the security flagged the app as a virus (trojan)
**To Reproduce**
1. Go to the exe
2. Click on it
3. boom flagged

virus total also get 3/63 
https://www.virustotal.com/gui/file-analysis/NWJhNDdkNDc1ZjliYzdmN2JhYTIxYjJmNTNjNjcyNGU6MTY4ODIyOTQ3MA==

is it a false detection by both virustotal and windows security ?

**Comment by himself65** [comment]
This is a known issue because we haven't gotten the Windows signature certificate. This could be fixed in 2 weeks.

/cc @Brooooooklyn

**Comment by DaEpicR** [comment]
> 

Oh i see , thank you and everyone help this project it is really helpful ,hope y'all the best !

**Comment by himself65** [comment]
I will keep this open until we finish this

**Comment by DaEpicR** [comment]
> Hi. So when this will be solved?

its a real issue and The problem has not been solved for a month.

**Comment by himself65** [comment]
Thank you for going on to follow up on this issue.

We have received the window app certificate, but it's a physical device, we have to plugin it into a PC when releasing a new version.

We are setting up the local CI to handle this situation. This should be fixed by the end of this month

/cc @darkskygit @Brooooooklyn

**Comment by darkskygit** [comment]
we have deployed the certificate server and are currently debugging the ci

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/commit/7d6e91f56e862f3504af828746f710dbe3ce4212

Please see our next stable version

**Comment by himself65** [comment]
Since those versions, we have signature support on windows
https://github.com/toeverything/AFFiNE/releases/tag/v0.8.0-canary.29
https://github.com/toeverything/AFFiNE/releases/tag/v0.8.0-beta.2

**Comment by himself65** [comment]
I will release a 0.7.3 soon

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/releases/tag/v0.7.3
