### ISSUE TITLE
​Low contrast on some tooltips when using dark mode

### ISSUE THREAD

**Issue by 0scvr** [toeverything/AFFiNE#2963]
### What happened?

When visiting the current demo page (https://app.affine.pro/workspace/lJnbFZcqju/hello-world) in Brave on macOS I noticed that some tooltips have very low contrast and are barely readable. I am using dark mode on my computer, so the affine web app was automatically set to dark mode too. Here are some screenshots:

![bottom-left](https://github.com/toeverything/AFFiNE/assets/71343264/71807526-940a-40e0-aeba-64ad30152f27)
![top-left](https://github.com/toeverything/AFFiNE/assets/71343264/60b4ca4c-8a88-4e02-a578-c9944c983776)
![top-right](https://github.com/toeverything/AFFiNE/assets/71343264/1aaa4c07-db5f-41a0-8265-51ffa949dc55)

Interestingly though, the "insert blocks" button doesn't seem to be affected by this issue:
![insert-blocks](https://github.com/toeverything/AFFiNE/assets/71343264/c74fe640-f407-4f52-8bd0-97b22e354eb1)

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

```shell
Project: @affine/web
Build date: 24/05/2023 11:49:47
Editor Version: 0.0.0-20230420210727-85b7de79-nightly
Version: 65a1401-dirty
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
This should be fixed in the latest canary version. But we have not deployed that.
