### ISSUE TITLE
Side menu link overflows on web version

### ISSUE THREAD

**Issue by 0scvr** [toeverything/AFFiNE#2964]
### What happened?

On the affine web demo, the workspace settings link in the side menu overflows when set to french. I haven't tested other languages, but I think the same issue would happen if the string is long enough.

Here's a screenshot:
![left-menu](https://github.com/toeverything/AFFiNE/assets/71343264/fd1fae0a-0bbf-4cf1-9066-cee3633fdd63)

NB: Tested on macOS in Brave browser.

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

```shell
Project: @affine/web
Build date: 24/05/2023 11:49:47
Editor Version: 0.0.0-20230420210727-85b7de79-nightly
Version: 65a1401-dirty
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
This should be fixed in the latest canary version. But we have not deployed that.
