### ISSUE TITLE
UI change for the delete page​

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#2970]
### What happened?
Please upgrade the delete page, the design team has moved the "restore", and "delete" buttons from the top right corner to the bottom, besides, [float button shadow2] has added
[internal figma](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=4552-115347&mode=design&t=etjTBUyGWUmVoePN-4)

![Image](https://github.com/toeverything/AFFiNE/assets/110808979/9d683b07-2c45-4577-9c8a-31489ac72dac)

### Distribution version
macOS x64

### Are you willing to submit a PR?
- [ ] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
Close with https://github.com/toeverything/AFFiNE/pull/3352
