### ISSUE TITLE
Add import button for Sidebar​

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#2975]
### Description

![shot-2023-07-03-15 32 55@2x](https://github.com/toeverything/AFFiNE/assets/24713927/262c3694-c7b3-4ac1-af97-bb5452de8a1d)

According to the discussion on the product side, we need to add an import button in the sidebar to enhance the priority of the import feature entrance.

and open with this dialog: 

![shot-2023-07-03-15 34 16@2x](https://github.com/toeverything/AFFiNE/assets/24713927/1b4251d2-e194-43cf-8bfb-2feec19aa2d7)

cc @joebeijing 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Svaney-ssman** [comment]
the modal background of import is missing, besides, please check the colors, the dark mode preview also offered @zuoxiaodong0815 
<img width="1367" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/bb3fb9a3-cb93-4086-a6e2-3b9bc858a1dc">
<img width="757" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/4653467d-0271-46cf-aa35-124de4bc703a">

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/commit/18874d0d1e0f6d7a3da9a68ed80cb25069a0a43d
