### ISSUE TITLE
In the pop-up window for deleting Workspace, cannot copy and paste the text

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#3007]
Note：
1. Currently, can only reproduces on Windows.
2. The issue only occurs when the user enters text in the pop-up window and then tries to copy and paste the selected text.

**Comment by kanweiwei** [comment]
> Note：
> 
> 1. Currently, can only reproduces on Windows.
> 2. The issue only occurs when the user enters text in the pop-up window and then tries to copy and paste the selected text.

I can not reproduce this problem. Can you provide a gif or a video?

**Comment by joebeijing** [comment]
This issue cannot be reproduced on the latest beta version of both Mac and Windows.
