### ISSUE TITLE
​Simple document navigation

### ISSUE THREAD

**Issue by petarsrepo** [toeverything/AFFiNE#3018]
# Simple document navigation

## Description

Nothing too fancy just a standard MSWord-like document navigation with:
- headings map with appropriate levels
- click heading to jump to position
- search document text
- highlight search result position in map (nice-to-have)

### Placement
a) left-hand sidebar with a button that flips between current workspace navigation and proposed document one
b) left-hand sidebar with a button to extend / retract proposed document navigation from the current workspace one
c) standalone right-hand sidebar with a button to show / hide like the current workspace navigation
![affine document navigation feature request](https://github.com/toeverything/AFFiNE/assets/24898023/6e9d70fe-4f27-452d-b1c4-8be296d5f282)

### How might this feature be used

To navigate a document and jump between its individual sections swifter and easier. Long-form text with a multitude of headings and levels is a nightmare to navigate through by only scrolling. This is especially true when rearranging paragraphs or other blocks between distant positions within the document. 

Pasting content in edgeless does not create a new element so mind-mapping content pieces and rearranging them to fit a desired order (as an alternative means of achieving the previous sentence's goal) is not possible either. 

That being said, the proposed simple document navigation offers a swift, easy to work with, and likely easier to implement way of working with multi-heading (and level) long-form text.

### Who might use it

Pretty much anyone and everyone using AFFiNE as a word processor, especially while working with long-form text consisting of a large set of headings and levels of such.

### Additional notes
Image attached in the description but it said to do it here so here it is. 

I'd offer to help implement my feature requests but I suck at TypeScript, so best leave it to the pros. 

For further reference of the feature concept just open a Word or Google Docs document and look to the left :)

Regardless of the outcome, your project is awesome and I love having it as a rich-media offline substitute for Notepad as it helps me move away from taking notes on a corporate Notion workspace that only works in the cloud. 

Wishing you a successful development!

![affine document navigation feature request](https://github.com/toeverything/AFFiNE/assets/24898023/6e9d70fe-4f27-452d-b1c4-8be296d5f282)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Related: https://github.com/toeverything/AFFiNE/issues/2955

**Comment by xell** [comment]
Thank you for the detailed suggestion. We planned this in https://github.com/toeverything/blocksuite/issues/4159 and please track it afterwards. This issue is closed.
