### ISSUE TITLE
cloud storage api with blocksuite

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3021]
Reference: https://github.com/toeverything/blocksuite/blob/master/packages/store/src/persistence/blob/mock-server-storage.ts

Use Affine Cloud to implement the corresponding Storage API, use Import {fetcher} from '@AFFINE/GRAPHQL'

**Comment by JimmFly** [comment]
Is the crud of the blob ready? @darkskygit

**Comment by darkskygit** [comment]
> Is the crud of the blob ready? @darkskygit

https://github.com/toeverything/AFFiNE/blob/himself65/0629-login/packages/graphql/src/graphql/index.ts

**Comment by darkskygit** [comment]
all apis ready
