### ISSUE TITLE
When using a custom storage path, the file name for storage is incorrect

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#3022]
### What happened?

report from [twitter](https://twitter.com/hylarucoder/status/1676461541762424833?s=20)

![F0P8juVaEAAmWrH](https://github.com/toeverything/AFFiNE/assets/24713927/d1d6dc82-ed5d-4c72-99e2-0fc58d3cad90)

added the undefined name at the beginning.

### Distribution version

macOS x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kanweiwei** [comment]
https://github.com/toeverything/AFFiNE/blob/8a565b8633a1e72dc5a7fbd62089367b0adb000a/apps/electron/src/helper/dialog/dialog.ts#L101-L102

seems like `db.getWorkspaceName()` will return undefined

**Comment by kanweiwei** [comment]
<img width="785" alt="image" src="https://github.com/toeverything/AFFiNE/assets/19727490/b42df99b-bf5e-4297-bded-c60c845f584c">
It can be undefined sometimes. But i can't reproduced.

**Comment by himself65** [comment]
@pengx17

**Comment by pengx17** [comment]
> It can be undefined sometimes. But i can't reproduced.

It seems there is some dataloss in the sqlite provider sometimes which will cause this issue. I am still investigating the issue.
