### ISSUE TITLE
New Page button in the All Pages is misplaced when the width of window is small

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#3026]
https://github.com/toeverything/AFFiNE/assets/132558/2712b42c-2270-48e1-beca-bb375f112406

**Comment by hwangdev97** [comment]
the [Internal link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=8155%3A153414&mode=design&t=GftXwTlPciElpTc6-1)

![image](https://github.com/toeverything/AFFiNE/assets/24713927/9a1b101b-8bed-40fd-967e-05f8f586b65f)

**Comment by Kaneki-Ken-7** [comment]
Hey @xell I think this issue I solved it in my previous issue (​All page list UI padding #2933) . these both issues were connected.

**Comment by xell** [comment]
> Hey @xell I think this issue I solved it in my previous issue (​All page list UI padding #2933) . these both issues were connected. but I think changes should be done on other two columns as well (created and updated).

Thanks for your contribution. After you complete the task, please link the PR here for the further review.

**Comment by Kaneki-Ken-7** [comment]
hey @xell , I have made the changes . Can you check it?

**Comment by xell** [comment]
> hey @xell , I have made the changes . Can you check it?

The dev team will check and finally merge it if there's no problem. Thank you.
