### ISSUE TITLE
In All Pages, tags will be masked or invisible when the width of window is small

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#3059]
The column of tags has responsive design problem.

https://github.com/toeverything/AFFiNE/assets/132558/e8a0c2d5-e668-4a84-ad21-e9c813868610

**Comment by lawvs** [comment]
Also related to https://github.com/toeverything/AFFiNE/issues/3026

**Comment by hwangdev97** [comment]
That's by design. We will optimize this in the next version.
