### ISSUE TITLE
Colors in this part of UI are incorrect in dark mode

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#3061]
![image](https://github.com/toeverything/AFFiNE/assets/132558/a6827243-f4b5-4298-84e1-076f3d429223)

**Comment by hwangdev97** [comment]
I think this is a design mistake. The design team used a white overlay with opacity of 0.6, which resulted in this appearance in dark mode. A reasonable approach would be to modify the opacity of these elements to 0.4 and change the mouse cursor style to disable.

cc @Svaney-ssman
