### ISSUE TITLE
Account name on the bottom left corner of workspaces list window overflows

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#3067]
![img_v2_c6ae1a92-215a-4bf9-abb9-c4044743d0fg](https://github.com/toeverything/AFFiNE/assets/132558/b1aae735-4676-4e52-b69b-9d2b5a4557db)

**Comment by QiShaoXuan** [comment]
It seems that this part is redesigning So I just adjusted the basic style to keep in order
