### ISSUE TITLE
Support for Deleting Multiple Pages or Restoring Them

### ISSUE THREAD

**Issue by adityash1** [toeverything/AFFiNE#3071]
### Description

Currently, Affine only allows users to delete or restore pages one at a time. This can be time-consuming and inefficient when dealing with a large number of pages.

### Anything else?

This could be implemented as checkboxes next to each page in the list view, with a dropdown menu or buttons for "Delete Selected" and "Restore Selected". To ensure that users do not accidentally delete or restore pages. It'll be better to add a confirmation prompt before performing these actions.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
@joebeijing
