### ISSUE TITLE
[feature]: Mindmaps

### ISSUE THREAD

**Issue by MarkGStacey** [toeverything/AFFiNE#308]
### 1~3 main use cases of the proposed feature

1: Mindmaps as an editable, shareable, web based solution are very useful for knowledge bases - MindManaget by Coral is the best functional version but no mobile access, and web based access to mind maps is the only reason I use Miro
2: showing a knowledge graph of linked blocks is a great way to explore a larger knowledge base

### Ideas for solution

1: Add an editable mind map
2: display a mind map of existing content 

### what types of users can benefit from using your proposed feature

All knowledge workers

**Comment by alt1o** [comment]
Mindmaps is very useful in many scenes. We will implement this function.

**Comment by joebeijing** [comment]
Related with https://github.com/toeverything/blocksuite/issues/2941

**Comment by himself65** [comment]
See https://github.com/toeverything/blocksuite/issues/2941
