### ISSUE TITLE
​Feat: Bottom Right Icon for Improved UX 

### ISSUE THREAD

**Issue by Saurav-Pant** [toeverything/AFFiNE#3096]
### Description

The website's logo becomes invisible when scrolling, creating a usability issue. Adding an upward-facing icon in the bottom right corner will enhance UX by providing an intuitive way to navigate upwards.

### Use case

By placing an upward-facing icon in the bottom right corner, users can easily navigate upwards on the website. This improvement enhances the overall user experience.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Please take a look at the website navigation optimization requirements.  @JackiePengp
