### ISSUE TITLE
Cloud storage ​support

### ISSUE THREAD

**Issue by stevefan1999-personal** [toeverything/AFFiNE#3106]
### Description

We should release an API that allows us to implement workspace storage on basically anywhere (similar to the fashion of VFS)

### Use case

For example, we can use our Google Drive, Onedrive, S3 compatible providers, rclone, Storj or even Synology Drive for ultimate privacy.

### Anything else?

I was not referring that we need major cloud storage providers support, but rather I want to have the API, the basic interface so that the community can implement as a plugin (in future)

Right now we are just relying on local file system support to have those major cloud storage providers utilized indirectly, and there is a lot of problem like cache coherency/eventual consistency problem (for example I used rclone + FUSE mode before and it is quite painful). We need a more direct API so that we can solve it at a more fundamental level.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
You will need to implement a Ydoc provider. For example, our sqlite provider https://github.com/toeverything/AFFiNE/blob/master/packages/workspace/src/providers/sqlite-providers.ts

And there is a universal protocol. https://github.com/toeverything/blocksuite/blob/master/packages/store/src/providers/async-call-rpc.ts

**Comment by ghost** [comment]
Are there any updates on the progress?
