### ISSUE TITLE
Demo doesn't load on Firefox

### ISSUE THREAD

**Issue by stefnotch** [toeverything/AFFiNE#3109]
When I open the https://app.affine.pro/workspace/0vzIq2_Z0W/all site on Firefox 115 on Windows, it refuses to finish loading.
![image](https://github.com/toeverything/blocksuite/assets/10220080/de280b1b-f965-487c-8225-19c840bb25c3)

I did try to set my usually strict adblock + anti-tracking settings to the minimum, and the issue still persists.

A bit of debugging later, it seems like the demo relies on https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/databases , which isn't supported by Firefox. (See also https://bugzilla.mozilla.org/show_bug.cgi?id=934640 )

**Comment by himself65** [comment]
We have fixed this in latest 0.7.0, please wait for the deployment in this end of month

**Comment by fourdim** [comment]
Fixed by #3417, https://github.com/toeverything/blocksuite/pull/3795, https://github.com/toeverything/blocksuite/pull/3738.
Please wait for the deployment.

**Comment by fourdim** [comment]
https://github.com/toeverything/AFFiNE/releases/tag/v0.8.0
