### ISSUE TITLE
Edgeless fatal crash when editing on first load​

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/AFFiNE#3141]
### What happened?

Create new workspace in Edgeless - try to add any objects (draw, shapes etc.) - will not work - switch to Page then back (blank page)

https://github.com/toeverything/AFFiNE/assets/79373028/5ddab5d7-f3de-4994-96e1-762e0111fa6e

### Distribution version

macOS x64

### What browsers are you seeing the problem on if you're using web version?

Other

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doouding** [comment]
This issue might be due to the same reason as issue [#3467](https://github.com/toeverything/AFFiNE/issues/3467). It should also have been resolved by PR [#3480](https://github.com/toeverything/blocksuite/pull/3480).
