### ISSUE TITLE
Module not found: Can't resolve '@affine/env/constant'​

### ISSUE THREAD

**Issue by Nunchakus888** [toeverything/AFFiNE#3165]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/14994145/7fe94e75-bba0-42b2-8153-7e959231b762)

### Distribution version

macOS ARM 64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

```shell
pnpm run dev
```

### Anything else?

<img width="518" alt="image" src="https://github.com/toeverything/AFFiNE/assets/14994145/bd4fc88f-4f28-41be-a029-db771c4b1af5">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
use `yarn`
