### ISSUE TITLE
White padding on exported PDF

### ISSUE THREAD

**Issue by Lantianyou** [toeverything/AFFiNE#3168]
### What happened?

在使用 affine 暗色模式写 2 页文档过程中，导出成 PDF 发现有如图所示白色 padding。PDF 如下

![image](https://github.com/toeverything/AFFiNE/assets/37259750/514d7e2b-645a-4cd3-979c-fe115a3cb94f)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
What version of affine you are using?

**Comment by hwangdev97** [comment]
We will update settings page 👇
![image](https://github.com/toeverything/AFFiNE/assets/24713927/1901339a-3572-4b9e-9a89-336aa2f2343a)

on windows, you can check app version info on settings -> apps & features : 

maybe looks like👇

on windows 10
![shot-2023-07-12-00 17 09@2x](https://github.com/toeverything/AFFiNE/assets/24713927/0d52dd67-0137-4ffd-8fa6-c61a6bf31118)

and windows 11:
![Uploading shot-2023-07-12-00.19.13@2x.png…]()

**Comment by Lantianyou** [comment]
I see. I must be using a older version with no about page. I will download and re-test it again

**Comment by Lantianyou** [comment]
It is 0.6 thanks to your help
![image](https://github.com/toeverything/AFFiNE/assets/37259750/25411ab6-47a8-4245-af36-795aa4c7399f)

**Comment by Lantianyou** [comment]
This isssue is resolved on the canary version based on my test :) Feel free to close this :)

**Comment by joebeijing** [comment]
Received, still thank you for your feedback, I will close it for now.
