### ISSUE TITLE
when changing to another workspace, a 404 page shows up strangely

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#3171]
The regularity of it is still under inspection.  

<img width="1512" alt="Screenshot 2023-07-11 at 14 01 55" src="https://github.com/toeverything/blocksuite/assets/132558/03ad9e53-0982-40e9-a7b4-ab3b3fdf3dca">

**Comment by himself65** [comment]
Fixed in https://github.com/toeverything/AFFiNE/pull/3190
