### ISSUE TITLE
Sidebar not collapsing properly

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#3212]
Sidebar auto collapses only halfway.

https://github.com/toeverything/AFFiNE-Community/assets/4605025/4f97ee1f-e303-4572-952d-75a88f476fef

**Comment by QiShaoXuan** [comment]
@Yipei-Operation Try to use this version https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-20230713084220-559d9bb

**Comment by ShortCipher5** [comment]
Solved in latest version.
