### ISSUE TITLE
Cannot import isBrowser from '@affine/env'​

### ISSUE THREAD

**Issue by Nunchakus888** [toeverything/AFFiNE#3224]
### What happened?

yarn install is ok,
yarn dev as follow error:

<img width="432" alt="image" src="https://github.com/toeverything/AFFiNE/assets/14994145/b03a9f15-40ea-4ebd-b7a8-399be5044cbf">

<img width="1038" alt="image" src="https://github.com/toeverything/AFFiNE/assets/14994145/bf2f070e-220d-45bd-a381-d31ce7972c81">

The env/package.json file exports attribute not work?

### Distribution version

macOS x64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Anything else?

yarn@3.6
node v18.16.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fourdim** [comment]
Use
```js
import { isBrowser } from '@affine/env/constant';
```
instead.
