### ISSUE TITLE
Request to relicense under Apache/MIT

### ISSUE THREAD

**Issue by ajavaer** [toeverything/AFFiNE#3225]
### Description

Hello,

I'm interested in using some code from this repository in a commercial closed-source project. However, the current MPL2 license has some restrictions that make this difficult.

The MPL2 is not compatible with closed-source licensing. As per the terms of MPL2, if I modify any files, I would be required to open-source my entire project under MPL2, which unfortunately won't work for my use case.

I would kindly request considering relicensing the repository under a more permissive license like Apache 2.0 or MIT. Both Apache 2.0 and MIT licenses allow using the code in proprietary closed-source software without requiring changes to be open sourced. This would make the project more usable for commercial applications.

I believe re-licensing under Apache 2.0 or MIT will help increase adoption of the project. Let me know if any clarification or discussion is needed around this request. I'd be happy to explain my use case in more detail if needed.

Thank you for creating this useful project and considering this request. Looking forward to your thoughts.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for your feedback! I'd say this meets our expectation. Based on our license, a fork is welcomed but you should open source your modified code. If you want to maintain a close source fork, you are also welcomed to contact us for potential licensing, instead of requesting us to invalidate our business model.

**Comment by himself65** [comment]
We are welcome to give specific enterprise closed source licenses. But we will continue use MPL2 license as usual. If you have any question, please email to contact@toeverything.info
