### ISSUE TITLE
sub-page did not show up in the sidebar area

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/AFFiNE#3230]
version: latest internal 
may appeared this problem in random workspace. 

https://github.com/toeverything/blocksuite/assets/134897361/9d9f710e-9556-4238-97ea-2f2dc96791f1

**Comment by ShortCipher5** [comment]
To expand on this:

1. The link will work when referring to the page, but will not show in the page tree if the link is in a list.
2. You can link to deleted pages (deleted pages should not show in the link list, and will not show in the page tree on the sidebar).

**Comment by pengx17** [comment]
related to https://github.com/toeverything/AFFiNE/issues/3029

**Comment by pengx17** [comment]
Should be fixed by https://github.com/toeverything/AFFiNE/issues/3230
