### ISSUE TITLE
​Table improvements (Page Linking, Sorting)

### ISSUE THREAD

**Issue by Quadrubo** [toeverything/AFFiNE#3242]
### Description

Sorting tables and linking to different pages inside a table is currently not possible.

### Use case

Linking pages inside would be useful for me to, for example, create a table filled with all of my ongoing projects, each with a link to their respective page. I could then use the sorting functionality to sort these projects by urgency, etc.

### Anything else?

If you'd like me to split these into 2 seperate issues I'd gladly do so.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Currently, linked pages can be placed in the title column. You can try it out. What else would you like to be supported in this feature?

![CleanShot 2023-07-14 at 17 46 39@2x](https://github.com/toeverything/AFFiNE/assets/22443345/9056812a-f1ab-42bd-bd3e-adf2ab19f18a)

**Comment by Quadrubo** [comment]
It should also be supported in the other columns, no reason not to.

**Comment by joebeijing** [comment]
We will soon support links in the latest beta, but we have not yet specifically adapted to linked pages. We will consider this later. Thank you very much for your feedback.
https://github.com/toeverything/blocksuite/issues/2667

**Comment by houjoe0829** [comment]
Currently, this is in the future iteration plan, but it has not started yet. We will temporarily close this issue. If there are any further questions or changes, please feel free to reopen it.
