### ISSUE TITLE
BlobStorage should provide consistent behaviour

### ISSUE THREAD

**Issue by zuoxiaodong0815** [toeverything/AFFiNE#3245]
The 'get' method of 'createIndexeddbStorage' returns the 'type' type. But, createSQLiteStorage and createStaticStorage do not. Please take time to add 'type' type. 

Please let me know if it is completed. I need to remove the temporary code. https://github.com/toeverything/blocksuite/pull/3555

**Comment by NextThread** [comment]
hey, I'd like to work on this issue

**Comment by zuoxiaodong0815** [comment]
Thank you. It has been assigned to you. @NextThread

**Comment by NextThread** [comment]
@zuoxiaodong0815 i did, but somebody told me that, it's not necessary, this thing can be skipped

**Comment by zuoxiaodong0815** [comment]
If we don't store the file type, we need to calculate the file type when reading the file, refer to the code https://github.com/toeverything/blocksuite/pull/3555/files
<img width="918" alt="image" src="https://github.com/toeverything/AFFiNE/assets/53252747/cbda951a-d2d5-430e-abe6-4f63db96fbe9">
So storing file types is a bit more appropriate.

The following two blob-storage, one of which provides the file type and one of which does not
https://github.com/toeverything/blocksuite/blob/master/packages/store/src/persistence/blob/indexeddb-storage.ts
https://github.com/toeverything/AFFiNE/blob/master/packages/workspace/src/blob/sqlite-blob-storage.ts

**Comment by NextThread** [comment]
ok I'm raising a PR again. Thanks

**Comment by zhe-he** [comment]
@zuoxiaodong0815  
     Hi, I noticed this issue because my editor keeps giving me warnings about the `file-type` module. Then I started trying to fix this problem. Since I'm not familiar with the business, if my approach is incorrect, please consider upgrading the `file-type` module so that my editor no longer gives the following warnings. Thank you in advance.
```
[plugin:vite:resolve] Module "events" has been externalized for browser compatibility, imported by "/Users/hezhe/work/processon/processon-prototype/node_modules/readable-web-to-node-stream/node_modules/readable-stream/lib/_stream_readable.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details
```

**Comment by fourdim** [comment]
> Hi, I noticed this issue because my editor keeps giving me warnings about the `file-type` module. Then I started trying to fix this problem. Since I'm not familiar with the business, if my approach is incorrect, please consider upgrading the `file-type` module so that my editor no longer gives the following warnings. Thank you in advance.
> 
> ```
> [plugin:vite:resolve] Module "events" has been externalized for browser compatibility, imported by "/Users/zhe-he/xxx/node_modules/readable-web-to-node-stream/node_modules/readable-stream/lib/_stream_readable.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details
> ```

@zhe-he Hi, we are always dedicated to using the latest dependencies. The thing is, we cannot upgrade it to the latest version as it's latest version does not support browser. Please consider contributing to the package `file-type`, `token-type`, and `readable-stream` in order to eliminate this warning.
