### ISSUE TITLE
​Clicking outside the page does not respond

### ISSUE THREAD

**Issue by elderhammer** [toeverything/AFFiNE#3281]
### What happened?

Clicking outside the page does not respond.
<img width="513" alt="Screenshot 2023-07-18 at 09 57 45" src="https://github.com/toeverything/AFFiNE/assets/81279860/e88d8c9c-aa7b-4f41-bb8f-2666a68b46ff">

### Distribution version

macOS x64

<img width="278" alt="Screenshot 2023-07-18 at 10 14 47" src="https://github.com/toeverything/AFFiNE/assets/81279860/7bcf5186-9ab5-4d04-aeb4-965b91c9815c">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
![CleanShot 2023-07-18 at 16 52 38@2x](https://github.com/toeverything/AFFiNE/assets/22443345/5bd96585-1c94-473b-b5a8-90df05056f0b)
Just to confirm, do you want the part near the border to also trigger the switch when clicked?

**Comment by elderhammer** [comment]
<img width="995" alt="Screenshot 2023-07-18 at 17 15 37" src="https://github.com/toeverything/AFFiNE/assets/81279860/76263ef4-0492-412f-931a-ae5ae5678f1a">

**Comment by houjoe0829** [comment]
Can you check if this trigger area meets the requirements from the design team? @xell

**Comment by xell** [comment]
> <img alt="Screenshot 2023-07-18 at 17 15 37" width="995" src="https://user-images.githubusercontent.com/81279860/254217383-76263ef4-0492-412f-931a-ae5ae5678f1a.png">

Hi. If what you meant is that, there's no effect while **clicking** the `T ˅` button of the toolbar which is outside the page (i.e. the editor), then I'd like to ask if the cursor hovering action can trigger the drop down menu? 

If the hovering action works, then I don't see any problem here because it's by design that the `T ˅` button is not to click no matter where it's -- you just hover the cursor to it.

**Comment by elderhammer** [comment]
As long as the T button is outside the page, even if it is not hovering over Trash, the click is no effict.
If the T button is no effict while outside the page, I think it is very inconvenient, because the user can only expand the window so that the T button is inside the page so that the click is effict. Of course, you can also use shortcut keys to modify Heading.
In addition, when the T button is hovering over Trash, intuitively it should be that the T button can be clicked instead of Trash. Otherwise, it's counterintuitive.

**Comment by xell** [comment]
Hi @elderhammer please write me at liuguozhu@toeverything.info in English or Chinese. I'd like to discuss this issue with you furthermore. Thanks.

**Comment by elderhammer** [comment]
你好，微信聊？



发自我的iPhone


------------------ Original ------------------
From: Guozhu Liu ***@***.***&gt;
Date: Fri,Jul 21,2023 6:26 PM
To: toeverything/AFFiNE ***@***.***&gt;
Cc: Haoran ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [toeverything/AFFiNE] ​Clicking outside the page does not respond (Issue #3281)





 
Hi @elderhammer please write me at ***@***.*** in English or Chinese. I'd like to discuss this issue with you furthermore. Thanks.

**Comment by JimmFly** [comment]
cc @lawvs

**Comment by elderhammer** [comment]
This issue is no longer reproduced in version [0.7.0-canary.51](https://github.com/toeverything/AFFiNE/releases/tag/v0.7.0-canary.51).

Thanks for replying. :-)
