### ISSUE TITLE
Add basic event tracking

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#3288]
This refers to the event tracking related to data tracking, including both client-side and server-side tracking.
```[tasklist]
### Client Monitor
- [ ] Origin tracking
- [ ] User <-> ClientID
```

**Comment by JackiePengp** [comment]
@himself65 hi, Alex, this project is not even done, we just finished the talk, but wait further progress being made,, can reopen this issue and let it be involved in the AFFiNE 0.8 scope
