### ISSUE TITLE
workspace can not show picture when i import can​ary workspace to beta

### ISSUE THREAD

**Issue by Mojicode** [toeverything/AFFiNE#3291]
### What happened?

As you see the title, I export the canary workspace, install 7.0beta and import workspace to 7.0beta, the picture in the file can not show

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Who can take a look at this issue? @himself65
