### ISSUE TITLE
​Update the icon library for the app

### ISSUE THREAD

**Issue by zanwei** [toeverything/AFFiNE#3293]
### Description

We're working a brand new icon library which will replace the old one. 

It will be used in **0.8.0**

![Image](https://github.com/toeverything/AFFiNE/assets/40333372/9eabbfbb-53c8-4292-b742-283034db3235)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
The icon used by Blocksuite needs to wait for Blocksuite to be updated. The icon of AFFiNE has been updated, and the issue is closed first.
