### ISSUE TITLE
Support sign in & up with cloud function

### ISSUE THREAD

**Issue by QiShaoXuan** [toeverything/AFFiNE#3355]
Internal doc: https://toeverything.feishu.cn/wiki/DKSHw2IpaiwqfxkTYI7cOysTnmb
Internal design: https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?node-id=5729%3A121146&mode=dev

**Comment by houjoe0829** [comment]
Duplicated with https://github.com/toeverything/AFFiNE/issues/2648
