### ISSUE TITLE
Improve e2e coverage on page deletion

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3359]
```[tasklist]
### E2E Improvement
- [ ] page delete -> it should be deleted
- [ ] page delete -> refresh page -> it should be disappear
- [ ] page delete -> create new page -> refresh page -> new page should be appear -> old page should be disappear
- [ ] delete multiple pages -> create multiple pages -> refresh
```

**Comment by teobler** [comment]
Doing some testing related stuff spike around this issue and #3198 

1. during coding, [#3412](https://github.com/toeverything/AFFiNE/issues/3412) happened, will block this issue.
2. need more context about 'logic abstraction' in #3198, something like build a page level model/class for holding navigation/click logic?
