### ISSUE TITLE
[bug]: The cursor is on incorrectly position

### ISSUE THREAD

**Issue by Zheaoli** [toeverything/AFFiNE#336]
### To Reproduce

1. Enter a new line 
2. Input some random text
3. First input ** and input some content, then finish the code with **. Yes, it's the markdown's bold text syntax
4. The cursor will go to the beginning of the line, not the end of the content.

### Platform

MacOS 13 Beta6

### Browser

Chrome 104.0.5112.101

### Additional context

Use the code in the commit 7eff19509fe057b6ef8217839ec397b5eae605e3

**Comment by tzhangchi** [comment]
Thank you for you feedback，we are working on it，next month we will release a better editing Experience editor
