### ISSUE TITLE
build error：​ Module not found

### ISSUE THREAD

**Issue by Junwen-xie** [toeverything/AFFiNE#3363]
### What happened?

after running ： yarn workspace @affine/native build
i tried: yarn dev 
the result show below.  
<img width="668" alt="image" src="https://github.com/toeverything/AFFiNE/assets/26343300/a17f2c38-f2dc-45c0-991d-19327b3dfdb6">

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
run `yarn build:infra` before dev
