### ISSUE TITLE
[bug]: The code block behavior is not correct

### ISSUE THREAD

**Issue by Zheaoli** [toeverything/AFFiNE#337]
### To Reproduce

1. input / , and input **code**
2. click the button code
3. you will find the page create a new code block below, and the text you input to filter the block type is not replaced

### Screenshots

<img width="1452" alt="CleanShot 2022-08-26 at 21 33 10@2x" src="https://user-images.githubusercontent.com/7054676/186915429-8cd77855-b6d7-4b0e-a97c-ec4d601bda19.png">

### Platform

MacOS 13 Beta6

### Browser

Chrome 104.0.5112.101

**Comment by tzhangchi** [comment]
Cool，we will fix it recently

**Comment by tzhangchi** [comment]
@DiamondThree it's unstable now

**Comment by tzhangchi** [comment]
@DiamondThree have fix it , @Zheaoli you can try it

**Comment by DiamondThree** [comment]
First, thank you for your advice. The bug was due to not taking into account the border situation and has now been fixed,

**Comment by Zheaoli** [comment]
Fixed, confirmed
