### ISSUE TITLE
All page filter add more date-time ​filter rule​

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#3372]
### Description

Please add some date-related filtering items, such as today, yesterday, three days ago, this week, this month, etc. For details, please refer to the internal documentation.

![shot-2023-07-25-21 00 55@2x](https://github.com/toeverything/AFFiNE/assets/24713927/00bac555-1d53-4e0f-8485-4506192eff0b)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
[Internal PRD](https://toeverything.feishu.cn/wiki/G2DowRoAeiQ9Z6khm1kcULrcnbs)
