### ISSUE TITLE
​In the sidebar area, there are inaccurate positioning problem

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/AFFiNE#3382]
### What happened?

version: newest beta

 From the video, you can observe that when the cursor is positioned in the collection area, it automatically transitions to the all-page area. It failed to position in the collection area. 

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Yanxi0202** [comment]
https://github.com/toeverything/AFFiNE/assets/134897361/61d211be-dc3b-4334-8698-7097ac6cd63d

**Comment by pengx17** [comment]
@houjoe0829 @xell I think this also needs product design input. IMO we need to hide new page if collection is enabled.

**Comment by houjoe0829** [comment]
> @houjoe0829 @xell I think this also needs product design input. IMO we need to hide new page if collection is enabled.

I suggest focusing only on the issue of misaligned display.

**Comment by xell** [comment]
> > @houjoe0829 @xell I think this also needs product design input. IMO we need to hide new page if collection is enabled.
> 
> 
> 
> I suggest focusing only on the issue of misaligned display.

Agree. As for the suggested behavior by @pengx17 , we will discuss later and probably use a new issue to track.

**Comment by Kaneki-Ken-7** [comment]
@xell can you tell me how do I create a collection?

**Comment by Kaneki-Ken-7** [comment]
@xell you only want here to display the collection to be selected and not All pages?
