### ISSUE TITLE
Change the current display mode of the open Workspace in the settings to use small dots

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#3383]
Currently, the label "Current" is being used, which takes up some space.
After changing to use "dots" for display, hover over the dots to show the Hovertips "Active Workspace".
![CleanShot 2023-07-26 at 16 13 51@2x](https://github.com/toeverything/AFFiNE/assets/22443345/8cbe999b-a43f-4da2-9c30-e08d0f4bb463)

**Comment by hwangdev97** [comment]
Update the deisgn:

![shot-2023-07-26-16 47 52@2x](https://github.com/toeverything/AFFiNE/assets/24713927/ce3d325b-3758-4817-8900-745c74919701)

[the figma file](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=5126%3A114683&mode=design&t=ba1oPAnh7hFNA9n0-1)
