### ISSUE TITLE
​0.7.0-canary.52，侧边栏展开关闭按钮不能用，快捷键可用

### ISSUE THREAD

**Issue by Mojicode** [toeverything/AFFiNE#3395]
### What happened?

如题，点击按钮没有反应，但是快捷键可用

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Related: https://github.com/toeverything/AFFiNE/pull/3343

**Comment by QiShaoXuan** [comment]
fixed In https://github.com/toeverything/AFFiNE/pull/3343
