### ISSUE TITLE
"Drag page to sidebar" does not work

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/AFFiNE#3410]
https://github.com/toeverything/AFFiNE/assets/134894293/9fcd7280-c391-4f8e-a9c9-e1fa0b7e53b3

**Comment by PaxtonXuan** [comment]
https://github.com/toeverything/AFFiNE/assets/134894293/128a5ad8-597d-47e6-8df0-fb0e7436246d

**Comment by houjoe0829** [comment]
As our expectation:
1. Could drag and add to Favourites.
2. Could adjust the order in Favourites.

**Comment by teobler** [comment]
to support sortable list, there are several ways:
1. just like collection pages, we can save favorite pages as an array to idb
2. add an array or related data structure to `workspace` to support sorted list
3. add two fields like `prevFavoritePage, nextFavoritePage` to make pageMeta a linked list

not sure if there is more option we can choose. cc: @himself65

**Comment by himself65** [comment]
> 

I believe this should be saved in the CRDT to sync to all clients. So you might need to know how to use `workspace.meta`

**Comment by teobler** [comment]
Sure, this is what I proposed in option 2, then I will create an `array` in `workspace.meta` maybe named `favoritePages`

**Comment by Garfield550** [comment]
@houjoe0829 Is this "drag and drop design" still effective?

<img width="1215" alt="image" src="https://github.com/toeverything/AFFiNE/assets/3471836/9aad6c97-3051-467f-bca0-e9fb9e3d6d6a">

**Comment by houjoe0829** [comment]
> @houjoe0829 Is this "drag and drop design" still effective?
> 
> <img alt="image" width="1215" src="https://user-images.githubusercontent.com/3471836/266239204-9aad6c97-3051-467f-bca0-e9fb9e3d6d6a.png">

Thank you for your attention. This design draft has expired and requires @xell  to update the new design for dragging to the sidebar.

**Comment by Garfield550** [comment]
> > @houjoe0829 Is this "drag and drop design" still effective?
> > <img alt="image" width="1215" src="https://user-images.githubusercontent.com/3471836/266239204-9aad6c97-3051-467f-bca0-e9fb9e3d6d6a.png">
> 
> Thank you for your attention. This design draft has expired and requires @xell to update the new design for dragging to the sidebar.

Okay, this issue is currently blocked. I will start working after the new design is completed.
