### ISSUE TITLE
workspace-directory​

### ISSUE THREAD

**Issue by tclxjiawei-ji** [toeverything/AFFiNE#3432]
### Description

I suggest the content in workspace should exist in tree-directory so that the knowledge can be remembered  in a better way

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
May I know if you want the pages in Workspace to be organized in a tree structure? And have you done this in any other product before?

**Comment by houjoe0829** [comment]
We will temporarily close this issue. If there are any further questions or changes, please feel free to reopen it.
