### ISSUE TITLE
​Bookmark is always in loading

### ISSUE THREAD

**Issue by xihale** [toeverything/AFFiNE#3438]
### What happened?

It's always hold this status.
![image](https://github.com/toeverything/AFFiNE/assets/62087089/26c84b38-e278-4eca-b574-c488ed7bb062)

### Distribution version

Linux

### Relevant log output

```shell
System information:
  OS: Manjaro Linux x86_64 
  Host: 80RT Lenovo XiaoXin 300 
  Kernel: 6.1.41-1-MANJARO 
  Uptime: 7 hours, 19 mins 
  Packages: 1634 (pacman), 10 (flatpak)
  Shell: bash 5.1.16 
  Resolution: 1920x1080 
  DE: Plasma 5.27.6 
  WM: KWin 

AFFiNE information:
  AFFiNE version: 0.7.0-beta.1
  Editor version: 0.0.0-20230717055529-79180930-nightly
```

### Anything else?

How did I get this version?
on [aur/affine-bin](https://aur.archlinux.org/packages/affine-bin)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fourdim** [comment]
We noticed that you might be in a network restricted area. Could you please check if the link of the bookmark is available in your country?
To use affine with proxy on linux, see https://www.electronjs.org/docs/latest/api/command-line-switches#--proxy-serveraddressport

**Comment by xihale** [comment]
I'm sure `bilibili.com` can be directly visited in my country.

**Comment by xihale** [comment]
but I 'm not sure if AFFiNE can get into the network, I don't know how to test it's network connection.

**Comment by fourdim** [comment]
Press `Ctrl+Shift+I` and paste following codes to the console. URL below can be replaced by yours.
```js
await window.apis.ui.getBookmarkDataByLink("https://github.com")
```
Then check the result.

**Comment by xihale** [comment]
Oh, I forget that it's electron and it can open the debug console!
I find that when I create a bookmark, it errors: `Uncaught (in promise) TypeError: Cannot destructure property 'title' of 'n' as it is undefined.` (the call stack cannot be shown beacause it's complied, the files are very complex)

**Comment by xihale** [comment]
I will try to debug the source to see what happend!

**Comment by xihale** [comment]
I tried `bilibili.com` `github.com`
they will all cause the errors

**Comment by fourdim** [comment]
Please add the schema, try use `https://bilibili.com` `https://github.com` instead.

**Comment by xihale** [comment]
I try the version listed in release, it is no wrong like that, now i'm sure that the problem was caused by aur/affine-bin package, let me see how its BUILDPKG writed

**Comment by xihale** [comment]
The BUILDPKG core code is
` asar pack "${srcdir}/${_appname}-beta-linux-x64/resources/app" "${srcdir}/${pkgname%-bin}.asar"`
It try to pack AFFiNE to asar and use system electron25 to run it, and I try some version of electron, it will cause this problem. 
But I don't know why it will cause problem with packing it to asar and  running it by system electron
