### ISSUE TITLE
​Insert various accessories

### ISSUE THREAD

**Issue by cycle2zhou** [toeverything/AFFiNE#3442]
### Description

Supports the insertion of various attachments, and can provide preview and other functions for common file formats. All files can be opened by external third-party corresponding software, and the note storage can be correctly deleted when the file is deleted

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Regarding attachment support, it is currently in progress. You can track the progress on [this issue](https://github.com/toeverything/blocksuite/issues/2952). After supporting basic file insertion, we will gradually adapt to preview different types of attachments, such as PDFs and videos. Thank you for your feedback. We will close this issue for now, but feel free to reopen it if you have any further questions.
