### ISSUE TITLE
​CANNY BOARD DOES NOT WORK

### ISSUE THREAD

**Issue by v479038280** [toeverything/AFFiNE#3453]
### What happened?

![微信截图_20230729113925](https://github.com/toeverything/AFFiNE/assets/25096045/fef2f006-0bc3-4d5d-93ee-d27cb271fae4)
CAN'T DARW 

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Please wait for 0.8.0-canary.0 release

**Comment by himself65** [comment]
Fixed in 0.8.0-canary.0

**Comment by himself65** [comment]
Please notice that every canary version does have such noticeable bugs. It's not designed for production-ready.

PLEASE USE 0.7.0 stable if you want stable
