### ISSUE TITLE
Login button UI incorrect

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3454]
![image](https://github.com/toeverything/AFFiNE/assets/14026360/cbe325db-b0cf-479a-86d5-407b2b65703b)

**Comment by Kaneki-Ken-7** [comment]
what is the correct design of this button? @himself65

**Comment by himself65** [comment]
see https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=2-1563&mode=design&t=aPmDZH7yacDZUSaT-0

**Comment by Kaneki-Ken-7** [comment]
@himself65 can you check my PR whether its the right UI or not?
