### ISSUE TITLE
[bug]: Incorrect keyboard icon on Windows

### ISSUE THREAD

**Issue by chriseikrem** [toeverything/AFFiNE#346]
### Describe the bug

Incorrect keyboard icon when hovering text

### To Reproduce

Steps to reproduce on Windows 10:
1. Write some text
2. Select it
3. Hover mouse over text to display overlay
4. Hover mouse over overlay-buttons to see the Mac Command button icon

### Screenshots

![image](https://user-images.githubusercontent.com/3619871/187369070-df0edc81-701e-4030-908b-2dd5ec7e1e04.png)

### Expected behavior

When on Windows 10, I should not see a Mac Command button icon, I should see ctrl.

### Platform

Windows 10

### Browser

Chrome

**Comment by Pranav4399** [comment]
Hello ! I'm interested in working on this bug.

**Comment by Pranav4399** [comment]
I've fixed this issue but getting an error when trying to commit the code. Need help with that.
