### ISSUE TITLE
​Windows/Microsoft Defender flags Affine and considers it potentially harmful.

### ISSUE THREAD

**Issue by NLBRT** [toeverything/AFFiNE#3468]
### What happened?

Self-explanatory title. Here's a screenshot.

![image](https://github.com/toeverything/AFFiNE/assets/93070290/7ae59e72-684d-4190-a148-2d6cfb6c89c4)

Any plans to contact Microsoft/refer to their Documentations to avoid this in the future?

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Duplicate with https://github.com/toeverything/AFFiNE/issues/2958
