### ISSUE TITLE
[bug]: undo shortcut not working 

### ISSUE THREAD

**Issue by chriseikrem** [toeverything/AFFiNE#347]
### Describe the bug

There is no way to undo a text change

### To Reproduce

1. Write or remove some text
2. Try to undo the change using either CTRL - Z or right click to select undo

### Expected behavior

I expect the text editor to work just like any other text editor, where ctrl-z would undo a change. And additionaly, ctrl-shift-z to redo.

### Platform

Windows 10

### Browser

Chrome

**Comment by tzhangchi** [comment]
Thank you for your feedback，we have fix it，you can have a try

**Comment by chriseikrem** [comment]
@tzhangchi It still doesn't seem to work for me. Ctrl - z and ctrl - x is not working at all for me. Windows 10, Chrome
