### ISSUE TITLE
[feature]: browser clipper support with web page annotation

### ISSUE THREAD

**Issue by iSwiftLiu** [toeverything/AFFiNE#348]
### 1~3 main use cases of the proposed feature

collection web page

**Comment by tzhangchi** [comment]
this is a fancy feature，we will plan it

**Comment by est7** [comment]
have any updates?

**Comment by EYHN** [comment]
The part of the product that was causing this issue has been removed or significantly reworked since it was created.

**Comment by est7** [comment]
Why turn it off? It's a good feature.people need to make notes on what they clip
