### ISSUE TITLE
​0.7.1 Stable Version 'Collections' not working

### ISSUE THREAD

**Issue by AreChen** [toeverything/AFFiNE#3483]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/20765464/ee5dd25c-607a-4e2d-a0d5-92a25488d8de)
The plus sign is missing, and the collection that was previously created has also disappeared.

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
It's not a bug, we for sure didn't add the plus button there by design at 0.7.0

**Comment by himself65** [comment]
Also, you need to pin the collection in the all page

![image](https://github.com/toeverything/AFFiNE/assets/14026360/b55464d3-c7e0-42a2-a7ab-634681ad639e)

**Comment by AreChen** [comment]
> Also, you need to pin the collection in the all page
> 
> ![image](https://user-images.githubusercontent.com/14026360/257165595-b55464d3-c7e0-42a2-a7ab-634681ad639e.png)

But how do I create a collection in 0.7.1?

**Comment by AreChen** [comment]
![image](https:github.com/toeverything/AFFiNE/assets/20765464/69be88fd-7d65-414a-998b-dfccd4c4e495)
In 0.7. 0 I can use this + sign to create a new collection

**Comment by AreChen** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/20765464/eff9c41c-4428-4ad9-b7cc-cbf95f319d96)
I can't find a place to create in 0.7.1, did I miss something?

**Comment by himself65** [comment]
I'm pretty sure there's no such button in 0.7.0. Or I misunderstood something

**Comment by himself65** [comment]
> > Also, you need to pin the collection in the all page
> > ![image](https://user-images.githubusercontent.com/14026360/257165595-b55464d3-c7e0-42a2-a7ab-634681ad639e.png)
> 
> But how do I create a collection in 0.7.1?

![image](https://github.com/toeverything/AFFiNE/assets/14026360/91b72d1b-9e99-40a5-9a0d-f427db05225e)
You select some filter from here

![image](https://github.com/toeverything/AFFiNE/assets/14026360/2d4bc5e5-2f82-4c94-9758-3ad0a6a7ead8)

And there is a button to save as the collection

**Comment by himself65** [comment]
> I'm pretty sure there's no such button in 0.7.0. Or I misunderstood something

If you are talking about 0.7.x canary, it might have but we didn't land it yet

**Comment by AreChen** [comment]
THANKS! SOLVED
