### ISSUE TITLE
All Pages: 3 UI bugs

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#3491]
- [x] the three-button-group does not align center

![Untitled](https://github.com/toeverything/AFFiNE/assets/132558/b8f9aa11-0168-4e3a-a87c-800daa588d7d)

- [x] the hover color should be `hoverColorFilled` in the Add button

![image](https://github.com/toeverything/AFFiNE/assets/132558/89f07ec6-583c-4ef7-85f5-8c4459a5f15e)

- [ ] the overlap problem seen in the above screenshot

**Comment by Kaneki-Ken-7** [comment]
@xell in the first task you want all the 3 buttons to have same width or something else?

**Comment by JimmFly** [comment]
i will handle it.

**Comment by JimmFly** [comment]
Can you check the PR？

**Comment by JimmFly** [comment]
Done.
