### ISSUE TITLE
race condition on lazy provider

### ISSUE THREAD

**Issue by fourdim** [toeverything/AFFiNE#3494]
### What happened?

https://github.com/toeverything/AFFiNE/blob/c8b2728e27da79540dc8c61ab6231a50f8f40d83/packages/y-indexeddb/src/provider.ts#L116-L118

After call function `createIndexedDBProvider`, you need to call `connect` function inside it to connect to it to create a indexeddb.

https://github.com/toeverything/AFFiNE/blob/c8b2728e27da79540dc8c61ab6231a50f8f40d83/packages/y-indexeddb/src/provider.ts#L25-L41

However, in the `createDatasource` function it calls `openDB` with promise, which can be a race condition.

### Distribution version

Web (dev.affine.live)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Relevant log output

```shell
DOMException: IDBDatabase.transaction: 'workspace' is not a known object store name
    wrapFunction wrap-idb-value.js:150
    queryDocState provider.ts:40
    p lazy-provider.ts:48
    f lazy-provider.ts:134
    C lazy-provider.ts:170
    connect provider.ts:118
    connect indexeddb-provider.ts:19
    syncProviders main.ts:94
    initWorkspace main.ts:127
    main main.ts:152
    <anonymous> main.ts:155
```

### Anything else?

Error is probably caused like this. As they produce the same result in the dev-tools' indexeddb pannel, and raise the same error.

```ts
import {
  createIndexedDBProvider,
} from '@toeverything/y-indexeddb';

import { openDB } from 'idb';

import * as Y from 'yjs';

const yDoc = new Y.Doc({
  // we use `guid` as unique key
  guid: 'my-doc',
});

const provider = createIndexedDBProvider(yDoc, 'PLAYGROUND_DB');


(await openDB('PLAYGROUND_DB')).transaction('workspace', 'readwrite')
.objectStore('workspace');

provider.connect();
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
Do you know how to reproduce the issue? I think the error `DOMException: IDBDatabase.transaction: 'workspace' is not a known object store name` in your example is that you need to pass a upgradeDB function like the following to create object store first:

```ts
export function upgradeDB(db: IDBPDatabase<BlockSuiteBinaryDB>) {
  db.createObjectStore('workspace', { keyPath: 'id' });
  db.createObjectStore('milestone', { keyPath: 'id' });
}
```

However I think there is an obvious flaw that if the provider connects twice without disconnect, there could be dangling db connections. 🤔

**Comment by fourdim** [comment]
To reproduce this issue: open `https://blocksuite-toeverything.vercel.app/` in firefox.
The upgrade event is not fired in firefox.

**Comment by fourdim** [comment]
Closed by https://github.com/toeverything/blocksuite/pull/3824
