### ISSUE TITLE
Pin icon not sync with its actual state

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#3498]
While a collection is pinned and shown in the sidebar, the icon in the list of Saved Collection stays unchanged.

By the way, it seems it's helpful to always show the pin icon? @houjoe0829 

![CleanShot 2023-08-01 at 14 26 37@2x](https://github.com/toeverything/AFFiNE/assets/132558/a25937fa-11bf-495a-a512-f7fa881ce7cb)

**Comment by houjoe0829** [comment]
After being pinned, it should display as 'Unpin' and this feature should always be visible. What do you think? @xell

**Comment by xell** [comment]
> After being pinned, it should display as 'Unpin' and this feature should always be visible. What do you think? @xell 

By the contrast, I think the icon should display as 'Pinned'. And, while the cursor hovers over it, the icon will change to 'Unpin' to let the user know the result of clicking.

**Comment by houjoe0829** [comment]
> > After being pinned, it should display as 'Unpin' and this feature should always be visible. What do you think? @xell
> 
> By the contrast, I think the icon should display as 'Pinned'. And, while the cursor hovers over it, the icon will change to 'Unpin' to let the user know the result of clicking.

I agree, however, the only concern is that it may be difficult to differentiate between 'Pinned' and 'Pin to Sidebar' using icons. We can give it a try.

**Comment by hqwuzhaoyi** [comment]
I fixed the issue of the icon not changing in #3625.

However, if a Tooltip is added, it will look strange.

I'm thinking maybe we can add a delay, for example, the Tooltip will disappear after one second.

![image](https://github.com/toeverything/AFFiNE/assets/44605072/9010063d-8845-48d7-9c5e-c7ba592f8a75)

**Comment by zzj3720** [comment]
thanks @hqwuzhaoyi , great job!
