### ISSUE TITLE
Right margin of the scrollbar is too large in Settings' sidebar

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#3499]
It should be 1px.

![image](https://github.com/toeverything/AFFiNE/assets/132558/b1d70654-025b-4017-a9e5-aab36467ff28)

**Comment by xell** [comment]
> There is a sidebar adjustment bar here.
> 
> ![image](https://github.com/toeverything/AFFiNE/assets/102217452/fb955838-a121-4da9-bc7a-51945a8a576c)
> 
> 

@hwangdev97 how about this?

**Comment by Kaneki-Ken-7** [comment]
> It should be 1px.
> 
> ![image](https://user-images.githubusercontent.com/132558/257426092-b1d70654-025b-4017-a9e5-aab36467ff28.png)

I dont see any scrollbar in settings modal . 


https://github.com/toeverything/AFFiNE/assets/30045569/e24c1b9c-8aad-486c-b0c0-51f3ca622f48

**Comment by JimmFly** [comment]
> @hwangdev97 how about this?

Oh, sorry it was my mistake, I mentioned the scrollbar in the sidebar, not in the settings.

**Comment by JimmFly** [comment]
> > It should be 1px.
> I dont see any scrollbar in settings modal .

I think it's the old version of AFFiNE that has a native scrollbar, maybe you can use AFFiNE's scrollbar component. Could you please submit a PR? @Kaneki-Ken-7

**Comment by Kaneki-Ken-7** [comment]
> 

yes I can do that . I just wanted to know that I need to add scrollbar component and add 1px right margin to it in settings modal right? @JimmFly

**Comment by JimmFly** [comment]
> > 
> 
> yes I can do that . I just wanted to know that I need to add scrollbar component and add 1px right margin to it in settings modal right? @JimmFly

Yes, that's right, looking forward to your PR.

**Comment by Kaneki-Ken-7** [comment]
> > > 
> > 
> > 
> > yes I can do that . I just wanted to know that I need to add scrollbar component and add 1px right margin to it in settings modal right? @JimmFly
> 
> Yes, that's right, looking forward to your PR.

btw do you have the figma design of settings modal?
I am able to put the scroll bar at correct position but other elements may not be at same margin or width? so to check this I need to see the design

**Comment by Kaneki-Ken-7** [comment]
This is how it looks. @JimmFly 
do you want the scrollbar width the same as its on the main page?

https://github.com/toeverything/AFFiNE/assets/30045569/2d2c0d43-e855-40d4-a2eb-51ddfa24ad6f

**Comment by xell** [comment]
> btw do you have the figma design of settings modal?
> I am able to put the scroll bar at correct position but other elements may not be at same margin or width? so to check this I need to see the design

Please use this video (you can always pause it to read the details). We're sorry that our design layout and systems in Figma are not ready for open source.


https://github.com/toeverything/AFFiNE/assets/132558/85687b47-3f15-4c80-bff9-97eddaf86d3d

**Comment by Kaneki-Ken-7** [comment]
@xell can you check my PR?

**Comment by xell** [comment]
> @xell can you check my PR?

Our developers will look at it. Thank you for the contribution :-)
