### ISSUE TITLE
error boundary when network error

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3512]
AFFiNE Cloud issue

**Comment by himself65** [comment]
need @xell give a UI design first

**Comment by houjoe0829** [comment]
According to this morning's discussion, we will determine the final handling of synchronization errors and various states. We can confirm again after the design draft is finalized later.

**Comment by Svaney-ssman** [comment]
Check here for [Workspace type design](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=10978-179838&mode=design&t=mwX0mkLmcZOw1D8c-4)

Check here for [sync error toast](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=8113-155449&mode=design&t=mwX0mkLmcZOw1D8c-4l)

@himself65
