### ISSUE TITLE
​yarn dev fail

### ISSUE THREAD

**Issue by yujianhui1993** [toeverything/AFFiNE#3520]
### What happened?

we use master branch，**yarn workspace @affine/native build** success，**yarn dev** fail,  my attempt **yarn build:infra**，but fail,
<img width="812" alt="image" src="https://github.com/toeverything/AFFiNE/assets/7228360/f60d5797-b0b6-4e71-b170-48f3800bd4c1">

<img width="829" alt="image" src="https://github.com/toeverything/AFFiNE/assets/7228360/6bce183d-8183-477b-a02b-5afaed7743de">
What is the problem。I haven't found a corresponding solution。Who can tell me how to solve it? Thank you

### Distribution version

macOS x64 (Intel)

### Relevant log output

```shell
NX   Running target build for 2 projects
    ✖  nx run infra:build
       failed to load config from /Users/yumeiren/Documents/myProject/AFFiNE/packages/infra/vite.config.ts
       
        >  NX   Unexpected token '??='
       
          Pass --verbose to see the stacktrace
 
>  NX   Ran target build for 2 projects (8s)
 
    ✔    0/2 succeeded [0 read from cache]
 
    ✖    2/2 targets failed, including the following:
         - nx run infra:build
         - nx run plugin-infra:build
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Can you try yarn nx reset

**Comment by Brooooooklyn** [comment]
>  NX   Unexpected token '??='

@yujianhui1993 upgrade your Node.js to latest LTS version

**Comment by yujianhui1993** [comment]
> > NX   Unexpected token '??='
> 
> @yujianhui1993 upgrade your Node.js to latest LTS version

thanks，It's already successful
