### ISSUE TITLE
Add simple password protection for note content

### ISSUE THREAD

**Issue by greedyhao** [toeverything/AFFiNE#3521]
### Description

The client that periodically locks notes requires a password to access the client
This timing can be configured
This password can also be used to protect some critical data
Refer to anytype's pin code feature

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you for your feedback. Are you hoping to lock individual notes or the entire client? What product are you currently using this feature on?

**Comment by houjoe0829** [comment]
Thank you again for your feedback. We have recorded this requirement, but there is currently no specific release date.

**Comment by EYHN** [comment]
Use https://github.com/toeverything/AFFiNE/issues/5491
