### ISSUE TITLE
Long title pushes and dislocates the buttons

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#3533]
It seems the width of Title needs a `max-width` or something And, of course the max width should consider the responsive layout setup in [internal PRD link](https://toeverything.feishu.cn/wiki/wikcnHv8944ZsglP1JnU27wGPBc)

![image](https://github.com/toeverything/AFFiNE/assets/132558/31c4ae8a-c7d9-4fe3-b8fd-fa12b6cf03b5)

**Comment by JimmFly** [comment]
Close with https://github.com/toeverything/AFFiNE/pull/3550
