### ISSUE TITLE
Switching animation

### ISSUE THREAD

**Issue by zanwei** [toeverything/AFFiNE#3548]
### **Description**

**Now**: The animation loops when the cursor hovers over the icon.

**Should**: When the cursor hovers over the icon, it should only play **once**, and when it hovers over the icon again after the cursor has been removed, the animation plays once more.

![Image](https://github.com/toeverything/AFFiNE/assets/40333372/ca69ec29-102c-4f23-8f4c-426ab1be4c87)

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Other

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/commit/3282344d4a2931c61642b224ed143bad1707e233
