### ISSUE TITLE
Switching animation​

### ISSUE THREAD

**Issue by zanwei** [toeverything/AFFiNE#3549]
### **Description**

**Now:** The animation loops when the cursor hovers over the icon
**Should:** Should only play **once** when the cursor hovers over the icon

https://github.com/toeverything/AFFiNE/assets/40333372/3b13d244-5f0c-45db-9848-47f28ac146cb

### Distribution version

macOS x64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Other

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/commit/3282344d4a2931c61642b224ed143bad1707e233

**Comment by himself65** [comment]
Sorry, this commit https://github.com/toeverything/AFFiNE/commit/3a0797955c3bc264d83159233cfba5c7cff91d9a
