### ISSUE TITLE
Please add text editor, let us can edit text style

### ISSUE THREAD

**Issue by readthecodes** [toeverything/AFFiNE#3554]
### Description

Please add text editor, let us can edit selected text style, like edit text color etc.
The usability of this tool will be significantly reduced if we can't edit selected text style

### Use case

edit selected text style, like edit text color etc.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by readthecodes** [comment]
Please complete the most basic writing functions first, such as editing the style of the selected text

**Comment by houjoe0829** [comment]
Thank you for your feedback. We have plans to prioritize supporting text highlighting. May I ask in what scenarios do you usually need to modify text color? Also, besides text color settings, is there anything else you hope to be supported?

**Comment by JimmFly** [comment]
This feature has been implemented in the latest version, please try it.
