### ISSUE TITLE
unexpected output files

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3559]
This might be a typescript related issue

https://github.com/toeverything/AFFiNE/pull/3557#issue-1835355016

**Comment by kanweiwei** [comment]
I'll do it.

**Comment by himself65** [comment]
> I'll do it.

Thank u!

**Comment by Anny023** [comment]
Is it still open?

**Comment by Raaaaaahul** [comment]
can you specify the issue in more detail

**Comment by dipshikha-adhikari** [comment]
I'm gonna fix it.

**Comment by pengx17** [comment]
I think this issue is related to a removed module "sdk". Not sure if it is still an issue
@dipshikha-adhikari feel free to open a new one if you plan to file a pr for it.
