### ISSUE TITLE
[improvement]: proxy on sub folder

### ISSUE THREAD

**Issue by ghost** [toeverything/AFFiNE#357]
### 1~3 main use cases of the proposed improvement

I have a lot of service in my private server and use nginx proxy access these in sub folder
just support a base URL and add nginx proxy example for deploy

### Ideas for solution

Add base URL for static assets and api

### what types of users can benefit from using your proposed improvement

Some one has a server but do not have subdomain

**Comment by ClonkDroid** [comment]
+1

**Comment by rafaeluriarte** [comment]
+1

**Comment by clemrdh** [comment]
Hey !
Has this been implemented yet ? 
Just installed AFFiNE and sturggling to find how to install it under a subfolder !?

**Comment by darkskygit** [comment]
> Hey ! Has this been implemented yet ? Just installed AFFiNE and sturggling to find how to install it under a subfolder !?

For security reasons, there are no plans to move forward for now.
