### ISSUE TITLE
​Full width Layout

### ISSUE THREAD

**Issue by Avey777** [toeverything/AFFiNE#3571]
### Description

![image](https://github.com/toeverything/AFFiNE/assets/35259040/ec2b81d6-73f2-413c-bd53-8ed3631dae26)

I hope the Full-width Layout feature can be set on a separate page instead of enabling it globally.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you very much for your feedback. We don't have this plan for now, but we will collect similar feedback and review it again in the future. For now, we will temporarily close this feedback. If you have any questions, you can always reopen it.
