### ISSUE TITLE
flaky test `database is useable`

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3587]

**Comment by SandeepJoel** [comment]
@himself65 Can you please provide some inputs on what this issue is all about ?

**Comment by himself65** [comment]
> @himself65 Can you please provide some inputs on what this issue is all about ?

You can run the test in your local machine, something it will fail(which mean flaky test)

**Comment by JimmFly** [comment]
This appears to be an issue with upstream slash menus, which is being fixed. /cc @lawvs

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/actions/runs/5836387492/job/15829920282

**Comment by himself65** [comment]
> This appears to be an issue with upstream slash menus, which is being fixed. /cc @lawvs

I think we shouldn't create a database in the slash menu in e2e. instead, we should use `addBlock` directly

**Comment by EYHN** [comment]
The part of the product that was causing this issue has been removed or significantly reworked since it was created.
