### ISSUE TITLE
[feature]: Support the drawing of flow chart

### ISSUE THREAD

**Issue by Avey777** [toeverything/AFFiNE#359]
1、作为一个PM 我希望一些简单的流程图可以在APPINE完成。这样我在不用切换工具的情况下，可以愉快的和我的客户沟通
2、最好可以有泳道图

**Comment by tzhangchi** [comment]
Thank you for your feedback，we are planning it，can you give some favarive diagram tools？

**Comment by May-Yaha** [comment]
> Thank you for your feedback，we are planning it，can you give some favarive diagram tools？

drawio？ https://github.com/jgraph/drawio

**Comment by Avey777** [comment]
yes, I like it

**Comment by Avey777** [comment]
Mind map Support

refer to：
https://github.com/my-mind/my-mind.github.io
https://github.com/hizzgdev/jsmind

**Comment by Avey777** [comment]
> > Thank you for your feedback，we are planning it，can you give some favarive diagram tools？
> 
> drawio？ https://github.com/jgraph/drawio

思维导图准备自研还是基于开源？
推荐一个：https://github.com/fex-team/kityminder

**Comment by xseth** [comment]
The only thing missing from this incredible application is drawio

**Comment by stone-yu** [comment]
> The only thing missing from this incredible application is drawio

+1
