### ISSUE TITLE
developer document need update

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3593]
```[tasklist]
### Basic
- [ ] how to build @affine/core
- [ ] how to build @affine/electron
- [ ] the concept of AFFiNE
- [ ] debug with blocksuite
- [ ] how to setup @affine/server
- [ ] run in docker
- [ ] how to contribute
- [ ] how to use @affine/storybook
```

```[tasklist]
### Plugins(WIP)
- [ ] @affine/sdk
- [ ] how to create a plugin
- [ ] plugin restriction
```

**Comment by imSuMN** [comment]
@himself65  Can you guide my what to do? I am new to open source (!coding)😄

**Comment by teobler** [comment]
![affine](https://github.com/toeverything/AFFiNE/assets/26424691/ba2cec1c-7a6a-42b9-9138-85c8dd910749)

To understand affine's high level concepts and infra, I made a draft diagram refer to source code based on my own understanding, if this is helpful, I can complete it and share to community.

**Comment by HeJiachen-PM** [comment]
> ![affine](https://user-images.githubusercontent.com/26424691/259272085-ba2cec1c-7a6a-42b9-9138-85c8dd910749.png)
> 
> To understand affine's high level concepts and infra, I made a draft diagram refer to source code based on my own understanding. There maybe something wrong, but if this is helpful, I can complete it first, then someone from team can help me to review it, after that we can share it with community.

Hello teobler, your diagram looks amazing and in general good to me. Regarding your questions:
1. No indeed. The cloud is optional.
2. Correct but we hope the indexDB can be replaced with SQLite wrapped by octobase in the electron client.
3. This is a major place that needs to be better built by an application data layer and state management tools, to where @himself65 @Brooooooklyn may have many things to add.
4. Currently a plugin system, a complete data driven layer, and cloud support.
5. In general, we hope our plugins can be similar to vscode's plugins where it is hosted on a dedicated plugin store, and its access to data and the network can be totally controlled by the plugin system.

I'd better leave the rest part to other members. Hope this great diagram can be spread for the good of others as well!

**Comment by teobler** [comment]
> > ![affine](https://user-images.githubusercontent.com/26424691/259272085-ba2cec1c-7a6a-42b9-9138-85c8dd910749.png)
> > To understand affine's high level concepts and infra, I made a draft diagram refer to source code based on my own understanding. There maybe something wrong, but if this is helpful, I can complete it first, then someone from team can help me to review it, after that we can share it with community.
> 
> Hello teobler, your diagram looks amazing and in general good to me. Regarding your questions:
> 
> 1. No indeed. The cloud is optional.
> 2. Correct but we hope the indexDB can be replaced with SQLite wrapped by octobase in the electron client.
> 3. This is a major place that needs to be better built by an application data layer and state management tools, to where @himself65 @Brooooooklyn may have many things to add.
> 4. Currently a plugin system, a complete data driven layer, and cloud support.
> 5. In general, we hope our plugins can be similar to vscode's plugins where it is hosted on a dedicated plugin store, and its access to data and the network can be totally controlled by the plugin system.
> 
> I'd better leave the rest part to other members. Hope this great diagram can be spread for the good of others as well!

Wow, thanks for replying. Actually notes on right bottom just for myself, some of questions I already got the answer, some of not, but you already gave the answer I want. Since this diagram still a very draft version, need add many details. I will finish it at my off hours and back here~

**Comment by teobler** [comment]
![affine](https://github.com/toeverything/AFFiNE/assets/26424691/81e2a06a-c4d5-49f7-b791-344f5e27703c)

Latest version updated, modify something which changed during previous weeks, and fixed something which is incorrect. If all okay, I can push it to a new doc maybe named 'Introduction' or 'Concepts'?

**Comment by himself65** [comment]
If you are talking about a milestone in y-indexeddb. It captures the snapshot for a single doc. I wanted to implement something like git history in AFFiNE but we don't have much time.
