### ISSUE TITLE
add the content menu function for title side

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#3602]
### Description

![shot-2023-08-07-16 19 26@2x](https://github.com/toeverything/AFFiNE/assets/24713927/f696220f-48b2-4485-89f0-ff7b2adcd388)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
@doodlewind BTW there's an existing error when you double-click the title in the latest Canary

**Comment by JimmFly** [comment]
The function of adding tags requires upstream support. /cc @zzj3720

**Comment by QiShaoXuan** [comment]
@xell Now only the function of Add Tag is missing. I think we can open a new issue for recording and assign it to @zzj3720

**Comment by xell** [comment]
> @xell Now only the function of Add Tag is missing. I think we can open a new issue for recording and assign it to @zzj3720

@houjoe0829 If the "Add Tag" function will be implemented in another issue, I think this one could be closed as long as the UI part is confirmed.

**Comment by houjoe0829** [comment]
Close with another follow-up https://github.com/toeverything/AFFiNE/issues/3867
