### ISSUE TITLE
Support renaming in the titlebar

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#3603]
### Description

![shot-2023-08-07-16 29 36@2x](https://github.com/toeverything/AFFiNE/assets/24713927/3f0e43d2-c97d-41cb-ace0-0d11cebadd43)

Automatically confirm the renaming status after losing focus

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xell** [comment]
Closed as a duplicate with #2645
