### ISSUE TITLE
fix global types in the root `tsconfig.json`

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3647]
I found that the `node` and `dom` are in the same environment.

**Comment by sumanthsumu1418** [comment]
Hii, would love to fix this

**Comment by himself65** [comment]
> 

If you want to work on this, you can try to remove `DOM` here and see the type errors

https://github.com/toeverything/AFFiNE/blob/bbd49252cf1335f801b823705765f741f3fc8bb5/tsconfig.json#L44

**Comment by sumanthsumu1418** [comment]
yeah sure

**Comment by ManishDait** [comment]
Hi @himself65 I would like to work on these issue, if it is still open.

**Comment by himself65** [comment]
Yeah, thanks to all of you guys.

Let me explain more, currently, you will see that `setTimeout` and `setInternal` will return `Node.Timer` instead of `number`. That's a bug

**Comment by Asish-AP** [comment]
> `setInternal`

Do u mean setInterval ?

**Comment by himself65** [comment]
> > `setInternal`
> 
> Do u mean setInterval ?

oh yes

**Comment by EYHN** [comment]
Not planned
