### ISSUE TITLE
​Sorry.. there was an error Integer out of RangeSorry.. there was an error Integer out of Range

### ISSUE THREAD

**Issue by kmq116** [toeverything/AFFiNE#3649]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/59247607/fa51ea0c-07f8-4401-b8d4-0191f08306b0)
The software won't open，I want to know why

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Are you the first to open the app? Could you please give more detail of the issue

**Comment by himself65** [comment]
It's an error from `lib0`, so it might be related to the data persistence. I think we need to check sqlite or indexeddb 

Do you have any idea of how to get the data? @pengx17

**Comment by kmq116** [comment]
> Are you the first to open the app? Could you please give more detail of the issue

This is not the first time I have opened affine, I have been using affine for more than a month, my desktop computer restarted yesterday, and when I opened the software again today, this problem occurred, and I don't know how to solve it. I tried to uninstall and reinstall the software, then import my backup workspace file, and it was ready to use

**Comment by himself65** [comment]
Have you upgraded the AFFiNE version, from 0.6.x to 0.7.x?

**Comment by kmq116** [comment]
> Have you upgraded the AFFiNE version, from 0.6.x to 0.7.x?

The problem version is 0.6 , then I uninstall 0.6 and install 0.7 the problem is disappeared
I think I uninstall 0.6 and reinstall 0.6 ，The problem will also disappear

**Comment by himself65** [comment]
Thanks for the response. I think there do have some issues in 0.6.0.

I think you directly install 0.7.0 and bugs will also be fixed.

Keep the latest stable version installed.
