### ISSUE TITLE
[bug]: The render behavior for bold text is not correct

### ISSUE THREAD

**Issue by Zheaoli** [toeverything/AFFiNE#365]
### To Reproduce

1. Input usual text like **abc**
2. Enter a space char after the text
3. You will find the space char seems like double width

### Screenshots

https://user-images.githubusercontent.com/7054676/188265939-f3aae266-20a6-4e0b-8c5d-ffc90f815464.mov

**Comment by Pranav4399** [comment]
I can look into this bug. Please assign it to me if no one else is working on this already.

**Comment by lawvs** [comment]
@Pranav4399 Great, you are welcome to work on this. We'd love to have your contribution.

**Comment by mola-molaa** [comment]
seems that slate contenteditable container unexpectedly kept the space char while react flush the correct data and render the TextString Component ? 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/115395695/194853283-e22ef4b8-2fb2-4ad4-b3a4-4286506e56a8.png">
