### ISSUE TITLE
​Sorry.. there was an error Page error Cannot find page 8HoViCf_QT in workspace OPjhtxMAiqrefresh Please copy the following information and send it to the developer.

### ISSUE THREAD

**Issue by kmq116** [toeverything/AFFiNE#3658]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/59247607/44fc2900-9d2b-4e10-a974-94aaa967039c)
red line code:
path: /workspace/OPjhtxMAiq/all
query: {"workspaceId":"OPjhtxMAiq"}
currentWorkspaceId: OPjhtxMAiq
currentPageId: all
metadata: [{"id":"OPjhtxMAiq","flavour":"local","version":2}]

在文章中点击移到垃圾箱
![image](https://github.com/toeverything/AFFiNE/assets/59247607/98f179bb-5044-4904-80b1-f8a8f2b63de4)
再点击 永久删除 按钮
![image](https://github.com/toeverything/AFFiNE/assets/59247607/da9d6a9b-8b55-479d-94ac-0969e233a8f4)
然后就崩溃了，数据也损坏了，之前写的一堆东西丢了一大堆
![image](https://github.com/toeverything/AFFiNE/assets/59247607/c23ef34a-f6dd-434a-9787-aad5f263207b)

软件版本 0.7+ 稳定版

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
What's the version?

**Comment by kmq116** [comment]
> What's the version?

软件版本 0.7+ 稳定版
我上面有写😢

**Comment by himself65** [comment]
> 

你是不是删除过page，然后开始写东西？

**Comment by himself65** [comment]
> 然后就崩溃了，数据也损坏了，之前写的一堆东西丢了一大堆

This might be unrelated to this issue. I didn't see the data loss because of deletion

**Comment by kmq116** [comment]
> > 
> 
> 你是不是删除过page，然后开始写东西？

是的，有删除过
