### ISSUE TITLE
[bug]: The number list can not create item  continuous after create sub number list

### ISSUE THREAD

**Issue by Zheaoli** [toeverything/AFFiNE#366]
### To Reproduce

Just see the video recording

https://user-images.githubusercontent.com/7054676/188266181-587ac666-693b-4f0e-ad85-10d9fb20deba.mov

You can compare with [yuque](https://www.yuque.com/)

https://user-images.githubusercontent.com/7054676/188266200-89f6145a-0a18-40ab-9eef-f1bfd5425a50.mov

**Comment by lawvs** [comment]
I think this is expected behavior. If you want to create continuous items, you can try to use `shift+Tab` to go back.
