### ISSUE TITLE
Single page sharing design updated

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#3661]
Single page sharing design has been upgraded, affecting the title bar, affine cloud, export, and read-only mode.
 This also relates to [#3287 ](https://github.com/toeverything/AFFiNE/issues/3287)

Here is the [design](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=534-15310&mode=designl)

![Image](https://github.com/toeverything/AFFiNE/assets/110808979/a380a1ac-4769-4637-8d41-f3993c8a2924)

**Comment by joooye34** [comment]
we need to implements this feature new iteration.

**Comment by Svaney-ssman** [comment]
[UI adjusted in figma](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=11259-179690&mode=design&t=X2I8cTOzbj4WEew0-4)
@JimmFly

**Comment by houjoe0829** [comment]
List the outline of the UI upgrade
1. The panel UI of Share page has been changed.
2. The UI of Publicly shared pages has been slightly modified, but the main reason is that the previous development work has not restored the design draft effect, including mobile adaptation.

**Comment by JimmFly** [comment]
Does it sound like the content of this PR#4584  ？

**Comment by JimmFly** [comment]
https://github.com/toeverything/AFFiNE/pull/4856 Close as completed
