### ISSUE TITLE
sqlite db migration on adding should follow the same migration steps of idb

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#3662]
### What happened?

I noticed that workspace after importing an old DB file will resulting in "Error: In workspace data, the block flavour affine:surface@3 is outdated. Please downgrade the editor or try data migration." error.

Right now the migration logic is mainly for idb (in `boostrap/setup.ts`). The logic mangles workspace/datasource/ydoc together and lacks abstraction that can be reused.

We want the migrations can work seamlessly for both idb/sqlite. Or in the short term, sqlite may need to replicate the logic in `boostrap/setup.ts` but for sqlite.

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
cc @himself65 
not sure how cloud handles data migration? @Brooooooklyn

**Comment by Brooooooklyn** [comment]
Cloud will reuse the JavaScript migration logic implemented in AFFiNE, so you should consider making it isomorphic.

**Comment by pengx17** [comment]
+1 to isomorphic

**Comment by himself65** [comment]
I will abstract it to infra package
