### ISSUE TITLE
[feature]: Embed Twitter in AFFiNE

### ISSUE THREAD

**Issue by XHXIAIEIN** [toeverything/AFFiNE#367]
### 1~3 main use cases of the proposed feature

1. Preview Twitter threads videos and GIFs

**Comment by CJSS** [comment]
Does this feature require Twitter's API?

**Comment by Philipinho** [comment]
> Does this feature require Twitter's API?

No, Twitter embed does not require the API. See https://publish.twitter.com.

**Comment by tzhangchi** [comment]
@Philipinho Thank you for your continuous attention to AFFiNE. In the latest https://github.com/toeverything/AFFiNE/releases/tag/v0.7.0-canary.8 version, we have started internal testing of the  Embed Twitter in AFFiNE function, and hope you can experience it and give us feedback

**Comment by joebeijing** [comment]
> Thanks for the update, I gave it a try. But the embed block doesn't seem to contain useful information.
> 
> ![Snipaste_2023-06-06_18-40-11](https://user-images.githubusercontent.com/45864744/243668140-fc511281-7c20-457d-8ea8-56d93d257c8b.png)
> 
> It would be even better if could get a preview video, picture, gif of the Tweet when you Add it.(You can refer to discord to send a preview of the twitter link in the channel.)

Currently, the Bookmark function only displays the meta information of the links in a richer format and does not support previewing. The feature you mentioned may be this one (https://github.com/toeverything/blocksuite/issues/2313) within our plan and we will keep you updated.
