### ISSUE TITLE
​invisible unicode for dynamicImportKey

### ISSUE THREAD

**Issue by Garfield550** [toeverything/AFFiNE#3692]
### What happened?

Is this what was expected?
<img width="599" alt="image" src="https://github.com/toeverything/AFFiNE/assets/3471836/799147c9-a782-4600-bb45-0763f8251eb1">

![49D1563C-17C6-45E8-889B-255B3783BEB2](https://github.com/toeverything/AFFiNE/assets/3471836/8e9f0a58-2180-4606-84e1-06a495ec1164)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Garfield550** [comment]
cc @himself65

**Comment by himself65** [comment]
I've reverted the commit since I realize that the reason is the output from our compiler has the invisible char.

I think you should open a PR in upstream (ses)

https://github.com/toeverything/AFFiNE/pull/3842
https://github.com/toeverything/AFFiNE/issues/3840

**Comment by Garfield550** [comment]
Looks like it was intentional.

https://github.com/endojs/endo/blob/b288b593b87eff6054c1e94122e24c6e9a79b1a6/packages/static-module-record/src/hidden.js#L1-L2
