### ISSUE TITLE
workspace name not saving​

### ISSUE THREAD

**Issue by ritatzhang** [toeverything/AFFiNE#3699]
### What happened?

cmd+s doesn't work to save workspace name, also no obviously visible save button (?)

also, missing space in description: "Only an owner can edit the the Workspace avatar and name.Changes will be shown for everyone."

beta version

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
I think there is a yes button on the right side.

![image](https://github.com/toeverything/AFFiNE/assets/14026360/8d53f9a6-2c19-49dd-8c32-0096771496da)

/cc @houjoe0829

**Comment by ritatzhang** [comment]
> I think there is a yes button on the right side.
> 
> ![image](https://user-images.githubusercontent.com/14026360/260144278-8d53f9a6-2c19-49dd-8c32-0096771496da.png)
> 
> /cc @houjoe0829

<img width="455" alt="image" src="https://github.com/toeverything/AFFiNE/assets/55301871/602c2410-0060-40c9-b047-2c069531e954">
I really think that the argument can be made that this doesn't look like a button and just looks like a signal to users that the username is available. also the username box is not align with the avatar circle. i'm sorry these are really nitpick-y but they're just things that I noticed.

I really really appreciate you telling me how to save though, I just renamed my demo workspace for the very first time! thanks again!

**Comment by houjoe0829** [comment]
1. It is suggested that during the editing process, both the "Enter" key and the "CMD/Ctrl + S" shortcut can be used to save the modified name.( CMD: Mac, Ctrl : Win)  @himself65 
2. After AFFiNE Cloud is back online, we will add corresponding instructions: only the owner of the Workspace can modify the name.
