### ISSUE TITLE
test case needed for linked pages

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3707]
Add some test cases for this PR https://github.com/toeverything/AFFiNE/pull/3702

- [x] linked page with paragraph blocks
- [ ] linked page with list blocks
- [ ] linked page with database block
- [ ] linked page with complex blocks

**Comment by Asish-AP** [comment]
Hey @himself65 can you just explain it with some more details ? I would love to work on this

**Comment by himself65** [comment]
> Hey @himself65 can you just explain it with some more details ? I would love to work on this

Yes, the thing is, we need to test whether linked pages are displayed in the sidebar

![image](https://github.com/toeverything/AFFiNE/assets/14026360/6878987e-9dcb-4d88-8eea-25a617461d6a)

**Comment by Yashh56** [comment]
Hi @himself65  I would like to work on this issue, if it is still open can you explain in deep? I am new to Open Source.
