### ISSUE TITLE
Set `Client Border Style` to false by default on Windows platform

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3714]
It's ugly on Windows

**Comment by AlfredRufus** [comment]
Hey can I solve  this issue. Can you explain  this more clearer

**Comment by shiivamtaneja** [comment]
Hi @himself65  does the issue still persists?

**Comment by Noothan-am** [comment]
is this issue still open?

**Comment by himself65** [comment]
This still open, yeah

**Comment by hwangdev97** [comment]
Windows does not support Mica/Acrylic materials, so I think this option can be turned off by default 

About Mica/Acrylic https://github.com/toeverything/AFFiNE/issues/2399

**Comment by shiivamtaneja** [comment]
Hi @himself65 can you explain about this issue? what exactly u mean by it?

**Comment by himself65** [comment]
I mean just set `client border style` to false by default if `environment.isWindows` is true. This doesn't mean that always set to false when the user refreshes the page(so this is incorrect https://github.com/rohitpawalia/AFFiNE/commit/83de93fe6828578f24703167f0bb5916769e58d3). Just the "default setting"

**Comment by Asish-AP** [comment]
> 



> I mean just set `client border style` to false by default if `environment.isWindows` is true. This doesn't mean that always set to false when the user refreshes the page(so this is incorrect [rohitpawalia@83de93f](https://github.com/rohitpawalia/AFFiNE/commit/83de93fe6828578f24703167f0bb5916769e58d3)). Just the "default setting"

You're suggesting that , This change should only apply to the initial appearance and shouldn't persist if the user refreshes the page. Please do correct me if I am wrong I am new to Open Source
