### ISSUE TITLE
Too narrow at the bottom on setting footer

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3715]
![image](https://github.com/toeverything/AFFiNE/assets/14026360/04c62da0-7e98-46d9-9cf5-387c28effc49)

**Comment by Shikha1234** [comment]
Try to zoom out. I don't see the issue. Can you please elaborate if the issue still persists. Thanks

**Comment by ideakaran** [comment]
@himself65 
I have created a PR here https://github.com/toeverything/AFFiNE/pull/3717

**Comment by himself65** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/14026360/9b0d7908-5c7d-472b-bc19-64f24f05b6ee)

Things fixed. Thanks to @ideakaran
