### ISSUE TITLE
Record last read position​ of every page, and show the last read position when next open page

### ISSUE THREAD

**Issue by Mojicode** [toeverything/AFFiNE#3719]
### Description

As the title show above, it is very convenient. Hope you guys think about it, thank you.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you very much for your feedback. AFFiNE currently does not have plans for this feature in the short term. However, we have added it to our list of requirements and will re-evaluate it later. For now, we will temporarily close this issue, but please feel free to reopen it if you have any questions.
