### ISSUE TITLE
Pre-load content opens doc in wrong mode

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#3731]
There are several docs that should be set to Edgeless Mode and open in Edgeless Mode directly (not to open in Page mode).

These include:
`AFFiNE - not just a note taking app`
`Travel Plan`

**Comment by ShortCipher5** [comment]
@Yanxi0202 to check the workspace for any other pages.

**Comment by Yanxi0202** [comment]
Other pages are fine, here is pre-set Mode for each pages. 
![Image](https://github.com/toeverything/AFFiNE/assets/134897361/7e3489d4-8970-4021-a609-6c1b3a106133)
