### ISSUE TITLE
AFFiNE cloud data migration

### ISSUE THREAD

**Issue by thorseraq** [toeverything/AFFiNE#3732]
```[tasklist]
### Tasks
```

**Comment by himself65** [comment]
I'm moving the migration logic into the infra layer. Hope I can do it soon

**Comment by thorseraq** [comment]
Currenly I directly used the subdoc part:

[const migratedDoc = migrateToSubdoc(originalDoc);](https://github.com/toeverything/AFFiNE/pull/3869/files#diff-7ba6fdc4e7e512e75f1065acbbec41d5f0a2f918f6a2907548779cec658532faR24)
