### ISSUE TITLE
The "recent pages" list​ doesn't update

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#3748]
### What happened?

After creating new page or visiting old pages, the "Recent" list still doesn't get updated.

https://github.com/toeverything/AFFiNE/assets/7312949/8ee0f330-0e78-4e8e-a12d-ee83ef7547bc

Version: latest internal

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ideakaran** [comment]
@himself65 I created a PR for this ticket here https://github.com/toeverything/AFFiNE/pull/3848
but not really sure if I put the change in the right area or not (and not even sure if the change is correct or not).
 It does solve the issue. I see the page in the recent list now.

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/pull/3848
