### ISSUE TITLE
Page options inconsistency

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#3756]
From the drop down in page (next to title) there are extensive page options. None of these options are available in the All Page view.

**Comment by houjoe0829** [comment]
In fact, there is no strict rule that all options must be placed in the Page Options list. However, we can put the 'Export' and 'Duplicate' options out. But is it feasible to put out the 'Export' option without opening the corresponding page? @zuoxiaodong0815  needs to confirm this first.

**Comment by zuoxiaodong0815** [comment]
can not export without opening the corresponding page.

**Comment by houjoe0829** [comment]
Please add "Duplicate" option here @QiShaoXuan 
![CleanShot 2023-08-21 at 17 58 05@2x](https://github.com/toeverything/AFFiNE/assets/22443345/09f4f6be-cf7d-423b-9ce5-72759ec467dd)
