### ISSUE TITLE
Page option features import

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#3758]
The page option features an import function. However this import function is for inserting pages and not a sub-feature or action that will impact the current page.

It should be considered to keep the import function restricted to non-specific page areas - such as all pages. As "import" within the page may insinuate importing an image, video or other asset.

![Image](https://user-images.githubusercontent.com/4605025/260635200-c10daf82-884e-4c4f-b585-1c8a3b40ec23.png)

**Comment by hwangdev97** [comment]
I think this idea is right. Perhaps we should consider removing the import option . What do you think, @houjoe0829 ?

**Comment by houjoe0829** [comment]
Putting 'import' next to the 'export' entry, or even adding 'new page', are common operations and are not strictly limited to page-level operations. I tend to maintain the status quo. I will close this issue for now, but feel free to reopen it if there are any further questions. @ShortCipher5 @hwangdev97
