### ISSUE TITLE
Pre-load content for each new workspace comes with added burden

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/AFFiNE#3760]
The new preload content is more of a workspace than a single introductory page.

Without any multi-select and multi-action features within the All Pages view there is a significant burden on going through to delete those files.

The current implementation is very unfriendly to users who have to delete over 10 pages whenever they start a workspace.

**Comment by houjoe0829** [comment]
There is already a duplicated requirement in the backlog, but it is not within the scope of this phase. I will close this issue for now, but we will follow up in this issue later.  https://github.com/toeverything/AFFiNE/issues/2305
CC @xell
