### ISSUE TITLE
Not compatible with `next-auth` 4.23.x

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3785]

**Comment by Sarvesh521** [comment]
Can I work on this issue?

**Comment by himself65** [comment]
You are welcome on this. Please check apps/server

**Comment by Sarvesh521** [comment]
This is my first attempt in contributing to open source. The error is in apps/server/src/modeuls/auth/service.ts right ?

**Comment by himself65** [comment]
right, i think they changed the api

**Comment by EYHN** [comment]
The part of the product that was causing this issue has been removed or significantly reworked since it was created.
