### ISSUE TITLE
​Can't open the latest canary version

### ISSUE THREAD

**Issue by jizhi0v0** [toeverything/AFFiNE#3793]
### What happened?

![CleanShot 2023-08-17 at 09 50 42@2x](https://github.com/toeverything/AFFiNE/assets/57976101/9cdc98e2-cab0-49af-bd67-70e944115671)

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/AFFiNE/commit/ef7ad4f111e671752952bf5652da97a6cf4b2783

Please wait for 0.8.0-canary.25

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/releases/tag/v0.8.0-canary.25

**Comment by jizhi0v0** [comment]
It works.Thanks!
