### ISSUE TITLE
"A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by elderhammer** [toeverything/AFFiNE#3796]
### What happened?

<img width="507" alt="Screenshot 2023-08-17 at 10 55 01" src="https://github.com/toeverything/AFFiNE/assets/81279860/359ff9fd-39ac-47df-bfdf-9667a8727362">

Version of AFFiNE-canary:
<img width="278" alt="Screenshot 2023-08-17 at 10 55 31" src="https://github.com/toeverything/AFFiNE/assets/81279860/2dc1ba7a-b7b7-4da2-987c-0c40d8b88590">

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Same as https://github.com/toeverything/AFFiNE/issues/3793

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/releases/tag/v0.8.0-canary.25
