### ISSUE TITLE
After closing the window (not quitting), can not open the AFFiNE window again.

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#3831]
Especially in macOS, if you click the close button of the window to close it, you won't be able to open it again at least by the menu. However, in some cases, clicking the Dock icon might open the window again.

https://github.com/toeverything/AFFiNE/assets/132558/841d7540-91a6-40ae-a344-ace39df6f48c

**Comment by kanweiwei** [comment]
can not reproduce

**Comment by houjoe0829** [comment]
I can still reproduce this issue in internal version(0.0.0-internal.20230823192451-0051439).
And i can't activate AFFiNE window from Mac Dock.
