### ISSUE TITLE
support affine://new?content=xxx​

### ISSUE THREAD

**Issue by m1911star** [toeverything/AFFiNE#3832]
### Description

I am working on a web clipper plugin(not in affine system), So I need to add content from outside the app

Here is the obsidian way

![telegram-cloud-photo-size-5-6258059567418160870-y](https://github.com/toeverything/AFFiNE/assets/4948120/671e5124-bde4-4538-b3cc-8b4c4b890475)

so we can try to implement affine://new?content=xxx protocal
also，for different version of affine
```
affine://new?content=xxx  // for stable
affine-canary://new?content=xxx
affine-beta://new?content=xxx
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Would you like to work on this? I think this is much easiler

**Comment by m1911star** [comment]
> Would you like to work on this? I think this is much easiler

Yes

**Comment by gotjoshua** [comment]
are there plans for an "API" layer anyway? the url handling "should" be one interface to hit an API endpoint...

**Comment by himself65** [comment]
Related:
https://github.com/toeverything/AFFiNE/blob/57950204031c4465fbba9c2987b2bf841d447fa6/apps/electron/src/main/index.ts#L41-L43
