### ISSUE TITLE
​ReferenceError: $h‍_import is not defined

### ISSUE THREAD

**Issue by dengquan** [toeverything/AFFiNE#3840]
### What happened?

<img width="1440" alt="hello_world_plugin" src="https://github.com/toeverything/AFFiNE/assets/3711119/209b9edc-439b-47b6-88bc-10c362f7209a">

1 enable hello_world_plugin
2 open a new page

Both browser and desktop distributions have this problem.

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
What's the version?

**Comment by himself65** [comment]
Oh I saw the bug. Let me handle this

**Comment by himself65** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/14026360/8fd9dd36-3513-4efb-83cd-a33ae60b466a)

Seems like the is a bug in the compiler
