### ISSUE TITLE
​add toast messages inside Trash files

### ISSUE THREAD

**Issue by Noothan-am** [toeverything/AFFiNE#3846]
### Description

When I click on "Restore" or "Delete" in the trash list page, a toast message is displayed. However, if I have already opened the page and then attempt to restore or permanent delete a page, the toast message for the restoration and permanent deletion does not appear.  So, I have to navigate back to the trash files to confirm whether the page has been successfully restored or not.

### Anything else?

Actual behavior 
https://github.com/toeverything/AFFiNE/assets/100135382/cad7b12b-4c9b-469f-8af5-787fcb188a7c

Expected behavior
https://gemoo.com/tools/upload-video/share/551850573801947136?codeId=vz25pqwWR4zrz&card=551850569095938048&origin=videolinkgenerator

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Noothan-am** [comment]
working on it

**Comment by Noothan-am** [comment]
hey @doodlewind, ig this will fix this issue. please let me know if any changes need to be done.

**Comment by houjoe0829** [comment]
I modified the issue's Tag. Actually, this is a bug. After restoring, a Toast prompt needs to be displayed with the content: {page's title} restored.

**Comment by Noothan-am** [comment]
> I modified the issue's Tag. Actually, this is a bug. After restoring, a Toast prompt needs to be displayed with the content: {page's title} restored.

 https://github.com/toeverything/AFFiNE/pull/3847 pr fixed this issue .
