### ISSUE TITLE
“Add Tag" is missing in In-Page Option

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#3867]
<img width="290" alt="CleanShot 2023-08-21 at 15 28 43@2x" src="https://github.com/toeverything/AFFiNE/assets/22443345/4791099c-2fe9-4502-87fd-3c4e813b1cfe">

Related with https://github.com/toeverything/AFFiNE/issues/3602

**Comment by om2137** [comment]
can I try to implement this feature?
Is there any specific design or UX for this? @JimmFly @houjoe0829

**Comment by JimmFly** [comment]
> can I try to implement this feature? Is there any specific design or UX for this? @JimmFly @houjoe0829

/cc @houjoe0829 @hwangdev97

**Comment by houjoe0829** [comment]
Sorry, after discussing with the internal designer, it was found that in the current interaction, clicking "Add Tag" requires scrolling to the top of the page and then opening "Page Info" to add tags. This is not aligned with expectations. As a result, we will remove this option from the page options for now. CC @om2137 @JimmFly @xell
