### ISSUE TITLE
​Add AFFiNE to Microsoft Store

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/AFFiNE#3868]
### Description

My workplace has strict installation requirements for apps. I can however install many apps from the Microsoft Store without security blocking the installation. I believe this is the case for a lot of corporate environments.

Request is to add Affine.Pro app to the Microsoft Store once version 1.0 is released to decrease barriers to adoption.

### Use case

Corporate environments with strict application installation policies.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you very much for your feedback. We will reevaluate this task after resolving the Windows client installation issue.

**Comment by SolarDesalination** [comment]
The web version at app.affine.pro is sufficient for people who have security restrictions for installing local apps on corporate-managed laptops. I think this isn't a high priority anymore. I made the request before the web-version was available.
