### ISSUE TITLE
​Affine docker image not working on Firefox browser

### ISSUE THREAD

**Issue by amitshuklabag** [toeverything/AFFiNE#3874]
### What happened?

I deployed the Affine docker image, and it works perfectly with Chrome but not with Firefox. 
When I tried it in the Firefox browser, it only showed a loading screen, and the error is shown in the console, which I've sent, so please look into it and fix the problem in your application.

![image](https://github.com/toeverything/AFFiNE/assets/53058928/4d744f28-d3b1-4457-bb9f-d2590fc4a263)
![image](https://github.com/toeverything/AFFiNE/assets/53058928/b3e9c88f-0923-44c8-9603-90919cb41e19)

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Relevant log output

```shell
Build info _app-fe13269c5825cb6c.js:1:195010
Project: @affine/app _app-fe13269c5825cb6c.js:1:195038
Build date: 6/1/2023, 7:42:47 pm _app-fe13269c5825cb6c.js:1:195077
Environment: production(ci) _app-fe13269c5825cb6c.js:1:195167
Editor Version: =0.3.1-20230106060050-1aad55d _app-fe13269c5825cb6c.js:1:195240
Version: f99bf74 _app-fe13269c5825cb6c.js:1:195288
AFFiNE is an open-source project, you can view its source code on GitHub! _app-fe13269c5825cb6c.js:1:195322
https://github.com/toeverything/AFFiNE/tree/f99bf74
_app-fe13269c5825cb6c.js:1:195411
token empty login +0ms _app-fe13269c5825cb6c.js:1:164876
@affine/logger: Render Track _app-fe13269c5825cb6c.js:1:458503
dc Init workspace affine with selfhosted +0ms _app-fe13269c5825cb6c.js:1:164876
Uncaught (in promise) TypeError: indexedDB.databases is not a function
    NextJS 2
196 _app-fe13269c5825cb6c.js:1:762973
Too many calls to Location or History APIs within a short timeframe. main-b5fee26f1089ab0d.js:1:8403
Uncaught (in promise) TypeError: indexedDB.databases is not a function
    NextJS 2
2 _app-fe13269c5825cb6c.js:1:762973
Uncaught (in promise) DOMException: The operation is insecure.
    NextJS 5
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
This does the browser compatibility issue. We are working on the next major version of the docker image and will release it soon

**Comment by amitshuklabag** [comment]
Okay, thanks for the update.

**Comment by fourdim** [comment]
https://github.com/toeverything/AFFiNE/releases/tag/v0.8.0

**Comment by felixsanz** [comment]
> This does the browser compatibility issue. We are working on the next major version of the docker image and will release it soon

can you publish the dockerfile so we can build the image by our own?

**Comment by samuelds** [comment]
Not updated docker image ?

**Comment by fourdim** [comment]
FYI
https://github.com/toeverything/AFFiNE/pkgs/container/affine-front
https://github.com/toeverything/AFFiNE/pkgs/container/affine-graphql
It's still in progress, please wait for the stable release.
And this issue no longer reproduces in our latest docker image, closing.

**Comment by fourdim** [comment]
Link to #5069.
