### ISSUE TITLE
bug: quick search didn't work

### ISSUE THREAD

**Issue by Niko030303** [toeverything/AFFiNE#3881]
### What happened?

What is the feature of the Quick Search Bar? To search the title or the content? I try to search both but wrong.

![image](https://github.com/toeverything/AFFiNE/assets/82041918/3a6c7008-14e4-4595-b139-cc92641103ab)

### Distribution version

macOS ARM 64 (Apple Silicon)

### Anything else?

For me, I think the best way is to search for both, and highlight the result

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Duplicated: https://github.com/toeverything/blocksuite/issues/4294
