### ISSUE TITLE
​After each overwrite installation, the Ctrl+K search cannot retrieve all the previous content.

### ISSUE THREAD

**Issue by Mojicode** [toeverything/AFFiNE#3894]
### What happened?

As the title, I can not search any content i create before when i install new canary version.

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Duplicated https://github.com/toeverything/blocksuite/issues/4294
