### ISSUE TITLE
Add early access progress for AFFiNE Cloud

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#3934]
### Description

Add an early access entrance[design](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=13096-76607&mode=design&t=l0H4vRRClDf7BWMz-4)

![Image](https://github.com/toeverything/AFFiNE/assets/110808979/e142e884-df3c-404e-b893-fac5d1bde4c8)

**Comment by Svaney-ssman** [comment]
Plz add me and operational members as reviewers

**Comment by QiShaoXuan** [comment]
Added in https://github.com/toeverything/AFFiNE/pulls?q=+is%3Apr+author%3AQiShaoXuan+
