### ISSUE TITLE
Double click to activate renaming feature

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#3939]
### Description

It's suggested using double click to activate renaming function:

https://github.com/toeverything/AFFiNE/assets/24713927/27973cff-6830-465a-a59f-01576823f4d9

and I think it would be more reasonable if the title could not be selected, `user-select: none;` for title.

**Comment by xell** [comment]
Currently, single clicking will trigger the rename operation, which is such an annoying bother.
