### ISSUE TITLE
Full Page Width for Some Pages, not for others​

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/AFFiNE#3945]
### Description

Pages where I have a Kanban Board look better in full-width. Other documentation pages look better without full-width. It would be cool to either have a toggle in the page so I don't have to go to the options every time to switch between full-width and regular. Further, it would be cool if a page remembered that toggle for that page.

So it would be like:
- Options page allows for Default Full-width or regular.
- each page has an option to switch between the two.
- Metadata about that page remembers the preferred width.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you very much for your feedback. We are currently prioritizing the support of full-screen display for Kanban. Similar to the preview mode of an image, we plan to enable users to open Kanban in full screen mode. Do you think this will improve the experience of viewing Kanban on a narrow page?

**Comment by SolarDesalination** [comment]
Yes, this would be the equivalent for my use case. Thanks!

**Comment by houjoe0829** [comment]
Roger, we will close this issue for now, the full screen view of the Database will be followed up in https://github.com/toeverything/blocksuite/issues/2517, feel free to reopen it if you have any problems.
