### ISSUE TITLE
Buttons overlapping file name

### ISSUE THREAD

**Issue by Subhahdip** [toeverything/AFFiNE#3956]
### What happened?

The restore it button is overlapping the file name in the trash section
<img width="958" alt="affine" src="https://github.com/toeverything/AFFiNE/assets/87298461/8ed578ef-a7d0-4e9f-86a5-f899bad5ba6d">

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
app.affine.pro has no update for a while, we will migrate to the latest version soon

/cc @thorseraq

**Comment by Subhahdip** [comment]
@himself65 which version has got the latest updates

**Comment by thorseraq** [comment]
Hey, currently we are actively maintaining AFFiNE Client, for the latest editing experience, please download and have a try! https://github.com/toeverything/AFFiNE/releases

**Comment by thorseraq** [comment]
For AFFiNE cloud in the screenshot, it will be migrated for latest editing and collaborating experience with data migrated

**Comment by Subhahdip** [comment]
okay, closing the issue
