### ISSUE TITLE
cloud public workspace logic

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3957]
currently, we have a field `public` in the workspace schema but it's not good if people only share one page.

So the `public` field will have `PUBLIC`, `ALL`, and `PRIVATE` enums now instead of a boolean value

**Comment by himself65** [comment]
Refs https://github.com/toeverything/AFFiNE/commit/605db160870650a8394aea0281b9a26a9ddd5b60

**Comment by imf-ali** [comment]
Hey @himself65 , I would like to work on this issue. Could you please assign it to me?

**Comment by himself65** [comment]
OK, you're welcome
