### ISSUE TITLE
Newly created collections should not automatically include all pages by default

### ISSUE THREAD

**Issue by Ksisioss** [toeverything/AFFiNE#3965]
### What happened?

Everytime i create new collection the content of "Getting started" is automatically in it
![image](https://github.com/toeverything/AFFiNE/assets/54034242/f54546bd-7d27-4618-9923-651f049a24e5)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
I can reproduce this issue in the latest Canary version. A newly created collection with no filter rules will automatically include all pages by default.
The expected result is that without any rules, no pages should be included.

**Comment by houjoe0829** [comment]
@Ksisioss Thank you for your feedback. The current logic of the collection feature is based on filters. We will adjust it so that newly created collections are more like folders and can include advanced rules such as filters. However, this is still under discussion.
