### ISSUE TITLE
Order of lined page incorrect

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3966]
![image](https://github.com/toeverything/AFFiNE/assets/14026360/8ca8b516-8b40-4dce-a4b8-437e3329e0da)

**Comment by Asish-AP** [comment]
can you give some more insights about the task ?

**Comment by Noothan-am** [comment]
hey @himself65, i am unable to recreate this issue, could you give steps to reproduce it ?

![image](https://github.com/toeverything/AFFiNE/assets/100135382/9a38f4bc-2204-494f-a18e-bbe6e9535a53)

**Comment by himself65** [comment]
> hey @himself65, i am unable to recreate this issue, could you give steps to reproduce it ?
> 
> ![image](https://user-images.githubusercontent.com/100135382/263511832-9a38f4bc-2204-494f-a18e-bbe6e9535a53.png)

Drag

**Comment by Noothan-am** [comment]
not able to drag and drop pages

https://www.veed.io/view/8cd8b891-63ee-42ca-8e35-e74797fda9ba?panel=share

**Comment by Asish-AP** [comment]
same for me . The drag and drop doesn't work
https://www.veed.io/view/cfc9d2c7-6bef-4cdc-a15b-147d7be8142d?panel=share

**Comment by sahith29s** [comment]
Hello guys I am new to open source , can Anyone give me some details how to get started?

**Comment by himself65** [comment]
> Contributor

Drag the block! not the sidebar

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/assets/14026360/687cc551-97e0-4af6-b39a-217dfec731db

**Comment by surajvast1** [comment]
Hey @pengx17  I would Like to work on this

**Comment by VamshiAlugoju** [comment]
So what exaclty is the issue?
If you drag in the block should it also move in the sidebar?

**Comment by houjoe0829** [comment]
1. AFFiNE's Page Tree defaults to automatic sorting, that is, displaying different linked pages in the order inside page. If there are duplicate linked pages, only the first one added will be displayed.
2. After becoming manually sorted, the Page Tree will be displayed in the order of manual sorting. The newly added Linked Page will be displayed at the bottom according to the added time. If there are duplicate linked pages, only the first one added will be displayed.

in addition:
- For the time being, we will not consider the function of allowing users to reset manually and back to automatic sorting. In the future, we will consider adding a Reset function.
- The default is automatic sorting. As long as the user manually drags and adjusts successfully, it will change to manual sorting mode.

Also to answer the above question from @VamshiAlugoju , if the user moves the order of linked pages inside page, and the Page tree is automatically sorted at this time, it will also change accordingly.
