### ISSUE TITLE
Quick search tip's position is in the wrong place at first when create a new page in demo site

### ISSUE THREAD

**Issue by linxiaowang** [toeverything/AFFiNE#3971]
### What happened?

Quick search tip's position is in the wrong place at first when creating a new page in demo site.

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Can you provide a screenshot? This way we can have a more accurate understanding of the problem. Thank you.
