### ISSUE TITLE
[bug]: language setting lost when reload page

### ISSUE THREAD

**Issue by m1911star** [toeverything/AFFiNE#398]
### To Reproduce

1. set language to CN
2. reload page
3. still english content

### Screenshots

https://user-images.githubusercontent.com/4948120/189349113-6aca3240-93d6-49f7-8d88-f56266f9a72a.mov

### Platform

any

**Comment by m1911star** [comment]
same problem with landing page

**Comment by lawvs** [comment]
We fixed the live demo. Thanks for your feedback.

See https://github.com/toeverything/AFFiNE/commit/ff1cb4da845b9e31cb1fc509ed8a009b8ef383d7

**Comment by m1911star** [comment]
> We fixed the live demo. The landing page will also be fixed later. Thanks for your feedback.
> 
> See https://github.com/toeverything/AFFiNE/commit/ff1cb4da845b9e31cb1fc509ed8a009b8ef383d7

lgtm
