### ISSUE TITLE
Image attachments not correct while importing from makrdown/html ​which exported by AFFiNE 0.8

### ISSUE THREAD

**Issue by leopku** [toeverything/AFFiNE#3980]
### What happened?

1. Exporting a page which had some images as md/html
2. Import files which generated by step 1 to another workspace
3. You can find all image attachments in new page were names `.undfined` file extension. For example: 

```
[images/NPT8tnFxIhBdJCu1xmwjuXykiolYSiQ6klVLftJyFa0=.undefined](https://github.com/toeverything/AFFiNE/issues/images/NPT8tnFxIhBdJCu1xmwjuXykiolYSiQ6klVLftJyFa0=.undefined)
```

AFFiNE: 0.8
OS: MacOS 11.7 (Intel)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zuoxiaodong0815** [comment]
The issue is as same as https://github.com/toeverything/blocksuite/pull/4342.

**Comment by zuoxiaodong0815** [comment]
Thank you. Also, the exported html/markdown zip may be not correct sometimes by importing notion button. The importing notion button is designed to import notion file.
