### ISSUE TITLE
Settings dialog unusual scrolling when menu opened and use “⬇️”“⬆️”

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#3982]
### What happened?

When I open the menu and press the up and down arrow keys on the keyboard, the page will scroll abnormally. 

The expected behavior should be the hover state of the menu, and then press enter to activate and close the menu

https://github.com/toeverything/AFFiNE/assets/24713927/3575842a-b272-4e47-b040-1d5ed37ea766

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joooye34** [comment]
Should this issue be closed ? @himself65 .

**Comment by joooye34** [comment]
cc @hwangdev97

**Comment by hwangdev97** [comment]
Yes, I think it's fixed

**Comment by joooye34** [comment]
Fixed by https://github.com/toeverything/AFFiNE/pull/4006
