### ISSUE TITLE
[improvement]: Add more tips about how to create new block group in a blank page

### ISSUE THREAD

**Issue by Zheaoli** [toeverything/AFFiNE#399]
### 1~3 main use cases of the proposed improvement

<img width="1278" alt="CleanShot 2022-09-09 at 21 22 53@2x" src="https://user-images.githubusercontent.com/7054676/189359833-cd027307-1773-4614-92e4-b7826fce8859.png">

As you see, this is a blank page without content.  People can create a block group by click this page

I think it should be better add some tips when the cursor is on the content zone, like the block group tips below

<img width="462" alt="CleanShot 2022-09-09 at 21 24 53@2x" src="https://user-images.githubusercontent.com/7054676/189360268-60c505d9-935b-4e86-be66-80590316c69e.png">

**Comment by tzhangchi** [comment]
This is a good experience feedback. We are redesigning this experience. If you have good suggestions, you can directly feedback to me here

**Comment by tzhangchi** [comment]
The Pre Alpha version has been archived, thank you for your continued support, you can fully experience and give feedback on our latest 0.6.0 version https://github.com/toeverything/AFFiNE/releases
