### ISSUE TITLE
user may easily bypass the throttling of cloud login via email​

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#3994]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/584378/b86a2455-9229-499f-a2ea-ceddf8acfa24)
If the user click the "back home" button and then click "continue with email", it will allow the user to send a new email login link without waiting for the timeout for resending the login link.

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by QiShaoXuan** [comment]
fixed in https://github.com/toeverything/AFFiNE/pull/4099
