### ISSUE TITLE
getting started part is still the previous version

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4003]
New changes in Getting Start Part can't be seen. It's still the old version.

![Image](https://user-images.githubusercontent.com/142964904/263931531-91fc3edb-35b5-4a79-89ef-c6d670db86ba.png)

![Image](https://user-images.githubusercontent.com/142964904/263931613-674274b3-41dd-4e9f-9d0d-6f887893a215.png)

https://user-images.githubusercontent.com/142964904/263931370-ade09be0-b728-475d-bb75-7a6354e2fa93.mp4

**Comment by himself65** [comment]
You need to create a new workspace because we won't modify your existing data.
