### ISSUE TITLE
0.9.0-canary.3 can not import 0.8.0-canary.27 workspace​

### ISSUE THREAD

**Issue by Mojicode** [toeverything/AFFiNE#4029]
### What happened?

As the title, I overwrite install 0.8.0-canary.27 use 0.9.0-canary.3, but it can not show all the file. I install  0.8.0-canary.27 back, and export workspace. then I install 0.9.0-canary.3, import the workspace, first time it show migration error, second time it finish import, but all the index is wrong and disorder.

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Thanks for the report, I will fix this ASAP

**Comment by himself65** [comment]
Please download 0.9.0-canary.5, we have a hot patch for the canary. The real issue is we change the origin of the app which will cause data actually be there but in a different place
