### ISSUE TITLE
Reinstallation should preserve the workspace

### ISSUE THREAD

**Issue by yuusheng** [toeverything/AFFiNE#4041]
### What happened?

When I upgraded my AFFiNE-canary to 0.9.0, it just broke. After I reinstalled AFFiNE-canary from the official website, my workspace disappeared. I think we should preserve the workspace when reinstalling the app to protect user data.

<img width="1067" alt="image" src="https://github.com/toeverything/AFFiNE/assets/64511565/482861f2-a435-4b61-ab1f-2e16d161acae">

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Garfield550** [comment]
Your data is in `/Users/<name>/Library/Application Support/AFFiNE-canary`, it is not lost. 

This is a known issue that will be fixed in a subsequent version. It is recommended to back up the data located in the `workspaces` folder, which have the `.db` extension.

**Comment by Garfield550** [comment]
If you have important files to view, please back up the `.db` files under `workspaces`, then rename them with the file extension `.affine`, and import them using version 0.8.2 or 0.8.0 (be sure to skip 0.8.1) or 0.9.0-canary.4.

**Comment by pengx17** [comment]
might be related to https://github.com/toeverything/AFFiNE/issues/4029

**Comment by yuusheng** [comment]
> might be related to #4029

I see! It's the same! I reinstalled AFFiNE canary 0.8, it's working now.

I think we should have a better way to handle this case. Not every user knows how to back up the previous version of AFFiNE! It's important!

Use a more obvious path to save *.affine file. Or auto-transform pages to markdown files (although I don't think it's a good way, it helped when the app crashes and the user doesn't know how to fix it)?

**Comment by himself65** [comment]
Please download canary.5? I believe everything could come back

**Comment by himself65** [comment]
If not, please re-open this issue
