### ISSUE TITLE
Add a reminder for Early access in the invitation email

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4044]
[Internal link](https://toeverything.feishu.cn/docx/YSE1d7ecOoHzFPx3FNacVH3rnVb#NzehdvZPEooiRexuTWKcWuJKnwe)

**Comment by Svaney-ssman** [comment]
[internal design](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=12828-48494&mode=design&t=wxcvd3b9RfXI6itj-4)
