### ISSUE TITLE
[feature]: Import information from different services. 

### ISSUE THREAD

**Issue by ChrisFarmer-dev** [toeverything/AFFiNE#405]
### 1~3 main use cases of the proposed feature

As a user who once used many different services like Notion, Miro, Monday, Trello, etc., importing data from such services would be a fantastic feature so I can control all of my existing data from different services. 

### what types of users can benefit from using your proposed feature

Users or Organizations who have migrated from other services to AFFiNE

**Comment by tzhangchi** [comment]
Thank you for your feedback. In fact, our team is also using such excellent tools as Notion, Miro and any others. We are also building a complete set of open APIs to import more data sources,

**Comment by ChrisFarmer-dev** [comment]
Thank you so muchh 🙏. You all are amazing 🫂

**Comment by RyzeNGrind** [comment]
Can we expect miro import to be implemented anytime soon? I am looking to migrate to self hosted Affine from Miro.

**Comment by houjoe0829** [comment]
> Can we expect miro import to be implemented anytime soon? I am looking to migrate to self hosted Affine from Miro.

Currently, importing Miro is not in the plan, and there is no suitable solution for the time being. This also includes other whiteboard products. The difference in data formats between different products is too large, and the priority is not high for the time being. However, we will continue to invest in importing doc or note tool products.

**Comment by houjoe0829** [comment]
For now, this issue will be temporarily closed because it is relatively general, and the overall requirement is already in our backlog. We will support them one by one. If there are any further questions, you can reopen it at any time.
