### ISSUE TITLE
Border display​ error

### ISSUE THREAD

**Issue by zanwei** [toeverything/AFFiNE#4055]
### What happened?

**Now**: There's a wrong status when the side-bar hidden

**Should**: The left edge should maintain some padding

![image](https://github.com/toeverything/AFFiNE/assets/40333372/2ed8c672-471c-42c9-a9ed-4cd73f164ace)

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
fixed in https://github.com/toeverything/AFFiNE/pull/4046
