### ISSUE TITLE
Mode buttons and title disappear while renaming untitled doc

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#4056]
After adding a new note with empty title and then clicking the title bar to rename it, the mode buttons and title disappear and there's no cursor:

https://github.com/toeverything/AFFiNE/assets/132558/cdebd278-d67d-4263-b1fd-fe9564968c96

**Comment by houjoe0829** [comment]
Similar with https://github.com/toeverything/AFFiNE/issues/3777#event-10125636150 ？

**Comment by ideakaran** [comment]
When we click on the page title (to rename it), the user can still type the title.
However, a border around the title seemed missing which is now added via this pull req https://github.com/toeverything/AFFiNE/pull/4080/files

Change demo: https://www.veed.io/view/f6080bf8-2ac6-43e3-a980-36c7b0d7aebc
