### ISSUE TITLE
[bug]: I can not input any text into the tag label

### ISSUE THREAD

**Issue by zhang-win** [toeverything/AFFiNE#406]
### Describe the bug

I found it's not possible to input any text if i am trying to create a new tag 

### To Reproduce

1. create a new text block
2. input some text
3. click button bottom to create a new tag
4. select the field type, such as text
5. click the input frame to active it and try to write something into it (actually, it can not be)

### Screenshots

![Quicker_20220912_060221](https://user-images.githubusercontent.com/37443093/189550708-2c3b2729-1c53-4d19-9739-1db8a26a13b8.png)

### Expected behavior

The input frame should be focused, and show anything i typed into 

### Platform

Linux

### Browser

Chrome

### Additional context

I installed it by this command:
docker run -p 4200:3000 --name affine -d ghcr.io/toeverything/affine:nightly-latest

**Comment by tzhangchi** [comment]
@QiShaoXuan maybe you can follow this issue, I think it is a compatibility problem, need to collect more environmental information

**Comment by Pranav4399** [comment]
This bug couldn't be reproduced in the windows environment. I think it is a Linux-specific issue. Attaching Image for reference - 

![image](https://user-images.githubusercontent.com/28348429/189712633-041ff816-34e9-4e37-aaee-3027cf1c15d7.png)
