### ISSUE TITLE
​Tooltip layer issue

### ISSUE THREAD

**Issue by zanwei** [toeverything/AFFiNE#4074]
### What happened?

**Should:** Tooltip needs to appear on the top level while hovering

<img width="285" alt="image" src="https://github.com/toeverything/AFFiNE/assets/40333372/e9fcbe73-eecf-46ff-8962-8e006a566daa">

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
Fixed with https://github.com/toeverything/AFFiNE/pull/4045
