### ISSUE TITLE
Markdown - Full Markdown syntax support

### ISSUE THREAD

**Issue by Avey777** [toeverything/AFFiNE#410]
### 1~3 main use cases of the proposed feature

Markdown syntax

### Ideas for solution

Refer to：https://github.com/pandao/editor.md

**Comment by tzhangchi** [comment]
Thank you for your feedback,Support  more Markdown syntax support is on our planning, but now we are working in refactor our editor , Major refactor for improving stability   https://github.com/toeverything/AFFiNE/discussions/380

**Comment by Avey777** [comment]
> 

ok
![image](https://user-images.githubusercontent.com/35259040/189918465-ed02f614-3dc9-4121-903c-f2b2a0005a5b.png)
Thank you for your efforts. I will record the request for adding a flowchart here, so that you can consider subsequent implementations. I am looking forward to the future of AFFIE.
