### ISSUE TITLE
Notification text cannot be selected when there is a modal.

### ISSUE THREAD

**Issue by JimmFly** [toeverything/AFFiNE#4100]
https://github.com/toeverything/AFFiNE/assets/102217452/86a8477d-8fa7-4b57-94b8-034524ae57aa

**Comment by pengx17** [comment]
caused by this https://github.com/mui/material-ui/blob/v5.14.7/packages/mui-base/src/Modal/Modal.tsx#L169-L177

**Comment by YashuaPervez** [comment]
Hi,
open for assign

**Comment by om2137** [comment]
@JimmFly  as affine cloud is not available for everyone Is there any other way I can reproduce this issue? any other notification?

**Comment by JimmFly** [comment]
> @JimmFly as affine cloud is not available for everyone Is there any other way I can reproduce this issue? any other notification?

For instance, in the drop-down menu beside the page title, there's an export function, wherein each button will trigger notification.

**Comment by om2137** [comment]
https://github.com/toeverything/AFFiNE/assets/33827410/69555128-e0f5-4320-88fa-41a805c0e132

@JimmFly  couldn't select the notification text even if the modal is off. solution for this issue is to make notification text selectable right?

**Comment by JimmFly** [comment]
https://github.com/toeverything/AFFiNE/assets/102217452/bd64116f-4be6-47af-b904-a1035d06e283


In the latest version of the master branch, the text in notifications is indeed selectable under normal circumstances. I cannot reproduce the error you are showing. Maybe you might need to sync or update your repository? All in all, the real problem to solve is ensuring that text can be selected in notifications in any given situation. @om2137 

App Version
0.9.0-canary.8

Editor Version
0.0.0-20230829150056-df43987c-nightly

**Comment by priyansh19csu225** [comment]
Hi! I saw this particular issue, as @pengx17 pointed above, the problem is that modal uses `disableEnforceFocus = false` by default, simple solution would be to pass the `disableEnforceFocus` prop in Modal
Example: Particularly for settings modal  ```
<Modal
      open={open}
      onClose={handleClose}
      wrapperPosition={['center', 'center']}
      data-testid="setting-modal"
      disableEnforceFocus
    >

```
    
Here's demo
https://github.com/toeverything/AFFiNE/assets/71059426/08af5dbe-e16b-488d-8191-08d4fbd5b75d

Please reply if you would like me to open a PR by including 'disableEnforceFocus' prop in all <Modal ... />

**Comment by JimmFly** [comment]
@priyansh19csu225 Wow, this looks splendid, I'm thoroughly looking forward to seeing your PR.

**Comment by JimmFly** [comment]
Wow, this seems to work as expected, however, it can cause various problems:
1. The original intention is that after Modal is opened, no operations outside Modal are allowed. Hope to be able to handle Notification exclusively.
2. This is not an isolated case of only one Modal. If we decide to do this, all modal issues must be addressed accordingly.

@priyansh19csu225

**Comment by JimmFly** [comment]
Do you folks have any sterling suggestions? @pengx17 @QiShaoXuan @himself65

**Comment by om2137** [comment]
> Wow, this seems to work as expected, however, it can cause various problems:
> 
> 1. The original intention is that after Modal is opened, no operations outside Modal are allowed. Hope to be able to handle Notification exclusively.
> 2. This is not an isolated case of only one Modal. If we decide to do this, all modal issues must be addressed accordingly.
> 
> @priyansh19csu225

@JimmFly 
passing `disableEnforceFocus` prop to root level Modal component may address the issue for all the modals. Can I test and open a PR?

**Comment by priyansh19csu225** [comment]
> Wow, this seems to work as expected, however, it can cause various problems:
> 
> 1. The original intention is that after Modal is opened, no operations outside Modal are allowed. Hope to be able to handle Notification exclusively.
> 2. This is not an isolated case of only one Modal. If we decide to do this, all modal issues must be addressed accordingly.
> 
> @priyansh19csu225

Addressing second issue is easier by simply passing prop in root level component as @om2137 said
Addressing first one is bit tricky... Would like to seek for others' opinion as well.

@om2137 I believe you are really interested on working on this issue, I am leaving this one to you.. If you require any help, I am available to help

**Comment by om2137** [comment]
Thank you @priyansh19csu225. @JimmFly should I open a PR, I have tested with all the modals I could find and it works as expected

**Comment by JimmFly** [comment]
> Thank you @priyansh19csu225. @JimmFly should I open a PR, I have tested with all the modals I could find and it works as expected

Looking forward to your GitHub PR.
