### ISSUE TITLE
Support horizontal scrolling in whiteboard

### ISSUE THREAD

**Issue by OneMoonLeft** [toeverything/AFFiNE#4109]
### Description

 It would be interesting to have left to right scrolling through pressing shift and using the mouse wheel, a little bit like obsidian canvas scrolling or photoshop ctrl+mouse wheel interaction

### Use case

Anyone who would use the mouse wheel to navigate through the whiteboard.

https://github.com/toeverything/AFFiNE/assets/115279639/5aac69a0-b1a4-4a66-a5c8-a5a93613cbfb

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hwangdev97** [comment]
I think we need to support shift + wheel to support horizontal scrolling. cc @houjoe0829
