### ISSUE TITLE
online preview outdated

### ISSUE THREAD

**Issue by omarcostahamido** [toeverything/AFFiNE#4112]
https://github.com/toeverything/AFFiNE/blob/e76cdf4d7178239f325aa45e794c28c515bc8dbb/README.md?plain=1#L69

remove or update it?

possible update is to just point at something like https://insider.affine.pro/ ?

**Comment by omarcostahamido** [comment]
there, quick fix suggestion added.

**Comment by himself65** [comment]
insider is for purchased users, and it's also the closed beta version with new cloud support. We are going to land this to app.affine.pro in the next months
