### ISSUE TITLE
can't copy title in edgeless mode​

### ISSUE THREAD

**Issue by omarcostahamido** [toeverything/AFFiNE#4118]
### What happened?

when in edgeless mode you can't copy/cut/past the title of the page on the top bar.

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
It seems to have been fixed in the latest Canary version. However, which version are you currently using? We will investigate this issue.

**Comment by omarcostahamido** [comment]
Latest official 082
Happens both on my Mac install and the new insider online version.
Thank you

**Comment by houjoe0829** [comment]
I can reproduce this issue in the official version. It has been fixed in the latest Canary version, but we need @himself65 to confirm it again.
