### ISSUE TITLE
​The filter of collections not works

### ISSUE THREAD

**Issue by lawvs** [toeverything/AFFiNE#4121]
### What happened?

https://github.com/toeverything/AFFiNE/assets/18554747/e177dbd2-a72c-4d50-951a-1431eef4765a

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Anything else?

App Version
0.9.0-canary.7
Editor Version
0.0.0-20230829150056-df43987c-nightly

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zzj3720** [comment]
@lawvs You can try this pr to see if it solves your problem.https://github.com/toeverything/AFFiNE/pull/4138
