### ISSUE TITLE
​Bugged out

### ISSUE THREAD

**Issue by OneMoonLeft** [toeverything/AFFiNE#4162]
### What happened?

Bugged out of the page on web version, using chrome, and firefox at the same time, both got this error message at same time, have no idea of what could have triggered it. Was using the collaborative feature. While try and replicate it but have no idea if it's going to work.

### Distribution version

Web (insider.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Firefox

### Relevant log output

```shell

```

### Anything else?

![image](https://github.com/toeverything/AFFiNE/assets/115279639/30da3cca-8006-4469-beac-2b85405abf8b)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by OneMoonLeft** [comment]
Refreshing the page got it out back runing, i don't know if this was a good reason to open this issue...

**Comment by himself65** [comment]
This might because some `useUser` returns null but no error boundary
