### ISSUE TITLE
Login fail issues in canary

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#4164]
Is it normal to log in to the cloud in canary (receive the email-click the link-then there is no response in the app)

<img width="685" alt="img_v2_5b89217b-f076-407e-b519-597bb51c5c4g" src="https://github.com/toeverything/AFFiNE/assets/5910926/0033b5a6-7a01-412f-b3dd-a6b5f761aa0b">

Feedback from @Yipei-Operation

**Comment by pengx17** [comment]
@tzhangchi can you try the latest canary and see if it has been fixed or not?
