### ISSUE TITLE
Collections in any workspace is not real-time syncing

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#4171]
<img width="1727" alt="image" src="https://github.com/toeverything/AFFiNE/assets/5910926/55a0179a-aa63-475a-8d92-71046044f05b">

**Comment by himself65** [comment]
We don't sync this at all!

@Brooooooklyn

**Comment by tzhangchi** [comment]
Now it is supported，☺️

**Comment by himself65** [comment]
Only synchronized in cloud workspace

**Comment by himself65** [comment]
We cannot support this in the local workspace because the local workspace doesn't have an such identifier as a user account ID.
