### ISSUE TITLE
data loss happened (with stable 0.8.3 version)​

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/AFFiNE#4172]
### What happened?

<img width="706" alt="截屏2023-09-04 17 35 04" src="https://github.com/toeverything/AFFiNE/assets/79373028/59223b68-5c26-41de-b7a8-290cc68c916b">
<img width="716" alt="截屏2023-09-04 17 37 01" src="https://github.com/toeverything/AFFiNE/assets/79373028/eb8f6708-c742-415e-a1a9-14806727a51d">
Related link: https://discord.com/channels/959027316334407691/959033875856756756/1148362632684912760
https://discord.com/channels/959027316334407691/959033875856756756/1148405570492170390

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by dronab** [comment]
Hi. It turns out that I upgraded to 0.8.3 then just copied the database file with explorer and then I could no longer import this workspace file in any version of the application. The fact that it is imported is not completely and not working.

**Comment by dronab** [comment]
The file can be opened directly in DB Browser did PRAGMA integrity_check; Execution finished without errors.  Everything is fine with the disk, the file is not broken.
