### ISSUE TITLE
The box of invite members did not support scroll 

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#4175]
<img width="602" alt="image" src="https://github.com/toeverything/AFFiNE/assets/5910926/6db97e8c-9856-41de-8bdc-d757dca46895">

So I can't remove more items in the bottom of the box for invite members

**Comment by tzhangchi** [comment]
@JimmFly To be honest, the product design is a pagination ui

**Comment by JimmFly** [comment]
> @JimmFly To be honest, the product design is a pagination ui 说实话，产品设计就是分页ui

/cc @QiShaoXuan

**Comment by QiShaoXuan** [comment]
This issue will close after fix pr merged, the pagination is a feature which will support in this iteration
