### ISSUE TITLE
When the invitation link is outdated , I re-invite the pending user, but the pending user didn't receive the new  invitation

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#4176]
<img width="1104" alt="image" src="https://github.com/toeverything/AFFiNE/assets/5910926/9ded757d-cbfa-4b2d-a813-d66975efb1ac">

**Comment by QiShaoXuan** [comment]
Such interaction is currently expected, and we will fully support it in the future. CC @houjoe0829 
If you encounter problems during the invitation, you can delete the invitee and invite it again
