### ISSUE TITLE
Does the appearance configuration of the Workspace necessitate synchronization with the cloud,

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#4188]
<img width="760" alt="image" src="https://github.com/toeverything/AFFiNE/assets/5910926/596a8423-7061-43bb-b7bd-cde50139049a">

Upon the successful initiation of AFFiNE Cloud, does the appearance configuration of the Workspace necessitate synchronization with the cloud, or should it be preserved locally?

@HeJiachen-PM @houjoe0829

**Comment by houjoe0829** [comment]
Sorry, we are not considering cross-device synchronization for appearance settings at the moment. 
Firstly, the cost of modification is relatively low. 
Secondly, different devices have different appearance settings, which is more flexible. If cross-device synchronization is implemented, it will make this feature more complex, requiring consideration of both synchronized and unsynchronized scenarios, with relatively low benefits. 
I will temporarily close this issue. If you have any further questions, please feel free to reopen it.
