### ISSUE TITLE
Create a New Workspace based on a selected template

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#4189]
Can we create a New Workspace based on a selected template? For example , choose “Get Started Workspace ” or "Empty Workspace"?

Why I make this feedback? You can image that, before I start to enrich the content of the workspace, I often need an empty workspace rather than a workspace which is full of preloading pages I dont't need 
@HeJiachen-PM @houjoe0829

**Comment by houjoe0829** [comment]
This is on the Roadmap, but it is not in the current iteration. It is a part that needs to be done in the future, but before that, there are many other basic features that need to be improved.

**Comment by tzhangchi** [comment]
> This is on the Roadmap, but it is not in the current iteration. It is a part that needs to be done in the future, but before that, there are many other basic features that need to be improved.

Thank you，look forward to the future
