### ISSUE TITLE
Upon opening the "Save as New Collection" dialog, the "Collection Name" input field is expected to be automatically focus.

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#4190]
<img width="1722" alt="image" src="https://github.com/toeverything/AFFiNE/assets/5910926/b131fe5b-c751-4002-9d4f-90565d42016e">

@himself65 @hwangdev97 I remain curious about how the default focus interactions of related forms are depicted within design methodologies and how to request development improvements.?

**Comment by Garfield550** [comment]
EditCollectionModel based on '@mui/base/Modal', has an annoying issue that makes Input inside the Modal lose focus.

https://github.com/mui/material-ui/issues/9131#issuecomment-1384804343
https://mui.com/material-ui/api/modal/#Modal-prop-disableEnforceFocus

**Comment by hwangdev97** [comment]
We are redesigning this part of the interaction
