### ISSUE TITLE
After signing in and then signing out, the cloud workspace all becomes local workspace.

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4195]
https://toeverything.feishu.cn/docx/SsLwdY3kjoLAYpxPtKpc8NdTn9c?from=from_copylink

sorry the video can't be uploaded here, pls open the feishu doc

**Comment by houjoe0829** [comment]
Related with https://github.com/toeverything/AFFiNE/issues/4192
Missing multiple selection for logout.
