### ISSUE TITLE
There is no reaction upon clicking the Back Home button on the 404 Page.

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#4201]
<img width="1727" alt="image" src="https://github.com/toeverything/AFFiNE/assets/5910926/8640a66b-47b1-4ea2-b838-525fd8265e76">

@xell

**Comment by Garfield550** [comment]
Unable to reproduce.

https://github.com/toeverything/AFFiNE/assets/3471836/a870d986-395a-4a55-ab27-070e6434c24f

**Comment by joooye34** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/9527419/d849b8ae-dae4-4251-a690-e23b91cdf22d)
If the "last_workspace_id" workspace been deleted, this issue will happen, especially local or insider development.

**Comment by joooye34** [comment]
Do the following steps to replay this issue:
https://github.com/toeverything/AFFiNE/assets/9527419/8613e736-7ade-47d8-a260-41a6cb84199a
