### ISSUE TITLE
​ User name and Workspace name UI issue

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#4210]
Comparing to current product. 1. Avatar remove button is missing. 2. Save button for inputting name is missing. 3. success toast style is incorrect

[Check figma here](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=4708-114908&mode=design&t=PaYHC4OHvnF9kBjs-4)

The correct design should be: 

![Image](https://github.com/toeverything/AFFiNE/assets/110808979/500ff8bb-38d2-464c-9651-f1dd4269e160)

**Comment by QiShaoXuan** [comment]
Delete avatar need extra develop and create new issue : https://github.com/toeverything/AFFiNE/issues/4259
