### ISSUE TITLE
After the invitee agreed to join the Workspace, AFFiNE did not send an email to the Owner

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4216]
The purpose of this is to give the inviter some feedback after the invitee agrees to join the Workspace.

Please refer to [Internal doc](https://toeverything.feishu.cn/docx/K8FhdhGU8oIlNgxZyIJcmYPfnBb#AiXQdAQbqozOPyxU9JxcOVeInac) 011

**Comment by QiShaoXuan** [comment]
Waiting merge: https://github.com/toeverything/AFFiNE/pull/4152
