### ISSUE TITLE
[feature]: It is hoped that in the future, more platforms can be added for online video playback, as well as local video and audio playback, as well as PDF display (handwritten notes or boxed notes)

### ISSUE THREAD

**Issue by jiang123lim** [toeverything/AFFiNE#422]
### 1~3 main use cases of the proposed feature

希望未来可以增加更多平台的视频在线播放，还有本地视频与本地音频的播放，还有PDF的显示（手写注释或框选备注）

**Comment by tzhangchi** [comment]
Thank you for your feedback，These are important features and we will plan for them
