### ISSUE TITLE
In public shared pages, the read-only mode does not meet expectations

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4222]
Please refer to the [new PRD](https://toeverything.feishu.cn/docx/RXEQdSljro0CWqxNmHCcwGB8n8c#FSFFd9pPHoMxvQxCJCTchIF8nTd) for details

There are a lot of non-essential options exposed at the moment.

**Comment by houjoe0829** [comment]
I have separately organized the effect of the public shared page. You can take a look at [this document](https://affine-pro.slack.com/docs/T03K3CD2015/F05S5P1FXGQ).

**Comment by doouding** [comment]
Can we have a table that lists all the hidden parts on each block or component between "the public shared page" and "the read-only viewer"? Right now it's a little bit confusing.

**Comment by doouding** [comment]
I've done the most part in blocksuite, but some remained:
- The database part needs to create a new issue to track the progress independently. /cc @zzj3720 
- Some adaption should be done on the AFFINE side /cc @himself65 :
    - Image Preview
    - Page info hidden (This can't be hidden on the blocksuite side directly cause it should hide on the public page but be visible on read-only collaborators page)

Refer to:
https://github.com/toeverything/blocksuite/pull/4635
https://affine-pro.slack.com/docs/T03K3CD2015/F05S5P1FXGQ
