### ISSUE TITLE
Tolgee may be a better way to solve language localization

### ISSUE THREAD

**Issue by Avey777** [toeverything/AFFiNE#424]
For language localization solutions, this may be a simpler and smarter solution

Refer to：https://github.com/tolgee/tolgee-platform
![image](https://user-images.githubusercontent.com/35259040/190328088-e64de45f-a464-450d-ad8c-798c65378ff8.png)

**Comment by CJSS** [comment]
This is what we are currently using for our localization needs. Thanks for sharing.
