### ISSUE TITLE
Where is the path of the work space saved?

### ISSUE THREAD

**Issue by liuhaili** [toeverything/AFFiNE#4250]
### Description

Where is the path of the work space saved? Is it possible to set up a workspace path function? In this way, the data can be saved by itself, can be controlled by git version, and can be opened directly in the form of a folder.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
AFFiNE does not currently support custom data storage locations. This is in our future plans, but currently all data is stored in the default path.

On Windows, you can find it by following this path: C:\Users\%USERNAME%\AppData\Roaming\AFFiNE-xxx.

On Mac, you can find it by following this path: /users/%USERNAME%/Library/Application Support/AFFiNE-xxx.

Here, AFFiNE-xxx refers to different versions of AFFiNE, such as Beta or Canary versions.

In addition, we will soon support cross-device synchronization based on AFFiNE Cloud. Please stay tuned for updates. And We will temporarily close the current issue. Please feel free to reopen it if you have any further questions.
