### ISSUE TITLE
AFFiNE Cloud 2.0 1013

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4255]
- [ ] Revamp the Pricing Plan page
- [ ] Remove the copy and special logic previously added for Early Access
- [ ] https://github.com/toeverything/AFFiNE/issues/3992
- [ ] The first email after a new user registers needs to be ready
- [x] Add different restrictions for AFFiNE Cloud Free and Pro users
- [x] Mark the account to differentiate between AFFiNE Cloud Free and Pro users
- [ ] https://github.com/toeverything/AFFiNE/issues/3991
- [x] Support for account upgrades and downgrades
- [ ] AFFiNE Cloud supports permanently deleting accounts
- [ ] AFFiNE Cloud supports exporting all user data
- [ ] https://github.com/toeverything/AFFiNE/issues/3287
- [ ] Update of Terms of Use & Privacy Policy
- [ ] Adjustments to all pages for collaboration
- [ ] Support disabling AFFiNE Cloud
- [ ] https://github.com/toeverything/AFFiNE/issues/4001
- [ ] Clicking "Visit Workspace" could open the client for the invitee

**Comment by tzhangchi** [comment]
cc: @HeJiachen-PM @Yipei-Operation
