### ISSUE TITLE
The effect of deleting a page to the trash needs to be modified

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4282]
1. After being deleted, the deleted page should be closed automatically and returned to the all page list.
2. A toast message should pop up to indicate that "{page's name} has been moved to Trash".

Current effect:

https://github.com/toeverything/AFFiNE/assets/22443345/45d3881a-9578-4e89-b124-c5dd911f9ced

**Comment by om2137** [comment]
https://github.com/toeverything/AFFiNE/assets/33827410/8e9db880-5cad-412c-8b78-880f5c522b42

I think this issue can be handled by adding `jumpToSubPath` (which points to all page list) to delete button in delete page modal as you can see in attached video.

@houjoe0829 @himself65 can I open PR for this issue ?

**Comment by om2137** [comment]
> Delete-to-home.mp4 
> I think this issue can be handled by adding `jumpToSubPath` (which points to all page list) to delete button in delete page modal as you can see in attached video.
> 
> @houjoe0829 @himself65 can I open PR for this issue ?

@JimmFly @pengx17  can I open PR for this issue? 
let me know if it is not okay to tag other people to different issues, I will keep that in mind forward

**Comment by pengx17** [comment]
@om2137 sure, looking forward for your PR :)

**Comment by om2137** [comment]
https://github.com/toeverything/AFFiNE/assets/33827410/10f71fb0-32c8-4ab2-af1a-a4c4c45dae98

toast in move-to-trash button doesn't. Used Push notification(can see in attached video). Should I keep push notification in final PR or remove it?
