### ISSUE TITLE
When first logging in to the cloud, part of the previously created cloud workspace is blank

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4304]

**Comment by Yuhang1015** [comment]
https://github.com/toeverything/AFFiNE/assets/142964904/e444203d-e82c-4eb5-8580-6b809d6874ea

**Comment by hwangdev97** [comment]
![shot-2023-09-12-16 03 51@2x](https://github.com/toeverything/AFFiNE/assets/24713927/522d1300-be60-453f-90e0-be79972fa8cf)

[the design file](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=8463%3A7424&mode=design&t=DkbW1QwYJvp4Rp8L-1)
