### ISSUE TITLE
One AFFiNE Cloud account should not be bound to multiple Google accounts

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4319]
There is a serious account merging issue currently, which ultimately leads to an AFFiNE account being bound to multiple Google accounts. The scenario triggering this issue is when a user logs in with Google account A on the web version, and then continues to log in with Google on the AFFiNE client, but selects a different Google account B after being redirected to the browser. This will result in the merging of accounts, binding the AFFiNE account to both Google A and Google B.

**Comment by pengx17** [comment]
The easiest solution right now is to automatically signout the user on the browser if the user signin through google oauth, which is provided in https://github.com/toeverything/AFFiNE/issues/4319
