### ISSUE TITLE
There is no check for logging into an AFFiNE Cloud account before displaying the 404 page

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4320]
Currently, the display of the 404 page is very aggressive. When accessing a AFFiNE's link, the 404 page is displayed regardless of whether the user has logged into their account or not. The expected behavior is that if it is a link to a AFFiNE's workspace or page (excluding publicly shared links), the user should be redirected to the login page first and then re-evaluate whether they have permission to access the link.
<img width="1012" alt="EVipmD8QHJ" src="https://github.com/toeverything/AFFiNE/assets/22443345/435da0fb-0200-486b-be41-b32d76db8850">

**Comment by himself65** [comment]
Please correct the logic @QiShaoXuan

**Comment by Svaney-ssman** [comment]
Check the [design and interaction](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=14702-132921&mode=design&t=aMBY4mLSnI5DDctM-4) @houjoe0829  @QiShaoXuan

**Comment by houjoe0829** [comment]
> Check the [design and interaction](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=14702-132921&mode=design&t=aMBY4mLSnI5DDctM-4) @houjoe0829 @QiShaoXuan

This will be followed up in another issue.
