### ISSUE TITLE
When logged into an AFFiNE account on the web version, accessing a public link should not display 404 page

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4335]
![image](https://github.com/toeverything/AFFiNE/assets/22443345/6a335fbe-56b1-4754-ade9-0dbaf59aee5e)

The expected result is that public links can be accessed normally regardless of whether an AFFiNE account is logged in or not.

**Comment by himself65** [comment]
which link?

**Comment by houjoe0829** [comment]
> which link?

DM you in Slack

**Comment by Brooooooklyn** [comment]
https://insider.affine.pro/share/e10dd0b4-490a-481b-986d-7c2826e58622/ElaaRuNbcX
