### ISSUE TITLE
[feature]: Easy way to change font

### ISSUE THREAD

**Issue by recklessnl** [toeverything/AFFiNE#434]
### 1~3 main use cases of the proposed feature

I'd love to change the default font of Affine. On the docs website, I find the font very nice to look at, but the demo has another font that's less pleasant, and not changeable.

Can we add a feature where you can easily change the font in Affine?

### Ideas for solution

Add an option for general default font selection, perhaps also per-page font.

### what types of users can benefit from using your proposed feature

Everybody

**Comment by lawvs** [comment]
We will adjust the font style on windows later. Sorry for any inconvenience.
