### ISSUE TITLE
Unexpected Error message after switching to an Untitled workspace - also doesn't work after restarting it

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4340]
![Image](https://user-images.githubusercontent.com/142964904/267561382-2729cc46-cccc-4714-b497-71976daa534e.png)

While the user tried to switch to an untitled workspace, there was an error. This is what the user just did:
1) I just deleted the whole cache folder
2) Tried to start AFFiNE by clicking the icon on my Desktop, it didn't lauch. (I guess because that "App Data-Local-Affine" folder had everything in it, including the executable file, and not just cache)
3) I downloaded the latest stable version (0.8.3) and installed it.
4) Launched it but it still throws the exact same error

Discord Link: https://discord.com/channels/959027316334407691/959033875856756756/1151405461954887752

**Comment by ShortCipher5** [comment]
Another user reports similar problems:

> I receive a similar error after creating a Workspace using the Beta version installed on Windows 11. Then I installed the stable version and imported the workspace.
> I had to export my Workspace from the Beta app and open with stable on a different PC after uninstalling and removing all the app data
> My Exports are empty. I tried exporting a page as both HTML and Markdown but the compressed .zip files are empty!

https://discord.com/channels/959027316334407691/959033875856756756/1152244332397609050
