### ISSUE TITLE
New Language for Interface

### ISSUE THREAD

**Issue by HBmatias** [toeverything/AFFiNE#4348]
### Description

Could you provide Portuguese as a language in the application?

### Use case

Unfortunately, Portuguese speakers have little affinity with the English language or other available languages, so it would be great to provide the application in Portuguese.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ShortCipher5** [comment]
Hi there @HBmatias,

We do have an i18n project - all of our translations are community powered.

For more information you can visit our community site: https://community.affine.pro/c/i18n-general/
