### ISSUE TITLE
The language switching menu does not pop up correctly

### ISSUE THREAD

**Issue by JimmFly** [toeverything/AFFiNE#4362]
https://github.com/toeverything/AFFiNE/assets/102217452/672350fb-a79f-464a-b404-ecb261e0a950

**Comment by om2137** [comment]
https://github.com/toeverything/AFFiNE/assets/33827410/1917efdf-5bd0-4726-91f6-6bed0bab8c2a

Can't reproduce the issue. I have updated my fork to latest.
