### ISSUE TITLE
Articles in the collection, the three dots on the right cannot be clicked

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4373]
![Image](https://user-images.githubusercontent.com/142964904/268196195-ff16380e-75fd-4e0b-8c41-101609edb073.gif)

**Comment by AFreeBaldy** [comment]
What version are you using, I can't reproduce this, on windows stable release

**Comment by Yuhang1015** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/142964904/f7d7f7e4-ebc6-407f-ba10-6a6659bd18bf)

**Comment by AFreeBaldy** [comment]
seems like its also a problem in the canary version. this is something i could definitely fix. I will get on it

**Comment by AFreeBaldy** [comment]
After buidling the canary version it seems like the problem is already fixed, as i do not have access to your internal version i wont be able to help

**Comment by Yuhang1015** [comment]
If it has been fixed in the latest version, I think it can be closed! In the lateser intenal version (0916), this issue doesn't exist.

**Comment by joooye34** [comment]
fixed
