### ISSUE TITLE
AFFiNE avatar blobs blinks when rendering

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#4382]
### What happened?

We could have a LRU cache for `createObjectURL` instead of creating one on request.

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joooye34** [comment]
Is this the workspace blinking issue when workspace list show ?

**Comment by pengx17** [comment]
oh, it should have been fixed in https://github.com/toeverything/AFFiNE/pull/4454
