### ISSUE TITLE
When the system language is switched to Chinese, there is still some English left

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4391]
![Image](https://github.com/toeverything/AFFiNE/assets/142964904/ff182131-31f4-4d29-ad47-e4e8f5ca75c7)

**Comment by houjoe0829** [comment]
简中/繁中
Font Style: 字体/字體
Choose your font style：选择你的字体风格/選擇你的字體風格
Sans：无衬线字体/無襯線字體
Serif：衬线字体/襯線字體
Mono：等宽字体/等寬字體

**Comment by om2137** [comment]
@houjoe0829  can I raise PR with changes?

**Comment by om2137** [comment]
https://github.com/toeverything/AFFiNE/assets/33827410/0865f075-7a13-4df9-8284-540d542ea53e

**Comment by JimmFly** [comment]
Oh, you can handle it with the i18n component. As for the content translation, you are welcome to contribute your translations on our platform. Later, one of our colleagues will invite you to join the translation platform. 
/cc @om2137  @ShortCipher5

**Comment by ShortCipher5** [comment]
https://community.affine.pro/c/i18n-general/

**Comment by joooye34** [comment]
fixed by #4448
