### ISSUE TITLE
Logged user can not visit shared page if this user is not in the workspace

### ISSUE THREAD

**Issue by Brooooooklyn** [toeverything/AFFiNE#4404]
You can test this issue with the link: https://insider.affine.pro/share/e10dd0b4-490a-481b-986d-7c2826e58622/ElaaRuNbcX

**Comment by houjoe0829** [comment]
Duplicated with https://github.com/toeverything/AFFiNE/issues/4335 ？

**Comment by Brooooooklyn** [comment]
Yes, I'll close this one.
