### ISSUE TITLE
When creating a workspace, selecting the option for cross-platform synchronization does not meet the expected result

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4407]
![image](https://github.com/toeverything/AFFiNE/assets/22443345/1daed67a-8154-4c1f-9bc4-3553295f6df4)

If you are already logged in, then this new workspace will automatically become a cloud workspace. If you are not logged in, then the prompt below will appear.

<img width="621" alt="CleanShot 2023-09-18 at 17 14 38@2x" src="https://github.com/toeverything/AFFiNE/assets/22443345/0b12bb1c-dc15-44b4-b12c-85cd371d9644">

**Comment by AFreeBaldy** [comment]
Wait so what is the problem exactly, is it that it's not syncing or do you want to get rid of the ui asking you to sign in, if the workspace is already synced.

**Comment by houjoe0829** [comment]
> Wait so what is the problem exactly, is it that it's not syncing or do you want to get rid of the ui asking you to sign in, if the workspace is already synced.

If you select 'Use on current device only', synchronization will not be enabled and it will only be used on the current device. If you select 'Sync across devices with AFFiNE Cloud', it will go through the process of enabling AFFiNE Cloud synchronization, which are the two situations mentioned above.

**Comment by houjoe0829** [comment]
Due to the new interaction design waiting to be done, the temporary solution is to suggest removing the pop-up process and creating a local workspace by default to avoid confusion.  cc @joooye34
