### ISSUE TITLE
Support for aggregation row and linked column in table of database​

### ISSUE THREAD

**Issue by XJTLUmedia** [toeverything/AFFiNE#4413]
### Description

1. Aggregation row should be able to use code to calculate aggregation, sort just like SQL
2. Linked column should be able to change value automatically when there are change in another column

### Use case

1. Last row should be aggregation row, using function include sum(),count(),percentile(),max(),min() etc.
2. Suppose Column C is linked column of A and B, which is calculated based on A+B, so the column C should be 6 and 9. If Column A row 1 change to 3, Column C row 1 will automatically update to 7
|A|B|C|
|--|--|--|
|2|4|  |
|3|6|  |
5 10  

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you very much for your feedback. Currently, this is in the future iteration plan, but it has not started yet. We will temporarily close this issue. If there are any further questions or changes, please feel free to reopen it.
