### ISSUE TITLE
cards in page mode​

### ISSUE THREAD

**Issue by GitVking** [toeverything/AFFiNE#4418]
### Description

I have created multiple notes in edgeless mode. These notes, which are not linearly related, are displayed on the page in chronological order of creation. Additionally, these notes are also presented as cards in the right sidebar. The order of the cards can be adjusted. I would like to inquire about the following possibilities:

1. Is it possible to hide specific cards in page mode?

2. Can a card be converted into an independent page to facilitate easier editing?

### Anything else?

https://community.affine.pro/c/feature-requests/cards-in-page-mode

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
![CleanShot 2023-09-20 at 11 00 59@2x](https://github.com/toeverything/AFFiNE/assets/22443345/4d4b0926-f194-4b17-84d9-5e354b1a6eed)
- For the first question, you can currently operate here. You can try it to see if it solves your problem.
- For the second question, it is currently not supported temporarily. However, it is in the plan, but has not started yet.

**Comment by GitVking** [comment]
The first question is solves! Thanks very much!

**Comment by houjoe0829** [comment]
Got it, we will temporarily close this issue. If there are any further questions or changes, please feel free to reopen it.
