### ISSUE TITLE
create a list while don't have to switch english input method​

### ISSUE THREAD

**Issue by GitVking** [toeverything/AFFiNE#4419]
### Description

Hi, I'm from China. Usually I edit content in Chinese. 
I have to switch to english input method before I type '1' , '.' and 'blank'  if I want to create a list . 
Is it possible to do this by directly type '1' , '。' and 'blank' ?
I can do this in 语雀.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you very much for your feedback. Currently, there is no plan for this yet, but it may be considered in the future. We will temporarily close this issue. If there are any new changes or questions, you can reopen it at any time.
