### ISSUE TITLE
The arrow in edgeless mode doesn't adapt to dark mode and light mode​

### ISSUE THREAD

**Issue by GitVking** [toeverything/AFFiNE#4420]
### What happened?

Can’t see the arrow clearly when you switch the other mode

### Distribution version

macOS x64 (Intel)

### Anything else?

https://community.affine.pro/c/bug-reports/the-arrow-in-edgeless-mode-doesn-t-adapt-to-dark-mode-and-light-mode

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hwangdev97** [comment]
Thank you for your issue.

This is a known issue, and we will change the default color of the arrow to make it look more appropriate in both dark and light.

Currently, you can change the color by selecting the arrow. 

You can see the progress in this issue: https://github.com/toeverything/blocksuite/issues/4538
