### ISSUE TITLE
Pre-loading directory cannot be expanded

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4435]
![Image](https://github.com/toeverything/AFFiNE/assets/142964904/5d7639e7-8f65-4160-bf22-f9e004d7653b)

internal version (0921): https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-internal.20230921060219-2521f2e

**Comment by joooye34** [comment]
@pengx17 need to check this issue

**Comment by pengx17** [comment]
@Yuhang1015 sorry I cannot reproduce this issue. Can you share your db file offline?
