### ISSUE TITLE
Mac 10.14.6 system cannot open internal (mac x64)

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4436]
![Image](https://github.com/toeverything/AFFiNE/assets/142964904/f009035c-ecf9-4e08-b21c-0f5fee64cf9c)

**Comment by YanxinLu0122** [comment]
https://github.com/toeverything/AFFiNE/assets/144991896/b007091d-dc55-40f0-ba15-87f604b08d93

**Comment by houjoe0829** [comment]
Can not reproduce it any more, Close it
