### ISSUE TITLE
New user guidance content cannot be displayed

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4437]
![Image](https://github.com/toeverything/AFFiNE/assets/142964904/5bb16fa1-297f-499f-8a80-fb3756cda793)

**Comment by himself65** [comment]
![Uploading image.png…]()

**Comment by himself65** [comment]
![Uploading image.png…]()

**Comment by himself65** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/14026360/69981b85-6574-4fbf-b15a-f65a91b320ec)

**Comment by pengx17** [comment]
I am sorry. I forgot to link the related fix https://github.com/toeverything/AFFiNE/pull/4441
