### ISSUE TITLE
Too many workspaces to scroll, making it impossible to create a new workspace

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/AFFiNE#4438]
![Image](https://github.com/toeverything/AFFiNE/assets/144991896/7c959d91-39ed-4c7e-9773-c03e7f969d1e)

**Comment by houjoe0829** [comment]
I can reproduce it in the newest Canary version. When there are too many workspaces, the Workspace list cannot scroll.

**Comment by joooye34** [comment]
Have been fixed by https://github.com/toeverything/AFFiNE/issues/4402
