### ISSUE TITLE
AppImage failed to be installed via AppImageLauncer​

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#4443]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/584378/39ae9e50-1f42-4622-a1bb-fd058aedb46a)

### Distribution version

Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
duplicated of https://github.com/toeverything/AFFiNE/issues/4500

**Comment by Dilettante258** [comment]
You are talking to each other under so many similar issues, which almost knocked me out. So since the issue has been closed, is there a solution? OK, Won't fix, can't repro, duplicate, stale...
