### ISSUE TITLE
The safe area with padding at the bottom of the page is missing, and there is also a white bar that covers the content

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4461]
1. The lack of sufficient safe area will affect the experience of content editing and reading.

![CleanShot 2023-09-22 at 17 18 34@2x](https://github.com/toeverything/AFFiNE/assets/22443345/d6dd74d0-a7d1-490b-aa2c-cea3296a3f54)

2. Now there is also a white bar at the bottom.

![CleanShot 2023-09-22 at 17 20 10@2x](https://github.com/toeverything/AFFiNE/assets/22443345/5b4e431f-d47a-4faa-a357-751d0daae2e6)

**Comment by SyedZain714** [comment]
Can you please attach any video?
