### ISSUE TITLE
storybook preview regression

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#4464]
https://github.com/toeverything/AFFiNE/commit/e0063ebc9bf5ddef81cf508b4ddab56b319a30ca

**Comment by pengx17** [comment]
@himself65 do you mean to approve changes in Chromatic right? Sorry I missed these. Will ask the designers to check them.

**Comment by himself65** [comment]
No, didn't you see the preview lost the search component?

**Comment by himself65** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/14026360/a14e9130-1575-4139-95be-3e6ecbf15b11)

**Comment by pengx17** [comment]
Will add it back today
