### ISSUE TITLE
Linux app of Affine doesn't work for Cloud login​

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/AFFiNE#4466]
### What happened?

1. I enter my email address into the Affine Cloud loging pop window.
2. The app tells me to check my email for a token-based login.
3. It directs me to a website to click an authentication token link to open the app.
 
The problem is I'm using Linux Mint, and when I click on the link the browser asks me if I want to use "xdg-open", which is a way to open applications from the browser, but I don't have Affine registered as an application because you packaged it as a standalone zip file
 
The other option you provided, to login with a password, does not work. When I try to use my forum password (the only one I have), it says password is incorrect.

### Distribution version

Linux

### Anything else?

I'm not an expert in Linux but I believe the web browser uses xdg-open to open applications from links clicked in the browser.

For xdg-open to work I found this but it's too complicated for me to spend time to figure out (there are missing steps): https://askubuntu.com/questions/62585/how-do-i-set-a-new-xdg-open-setting

IMO, Affine needs to be packaged as a Snap, Flatpack, Deb, or Rpm package in order for it to be registered in xdg-open without having to manually configure xdg-open. The .appimage package may also work but I'm not sure.

Linux users are often more tech-savvy but I think they will be frustrated with this login flow if it doesn't work out of the box and they have to manually make the fix. Also there are more non-tech users using Linux so I would encourage changing the way AppFlowy is packaged.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fayasgit** [comment]
Hi there team, is this fixed?

**Comment by joooye34** [comment]
> Hi there team, is this fixed?

@fayasgit I am so glad to receive your feedback. @pengx17 will take this and find out what's wrong.
