### ISSUE TITLE
web version of Affine cloud shows "upgrade workspace" and nothing else​

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/AFFiNE#4469]
### What happened?

- Logged into insider.affine.pro.
- Created new workspace
- connected new workspace to the cloud
- deleted demo workspace
- Welcome page on new workspace showed up correctly
- used "/" and selected new page.
- Created page called "Tasks"
- Clicked on "Tasks" link.

Following screenshot is what appeared. and now all of the pages I click on only show the following. Clicking on "Upgrade Workspace" does nothing.
![image](https://github.com/toeverything/AFFiNE/assets/51060565/7581fe03-deb1-41bb-b24b-9aecbb98cdf8)

### Distribution version

Web (insider.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chromium Browser

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fundon** [comment]
Same problem. 
<img width="1357" alt="Screenshot 2023-09-25 at 10 25 24 AM" src="https://github.com/toeverything/AFFiNE/assets/27926/0007c3de-6915-4ef5-9dba-774cd7e68548">

**Comment by joooye34** [comment]
This issue is duplicated with https://github.com/toeverything/AFFiNE/issues/4304. We try to upgrade local workspace to new version automatically. But if failed and transformed to be cloud, this issue will show.

**Comment by joooye34** [comment]
We have designed the manual upgrade feature and will implement later.

**Comment by joooye34** [comment]
@himself65 The log from @fundon show this "versions" maybe undefined, any ideas?
![image](https://github.com/toeverything/AFFiNE/assets/9527419/66ee404d-b283-4ef3-9290-e89d5e02d30e)
