### ISSUE TITLE
​Date selector should be ISO format

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/AFFiNE#4470]
### Description

When using the date selector in the table, Affine chose the least preferred date format in the world, the Month-Day-Year option. This is the most confusing and least logical date format.

Please allow for the ISO date format (YYYY-MM-DD) to be used. I would encourage it to be the default to promote good practices. Affine's motto is "To Shape, not to Adapt", so I think adapting to an inefficient date format is not in line with Affine's mission.

### Use case

This would be used by anyone outside of the USA who believes in international standards.

### Anything else?

https://www.iso.org/iso-8601-date-and-time-format.html

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zzj3720** [comment]
Since this input is currently native, there is no way to customize its format.
Maybe we can implement one to replace it later, but it will take some time to make it accessible enough.

**Comment by houjoe0829** [comment]
Thank you for your feedback. Due to current implementation limitations, a unified format cannot be implemented yet. However, we will consider this suggestion in the future. We will temporarily close this issue. If there are any further questions or changes, please feel free to reopen it.
