### ISSUE TITLE
Can't export nor import[bug]: 

### ISSUE THREAD

**Issue by notaprodev** [toeverything/AFFiNE#449]
### Describe the bug

I am self-hosting an affine instance, and I was playing around, but i am unable to export nor import any files. It is present on the livedemo instance

### To Reproduce

1. Go to your instance or demo instance
2. Click export
3. Nothing same for import

### Screenshots

![Screenshot from 2022-09-21 13-18-33](https://user-images.githubusercontent.com/64326282/191490898-3ed21762-a9f0-49f9-b2bb-0f1d031e6018.png)
![Screenshot from 2022-09-21 13-18-11](https://user-images.githubusercontent.com/64326282/191490906-f8e79bec-a055-4ba3-9fc6-08de12b0beea.png)

### Expected behavior

Save a file and then later be able to import it

### Platform

Ubuntu 

### Browser

Chrome

### Additional context

The stage thing is that i am able to export and import on my local docker container but not in a VPS.
Some details about the setup:
using nginx as a proxy 
certbot for the ssl

**Comment by CJSS** [comment]
We're looking into this, thanks.

**Comment by lawvs** [comment]
Sorry for any inconvenience. We will fix this as soon as possible.

**Comment by notaprodev** [comment]
Thank you for the quick fix
