### ISSUE TITLE
The updated time data in the 'All page list' is incorrect

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4494]
From the actual experience, the current 'Updated' should be the last viewed time, which is not as expected.

![CleanShot 2023-09-25 at 21 55 03@2x](https://github.com/toeverything/AFFiNE/assets/22443345/ca010fe9-a752-4dbf-b54b-d2ea8eaefe93)

**Comment by forehalo** [comment]
@joooye34 btw, Im always confused about why the `updated` should be last viewed time. I will never expect the time changes without any updates on the doc itself

**Comment by joooye34** [comment]
I am not sure this logic, let me check it.
