### ISSUE TITLE
[bug]: Tag pop-up is obscured

### ISSUE THREAD

**Issue by QiShaoXuan** [toeverything/AFFiNE#45]
**Describe the bug**
In whiteboard mode, the tag pop-up is obscured

**To Reproduce**
1. Change mode to whiteboard 
2. Click the exist tag to display pop-up

**Screenshots**
![image](https://user-images.githubusercontent.com/22772830/182368678-1887e29c-99dc-4ff3-b577-723c9d5d0d9f.png)

**Comment by fyZheng07** [comment]
The function box is also blocked in text view @QiShaoXuan 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63830919/182811396-45f3daa1-71b2-4d2d-8da7-d5c63024ad24.png">
