### ISSUE TITLE
Cloud ​membership pagination issues

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#4503]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/584378/7d360f41-cf72-4ecc-9b0b-b163d8c9ffd5)
It seems the pagination handling is still incorrect.
Also should hide pagination ui when there is only one membership page 

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Svaney-ssman** [comment]
Please check [details on Figma](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=15377-59534&mode=design&t=hfWx6IUAzr59X7eN-4)
1. Hide pagination when the number of members is less than or equal to 8
<img width="754" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/72855874-c7a5-4cb4-a155-e58d2d730405">

2. Fix height while the number is over 8 even when the last page's number is less than 8
<img width="1431" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/e388fe27-9fb7-46fa-865b-25ce123d28c4">

**Comment by forehalo** [comment]
@Svaney-ssman open a new issue to track ui problem
