### ISSUE TITLE
’Discover What's new‘ will jump to blog 'launch week day 5'——intenal 0.8.4

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4509]
![Image](https://github.com/toeverything/AFFiNE/assets/142964904/f7537c73-dc3b-4937-8d5f-4a2bac5cdb05)

I'm not sure if this jump page is what you want, but “Discover What's new” in beta 0.9.0 will also jump to the previous blog. Both versions may need to be checked.

**Comment by Yuhang1015** [comment]
![Image](https://github.com/toeverything/AFFiNE/assets/142964904/73a1321a-fec8-4eb2-a796-b9940d1eaa90)

beta 0.9.0 "Discover What's new"

**Comment by houjoe0829** [comment]
The "Discovery What's new" button of AFFiNE Beta and Stable versions should all jump to [this link](https://affine.pro/what-is-new) after clicking.
