### ISSUE TITLE
Cursor Moves to Center of Shape Block When Clicking Note Block.

### ISSUE THREAD

**Issue by GitVking** [toeverything/AFFiNE#4516]
### What happened?
I have encountered a potential bug and I'm not sure if it's intended behavior. Whenever I click on the note block, the cursor moves to the center of a shape block. This behavior seems unexpected and may indicate a bug.

![CleanShot 2023-09-27 at 00 22 31](https://github.com/toeverything/AFFiNE/assets/49601977/984592e3-0f9b-42cd-89de-818f262eedac)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by donteatfriedrice** [comment]
Hi, thanks for your feedback, I think we have solved the issue in later editor version, maybe you can check it again in our next version.
