### ISSUE TITLE
Change the width of the editing area to `944px`

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#4524]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/24713927/fd41579a-245d-4998-99fe-11ed1cdb7b42)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Karan-Palan** [comment]
I'd like to work on this!

**Comment by joooye34** [comment]
@Karan-Palan I am so glad to expect your PR. Any questions if you have, just tell me.
