### ISSUE TITLE
Adjust the interaction design logic of Copy link in Sharing page

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4528]
Related with https://github.com/toeverything/AFFiNE/issues/4485

The current design effect needs to be adjusted, you can [check this doc](https://insider.affine.pro/workspace/af3478a2-9c9c-4d16-864d-bffa1eb10eb6/pIZG3S_9DB).

**Comment by joooye34** [comment]
Is this a design issue ?

**Comment by houjoe0829** [comment]
> Is this a design issue ?

Yes, it can be considered a purely UI design issue

**Comment by Svaney-ssman** [comment]
Check [design in figma](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=11287-252990&mode=design&t=tqNtBn9THvUQ82dB-4)
