### ISSUE TITLE
​Error when activating affine cloud on a workspace 

### ISSUE THREAD

**Issue by OneMoonLeft** [toeverything/AFFiNE#4531]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/115279639/2b3e8219-0ee8-46c9-851b-fe377f5c588f)
Error when i tried 

### Distribution version

Windows x64

### Relevant log output

```shell
Version
0.9.0-beta.1

Editor version
0.0.0-20230921103931-38d8f07a-nightly
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/blob/2f6c4e36965bab1c77f36ea28774beac3aa2e998/apps/core/src/hooks/use-workspace.ts#L19

**Comment by joooye34** [comment]
This seems happened when connecting cloud and id changing.
