### ISSUE TITLE
Cannot copy & paste in beta 0.9.1​

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#4536]
### What happened?

One user reports that he cannot copy & paste at all using Mac with the latest beta version. Need more time to investigate.

Possibly related to?
https://github.com/electron/electron/blob/5af6b898d92432369ce9495e75d75b02af651531/lib/browser/api/menu-item-roles.ts#L36-L41

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AreChen** [comment]
Cannot copy in beta 0.10.2

**Comment by AreChen** [comment]
Although code block copying is available in 0.11.1, the copied content is in MD format instead of actual code.
