### ISSUE TITLE
​Tags prompt not getting erased after pressing enter

### ISSUE THREAD

**Issue by OneMoonLeft** [toeverything/AFFiNE#4537]
### What happened?

When I Look for a Tag and have it on top, then press enter to have it selected the tag comes in but the prompt doesnt get erased (see on video)

### Distribution version

Windows x64

### Anything else?

https://github.com/toeverything/AFFiNE/assets/115279639/68f465f6-7bb4-46db-a917-27ad8fafebc2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by OneMoonLeft** [comment]
(Also missing translation but that's another thing, i'll ask shortcipher for that)

**Comment by OneMoonLeft** [comment]
Version
0.9.0-beta.1
Mode Édition
0.0.0-20230921103931-38d8f07a-nightly

**Comment by houjoe0829** [comment]
In the expected effect, the previously entered keywords should be eliminated after confirming with the Enter key.
