### ISSUE TITLE
Multiple files import ​

### ISSUE THREAD

**Issue by OneMoonLeft** [toeverything/AFFiNE#4538]
### Description

Cannot import multiple markdown files on AFFiNE.. I have aprox 790 markdown files to import is there any faster way?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by OneMoonLeft** [comment]
App Version
0.8.4
Editor Version
0.0.0-20230830111255-92eab248-nightly

**Comment by houjoe0829** [comment]
Duplicated with https://github.com/toeverything/blocksuite/issues/4307
