### ISSUE TITLE
Edgeless improvement

### ISSUE THREAD

**Issue by ForteDexe** [toeverything/AFFiNE#4556]
### Description

Display each item in the database as a card, with its property.

### Use case

In my job environment, dependency is always an issue, with the feature as described above, I can draw all the dependency on the whiteboard, every time the upstream make an update on its properties, I will know which task is affected by it.

### Anything else?

I don't know if you guys checked the Fibery whiteboard yet, but their board really powerful, it can do what I described above.

Fibery example:
![image](https://github.com/toeverything/blocksuite/assets/57673412/75922a9c-5ec3-4c59-9990-fc43c70df65a)
![image](https://github.com/toeverything/blocksuite/assets/57673412/1f9a9449-7e0e-4ba9-85a4-4d8b5a8c0994)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you very much for your feedback. There are currently no relevant plans. However, we will consider this requirement in future iterations and continue to pay attention to other similar feedback. And we will temporarily close this issue. If there are any further questions or changes, please feel free to reopen it.
