### ISSUE TITLE
Potential security breach of desktop app​

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#4557]
### What happened?

In the current workflow, a bad guy could make a fake electron app, register the same scheme like affine:// and intercept the user token.

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by HeJiachen-PM** [comment]
You good boy against the bad guy

Peng Xiao ***@***.***>于2023年10月2日 周一01:33写道：

**Comment by forehalo** [comment]
planned in new auth system
