### ISSUE TITLE
In dark mode "Help and Feedback​" button's tip is black

### ISSUE THREAD

**Issue by khalid4060** [toeverything/AFFiNE#4558]
### What happened?

Tool tip should be blue as other tool tip in dark mode

![Screenshot from 2023-10-03 02-56-31](https://github.com/toeverything/AFFiNE/assets/65712756/7c90f962-7c98-4b35-beba-6833153d5444)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by aditya-sodhiya** [comment]
I would like to take this one. Please assign it to me.

**Comment by joooye34** [comment]
@aditya-sodhiya Welcome and you can create pr and let me review.

**Comment by joooye34** [comment]
@khalid4060 What version are you seeing the problem? Client or browser ?

**Comment by khalid4060** [comment]
I am working on it @joooye34 , problem is in browser

**Comment by aditya-sodhiya** [comment]
@khalid4060 @joooye34 , I was unable to replicate this. Can you please walk me through steps to reproduce it?
