### ISSUE TITLE
Disabled form item in the settings can still be operated via keyboard

### ISSUE THREAD

**Issue by CatsJuice** [toeverything/AFFiNE#4570]
### What happened?

The `Publish` toggle is disabled, but it can still be focused and operated via keyboard.

https://github.com/toeverything/AFFiNE/assets/39363750/f3f56082-4607-4a6f-98e5-3c0da0a00275

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Noothan-am** [comment]
hey @CatsJuice, i am not able reproduce this issue please give me more steps.

**Comment by CatsJuice** [comment]
> hey @CatsJuice, i am not able reproduce this issue please give me more steps.

1. open `settings`
2. click `workspace name` input to focus on it
3. toggle with `Tab` until the publish tooltip is displayed
4. press `Space` bar

**Comment by aditya-sodhiya** [comment]
@JimmFly please assign this to me. I can take this up.
/attempt #4570

**Comment by JimmFly** [comment]
> @JimmFly please assign this to me. I can take this up. /attempt #4570

I'm overwhelmed by your proactive contributions, could you all discuss amongst yourselves who will fix this issue?
/cc @Noothan-am @aditya-sodhiya

**Comment by joooye34** [comment]
@aditya-sodhiya Thank you so much for your PR. The PR from @electron97 is ok and we merged. So glad to see your PR next time.
