### ISSUE TITLE
[bug]: Can not show image option

### ISSUE THREAD

**Issue by sudongyuer** [toeverything/AFFiNE#459]
### Describe the bug

Can not show image option

### To Reproduce

1. write down  '/'
2. choose image option
3. click the image button

### Screenshots

![image](https://user-images.githubusercontent.com/76603360/192105254-96d4fcc0-19f1-444e-aa2b-9f72fd924e6d.png)

### Expected behavior

open the image option window

### Platform

MacOS

### Browser

Chrome

### Additional context

Just see the video information below 
https://jam.dev/c/a494e4b2-fd13-4cef-88e8-e63d76b7c7c1

**Comment by CJSS** [comment]
Thank you for reporting this.

Currently this "Add an image" seem to only be a placeholder - and does not contain the file upload logic. The actually file upload dialogue does not appear to pop-up correctly in the Kanban mode.

As a quick workaround may I suggest you switch to text view - insert an image (use the dialogue box that shows) and then you can switch back to Kanban.

**Comment by sudongyuer** [comment]
Thx reply～ should i close this issue ？

**Comment by lawvs** [comment]
We also updated the interaction, you can upload an image in the Kanban mode after https://github.com/toeverything/AFFiNE/pull/464 merged, thank you for the feedback.
