### ISSUE TITLE
​Text search within documents

### ISSUE THREAD

**Issue by bestrocker221** [toeverything/AFFiNE#4591]
### Description

Hi, thanks for the project!
I cannot find a way to search (the classic way with ctrl+f) within a page. Is that a missing feature?

The ctrl+k searches text in all the documents and brings you to the one (although it still does not bring you to the exact string match location within the document, which is a bit annoying).

Is it possible to add the in-document search functionality?

### Use case

Basic quick searching usage

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Related: https://github.com/toeverything/AFFiNE/issues/4607

**Comment by EYHN** [comment]
Duplicate with https://github.com/toeverything/AFFiNE/issues/5479
