### ISSUE TITLE
[bug]: ALT-drag rectangle original copy disappears switching Edgeless to Paper mode

### ISSUE THREAD

**Issue by vizanto** [toeverything/AFFiNE#460]
### Describe the bug

After duplicating a rectangle with text multiple times and editing them, switching to Paper mode only remembers the last modified copy.

### To Reproduce

In the [online demo](https://livedemo.affine.pro)

1. I created a rectangle and added text.
2. then ALT-dragging to duplicate 
3. changed text of duplicate
4. switched to paper mode

The original disappears, only the last copy remains.

### Expected behavior

No rectangle should disappear switching between modes.

### Platform

OSX

### Browser

Safari 15.6.1

**Comment by CJSS** [comment]
I have managed to replicate this following your instructions (option key for Mac).

Thank you for reporting this.
