### ISSUE TITLE
It would be better if the title is derived from the file name

### ISSUE THREAD

**Issue by francisxihe** [toeverything/AFFiNE#4603]
### Description

In Affine, when importing a Markdown file, the title is taken from the first line of the file's content, rather than the file name.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you for your feedback. For Markdown files, the first line is usually the real title of the Markdown file. This is also the standard Markdown format processing. We will retain the current processing logic for the time being, but we will continue to pay attention to other related feedback in the future.
