### ISSUE TITLE
REST Api​

### ISSUE THREAD

**Issue by kmlkcl** [toeverything/AFFiNE#4609]
### Description

As a software dev team, we have many other tools to collaborate and I'd like to automate some processes, like creating a document with automation.  

### Use case

Dev teams can use this kind of features. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Brooooooklyn** [comment]
We will have an open GraphQL API in the future

**Comment by EYHN** [comment]
This feature is not in our short-term plan, I will close this issue first

**Comment by shiny** [comment]
API is quite useful for Headless CMS purpose, it’s unfortunate that it’s missing.

**Comment by laelhalawani** [comment]
Great thing about Notion is the API

**Comment by ddean6232** [comment]
where are you at with provisioning an REST API for the product?

**Comment by SChoumiloff** [comment]
What is the current status of API support?

**Comment by WaldemarEnns** [comment]
Same question here. Would really appreciate an API to integrate with automation-tools.

**Comment by karahanyilmazer** [comment]
Same question here. It is a major holdup to fully migrating to Affine.

**Comment by mkostechuk** [comment]
+1, that would be a game changer for some teams (like mine)

**Comment by Keith-Hon** [comment]
Will be to use affine as a data source for chatbot with the restapi

**Comment by M0okz** [comment]
Our team also waitting
