### ISSUE TITLE
Multiple File Selection On All Pages​

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/AFFiNE#4610]
### Description

When I create a new workspace, it's filled with template stuff. Either creating the workspace totally empty, and/or being able to select multiple files to delete would be nice

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Duplicated with https://github.com/toeverything/AFFiNE/issues/2305
Thank you
