### ISSUE TITLE
Filtering To-do items ​

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/AFFiNE#4613]
### Description

An overview of all to-do items in a workspace with their root (like from document x, or edgeless y) 

### Use case

That's highly probable that a team of collaborators will put a to-do here and there on an edgeless document. A cluster view of all todo's on each document would be very helpful so we don't miss things.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you very much for your feedback. This is indeed part of our future plans, however, there are no specific detailed plans for its implementation yet. And we will temporarily close this issue. If there are any further questions or changes, please feel free to reopen it.
