### ISSUE TITLE
Delete several pages at once

### ISSUE THREAD

**Issue by jmbuster** [toeverything/AFFiNE#4614]
### Description

Hello guys, I have been using it for not too much time, I would like to have the option to delete several notes at a time.

### Use case

Sometimes I create notes for any project or study, but It has been a long time since I used or opened them, and I don't need them anymore. it is a little annoying to delete one page at a time.

### Anything else?

.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kemalakcc** [comment]
Seems like I suggested something similar a few hours ago: https://github.com/toeverything/AFFiNE/issues/4610

**Comment by houjoe0829** [comment]
Duplicated with https://github.com/toeverything/AFFiNE/issues/2305
Thank you
