### ISSUE TITLE
A way to unsync?​

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/AFFiNE#4623]
### Description

My early access is activated 🥳  I just synced a workspace randomly, but it seems it's a one way ticket 😄 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you very much for your feedback. Currently, this is in the future iteration plan, but it has not started yet. You can check the progress here. https://github.com/toeverything/AFFiNE/issues/4627
