### ISSUE TITLE
BUG: ​Could not find a declaration file for module '@toeverything/y-indexeddb'.

### ISSUE THREAD

**Issue by zhe-he** [toeverything/AFFiNE#4624]
### What happened?

```typescript

import { createIndexedDBProvider, type IndexedDBProvider } from "@toeverything/y-indexeddb"; // Could not find a declaration file for module '@toeverything/y-indexeddb'

```

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Other

### Anything else?

I looked into the issue, and it turns out that the problem is due to the absence of the types property declaration in the package.json file.

Here is a screenshot of the package.json in the npm repository.

<img width="606" alt="image" src="https://github.com/toeverything/AFFiNE/assets/11306583/57075ae3-464a-4aba-b51d-798f785c01f5">

Now I manually opened the file node_modules/@toeverything/y-indexddb/package.json and added "types": "./dist/index.d.ts" at the bottom to resolve this issue.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Could you please give me a mini reproduction?

**Comment by himself65** [comment]
Please also set moduleResolution to `bundler`. Since it's not a cjs module

```json
{
  "compilerOptions": {
    "moduleResolution": "bundler"
  }
}

```

**Comment by himself65** [comment]
See https://gist.github.com/himself65/f4a62f8a421ed92198867cfc9ad44b16

**Comment by zhe-he** [comment]
Thank you, I just need to change the value of moduleResolution from `nodenext` to `bundler`. 
Hmm... If I want to keep the value of moduleResolution as `nodenext`, are there any other solutions?
