### ISSUE TITLE
Timer widget

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/AFFiNE#4625]
### Description

A timer widget that counts down that is seeable by team members on edgeless mode. Restricting the editing capabilities for a selected area on that time limit would be also nice but not that important

### Use case

Agile teams use a timer one way or another (especially in a retrospective)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you very much for your feedback. There are currently no relevant plans. However, we will consider this requirement in future iterations and continue to pay attention to other similar feedback. And we will temporarily close this issue. If there are any further questions or changes, please feel free to reopen it.

**Comment by kemalakcc** [comment]
No worries! Sorry, should I stop submitting those? 😄 I don't want to spam here. Do you want me to send any other feature request privately to a mail or something? I really liked the product and want to share insight that "hopefully" will attract many new users who are using whiteboard-style collaboration tools. Sorry again if I'm sending too much. I'll continue based on your response or stop 😄

**Comment by houjoe0829** [comment]
Thank you for your understanding. Currently, we mainly follow up on ongoing or upcoming issues in GitHub. If you have any feedback, you can start a discussion in GitHub Discussion or submit it to the [AFFiNE Community](https://community.affine.pro/c/feature-requests/). However, please note that these are not spam. They are all processes that require us to respond individually, and your feedback will contribute to the popularity of these product requests.
