### ISSUE TITLE
Text color on dark theme

### ISSUE THREAD

**Issue by kmlkcl** [toeverything/AFFiNE#4628]
### What happened?

- Create a rectangular (empty inside) shape on dark theme
- Write something (which will be white and its okay)
- Change the fill color of the rectangle to any. 
- Text becomes black
- Now, if you don't ctrl + z, there's no way to fix the font color inside the rectangle

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
please take a look @hwangdev97

**Comment by kemalakcc** [comment]
Almost same problem in a different way:

- Create a yellow rectangular shape. Filled this time, not empty inside.
- Write something. It will be white and hard to see. 
- Select the color of rectangular shape to yellow again. This time it'll update the font color and will be okay.

**Comment by hwangdev97** [comment]
I think this does not meet the design expectations. The color of the internal text should be adjustable. 
We will deal with this issue after discussing specific options cc @Svaney-ssman
