### ISSUE TITLE
Grouping Shapes, texts etc on Edgeless Mode​

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/AFFiNE#4629]
### Description

A very common and essential part of white boards is to group a few items together. This way when you select one of them, you select the group as a whole and move them in to another place (or copy all etc) 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Thank you, we are working on that, you could check progress here. https://github.com/toeverything/blocksuite/issues/4999
