### ISSUE TITLE
​Can't add text on some areas (Edgeless Mode)

### ISSUE THREAD

**Issue by kmlkcl** [toeverything/AFFiNE#4659]
### What happened?

Here is a gif: https://jmp.sh/4ZFngDr1

You can deduce it from the yellow mark that I'm clicking but unable to write new text in some areas. It feels like some hidden thing is overlapping. I first thought it was something happening when you're close to the toolbar but it also happens in many different areas.

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
We are temporarily unable to reproduce this issue on Windows devices. Can you:
1. Provide the version you are currently using
2. Try downloading the latest Canary version to see if the problem still occurs. https://affine.pro/download
