### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by DemoRoyalD** [toeverything/AFFiNE#4674]
### Description

mac m2 desktop version, import a large markdown, and then view the thumbnail in the top right corner, at the same time, the memory consumption is 1 gigabit, and the corresponding is very slow, can be optimized

### Use case

lastest mac desktop version

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
It's been a while, please try the new version
