### ISSUE TITLE
All cloud workspace turned to local while first signin

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4694]
When logging in for the first time, all cloud workspaces became local, and when enabling to cloud, I was the only collaborator left. But after repeated refreshes and upgrades, the cloud workspace will become double, one is the original good one, and the other one is enabled later.

![Image](https://github.com/toeverything/AFFiNE/assets/142964904/fdd57636-ded9-4a32-80ea-836ade4ea674)

**Comment by houjoe0829** [comment]
To prevent any misunderstandings, let’s note the observed symptoms of this issue. After logging into the account, the Cloud Workspaces for that account are displayed as Local Workspaces. However, when manually re-enabling AFFiNE Cloud for these Local Workspaces, the Cloud Workspaces are duplicated. However, Zoey’s side is currently unable to reproduce this issue.

**Comment by zkreutzjanz** [comment]
@EYHN Was this resolved? facing this issue now.
