### ISSUE TITLE
Kanban view cannot edit card directly; Table view cannot add page link

### ISSUE THREAD

**Issue by jianghoy** [toeverything/AFFiNE#4696]
### What happened?

Hi, I found two bugs:
1. In Kanban view, I cannot directly edit the card; I have to open it, click the pencil icon, and edit it in the right bar.
2. In Table view, I can no longer add page links.
What I would expect to happen:
1. In Kanban view, I should be able to edit the card directly.
2. In table view, I can add page link.

I'm using the 0.8.4 version on an Apple silicon MacBook pro.
You can see the screen recording.
https://www.loom.com/share/bc63eb0cb4464f5f999907068dea9643?sid=628d9e0c-1db9-476d-8c90-316eee22da05

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by dxkrs** [comment]
Maybe I have similar doubts.
I try to expand a new card in kanban view, and I accidentally clicked the 'click to create a linked doc in center peek'. After that, the card seem to be a page, I don't want to do this and I try to go back but I can't. The card will be 404 if I hard delete the page.
Later, I saw this issue and found that something could be edited in the table view. Bingo, edit the card 'Title' in table view can do my "go back" operation!
So why the kanban view can't do this "go back"？
