### ISSUE TITLE
Kanban view's date cell is off​

### ISSUE THREAD

**Issue by jianghoy** [toeverything/AFFiNE#4697]
### What happened?

Bug:
1. when I add a date in Kanban view, the date is off by one when I exit, also the date format changes from MMDDYYYY to YYYYMMDD
What I expect:
1. Stick with 1 date format
2. Do not change my date input (if you need to deal with the timezone, let the user choose one or just use the local device timezone).

I'm using ver. 0.8.4. at an Apple Silicon Macbook pro
Recording:
https://www.loom.com/share/7efdec1e48824ab59e1d4fac3276ca13?sid=d39a44d5-d1af-422c-8486-c002657b0762

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by sachin-duhan** [comment]
/ attempt
