### ISSUE TITLE
Replace Twitter icon to X icon

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#4721]
[X icon here](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?type=design&node-id=120-3603&mode=design&t=DzU91iQkVETxfPit-4)

![Image](https://github.com/toeverything/blocksuite/assets/110808979/f32a3a04-2da6-4ff7-a73b-c62d4ed8b927)

**Comment by yash001dev** [comment]
I will work on this issue.
Certainly, I'll handle this matter. 
Could you please grant me design access? 
This way, I can easily download the X icon.
/assign

**Comment by yash001dev** [comment]
the issue has already been addressed
here is a reference image: 👇
![Screenshot 2023-11-01 at 12 34 55 AM](https://github.com/toeverything/AFFiNE/assets/38398261/dfe40cf8-504c-4391-bf22-01c76a23c402)

If you verified then please close above issue.

**Comment by EYHN** [comment]
Has been replaced in the latest canary.
