### ISSUE TITLE
[bug] Edgeless Mode drawings lost when adding a new group in Paper Mode

### ISSUE THREAD

**Issue by Avey777** [toeverything/AFFiNE#473]
### Describe the bug

Edit data in edgeless mode first, then edit data in paper mode; return to edgeless mode, the data previously edited in edgeless mode will be lost

### To Reproduce

1.、Edit data in edgeless mode first, 
2、then edit data in paper mode; 
3、return to edgeless mode, the data previously edited in edgeless mode will be lost

**Comment by CJSS** [comment]
Thanks for the report.

Is this occurring in the live demo or your own Docker deployment?

If in Docker please let me know which version/tag of the AFFiNE Docker releases you are using for deployment.

Also to further add information, please could you share the OS and browser.

**Comment by Avey777** [comment]
docker.    affine-server
debian11

chrome 
edge

**Comment by darkskygit** [comment]
`docker inspect --format='{{.Id}} {{.Name}} {{.Image}} {{.Args}}' $(docker ps -aq)`
please run the above script and paste the result to help us confirm the specific container version

**Comment by Avey777** [comment]
> `docker inspect --format='{{.Id}} {{.Name}} {{.Image}} {{.Args}}' $(docker ps -aq)` please run the above script and paste the result to help us confirm the specific container version

![image](https://user-images.githubusercontent.com/35259040/193166463-b8cbc9dc-c4e9-444c-af88-7d6f2afae27d.png)

**Comment by CJSS** [comment]
I couldn't find the matching sha256 image, I would suggest you try pulling the latest image.

You can try pulling the latest image and deploying it using the following guide from the docs: [https://docs.affine.pro/affine/getting-started/install-affine-with-docker](https://docs.affine.pro/affine/getting-started/install-affine-with-docker)

**Comment by Avey777** [comment]
The latest image has been pulled, but this problem still exists

**Comment by Avey777** [comment]
> I couldn't find the matching sha256 image, I would suggest you try pulling the latest image.
> 
> You can try pulling the latest image and deploying it using the following guide from the docs: https://docs.affine.pro/affine/getting-started/install-affine-with-docker

Recently, the Docker image has always had this problem of data loss

**Comment by Avey777** [comment]
https://livedemo.affine.pro/

I tried the online trial version and also have this problem

**Comment by Avey777** [comment]
> I couldn't find the matching sha256 image, I would suggest you try pulling the latest image.
> 
> You can try pulling the latest image and deploying it using the following guide from the docs: https://docs.affine.pro/affine/getting-started/install-affine-with-docker

You can try to edit the content in edgeless mode when there is no content in pager mode, then edit the content in pager mode, and then switch back to edeless mode to view; The data edited in edgeless before is lost

**Comment by CJSS** [comment]
If it's not too much trouble, would you be able to provide a video/gif of this issue. As I've tried and am not able to recreate this issue.

Thanks.

**Comment by darkskygit** [comment]
I can't reproduce the problem either, here's a record of my actions
https://user-images.githubusercontent.com/25152247/193188257-c660d670-114a-4ede-bb86-75484130eab2.mp4

**Comment by Avey777** [comment]
> I can't reproduce the problem either, here's a record of my actions
> 
>  record.mov


https://user-images.githubusercontent.com/35259040/193242124-c7dd3dfa-5b5d-4101-98f4-37121ff776bb.mp4

**Comment by Avey777** [comment]
I just found the rule. Don't fill in any content in the title of the page.

**Comment by CJSS** [comment]
OK thanks for this. It seems that adding a new group will clear the Edgeless Mode drawings and objects.

Easily reproduced with the following:

- Draw in Edgeless Mode
- Add a new group in Paper Mode

**Comment by darkskygit** [comment]
we have refactor our editor kernel, and there is no problem at present, so close this issue.
