### ISSUE TITLE
​icon update for Trash

### ISSUE THREAD

**Issue by zanwei** [toeverything/AFFiNE#4731]
### Description

We would like to have an update for Trash icon. Please check [design ](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?type=design&node-id=750-10979&mode=design&t=Xe01N24Olz6Rm0rG-4)

Before:
<img width="213" alt="image" src="https://github.com/toeverything/AFFiNE/assets/40333372/97c88dcd-80c0-46f2-ba82-604121e92476">

Should:
<img width="314" alt="image" src="https://github.com/toeverything/AFFiNE/assets/40333372/710f717f-0df6-4334-bb3b-f9a1f96c8eb3">

### Use case

All places with deletion functions need to be replaced

1. Sidebar
<img width="224" alt="image" src="https://github.com/toeverything/AFFiNE/assets/40333372/6ee42af4-dd7b-44e7-a637-8642c32523bd">

2. Page/Edgeless actions
<img width="199" alt="image" src="https://github.com/toeverything/AFFiNE/assets/40333372/2d03d33e-2dd6-4c87-95b7-a63503874d99">

3. All pages list
<img width="200" alt="image" src="https://github.com/toeverything/AFFiNE/assets/40333372/cf6238cf-2198-4d20-9a91-28856ee442c7">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
fixed in https://github.com/toeverything/AFFiNE/pull/4530
