### ISSUE TITLE
​Don't unfold automatically when using todo list

### ISSUE THREAD

**Issue by nickyi1990** [toeverything/AFFiNE#4750]
### Description

when I fold my todo lists like below.
![image](https://github.com/toeverything/AFFiNE/assets/13381684/a9354317-d79e-4c6d-92b0-00b23a05febf)

everything I exit this page and enter it again, my todo lists will unfold automatically like below
![image](https://github.com/toeverything/AFFiNE/assets/13381684/abc9ee30-95f9-4310-82d1-86faa0c95e88)

It should better do not do this, and remember what user had done before, I really want a component like "Toggle list in Notion", this will much better for my workflow and for this software.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lawvs** [comment]
I believe this issue has been fixed in https://github.com/toeverything/blocksuite/pull/4865. We will release a new version soon.

**Comment by nickyi1990** [comment]
> I believe this issue has been fixed in [toeverything/blocksuite#4865](https://github.com/toeverything/blocksuite/pull/4865). We will release a new version soon.

by the way, would u make heading also foldable?
