### ISSUE TITLE
​Complete existing incomplete search mechanisms, such as text content search

### ISSUE THREAD

**Issue by fdjsxjn** [toeverything/AFFiNE#4792]
### Description

I hope to increase the search for characters in the file
The character search function in the article is really practical and can greatly increase search efficiency for users

Option 1: Combining ctrl+f (quickly locate the location of search content) with ctrl+k (quickly locate the approximate article of search content)
Option 2: After CTRL+K search, automatically jump to the specified location when clicking on the results

I think Option 2 is easier to implement because the existing mechanism can already search for specific content lines within the article. Simply center the display to achieve this

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Duplicated with https://github.com/toeverything/AFFiNE/issues/4591
