### ISSUE TITLE
[improvement]: include repository in hacktoberfest

### ISSUE THREAD

**Issue by CarlosZoft** [toeverything/AFFiNE#480]
### 1~3 main use cases of the proposed improvement

The hacktoberfest event is an event that encourages open-source contribution in the month of October. It would be nice to participate too, it would attract new contributors!

### Ideas for solution

For that you have to add a new label with the name "hacktoberfest" in the PR's

### what types of users can benefit from using your proposed improvement

Open-source community 

Link of event : https://hacktoberfest.com/

**Comment by CJSS** [comment]
We'll definitely consider this for next time around, thanks for the suggestion. As for this year we didn't get our refactor release out in time to participate.
