### ISSUE TITLE
Payment UI Issues

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#4800]
- [ ] Wrong pricing plan card background > backgroundPrimaryColor
<img width="524" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/d7c111b0-781e-4625-a5c3-1810dc5b37c7">

- [ ] wrong toast while changing monthly plan to yearly plan [CHECK DESIGN](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%F0%9F%96%8C%EF%B8%8F-2023.Late?type=design&node-id=11552-120418&mode=design&t=vGaBVSk3CioDk3mJ-4)
![image](https://github.com/toeverything/AFFiNE/assets/110808979/c666d80d-feb2-4cec-b2b7-3a2f65e46065)

- [ ] wrong toast while canceling plan [CHECK DESIGN](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%F0%9F%96%8C%EF%B8%8F-2023.Late?type=design&node-id=13006-238917&mode=design&t=vGaBVSk3CioDk3mJ-4)
![image](https://github.com/toeverything/AFFiNE/assets/110808979/b838945d-2c83-4894-a247-71e733d6fb8e)

- [ ] Flex height of description area [CHECK DESIGN](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%F0%9F%96%8C%EF%B8%8F-2023.Late?type=design&node-id=12729-69840&mode=design&t=vGaBVSk3CioDk3mJ-4)
<img width="415" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/dee8a9f2-89de-4fbb-a4ff-ee39c3e6e598">

- [ ] Alignment of icon and description at button [CHECK DESIGN](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%93%8C-AFFiNE-2023?type=design&node-id=11222-177831&mode=design&t=TuLDrMFjMXHtkrCC-4)
<img width="394" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/db8f5d89-63f3-4a1a-8b80-4176ce06bc15">

- [ ] Scroll bar: invisible scroll bar when mouse is not moving after 5s
<img width="713" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/87cba0e0-162d-4c8e-9ece-b3e3bf3ff469">

- [ ] Account settings missing active status
<img width="321" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/6dfc2a71-3a96-4aa5-b955-ed6d5595d60b">

**Comment by joooye34** [comment]
The version is stable. If some issues haven't been fixed, create individual issue to fix.
