### ISSUE TITLE
Show data risk information in the web version.

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#4806]
### What happened?

![shot-2023-11-01-15 25 01@2x](https://github.com/toeverything/AFFiNE/assets/24713927/0c061037-96bf-45f8-a696-aca44c320da0)

The main three functionalities are:

	•	Displaying banners. 
	
![shot-2023-11-01-15 27 35@2x](https://github.com/toeverything/AFFiNE/assets/24713927/99e46dac-46cd-459b-8ce2-9cbb59c7ceeb)

	
	•	Providing workspace status prompts
	
	
![shot-2023-11-01-15 27 45@2x](https://github.com/toeverything/AFFiNE/assets/24713927/161808bd-c672-4fcc-9115-e5f784ed0131)

	•	Showing a download button in the sidebar, which will display a close icon when hovered over.
	
	
![shot-2023-11-01-15 27 57@2x](https://github.com/toeverything/AFFiNE/assets/24713927/c6063b0c-f489-4344-8490-8e71e3790bd2)

[the design file](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%F0%9F%96%8C%EF%B8%8F-2023.Late?type=design&node-id=12505%3A64716&mode=design&t=f9JOSDWvsRbNnVFm-1)

**Comment by lawvs** [comment]
Duplicated of #4805
