### ISSUE TITLE
[bug]: Importing workspace doesn't spawn file explorer window

### ISSUE THREAD

**Issue by DMNinja** [toeverything/AFFiNE#481]
### Describe the bug

To expand upon the title, although the export button functions as intended, and i can freely export a workspace, the import button doesn't seem to behave as expected

### To Reproduce

1: Open up Docker Desktop for Windows (v 4.12.)
2: Open up the latest Affine Container (Image ID: 0a0ddba15863683598d8138c8aeed6ddebe8c50df976e79234144a565b03621c)
3: Press the Import Button
4: Click on the browser prompt
(I have included a video as a zip file for reference)

### Screenshots

Video Is provided instead of screenshots
[2022-10-06 14-14-01.zip](https://github.com/toeverything/AFFiNE/files/9724254/2022-10-06.14-14-01.zip)

### Expected behavior

A file browser menu is expected when clicking the import button.

### Platform

Windows 10

### Browser

Brave Browser

**Comment by CJSS** [comment]
This is likely due to the browser, as I notice you are using Brave Browser. Officially we only currently support Chrome.

For further information, the following error is reported in the console: `window.showOpenFilePicker is not a function`

**Comment by alt1o** [comment]
some relative information: https://github.com/brave/brave-browser/issues/18979
or follow this steps below:
1. open a blank tab, and enter in location bar: brave://flags
2. find the "File System Access API", and change the value to "enabled"

![image](https://user-images.githubusercontent.com/21084335/194987186-89950f77-be35-401c-aeb1-4bf22e457f7b.png)
