### ISSUE TITLE
Full text search only works on loaded pages

### ISSUE THREAD

**Issue by EYHN** [toeverything/AFFiNE#4825]
Currently, the page list will load all pages, so this problem is not obvious.

It can be reproduced by open a page content and reload the app.

Before load:
![image](https://github.com/toeverything/AFFiNE/assets/13579374/e9dfb284-851b-4dda-88aa-aa061852bf3e)

After load:
![image](https://github.com/toeverything/AFFiNE/assets/13579374/ce9249fb-f5cd-4f3c-9de0-103f0f3135cf)

**Comment by pengx17** [comment]
Oops, this is indeed an issue that has not been anticipated.

**Comment by pengx17** [comment]
caused by https://github.com/toeverything/AFFiNE/pull/4775

**Comment by pengx17** [comment]
should have been fixed (workaround) in https://github.com/toeverything/AFFiNE/pull/4834
but we may need a better solution for that
