### ISSUE TITLE
Unable to open page in local workspace

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/AFFiNE#4828]
https://github.com/toeverything/blocksuite/assets/144991896/2d5eb253-8b68-4c77-b955-fcd689287120

**Comment by EYHN** [comment]
Maybe need more information?

Do you have steps to reproduce, or logs?

**Comment by fdjsxjn** [comment]
I prove that this problem does exist


Reproduction plan
1. Download an AFFINE 10.0 version( like 9 ) smaller than  and export it to the local workspace
2. Import this workspace into version 10.0 of AFFINE and you will see a blank page


However, the exported content of version 10 can only be imported from version 10

This seems to be a serious problem

**Comment by EYHN** [comment]
Hi @fdjsxjn, thank you for reporting this issue, I was able to reproduce the behavior you described, it seems that the migrations were not working correctly during the import, the exact reason is under investigation.

**Comment by pengx17** [comment]
https://github.com/toeverything/AFFiNE/pull/4912 may fix this issue
