### ISSUE TITLE
[improvement]: Edgeless mode, scale increase button can not be click

### ISSUE THREAD

**Issue by wylovely** [toeverything/AFFiNE#483]
### 1~3 main use cases of the proposed improvement

![image](https://user-images.githubusercontent.com/50231506/194734319-354d69f8-f176-457d-a945-0442f687c696.png)

**Comment by tzhangchi** [comment]
Thank you for your feedback, we will fix it

**Comment by alt1o** [comment]
We removed livechat button in livedemo and added livechat in https://affine.pro . If you have free time, we highly recommend you to try https://pathfinder.affine.pro . It is more stable and smooth.
