### ISSUE TITLE
Toast update

### ISSUE THREAD

**Issue by zanwei** [toeverything/AFFiNE#4835]
### Description

We would like have an update for [Toast](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?type=design&node-id=292-2502&mode=design&t=CDp6t157OPMoOQaM-4).

**Logic:** When Toast needs to pop up many times in a short period of time, we recommend that the latest toast will always show the latest toast

**Animation parameters:**  `0.25, 0.1, 0.25, 1` `300ms` , Disappear after 3 seconds

please refer the video

https://github.com/toeverything/AFFiNE/assets/40333372/f45f1406-8efc-4752-a3ca-552d3618c1d9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by om2137** [comment]
@zanwei @JimmFly  can I raise PR for this?

**Comment by JimmFly** [comment]
> @zanwei @JimmFly can I raise PR for this?

Sure, I would appreciate your help! You can proceed and work on this issue. Thank you for your contribution! Feel free to reach out to our designer @zanwei  at any time if you have any queries.

**Comment by zanwei** [comment]
Hi @om2137 , just wanted to check with you, are you still planning to raise a PR for this issue? If you don't have time, we will handle it internally :D

**Comment by om2137** [comment]
@zanwei sorry for the delay, I will do it today.

**Comment by om2137** [comment]
Apologies for the delay, there was issue with my internet.
Done the necessary changes @zanwei @JimmFly, can anyone review

**Comment by om2137** [comment]
I am having a bit of time crunch, if anyone want to take this issue

**Comment by JimmFly** [comment]
> I am having a bit of time crunch, if anyone want to take this issue

I will take over this issue.
