### ISSUE TITLE
Kanban View Update with new filter (progress bar)​

### ISSUE THREAD

**Issue by kmlkcl** [toeverything/AFFiNE#4838]
### What happened?

I have a Kanban view with some progress bars. Some of them are at 100 percent. When I add a progress bar filter that must hide things with 100 "after", I still can see the items which must be hidden. When I click any progress bar with 100 values, they start to become hidden. So, to summarize, I guess filter doesn't check progress bar values before any progress bar value change. 

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by umar23faiz** [comment]
Hi @kmlkcl , I am willing to work on this one . Can you please share screenshots or steps to reproduce this issue ?
