### ISSUE TITLE
Loading data from the server is too slow.

### ISSUE THREAD

**Issue by Avey777** [toeverything/AFFiNE#484]
### 1~3 main use cases of the proposed feature

Loading data from the server is too slow. I hope you can load the directory level by level first; When necessary, load the contents of the directory.

The server configuration may be too low. I hope you can give the server the minimum configuration parameters

**Comment by CJSS** [comment]
Please may I ask for some more information.

Are you trying to browse the server file directory? What's your use case here? Are you trying to import files from a remote location?

Maybe a screenshot may help of where you are facing these issues.

**Comment by Avey777** [comment]
> Please may I ask for some more information.
> 
> Are you trying to browse the server file directory? What's your use case here? Are you trying to import files from a remote location?
> 
> Maybe a screenshot may help of where you are facing these issues.
![image](https://user-images.githubusercontent.com/35259040/194827084-a97a3809-da06-4388-b033-3af024f9722b.png)

The affine server I use stores the data in the server, but every time I refresh the page or open my data from another computer, I have to wait about 3 to 10 minutes for the data to load normally

**Comment by CJSS** [comment]
Is the file particularly large? I'm inclined to believe this might be down to your server configuration and/or hardware.

May I suggest you try the following:
1) Export your workspace to your local device
2) Head over to our demo [livedemo.affine.pro](livedemo.affine.pro)
3) Import your file into the demo

Please do let me know if you run into the same issues following the above steps.

**Comment by Avey777** [comment]
> Is the file particularly large? I'm inclined to believe this might be down to your server configuration and/or hardware.
> 
> May I suggest you try the following:
> 
> 1. Export your workspace to your local device
> 2. Head over to our demo [livedemo.affine.pro](https://livedemo.affine.pro)
> 3. Import your file into the demo
> 
> Please do let me know if you run into the same issues following the above steps.


Can you provide an email address? I will send you the document
I don't think a file of about 2M size needs me to wait for a long time

**Comment by CJSS** [comment]
You can contact our email: contact@toeverything.info
Please do not share any sensitive or important data.

**Comment by Avey777** [comment]
> You can contact: [contact@toeverything.info](mailto:contact@toeverything.info) Please do not share any sensitive or important data.

Emali has been send，thank you！

**Comment by CJSS** [comment]
Received.

I personally test this using the live demo deployment, considering the >2MB file size, it took around 8 secs to load.

We can look to optimize the importing process, though there are several factors out of our control such as hardware and internet speed.

From the user side, I think the addition of some kind of progress bar to show the importing status would give better feedback and improve the experience. 

What's your opinion?

**Comment by Avey777** [comment]
> 收到。
> 
> 我个人使用实时演示部署对此进行了测试，考虑到>2MB文件大小，加载大约需要8秒。
> 
> 我们可以考虑优化导入过程，尽管有几个因素不受我们的控制，例如硬件和互联网速度。
> 
> 从用户的角度来看，我认为添加某种进度条来显示导入状态将提供更好的反馈并改善体验。
> 
> 你怎么看？
I suggest that when loading from the affine server, the document level can be loaded first, and the document content can be loaded on demand. In this way, the loading time will not be too long

**Comment by Avey777** [comment]
> Received.
> 
> I personally tested this using the live demo deployment, considering the >2MB file size, it took around 8 secs to load.
> 
> We can look to optimize the importing process, though there are several factors out of our control such as hardware and internet speed.
> 
> From the user side, I think the addition of some kind of progress bar to show the importing status would give better feedback and improve the experience.
> 
> What's your opinion?

I suggest that when loading from the affine server, the document level can be loaded first, and the document content can be loaded on demand. In this way, the loading time will not be too long
