### ISSUE TITLE
Add basic ​responsive design

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#4843]
### Description

![9e2456b5bb1d264e8509a5668c6f0a81](https://github.com/toeverything/AFFiNE/assets/24713927/c7cccfa3-6054-4dc4-a2ed-be0dba1bb79f)

In mobile device sizes, the sidebar collapses by default

![4895b662a18fea7cd1f9745f7204027e](https://github.com/toeverything/AFFiNE/assets/24713927/9300ec56-a27a-44ac-a276-1c39fd35489c)

![shot-2023-11-06-15 26 18@2x](https://github.com/toeverything/AFFiNE/assets/24713927/017e310f-8973-469b-9898-1b2b5765eba6)
👆 These pages should be mobile-friendly cc @Svaney-ssman 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Svaney-ssman** [comment]
Design added in [Figma AFFiNE 2023](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%93%8C-AFFiNE-2023?type=design&node-id=16841-110927&mode=design&t=2X66wbuRyGz67eAB-4)
<img width="1206" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/379c997c-f198-4783-b1e8-9a08e85c88f9">
