### ISSUE TITLE
Table View Ordering Rows with Drag & Drop [Edgeless Mode]​

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/AFFiNE#4853]
### What happened?

It works correctly and very smoothly on paper mode, but if you're in edgeless, everything goes crazy.

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
Hi kemal 👋

I tried the table view in edgeless mode on my computer and couldn't reproduce the situation you described.

Could you please provide a screen recording demonstrating the situation you mentioned?

**Comment by kemalakcc** [comment]
Hi! I tried but I couldn't 😄

**Comment by EYHN** [comment]
I think I can close this issue first. If you can reproduce it, feel free to reopen.
