### ISSUE TITLE
Password reset not working​

### ISSUE THREAD

**Issue by dingemann** [toeverything/AFFiNE#4872]
### What happened?

When I'm logged in via magic-email-link and want to set a password in the settings, the set password doesn't work to log in.
Response: "Invalid password" 

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
Hi dingemann.

Thank you for reporting this issue. I confirm this issue exists.

**Comment by EYHN** [comment]
duplicate https://github.com/toeverything/AFFiNE/issues/4881
