### ISSUE TITLE
German letter ß switches modes​

### ISSUE THREAD

**Issue by dingemann** [toeverything/AFFiNE#4874]
### What happened?

When I try to type the german letter ß in the native app it switches between page- and edgeless-mode.
Using Version 0.9.0-beta.3 on MacOS Sonoma 14.0 (23A344)

This is NO issue in the web-version.

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
Hi Dingemann,

This is a duplicate issue https://github.com/toeverything/AFFiNE/issues/4793, it has been fixed and will be released in the next version.
