### ISSUE TITLE
Old page content can not be load​ed

### ISSUE THREAD

**Issue by lawvs** [toeverything/AFFiNE#4875]
### What happened?

All old pages fail to load even after waiting more than 10 seconds

https://github.com/toeverything/AFFiNE/assets/18554747/1967a29b-24cf-45b5-ae1b-9b7e71a332e9

### Distribution version

macOS x64 (Intel)

### Anything else?

App Version
0.10.0-canary.14
Editor Version
0.0.0-20231108041746-2e7e3467-nightly

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
This might caused by the problematic schema migration of old docs.
We are continuing investigating.

**Comment by lawvs** [comment]
In the latest version, errors are logged in the console.

```
page xxxxxx-6191-4458-bee8-xxxxx upgrade failed Error: Migration failed. Please report to https://github.com/toeverything/blocksuite/issues
          frame element --> frame block (page v1 --> v2)
            Error: val does not exist
  at new eE (error.js:10:9)
  at new eP (error.js:18:9)
  at schema.js:69:27
  at Array.forEach (<anonymous>)
  at eB.upgradePage (schema.js:62:28)
  at blocksuite.js:510:14
  at yjs.cjs:6032:9
  at Map.forEach (<anonymous>)
  at nN.forEach (yjs.cjs:6030:15)
  at f (blocksuite.js:508:10)
```

<img width="761" alt="Screenshot 2023-11-10 at 18 47 09" src="https://github.com/toeverything/AFFiNE/assets/18554747/df19692b-1503-43a0-bec6-ba92931d7b19">


<img width="586" alt="Screenshot 2023-11-10 at 18 50 56" src="https://github.com/toeverything/AFFiNE/assets/18554747/3316c474-d9b7-4fbb-a7c0-44c9207a93fa">

<img width="708" alt="Screenshot 2023-11-10 at 18 49 57" src="https://github.com/toeverything/AFFiNE/assets/18554747/1c64917b-6bdb-4c41-a3de-ce538f495fb4">

**Comment by lawvs** [comment]
In the version `0.10.2`, all data was recovered.
