### ISSUE TITLE
The content of the email sent for new account registration is incorrect

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4890]
### Current:
When entering an email address that has not been previously registered and clicking the Continue button, AFFiNE sends the user an email for logging in.
![CleanShot 2023-11-09 at 17 52 53@2x](https://github.com/toeverything/AFFiNE/assets/22443345/fb191b4d-36e6-498f-b1f0-01bb098a748f)

### Expected：
The emails for registration and login look similar, but the text is differentiated to inform users whether they are registering or logging in.
**Subject of email：** Your AFFiNE account is waiting for you!
**Title of email content：** Create AFFiNE Account
**Description of email content：** Click the button below to complete your account creation and sign in. This magic link will expire in 30 minutes.
**Button：** Create account and sign in

**Comment by rakheesingh** [comment]
@houjoe0829 I am not able to reproduce this issue .
