### ISSUE TITLE
When importing markdown files, the page title always displays untitled

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#4906]
https://github.com/toeverything/AFFiNE/assets/142964904/65ee9101-5307-4ad0-a91c-de143f734105

**Comment by EYHN** [comment]
I confirm that this issue has been fixed in https://github.com/toeverything/blocksuite/pull/5297 , Markdown titles can be displayed in the affine 0.10.2

**Comment by 9j** [comment]
@EYHN The issue appears to be occurring again in v0.13.1.

https://github.com/toeverything/AFFiNE/assets/11691670/ba46558f-b8f8-4353-8483-63eb9f7c8f5c
