### ISSUE TITLE
Revive and update the Self-Hosted Docker Image + tutorial

### ISSUE THREAD

**Issue by omarcostahamido** [toeverything/AFFiNE#4914]
### Description

This is a long awaited feature.
Previously the issue was raised on the [OctoBase](https://github.com/toeverything/OctoBase/) repo [[457](https://github.com/toeverything/OctoBase/issues/457)] but, according to @darkskygit it should be moved here.
I am taking the liberty to create the issue here because I am really interested in trying this out on my synology NAS. I also noticed that the new website doesn't mention self host mode anymore so... i just really want for this to not be discarded.
Thank you for your work 🙏 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by romainds-tech** [comment]
I am also very interested with this feature, I'm able to participate if needed

**Comment by EYHN** [comment]
Hi there, @omarcostahamido.
Thank you for your question! We are currently in the process of  developing self-hosted deployment options. The details in this regard are still under consideration and planning. Once we have a comprehensive plan in place, we will release it to our users.
Appreciate your patience and stay tuned for updates!

**Comment by omarcostahamido** [comment]
Dear @EYHN 
Thank you for sharing the status on this with us!
We are looking forward.

**Comment by bolavefasfas** [comment]
> Hi there, @omarcostahamido. Thank you for your question! We are currently in the process of developing self-hosted deployment options. The details in this regard are still under consideration and planning. Once we have a comprehensive plan in place, we will release it to our users. Appreciate your patience and stay tuned for updates!

Whats the Eta. we can expect ?

As the cuppon for early access isnt working from last 4-5 days even on blog post no update or on email please enable the cuppon 

Thanks

**Comment by EYHN** [comment]
Hi @bolavefasfas 

The self-host version is already in our plan scope. I believe it won’t be long before it becomes available, and some work has already begun. (related: https://github.com/toeverything/AFFiNE/issues/5003)

For second question. The cuppon for early access should already be available, You can report the situation on https://community.affine.pro/home and attach your registration email, and staff will solve your problem.

**Comment by bolavefasfas** [comment]
> Hi @bolavefasfas
> 
> The self-host version is already in our plan scope. I believe it won’t be long before it becomes available, and some work has already begun. (related: #5003)
> 
> For second question. The cuppon for early access should already be available, You can report the situation on https://community.affine.pro/home and attach your registration email, and staff will solve your problem.

I did they said promo ended i tried it on 6 th day as my laptop was gone for repair for 1 week sad

**Comment by Yipei-Operation** [comment]
> > Hi there, @omarcostahamido. Thank you for your question! We are currently in the process of developing self-hosted deployment options. The details in this regard are still under consideration and planning. Once we have a comprehensive plan in place, we will release it to our users. Appreciate your patience and stay tuned for updates!
> 
> Whats the Eta. we can expect ?
> 
> As the cuppon for early access isnt working from last 4-5 days even on blog post no update or on email please enable the cuppon
> 
> Thanks

Hi @bolavefasfas , if you have paid for our early access believer plan, you should have received the email we sent to all early bird users to upgrade from free to pro (guide link is here: https://community.affine.pro/c/community-support/special-offer-for-early-access-users-claim-your-free-pro-upgrade-now) if you have not paid for our early access believer plan, then currently we have closed this special discount, and you can go to our official website and pick up annual plan, which will give you 15% discount. Any questions please feel free to let me know.

**Comment by EYHN** [comment]
Tracked in https://github.com/toeverything/AFFiNE/issues/5069
