### ISSUE TITLE
Cloud workspace before September upgrade error

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/AFFiNE#4928]
https://github.com/toeverything/AFFiNE/assets/144991896/2d4a2e05-a00f-4615-ba7b-503697d770fc

![Image](https://github.com/toeverything/AFFiNE/assets/144991896/a7bf7d8e-4c77-44b3-a9b8-a3ccab9eaa46)

**Comment by EYHN** [comment]
should fixed by 0.10.2
