### ISSUE TITLE
Cannot add public link

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/AFFiNE#4931]
![Image](https://github.com/toeverything/AFFiNE/assets/144991896/dc5d2745-f582-4944-bba2-10e985de0ef6)

https://github.com/toeverything/AFFiNE/assets/144991896/f1008d11-c38b-4281-8c9c-e11c01280ed5

**Comment by EYHN** [comment]
fixed by https://github.com/toeverything/AFFiNE/pull/4968
