### ISSUE TITLE
After detecting the need to create an account, the displayed text is incorrect.

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#4949]
Currently, AFFiNE's registration and login processes are combined. That is, after entering the email, it determines whether it is a login or registration. If it has been determined as a registration, it should display as "Sign up," but currently, it is displaying as "Sign in."

Current：
![CleanShot 2023-11-15 at 15 55 53](https://github.com/toeverything/AFFiNE/assets/22443345/cfd80e66-0b7a-47c2-874a-80d14db2431d)

Expected
![CleanShot 2023-11-15 at 15 56 49@2x](https://github.com/toeverything/AFFiNE/assets/22443345/bda0ec90-8dd2-487a-9dd7-1570ee35d12a)

**Comment by Tensor453** [comment]
Can I work on It?

**Comment by deadland2002** [comment]
Can i work on It ?

**Comment by EYHN** [comment]
Hi @deadland2002, Thanks for your willingness to help, but I've confirmed that this issue has been fixed and I'll closing this issue.
