### ISSUE TITLE
[bug]: Markdown "Heading 1 " mode with short key won't end automatically

### ISSUE THREAD

**Issue by joeyleeeeeee97** [toeverything/AFFiNE#496]
### Describe the bug

Markdown short key  won't end automatically

### To Reproduce

in https://livedemo.affine.pro

Create a new group

Tab `#` `space` `1` enter "Heading 1" mode, type something.

Notice the content is unable to delete and the "Heading 1" is active for all content later..

**Comment by tzhangchi** [comment]
Thanks for your feedback, we are improving this situation in the new alpha version
