### ISSUE TITLE
Old notes cannot open after update​

### ISSUE THREAD

**Issue by lsyxiaopang** [toeverything/AFFiNE#4964]
### What happened?

I updated the software to the newest version this morning and found my old notes cannot open while I still can create new notes and it works well.

When I tried to open my old notes, it would give me a blank page like this 
<img width="1697" alt="image" src="https://github.com/toeverything/AFFiNE/assets/28998097/653764cc-7467-42a5-ae0f-4af2ac9e9366">
Also, I tried to "export" the note into pdf. It told me it have been converted successfully while I could not find the file in the download folder

Also, I am not sure where to read the log, so I could not paste the log here

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lsyxiaopang** [comment]
It seems from other issues that the problem comes form the loss. of the page's data, do I have any way to recover the data or it would be lost permantly

**Comment by joooye34** [comment]
@lsyxiaopang So sorry for the late reply. Do you use the browser or desktop app?

**Comment by joooye34** [comment]
We upgraded the data schema in this version, and unexpected breaking may have happened. Could you give us the error log screenshot? It will help us to find out the issue and recover the data. The data wasn't lost, it was corrupted.

**Comment by lsyxiaopang** [comment]
> We upgraded the data schema in this version, and unexpected breaking may have happened. Could you give us the error log screenshot? It will help us to find out the issue and recover the data. The data wasn't lost, it was corrupted.

I am using the desktop app, but I am not sure where to read the log, so it would be very nice of you if you can give me some tutorial

**Comment by YanxinLu0122** [comment]
Dear lsyxiaopang, I sincerely apologize for the inconvenience you've experienced.

To assist you further and address these issues, could you please export your workspace and send it to our email address at [contact@toeverything.info](mailto:contact@toeverything.info)? Our technical team is dedicated to resolving these issues, and having your workspace will greatly aid in the investigation and solution process.

Once again, I'm sorry for any disruption this has caused, and we appreciate your cooperation in helping us resolve this matter promptly.

**Comment by pengx17** [comment]
Sorry @lsyxiaopang, I have recovered the data you gave. It looks like there are some issues during migration. Will send it back to your email.

**Comment by pengx17** [comment]
We have fixed this issue offline

**Comment by JunjieShii** [comment]
我遇到了同样的问题，解决方案能不能公布下？ @pengx17

**Comment by EYHN** [comment]
@JunjieShii 你可以把你旧版本的workspace用affine桌面版导出，然后发送到 [contact@toeverything.info](mailto:contact@toeverything.info) 我们会尝试帮你恢复数据。
