### ISSUE TITLE
Cursor focus lost after adding a to-do item​

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/AFFiNE#4977]
### What happened?

Below, I'm trying to add a to-do item without using mouse. After adding an item, cursor focus is getting lost so I need to click with mouse to continue writing

![Peek 2023-11-17 14-27](https://github.com/toeverything/AFFiNE/assets/117591520/7844cffe-045d-43f0-8fba-18b53b0c137a)

### Distribution version

Web (insider.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SuyashOP-2** [comment]
It is working fine

**Comment by SuyashOP-2** [comment]
It is working fine 🙂

**Comment by kmlkcl** [comment]
what do you mean by that? Working fine?

**Comment by EYHN** [comment]
I've reproduced the issue but I haven't had time to investigate the cause yet, it would be great if anyone would help.

**Comment by deadland2002** [comment]
I can try

**Comment by EYHN** [comment]
@deadland2002 Give it a try and ask here if you have any questions.

**Comment by EYHN** [comment]
Looks like it's been fixed in 0.10.2
