### ISSUE TITLE
Can't login to cloud with Linux distribution​

### ISSUE THREAD

**Issue by kmlkcl** [toeverything/AFFiNE#4978]
### What happened?

When I click to Sign up/Sign in, it says I see "AFFINE Cloud is upgrading now" message. Maybe an older release is the latest on linux distribution?

### Distribution version

Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by heihei180** [comment]
windows 11  is also
