### ISSUE TITLE
Members with permissions do not see the "Edit" button in the top bar after opening the public link

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#5010]
The expected behavior is that members belonging to the current workspace, upon opening the public link, should see the "Edit" option in the top right corner. Clicking on it should lead them to the editing interface, whether it's Page sharing or Edgeless sharing.

**Comment by Dharmavineta** [comment]
Can you please add how to reproduce the issue so that I can work on it?

**Comment by houjoe0829** [comment]
I am currently unable to reproduce this issue. Let's temporarily close it for now.
