### ISSUE TITLE
[improvement]: UI style display is not correct

### ISSUE THREAD

**Issue by allenYetu211** [toeverything/AFFiNE#503]
### 1~3 main use cases of the proposed improvement

UI style display is not correct

### Ideas for solution

<img width="359" alt="WechatIMG7" src="https://user-images.githubusercontent.com/17957079/197976095-98fe27c3-24f7-4355-b52d-f2141857e993.png">

**Comment by tzhangchi** [comment]
Thanks for your feedback

**Comment by xell** [comment]
As we moved to a new AFFiNE web and app, there's no such a bug. Thanks anyway.
