### ISSUE TITLE
​能不能加一个笔记分享到百度和谷歌的功能，希望笔记可以被搜索引擎检索的到

### ISSUE THREAD

**Issue by 1557812300** [toeverything/AFFiNE#5036]
### Description

​能不能加一个笔记分享到百度和谷歌的功能，希望笔记可以被搜索引擎检索的到，比如我的笔记想有人关注，有更多人可以学习阅读。

### Use case

notion和flowUs

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by HeJiachen-PM** [comment]
可以的，这需要ssr的支持

末蓝 ***@***.***>于2023年11月23日 周四10:26写道：

**Comment by lawvs** [comment]
Also related to https://github.com/toeverything/AFFiNE/issues/1691

**Comment by EYHN** [comment]
This feature is not in our near-term plans, so I'll close this issue first
