### ISSUE TITLE
Notes and files sync to cloud 

### ISSUE THREAD

**Issue by bolavefasfas** [toeverything/AFFiNE#5039]
### Description

**Syncing Notes to Cloud Storage:**

Notes and files are synced to cloud storage services such as Google Drive, OneDrive, Dropbox, or Nextcloud in an encrypted format. The notes will be stored locally and continuously synced to the cloud, possibly using Rclone. Rclone is lovely for saving encrypted data to the cloud.

The process is as follows:

1. **Obsidian** saves notes into a local folder.
2. This **Local Folder** is synced to Google Drive using a cron job every minute.
3. The notes in **Google Drive** can be accessed on another device using the same cron script in reverse.

This process is a bit cumbersome, and it would be more efficient if a plugin could be developed to sync notes directly to a chosen cloud provider for backup purposes. Not only big cloud providers, but also self-hosted solutions like Nextcloud work. If we use Rclone, we don't need to worry about which cloud provider to use; just a text box to paste the Rclone config will do.

---

**Creating New Pages:**

When we create a new page, it should open the new page.

---

**Sending Notes from Webpages and Apps:**

- Ability to send notes from any webpage directly to a new page, which is implemented by [lazy.so](https://lazy.so).
- Ability to send notes from apps like Telegram and WhatsApp, which is implemented by Capacities. [Link to this feature implemented](https://docs.capacities.io/reference/integrations/telegram#:~:text=Telegram%20integration%20%E2%80%8B,resources%20from%20within%20the%20messenger.).

---

**Missing Features:**

- Web UI is missing.
- Need apps for iOS, Windows, and Linux.
- Please update the Docker image.

### Use case

All the people as most of the cloud proviers provide ample of free space like 15 gb to 10 gb for taking backup of their notes and files.

### Anything else?

update docker image please.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
Hi bolavefasfas, Thank you for so many suggestions

> **Syncing Notes to Cloud Storage**

Affine's current cloud storage solution base on cloud server.

Different from using file synchronization storage solutions such as Google Drive, we can implement more functions such as "multi-player collaboration", "permission management", and "share pages" on our server.

If you want cloud storage out of the box, just sign up your affine account, or purchase affine pro https://affine.pro/pricing

If you want self-hosted cloud storage, you can stay tuned for our upcoming self-hosted version/tutorial. (Related: https://github.com/toeverything/AFFiNE/issues/4914)

We currently have no plans to support synchronizing notes using the file sync software.

> **Creating New Pages**

The page does open when you create it. Can you provide a screen recording showing what you encountered?

> **Sending Notes from Webpages and Apps**

Great suggestion, we currently have a `daily note` feature on our development roadmap. We can improve the design of daily note based on your suggestions.

> **Web UI is missing**

Our web should work just like the desktop application, can you provide a screen recording?

> **Need apps for iOS, Windows, and Linux.**

Windows and Linux are already supported

https://github.com/toeverything/AFFiNE/releases/tag/v0.10.2

iOS and Android mobile versions are on our roadmap.

> **New Docker image**

We need to finish the self-hosted version first.

currently there is some features that is specific to the hosted version of affine, such as "payment", we need to make them optional to release self-hosted version.

**Comment by EYHN** [comment]
I think I have answered this issue. I will close it first. If you want to know the progress of a specific feature, please create a new issue.
