### ISSUE TITLE
​Stuck in synch

### ISSUE THREAD

**Issue by dingemann** [toeverything/AFFiNE#5040]
### What happened?

My Workspace unfortunately wasn't synched with my colleague. Which lead to some misunderstanding. Pressing the Sync-Button makes it spin endlessly. Restarting the native MacOS App and pressing sync solves the issue.

https://github.com/toeverything/AFFiNE/assets/714974/81bc8110-f662-4c38-8033-4f22ce4bb7d6

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
We have made many improvements to sync recently (after 0.10.2), which should solve many issues including this.

These improvements will be released in the near future (this week or next week), so please stay tuned.

I think we can keep this issue until the next version is released, and you can check whether this situation still occurs at that time.

**Comment by EYHN** [comment]
fixed in 0.10.2 released
