### ISSUE TITLE
cloud workspace disappeared after logging in

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/AFFiNE#5052]
![Image](https://github.com/toeverything/AFFiNE/assets/144991896/b40691ef-4da9-40a6-94be-c65ef26be3ed)

![Image](https://github.com/toeverything/AFFiNE/assets/144991896/7ee8780d-8959-42e6-984c-e0ae638e1cf3)

**Comment by EYHN** [comment]
This was confirmed to be a misunderstanding
