### ISSUE TITLE
Permission prompt is incorrect when sharing pages

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#5088]
Version: v0.10.3-beta.0

The prompt should directly tell the user that this is a sharing failure caused by "not the owner of the workspace/does not have permission". This issue cannot be solved by "try again later".

![Image](https://github.com/toeverything/AFFiNE/assets/142964904/1ebaee5f-5f6c-4556-843c-ffb6f18c5450)

**Comment by Yuhang1015** [comment]
Only when the hover moves to the error prompt, then will find a second permission denied message. But if the user didn't move the hover to the specific position, they may not see the second message and keep trying again.

![Image](https://github.com/toeverything/AFFiNE/assets/142964904/33a4327e-aee4-415f-b5be-d1708eb51e8d)

**Comment by EYHN** [comment]
Related #5096

**Comment by JimmFly** [comment]
The issue regarding only the owner being able to share has been resolved ( https://github.com/toeverything/AFFiNE/pull/4968), as for the pop-up problem, I believe it needs to be addressed in a separate issue.
