### ISSUE TITLE
Error message stacked and block other errors behind

### ISSUE THREAD

**Issue by EYHN** [toeverything/AFFiNE#5096]
before mouse hover (looks like only one error)

![image](https://github.com/toeverything/AFFiNE/assets/13579374/18e8831f-dfe8-4773-9243-b6889dccefb0)

mouse hover (actually there are three)

![image](https://github.com/toeverything/AFFiNE/assets/13579374/e37f9312-cfe4-452a-9a06-707c12343dbe)

**Comment by techsmartjsk** [comment]
I want to solve it

**Comment by umar23faiz** [comment]
Hi @techsmartjsk , are you solving this or can I pick it up?

**Comment by keerthi5465** [comment]
Hi can i work on it
