### ISSUE TITLE
Add new feature to filter shared pages

### ISSUE THREAD

**Issue by lawvs** [toeverything/AFFiNE#5102]
### Description

Hope to support the function of filtering shared pages.

<img width="465" alt="Screenshot 2023-11-28 at 23 15 50" src="https://github.com/toeverything/AFFiNE/assets/18554747/ce21ed4f-342b-465e-ad9d-d5a02720a06e">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Himasnhu-AT** [comment]
Hi, if you ever decide to add this feature, ill be glad to handle it.
Can you assign it to me

**Comment by EYHN** [comment]
Hi @Himasnhu-AT 

Thank you for your willingness to contribute to affine!

I've discussed this feature request with our product team and the consensus is that this feature is very important and we will implement it in the near future.

To solve this feature request, we will need to obtain the shared list from the backend server, which may involve some network requests. We need to consider asynchronous data flow and exception handling, which may be relatively difficult.

If you are willing to contribute, we have some simpler requirements to enhance the page filter function, such as supporting filtering pages by **"relative"** created time and last updated time. see https://github.com/toeverything/AFFiNE/issues/5141

**Comment by Himasnhu-AT** [comment]
Thanks for your time, I'll look into them.
