### ISSUE TITLE
Unable to load ALL images after enabling AFFiNE Cloud​

### ISSUE THREAD

**Issue by lawvs** [toeverything/AFFiNE#5104]
### What happened?

https://github.com/toeverything/AFFiNE/assets/18554747/3786c728-99e8-4fd8-8df9-05d8e63746b9

### Distribution version

macOS x64 (Intel)

### Relevant log output

```shell
Error: Cannot find blob
```

### Anything else?

v0.10.2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
should be fixed in 0.10.3-beta https://github.com/toeverything/AFFiNE/pull/5037

**Comment by lawvs** [comment]
It does not work on `0.10.3-beta.7`

**Comment by EYHN** [comment]
You may need to open the workspace at the desktop/browser that originally "enabled cloud" to finish the synchronization.

I tested according to your process and it works in beta.7.

https://github.com/toeverything/AFFiNE/assets/13579374/f966ce6d-dd68-4664-878d-d2ad7579dff4

**Comment by lawvs** [comment]
Oh, it takes 10 minutes to sync. After a long wait, all blobs have been synced.

Thank you very much for your patient help!

<img width="456" alt="Screenshot 2023-12-03 at 02 47 15" src="https://github.com/toeverything/AFFiNE/assets/18554747/c3e7609b-9bfd-46a8-a770-6d933417b8de">
