### ISSUE TITLE
Arrow weight is not consistent with ​buttons nearby

### ISSUE THREAD

**Issue by xiazeyu** [toeverything/AFFiNE#5136]
### Description

The forward and backward arrow is too small especially in weight.

Before (upper) & After (lower)
![telegram-cloud-photo-size-5-6285309623082792797-x](https://github.com/toeverything/AFFiNE/assets/10560038/db8c337d-19dd-4eb2-ac31-0d917ddfbdec)

for reference, obsidian's
![telegram-cloud-photo-size-5-6285309623082792792-x](https://github.com/toeverything/AFFiNE/assets/10560038/1bb8f45d-19c6-479c-b023-a3b45c4a859b)

google's
![CleanShot 2023-11-29 at 20 57 31@2x](https://github.com/toeverything/AFFiNE/assets/10560038/aaa4db4b-21e1-4295-b1ce-55f77037579a)

Also, the measurement tells there's a huge difference.

![telegram-cloud-photo-size-5-6285309623082792774-m](https://github.com/toeverything/AFFiNE/assets/10560038/6d45dc3f-6cd9-4862-89e6-913ab209d652)
![telegram-cloud-photo-size-5-6285309623082792775-m](https://github.com/toeverything/AFFiNE/assets/10560038/685a1910-0b0b-43cb-ba9d-c65f0b7d87c1)

### Use case

It is actually impossible to move your eyes away from these two buttons. When using full-trackpad operations on a Mac, forward and backword using keyboard shortcut is takes too much effort, and thus clicking these buttons is the most intuitive ways to do it. But it takes too much effort for the eyes to locate these two buttons, especially they have shallow contrast with the background, and are relatively small.

Also, align the small and large buttons in the same line makes no sense since they should have the same level of impoerance and frequency of use.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hwangdev97** [comment]
Thank you for your issue. This is a known issue, but it is currently in line with the design. 

We will uniformly adjust this part of the design after providing the display ratio function in the future. In addition, if it is convenient, you can tell us your monitor resolution so that we can sort it out.

**Comment by xiazeyu** [comment]
Hi,

I’m using MacBook Pro 16” @ 2056x1329 with HiDPI.

**Comment by EYHN** [comment]
We have reviewed the issue and decided that, even though it has merit, we cannot currently include it in our near-term plan.
