### ISSUE TITLE
​Support filter pages by "relative" created time and last updated time

### ISSUE THREAD

**Issue by EYHN** [toeverything/AFFiNE#5141]
### Description

![CleanShot 2023-11-30 at 16 44 49](https://github.com/toeverything/AFFiNE/assets/13579374/aa369718-bcd9-497b-aa78-a68271986c80)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by rakheesingh** [comment]
@EYHN what exactly needs to do here? wanted to contribute on that

**Comment by EYHN** [comment]
@rakheesingh You need expend the filterMatcher in  `packages/frontend/component/src/components/page-list/filter/vars.tsx`, and register a new filter maybe named 'last'.

Looking forward to your PR 😄

**Comment by rakhee28** [comment]
@EYHN issue here will be number, the current filter is based on calendar,
New implementation for the last 'n' days, I need to implement a new filter to select numbers also, 
Do you have designs or some other easy approach for this ?

**Comment by EYHN** [comment]
@rakheesingh I think you can create a new custom type for the `last 'n' days` number in `filter/logical/custom-type.ts`, perhaps we could name it DateRange? Here's a possible implementation:

```ts
export const tDateRange = typesystem.defineData(
 DataHelper.create<{ value: number }>('DateRange')
);
```

Regarding the UI, you can use our standard design components, i tried make a demo to illustrate how this might look, I think it’s good.

we just need to modify `filter/literal-matcher.tsx` implement the component the new `DateRange` data type.

```
import { Menu, MenuItem } from '@toeverything/components/menu';
import { Input } from '@affine/component';

//...

literalMatcher.register(tDateRange.create(), {
  render: ({ type, value, onChange }) => {
    return (
      <Menu
        items={
          <div>
            <Input />
            {[1, 2, 3, 7, 14, 30].map(i => (
              <MenuItem key={i}>{i} days</MenuItem>
            ))}
          </div>
        }
      >
        <div>
          <span>{value}</span> days
        </div>
      </Menu>
    );
  },
});
```

The result looks like:

![CleanShot 2023-12-03 at 02 18 53](https://github.com/toeverything/AFFiNE/assets/13579374/e13104f2-8b14-404d-b7ff-401ba6cc8b66)

You can add interaction to it, let users have the flexibility to input data using the keyboard or make selections using the mouse.

**Comment by rakheesingh** [comment]
@EYHN I am not able to run this project on local, I checked out contribution.md file still it is showing error

**Comment by EYHN** [comment]
@rakheesingh I don't know what issue you are facing, starting this project just run `yarn` then `yarn dev`

Maybe you need to make sure your nodejs version is 18.x

**Comment by gauravruhela07** [comment]
@EYHN I am interested in solving this issue. Can you assign this issue to me if @rakheesingh is done with it. Thank you.

**Comment by EYHN** [comment]
@gauravruhela07 Thank you for asking, @rakheesingh has submitted a pr for this https://github.com/toeverything/AFFiNE/pull/5167

**Comment by ghost** [comment]
please close this, if this issue is resolved

**Comment by lawvs** [comment]
Fixed in https://github.com/toeverything/AFFiNE/pull/5167
