### ISSUE TITLE
Error page dose not fit dark mode

### ISSUE THREAD

**Issue by joooye34** [toeverything/AFFiNE#5155]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/9527419/9c6aae88-7a96-4ec6-99e7-e6a51e838881)

Follow design system https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?type=design&node-id=11815-11510&mode=design&t=x0CJ7aVuA2jYd4IX-0

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by moshiuzzaman** [comment]
i want to work on it but cannot access design system figma link

**Comment by moshiuzzaman** [comment]
And can you give me the link of this page

**Comment by moshiuzzaman** [comment]
can you please tell me when you face this page ?? i cannot find it in my browser

**Comment by sandy088** [comment]
Hey, I can solve this one and want to work on this, But not able the access your figma file as permission is required to watch this figma file. Can you approve my access request to this figma file and assign me this issue?

**Comment by sandy088** [comment]
Hey @joooye34 can you please mention How to reproduce this error, Because I tried and this butt it looks, this page is replaced by new 404 page

**Comment by joooye34** [comment]
@moshiuzzaman @sandy088 so sorry I decided to take this issue myself. The design file is our inner file and it is easy for us to fix this situation and future issues.

**Comment by moshiuzzaman** [comment]
> @moshiuzzaman @sandy088 so sorry I decided to take this issue myself. The design file is our inner file and it is easy for us to fix this situation and future issues.
ok thanks for confirmation
