### ISSUE TITLE
​Add title and new page button for empty state on all page

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#5157]
### What happened?

by deign
![shot-2023-12-01-17 38 59@2x](https://github.com/toeverything/AFFiNE/assets/24713927/069383f7-21c3-457d-b155-216b220fbf32)

current:
![shot-2023-12-01-17 40 38@2x](https://github.com/toeverything/AFFiNE/assets/24713927/1735e367-7568-4f22-b329-f7287316ab9f)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by rakheesingh** [comment]
Wnted to take this up. One question- Why does the new page button feature a dropdown icon, and what will be displayed when a user clicks on it?

**Comment by EYHN** [comment]
Hi @rakheesingh 

we already have this button on this page, but it hidden on empty mode.

![image](https://github.com/toeverything/AFFiNE/assets/13579374/544957e4-6e81-4c9f-bdde-c9d7b3408d85)

I can assign this to you, if you want working on this.

**Comment by rakheesingh** [comment]
@EYHN here is the PR for this issue
https://github.com/toeverything/AFFiNE/pull/5162

**Comment by EYHN** [comment]
Fixed by @rakheesingh in #5162 👏
