### ISSUE TITLE
​UnhandledPromiseRejectionWarning: TypeError: Not start with rpc.

### ISSUE THREAD

**Issue by TinsFox** [toeverything/AFFiNE#5172]
### What happened?

https://github.com/toeverything/AFFiNE/blob/91f31491488dd114fb01f50849bd408662fee1db/packages/frontend/electron/src/main/main-window.ts#L28

When the development environment runs the client and outputs `helperProcessManager`, you will get the following error message:

<img width="1180" alt="image" src="https://github.com/toeverything/AFFiNE/assets/33956589/b4e8fcf1-deb6-4675-815d-84ffb7b40a9a">

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
you need run `yarn dev`, and keep the dev server running while the electron start.

**Comment by TinsFox** [comment]
Where should I run it?

I now execute `yarn dev` in `packages/frontend/core` and `packages/frontend/electron`

The following is my operation video
[Demo Video](https://buckets.tinsfox.com/Export-1701689785504.mp4)

**Comment by EYHN** [comment]
Sorry, I missed your reply, it looks like you successfully started affine at the end of the video. I think I can close this issue.

**Comment by TinsFox** [comment]
It works successfully, but I think there is a potential bug.
