### ISSUE TITLE
The right half of settings has different clarity in different browsers

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#5176]
User from telegram: "Texts in Chrome-based browsers and the native app are really blurry, nothing like in Gecko-based browsers like Firefox where everything is crisp and clear. It's all happening on a 1080p screen and Win11. Checked this on two different systems."

![Image](https://github.com/toeverything/AFFiNE/assets/142964904/02738f5e-8bcd-4d30-8056-895bae53b710)

**Comment by joooye34** [comment]
We will fix this issue next version.
