### ISSUE TITLE
chore: Disable ​useless workflows for GitHub Action 

### ISSUE THREAD

**Issue by Zheaoli** [toeverything/AFFiNE#5243]
### What happened?

For now, I have noticed that we have a lot of workflows which are not runned in the last year and the yaml file has been deleted in the repo. So maybe we can disable it

1. https://github.com/toeverything/AFFiNE/actions/workflows/add-to-project.yml
2. https://github.com/toeverything/AFFiNE/actions/workflows/build-test.yml
3. https://github.com/toeverything/AFFiNE/actions/workflows/livedemo.yml
4. https://github.com/toeverything/AFFiNE/actions/workflows/affine.yml
5. https://github.com/toeverything/AFFiNE/actions/workflows/build-aio-docker.yml
6. https://github.com/toeverything/AFFiNE/actions/workflows/lisa.yml
7. https://github.com/toeverything/AFFiNE/actions/workflows/build-pr.yml
8. https://github.com/toeverything/AFFiNE/actions/workflows/nx.yml
9. https://github.com/toeverything/AFFiNE/actions/workflows/pr-title-line.yml
10. https://github.com/toeverything/AFFiNE/actions/workflows/test-visual.yml

### Distribution version

Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Brooooooklyn** [comment]
It’s all used by the old https://app.affine.pro branch. We will delete them soon once the stable branch codes replace https://app.affine.pro.
