### ISSUE TITLE
Fix font color of share button​

### ISSUE THREAD

**Issue by zanwei** [toeverything/AFFiNE#5250]
### What happened?

<img width="864" alt="image" src="https://github.com/toeverything/AFFiNE/assets/40333372/1ef86f32-9d85-4d46-8555-91e4fa4e8650">

### Distribution version

Web (affine.fail)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by gauravruhela07** [comment]
@zanwei I am interested in solving this issue. Can you please assign it to me? Thank you

**Comment by zanwei** [comment]
Sure

**Comment by gauravruhela07** [comment]
@zanwei I am seeing the correct font color of the button. Attaching screenshot for your reference. 

<img width="826" alt="Screenshot 2023-12-12 at 7 52 18 AM" src="https://github.com/toeverything/AFFiNE/assets/37220287/e19f0716-0ac3-4f52-bb2f-e1629c441a4a">

If I am mistaken, could you please provide steps to recreate the same issue?

**Comment by gauravruhela07** [comment]
@zanwei I have been trying to go through the code base so that I can contribute in future. For that can you please help me with understanding repository structure like what framework AFFine is using etc. It would be better if you can share some resources from where I can clear all of my doubts. Thanks.

**Comment by zanwei** [comment]
hi @gauravruhela07 , just checked with @pengx17 . This issue has been fixed so I will close this issue. In terms of contribution, my colleagues may be able to help you

cc @pengx17 @joooye34 @JimmFly

**Comment by pengx17** [comment]
fixed in https://github.com/toeverything/AFFiNE/pull/5239

**Comment by gauravruhela07** [comment]
Hi @pengx17 @joooye34 @JimmFly can you please help here. I am new to open source and even a slightest help from you to understand code repository structure, can improve my understanding. Thank you.
