### ISSUE TITLE
The right ​sidebar will automatically appear or disappear when resizing the window

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#5253]
### What happened?

![shot-2023-12-11-11 36 58](https://github.com/toeverything/AFFiNE/assets/24713927/f6e0c601-74d9-422b-9e0f-6f5523872cfe)

### Distribution version

macOS ARM 64 (Apple Silicon)

### Anything else?

![shot-2023-12-11-11 39 35@2x](https://github.com/toeverything/AFFiNE/assets/24713927/0353eec0-ccad-4a5d-ac38-d19f8f8a72d6)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joooye34** [comment]
Fixed by https://github.com/toeverything/AFFiNE/pull/5262
