### ISSUE TITLE
The TOC type icon is incompletely displayed

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/AFFiNE#5272]
https://github.com/toeverything/blocksuite/assets/142964904/41a960e6-42c9-43c2-9b75-bf558f2abae3

**Comment by hwangdev97** [comment]
![shot-2023-12-12-15 04 01](https://github.com/toeverything/blocksuite/assets/24713927/d5484638-171d-45ea-80d4-93bcc3fbcd86)

**Comment by hwangdev97** [comment]
There is one missing line here. In fact, the size should be adjusted here.

**Comment by pengx17** [comment]
should have been fixed in latest version
