### ISSUE TITLE
The pitch zooming function incorrectly zooms the toolbar

### ISSUE THREAD

**Issue by vincentdchan** [toeverything/AFFiNE#5293]
### What happened?

https://github.com/toeverything/AFFiNE/assets/2352832/e6a71a97-9915-4122-9eca-f521fedc45df

When zooming the image with trackpad, the toolbar and the hold page should not be zoomed.

### Distribution version

Web (insider.affine.pro)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by umar23faiz** [comment]
I am working on this and #5294 . Both are same issue.
