### ISSUE TITLE
[bug]: double click crash at the end of the text

### ISSUE THREAD

**Issue by m1911star** [toeverything/AFFiNE#530]
### To Reproduce

1. set cursor at the end of the text
2. double click

### Screenshots

<img width="979" alt="34f7f630881aa2e3bc18c849a70ff2b" src="https://user-images.githubusercontent.com/4948120/201685406-112e6237-6d76-4ea9-bdb6-3fd5d4537872.png">

### Platform

Windows 10

### Browser

Edge

**Comment by tzhangchi** [comment]
Thanks for your feedback, I wil track it

**Comment by tzhangchi** [comment]
@m1911star Thank you for your feedback, we have [fixed the bug](https://github.com/toeverything/blocksuite/commit/34aa9c64668fd218a22adc6b93aae80b15679a9d) in the newest version  http://pathfinder.affine.pro/ , happy new year
