### ISSUE TITLE
Unable to use drag to upload file or images

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#5313]
1. drag to upload file failed
2. drag to upload image won't insert to expected position

https://github.com/toeverything/blocksuite/assets/110808979/84b9198c-38a3-4d25-aea5-a7806b4d62ca

**Comment by fourdim** [comment]
Related to AFFiNE's optimization which transforms
https://github.com/toeverything/blocksuite/blob/2b5bb47533b022cea0cef72422cf8ba31721f280/packages/blocks/src/attachment-block/attachment-service.ts#L16
to
```ts
e=>e.type.startswith("image/")
```
![image](https://github.com/toeverything/blocksuite/assets/59462000/9a16e7f8-159b-49ed-97b9-b650e3eed37e)
