### ISSUE TITLE
Incorrect ​500 page image

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#5336]
### What happened?

![Image](https://github.com/toeverything/AFFiNE/assets/110808979/9e46795a-13eb-4d64-8159-616835405e06)

[check design👇](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?type=design&node-id=11815-11511&mode=design&t=mPBiiieUtM8LSeWe-4)

![Image](https://github.com/toeverything/AFFiNE/assets/110808979/c24b2946-b61b-4532-b749-6555cb9645f8)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ZacharyBacon** [comment]
I have had this problem before, and it is recommended to lower the version and open it. I solved it by accident. I have to back up my data frequently, but I feel sorry for my data. Although there is no danger
