### ISSUE TITLE
​when building the project with command "yarn workspace @affine/native build"?

### ISSUE THREAD

**Issue by arthurchen1906** [toeverything/AFFiNE#5385]
### What happened?

```
E:\AFFiNE>yarn workspace @affine/storage build
   Compiling affine_storage v1.0.0 (E:\AFFiNE\packages\backend\storage)
error: expected item, found `..`
 --> packages\backend\storage\src\hashcash.rs:1:1
  |
1 | ../../../frontend/native/src/hashcash.rs
  | ^^ expected item
  |
  = note: for a full list of items that can appear in modules, see <https://doc.rust-lang.org/reference/items.html>

error: could not compile `affine_storage` (lib) due to previous error
Internal Error: Build failed with exit code 101
    at ChildProcess.<anonymous> (file:///E:/AFFiNE/node_modules/@napi-rs/cli/dist/api/build.js:174:28)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:526:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

in the BUILDING.md tutorial, when executing command "yarn workspace @affine/native build", the error happens

in the packages\backend\storage\src\hashcash.rs, only one line found -> `../../../frontend/native/src/hashcash.rs`

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Relevant log output

```shell
as above
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by arthurchen1906** [comment]
the default `canary` repo

**Comment by darkskygit** [comment]
I already update our building guide, please refer to latest documentation:

https://github.com/toeverything/AFFiNE/blob/canary/docs/BUILDING.md#windows

**Comment by arthurchen1906** [comment]
来信已收到！我会及时处理。
