### ISSUE TITLE
Preferences the font blur on ArchLinux

### ISSUE THREAD

**Issue by nawbc** [toeverything/AFFiNE#5392]
### What happened?

It seems like blur filter?

![image](https://github.com/toeverything/AFFiNE/assets/45007226/20eef47b-def4-4ab0-a0d8-0a8b14eefff1)

More than just fonts
![image](https://github.com/toeverything/AFFiNE/assets/45007226/d620b790-1fb7-4f51-a5b3-25be99367ad1)

Correct:
![image](https://github.com/toeverything/AFFiNE/assets/45007226/cee17ddb-3c00-4b95-9bbf-b96a035c66fe)

Version
App Version
0.10.3 stable
Editor Version
0.0.0-20231122113751-6bf81eb3-nightly

### Distribution version
OS: EndeavourOS Linux x86_64 
Kernel: 6.6.7-arch1-1 
DE: GNOME 45.0 
GPU: Intel TigerLake-H GT1 [UHD Grap 
GPU: NVIDIA GeForce RTX 3060 Mobile

**Comment by fourdim** [comment]
Duplicated of #4963.
