### ISSUE TITLE
Migrate next-auth to @auth/core

### ISSUE THREAD

**Issue by Brooooooklyn** [toeverything/AFFiNE#5421]
next-auth is designed for next.js framework, the `@auth/core` is more suitable for our usecase.

**Comment by shubhamku044** [comment]
I would like to work on this issue

**Comment by MohammedAslam106** [comment]
I haven't worked auth/core before. I would love to. Can you explain why you want to migrate from next-auth to auth/core so I can work on it?

**Comment by hrithik01** [comment]
Is anyone working on it?

**Comment by shubhamku044** [comment]
yes, I am
