### ISSUE TITLE
[feature]: Login authentication

### ISSUE THREAD

**Issue by LIHAQI** [toeverything/AFFiNE#545]
### 1~3 main use cases of the proposed feature

能不能增加登陆认证功能，如果自己搭建开放到公网，需要登陆认证的功能。

**Comment by tzhangchi** [comment]
Hello, thanks for the feedback, this is already under development

**Comment by hhzx** [comment]
感谢这个问题 这正是我想说的 目前这样完全不敢开放公网访问...这个笔记只能本机使用

**Comment by Fabioax7** [comment]
Support Permission and Collaboration will be a great feature. I intend to have an instance to be used by my company's team and having the permissions feature is essential.

**Comment by robinduerhager** [comment]
> Hello, thanks for the feedback, this is already under development

Hi, can you elaborate a little more on which types of authentication will be supported and when this will be built in? :)

**Comment by darkskygit** [comment]
> > Hello, thanks for the feedback, this is already under development
> 
> Hi, can you elaborate a little more on which types of authentication will be supported and when this will be built in? :)

We will start the development of this feature after the next pre-release version(we call it downhills). Currently, we are still evaluating the complexity of login config for ordinary users. Therefore, we may only have the simplest user password option at the beginning, and then gradually add OAuth, LDAP and other solutions

**Comment by tzhangchi** [comment]
Thank you for all your feedback. We are currently addressing the related issue on https://github.com/toeverything/AFFiNE/issues/2648.
