### ISSUE TITLE
[user feedback] public links cannot view images

### ISSUE THREAD

**Issue by Yixuan-0602** [toeverything/AFFiNE#5460]
The pages says “image loading failed” in affine beta version.
After the user logged out, then it shows syncing but it has been like this 30 min.

![Image](https://github.com/toeverything/AFFiNE-Community/assets/154396382/addfcb2a-e5b0-4275-a1cd-4c464f7b6b9a)

**Comment by joooye34** [comment]
Maybe this is caused by https://github.com/toeverything/AFFiNE/issues/5448.
