### ISSUE TITLE
version 0.11.2 keeps re-downloading.

### ISSUE THREAD

**Issue by icarus-00** [toeverything/AFFiNE#5475]
### What happened?

the desktop app keeps fetching a new update (0.11.2) download it and then prompting me to install it
![image](https://github.com/toeverything/AFFiNE/assets/147264641/6dac2201-70ea-4f7b-ad4d-9ef07f72279d)
![image](https://github.com/toeverything/AFFiNE/assets/147264641/1e7ea34a-5ff9-48f9-b0d6-67f41d9832b2)
![image](https://github.com/toeverything/AFFiNE/assets/147264641/e749b73d-1760-45d9-a75b-1d8beca14b90)

if I click on this restart to install button, the app restarts but the loop goes on again, version 0.11.2 downloads again, etc.
if I restart the app in middle of the download, nothing gets fixed, the download just starts from the beginning, even the update was downloaded before I restart the app.

i downloaded affine, once from the website, uninstalled it and downloaded it again from GitHub releases, both have the same issue

![image](https://github.com/toeverything/AFFiNE/assets/147264641/6864739a-5558-4f5e-bc54-a13c109c967f)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by icarus-00** [comment]
just want to add
this issue occurs in canary as well.
this can be prevented by disabling auto update features in settings, but thought I might report it for newer releases.

**Comment by poluxmx** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/30530465/4bb8637a-552d-4802-bb98-7fc17f61c764)

**Comment by joooye34** [comment]
Thanks for reporting this issue, I have found this reason. It will be fixed soon.

**Comment by icarus-00** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/147264641/a23453de-a5a8-440a-9fe0-d0eedc9cea83)
issue solved, amazing work.
