### ISSUE TITLE
​Search in Page

### ISSUE THREAD

**Issue by ZoneTwelve** [toeverything/AFFiNE#5479]
### Description

There is a missing feature that allows me to search for content on the page

### Use case

Search content on that page

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
I have forwarded your request to our product design team.

**Comment by FurryWolfX** [comment]
Also missing Replace, I can't replace keywords in batches.

**Comment by forehalo** [comment]
@hwangdev97

**Comment by hwangdev97** [comment]
We have already supported this feature. Please update to the latest client.
