### ISSUE TITLE
Share certain pages or sections with externals 

### ISSUE THREAD

**Issue by swissbyte** [toeverything/AFFiNE#5532]
### Description

I would like to be able to create share links for pages or sections.

the share link should be unique like: https://mydomain.com/share/UUID

it should be possible to create multiple share links per page

it should be possible to create a vaild through date for each shre link

it should be possible to make the share read only (this is the standard requirement, read only)

there should be one central view to manage all shared links/pages (for example under settings)

In the first implementation of this feature, the viewer of the shared link should only see the lahe itself. No login buttons or collaboration features. The focus should be to show him this page and not the whole menue of affine. Therefore like a light reader mode just for pages

### Use case

I like to document things and stuff for others. For example: documenting a personal project or even a oublic one.

i would like to be able to share the documentation or even the manual i wrote within affine with lthers and be able to link to it from my website for example.

the viewer should only be able to see that single page. 

This feature would be awesome

### Anything else?

I really hope to see that feature as it would help a lot to save precious lifetime in not doing things twice.

another usecase could be to show project progress to various stakeholders of a project. Assuming that you use affine for light projectmanagement.

Thank you for your efforts! 
 
### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jaymehta002** [comment]
i would like to work on this issue with your team

**Comment by swissbyte** [comment]
Hi @jaymehta002 great 😍 how can we support you?

**Comment by jaymehta002** [comment]
Assign some task to me. I can make really efficient API's but my tech stack is bit different. So I will work along with anyone.

**Comment by swissbyte** [comment]
Im a bit confused @jaymehta002 do we talk about the same? This is an opensource project. Therefore you can start implementing the requested features right away… :)

**Comment by EYHN** [comment]
I'm not sure if you've used affine's existing share feature?

what do you think about it?

![Image](https://github.com/toeverything/AFFiNE/assets/13579374/be6a33cd-c099-4862-bf82-c90376c2d575)
