### ISSUE TITLE
Unable to sign-in to AFFiNE Cloud

### ISSUE THREAD

**Issue by evdcush** [toeverything/AFFiNE#5587]
### What happened?

- `AFFiNE 0.11.2` AppImage
- `Ubuntu 20.04 5.15.0-91`

This app does not allow sign-in.

Attempts to "sign up" or "login" to AFFiNE Cloud:

### Via Google
Selecting this option opens the browser to authenticate through one's Google account and authorize AFFiNE Cloud.
After authorizing, you get stuck on a screen that says "Opening AFFiNE app now":

![screencap_2024-01-13_19-29-09](https://github.com/toeverything/AFFiNE/assets/28853935/ddd2871a-2690-4a86-b821-78e366efbf13)

If you click try-again, it will attempt an XDG open which does nothing and will not link/open to the active AFFiNE app.

### Via Email
This is just broken.
Doesn't work with any email, either through the AppImage or on the web.

AppImage:
![screencap_2024-01-13_19-24-49](https://github.com/toeverything/AFFiNE/assets/28853935/aeeb8ad2-ae83-40e9-8b24-0bfad6251a18)

Web:

![screencap_2024-01-13_19-33-11](https://github.com/toeverything/AFFiNE/assets/28853935/b4be6602-69f4-423e-83d2-574495b16044)

### Distribution version

Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
Thanks for your reporting.

This web sign-in issue was caused by a recent miss configuration and should've been solved.

For the app activating issue, @pengx17 might have any feedback?

**Comment by EYHN** [comment]
This issue should have been fixed already. If you are still encountering this issue, please reopen this
