### ISSUE TITLE
Adjust font stack to improve Japanese text rendering

### ISSUE THREAD

**Issue by mutokrm** [toeverything/AFFiNE#5591]
## Japanese not rendering correctly

I've observed an issue where **Japanese characters in the application are not rendering correctly**. They appear to be influenced by the PingFang SC font, leading to a display that resembles Chinese/Korean-style characters instead of Japanese. This issue significantly impacts the readability and user experience for the Japanese-speaking users.

All the Japanese letters displayed in the picture are adversely affected by the font. This issue is compromising the overall quality of the product, which otherwise is an exceptional product!
![Screenshot](https://github.com/toeverything/AFFiNE/assets/90857923/a78ce472-3a75-469d-84e7-faaa77696704)

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome

## Root cause
The CSS variable `--basic-font-family` has "Ping Fang SC", as defined in [packages/theme/src/index.ts](https://github.com/toeverything/design/blob/ba83dabbfb3fe8fef98a561d3cf9e7d78c7b7a33/packages/theme/src/index.ts#L33). This font is being used to render Japanese, leading to the issue.

## Proposed Solution
I suggest **overriding the font stack specifically for Japanese**. The plan is to modify the fontFamily property for the body element in [packages/frontend/component/src/theme/theme.css.ts](https://github.com/toeverything/AFFiNE/blob/canary/packages/frontend/component/src/theme/theme.css.ts), ensuring that it excludes "Ping Fang SC" when the selected language is Japanese. This approach will maintain the existing font stack for the other languages while enhancing the rendering quality for Japanese.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
I've forwarded the issue to the design team to look at

**Comment by pengx17** [comment]
Should be fixed in next release.

**Comment by mutokrm** [comment]
Awesome! Looking forward to it!
