### ISSUE TITLE
​Failed to set password

### ISSUE THREAD

**Issue by Jengro777** [toeverything/AFFiNE#5611]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/35259040/a9bc3e44-04f1-4b02-ad4f-1fa08cc5bbbb)

![image](https://github.com/toeverything/AFFiNE/assets/35259040/a74be39c-5ae9-44a0-a5ae-436d919208a4)

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by darkskygit** [comment]
Hi, we have fixed the problem. Please try it again.
