### ISSUE TITLE
This is Local-first software Hovar problem

### ISSUE THREAD

**Issue by ShlokMathur** [toeverything/AFFiNE#5612]
### What happened?

when we click on the connecting page the page starts hovering

https://github.com/toeverything/AFFiNE/assets/80643183/bbf11996-78b6-4585-9af7-4bf297ba9e1e

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Safari

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
I think this is a compatibility issue between affine and safari browser.

Affine is currently in the early stages of development, and we are not spending too much effort on Safari compatibility at the moment. I suggest you use Chrome.

**Comment by Meow1993** [comment]
> I think this is a compatibility issue between affine and safari browser.
> 
> Affine is currently in the early stages of development, and we are not spending too much effort on Safari compatibility at the moment. I suggest you use Chrome.
