### ISSUE TITLE
​Can not add a new line

### ISSUE THREAD

**Issue by Orca-bit** [toeverything/AFFiNE#5628]
### What happened?

version  0.11.3

when the last line was in a code block, I can not add a new normal line
![image](https://github.com/toeverything/AFFiNE/assets/52285880/1a44d0c3-0440-441c-bbdb-a0c0d8f56c21)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by huangfenggu** [comment]
I also encountered this problem

**Comment by Throows** [comment]
Hello !
You can add another line below by using the shortcut `CTRL + Enter` on Windows and `CMD + Enter` on MacOS.
Can you tell me if it works for you ?
I can work on if not 😉
Have a nice day !

**Comment by Orca-bit** [comment]
> Hello ! You can add another line below by using the shortcut `CTRL + Enter` on Windows and `CMD + Enter` on MacOS. Can you tell me if it works for you ? I can work on if not 😉 Have a nice day !

It works. thanks
