### ISSUE TITLE
​Add open log folder and storage folder buttons in settings.

### ISSUE THREAD

**Issue by fourdim** [toeverything/AFFiNE#5647]
### Description

It often the case that users want to backup their storage or report a bug using the log.
It would be convenient if these buttons are present.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jnrage** [comment]
how can i do it

**Comment by aadityath09** [comment]
Something lagging with line and other bugs are detected!!
