### ISSUE TITLE
​从pycharm上复制的代码,无法粘贴

### ISSUE THREAD

**Issue by ningxiangyu2020** [toeverything/AFFiNE#5649]
### What happened?

1. 从pycharm中使用ctrt+v 或者鼠标右键选择一段代码,然后复制
2. 粘贴到affine
3. 光标会移动到代码长度末尾的位置
4. 但是界面上没有代码
5. 如果将代码先粘贴到其他地方,比如说微信聊天窗口,然后再在聊天窗口复制一遍
6. 再粘贴到affine,就没有问题

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fourdim** [comment]
Fixed in the latest release.
