### ISSUE TITLE
Allow the ability to set the working directory​

### ISSUE THREAD

**Issue by CapedBojji** [toeverything/AFFiNE#5662]
### Description

Hello, Loving the app so far, but i wish there was a way to set the working directory of a workspace, so i could set up sync using syncthing. This way i don't have to manually and export the workspace

### Use case

Will allow for free and open source auto syncing. For those that don't want to use proprietary sync

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
According to the current design, you should not use software such as syncthing to sync affine's data files. Otherwise, data may be damaged.

We currently only support using official affine cloud or selfhost to synchronize your documents.
