### ISSUE TITLE
Export error​ in AFFiNE 0.11.3

### ISSUE THREAD

**Issue by udfed** [toeverything/AFFiNE#5670]
### What happened?

In page mode, when export to pdf or png, only current screen will be generated.
It also means the exported pdf or png is always one page.

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zol9527** [comment]
Yeah. I met the same problem. Hope the team can fix this soon.

**Comment by gusakovs** [comment]
Bumping this as I also have the same problem !

**Comment by EYHN** [comment]
fixed https://github.com/toeverything/blocksuite/pull/5973
