### ISSUE TITLE
Unable to Update Profile Photo - "Update User Avatar Failed" Issue

### ISSUE THREAD

**Issue by Sufi-Yan-Raza** [toeverything/AFFiNE#5689]
### What happened?

**Issue Overview:**
I am encountering difficulties updating my profile photo within the AFFiNE management software. Despite attempting the update through various means, including the Microsoft Edge browser and the application itself, the process consistently fails. Upon uploading the image, a popup notification appears, stating, "Update User Avatar failed - failed to put object objectno-avatar.

**Steps Taken:**
I have made multiple attempts using different sizes of images to ensure compatibility. However, the issue persists, and the profile photo update remains unsuccessful.

**Error Message:**
"Update User Avatar failed - failed to put object **objectno-avatar.**"

**Environment:**
1. Browser: Microsoft Edge
2. AFFiNE Application

**Expected Behavior:**
A successful update of the profile photo without encountering the "Update User Avatar failed" error message.

**Additional Information:**
Please note that I have tested this issue across different platforms and sizes of images, but the problem persists consistently. Any guidance or resolution steps to address this matter would be highly appreciated.

**Attachments:**
![Screenshot 2024-01-24 134812](https://github.com/toeverything/AFFiNE/assets/123558804/724cd538-f1c5-44f7-accc-50b8bb3dcb80)

Thank you for your prompt attention to this matter.

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Brooooooklyn** [comment]
Fixed
