### ISSUE TITLE
Where is the​ local data path?

### ISSUE THREAD

**Issue by LockeCipher** [toeverything/AFFiNE#5690]
### What happened?

May I ask where the data storage path is in affine offline mode? If switch the working environment, can the data be migrated to another computer?

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
AFFiNE storage it data in per-user application data directory, which by default points to:
%APPDATA% on Windows
$XDG_CONFIG_HOME or ~/.config on Linux
~/Library/Application Support on macOS

to migrate to another computer:
![CleanShot 2024-01-25 at 14 59 23](https://github.com/toeverything/AFFiNE/assets/13579374/54d254f1-9a09-4eee-94e3-fcb7ca00fd61)
![CleanShot 2024-01-25 at 14 59 36](https://github.com/toeverything/AFFiNE/assets/13579374/95b429a4-3294-4593-9a29-5dd7654c7a79)
