### ISSUE TITLE
Please enhance the effectiveness of the search results in the quick search panel

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#5699]
### Description

![shot-2024-01-25-14 28 29@2x](https://github.com/toeverything/AFFiNE/assets/24713927/df6e6823-871a-4090-a1d6-ce37032af23e)

I think we need to display the results matching 'aff' first. Also, I suggest that the number of document results should be limited to less than 10.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by keerthi5465** [comment]
Can i work on it

**Comment by EYHN** [comment]
fixed in https://github.com/toeverything/AFFiNE/pull/5722
