### ISSUE TITLE
PWA support​ please

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/AFFiNE#5700]
### Description

Add PWA support, and update the favicon cc @zanwei 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hwangdev97** [comment]
The favicon resources 👇
[Favicons (favicon-192).zip](https://github.com/toeverything/AFFiNE/files/14060753/Favicons.favicon-192.zip)

**Comment by EnterMan123** [comment]
Need this

**Comment by forehalo** [comment]
pwa is dead

**Comment by lexfreedomcom** [comment]
@forehalo why pwa is dead?) what will be your advise ?
