### ISSUE TITLE
​Sort of Favourities in the left column

### ISSUE THREAD

**Issue by MingStudentSE** [toeverything/AFFiNE#5711]
### Description

Favorities in the left column cannot be reordered through manual adjustment or rule sorting. It is currently sorted by adding time. It is very inconvenient if you want to adjust the order. Hopefully manual sorting or rule sorting will be allowed.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
This feature will be incorporated into the next stable version of AFFiNE, stay tuned.
