### ISSUE TITLE
Opt out of telemetry​

### ISSUE THREAD

**Issue by MichaelDevon** [toeverything/AFFiNE#5759]
### Description

The Affine privacy policy outlines a type of data collection that i find very intrusive and i would like to opt out.
I don't plan to make a cloud account and i would like to use it offline, without my (according to your policy) GPS data, IP, OS, unique device ID, type of device, what i do in affine such as what pages i visit being collected and stored indefenitely. 

Preferably affine should prompt the user before sending any telemetry data to the server on first launch,  or at least have an option to disable this in settings.

"We may also collect information about you from third parties, such as social media platforms or other companies that provide us with data."

I have no idea how it serves the user to go through their social media platforms for example to obtain more data about them, but thats another question for another day.

Additionally please clarify in the policy when this info is being sent. Only if online account is used? And give choices to the user other than "If you do not agree with our policies and practices, do not use the Services."

### Use case

For people who value their privacy, this toggle would actually let them use the app.

### Anything else?

https://affine.pro/privacy

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MichaelDevon** [comment]
Its also pretty misleading to market AFFiNE as "Privacy first" when its actually impossible to stop it from gathering all of these types of data.

**Comment by RyzeNGrind** [comment]
Wow that was super misleading and I had no idea (just started to run the app now on desktop). Does this only apply to the cloud account or the selh-hosted/desktop application as well?

**Comment by MichaelDevon** [comment]
> Wow that was super misleading and I had no idea (just started to run the app now on desktop). Does this only apply to the cloud account or the selh-hosted/desktop application as well?

I have reason to beleive it applies to everything, becuase they would normally mention under "when is this data collected". By using their products/services you agree to this collection and they keep the policy very vague on purpose. appflowy.io which is a competing app has its privacy policy written propperly and can be understood easily.

**Comment by HeJiachen-PM** [comment]
Sorry, we will update it to narrow down the scope of data related terms.

**Comment by MichaelDevon** [comment]
What does that mean?

**Comment by HeJiachen-PM** [comment]
We are not collecting data from the non-cloud part so we will draft up a
new services agreement.

MichaelDevon ***@***.***>于2024年2月14日 周三22:49写道：

**Comment by vince-vibin** [comment]
The main drawback of not using the non-cloud version is a lack of features (The last release seems to be around 1 Year ago). In the ReadMe it says the same. 
Is there any roadmap or anything like it about the selfhosted version? The commit of the ReadMe that says you are working on fixing up the selfhosted version is also six months old

**Comment by MichaelDevon** [comment]
Probably best to open a new issue for that.

**Comment by mockinbirdy** [comment]
Sad to see. I've been keeping an eye on this project since 2022, hoping to find a genuine, no-nonsense alternative to Notion. Welp. Back to waiting for another group of enthusiasts who take user data seriously.

**Comment by HeJiachen-PM** [comment]
This issue is about better privacy terms Which we are still working on. However, I'd like to point out that the self hosted version has been updated a month ago and now is updating with every release. Moreover, the non-cloud part is just having full features except for the cloud native ones like page history and cloud sync. Y

**Comment by HeJiachen-PM** [comment]
> The main drawback of not using the non-cloud version is a lack of features (The last release seems to be around 1 Year ago). In the ReadMe it says the same. Is there any roadmap or anything like it about the selfhosted version? The commit of the ReadMe that says you are working on fixing up the selfhosted version is also six months old

The non cloud part is under MIT and being updated everyday. What are you talking about?

**Comment by vince-vibin** [comment]
> > The main drawback of not using the non-cloud version is a lack of features (The last release seems to be around 1 Year ago). In the ReadMe it says the same. Is there any roadmap or anything like it about the selfhosted version? The commit of the ReadMe that says you are working on fixing up the selfhosted version is also six months old
> 
> The non cloud part is under MIT and being updated everyday. What are you talking about?

This was written before the release of the self hosted version so it's not relevant anymore.

**Comment by MichaelDevon** [comment]
So until we "log in" there will be no data collected?

**Comment by forehalo** [comment]
you can opt-out telemetry in app settings now

**Comment by MichaelDevon** [comment]
> you can opt-out telemetry in app settings now

What happens in that period of time until we get to that option while setting up the app?

**Comment by HeJiachen-PM** [comment]
What do you mean? No matter what setting is applied, Affine never collect
your personal data. The telemetry part refers to basic log info about your
usage, not related your content, files or personal data, in any way.

MichaelDevon ***@***.***>于2024年8月9日 周五20:37写道：

**Comment by MichaelDevon** [comment]
First of all, GPS, IP, OS, Device ID and Device type are sensitive to me. And what is sensitive is subjective. I don't want to share any data, including diagnostics. What you said has nothing to do with my question. What i am asking, is what happens until i get to the opt-out toggle? You collect the data before i even have a chance to decline? This is not how consent works, and most users would not be comfortable with this if they were aware. This should be asked on first app launch to obtain PROPPER consent, as many of us want to use this offline.
