### ISSUE TITLE
The title display and the content sync problem

### ISSUE THREAD

**Issue by isaiah5818** [toeverything/AFFiNE#5796]
### What happened?

1. The title and the navigation are inconsistent
![image](https://github.com/toeverything/AFFiNE/assets/145014234/aa261cf3-44e0-4296-b023-a8f349c6a5e1)

2. The content of the desktop and web versions is not synchronized
![image](https://github.com/toeverything/AFFiNE/assets/145014234/53a3f242-a11c-4308-ac09-088fa2df3da5)
![image](https://github.com/toeverything/AFFiNE/assets/145014234/bb009cfa-0aa9-43ca-9563-a620ba044066)

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
It’s fixed in latest beta version, we will release stable version in next few days
