### ISSUE TITLE
Sync state is always syncing

### ISSUE THREAD

**Issue by zkwolf** [toeverything/AFFiNE#5806]
### What happened?

1. proxy enviorment: clash pro 
  auto select mode
2. happen condition: 
  when app running for a long time
4. error message: sometimes notify `failed to fetch`
5. AFFINE version: 0.11.3
### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

<img width="251" alt="image" src="https://github.com/toeverything/AFFiNE/assets/8555127/43b8dc71-9bb2-4865-9a92-576268de8105">
<img width="1133" alt="image" src="https://github.com/toeverything/AFFiNE/assets/8555127/2b127144-63a8-4a2d-b54c-1161e22a9901">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
This problem will be fixed in 0.12.0. If you encounter this issue in 0.11.3, you can try refreshing the web page or restarting the desktop app.

**Comment by EYHN** [comment]
should be fixed in 0.12.0
