### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by lucaszischka** [toeverything/AFFiNE#5807]
### Description

Many (Markdown) editors support LaTeX for rendering Math equations. For example GitHub (only inline), Obsidian, Zettlr, AppFlowy and MarkText.

---

To clear up confusion, im referring to "full block" latex support, as inline has been implemented in https://github.com/toeverything/blocksuite/pull/5909 and only hasn't made it to AFFiNE jet.

> Note that this is only supported as an extension example based on the framework, require some more time to further land it in AFFiNE.

Following https://github.com/toeverything/blocksuite/issues/3014 has been marked as resolved, just as the duplicates
https://github.com/toeverything/AFFiNE/issues/512
https://github.com/toeverything/AFFiNE/issues/4916
https://github.com/toeverything/blocksuite/issues/3282
https://github.com/toeverything/blocksuite/issues/3432
https://github.com/toeverything/blocksuite/issues/4158
https://github.com/toeverything/blocksuite/issues/5569
https://github.com/toeverything/blocksuite/pull/5442

---

To my understanding the inline LaTeX support was (or currently is) missing as there was no support to add custom inline nodes.
However it looks like `$$ full line LaTeX equation $$` went unnoticed, as it could be implemented as a normal block (I hope).

Therefore im opening this issue, as this feature does not seem to be on the roadmap and also neither LaTeX support is found in AFFiNE jet, so it might me good to have an issue open to prevent further duplicates from people not looking at closed issues.

---

Anyway thank you for this amazing app, can't wait to switch ❤️!

### Use case

People who would like to write down Math equations (for example Math, IT Students or Profs).

### Anything else?

> Except for the substitution method the term has to look like this:
> $$T(n)=a\times T(\frac{n}{b})+f(n),\qquad\text{with $T(1)=1$}$$

In this example I showcase full line LaTeX with a nested inline LaTeX (`T(1)=1`) which is commonly also supported by other editors. Unfortunately the inline one is rendered by GitHub and escaping the $ by backslash does not seem to work.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ryanrpj** [comment]
BlockSuite v0.11.0 was released three weeks ago, and brings with it LaTeX support. Yay! toeverything/blocksuite#5909. However, AFFiNE v0.12.0 was released today, three weeks later, and, to my surprise, LaTeX support is still missing. Can anybody give us some update on this?

To give some context, I'm trying to use the same syntax documented on the supra mentioned PR: `$a=b^2$`.

Am I doing something wrong, or this feature hasn't made its way into AFFiNE yet?

**Comment by hwangdev97** [comment]
Yes, BlockSuite now supports basic inline styles, but it is a developer-oriented suite, whereas AFFiNE is a product designed for users.

I understand the demand for Latex, and its implementation in AFFiNE primarily involves two aspects:

1. Inline LaTex Styles: BlockSuite has already implemented basic inline styles. However, support for particularly complex styles might disrupt the standard layout, requiring future fixes.

2. Independent LaTex Block: We have not yet completed this feature. We aim for it to render independently as a block, with its own toolbar for control and the ability to be placed anywhere on the whiteboard after dragging.

We are aware of the significant interest in this feature and will prioritize it. We plan to introduce this functionality in the upcoming versions.

**Comment by notpaulmartin** [comment]
Any update on this?

**Comment by UyCode** [comment]
still does not support inline or block math equation rendering

**Comment by hwangdev97** [comment]
coming https://github.com/toeverything/blocksuite/pull/8177

**Comment by hwangdev97** [comment]
Finally, we can close this issue!  Welcome to download 0.17 and experience the Latex functionality. If you have any questions, feel free to continue raising issues or join our Discord for discussion.

About affine 0.17: https://x.com/AFFiNEOfficial/status/1837058105642996094
Discord: https://discord.gg/uFJXQcwE

**Comment by aruiplex** [comment]
Hi @hwangdev97, thank you very much for adding the math equation rendering. 

I want to know if it is possible to directly render the contents between `$...$` and `$$...$$` into an equation. Now I need to enter `$$` followed by a space, and then click the Equation button to enter the formula. However, this operation is not friendly to copy and paste.

<img width="356" alt="image" src="https://github.com/user-attachments/assets/e58a5054-df8a-4aa5-8c04-816c41cb34cd">

**Comment by IveTian** [comment]
> Hi @hwangdev97, thank you very much for adding the math equation rendering.
> 
> I want to know if it is possible to directly render the contents between `$...$` and `$$...$$` into an equation. Now I need to enter `$$` followed by a space, and then click the Equation button to enter the formula. However, this operation is not friendly to copy and paste.
> 
> <img alt="image" width="356" src="https://private-user-images.githubusercontent.com/40193711/369705756-e58a5054-df8a-4aa5-8c04-816c41cb34cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODg5MjUsIm5iZiI6MTcyNzA4ODYyNSwicGF0aCI6Ii80MDE5MzcxMS8zNjk3MDU3NTYtZTU4YTUwNTQtZGY4YS00YWE1LThjMDQtODE2YzQxY2IzNGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDEwNTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMzNiMzRjODBjODRhMzA5OTFjMTlkNjEwNmNlMjFmMzgxYzY5NzRhMTk2Y2NjNjc3OTliZmI0MmI5MWRhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iagWnFmf3xsNaLIG6I-oM9-XSWmmFFibmHHWvcz7hh0">

Hi there, thanks for you asking the question.
Due to trade-off considerations, we haven't included this feature in the current version. However, we've noted your request and greatly appreciate your feedback.
If you have more thoughts to share with us, we welcome you to join our [Discord community](https://discord.gg/whd5mjYqVw) for further discussion and feedback.

**Comment by GauravChambhare** [comment]
Hi @IveTian ,  

> Due to trade-off considerations, we haven't included this feature in the current version. However, we've noted your request and greatly appreciate your feedback.

Do you have any updates on this?  For me personally, this has been the wait for this feature, along with the ability to search/filter in collections for affine. I appreciate the work you and your team have put into Affine. :)

**Comment by sightseeer** [comment]
Thinking of switching to Affine but sadly, I mandatorily need Latex support.
