### ISSUE TITLE
Auto focus the delete confirm button

### ISSUE THREAD

**Issue by golok727** [toeverything/AFFiNE#5813]
### Description

It would be better if the delete button in the confirmation modal is autoFocussed so that I can use the enter key instead of clicking the button to delete

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by dev19Aman** [comment]
in which file is the confirm button located?

**Comment by golok727** [comment]
> in which file is the confirm button located?

After taking a look at the code, it seems that the dialog from radix ui uses the enter key to close the modal instead of confirming it.

https://github.com/toeverything/AFFiNE/blob/282b788258ae6f3699cd82a751aeda182fd8cc3d/packages/frontend/component/src/ui/modal/confirm-modal.tsx#L16

https://www.radix-ui.com/primitives/docs/components/dialog#keyboard-interactions

**Comment by pengx17** [comment]
Not sure about this UX. What do you think @hwangdev97 ?

**Comment by RevanthS5** [comment]
Hi If this issue is still open , can I start working on it?

**Comment by hwangdev97** [comment]
lgtm 🤔
