### ISSUE TITLE
Can't copy and paste into table

### ISSUE THREAD

**Issue by EnterMan123** [toeverything/AFFiNE#5814]
### What happened?

I used the keyboard Ctrl+A to select a paragraph of text elsewhere, and then Ctrl+C to copy it. When I returned to Affine, I couldn't paste it into the table. Then nothing can be entered in the title bar and text field of the row.

After waiting for several months, it still has not been fixed. This is a bug that greatly affects the use, so please fix it as soon as possible.

I have this problem on both the desktop version and the web version of windows 11.

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Other

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EnterMan123** [comment]
If you perform the operation I described on a title bar or text bar with content, the existing text will disappear immediately.

**Comment by EnterMan123** [comment]
bug show: https://www.youtube.com/watch?v=OUC7w7SJO9w

**Comment by EYHN** [comment]
The fix will be included in next release
