### ISSUE TITLE
Allow magnification in notes

### ISSUE THREAD

**Issue by TanmayChhatbar** [toeverything/AFFiNE#5823]
### Description

Allow magnification of the page with Ctrl+Scroll.

### Use case

I use a 32in monitor with a 13in laptop. Most use is on the 32in monitor. When I drag the Affine window to the 13in laptop, the text is far too small to be comfortable for reading.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
You can use `ctrl` + `plus(+)` or `minus(-)` to zoom the application

**Comment by TanmayChhatbar** [comment]
I tried again and observed the following.
- The Numpad shortcuts don't work for me, 
- The symbols over the number row work. 

It is interesting, as I expected these keys to register the same. 
I tried two keyboards, Corsair K55 and Logitech K850. Same response on both. My issue has been solved, but I'd still love to get the Numpad keys working if that's not much effort on your end. Thanks.

**Comment by EYHN** [comment]
Sorry I don't currently have a keyboard with numpad.

@pengx17 can you help me look at this?

**Comment by EYHN** [comment]
The zoom shortcut key issue is controlled by `electron`. There's not much we can do, so I'd like to close this issue first.
