### ISSUE TITLE
Allow Embedding the shared URL to other sites.​

### ISSUE THREAD

**Issue by Mic-360** [toeverything/AFFiNE#5826]
### Description

Using the public URL provided by AFFine to be used with html's iFrame Element.
```html
<iframe src="https://insider.affine.pro/share/<user-ID i think it is.>/<some-ID>" width="25%" height="50vh">
</iframe>
```

### Use case

Can be used as a element into a blog site. Where collaborator who have access to that can change things  add their own block in edgeless mode with that edit button.

### Anything else?

Shared URL has restrictions on Zoom-out but no restrictions in Zoom-in.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by darkskygit** [comment]
There are currently no plans to allow embedding editable interfaces in the form of iframes.
In the future, it may be possible to support referencing blocks on external pages through APIs or in a more lightweight way.
