### ISSUE TITLE
​Selfhosted version out of date

### ISSUE THREAD

**Issue by vince-vibin** [toeverything/AFFiNE#5827]
### Description

In the ReadMe it states a that the selfhosted version is lacking features.
As far as i can see there the last release is from around one year ago. Also the part in the ReadMe saying that it is outdated is around 6 months old.

Because the main drawback of the cloud version is that there is data collection which is not done in the selfhosted version. Which is stated in this issue #5759. Especially in a notes taking app where privacy is a really important factor for a lot of people when choosing an app.

The question is, is there a roadmap or a list of features lacking from the selfhosted version. It would be nice to have more clarity about these things than just saying you are working on it when there has not been a release in the six months this was written in the ReadMe.

### Use case

This would help people choose an exact version they want to use.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by fourdim** [comment]
Dup of #5069 (Self host progress), #5759 (telemetry).
