### ISSUE TITLE
​Copy and paste from code block without extra characters added by affine

### ISSUE THREAD

**Issue by victorburgos12** [toeverything/AFFiNE#5829]
### Description

Hello, I normally put shell commands into affine for future reference, I then copy and paste the commands to shell sessions.
I have a problem because affine adds extra characters to the command and that breaks the command.
Here is the line I want to paste somewhere else from affine:
``` Plain&#x20;Text
apt-get install curl gnupg lsb-release
```
I get this when I paste into my shell session, extra lines that break everything.
![image](https://github.com/toeverything/AFFiNE/assets/37320468/e5558874-b603-407c-b14c-d30c7e85f5e2)

How can I copy and paste only the text that I have selected?
Thanks for your help.

Note: I am using affine code blocks.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
Thanks for bringing this to our attention. We appreciate your patience and contribution towards improving AFFiNE.

I'm happy to inform you that we've addressed this issue and the fix will be part of our upcoming release. Please keep an eye on our release notes for further updates.

Once again, thanks for your involvement in making AFFiNE better. Feel free to report any other issues you may encounter.

**Comment by EYHN** [comment]
I will leave this issue until the new version is released

**Comment by victorburgos12** [comment]
Hello [JimmFly](https://github.com/JimmFly), I will be checking the next release.
Thanks for your help, I am testing AFFiNE after moving from mediawiki to thebrain, then MindMeister, and then to freeplane.
Different solutions for different needs, so far AFFiNE seem very promising for my needs of very fast note-taking during meetings and daily tasks.

**Comment by EYHN** [comment]
@victorburgos12 

By the way, you can experience the new version at https://insider.affine.pro (you can also download the beta version from the official website)
