### ISSUE TITLE
BUG: Sidebar texts can be selected.​

### ISSUE THREAD

**Issue by qpomelo** [toeverything/AFFiNE#5846]
### What happened?

<img width="360" alt="affine 0.12.0-canary.1" src="https://github.com/toeverything/AFFiNE/assets/35286331/009530d2-a1ae-403f-83fc-ee6e68124c64">
<img width="352" alt="affine stable 0.11.3" src="https://github.com/toeverything/AFFiNE/assets/35286331/b7c235fe-692a-4f33-979f-c7e1181c23fa">

This bug exists in both 0.12.0-canary.1 and latest stable version. 

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
fixed in 0.12.0
