### ISSUE TITLE
在无边界中切割和新建重合时，切割不能响应。

### ISSUE THREAD

**Issue by vankeoa** [toeverything/AFFiNE#5847]
### Description

在无界模式中切割和新建重合时，切割不能响应。

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
In the latest beta version, we have redesigned the cutting tool.

You can download the beta version to try it out, or wait for the stable version.

**Comment by vankeoa** [comment]
谢谢你的回复，软件后续会对中文进行梳理吧


    TRANSLATE with  x
    English    ArabicHebrewPolish 
 BulgarianHindiPortuguese 
 CatalanHmong DawRomanian 
 Chinese SimplifiedHungarianRussian 
 Chinese TraditionalIndonesianSlovak 
 CzechItalianSlovenian 
 DanishJapaneseSpanish 
 DutchKlingonSwedish 
 EnglishKoreanThai 
 EstonianLatvianTurkish 
 FinnishLithuanianUkrainian 
 FrenchMalayUrdu 
 GermanMalteseVietnamese 
 GreekNorwegianWelsh 
 Haitian CreolePersian 
   



 
         
   
 
  TRANSLATE with 
    COPY THE URL BELOW  
      
     Back 
    
   EMBED THE SNIPPET BELOW IN YOUR SITE   
  

 Enable collaborative features and customize widget: Bing Webmaster Portal
 Back
 
 ORIGINAL: "; langMenu.appendChild(origLangDiv); LanguageMenu.Init('LanguageMenu', LanguageMenu_keys, LanguageMenu_values, LanguageMenu_callback, LanguageMenu_popupid); window["LanguageMenu"] = LanguageMenu; clearInterval(intervalId); } }, 1);  
&nbsp;


张志祥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月21日(星期三) 凌晨1:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [toeverything/AFFiNE] 在无边界中切割和新建重合时，切割不能响应。 (Issue #5847)






在最新的测试版中，我们重新设计了切割工具。

你可以下载测试版试用，或者等待稳定版。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了线程。消息ID:<每一件事/每一个问题/ 5847 / ***@***.***和&gt;
