### ISSUE TITLE
[feature request]Want to transfer articles between workspaces by dragging with the mouse

### ISSUE THREAD

**Issue by wold9168** [toeverything/AFFiNE#5860]
### Description

I hope to be able to transfer articles between workspaces by dragging with the mouse.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
Based on the current design, this is unlikely to be implemented, as the isolation between workspaces is very deep.

However, I will pass this suggestion on to our product team for discussion.

**Comment by EYHN** [comment]
We will not implement this feature in the short term, so I will close this issue first.
