### ISSUE TITLE
[feature request]​ A dedicated UI is needed to manage tags

### ISSUE THREAD

**Issue by wold9168** [toeverything/AFFiNE#5861]
### Description

A dedicated UI is needed to manage tags so that we can operate tags in batches, including delete, rename, attach tags to article.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
I can summarize the current place where you can manage your tags.

When adding a tag in a page, you can manage all the tags:

![CleanShot 2024-02-22 at 10 49 01@2x](https://github.com/toeverything/AFFiNE/assets/13579374/cf3e604d-f080-424a-b805-3922d9198f8c)

In our upcoming new version (0.12.0), we will have a dedicated all-tag page to display all your tags, but currently, it is not possible to rename tags. I think we will improve this.

![CleanShot 2024-02-22 at 10 56 28@2x](https://github.com/toeverything/AFFiNE/assets/13579374/a0e7077f-fe83-4e94-a58d-24724a1613e5)

you can try this on [insider.affine.pro](https://insider.affine.pro)
