### ISSUE TITLE
​Can't invite collaborator

### ISSUE THREAD

**Issue by johannesCmayer** [toeverything/AFFiNE#5878]
### What happened?

I invited somebody to a workspace, and then they could not join. When they opened the workspace it said that it was not accessible to them. The same happened when they created a workspace and invited me. However, when I pressed to go back to my files, I could click on the workspace button in the top left and select the workspace they invited me to. However, I would like to be the owner, because in case we have more than 3 collaborators which would definitely happen if we evaluate affine to be good, then I would need to be the person that pays.

I am in Germany and they are in the United Arab Emirates in case that is important (maybe there is some region blocking?)

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

```shell
I can't really provide a log right now because the other person is now offline, and I can now work their workspace without problem.
```

### Anything else?

https://app.affine.pro/workspace/b903f024-84eb-45d2-af13-e89c21e870a2/all
This is the workspace that the other person could not join. It does not contain any files but the default files so it is totally fine for you to look at it, or look at the logs or something.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Brooooooklyn** [comment]
> maybe there is some region blocking?

We don't have any region blocking logic right now; we will check if there are any issues related to the invitation.

**Comment by JimmFly** [comment]
We have released a new version. Does this issue still exist in this version?
