### ISSUE TITLE
​Running error (forgot specific information), mistakenly deleting software

### ISSUE THREAD

**Issue by MaxHang** [toeverything/AFFiNE#5880]
### What happened?

On February 21, 2024, at 16:33 Beijing time, a software error occurred while running the computer. Subsequently, many software (such as git and anaconda) were deleted from the computer (presumably due to this, as the folder where these software are located was modified at 16:33)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Brooooooklyn** [comment]
@MaxHang We do not have any codes to ***delete files within the App folder that do not belong to us***. I believe your issue is not related to our app.

**Comment by fourdim** [comment]
You are welcomed to review codes by searching the word `fs` via the GitHub code search.
https://github.com/search?q=repo%3Atoeverything%2FAFFiNE+fs+path%3Apackages%2Ffrontend%2Felectron&type=code
There are 17 files available and there should be far more less when you exclude test files and scripts.
In addition to that, all releases are produced by GitHub actions automatically and we cannot introduce any codes during this compilation process.
