### ISSUE TITLE
arm64 macos distribution is not codesigned​

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#5898]
### What happened?

```shell
codesign -v -v ./affine-canary-macos-arm64.dmg
./affine-canary-macos-arm64.dmg: code object is not signed at all
```

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
Thanks. It should be fixed in #5921
<img width="612" alt="image" src="https://github.com/toeverything/AFFiNE/assets/584378/767e53b4-2f85-4b9d-8997-237520af3e1f">
