### ISSUE TITLE
Allow other pages or edgeless to be added in egdeless mode​

### ISSUE THREAD

**Issue by curlykay** [toeverything/AFFiNE#5907]
### Description

In Obsidian's canvas there is a built-in option to add other notes, and the added notes can be edited in real time in the canvas.
Although edgeless is more of an alternative way of presenting pages in Affine, it's very natural for me to want to add other completed pages or even edgeless when using edgeless.

Currently I can only add other pages using `@link` in edgeless first and then use card view mode to display them, but pages added using `@link` in edgeless cannot be edited in real time，or even jumped (which may be another issue)，It feels a little less "egdeless".

So is it possible to add other pages or edgeless in edgeless, and edit and jump to them freely in edgeless?

Maybe my ideas are at odds with your design concepts, but I think I'll gladly accept them - after all, you've done a fantastic job and I'd love to hear your ideas.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
This is a great idea, in fact, we've already conducted some experiments in blocksuite. You will be able to embed other documents (either in whole or specific blocks) in paga or edgeless mode, and also support editing the embedded documents. However, since the interaction of embedded blocks is not yet complete, it is currently disabled in affine. We expect to launch these features in version 0.13.0.

You can try it here now:

https://try-blocksuite.vercel.app/starter/?init=synced

**Comment by EYHN** [comment]
https://github.com/toeverything/AFFiNE/assets/13579374/4c5f9309-97aa-4672-a275-56ff847da902

**Comment by curlykay** [comment]
Just returned from the experience and well, you guys absolutely nailed it, the inspiration resonates so wonderfully.
I have every confidence that you guys have been eating your own dog food and have no doubt imagined more about Affine than I have.
You guys are creating great work, thank you for all you do.

**Comment by curlykay** [comment]
There is a hint of unnaturalness in my experience with https://try-blocksuite.vercel.app/starter/?init=synced:
After jumping from note A (edgeless mode) to another page or edgeless (note B), if I want to go back to the original note A, I need to switch note B to page mode, and then return to note A from Backlinks.
So in edgeless mode, it might be a better UX if it also shows jumpable Backlinks.

**Comment by EYHN** [comment]
In v0.15.0 we will mainly focus on implementing this
