### ISSUE TITLE
Integration of Spaced Repetition System

### ISSUE THREAD

**Issue by Hopy-Jaden** [toeverything/AFFiNE#5915]
### Description

Currently, Affine can switch between a linear-note system and an infinite-canvas system. However, sometimes when learning some very intricate knowledge, the spaced repetition system kicks in and really helps a lot. 
Meanwhile, the infinite-canvas system is good for building networks for a big-picture of concept, it would be great if it could also integrate with a spaced repetition system.

### Use case

A common form of spaced repetition system is flashcards. For example, in the top bar where you can switch between linear notes and infinite canva, perhaps there may be an addition of a button to switch to a spaced repetition system, having flashcards that belong to that page and its subpages. This can access users from time to time and prevent users from forgetting knowledge. 
Perhaps infinite canvas can also integrate with a spaced repetition system, which can build relationships and connect the flashcards.

### Anything else?

Anki is a common spaced repetition platform, targeting flattening forgetting curves with algorithms: https://apps.ankiweb.net/
Besides, there is another platform that integrates with Notion and turn notion notes into flashcards, which I guess is a good reference for building a spaced repetition system in affine: https://zorbi.com/

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
I think this "Spaced Repetition System" deviates from Affine's main function (document writing).

Perhaps we could implement this through a plugin in the future, but a plugin system is not in our short-term plan, so I will close this issue for now.

**Comment by linonetwo** [comment]
> but a plugin system is not in our short-term plan

Really? I'm always looking forward to it, and search for this today.
