### ISSUE TITLE
After switching page mode to edgeless mode, the jump option for clicking on the `@` link does not work.

### ISSUE THREAD

**Issue by curlykay** [toeverything/AFFiNE#5918]
### What happened?

The web version has the same problem，but there is no such problem in the try-blocksuite web page.

version: 0.12.0

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
I can add a reproduction video:

https://github.com/toeverything/AFFiNE/assets/13579374/8005f527-ab2a-4613-a631-5f60f103637b

**Comment by Abdurrafey-Siddiqui** [comment]
Same issue with me, windows

**Comment by forehalo** [comment]
fixed in 0.16.0
