### ISSUE TITLE
​客户端登录

### ISSUE THREAD

**Issue by oliverwu-cn** [toeverything/AFFiNE#5919]
### Description

请问AFFiNE 是否支持win/mac 客户端登录 self-host docker 版本服务？

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
It is already planned for the next major release.

**Comment by oliverwu-cn** [comment]
Haha, is there any ETA for the next major release ? I just tried current local version, it is very good !!!

**Comment by forehalo** [comment]
close duplicated #2646
