### ISSUE TITLE
在无界里进行连接后如果移动其中一个，连接线不是绑定的跟随。

### ISSUE THREAD

**Issue by vankeoa** [toeverything/AFFiNE#5937]
### Description

！[上传截屏2024-02-28 11.52.09.png...]()
在无界里进行连接后如果移动其中一个，连接线不是绑定的跟随。

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
```[tasklist]
### Tasks
```

**Comment by EYHN** [comment]
能否提供一个录屏

**Comment by vankeoa** [comment]
这个是录屏内容


张志祥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "toeverything/AFFiNE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月28日(星期三) 中午1:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [toeverything/AFFiNE] 在无界里进行连接后如果移动其中一个，连接线不是绑定的跟随。 (Issue #5937)





 
能否提供一个录屏

**Comment by EYHN** [comment]
Github 上看不到你的视频和图片

**Comment by vankeoa** [comment]
Uploading 2024-02-28_13-53-14.mp4…

**Comment by vankeoa** [comment]
有了吗

**Comment by vankeoa** [comment]
邮件里发给你了&nbsp;


张志祥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "toeverything/AFFiNE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月28日(星期三) 下午2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [toeverything/AFFiNE] 在无界里进行连接后如果移动其中一个，连接线不是绑定的跟随。 (Issue #5937)





 
Github 上看不到你的视频和图片

**Comment by forehalo** [comment]
BTW which client version you are using or you are on `app.affine.pro`

**Comment by vankeoa** [comment]
0.12.0


张志祥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "toeverything/AFFiNE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月28日(星期三) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [toeverything/AFFiNE] 在无界里进行连接后如果移动其中一个，连接线不是绑定的跟随。 (Issue #5937)





 
BTW which client version you are using or you are on app.affine.pro

**Comment by EYHN** [comment]
没收到你的视频,也无法复现

**Comment by vankeoa** [comment]
https://github.com/toeverything/AFFiNE/assets/116714294/1cb1f909-6541-43fd-82f0-f7acc093caa6


Uploading 2024-02-28_13-53-14.mp4…

**Comment by vankeoa** [comment]
看看到了吧

**Comment by vankeoa** [comment]
发了你再看看应该是有了&nbsp;




张志祥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "toeverything/AFFiNE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月28日(星期三) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [toeverything/AFFiNE] 在无界里进行连接后如果移动其中一个，连接线不是绑定的跟随。 (Issue #5937)





 
没收到你的视频,也无法复现

**Comment by vankeoa** [comment]
升级到0.12.1了也是这样的情况。

**Comment by EYHN** [comment]
I have received your screen recording and successfully reproduced the issue. We will fix it ASAP.

**Comment by JimmFly** [comment]
Thank you ever so much for your feedback, we've rectified the issue in the latest version, please do update your client.
