### ISSUE TITLE
​Can not copy

### ISSUE THREAD

**Issue by mcgradycchen** [toeverything/AFFiNE#5944]
### What happened?

I'm deploy a selfhosted affine with affine-graphql:stable-6ed5ec3, and access with Chrome.
Everything is working except copy content from affine. Both ctrl+c and copy button in the page are not working.

![image](https://github.com/toeverything/AFFiNE/assets/3260884/a55004e5-887d-4912-be40-b30b3e32a29c)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mcgradycchen** [comment]
Update
Ctrl+C to copy page title text is working.

**Comment by mcgradycchen** [comment]
Update

The error message in developer console

TypeError: Cannot read properties of undefined (reading 'write')
    at a.writeToClipboard (index.js:169:35)
    at async a.copySlice (index.js:106:13)

**Comment by EYHN** [comment]
The error message was helpful and we will investigate the issue.

**Comment by EYHN** [comment]
It seems that we cannot write to your clipboard because of the non-https environment.

**Comment by mcgradycchen** [comment]
> It seems that we cannot write to your clipboard because of the non-https environment.

@EYHN  yes, it is http environment. Is it a must to enable https ?

**Comment by mcgradycchen** [comment]
https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined
OK, by the above link, it looks like I have to enable https. 

@EYHN  thanks
