### ISSUE TITLE
Connect to self-hosted server in desktop client​

### ISSUE THREAD

**Issue by arno4000** [toeverything/AFFiNE#5948]
### Description

Add the ability to connect to a self-hosted server using the desktop client. What is the purpose of having a desktop client if it only can be used with the cloud or locally?

### Use case

For users who want to have control over their data and use the desktop client.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
In the future, desktop clients will support connecting to selfhost servers.

This requires some work and I can't give you a specific time, but it may be included in our next major release.

**Comment by EYHN** [comment]
duplicate with #2646
