### ISSUE TITLE
How to create a new account on self-hosted affine ​

### ISSUE THREAD

**Issue by StudyingLover** [toeverything/AFFiNE#5957]
### What happened?

I deploy a affine bu docker, and login in by admin user acoount. Now I want to create a new account to my co-worder, but I didn't find how to create a new account. What should I do?

### Distribution version

Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
Currently the only way to register a new user is by sending magic link through email if configured.

We do provide a GraphQL mutation to sign up but the UI is not implemented yet. 

So if it won't bother you, you may open `http://your-host-of-affine.com/graphql`, the GraphQL playground and manually call the api:

![image](https://github.com/toeverything/AFFiNE/assets/8281226/5940e355-bbd3-48c6-956b-43225c5a4cde)

**Comment by StudyingLover** [comment]
oooo! Can you paste the code for create new account in your picture? 
btw, what is magic link, how to configure it?

**Comment by forehalo** [comment]
@StudyingLover 
```graphql
mutation {
  signUp(email: "YOUR_EMAIL_ADDRESS", name: "NAME", password: "PASSOWRD" {
    id
  }
}
```

**Comment by Gromochan** [comment]
Did something change? 
![firefox_2024-09-06_10-30-32](https://github.com/user-attachments/assets/91c79832-eae9-4799-bcde-cf96efa84294)

**Comment by Pawel-Bedn4rczyk** [comment]
I had the same issue. I coudn't create admin user through web UI  and with that graphql mutation. 
But I solved that by creating admin user in database table affine>users ;)
