### ISSUE TITLE
Journals create time error​

### ISSUE THREAD

**Issue by StudyingLover** [toeverything/AFFiNE#5958]
### What happened?

Journals create time error, I create it on 14:24, but the app shows that the create time is 00:00

![image](https://github.com/toeverything/AFFiNE/assets/68844494/5112df5b-9fac-449d-962a-93aa0d72d9a1)

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
I think this is by design, when creating a journal we will set the journal creation time to the corresponding date

**Comment by CatsJuice** [comment]
> I think this is by design, when creating a journal we will set the journal creation time to the corresponding date

Yeah, maybe it's better to modify date only

**Comment by azoller1** [comment]
My issue may be different, but the date on the journals page created (title) is not the correct date listed versus the calendar bar:

![Screenshot 2024-03-01 131419](https://github.com/toeverything/AFFiNE/assets/2552829/2ade7eaf-945a-415a-89cf-efff7abc3a4d)

Feb 29th is the incorrect date for the actual day. March 1st listed in the top bar is the correct actual date.

Using web version and self-hosted sync server.

Version 0.12.2-stable and editor version says: 0.12.0-canary-202402220729-0868ac6

**Comment by forehalo** [comment]
This is a confirmed issue and has already been fixed. Please wait for the next patch release.
