### ISSUE TITLE
​AFFiNE is unavailable when the network is offline.

### ISSUE THREAD

**Issue by L-Sun** [toeverything/AFFiNE#5959]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/20479050/ecb156e6-eeb9-4800-b997-098879600bee)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Brooooooklyn** [comment]
We are working on fixing this issue in https://github.com/toeverything/AFFiNE/pull/5895

**Comment by EYHN** [comment]
We will implement this as a high priority goal in 0.14.0 👏

**Comment by EYHN** [comment]
AFFiNE is completely available offline
