### ISSUE TITLE
[improvement]:  Please Add Unit Testing React Components and Typescript

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#596]
### 1~3 main use cases of the proposed improvement

Please Add Unit Testing React Components and Typescript

Unit tests are very low level and close to the source of an application. They consist in testing individual methods and functions of the classes, components, or modules used by your software. Unit tests are generally quite cheap to automate and can run very quickly by a continuous integration server.

For exmaple, `npx jest` -> `packages/app/src/utils/__tests__/get-is-mobile.spec.ts`

**Comment by teobler** [comment]
not sure if AFFiNE already has a internal test strategy like:
- what kind of functionality should be cover by unit test / component test
- what kind of functionality should be cover by integration test / e2e test
- should we use UI test to protect UI change
- ...
