### ISSUE TITLE
​Right side menu is triggered as unexpected in table view

### ISSUE THREAD

**Issue by zkwolf** [toeverything/AFFiNE#5969]
### What happened?

Step to reproduce:

1. new a table view
2. cursor to title line after Task 1
3. `tab` two times
4. the page is pushed to left

![image](https://github.com/toeverything/AFFiNE/assets/8555127/1d1136f8-d2d5-4ac5-82eb-9f17b93cdd97)
![image](https://github.com/toeverything/AFFiNE/assets/8555127/cd7267cd-b475-4526-89b0-5403c69439f2)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
should be fixed in https://github.com/toeverything/AFFiNE/pull/5971

**Comment by zkwolf** [comment]
I think there are some more problems here.

1. table view is not allowed to use `tab` to move selection in editing mode.
2. when type `tab` in title cell, it is lost the cursor (I think it's unexpected behavior).
3. when type next `tab`, it will find the focus area from page header.

**Comment by EYHN** [comment]
Let’s focus on the sidebar in this issue.

As for the keyboard navigation issues you mentioned, as far as I know there are many more. and it is best to optimize these issues uniformly when we have time.

We currently do not have enough manpower to focus on all aspects.
