### ISSUE TITLE
Self-hosted sync problem

### ISSUE THREAD

**Issue by LIHAQ** [toeverything/AFFiNE#5972]
### What happened?

I used docker to build a self-hosted service, and I created an account, but when I created a note and tried to sync it in another browser, the following error occurred.
![image](https://github.com/toeverything/AFFiNE/assets/57976650/26174bd2-e7c5-48a4-9e64-3bc0356f22cb)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
Have you enabled any browser extensions?

**Comment by LIHAQ** [comment]
> Have you enabled any browser extensions?

I only use some of the browser extensions I need for my work, and I don't use the rest

**Comment by EYHN** [comment]
I can't reproduce this issue. After searching for the error message, it seems that enabling extensions such as Google Translate may cause this error.

Can you record a screen recording to reproduce this issue?

**Comment by LIHAQ** [comment]
> I can't reproduce this issue. After searching for the error message, it seems that enabling extensions such as Google Translate may cause this error.
> 
> Can you record a screen recording to reproduce this issue?

I have solved this problem, it is the translation function of the browser.
But I also ran into another problem, if I used the nginx agent, it would always show sync, but there was no sync.

**Comment by EYHN** [comment]
pls checkout this issue https://github.com/toeverything/AFFiNE/issues/5993 , may help you. 

If you still have problems, please open an new issue.

**Comment by LIHAQ** [comment]
> pls checkout this issue #5993 , may help you.
> 
> If you still have problems, please open an new issue.

It's settled
