### ISSUE TITLE
Self-hosted upload and storage limit​

### ISSUE THREAD

**Issue by baldemar-wuda** [toeverything/AFFiNE#5978]
### What happened?

![SCR-20240301-ifft](https://github.com/toeverything/AFFiNE/assets/61502547/1c469b76-4591-4ef2-b292-89a1f48b572e)

Are these limits about to change in self-hosted version? 

### Distribution version

Web (app.affine.pro)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
selfhost should have unlimited storage.

I haven't tested it yet, but if you encounter storage size limitations it should be a bug and you can open an issue.
