### ISSUE TITLE
​link between image will disappear after AFFINE reopen

### ISSUE THREAD

**Issue by greedyhao** [toeverything/AFFiNE#5980]
### What happened?

As shown in the figure

![丢失数据](https://github.com/toeverything/AFFiNE/assets/25771942/386e4f9d-4f58-40c9-9c56-c49611a78a14)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by HananoshikaYomaru** [comment]
This bug is probably related to #5937 , the link is still there, it just disappear. If you drag the linked node, the link will appear again. But this bug makes user think that the link is gone and make they accidentally create another links.

**Comment by EYHN** [comment]
I have checked this issue has been fixed in latest beta version, https://github.com/toeverything/AFFiNE/releases/tag/v0.13.0-beta.0

We will release stable version in next few days.
