### ISSUE TITLE
Sync with Self-hosted Affine Docker instance​

### ISSUE THREAD

**Issue by justin13888** [toeverything/AFFiNE#5984]
### Description

At time of writing, Affine feels great to use on the browser and I wanted to use the Affine application (specifically the Windows and Linux versions) on a self-hosted Affine instance via Docker! However, such a feature doesn't seem to exist or isn't apparent.

Is this a planned feature? Have I missed it?

### Use case

Anybody interested in using Affine with self-hosted instance

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
duplicate #2646
