### ISSUE TITLE
Page often loses mouse focus

### ISSUE THREAD

**Issue by aliuq** [toeverything/AFFiNE#5990]
### What happened?

The github link address was added, then deleted, and then lost focus. 

https://github.com/toeverything/AFFiNE/assets/11707934/d43af173-f959-4b06-b525-a4fec618ffae

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Anything else?

Can you add a shortcut key to manually gain focus on the page

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
I think the situation is that you deleted all the "paragraphs" in the document. You can create a new paragraph by clicking on the page title and pressing enter.

**Comment by EYHN** [comment]
Our next version we will support clicking on a blank space and create a new paragraph, so this issue should not occur.

https://github.com/toeverything/AFFiNE/pull/5869
