### ISSUE TITLE
Please allow shared documents content be copying

### ISSUE THREAD

**Issue by aliuq** [toeverything/AFFiNE#5992]
### Description

Hi, shared documents should allow content to be copied which friendly

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
I confirm this is a bug and we will fix it as soon as possible.

**Comment by JimmFly** [comment]
AFFiNE has released their latest version - does this issue still persist?

**Comment by EYHN** [comment]
Looks like it's been fixed in the latest version
