### ISSUE TITLE
​Support for Mermaid.js Integration

### ISSUE THREAD

**Issue by Adek06** [toeverything/AFFiNE#5999]
### Description

The current editor lacks integration support for Mermaid.js, causing inconvenience when editing and rendering Mermaid.js charts. Mermaid.js is a popular JavaScript charting library used for creating flowcharts, sequence diagrams, Gantt charts, and more.

### Use case

Consider a scenario where a software development team is using the editor for documenting architectural designs. The team often includes Mermaid.js charts to illustrate complex workflows and system interactions. With native Mermaid.js support in the editor, team members can easily integrate these charts directly into their documentation, streamlining the collaboration process and making it more accessible to team members.

**Comment by EYHN** [comment]
In the future, we will support it through plugins, but implementing a plugin system is not in our short-term plan. We will support plugins after the core features is stable. Please pay attention to our subsequent updates.

**Comment by cmdaltctr** [comment]
Hi, I think Affine is super awesome. I've tried Anytype for a long time, and when I use Affine, it just blew every other competitor to dust. Appreciate all the hard work. A plugin system is essential, allowing us, the users to create an ecosystem around Affine. This way, you don't have to develop all the plugins that come to mind.
