### ISSUE TITLE
Backlink in self-hosted version ​return 404

### ISSUE THREAD

**Issue by zkwolf** [toeverything/AFFiNE#6000]
### What happened?

Step to reproduce:
1. use `@` to add a new page
2. redirect to new page
3. click the backlink in new page

![image](https://github.com/toeverything/AFFiNE/assets/8555127/9f90e846-3b71-4177-b0fc-ea3ae6fb4b4f)

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
What does the 404 URL look like? Is it the correct path?

**Comment by zkwolf** [comment]
The link in backlink is correct, right click and open it in a new tab is normal. 

![GIF](https://github.com/toeverything/AFFiNE/assets/8555127/a26fe84a-a702-42d1-86b0-775399834263)

**Comment by EYHN** [comment]
Are you using the canary version? Please update your docker image, we recently fixed this issue.

**Comment by zkwolf** [comment]
@EYHN  Unfortunately, today I have updated the docker image to latest canary version but the bug is not fixed.
BTW, the project use `yarn dev` run `browser` mode can also reproduce this bug.

**Comment by EYHN** [comment]
will fixed by https://github.com/toeverything/AFFiNE/pull/6034
