### ISSUE TITLE
How do I change the file storage location for my work?​

### ISSUE THREAD

**Issue by kiradzS** [toeverything/AFFiNE#6006]
### Description

How do I change the file storage location for my work?​

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
If you use the desktop version, there is currently no way to change the document storage path.

But you can back up your documents by exporting the workspace.

![CleanShot 2024-03-05 at 15 27 08@2x](https://github.com/toeverything/AFFiNE/assets/13579374/b9b1b809-e45a-4992-ae44-bba6806cfde8)

**Comment by EYHN** [comment]
We will support changing the storage path in the future, but this is not in our short-term plan, so I will close this issue first and reopen it if you still have questions.
