### ISSUE TITLE
Self Hosted​ Avatar

### ISSUE THREAD

**Issue by ScaredyCat** [toeverything/AFFiNE#6008]
### What happened?

Uploaded a new user avatar which seemed successful (green success box in bottom right) however looking at the header in the Chrome inspector the web application is trying to load the avatar from localhost, http://localhost:3010/api/avatars/ so fails and falls back to the default first character of the user name.

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

```shell
Request URL:
http://localhost:3010/api/avatars/4cd5e48e-5660-4c0c-a43a-3aed65584376-avatar
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
Looks like is a bug, @forehalo  @darkskygit  pls take a look

**Comment by darkskygit** [comment]
cannot reproducible, can you provide a video record?

**Comment by EYHN** [comment]
@darkskygit avatarUrl stores a complete URL, which may be inconsistent with the user's actual server Url ?

**Comment by darkskygit** [comment]
just check the cloud, user `4cd5e48e-5660-4c0c-a43a-3aed65584376` not exists

**Comment by EYHN** [comment]
@darkskygit is selfhost

**Comment by forehalo** [comment]
the url consists of user provided domain, in other words, the url prefix of user avatar should be the same as `serverConfig.baseUrl`

**Comment by darkskygit** [comment]
please make sure your `AFFINE_SERVER_HOST` and `AFFINE_SERVER_PORT`(optional, set it if you not use 80 or 443) 
env has been setted

**Comment by ScaredyCat** [comment]
> cannot reproducible, can you provide a video record?

Avatar upload:



but it does work for Workspace icons

**Comment by ScaredyCat** [comment]
> please make sure your `AFFINE_SERVER_HOST` and `AFFINE_SERVER_PORT`(optional, set it if you not use 80 or 443) env has been setted

I can confirm after installing vi, copying the .env.example to .env and updating the AFFINE_SERVER_HOST line,  that uploading of avatars works.

In my defence the [documentation](https://docs.affine.pro/docs/self-host-affine) don't mention the .env file at all.

However the Workspace icon working without the change makes me think they should both work in the same manner.

**Comment by darkskygit** [comment]
the avatar sync method of workspace is different from that of account's icon, so it does not rely on `baseUrl`. I will update the corresponding documentation later.

**Comment by darkskygit** [comment]
i have updated the relevant docs, and you can also see other available env vars in the doc: https://docs.affine.pro/docs/self-host-affine/run-affine-with-custom-options

i will set this issues as completed.
if you encounter other problems, you are welcome to submit a new issue
