### ISSUE TITLE
📌 Overall Roadmap 202301 - Alpha "Downhills"

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#604]
We are mainly working on features for pathfinder.

* [x] #629
* [x] #630
* [ ] #631
* [x] #632 @lawvs 
* [ ] #633 @Himself65 
* [x] #608 @alt1o @darkskygit 
* [x] #609 @darkskygit @zuoxiaodong0815 
* [x] #610 @QiShaoXuan @darkskygit 
* [x] #611 @alt1o @SaikaSakura @darkskygit 
* [x] #612 @darkskygit  @alt1o @SaikaSakura 
* [x] #613 @alt1o @SaikaSakura 
* [x] #615 @QiShaoXuan @thorseraq 
* [x] #567 @JimmFly 
* [x] #708

**Comment by tzhangchi** [comment]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/5910926/212447544-9dc6b01b-c900-4e0a-af4f-acaa2c79c571.png">

**Comment by doodlewind** [comment]
Finished since we have [released Downhills](https://affine.pro/content/blog/downhills-release-announcement/index) 🎉
