### ISSUE TITLE
Mail ignoreTLS​

### ISSUE THREAD

**Issue by BL19** [toeverything/AFFiNE#6042]
### Description

I am hosting a mail server for myself and don't have a trusted certificate, thus I cannot send invite mails using the mail server. 

Would it be possible to add a `MAILER_IGNORETLS` that would ignore the TLS certificate of the mail server?

### Use case

This is a feature that can disable TLS verification and allow self-hosted mail servers.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
Use `MAILER_SECURE=false`

**Comment by Muyv** [comment]
@forehalo 

added this variable still not working, im not sure if it is the tls issue.

- `MAILER_SECURE=false` in `.env`
- `MAILER_SECURE=${MAILER_SECURE}` in `docker-compose.yml`

log:
```log
affine_selfhosted  | [Nest] 133  - 03/20/2024, 6:16:39 AM    WARN [WorkspaceResolver] failed to send 7c95efb3-d8c4-4aa9-8d94-ababbf771869 invite email to ****@***.***, but successfully revoked permission: Error: certificate has expired
```

**Comment by BL19** [comment]
When I'm using `MAILER_SECURE=false` I'm getting:
```
[WorkspaceResolver] failed to send 5fb3a2b6-491b-4d80-945e-1faa276d6a41 invite email to ***@***.net, but successfully revoked permission: Error: unable to verify the first certificate
```

I'm hosting the mailserver myself and I'm accessing it locally, I just want to ignore these issues so that I can use affine.

**Comment by psi-4ward** [comment]
This should be documented in https://docs.affine.pro/docs/self-host-affine/run-affine-with-custom-options
