### ISSUE TITLE
Journal date is off by one​

### ISSUE THREAD

**Issue by kherge** [toeverything/AFFiNE#6047]
### What happened?

1. Create a journal entry for today.
2. The page title is off by one.

# Examples

# Page View

<img width="1112" alt="Screenshot 2024-03-07 at 4 04 06 PM" src="https://github.com/toeverything/AFFiNE/assets/9122157/5a1ae0fb-ea16-4b85-a8c0-55eab3008302">

# All Pages View

<img width="1159" alt="Screenshot 2024-03-07 at 4 05 39 PM" src="https://github.com/toeverything/AFFiNE/assets/9122157/7acd489b-3299-4a6f-bd3c-8252e71291d6">

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
Already fixed in the latest beta version. You can download from here https://github.com/toeverything/AFFiNE/releases/tag/v0.13.0-beta.0

We will release a stable version in a few days.
