### ISSUE TITLE
Adding doc template when creating a new doc​

### ISSUE THREAD

**Issue by hkkmalinda** [toeverything/AFFiNE#6048]
### Description

Hi, 
It would be really nice if you could make AFFiNe automatically use a predefined template (by the user) for every doc when it was created. Also, it is better to create a template creation method too.

### Use case

Let's say for a journal doc I like to use a specific table so when creating a doc I need that table to be added on every doc. So if I can use a doc template with the creation of the doc that will be very easy. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hkkmalinda** [comment]
I think this feature is a good one to have in the app

**Comment by Arcadianer** [comment]
I agree. I use templates in other notes app all the time to provide a good structure in all of my blocks. Combine this with the new property system and you have a really powerful tool. 
This is also one of the showstopper points for me that prohibit me from fully switching over to this tool for my everyday work.
