### ISSUE TITLE
The Calendar Day in the Journal View Doesn't Correspond to the Date in the Journal Page​

### ISSUE THREAD

**Issue by vickalchev** [toeverything/AFFiNE#6050]
### What happened?

Please see that the date on the Journal Page is a day behind on the selected date selected in the calendar. 

<img width="1079" alt="image" src="https://github.com/toeverything/AFFiNE/assets/86238419/8ac2582d-acf0-448b-a69c-e2b1606f5302">

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
We have a fix in the beta version and we will release a stable version in a few days.

try beta: https://github.com/toeverything/AFFiNE/releases/tag/v0.13.0-beta.0

**Comment by CtheCondor** [comment]
What advice/direction do you have for implementing this on a self-hosted instance currently running "0.12.0-nightly-202403121527-49bead7" via the docker pull "ghcr.io/toeverything/affine-graphql:stable"

**Comment by EYHN** [comment]
It is recommended that you wait a few days and we will release 0.13.0 before 15th
