### ISSUE TITLE
Cannot change password on self-hosted affine installation​

### ISSUE THREAD

**Issue by arno4000** [toeverything/AFFiNE#6053]
### What happened?

I cannot change the password of my user on a self-hosted affine instance. I get the password reset link by mail, but when I click on the link and then type in a new password, I get an error message that I need to verify my email first. But I didn't find any way to do this.

The affine instance is self-hosted using the official docker compose.

![image](https://github.com/toeverything/AFFiNE/assets/50365065/88cfa8e9-5843-4359-8324-5fbe11879497)

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
pull the latest image, and the `verify email` button is in your profile setting page
