### ISSUE TITLE
Line cannot be saved

### ISSUE THREAD

**Issue by Lao-jun** [toeverything/AFFiNE#6055]
### What happened?

The lines between the boxes on the page may not be saved, including (Straight , Elbowed, Curve), there is a certain probability of disappearing. This will happen when saving to a self-hosted website. The same is true when using the live demo you provided. Refresh the page. , the lines disappear

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by Lao-jun** [comment]
I found that someone has already mentioned this issue before.

**Comment by EYHN** [comment]
duplicate https://github.com/toeverything/AFFiNE/issues/5980
