### ISSUE TITLE
​Self Hosted WorkSpace Avatar

### ISSUE THREAD

**Issue by iqiuzixuan** [toeverything/AFFiNE#6057]
### What happened?

The workspace avatar setting was unsuccessful. After uploading the file, you can request `blob: http://xxxx:3031/xxxxx`. I am using the chrome browser, and `AFFINE_SERVER_HOST` has been set in `env`.

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by JimmFly** [comment]
Hello, we are truly sorry to hear you've encountered this problem. I believe we can discuss this matter in this discussion thread.
https://github.com/toeverything/AFFiNE/discussions/5975

**Comment by EYHN** [comment]
There will be issue if you upload images without https.

**Comment by iqiuzixuan** [comment]
> There will be issue if you upload images without https.

Thank you, I set up `AFFINE_SERVER_HTTPS=true` and accessed my AFFiNE through the domain name successfully.
I have a suggestion: Can you obtain the requested url through the browser and quietly use the url as a standard? Would this be more flexible? In this way, it can be set normally even in the case of http and ip address.

**Comment by EYHN** [comment]
Unfortunately, this is not possible, affine needs to know the correct full url for many place.
