### ISSUE TITLE
Urgent Security Vulnerability Discovered: Unsecured GraphQL Access​

### ISSUE THREAD

**Issue by erfuuan** [toeverything/AFFiNE#6060]
Hello friends, today I discovered a security issue regarding this tool that could be serious. The GraphQL access is open, allowing hackers to create a new user account and perform malicious actions through GraphQL. Do you have any ideas for addressing this? For instance, you could secure the communication between backend and frontend by using token-based authentication.

**Comment by EYHN** [comment]
There are no security issues in exposing GraphQL itself, and sign up users need to verify via email.

**Comment by darkskygit** [comment]
hello, our production env(app.affine.pro) has been configured to check normal clients, and the self-hosted version is not suitable for exposure to the public network under the default configuration.

in the situation you mentioned, users need to pass Google account verification or email verification to successfully create a user. if you find other situations, please provide more information for us to troubleshoot
