### ISSUE TITLE
Custom font families

### ISSUE THREAD

**Issue by yjlin0224** [toeverything/AFFiNE#6092]
### Description

Please add a feature to allow change these css variables in settings UI to custom font families:
- `--affine-font-family`
- `--affine-font-serif-family`
- `--affine-font-mono-family`
- `--affine-font-sans-family`
- `--affine-font-number-family`
- `--affine-font-code-family`

### Use case

For example, it can let me to specify UI and sans font to Noto Sans CJK TC with fallback to Noto Sans, specify serif font to Noto Serif CJK TC with fallback to Noto Sans, specify mono and code font to Fira Code. It can make the UI render better Traditional Chinese characters and render code with ligatures.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hwangdev97** [comment]
We plan to add settings for custom fonts, but it will need to wait until a later iteration (version 0.15 or 0.16; currently we are preparing version 0.14) to provide support.

**Comment by yjlin0224** [comment]
I want to know why it has become unplanned, especially since it was previously mentioned that the plan might be implemented in version 0.15 or 0.16.

**Comment by KavinMK05** [comment]
Hey are there any updates regarding custom font families ?

**Comment by hwangdev97** [comment]
0.17 released, so you can download the latest version from affine.pro/download and try this feature by the following step:
![shot-2024-09-23-18 52 46@2x](https://github.com/user-attachments/assets/a2c4499f-61a0-4d1b-a8ed-5713b4a1baac)

**Comment by yjlin0224** [comment]
But this only allows for a single font selection; it doesn’t support inputting multiple fonts like CSS rules do, which provide fallback options when certain characters are not supported by a font. Additionally, it can only change the font for regular text blocks and cannot specify fonts for UI elements or code blocks. This does not meet the functional requirements I initially mentioned.

**Comment by eshack94** [comment]
I am also interested in this feature. Why was this closed? A custom font family per font type would be hugely beneficial.
