### ISSUE TITLE
Emails sent have a non-usable action button​

### ISSUE THREAD

**Issue by lancedouglas1** [toeverything/AFFiNE#6106]
### What happened?

I have self-hosting setup and running.  I was testing my email server settings by sending a password reset to from the admin account as well as inviting a user to a workspace.  Both emails were sent successfully but the button in both emails doesn't have a link "href" nor an "id" associated with their "a" tags, so they are really just for show. 

`<a style="font-size:15px;font-family:inter,Arial,Helvetica,sans-serif;font-weight:600;line-height:24px;color:#fff;text-decoration:none;border-radius:8px;padding:8px 18px;border:1px solid rgba(0,0,0,.1);display:inline-block;font-weight:bold">Set new password</a>`

`<a style="font-size:15px;font-family:inter,Arial,Helvetica,sans-serif;font-weight:600;line-height:24px;color:#fff;text-decoration:none;border-radius:8px;padding:8px 18px;border:1px solid rgba(0,0,0,.1);display:inline-block;font-weight:bold">Accept &amp; Join</a>`

I'm using gmail smtp and sending to gmail accounts.

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
No relevant logs.
```

**Comment by EYHN** [comment]
Duplicate with https://github.com/toeverything/AFFiNE/issues/6024

**Comment by lancedouglas1** [comment]
Thank you @EYHN .  I read #6024 previously and I don't believe it is a duplicate.  My issue is that there isn't a link at all, not that the link is invalid.  The HTML is invalid.  Can you review mine again and confirm that you believe it's a duplicate, please?

**Comment by EYHN** [comment]
oh sorry, it was my mistake, we will investigation this issue
