### ISSUE TITLE
Shortcut ⌥+S stands for "ś" in Polish

### ISSUE THREAD

**Issue by mokrafanka** [toeverything/AFFiNE#6108]
### What happened?

Hi, 

I really love your app, but I can't write properly in my language (Polish) because `⌥+s` shortcut makes letter "ś" (`⇧+⌥+s` big letter "Ś"). 

This shortcut switches between Edgeless and Page modes.

I beg you let me change the shortcut on my client because I'm tired of copying this letter every few sentences.

In Polish there are thousands of words with letter "ś".

We also have ć, ą, ż, ź, ń, ł, ó, ę, ł which are made with `⌥` button (just FYI).

Have a nice day and keep up the great work!

❤️ Sending love from Poland with one of the hardest languages:

Wszystkiego dobrego i miłego dnia! 

W Szczebrzeszynie chrząszcz brzmi w trzcinie! 

Stół z powyłamywanymi nogami.

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
Sorry for the bad experience, I really want to solve this issue, but custom shortcut keys require a lot of effort to implement, and we currently don't have the manpower to do this.

Perhaps a feasible approach would be to add a separate setting for ⌥+S to allow switching to another specific key.

**Comment by EYHN** [comment]
Maybe `ctrl + s` in macos, will it work?

**Comment by robinmoussu** [comment]
Hello, I’ve just hit the exact same issue. Any European layout will have issue with this shortcut. I think the easiest would be to change this shortcut to be command+option+s by default.
