### ISSUE TITLE
Can't login​ when upgrading to beta

### ISSUE THREAD

**Issue by patrick-men** [toeverything/AFFiNE#6120]
### What happened?

I'm running AFFiNE locally with docker compose, and when I changed the image from `stable` to `beta`, I couldn't log in anymore. There weren't any logs regarding authentication or anything alike. After reverting back to the `stable` image, i was directly logged back in.

I checked in the `affine_selfhost` container, and both `AFFINE_ADMIN_EMAIL` and `AFFINE_ADMIN_PASSWORD` are as defined in the docker compose file.

It is running on an 
- Ubuntu Server 22.04.3
- Docker 25.0.1
- Docker Compose v2.24.2

### Distribution version

Linux

### Are you self-hosting?

- [x] Yes

**Comment by RandomLegend** [comment]
I have the same issue on the stable tag as of right now.

**Comment by EYHN** [comment]
@RandomLegend  If you are still unable to log in, please fall back to `stable-cccea3e` , We will fix this next week

**Comment by RandomLegend** [comment]
@EYHN thanks, that image works for me

**Comment by pengx17** [comment]
Looks like the issue is being resolved.

**Comment by forehalo** [comment]
stable tag is ok now

**Comment by RandomLegend** [comment]
@forehalo sorry maybe theres something wrong but i still can't login with the latest stable tag...
![image](https://github.com/toeverything/AFFiNE/assets/38812603/ee58fcc9-1aa2-4ca9-a268-7e93492849b3)
This is what it shows me after pulling all the latest images.

Logging in just closes the login window but doesn't log me in at all.

**Comment by aware2** [comment]
Hi,

I also had this connection problem.
In the affine.js config file, before modification I had : 
AFFiNE.https = false;
AFFiNE.host = 'localhost';

I set true and my host, and I was able to connect.
I don't know if that was really the problem, but it solved it.
