### ISSUE TITLE
error: always show 5xx wrong​

### ISSUE THREAD

**Issue by last-misaka** [toeverything/AFFiNE#6130]
### description
_tried restarting mac and reinstalling APP_
as title.

![image](https://github.com/toeverything/AFFiNE/assets/41295175/abdd7881-b034-4d64-9ddd-d4121bc4d370)

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
sorry to hear that 😢 

Your workspace may have encountered a issue that caused the data to fall into an unrecoverable error.
In last year, we encountered many similar data issues and worked hard to resolve the vast majority of them, but you obviously still experienced one. We can help you recover your data. 
Please send the files from this path on your computer, 
/Users/<YOUR_USER_NAME>/Library/Application Support/AFFiNE/workspaces
to our support email: support@toeverything.info
We will reply to you with the recovered workspace.
Your data will also be of great help to us in diagnosing the issue. Your data will only be used for data recovery and issue diagnosis, and we will completely delete it after that.

**Comment by EYHN** [comment]
@lzeiw We have received your file, but we have just released version 0.13.0. I found that 0.13.0 can already open your workspace. Please install 0.13.0 and try again.

**Comment by EYHN** [comment]
https://github.com/toeverything/AFFiNE/releases/tag/v0.13.0
