### ISSUE TITLE
The position of menubar icon when unfolding is not correct, comparing to the web version​

### ISSUE THREAD

**Issue by alissa-tung** [toeverything/AFFiNE#6155]
### What happened?

<img width="1512" alt="截屏2024-03-17 11 20 19" src="https://github.com/toeverything/AFFiNE/assets/80032304/a5585434-9796-4105-bbc9-51362fc6bb84">

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Other

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
Looks like a bug, we will fix ASAP
