### ISSUE TITLE
 The app flashes a white screen on startup

### ISSUE THREAD

**Issue by georgel2020** [toeverything/AFFiNE#6158]
### What happened?

When I open AFFiNE, it flashes several times as follows: 

- A white screen with a system title bar
- An empty AFFiNE workspace page with shape placeholders
- A white screen with a system title bar
- Workspace content

The behavior is especially noticable with dark mode on. 

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

### Anything else?

# Images

![White screen with a system title bar](https://github.com/toeverything/AFFiNE/assets/86717650/e3b61846-e728-407d-be16-205b0aa31de4)

![Empty AFFiNE workspace page with shape placeholders](https://github.com/toeverything/AFFiNE/assets/86717650/dcbb6864-2ecb-4501-8a8e-2573d217b044)

# Version

- AFFiNE version: 0.13.0
- Editor version: 0.13.0-canary-202403140735-2367cd5
- Billing plan: Free
- Workspace sync with AFFiNE Cloud

**Comment by pengx17** [comment]
Should be related to layers of status checks on first load. Planned be resolved when auth is refactored in 0.14 next release

**Comment by EYHN** [comment]
@pengx17 do you have any idea about `A white screen with a system title bar`

**Comment by pengx17** [comment]
<img width="1913" alt="image" src="https://github.com/toeverything/AFFiNE/assets/584378/2b3ed016-6f77-42ed-a689-b6d00c0d47b7">
I guess it is the time of the blocking script is being evaluated (above perf profile is generated with x6 cpu slow down).

Some possible solutions:
- reduce the load of blocking js before first render. e.g., take the main react app as async module
- add a non-js loading screen for electron entry
- only show electron window after js is finished evaluating
- v8 snapshot?

**Comment by EYHN** [comment]
Please try the latest version again. If the problem persists, reopen this issue
