### ISSUE TITLE
Suggestions for sidebar area adjustments

### ISSUE THREAD

**Issue by xqyi** [toeverything/AFFiNE#6159]
### Description

The space allocated for the favorites and Collections sections in the sidebar is too small. When there is a lot of content, browsing through the featured section becomes difficult. It is recommended to increase the space allocated for the favorites and Collections  sections in the sidebar.
![image](https://github.com/toeverything/AFFiNE/assets/3350573/95e4e36a-5f76-4638-b35e-be1b9e77ad41)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
Have you tried 0.13.0? 

In 0.13.0, if the sidebar has a lot of content, will display the scroll bar.

If there is a scroll bar, do you still feel crowded? Tell me what you feel.🙏

**Comment by pengx17** [comment]
@hwangdev97 thoughts on this?

**Comment by hwangdev97** [comment]
I think scrolling the sidebar can solve this problem.

**Comment by xqyi** [comment]
Today I upgraded to version 0.13.1. The color theme now follows the system, but the left sidebar remains black. Here are a few points about the sidebar layout experience:
![微信截图_20240325105853](https://github.com/toeverything/AFFiNE/assets/3350573/c1e86f97-2f68-477e-9aed-fb947c38fa4e)

1. I don't use the functionality in the red area often. I suggest reducing its space. For example, I usually create a new document structure by clicking the "+" button within an existing document structure to maintain the document's organization.

2. The functionality in the blue area is necessary, but it occupies too much space in the left sidebar. Consider moving it to the right or reducing the space it occupies.

3. Having a scrollbar in the left sidebar feels inconvenient. When there is a lot of content, I still prefer to see as much of the document structure list as possible and minimize scrolling to view the list content.

**Comment by hwangdev97** [comment]
The black background is due to a bug, we will fix it as soon as possible. 

Regarding the issue of document area size, we will also provide customization options for sidebar information in the future, where you can customize the displayed content. However, this will take some time to complete.( eg. For example, if there is no entry for all docs, how can users open this route page. Which ones can be closed and which ones must be displayed.)

**Comment by JimmFly** [comment]
As an aside, you might be able to adjust the width of the sidebar by dragging it.

<img width="459" alt="image" src="https://github.com/toeverything/AFFiNE/assets/102217452/f2d7c76b-0cda-47d5-93d9-c39d4632e48a">
