### ISSUE TITLE
journals中的updated如实的关联docs中实际调整的是否更好，可以通过updated了解到对应日期的工作调整。

### ISSUE THREAD

**Issue by vankeoa** [toeverything/AFFiNE#6182]
### Description

journals中的updated如实的关联docs中实际调整的是否更好，可以通过updated了解到对应日期的工作调整。

### Use case

！[上传截屏2024-03-19 07.56.11[07.56.11.p]
![Uploading 截屏2024-03-19 07.56.11.png…]()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
我没太能理解你的意思，你是说假如一篇文章 "foo" 在日期 A/B/C 都有编辑过，那么在日期 A/B/C 的 journal 里都显示 foo 吗？另外图片挂了。
