### ISSUE TITLE
[SELF-HOST] If in config ​`AFFINE_SERVER_HOST` is quoted by single quote, some format is not correct

### ISSUE THREAD

**Issue by alissa-tung** [toeverything/AFFiNE#6183]
### What happened?

consider in selfhost compose yaml

```yaml
environment:
    AFFINE_SERVER_HOST='sdsds.asdad.asdsa'
```

if the host is quoted by single quote, then

- the starting log will in incorrect to display host name, which is `https://'sdsds.asdad.asdsa'`
- the copy private share link url will be incorrect, which is `https://'sdsds.asdad.asdsa'/${workspaceId}/${note}`

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
env docker passed to the containers will be automatically converted to string value, which means you don't need to add quote surround, no matter single or double quote.

This is docker's behavior, not suitable to be taken cared in AFFiNE

let's say
```
environment:
  a: 1
  b: "2"
```

will be passed in form of:

```
export a="1"
export b="\"2\""
```
