### ISSUE TITLE
Bug: ​Settings modal window texts can be selected.

### ISSUE THREAD

**Issue by qpomelo** [toeverything/AFFiNE#6194]
### What happened?

<img width="914" alt="Screenshot 2024-03-19 at 3 06 06 PM" src="https://github.com/toeverything/AFFiNE/assets/35286331/97d51b21-918e-474e-9a76-d34c84abac18">

AFFiNE (macOS, arm64, 0.13.1 Stable)

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you self-hosting?

- [ ] Yes

**Comment by pengx17** [comment]
I think we do not have a rule of thumb on which text can be selected in the UI thus it should not be considered as a bug
