### ISSUE TITLE
Add About shortcut for macOS Menubar.

### ISSUE THREAD

**Issue by qpomelo** [toeverything/AFFiNE#6195]
### Description

Expected behavior: click "about" menu item and open about page in settings.
<img width="574" alt="Screenshot 2024-03-19 at 3 08 07 PM" src="https://github.com/toeverything/AFFiNE/assets/35286331/a16c315d-7ca3-4e63-a9ba-81940755fcfa">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Aniruddha775** [comment]
hey can i work on this issue?

**Comment by qpomelo** [comment]
Hi Aniruddha,


I hope this message finds you well. I wanted to take a moment to express
our gratitude for your interest in the AFFiNE project. It’s always exciting
to see new faces eager to contribute, and we’re thrilled to have you join
our community!


We believe that with your assistance, we can make AFFiNE even better. As
you get started, please take a look at our contribution guidelines and
project license to ensure a smooth collaboration. If you have any questions
or need further clarification on any points, feel free to reach out.


Thanks once again for being a part of this journey. We can’t wait to see
the great things we will achieve together!


Best regards,


QPomelo


Aniruddha Dhar Chowdhury ***@***.***>：
