### ISSUE TITLE
[Bugs]​ The icon's problem

### ISSUE THREAD

**Issue by zxp19821005** [toeverything/AFFiNE#6212]
### What happened?

The icons in the packaged Linux AppImage was Electron!

### Distribution version

Linux

### Are you self-hosting?

- [ ] Yes

**Comment by CatsJuice** [comment]
Is this fixed? @pengx17

**Comment by pengx17** [comment]
Not yet. It looks like to be some restrictions to AppImage related to icons.
I guess this can be solved by using other more desktop friendly solutions like flatpak. Still working on it right now.

**Comment by zxp19821005** [comment]
I think you should check this : https://github.com/toeverything/AFFiNE/blob/canary/packages/frontend/electron/forge.config.mjs

**Comment by pengx17** [comment]
> I think you should check this : [`canary`/packages/frontend/electron/forge.config.mjs](https://github.com/toeverything/AFFiNE/blob/canary/packages/frontend/electron/forge.config.mjs?rgh-link-date=2024-03-20T09%3A17%3A22Z)

AFIAK to show the icon in the filesystem (in the file explorer ui) a daemon process is required (like https://github.com/probonopd/go-appimage).
To show the correct icon in the app tray it says that we can call setIcon when app is running - however it did not successfully worked in my last try. Will take a look later.

**Comment by pengx17** [comment]
fixed in https://github.com/toeverything/AFFiNE/pull/6257
