### ISSUE TITLE
Risk of creating multiple cloud workspaces simultaneously

### ISSUE THREAD

**Issue by CatsJuice** [toeverything/AFFiNE#6213]
### What happened?

Create workspace's button can still be clicked after first click, and there is no feedback about being created.

https://github.com/toeverything/AFFiNE/assets/39363750/774e0810-8fcb-4e36-ab9a-e94f6b5ac0e8

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

**Comment by CatsJuice** [comment]
@hwangdev97 cc

**Comment by hwangdev97** [comment]
This is a bug, I think we need to add a response time limit for the button! Can you handle this issue?
