### ISSUE TITLE
UI Bug when using PgUp or PgDown

### ISSUE THREAD

**Issue by GabrielQuinmat** [toeverything/AFFiNE#6232]
### What happened?

When using PgUp or PgDown keys the UI crashes for a millisecond. Then a black block appears on the right side of the app. Everything else is pushed to the left and even if I try to minimize, then maximize, is no use. The only way to fix it is restarting the application or by clicking the right sidebar toggle button from the top toolbar. Is not that is blocking me from using the app, as the solution is simple, but I think it worth to mention as it doesn't feel right.

![image](https://github.com/toeverything/AFFiNE/assets/26678783/9922ff0b-6544-44fb-994a-daebc782d70e)

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by KorewaLidesu** [comment]
Affect Edgeless mode, hand-write are not scale correctly. Other elements like pages and image are scaling correct.

**Comment by EYHN** [comment]
I can't reproduce this on my mac.

@pengx17 Can you reproduce this using windows?

**Comment by pengx17** [comment]
> I can't reproduce this on my mac.
> 
> @pengx17 Can you reproduce this using windows?

Yes I can (windows). It seems PgUp & down in the blocksuite editor will force the parent container from scrolling.
