### ISSUE TITLE
​Unable to sign in / sign up into self-hosted version

### ISSUE THREAD

**Issue by HitchRait** [toeverything/AFFiNE#6236]
### What happened?

After updating selfhosted version from 12.2 (not sure about last digit) to 13.1 (I guess? pulled image today) I am not able to login into AFFiNE Cloud. Different behavior:
1. Vivaldi (chrome-based) - successfully used this browser with 12.2 version, but after upgrade I am no longer able to login, enter email, then password and then... I get sign-in/sign-up page (see picture below)
2. Firefox - this one has never touched AFFiNE and I walked through a pleasing intro and got Demo Wokspace. Then I tried Sign up/Sign in with ADFFiNE Cloud and login failed exactly like with Vivaldi browser - enter email, password and then I see is Demo Workspace again.

Selfhosting on linux via docker, used docker-compose file from current repository.

![Screenshot from 2024-03-20 20-22-06](https://github.com/toeverything/AFFiNE/assets/25616103/3cfe2c8b-13bc-4731-ba99-864442645f32)

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome, Firefox

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
did you get any suspicious logs from your container?

**Comment by christianpedersen** [comment]
I got the same issue with the latest version. Nothing in logs. In Chrome console the following error appears:

use-current-user.ts:70 {}
(anonymous) @ use-current-user.ts:70
Promise.then (async)
reload @ use-current-user.ts:69
(anonymous) @ sign-in-with-password.tsx:49
await in (anonymous) (async)
(anonymous) @ affine-async-hooks.ts:25
eI @ react-dom.production.min.js:54
eB @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
t7 @ react-dom.production.min.js:55
re @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
oP @ react-dom.production.min.js:274
eM @ react-dom.production.min.js:52
ru @ react-dom.production.min.js:109
nI @ react-dom.production.min.js:74
nO @ react-dom.production.min.js:73

**Comment by NeoHuncho** [comment]
I have the same issue, the error is coming from this frontend hook:
_use-current-user.ts:70_ 
 ```
return mutate().then(e => {
        console.error(e);
      });
    },
```

The e object is empty.

**Comment by EYHN** [comment]
@NeoHuncho @christianpedersen @HitchRait 
Hey guys.

I helped a self-hoster solve a similar problem yesterday because he did not configure `AFFINE_SERVER_HOST` correctly. This variable defaults to `localhost`, and he is using ip to access his server. Please ensure that `AFFINE_SERVER_HOST` and `AFFINE_SERVER_PORT` are consistent with the url used for browser access.

https://docs.affine.pro/docs/self-host-affine/run-affine-with-custom-options

**Comment by NeoHuncho** [comment]
Hi @EYHN, thanks for the quick reply. Is this environment variable new? As I didn't have it in my docker-compose,but v0.12 was working fine without it.

**Comment by christianpedersen** [comment]
Hi @EYHN! 

That fixed it for me, thank you!

**Comment by NeoHuncho** [comment]
Worked for me too, thanks!

**Comment by EYHN** [comment]
> Hi @EYHN, thanks for the quick reply. Is this environment variable new? As I didn't have it in my docker-compose,but v0.12 was working fine without it.

I honestly don't know why 0.12 works, but I'll add a reminder about this to the selfhost tutorial.

**Comment by HitchRait** [comment]
Thanks, @EYHN ! It worked.

The last thing to mention: I have a VPN network and so my AFFiNE server has 2 IP's (local and VPN) and this solution doesn't work with another IP not mentioned in `AFFINE_SERVER_HOST`. Though it worked with my previous version (12). 

I have a very specific use case, but hope to see it working regardless of IP address.

**Comment by StudyingLover** [comment]
works，thanks.

> "Docker Compose will generate AFFiNE configuration files within the `~/.affine/self-host/config` directory on the host system after the initial startup."

 **This statement should be emphasized in bold; initially, I thought it was written in the shell's environment variables.**

**Comment by attorneyatlaw** [comment]
Could you give me an example code(script, affine.js?) to fix this?
The below is correct? (my environment is ubuntu, arm64)

AFFINE_SERVER_HOST='https://affine.example.com'
AFFINE_SERVER_PORT=3010(_right? I am now using affine behind nginx proxy manager_)
AFFINE_SERVER_HTTPS=true;

I installed a stable version(self-host) but log-in just close the window and not log-in actually.
So my affine self host is not switched from local to cloud.

**Comment by EYHN** [comment]
> Could you give me an example code(script, affine.js?) to fix this? The below is correct? (my environment is ubuntu, arm64)
> 
> AFFINE_SERVER_HOST='https://affine.example.com' AFFINE_SERVER_PORT=3010(_right? I am now using affine behind nginx proxy manager_) AFFINE_SERVER_HTTPS=true;
> 
> I installed a stable version(self-host) but log-in just close the window and not log-in actually. So my affine self host is not switched from local to cloud.

@attorneyatlaw The configuration here should be consistent with the URL you ultimately access with your browser. If the port number is 443 after you go through nginx, then AFFINE_SERVER_PORT should be 443

**Comment by attorneyatlaw** [comment]
not work for me.
log-in does not work.

**Comment by EYHN** [comment]
> not work for me. log-in does not work.

@attorneyatlaw I noticed that your AFFINE_SERVER_HOST is wrong, it should not contain `https://`

If issue still exists, please tell me your configuration and what URL you use to access affine.

**Comment by Arthur-Llevelys** [comment]
same problem with selfhost, my configuration is :  
```
.../...
     AFFINE_SERVER_HOST=affine.example.com
     AFFINE_SERVER_PORT=3010
     AFFINE_SERVER_HTTPS=true
.../...
```
![image](https://github.com/toeverything/AFFiNE/assets/101706410/ebddbc6b-16bd-423f-bf00-c1d76e5501b2)

**Comment by attorneyatlaw** [comment]
I tried without https:// and it worked. after log-in, mine is changed from local to AFFiNE Cloud.
I wrote down only the below in the yml file.

AFFINE_SERVER_HOST=affine.example.com

log-in worked but another problem happened.
The problem is that my affine is reset for the next time log-in.

Connection to my affine URL is directed to
https://af.example.com/onboarding (initialization setup display including 'AFFiNE is a workspace with fully merged docs,
whiteboards and databases' )

Initialization setup process happens again and again(when session is out, connected with other web browser).
Whenever I log-in, Demo Workspace is generated.

I used a stable image(ghcr.io/toeverything/affine-graphql:stable).

![Untitled](https://github.com/toeverything/AFFiNE/assets/35063408/9313adf9-d5e7-49a0-a84e-77639cd4036d)

**Comment by EYHN** [comment]
@attorneyatlaw When start on a new browser, affine will always create a new workspace (just a temporary workspace stored locally in the browser).

You can ignore it and click the workspace button from the upper sidebar to sign in to your account.

If you click `Sign in and enable`, it means logging in and upload this local workspace into cloud.

![CleanShot 2024-03-26 at 21 48 53](https://github.com/toeverything/AFFiNE/assets/13579374/b9116f89-0843-470f-80b2-dad5a7878624)

If you are experiencing other issues, please provide a screen recording.

**Comment by attorneyatlaw** [comment]
You mean that whenever I connect my affine URL to sign-in, I should see the below and click to go to the next steps(clicking 3 next buttons, 1 Get Started button and 1 Got it! button), right?
(I use my web browser with the setting of clearing all data when the browser is closed.)

![aUntitled](https://github.com/toeverything/AFFiNE/assets/35063408/c9aebc20-161c-4f08-952b-d081133a396d)

The above process is too burdensome.

I hope I can see the sign-up/sign display directly whenever I connect my affine URL.
I am curious that others use affine self host like this.

**Comment by EYHN** [comment]
@attorneyatlaw  This onboarding animation has been removed from the web version. You can try updating to the latest version.

**Comment by attorneyatlaw** [comment]
@EYHN I tried the stable version again(2024. 03. 28. 09:53 AM UTC +9) and no onboarding animation is shown!
Thank for your help and effort.

**Comment by Arthur-Llevelys** [comment]
@attorneyatlaw  I've written a tutorial for me, for installing AFFiNE on a VPS server, but I use apache not nginx.
[link tutorial](https://juris-tyr.com/installation-juris-tyr-chapter-8-and-next/#affine)

with theses variables environment :  
```
.../...
     AFFINE_SERVER_HOST=localhost
     AFFINE_SERVER_PORT=3010
     AFFINE_SERVER_HTTPS=false
.../...
```
