### ISSUE TITLE
self-hosting share link

### ISSUE THREAD

**Issue by wentevill** [toeverything/AFFiNE#6242]
### What happened?

I deployed Affine on the host and used Nginx to reverse proxy the domain. However, when I try to share the link, it shows `http://localhost:3010/...` instead of the expected domain. I haven't found any relevant configuration in the Docker deployment. Please let me know if I missed something.

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Anything else?

<img width="404" alt="image" src="https://github.com/toeverything/AFFiNE/assets/59240428/3b658a6d-948e-44f5-b9a5-5a1169d44088">

**Comment by wentevill** [comment]
docker image version is `stable-cccea3e`.

**Comment by forehalo** [comment]
you need to update the config at `~/.affine/self-host/config/affine.js` in your host machine

```js
/* Domain of your server that your server will be available at */
AFFiNE.host = 'your.domain';
```

or use environment variable called `AFFINE_SERVER_HOST=your.domain`

**Comment by wentevill** [comment]
> you need to update the config at `~/.affine/self-host/config/affine.js` in your host machine
> 
> ```js
> /* Domain of your server that your server will be available at */
> AFFiNE.host = 'your.domain';
> ```
> 
> or use environment variable called `AFFINE_SERVER_HOST=your.domain`

Great, it's working!
```
# domian
AFFINE_SERVER_HTTPS=true
AFFINE_SERVER_HOST=foo.com
```
