### ISSUE TITLE
​smtp Invite Members failed

### ISSUE THREAD

**Issue by efremov-it** [toeverything/AFFiNE#6260]
### What happened?

Invite Members doesn't work (
I use docker self-hosted instruction [LINK](https://docs.affine.pro/docs/self-host-affine)

I use [ThisSite](https://www.gmass.co/smtp-test) to test my Tls smtp server connection, and it works!

There are these variables. 
    environment:
      - MAILER_HOST=mail.mydomain.com
      - MAILER_PORT=587
      - MAILER_USER=affine@mydomain.com
      - MAILER_PASSWORD=passwordkAfpbCEJxHrVa

When i use Invite Members i get Error: failed to send invite email, please try again.
![image](https://github.com/toeverything/AFFiNE/assets/143379288/d802e558-98c6-4c0e-8dd4-7726d871a29d)

When i don't use MAILER_SECURE=true
i get 
`affine_selfhosted  | [Nest] 133  - 03/21/2024, 1:21:14 PM    WARN [WorkspaceResolver] failed to send 5c5c0db7-7ba1-43ed-bfe8-5f37f4cafed1 invite email to test@mail.com, but successfully revoked permission: Error: self-signed certificate`

When i use MAILER_SECURE=true
i get
`affine_selfhosted  | [Nest] 133  - 03/21/2024, 1:19:32 PM    WARN [WorkspaceResolver] failed to send 5c5c0db7-7ba1-43ed-bfe8-5f37f4cafed1 invite email to sadas@mail.com, but successfully revoked permission: Error: 00B8E5B9257F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:`

Help me plz. What do i need to do to fix this errors?

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome, Firefox

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
MAILER_SECURE=false
affine_selfhosted  | [Nest] 133  - 03/21/2024, 1:21:14 PM    WARN [WorkspaceResolver] failed to send 5c5c0db7-7ba1-43ed-bfe8-5f37f4cafed1 invite email to test@mail.com, but successfully revoked permission: Error: self-signed certificate

MAILER_SECURE=true
affine_selfhosted  | [Nest] 133  - 03/21/2024, 1:19:32 PM    WARN [WorkspaceResolver] failed to send 
5c5c0db7-7ba1-43ed-bfe8-5f37f4cafed1 invite email to sadas@mail.com, but successfully revoked permission: Error: 00B8E5B9257F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354
```

**Comment by forehalo** [comment]
looks like your SMTP server is using a self-signed certification
you could update your config at `~/.affine/self-host/config/affine.js` on your host machine 

```js
AFFiNE.mailer = {
  tls: {
    rejectUnauthorized: false,
  }
},
```

**Comment by efremov-it** [comment]
@forehalo when i use `MAILER_SECURE=false` it works! Thank you!
But i still have one question. Is it possible to have more than 3 users?

**Comment by EYHN** [comment]
@efremov-it 

selfhost currently cannot invite more than 3 people because it still uses affine cloud's free plan, but we will fix this.

**Comment by William-715** [comment]
我的搞定了，腾讯企业邮箱需要设置：MAILER_PORT="465"
MAILER_SECURE="true"  这两个参数需要同时配置正确才行。
