### ISSUE TITLE
​After the document is updated, the last update time remains unchanged

### ISSUE THREAD

**Issue by greedyhao** [toeverything/AFFiNE#6264]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/25771942/85d24dd4-1563-456b-b7bc-8edeecd88fd9)
![image](https://github.com/toeverything/AFFiNE/assets/25771942/53cf9404-d005-416a-a674-45ff7847de1e)

The document was opened on the night of the 21st and has not been closed
After the modification on the 22nd, the document update date does not change, but the document history will be updated

![image](https://github.com/toeverything/AFFiNE/assets/25771942/52413229-cbb7-41fd-88fa-6d31561a932c)

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you self-hosting?

- [ ] Yes

**Comment by JimmFly** [comment]
AFFiNE has released the latest version. Does this problem still exist in this version? I tried it and the sidebar update time is real-time. The update time in the historical version needs to wait for a while, it is not updated in real time.

I will close this issue first. If this issue still exists, you can reopen it.
