### ISSUE TITLE
​Copying text not working in Firefox

### ISSUE THREAD

**Issue by christianpedersen** [toeverything/AFFiNE#6271]
### What happened?

As the title says, ​copying text from any document does not get copied to the clipboard.
I've tried in Chrome, Firefox and Safari on macOS, and Chrome on Windows.

Pasting works fine.

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Firefox, Safari

### Are you self-hosting?

- [X] Yes

**Comment by EYHN** [comment]
In the http environment, we do not have permission to write to your clipboard, please configure the server to https protocol

**Comment by modhug** [comment]
@EYHN 
I am using firefox (124.0.1 windows) for https://app.affine.pro/ (official hosted version).

for text box in ctrl+k search bar
- can copy
- can paste

for page editor (both 2 modes)
- can paste
- **can not copy**

**Comment by EYHN** [comment]
Seems to be a compatibility bug with firebox

**Comment by EYHN** [comment]
@fourdim take a look

**Comment by fourdim** [comment]
Unfortunately, `ClipboardItem` isn't supported in Firefox. Support can be enabled via an `about:config` setting.
https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem/ClipboardItem
We will try to find a workaround for this.

**Comment by javix64** [comment]
It is working for me with Firefox in Linux/Manjaro changing `ClipboardItem` in `about:config` from false to true
