### ISSUE TITLE
​unable to sign in on canary selfhost

### ISSUE THREAD

**Issue by mwlegath** [toeverything/AFFiNE#6273]
### What happened?

deployed using docker compose file below:

services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:canary
    container_name: affine_selfhosted
    command:
      ['sh', '-c', 'node ./scripts/self-host-predeploy && node ./dist/index.js']
    ports:
      - '3010:3010'
      - '5555:5555'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      # custom configurations
      - ~/.affine/self-host/config:/root/.affine/config
      # blob storage
      - ~/.affine/self-host/storage:/root/.affine/storage
    logging:
      driver: 'json-file'
      options:
        max-size: '1000m'
    restart: unless-stopped
    environment:
      - NODE_OPTIONS="--import=./scripts/register.js"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgres://affine:affine@postgres:5432/affine
      - NODE_ENV=production
      - AFFINE_ADMIN_EMAIL=user@gmail.com
      - AFFINE_ADMIN_PASSWORD=userxxxxx
      - AFFINE_SERVER_HOST=localhost
      - AFFINE_SERVER_PORT=3010
  redis:
    image: redis
    container_name: affine_redis
    restart: unless-stopped
    volumes:
      - ~/.affine/self-host/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres
    container_name: affine_postgres
    restart: unless-stopped
    volumes:
      - ~/.affine/self-host/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U affine']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: affine
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata

Service is fully running with no logs to show errors. I click "Sign up/Sign in with cloud". It allows me to enter my default email and password. Once I enter the password and click login, the sign in box disappears, but puts me right back to the default page without logging me in.  

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [X] Yes

**Comment by n1njaznutz** [comment]
Canary self hosted has been broken for a week.  Still waiting for v 0.13.1 to be pushed out (despite an image update today which wasnt the v0.13.1 update....

**Comment by mwlegath** [comment]
I tested the same compose file on the stable image as well and have the same issue. I am assuming they are both broken at this time?

**Comment by n1njaznutz** [comment]
I believe so. Apparently fixed in v0.13.1. Not entirely sure why we're still waiting for image to be deployed.

**Comment by EYHN** [comment]
I guess it's a configuration problem? The solution is here https://github.com/toeverything/AFFiNE/issues/6236#issuecomment-2011867319
