### ISSUE TITLE
​Link for Unraid / Docker is Broken

### ISSUE THREAD

**Issue by xer0-1ne** [toeverything/AFFiNE#6283]
### What happened?

https://github.com/-/toeverything/packages/container/package/affine-self-hosted 

The above link is used to get the latest image for unraid to build the self-hosted container for Affine.  That link is now broken.

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by EYHN** [comment]
should use https://github.com/toeverything/AFFiNE/pkgs/container/affine-graphql
