### ISSUE TITLE
Using two fingers on touchscreen makes whiteboard pen tool go crazy

### ISSUE THREAD

**Issue by ntrkd** [toeverything/AFFiNE#6286]
### What happened?

Open a new document, switch to whiteboard mode. Select pen tool then on your touchscreen use 2 fingers at the same time and drag. It makes lines between those fingers.

Instead it should probably zoom into the whiteboard.

![image](https://github.com/toeverything/AFFiNE/assets/140664254/d110f18c-5bb9-40f2-a87f-438bfafb9fe8)

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

### Anything else?

I don't use touchscreen much so this isn't a high priority issue for me.

Client information -
AFFiNE - 0.13.1
Editor Version - 0.13.0-canary-202403140735-2367cd5

**Comment by EYHN** [comment]
In fact, we have not yet optimized for the touch screen. For at least one month, our manpower will be mainly focused on AI functions. Let's look at this in a month.

**Comment by ntrkd** [comment]
Yeah that's what I assumed. Touchscreen is good enough for now in my opinion
