### ISSUE TITLE
​Multiple windows will appear when click quickly on dock

### ISSUE THREAD

**Issue by iewnfod** [toeverything/AFFiNE#6303]
### What happened?

I'm using 0.13.0-canary.7. When I open AFFiNE and it is bouncing on the dock, if I click the icon in the dock quickly for many times, a lot of same window will appear. If one of them is closed, all of them will appear, and if you click the icon on dock again, all things would be normal.

<img width="1643" alt="image" src="https://github.com/toeverything/AFFiNE/assets/108739262/a3bdf2b1-5dcb-4cc8-be11-245c2d1472af">

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
@pengx17 pls take a look
