### ISSUE TITLE
Image loading failed​

### ISSUE THREAD

**Issue by Jycreyn** [toeverything/AFFiNE#6304]
### What happened?

Hello,

After importing from notion . 

I got " image loading failed " 

![image](https://github.com/toeverything/AFFiNE/assets/94803198/a56d87f1-2633-4f19-b74a-d43f7852c53c)

![image](https://github.com/toeverything/AFFiNE/assets/94803198/6a15512e-7c74-4d1c-8086-4c5767d4a0cc)

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by EYHN** [comment]
duplicate https://github.com/toeverything/AFFiNE/issues/6038

should be fixed in next version

**Comment by Jycreyn** [comment]
> duplicate #6038
> 
> should be fixed in next version

Hi,

I reopened because it's not exactly same issue. 

Now i have the image field

**Comment by EYHN** [comment]
@fourdim can u take a look at this?

**Comment by fourdim** [comment]
Could you please take a screenshot of your browser console after you import?

**Comment by zkwolf** [comment]
Embed images import not support in current version.  Unfortunately [#6419](https://github.com/toeverything/blocksuite/pull/6419) only fixed the external link images import.

**Comment by Jycreyn** [comment]
> Could you please take a screenshot of your browser console after you import?

yes here it is, screen and log output

![image](https://github.com/toeverything/AFFiNE/assets/94803198/d56dbf62-9056-48e6-a5ce-aa9e318c5b48)
[affine-1711530087254.log](https://github.com/toeverything/AFFiNE/files/14770753/affine-1711530087254.log)
