### ISSUE TITLE
​Duplicate buttons appear when opening trash

### ISSUE THREAD

**Issue by ruhuang2001** [toeverything/AFFiNE#6310]
### What happened?

AFFiNE version : 0.13.0-canary-202403140735-2367cd5

When I open trash, a duplicate button appears, as shown in the upper right corner of the picture. Whichever delete button is clicked will close whole affine.

![f0f7c15a6d0922d2f36bc5ac91a3c9bd](https://github.com/toeverything/AFFiNE/assets/36697407/721e4667-eef1-4491-93a1-571972f142fa)

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by ruhuang2001** [comment]
I have another small question, how can I clear all the contents of the trash instead of deleting them one by one. I don't find the select all button.

**Comment by EYHN** [comment]
I've created a new issue for your suggestion https://github.com/toeverything/AFFiNE/issues/6330

**Comment by JimmFly** [comment]
This issue has been fixed in the latest version of AFFiNE, thank you for your feedback.
