### ISSUE TITLE
electron package dependencies issue​

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#6312]
### What happened?

helper.js bundle include some blackholes of blocksuite packages. This will slow down electron from opening.

See the following diagram:
<img width="1898" alt="image" src="https://github.com/toeverything/AFFiNE/assets/584378/f7093ecf-6722-48fe-946a-78d68a2371fd">

To see it in action, upload [meta.json](https://github.com/toeverything/AFFiNE/files/14751984/meta.json) to https://esbuild.github.io/analyze/

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
In fact, these codes are not used in the end. Can we remove this code via bundler tree-shaking

**Comment by pengx17** [comment]
I suppose so and treeshaking is already turned on, but it seems esbuild does not handle treeshaking well in this case.
