### ISSUE TITLE
‌‌‌Incorrect handling of rich text

### ISSUE THREAD

**Issue by KyoSakuyo** [toeverything/AFFiNE#6327]
### What happened?

‌‌‌‌I hope that after I have selected and rich-formatted a piece of text, the text I input will maintain the original text format set within this block rather than the rich-text format set in the pop-up menu.

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

### Anything else?

![测试](https://github.com/toeverything/AFFiNE/assets/59904064/7e6066ca-8a83-4967-86b1-23a3271624ae)

**Comment by EYHN** [comment]
I think this is by design. Many note-taking app adopt the same design, such as notion, appflowy, heptabase ...
