### ISSUE TITLE
Support multiple selection and emptying in the trash

### ISSUE THREAD

**Issue by EYHN** [toeverything/AFFiNE#6330]
### Description

Support multiple selection and emptying in the trash

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Aniruddha775** [comment]
Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
This feature is released in the latest version of AFFiNE, thank you for your feedback. https://github.com/toeverything/AFFiNE/pull/6798
