### ISSUE TITLE
Huge bug?! Unable to recover document

### ISSUE THREAD

**Issue by headerloc215** [toeverything/AFFiNE#6333]
### What happened?

Downloaded affine-0.13.1-stable-linux-x64.
-had trouble logging in via password and via link. But on web, i'm able to login
-after i got in using the app, i was working on document. Somewhere i used CTRL Z, and for some reason it kept deleting some lines.. then i clicked version history. more things kept getting deleted when left clicking,
-went to login on web, i am not able to open the document. duplicating it creates blank page.

![image](https://github.com/toeverything/AFFiNE/assets/121714184/d82aa9
![Screenshot from 2024-03-26 18-58-45](https://github.com/toeverything/AFFiNE/assets/121714184/0843f1a0-0cad-4adf-8009-c744a3f8abd0)
1d-e35c-48a1-82e5-cdcc117868c0)
![Screenshot from 2024-03-26 18-56-02](https://github.com/toeverything/AFFiNE/assets/121714184/f5ffa8b9-801e-4ad9-8259-086af3a26f44)

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome, Other

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
Can you use version history to restore content?

**Comment by headerloc215** [comment]
I was able to now restore it, but on web version. i still cant login desktop app.
i was clicking around the history versions, i think i clicked somewhere in the middle (on the image) and it restored it to a version i am satisfied with

This screenshot here is on the duplicate document that was made. but it showed the same error
"block children is not found"
![image](https://github.com/toeverything/AFFiNE/assets/121714184/c52c3743-c9ac-4846-8e4a-364d74ce5e27)

**Comment by EYHN** [comment]
We fixed the login issue today, you can update to 0.13.2
