### ISSUE TITLE
​collection with fliter tag can not perform properly when many tags are selected

### ISSUE THREAD

**Issue by Boring545** [toeverything/AFFiNE#6334]
### Description

Although the desired label can be determined by keyboard input, if there are many labels, I can not see some labels displayed outside the screen in the label selection area due to screen size.

### Anything else?

![屏幕截图 2024-03-27 102128](https://github.com/toeverything/AFFiNE/assets/78906011/56e97533-0099-49f2-850c-8d332a9e10b4)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
@CatsJuice @hwangdev97  Can we add scrollbar to this component?

**Comment by CatsJuice** [comment]
> @CatsJuice @hwangdev97 Can we add scrollbar to this component?

I think `max-height` is necessary
