### ISSUE TITLE
[Bugs]​ .desktop文件运行参数问题

### ISSUE THREAD

**Issue by zxp19821005** [toeverything/AFFiNE#6340]
### What happened?

最新版本：https://github.com/toeverything/AFFiNE/releases/tag/v0.13.2
我在将其移植到ArchLinux的过程中，发现程序无法正常运行。仔细查看了下，是`.desktop`文件中运行参数有问题：
`Exec=AFFiNE --enable-features=UseOzonePlatform --ozone-platform=wayland %u`
按照ArchLinux官方wiki：https://wiki.archlinux.org/title/Wayland#Environment_variable 的说法：

Applications using Electron 28 and higher can use the [environment variable](https://wiki.archlinux.org/title/Environment_variable) [ELECTRON_OZONE_PLATFORM_HINT](https://github.com/electron/electron/blob/main/docs/api/environment-variables.md#electron_ozone_platform_hint-linux) set to auto or wayland.

This takes lower priority than the command line flags.

直接在运行参数中添加：
```
env ELECTRON_OZONE_PLATFORM_HINT=auto
```
即可，这样即便是使用x11也不影响程序运行。
我修改完成后目前运行正常。
详见： https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=affine-bin

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome, Microsoft Edge, Firefox, Other

### Are you self-hosting?

- [ ] Yes

**Comment by pengx17** [comment]
duplicated with https://github.com/toeverything/AFFiNE/issues/6252

简单的修改 Exec 参数不行，AppImageLauncher 处理 env 参数有问题，参考 https://github.com/audacity/audacity/issues/2498
可能需要修改 electron make 过程中生成的 AppRun 脚本

**Comment by pengx17** [comment]
fixed in #6371
