### ISSUE TITLE
​Self-hosted: Share doc generate localhost URL

### ISSUE THREAD

**Issue by GritsanY** [toeverything/AFFiNE#6347]
### What happened?

Hello!
Created new self-hosted AFFiNE, put it behind nginx proxy at https://affine.example.com.
Configured .env with AFFINE_SERVER_HOST=affine.example.com
Sharing any doc still generates "localhost" URL.
![image](https://github.com/toeverything/AFFiNE/assets/17610768/c4e9ba34-930a-4591-9687-1db1e1c3c396)

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Firefox

### Are you self-hosting?

- [X] Yes

**Comment by EYHN** [comment]
@darkskygit pls take a look

**Comment by darkskygit** [comment]
are you using the docker compose file [in our repo](https://github.com/toeverything/AFFiNE/blob/canary/.github/deployment/self-host/compose.yaml)? seems the `AFFINE_SERVER_HOST` and `AFFINE_SERVER_HTTPS` env are not effective
if you using k8s, you need import the envs by corresponding syntax in k8s config

or if you using docker-compose, please provide the command that you using to bootstrap the containers

**Comment by GritsanY** [comment]
> are you using the docker compose file [in our repo](https://github.com/toeverything/AFFiNE/blob/canary/.github/deployment/self-host/compose.yaml)? seems the `AFFINE_SERVER_HOST` and `AFFINE_SERVER_HTTPS` env are not effective if you using k8s, you need import the envs by corresponding syntax in k8s config
> 
> or if you using docker-compose, please provide the command that you using to bootstrap the containers

I am using podman with podman-compose to build containers from official compose.yml (https://github.com/toeverything/AFFiNE/blob/canary/.github/deployment/self-host/compose.yaml).
I can see that the volume with the config folder was successfully mounted and the .env file can be read from inside the container:

```
# podman inspect affine_selfhosted
...
 "Mounts": [
               {
                    "Type": "bind",
                    "Source": "/root/.affine/self-host/config",
                    "Destination": "/root/.affine/config",
                    "Driver": "",
                    "Mode": "",
                    "Options": [
                         "rbind"
                    ],
                    "RW": true,
                    "Propagation": "rprivate"
               },
               {
                    "Type": "bind",
                    "Source": "/root/.affine/self-host/storage",
                    "Destination": "/root/.affine/storage",
                    "Driver": "",
                    "Mode": "",
                    "Options": [
                         "rbind"
                    ],
...
```
```
# podman exec affine_selfhosted cat /root/.affine/config/.env
AFFINE_PRIVATE_KEY=-----BEGIN EC PRIVATE KEY-----
[REDACTED]==
-----END EC PRIVATE KEY-----

# AFFINE_SERVER_PORT=3010
# AFFINE_SERVER_HOST=affine.[REDACTED]
# AFFINE_SERVER_HTTPS=true
# DATABASE_URL="postgres://affine@localhost:5432/affine"

```

**Comment by darkskygit** [comment]
> ```
> # podman exec affine_selfhosted cat /root/.affine/config/.env
> # AFFINE_SERVER_PORT=3010
> # AFFINE_SERVER_HOST=affine.[REDACTED]
> # AFFINE_SERVER_HTTPS=true
> # DATABASE_URL="postgres://affine@localhost:5432/affine"
> ```

please remove `# ` prefix

**Comment by GritsanY** [comment]
> > ```
> > # podman exec affine_selfhosted cat /root/.affine/config/.env
> > # AFFINE_SERVER_PORT=3010
> > # AFFINE_SERVER_HOST=affine.[REDACTED]
> > # AFFINE_SERVER_HTTPS=true
> > # DATABASE_URL="postgres://affine@localhost:5432/affine"
> > ```
> 
> please remove `# ` prefix

Wow, that's so embarrassing 😁 Issue is fixed, obviously.
Thank you and sorry for the time taken.
