### ISSUE TITLE
​Mass Export of Workspace

### ISSUE THREAD

**Issue by ntrkd** [toeverything/AFFiNE#6353]
### Description

When in a workspace on the homepage there should be a button that goes through and exports all the files to the selected export type.

### Use case

For backing up their workspace to a more universal format other than just the default affine file type or for converting their workspace to some other format.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
What do you think about this? @hwangdev97
