### ISSUE TITLE
Close button overlaps with left sidebar button on macOS

### ISSUE THREAD

**Issue by mx2913** [toeverything/AFFiNE#6363]
### What happened?

Close button overlaps with left sidebar button on macOS
![图片](https://github.com/toeverything/AFFiNE/assets/15864713/9402f5b9-09a3-4d3c-bd46-1f625f0c60a5)

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

**Comment by JimmFly** [comment]
This issue has been fixed in #6351. Please look forward to the next update. If the same problem persists, we hope you will contact us.
