### ISSUE TITLE
When exporting, please include the current page and all subpages

### ISSUE THREAD

**Issue by aliuq** [toeverything/AFFiNE#6389]
### Description

I have a scenario where I need to export content and share it with others for offline use. The exported html cannot contain subpages.

Similarly, when I share a document that contains a subpage, the subpage cannot be accessed in the shared link.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
What do you think about this? @hwangdev97
