### ISSUE TITLE
Sort and reorder collections and pages with the mouse​

### ISSUE THREAD

**Issue by utilisateuralpha** [toeverything/AFFiNE#6410]
### Description

I propose that we can classify and reorganize collections and pages with the mouse in the left pane of the application.
I would also like to be able to put a page inside another page directly with the mouse in this pane.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
1. reorder collection already supported.
2. Using mouse to reorder the docs in a collection may not be possible, because the nature of the collection is a set of rules.
3. drag and drop of doc to another doc is not supported yet, but I think it is doable, what do you think?@hwangdev97

**Comment by utilisateuralpha** [comment]
1. Weird. I claim that I cannot rearrange with the mouse the sort order of the collections in the left pane. Is there any special handling to do?
2. Even with the rules, I think manual sorting is possible. If a new page is created and there is a rule that concerns this page, then it will be ranked last in the sorting. And if it is deleted, this should preserve the sort order by excluding this page.
3. Thanks for thinking about it. It will be very practical.

**Comment by EYHN** [comment]
Oh, sorry, the code for the reorder feature has been merged, but we have not released a new version yet. This function will be included in the next version.

**Comment by forehalo** [comment]
done in 0.16.0
