### ISSUE TITLE
Option / How to remove "Updated at" and "Info"​ repeated texts on every single page

### ISSUE THREAD

**Issue by MarArMar** [toeverything/AFFiNE#6429]
### Description

![image](https://github.com/toeverything/AFFiNE/assets/136232300/a4e5c0f5-d478-4f82-9cd2-1813ba463cac)

The "Updated at" information occupies very valuable space just under the title yet is not useful at all at least to me

This is the 1st time I open Affine and I immediately want this removed, how to ?

The "Info" information is also occupying valuable space, I do not plan to use it at the moment

I believe the "Info" text could be completely removed but the little triangle could stay so that people use it can and this saves valuable screen space

Otherwise both the "Info" and "Updated at" text are at the top of literally every single page I open, and I do not use them at all, at a very valuable space IMO

How to remove them ? Can you allow users to hide or remove them ?

Thanks

**Comment by MarArMar** [comment]
I see "Updated at" was not here in Affine 1 month ago ??

![image](https://github.com/toeverything/AFFiNE/assets/136232300/4a181ad8-0645-4bb6-a28c-3f7e2e456223)

From https://www.youtube.com/watch?v=EQ1ppa2c4X8

I believe it is MUCH cleaner, please allow us to remove it

**Comment by zanwei** [comment]
hi @MarArMar 

Thank you for your feedback. 

This is for product-level considerations. The reason why Info exists is because Page will eventually be defined as a database in the product dimension, and its added Property type will eventually appear on All docs. So in terms of type, it will definitely appear here. In fact, we have hidden it as much as possible out of consideration.

**Comment by MarArMar** [comment]
I don't understand, I see it on evey page 

Can I have the option to hide it anyway ? As a User I with to only have relevant information presented to me

**Comment by zanwei** [comment]
hi @MarArMar 

I'm afraid not. If you really want to hide it, you can try to use the Arc browser's custom CSS function which called **Boost** to hide it.

**Comment by MarArMar** [comment]
Or I will just not use Affine because they do not understand that Notion is about decluttering the space and focus

And I beleive Affine is about cluttering the space and deceptive marketing 

I just saw this

![image](https://github.com/toeverything/AFFiNE/assets/136232300/f373f1d0-3df2-40e8-9ef9-7a0ef3b438a2)
 
 There is no sort feature in your product, yet you advertise it in your landing page ?

**Comment by zanwei** [comment]
Regarding what you said, the sorting function is being planned and the corresponding design has been completed. The task needs to be completed step by step according to our timeline :))) There is no deception as you said. Please stay tuned.
