### ISSUE TITLE
Option to remove the icon repeated on every line of a Database​

### ISSUE THREAD

**Issue by MarArMar** [toeverything/AFFiNE#6432]
### Description

I see the [ T ] Icon at the start of every line in my database

How to remove them ?

What is their purpose ? They seem completely useless : why would they be on every single column ,repeated every time ? It is only distracting to me

If it is to indicate the Title column it should be in the title column, not in every single line

What purpose does adding this icon to every single line serves ?

![image](https://github.com/toeverything/AFFiNE/assets/136232300/4ff0076f-5d56-49dd-8991-2e41a96c25fe)

**Comment by utilisateuralpha** [comment]
I have already made a request concerning this improvement on this post :

https://github.com/toeverything/blocksuite/issues/6650

**Comment by EYHN** [comment]
Thanks for the fallback, let's track this issue in blocksuite https://github.com/toeverything/blocksuite/issues/6650
