### ISSUE TITLE
Remove deceptive marketing about the "Sorting" feature on database from the Affine landing page ​

### ISSUE THREAD

**Issue by MarArMar** [toeverything/AFFiNE#6435]
### Description

There is a screenshot in the Affine landing page that is deceptive as it advertises a "sorting" feature that does not exist in the current product

![image](https://github.com/toeverything/AFFiNE/assets/136232300/86b166e3-6780-49a7-9d04-bacc6f1160e3)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CatsJuice** [comment]
Thank you for your feedback. Due to our rapid version iteration, there may be differences between the demo images on the landing page and the actual product. We will do our best to improve them.
