### ISSUE TITLE
​import multi-file and export includes subpages

### ISSUE THREAD

**Issue by X-pCheng** [toeverything/AFFiNE#6447]
### Description

- export includes subpage
exported currently only has itself if it includes subpages

- import support multi-file
now only single file

### Use case

just import and export, it‘s often

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CatsJuice** [comment]
I think batch import is supported. When selecting files, you can hold down `ctrl` / `⌘` to select multiple files.

As for "export subpages", it's duplicated with #6408. I'll close this issue for now, feel free to reopen it if you think it's different.

**Comment by X-pCheng** [comment]
yeah i get it～
and thanks for your answer
