### ISSUE TITLE
​Support additional Oauth2/OIDC/SAML providers

### ISSUE THREAD

**Issue by dbrandonjohnson** [toeverything/AFFiNE#6464]
### Description

Add support for additional authentication providers that support Oauth2, OIDC or SAML such as [keycloak](https://www.keycloak.org/), [authentik](https://goauthentik.io/), Ipsilon or AzureAD.

Based on the current code base, it appears to only support Google and Github as identity providers.

### Use case

Adding additional authentication options provides authentication for Self-Hosted users and Affine Cloud business customers that use authentication providers other than Google Auth or Github.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
Other auth providers are truly on the table, but TBH, they are in low priority.
