### ISSUE TITLE
​Unable to sign in  into self-hosted version

### ISSUE THREAD

**Issue by a13782425** [toeverything/AFFiNE#6468]
### What happened?

Unable to sign in to the latest version

 environment:
      - AFFINE_SERVER_HOST=affine.example.com
      - AFFINE_SERVER_PORT=3010
      - AFFINE_SERVER_HTTPS=false
      - NODE_OPTIONS="--import=./scripts/register.js"
      - AFFINE_CONFIG_PATH=.affine/config
      - REDIS_SERVER_HOST=redisdb
      - DATABASE_URL=postgres://user:pass@url:port/affine
      - NODE_ENV=production
      - AFFINE_ADMIN_EMAIL=test@test.com
      - AFFINE_ADMIN_PASSWORD=test1234

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
affine_selfhosted  | [Nest] 1  - 04/06/2024, 2:40:55 PM   ERROR [GQLLoggerPlugin] GraphQL Unhandled Error
affine_selfhosted  | PrismaClientKnownRequestError:
affine_selfhosted  | Invalid `prisma.user.findFirst()` invocation:
affine_selfhosted  |
affine_selfhosted  |
affine_selfhosted  | The table `public.users` does not exist in the current database.
affine_selfhosted  |     at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6854)
affine_selfhosted  |     at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6188)
affine_selfhosted  |     at _n.request (/app/node_modules/@prisma/client/runtime/library.js:123:5896)
affine_selfhosted  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:128:10871)
affine_selfhosted  |     at async UserResolver.user (file:///app/dist/core/user/resolver.js:45:22)
affine_selfhosted  | [Nest] 1  - 04/06/2024, 2:41:00 PM   ERROR [Scheduler] PrismaClientKnownRequestError:
affine_selfhosted  | Invalid `prisma.update.count()` invocation:
affine_selfhosted  |
affine_selfhosted  |
affine_selfhosted  | The table `public.updates` does not exist in the current database.
affine_selfhosted  | [Nest] 1  - 04/06/2024, 2:42:00 PM   ERROR [Scheduler] PrismaClientKnownRequestError:
affine_selfhosted  | Invalid `prisma.update.count()` invocation:
affine_selfhosted  |
affine_selfhosted  |
affine_selfhosted  | The table `public.updates` does not exist in the current database.
affine_selfhosted  | [Nest] 1  - 04/06/2024, 2:43:00 PM   ERROR [Scheduler] PrismaClientKnownRequestError:
affine_selfhosted  | Invalid `prisma.update.count()` invocation:
affine_selfhosted  |
affine_selfhosted  |
affine_selfhosted  | The table `public.updates` does not exist in the current database.
```

**Comment by forehalo** [comment]
how did you start running your deploy. it seems like your deploy didn't even run the database migrations

**Comment by ghost** [comment]
> NODE_OPTIONS

how to run database migrations？

**Comment by EYHN** [comment]
Try to reconfigure your docker?

Please delete your image, container, and the database and configuration files in the ~/.affine directory.

Then try again

**Comment by ghost** [comment]
> Try to reconfigure your docker?
> 
> Please delete your image, container, and the database and configuration files in the ~/.affine directory.
> 
> Then try again
I remove ~/.affine dir
It worked，Thanks~

**Comment by a13782425** [comment]
I remove /.affine dir
It worked too，Thanks
