### ISSUE TITLE
​Annotations disappeared with the 0.13.0 update

### ISSUE THREAD

**Issue by CarbonX95** [toeverything/AFFiNE#6469]
### What happened?

I had prepared a lot of notes for a language I was learning and made many annotations and drawings to help visualize patterns and structures. I had created maps and pointers with the pen tool, all which is gone now. 
All shapes and pen tool items are gone as if they never existed. Now all that's left in the edgeless view are a few note items. That's quite some work that just got disappeared in thin air. I am hoping a future update can bring it all back...
![Screenshot (307)](https://github.com/toeverything/AFFiNE/assets/59415344/0c686c48-a049-480d-8fdf-6794b9abdd0f)

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

**Comment by Flrande** [comment]
Don't be nervous, from the selection box, they are all still there🫂, but there are some rendering issues. Can you open the console to see if there are any errors?

**Comment by JimmFly** [comment]
AFFiNE has released the latest version. Does this problem still exist? 
If this problem still exists, can you please provide more information to help us locate this problem faster?
