### ISSUE TITLE
Unable to View All Tags When Having Many Tags

### ISSUE THREAD

**Issue by oNo500** [toeverything/AFFiNE#6504]
### What happened?

When creating collections and defining rules, particularly when utilizing the "contains one of.." rule, I encounter limitations in selecting the desired tags due to incomplete visibility. Despite having numerous tags assigned, only a fraction of them are visible for selection. This impedes the efficiency of creating collections as it restricts my ability to filter based on the full range of available tags. I would appreciate it if there could be an improvement in the visibility of tags during the collection creation process, allowing for easier selection and application of filtering rules.

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

### Anything else?

![1712740409211](https://github.com/toeverything/AFFiNE/assets/24784662/294ddae3-5657-495e-8e9c-71ace3126c25)

**Comment by JimmFly** [comment]
This issue has been fixed in https://github.com/toeverything/AFFiNE/pull/6442, so look forward to the roll-out of the new version.
