### ISSUE TITLE
macOS​: close all opened documents, then press `cmd+w` won't close document window

### ISSUE THREAD

**Issue by alissa-tung** [toeverything/AFFiNE#6507]
### What happened?

close all opened documents, then press `cmd+w`, the UI is all black, without any components

the expected behavior:

closed all opened documents, press `cmd+w`, the document window is closed, the application is not stopped. click the running application icon from dock, the document window started at the `All Documents` page

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

**Comment by alissa-tung** [comment]
also applies for directly clicking the close (red) button, the UI is all black

**Comment by JimmFly** [comment]
Thank you for your feedback, this problem has been fixed in the upcoming new version, look forward to it.
