### ISSUE TITLE
Database: Data loss on change of 'column type'​

### ISSUE THREAD

**Issue by wondering1** [toeverything/AFFiNE#6514]
### What happened?

When working with a database, if the user changes the column type of a column that contains data on it, all data on that column in lost. 

**Example:**
1. Create database (table)
2. Change type of 'Status' column to type=Progress. By default, the column will be titled "Status".
3. Rename the "Status" column to "Score"
4. For each record, enter a value in the "Score" column
5. Change the column type to = Number
6. Without entering any value, immediately change the column type to = Progress

This happens on Mac and Web-version. Not tested on windows, but I presume it is the same.

**Result:**
The column values are blank. Only way to retrieve content is via CMD/CTRL + Z

**Expected result:**
The data entered at step 4 is returned

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Microsoft Edge, Firefox, Safari, Other

### Are you self-hosting?

- [ ] Yes

**Comment by JimmFly** [comment]
This is expected behavior. If you have any ideas, please feel free to create a PR in [blocksuite](https://github.com/toeverything/blocksuite).
