### ISSUE TITLE
BUG : ​Data Loss while exporting documents to PNGs, and PDFs.

### ISSUE THREAD

**Issue by offensive-vk** [toeverything/AFFiNE#6515]
### What happened?

Whenever, i'm exporting an document from Affine to PNG or PDF, some text is lost / not visible in Exported Document. Exported documents having no margin from left at all. 
Facing this issue on Version `0.13.5`.

## Client Details: (*AFFiNE*)
![version](https://github.com/toeverything/AFFiNE/assets/121493131/0358f13e-4c78-4c9a-870b-83e782e6b706)

## Actual Data in AFFiNE:

![Data_loss](https://github.com/toeverything/AFFiNE/assets/121493131/b6ecabe5-0451-4f98-8a2f-c34e4bcfbaab)

## Exported Document (PDF):
![data_lost_in_pdf](https://github.com/toeverything/AFFiNE/assets/121493131/d6fe3c3a-9c73-43bb-bb4e-8e00a573df39)

## Margin issue:

![no-margins](https://github.com/toeverything/AFFiNE/assets/121493131/a8555677-e676-4e43-bdbf-2ad5ad421dc9)

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

### Anything else?

Facing this issue from two recent updates. However, it was happening in previous builds.

**Comment by crypticbeing** [comment]
Hi I have generate a random Lorem Ipsum PDF with AFFIne. THis problem is not occuring. Please see the screenshot.
![Screenshot 2024-04-11 204303](https://github.com/toeverything/AFFiNE/assets/71935479/ea22611b-e5a3-447a-bec7-a04fa0bbfede)

**Comment by offensive-vk** [comment]
Idk, But On my Affine , its still the same. Tried two three times today.
Lets wait for someone from AFFiNE to Work on this issue.
Maybe they can help me troubleshoot.

**Comment by zkwolf** [comment]
Some string lose in the title?

**Comment by offensive-vk** [comment]
In the entire document, mostly ending of a line or paragraph.

**Comment by Jycreyn** [comment]
Hi, I got same issue here

**Comment by offensive-vk** [comment]
Bro , No one from AFFiNE has responded yet. I should close this Issue within few hours.
😶‍🌫️😶‍🌫️
