### ISSUE TITLE
mobile version

### ISSUE THREAD

**Issue by LIHAQ** [toeverything/AFFiNE#6517]
### Description

Using AFINE on a PC is very useful, but it is still inconvenient without a mobile version. So are there any plans to develop a mobile version

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
We plan to launch mobile app (android&ios) within this year. Some design work is happening. Stay tuned

This issue has no specific tasks associated with it. I'll close this issue first.

**Comment by EaMarWi** [comment]
> We plan to launch mobile app (android&ios) within this year. Some design work is happening. Stay tuned
> 
> This issue has no specific tasks associated with it. I'll close this issue first.

What technical architecture will be used for affine's android and ios clients? flutter, react native, capacitor or native development?

**Comment by Fau57** [comment]
Im also curious on the above question. Still working on becomibg a developer and part of my heart is mobile oriented. I do think a modality switch is coming but thats not stopping me from trying. So id be eager to help in whatever way i can

**Comment by ill-yes** [comment]
Any updates regarding this topic?
Would be awesome to have an app for Affine 🫶🏽

**Comment by csymlou** [comment]
2024 is ended, but when the app will come?

**Comment by juzdm** [comment]
2024 is ended, but when the app will come?

**Comment by juzdm** [comment]
+1

**Comment by begbaj** [comment]
would be great to know at what point is right now the development of the mobile version for your customers. We need to make some choices and some of them depend on what your honest answer is about this topic

**Comment by rexxDZN** [comment]
+1 would love an android beta or alpha (internal test) version to start rolling out

**Comment by ShyneTurtle** [comment]
+1

**Comment by mrcomoraes** [comment]
+1

**Comment by Magi-Wang** [comment]
+1
+2

**Comment by weiminw** [comment]
+1

**Comment by rafarje** [comment]
+1

**Comment by Zaschii** [comment]
+1

**Comment by Murguth** [comment]
+1

**Comment by ill-yes** [comment]
+1

**Comment by samypan** [comment]
+1

**Comment by vedxp** [comment]
There has been no comments from the team regarding the same for almost a year now. Will be glad to know the current progress for the Mobile client. 

@EYHN

**Comment by wolflu05** [comment]
They have posted something on there discord server about the app a while ago: https://discord.com/channels/959027316334407691/959033233683673088/1339131676130807839

(They said the app is launching soon and shared a form to sign up for a beta)

**Comment by vedxp** [comment]
> They have posted something on there discord server about the app a while ago: https://discord.com/channels/959027316334407691/959033233683673088/1339131676130807839
> 
> (They said the app is launching soon and shared a form to sign up for a beta)

Thank you @wolflu05 for the information.

**Comment by moiz-qureshi** [comment]
+1

**Comment by NexusOnePlus** [comment]
+1

**Comment by alpha-k911** [comment]
+1, any update on the android release?

**Comment by NoverNobida** [comment]
+1

**Comment by zby0407** [comment]
+1

**Comment by zx108wl** [comment]
+1

**Comment by cmd8** [comment]
+1

**Comment by senan-sh** [comment]
+1

**Comment by mafeifan** [comment]
+1 will be great if have a mobile version

**Comment by luoxding** [comment]
+1 android

**Comment by Kingong** [comment]
+1 Looking forward to the release of the mobile app

**Comment by CoceCole** [comment]
+1 Looking forward to the release of the mobile version. Affine is the most comfortable note-taking tool I've ever used. Thanks to every open-source contributor for your efforts.

**Comment by HeadOfWood** [comment]
At the end of this article the form to sign up for beta testing on android is available:
https://affine.pro/blog/whats-new-june-update
