### ISSUE TITLE
Create a one-click install for AFFiNE in Caprover (app/database deployment & web server manager )​

### ISSUE THREAD

**Issue by arthuragone** [toeverything/AFFiNE#6518]
### Description

Hi, I have almost zero knowledge regarding docker, Nginx and SSL. 
Therefore when starting my homeserver I chose to use Caprover as my server manager. 
There is a list of app available with their "one click install" which is a beautiful function for people like me. 

AFFiNE would greatly benefit from being listed there. All il takes (but which is more than I am capable of) is to adapt the .yml file for Caprover needs.

Detailed instructions here: https://github.com/caprover/one-click-apps

### Use case

People with no docker experience

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by vsthemarket** [comment]
Try Zeabur-- they had Affine last year. Same premise.

**Comment by arthuragone** [comment]
@forehalo hi, you closed the ticket as "completed" but could you precise how ?
