### ISSUE TITLE
How to play around with toolbar?​

### ISSUE THREAD

**Issue by mirtaqi07** [toeverything/AFFiNE#6549]
### Description

Hi, I'm just a beginner with electron and this whole Affine project is a nightmare for me. I mean this is much more sophisticated, well structured and I find it difficult to understand it.

There's no proper documentation for editing the tools. I couldn't find. Can somebody please help me how to edit the main toolbar buttons, remove or shuffle them, where button shortcuts are being enabled and how to disable press “/” to see commands? I hope you understand what I want. I'll really appreciate if you help me more with a little guide tour.

Thanks!

![Screenshot_2024-04-14-16-56-33-511_com android chrome](https://github.com/toeverything/AFFiNE/assets/88597955/8d5ee709-cf64-41a0-9dde-702798373d2c)

I've posted this already in technical discussion in Affine community, but it seems like not very active.

https://community.affine.pro/c/techincal-discussion/how-to-play-around-with-toolbar

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mirtaqi07** [comment]
**Can somebody please help me?**

I am modifying `AFFiNE\node_modules\@blocksuite\blocks\src\root-block\edgeless\components\toolbar\edgeless-toolbar.ts` but the change isnt happening to toolbar when I do `yarn dev`.

I've tested with `blocksuite\packages\blocks\src\root-block\edgeless\components\toolbar\edgeless-toolbar.ts` and change does happen in the webapp. 

But in Affine it doesnt happen. I cleared the `target directory`. Is there any other cache or something I need to delete?

**Comment by JimmFly** [comment]
In AFFiNE's yarn dev, there is an option to `debug blocksuite locally`. You can clone [Blocksuite](https://github.com/toeverything/blocksuite) locally and then paste its local path into debug blocksuite locally.

<img width="321" alt="image" src="https://github.com/toeverything/AFFiNE/assets/102217452/ce68c162-ec4c-4ede-8e50-4fadea91cf6f">

**Comment by mirtaqi07** [comment]
Thanks man. Affine's architect is truly impressive. 

> I'm gonna keep this issue open for a few days, in case I need the similar help. I'll close it after that.

**Comment by mirtaqi07** [comment]
Hi @JimmFly, hope you are doing fine.

I am trying to keep the left sidebar open, so it can't be hidden with `ctrl + /`. I couldn't fix that, the `AFFiNE\packages\frontend\core\src\hooks\affine\use-shortcuts.ts` is only for `Keyboard shortcuts` that are being displayed in the `setting` menu.

I want to stop the General keyboard operations.

| Operations | Shortcut Keys |
|--------|--------|
| Cancel | `ESC` |
| Quick Search | `Ctrl + K` |
| New Doc | `Ctrl + N` |
| Expand/Collapse Sidebar | `Ctrl + /` |
| Go Back | `Ctrl + [` | 
| Go Forward | `Ctrl + ]` |

**Comment by mirtaqi07** [comment]
Anybody?? Bros... @JimmFly @gbiggs @fundon @pengx17 

I'm also having troubling with the build. exe is created with `yarn make`, but getting this error on opening it.

![image](https://github.com/toeverything/AFFiNE/assets/88597955/c9866d44-29c5-44b5-917a-28c469b1f951)

**Comment by pengx17** [comment]
@mirtaqi07 actually if your task is to running affine locally, you don't need to make the app yourself. Please do not comment unrelated issues on this one. Closing now.
