### ISSUE TITLE
Direct Dashboard Loading Issue Upon Returning to Website

### ISSUE THREAD

**Issue by Anonymous961** [toeverything/AFFiNE#6550]
### What happened?

Upon revisiting the web project after closing the browser, users are directed to the intro page instead of being routed directly to the dashboard content. This behavior disrupts the expected flow for returning users who anticipate immediate access to the dashboard upon reentry.

![Screenshot from 2024-04-14 23-30-36](https://github.com/toeverything/AFFiNE/assets/96728156/5899a87b-b98d-406b-a7fd-e5799d13155a)

This creates confusion for users whether the user is signed in or not.

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

**Comment by JimmFly** [comment]
I'm not entirely sure I understand your question, but you can make use of AFFiNE directly through [app.affine.pro](app.affine.pro) rather than [affine.pro](affine.pro). The latter is our official website, which indeed, consistently presents the introduction page each time it's visited.
