### ISSUE TITLE
​​Failed to send invite email

### ISSUE THREAD

**Issue by vitaaaaa1** [toeverything/AFFiNE#6570]
### What happened?

Hello, I met a problem that I could not invite members because I could not send emails, please help me to study it
I used your official configuration file to configure the corresponding email environment variables. This is your official document address.(https://docs.affine.pro/docs/self-host-affine/run-affine-with-custom-options).This is the environment variable that I configured

 vim ~/.affine/self-host/config/.env
MAILER_HOST=smtp.gmail.com
MAILER_PORT=587
MAILER_USER=xxxxxxxxx@gmail.com
MAILER_PASSWORD=xxxxxxxxxxxx

I can make sure that there is nothing wrong with my email account and password, and I have checked the environment variables in the container, and these parameters are indeed loaded, and the container configuration file also has these parameters, why is there still an error
Error message

affine_selfhosted  | [Nest] 132  - 04/16/2024, 1:48:55 AM    WARN [WorkspaceResolver] failed to send 644624ca-9e33-444b-8ae0-87550909b106 invite email to 5106xxxxx@qq.com, but successfully revoked permission: Error: Mailer service is not configured.

compose.yaml：

services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:stable
    container_name: affine_selfhosted
    command:
      ['sh', '-c', 'node ./scripts/self-host-predeploy && node ./dist/index.js']
    ports:
      - '3010:3010'
      - '5555:5555'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      # custom configurations
      - ~/.affine/self-host/config:/root/.affine/config
      # blob storage
      - ~/.affine/self-host/storage:/root/.affine/storage
    logging:
      driver: 'json-file'
      options:
        max-size: '1000m'
    restart: unless-stopped
    environment:
      - NODE_OPTIONS="--import=./scripts/register.js"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgres://affine:affine@postgres:5432/affine
      - NODE_ENV=production
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_PORT=${MAILER_PORT}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
    
  This is the information for the configuration file
// Convenient way to map environment variables to config values.
AFFiNE.ENV_MAP = {
    AFFINE_SERVER_PORT: ['port', 'int'],
    AFFINE_SERVER_HOST: 'host',
    AFFINE_SERVER_SUB_PATH: 'path',
    AFFINE_SERVER_HTTPS: ['https', 'boolean'],
    DATABASE_URL: 'db.url',
    ENABLE_CAPTCHA: ['auth.captcha.enable', 'boolean'],
    CAPTCHA_TURNSTILE_SECRET: ['auth.captcha.turnstile.secret', 'string'],
    OAUTH_GOOGLE_CLIENT_ID: 'plugins.oauth.providers.google.clientId',
    OAUTH_GOOGLE_CLIENT_SECRET: 'plugins.oauth.providers.google.clientSecret',
    OAUTH_GITHUB_CLIENT_ID: 'plugins.oauth.providers.github.clientId',
    OAUTH_GITHUB_CLIENT_SECRET: 'plugins.oauth.providers.github.clientSecret',
    MAILER_HOST: 'smtp.gmail.com',
    MAILER_PORT: '587',
    MAILER_USER: 'vxxxxxxxxxx@gmail.com',
    MAILER_PASSWORD: 'ddcfkiexxxxxxx',
    THROTTLE_TTL: ['rateLimiter.ttl', 'int'],
    THROTTLE_LIMIT: ['rateLimiter.limit', 'int'],
    REDIS_SERVER_HOST: 'plugins.redis.host',
    REDIS_SERVER_PORT: ['plugins.redis.port', 'int'],
    REDIS_SERVER_USER: 'plugins.redis.username',
    REDIS_SERVER_PASSWORD: 'plugins.redis.password',
    REDIS_SERVER_DATABASE: ['plugins.redis.db', 'int'],
    DOC_MERGE_INTERVAL: ['doc.manager.updatePollInterval', 'int'],
    DOC_MERGE_USE_JWST_CODEC: [
        'doc.manager.experimentalMergeWithYOcto',
        'boolean',
    ],
    STRIPE_API_KEY: 'plugins.payment.stripe.keys.APIKey',
    STRIPE_WEBHOOK_KEY: 'plugins.payment.stripe.keys.webhookKey',
    FEATURES_EARLY_ACCESS_PREVIEW: ['featureFlags.earlyAccessPreview', 'boolean'],
    FEATURES_SYNC_CLIENT_VERSION_CHECK: [
        'featureFlags.syncClientVersionCheck',
        'boolean',
    ],
};

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
affine_selfhosted  | [Nest] 132  - 04/16/2024, 1:48:43 AM   DEBUG [CacheInterceptor] cache blobs:0a27b5e8-83f4-4975-a47b-9a746106ae05 miss
affine_selfhosted  | [Nest] 132  - 04/16/2024, 1:48:45 AM   DEBUG [CacheInterceptor] cache blobs:644624ca-9e33-444b-8ae0-87550909b106 miss
affine_selfhosted  | [Nest] 132  - 04/16/2024, 1:48:55 AM    WARN [WorkspaceResolver] failed to send 644624ca-9e33-444b-8ae0-87550909b106 invite email to xxxxxxxxxx@qq.com, but successfully revoked permission: Error: Mailer service is not configured.
affine_selfhosted  | [Nest] 132  - 04/16/2024, 1:49:43 AM   DEBUG [CacheInterceptor] cache blobs:0a27b5e8-83f4-4975-a47b-9a746106ae05 hit
affine_selfhosted  | [Nest] 132  - 04/16/2024, 1:50:44 AM   DEBUG [CacheInterceptor] cache blobs:0a27b5e8-83f4-4975-a47b-9a746106ae05 hit
affine_selfhosted  | [Nest] 132  - 04/16/2024, 1:51:45 AM   DEBUG [CacheInterceptor] cache blobs:0a27b5e8-83f4-4975-a47b-9a746106ae05 hit
affine_selfhosted  | [Nest] 132  - 04/16/2024, 1:52:46 AM   DEBUG [CacheInterceptor] cache blobs:0a27b5e8-83f4-4975-a47b-9a746106ae05 hit
```

**Comment by JimmFly** [comment]
We are still discussing solutions to the problem of selfhost not being able to send emails. If you have any ideas, please feel free to create a PR.

**Comment by JimmFly** [comment]
Maybe you can discuss it in this [discussions](https://github.com/toeverything/AFFiNE/discussions/5975)

**Comment by EYHN** [comment]
You should not modify affine.env.ts, you need to restore it now and only modify the .env file.

**Comment by vitaaaaa1** [comment]
> 您不应该修改 affine.env.ts，您需要立即恢复它并且仅修改 .env 文件。
Thanks for your reply, I only need to modify the.env file, not the configuration file outlined, right

**Comment by vitaaaaa1** [comment]
> 您不应该修改 affine.env.ts，您需要立即恢复它并且仅修改 .env 文件。

Thank you for your reply. I only need to modify the.env file, not the AFFiNE configuration file, right

**Comment by vitaaaaa1** [comment]
> We are still discussing solutions to the problem of selfhost not being able to send emails. If you have any ideas, please feel free to create a PR.

啥意思哥，您也有这种问题吗

**Comment by William-715** [comment]
我是Ubuntu22。04部署的，用的腾讯企业邮箱，也有同样的问题，邀请成员邮件无法发送成功

**Comment by dxkrs** [comment]
> send emails

Has the problem of sending emails been fixed?

**Comment by dxkrs** [comment]
> We are still discussing solutions to the problem of selfhost not being able to send emails. If you have any ideas, please feel free to create a PR.

Has the problem of sending emails been fixed?
