### ISSUE TITLE
​Self-host  cannot copy code block data

### ISSUE THREAD

**Issue by LIHAQ** [toeverything/AFFiNE#6575]
### What happened?

Self-host  cannot copy code block data
![image](https://github.com/toeverything/AFFiNE/assets/57976650/234ab2aa-c0da-4d23-9e4e-dc362e4e18b4)

### Distribution version

Web (affine.fail)

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you self-hosting?

- [X] Yes

**Comment by JimmFly** [comment]
Can this issue be reproduced in [blocksuite playground](https://try-blocksuite.vercel.app/starter?init)?

**Comment by LIHAQ** [comment]
> Can this issue be reproduced in [blocksuite playground](https://try-blocksuite.vercel.app/starter?init)?

Yes, I found that because of the MD file I exported from flowus, the type of the code block would default to Plain, and when imported into AFFINE it would not be able to be copied.

![image](https://github.com/toeverything/AFFiNE/assets/57976650/eb8bb6fa-0fa7-4c31-98c6-bae338f6a3e7)
![image](https://github.com/toeverything/AFFiNE/assets/57976650/256fafaf-85e4-423d-87ed-4dd5c065d8f8)
