### ISSUE TITLE
Cannot copy embedded image to clipboard, or download it​

### ISSUE THREAD

**Issue by maventis** [toeverything/AFFiNE#6603]
### What happened?

I pasted an image into the desktop editor and it pasted in fine, however, I now cannot copy that image out to an email, nor can I download it to a file.

Neither `Ctrl+C` or either of these two buttons do anything in terms of being able to "extract" embedded images out to another application:
![image](https://github.com/toeverything/AFFiNE/assets/36198985/ae5137ea-04d4-4937-89ca-f35b7a766310)

I also tried embedding a PNG file from the block menu, this also gave same result.

Note that I am able to copy paste _within_ AFFiNE but not out to other external applications.

This means that my images are "trapped" inside AFFiNE :(

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by JimmFly** [comment]
Thank you for your feedback. We will follow up on this issue and will reply in this issue if there is any progress.

**Comment by lawvs** [comment]
I can reproduce this issue and get the following error

<img width="707" alt="Screenshot 2024-04-18 at 11 31 13" src="https://github.com/toeverything/AFFiNE/assets/18554747/fcb1df1f-eb04-4d0e-9c23-9a1a2468c507">

**Comment by lawvs** [comment]
Fixed in https://github.com/toeverything/blocksuite/pull/6803
