### ISSUE TITLE
Improper Closing in Fullscreen Mode (macOS)

### ISSUE THREAD

**Issue by ishavlega08** [toeverything/AFFiNE#6623]
### What happened?

**Affine Application Bug Report - Improper Closing in Fullscreen Mode (macOS)**

**Description:**

I am reporting a bug with the Affine application on macOS. When I am using the application in fullscreen mode and attempt to close it using the red "X" button in the top left corner of the window, the application does not close properly. Instead of closing, a black screen appears.

**Steps to Reproduce:**

1. Open the Affine application.
2. Enter fullscreen mode (usually by pressing F11 or using the green fullscreen button in the top left corner of the window).
3. Work on your project for some time.
4. Click the red "X" button in the top left corner of the window (while still in fullscreen mode).
5. Observe the black screen instead of the application closing.

**Expected Behavior:**

Clicking the red "X" button should close the Affine application completely, even when in fullscreen mode, returning the user to the desktop.

**Additional Information:**

- macOS Version: MacBook Air M1 ( Silicon Chip)
- Affine Version: 0.13.5
- This issue has been observed for the starting when I started to use the Affine
- I am using a Macbook Air.

**Workaround:**

The application can be closed successfully using the following methods:

- Move your cursor to the top of the screen to reveal the menu bar. Then, select "Affine" from the top menu bar and choose "Quit Affine".
- Use the keyboard shortcut "Command + Q".

I hope this detailed description helps the Affine development team identify and fix this bug specific to the fullscreen mode.

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you self-hosting?

- [ ] Yes

### Anything else?

Some photos for the issues

<img width="1440" alt="Screenshot 2024-04-18 at 7 52 41 PM" src="https://github.com/toeverything/AFFiNE/assets/91582645/8a39ba35-8d7d-439a-a4dd-12b1d896c300">
<img width="1440" alt="Screenshot 2024-04-18 at 7 53 10 PM" src="https://github.com/toeverything/AFFiNE/assets/91582645/16c251e9-420b-4908-80e2-07ced6ef9694">

**Comment by EYHN** [comment]
fix by #6534
