### ISSUE TITLE
Selfhost link card view: Failed to retrieve link information ​

### ISSUE THREAD

**Issue by EricWvi** [toeverything/AFFiNE#6648]
### What happened?

Hey there, I got a problem while using self-hosted Affine.

Inline view:
![image](https://github.com/toeverything/AFFiNE/assets/49674577/800a8aef-faf6-474b-90ed-58550bdfbdce)

Card view:
![image](https://github.com/toeverything/AFFiNE/assets/49674577/8e37eb58-d2bc-4346-9ec4-e0366caabadc)

Console log:
<img width="458" alt="image" src="https://github.com/toeverything/AFFiNE/assets/49674577/dbf327bf-c032-4eec-862a-4b81a0dcb3ec">

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by pengx17** [comment]
You may need to self hosting [workers](https://github.com/toeverything/affine-workers) as well. We have not provided full support for it yet and you can try to adopt it.

**Comment by vaites** [comment]
Is there any instructions to install workers on self-hosted AFFiNE? Thanks!
