### ISSUE TITLE
​ group pages with tags is empty when no tags in new affine vault

### ISSUE THREAD

**Issue by aiyou9** [toeverything/AFFiNE#6688]
### What happened?

when new user in affine, it may be Confusing. and why not priviod a default group to collect page with no tags?
it happened in last window app 
![image](https://github.com/toeverything/AFFiNE/assets/15712822/90ee27fb-8d3e-4c7f-b2c2-f0665b47c275)
may be in all platforms

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

### Relevant log output

```shell
just system desgin talk without log
```

### Anything else?

nothing

**Comment by JimmFly** [comment]
Thank you very much for your feedback, I decided to implement it.

**Comment by JimmFly** [comment]
This issue has been fixed in the latest version, please update your client.
