### ISSUE TITLE
[improvement]: support shortcuts "Command + Backspace" to remove paragraphs consecutively

### ISSUE THREAD

**Issue by chenmoonmo** [toeverything/AFFiNE#672]
### 1~3 main use cases of the proposed improvement

When I need to selectively delete paragraphs (e.g. several consecutive items in a list), I usually use the "Command + Backspace" shortcut, which allows me to easily delete consecutive paragraphs by holding down Command while clicking Backspace a few times.
Affine can not consecutively remove paragraphs by this way.

https://user-images.githubusercontent.com/36295999/210746439-386f1300-1d7c-4e71-ad65-4f2c54bb83fe.mov

**Comment by doodlewind** [comment]
Supported in https://github.com/toeverything/blocksuite/pull/729
