### ISSUE TITLE
​Recycle bin improvements

### ISSUE THREAD

**Issue by EnterMan123** [toeverything/AFFiNE#6739]
### Description

Supports multi-select document recovery and deletion
And you can delete all documents in the recycle bin with one click

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
In all docs， you can hold `shift` + `mouse left button` to batch select.

**Comment by EYHN** [comment]
I think the trash should also support batch operations. But it does not yet

**Comment by JimmFly** [comment]
This feature has been introduced in the latest version, please update and enjoy utilising it.
