### ISSUE TITLE
​doc input: `---` + `\return` will trigger separator, but `---` with `\up` will not

### ISSUE THREAD

**Issue by alissa-tung** [toeverything/AFFiNE#6749]
### What happened?

​doc input: `---` + `\return` will trigger separator, but `---` with `\up` will not

`\return` for `↵` and `\up` for `↑`

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by EYHN** [comment]
I think this is by design, the editor will not convert your markdown to block until you press Enter.
