### ISSUE TITLE
Often get logged out​ of the app on macOS

### ISSUE THREAD

**Issue by juliusvaart** [toeverything/AFFiNE#6758]
### What happened?

We've got issues that we get logged out of the app often. This makes Affine really harsh to use. We need to stay logged in on our macOS desktop apps for it to replace our previous tools.

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
This is a bug, we have fixed it in 0.14, we will release 0.14 in a few days, please be patient.
