### ISSUE TITLE
​OIDC support for self-hosted SSO

### ISSUE THREAD

**Issue by brunostjohn** [toeverything/AFFiNE#6760]
### Description

Hi!

I've been using Affine for a while in the self hosted version and have been enjoying it a lot! It's great.

One thing that's missing is OIDC based SSO. I personally use Authentik but others may use something else.

### Use case

OIDC backed SSO for self hosted installs. Lots of accounts on services are annoying.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
We have a lot of work now, and we evaluate this requirement as low priority, but our account system is modular, if you are familiar with nodejs, you can provide us with a PR, and you can also discuss it [here](https://github.com/toeverything/AFFiNE/discussions/1142).

**Comment by OliverRM** [comment]
As I have seen, this has now been implemented. Thanks for the effort! 🥳

In lack of documentation, let me note the most important for anyone who wants to use it in future: It can be activated by navigating in the Admin Panel to _Settings_ -> _OAuth_ and then configuring _OIDC OAuth provider config_. The scheme for the config is as follows:
```
{
  clientId: string;
  clientSecret: string;
  issuer: string;
  args?: {
    scope?: string; // Default: openid profile email
    claim_id?: string; // Default: preferred_username
    claim_email?: string; // Default: name
    claim_name?: string; // Default: email
  }

```

`issuer` is used to fetch `/.well-known/openid-configuration`, therefore `${issuer}/.well-known/openid-configuration` must point to a valid config.

**Comment by maxhoheiser** [comment]
hi @OliverRM - i am currently trying to setup OpenID connect with Entra ID, do you know where I need to point the redirect URL from entra id to affine to?

**Comment by OliverRM** [comment]
Check [the docs on OAuth](https://docs.affine.pro/self-host-affine/administer/oauth-2-0)

It should point to `/oauth/callback`

**Comment by pihomeserver** [comment]
Using PocketID as a provider I have set the callback url to the `https://<my domain>/oauth/callback` but I have a `Invalid callback URL, it might be necessary for an admin to fix this.`
I'm using Affine 0.26.6 and PocketID is successfuly used for other self hosted apps
