### ISSUE TITLE
​upload video, pdf failed, but image success

### ISSUE THREAD

**Issue by StudyingLover** [toeverything/AFFiNE#6765]
### What happened?

I ​upload video, pdf failed, but image success on my self-hosted server. If needed, I can help you to find out why.

### Distribution version

Linux

### Are you self-hosting?

- [X] Yes

**Comment by EYHN** [comment]
Please provide your browser console log.

**Comment by StudyingLover** [comment]
I draged my pdf file to affine and not work. There is no log in my web console log, and this is the /graphql response 
```
{"data":{"workspace":{"publicPages":[]}}}
```

**Comment by JimmFly** [comment]
Can this problem be reproduced in the latest version?
If you are using the web version, will you still have this problem with the latest chrome browser?

**Comment by StudyingLover** [comment]
success in  the latest version,thanks.
