### ISSUE TITLE
self-host:​ GraphQLError: Cannot query field "copilot" on type "UserType".

### ISSUE THREAD

**Issue by alissa-tung** [toeverything/AFFiNE#6774]
### What happened?

Failed to load quota and Load error in UI, at settings and avatar drop down menu

latest `ghcr.io/toeverything/affine-graphql:beta`

```
[Nest] 133  - 05/06/2024, 8:56:56 AM   ERROR [GQLLoggerPlugin] GraphQL Unhandled Error
GraphQLError: Cannot query field "copilot" on type "UserType".
```

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
[Nest] 133  - 05/06/2024, 8:56:56 AM   ERROR [GQLLoggerPlugin] GraphQL Unhandled Error
GraphQLError: Cannot query field "copilot" on type "UserType".
```

**Comment by EYHN** [comment]
We are aware of this issue, please use the `stable` image for now.

**Comment by kbzowski** [comment]
The same errors happens with ` ghcr.io/toeverything/affine-graphql:stable`

**Comment by crooowned** [comment]
same here on stable image

**Comment by EYHN** [comment]
fixed in #6796

**Comment by yihaozhadan** [comment]
I'm facing same issue even it is stable image.

**Comment by qweryty** [comment]
I just deployed self-hosted version and still facing this issue on both stable and beta versions. Should I create a new issue or maybe you can reopen this one?

**Comment by tiritto** [comment]
Same issue here. Stable as well.

**Comment by davidcampos** [comment]
The same issue on stable.

**Comment by xu756** [comment]
> 稳定版上存在同样的问题。

metoo

**Comment by Ftrybe** [comment]
Same issue here. Stable as well.

**Comment by o10s** [comment]
Same issue on latest stable branch

**Comment by 662** [comment]
Same issue on latest stable branch

**Comment by carnevlu** [comment]
Same issue on latest stable branch

**Comment by xu756** [comment]
Same issue here. Stable as well.

**Comment by Piratski** [comment]
fix it, when re-pull stable image

**Comment by tienskowl** [comment]
I'm using the latest stable version and am facing this issue as well

**Comment by ipv6ok** [comment]
use The same errors happens with  ghcr.io/toeverything/affine-graphql:stable   by 20250110 ,same  errors. self too,but configure openai base url

**Comment by madduck** [comment]
I don't have nor would I want "Open"AI integration. I get the same error.

**Comment by Liam-Hegarty** [comment]
Seeing this issue on the current stable build
