### ISSUE TITLE
[feature]:  In paper mode, mouse drag and drop can achieve grid item.

### ISSUE THREAD

**Issue by SaikaSakura** [toeverything/AFFiNE#68]
### 1~3 main use cases of the proposed feature

Drag block as item like:

https://user-images.githubusercontent.com/11530942/182591704-5fd74d17-a2fc-4800-b80c-ee80c2344930.mp4

https://user-images.githubusercontent.com/11530942/182591738-8050aaa7-a6c0-4b0e-b159-eea1a4d2ee23.mp4

### Ideas for solution

Get nearest block use Binary Tree Level Order Traversal and dom bounding client rect. Add grid or grid item for different block.

**Comment by mitsuhatu** [comment]
link to: [Issues#92](https://github.com/toeverything/Ligo-Virgo/issues/558)
