### ISSUE TITLE
[bug]: pnpm install fails on chalk-next

### ISSUE THREAD

**Issue by ntompkins** [toeverything/AFFiNE#683]
### Describe the bug

New instances fail to install the npm package chalk-next as it is now deprecated.

### To Reproduce

Following the installation instructions found here: https://docs.affine.pro/affine/developer-docs/setup

```
git clone https://github.com/toeverything/AFFiNE.git
cd AFFiNE
git checkout v0.0.1-alpha-Abbey-Wood
```

```
$ pnpm install
pnpm install
Scope: all 4 workspace projects
 WARN  GET https://registry.npmjs.org/chalk-next/-/chalk-next-6.1.5.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/chalk-next/-/chalk-next-6.1.5.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/chalk-next/-/chalk-next-6.1.5.tgz: Not Found - 404

No authorization header was set for the request.
Progress: resolved 60, reused 60, downloaded 0, added 0
```

I visited https://www.npmjs.com/package/chalk-next to make sure the package is available and saw npm has removed the package due to "malicious code."

### Screenshots

![image](https://user-images.githubusercontent.com/12280402/211089716-6f41b62b-0ab1-4832-b057-8d14adbb2140.png)

### Expected behavior

`$ pnpm install` should succeed

### Platform

Ubuntu 20.04

### Browser

Firefox

### Additional context

Since this is a dependency issue, it might be resolved by that package maintainer, but I wanted to draw attention to the failing install.

**Comment by darkskygit** [comment]
We have withdrawn the original tag and released the latest commit to fix the problem with the tag of the same name, and updated the online version. Please feel free to use it.
If you want to update the tag of the local repository, please delete the repository folder and reclone, or use the following command line to synchronize the latest online tag: `git fetch --all --prune --tags -f`
