### ISSUE TITLE
Feature request: Add search for notes and pin notes in sidebar​

### ISSUE THREAD

**Issue by helmi-s0** [toeverything/AFFiNE#6838]
### Description

I love the concept of accessibility of notes in the sidebar. Where I can find related notes, make notes, and attach notes to the main work area from the sidebar (something like what Logseq does). I believe it will be a great feature that Affine need, especially for writers. I hope this feature can be implemented in Affine. Thanks for listening.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
you can favorite docs, organize docs, tag docs in side bar
