### ISSUE TITLE
Jump to a new page and return, the scrollbar is reset

### ISSUE THREAD

**Issue by FurryWolfX** [toeverything/AFFiNE#6848]
### What happened?

Double-click `Link Doc` to jump to a new page, press `Ctrl+[` to return to the old page and the position of the scrollbar is reset.

I would like to be able to go back to where I clicked on the `Link Doc` in order to continue reading.

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by JimmFly** [comment]
This feature was added in the latest version of AFFiNE, feel free to use it.
