### ISSUE TITLE
[bug]: `Ctrl/⌘ + ?` should be replaced with `Ctrl/⌘ + K`

### ISSUE THREAD

**Issue by MarvinJWendt** [toeverything/AFFiNE#687]
### 1~3 main use cases of the proposed improvement

As a person who is using a German keyboard, I cannot type the shortcut <kbd>CTRL</kbd>+<kbd>?</kbd>. The <kbd>?</kbd> key does not exist on the German keyboard, and is a shortcut by itself (<kbd>SHIFT</kbd>+<kbd>ß</kbd>).

### Ideas for solution

I propose to change the shortcut to something else. GitHub for example uses <kbd>CTRL</kbd>+<kbd>K</kbd> and <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>K</kbd> inside text boxes to work around the conflict with creating a link.

### what types of users can benefit from using your proposed improvement

users that use a non-english keyboard layout

### Additional context

<kbd>CTRL</kbd>+<kbd>K</kbd> and <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>K</kbd> are commonly used to search for other pages, and to open quick search menus.

**Comment by MarvinJWendt** [comment]
Hi, I wasn't sure if I should label this as a bug or as an improvement. I decided to choose `improvement`, because there is no broken feature. I hope that fits.

**Comment by MarvinJWendt** [comment]
Oh, it seems like <kbd>CTRL</kbd>+<kbd>K</kbd> is already working 😅 
But it's not shown in the shortcuts help menu, maybe it can be added there?

**Comment by doodlewind** [comment]
Thanks for your feedback! I'm a bit confused since I can see the `CMD-K` hint on latest [AFFiNE Alpha](https://pathfinder.affine.pro/) page:

![image](https://user-images.githubusercontent.com/7312949/211201653-7bfca9df-b177-4bf7-b86e-5b8d94618e46.png)

And it seems that we don't have a `CMD-?` binding, because in American keyboard layout, neither can we input a `?` character without pressing `SHIFT`. Could the `CMD/CTRL-K` hotkey meet your needs for now?

**Comment by MarvinJWendt** [comment]
Hi, the alpha page has this paragraph:

![image](https://user-images.githubusercontent.com/31022056/211203646-10dec01b-b563-4cd5-8e62-d0e503d44db8.png)

Yes the `CMD/CTRL-K` fits, but the shortcut menu only shows `CMD/CTRL-K` for creating links, not for opening the quick search :)

**Comment by ShortCipher5** [comment]
Hi there, this is actually a placeholder "?" and should have been replaced with "K". 
I thought this was resolved with #654, so thanks for bringing this up, we'll look to get it updated ASAP.

So to clarify "K" is the correct key, and not "?".

**Comment by ShortCipher5** [comment]
This has been resolved, thank you.
