### ISSUE TITLE
Run AI locally or through API​

### ISSUE THREAD

**Issue by metahleon** [toeverything/AFFiNE#6872]
### Description

It would be interesting to have AFFiNE working as an AI UI environment such as WebUI which can directly be connected.

### Use case

User's running local LLM's and who have need for privacy.

Creatives who can link outputs directly into their notes/second brain.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AreChen** [comment]
I also hope to have this function. You can configure the API yourself to use the AI ​​function, similar to the [novel project](https://github.com/steven-tey/novel).

**Comment by simseb** [comment]
An API config (GPT or local) via envars would be awesome...

**Comment by forehalo** [comment]
duplicated #7705

**Comment by LeoGarcia109** [comment]
Yes, Craft is already doing this and it was very good!

**Comment by nauti23** [comment]
love the self-hosted version, just need the option to use local models via ollama interface api etc. like open webUi, flowise, n8n you name it
