### ISSUE TITLE
​After closing the left sidebar, the back and forward shortcut keys no longer work. Is this a special design to lock the page?

### ISSUE THREAD

**Issue by aiyou9** [toeverything/AFFiNE#6877]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/15712822/87d02db4-cd03-412f-ae38-d76f6e4437ae)
![image](https://github.com/toeverything/AFFiNE/assets/15712822/31b9ad25-7c8d-442a-ad33-1c96b6f734d3)

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

### Anything else?

I did not continue to test whether other shortcuts behave normally after the left sidebar is closed.

**Comment by JimmFly** [comment]
close with fixed
