### ISSUE TITLE
Ability to insert a "drawing" block for hand-written notes/drawings into the Page env.

### ISSUE THREAD

**Issue by justatechie** [toeverything/AFFiNE#6883]
### Description

Having the whiteboard is great, but it lacks easy organization of handwritten notes/drawings. It would be awesome to be able to insert a "drawing" block into the Page environment so if a diagram needs to be quickly written down in-line with the text, it can be done rather than needing to later remember that it's only in the whiteboard canvas.

### Use case

As a student, this would be huge for nearly all of my classes. Additionally for work, it would be great to be able to ditch my physical notebook since I need to be able to quickly sketch things out while also taking notes. Less device switching is always ideal!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
like this?

https://github.com/toeverything/AFFiNE/assets/13579374/1a51733a-d510-4145-9ba6-176bb454709e

**Comment by justatechie** [comment]
omg yes, sorry I'm blind 😅.
