### ISSUE TITLE
Local first app why doesn't supports folder and git?

### ISSUE THREAD

**Issue by lucasjinreal** [toeverything/AFFiNE#6884]
Local first app why doesn't supports folder and git?

Which means, using same folder heierechy in system?

**Comment by EYHN** [comment]
Our data is stored in a database rather than scattered files.

Local first means you can edit offline, then sync with your collaborators when you online, and automatically merging your edits.

Scattered files cannot do this offline collaboration, we use specific databases to store your edit data.

**Comment by lucasjinreal** [comment]
I think database hard to manage, using files can sync with git, just like obsidian.
