### ISSUE TITLE
​Self-hosted: Invite email link can be re-used, potential DoS

### ISSUE THREAD

**Issue by dennorske** [toeverything/AFFiNE#6889]
### What happened?

When a user is invited to the platform, the user who receives the invite can re-use the invite link multiple times. Every time the user uses that link, a new email is sent out to the person who invited him, to inform that the invite was accepted.

**Steps to reproduce**
1. Invite a new user
2. New user rapidly spam-clicks the invite link (opens multiple tabs).
3. The equivalent amount of emails are sent to the inviter, to inform the user has accepted the invitation.

See the attached screenshot for a sample:

![image](https://github.com/toeverything/AFFiNE/assets/3287543/b4448324-5e3f-4eee-9e4e-7f783df4bff0)

### Distribution version

Linux

### Are you self-hosting?

- [X] Yes

**Comment by simeneriks1** [comment]
This seems fixed now, thank you.
