### ISSUE TITLE
[improvement]: Unify naming according to convention

### ISSUE THREAD

**Issue by DiamondThree** [toeverything/AFFiNE#690]
### 1~3 main use cases of the proposed improvement

There are some inconsistency in our current codebase, one example is about file naming:

<img width="248" alt="image" src="https://user-images.githubusercontent.com/24630517/211231073-68431009-acb5-402f-ac40-0050869d270a.png">

### Ideas for solution

We need to unify the naming above to `ConfirmProvider.tsx`  / `GlobalModalProvider.tsx`.

**Comment by suyanhanx** [comment]
I want to take this.
