### ISSUE TITLE
self-host: GraphQLError: Cannot query field "signUp" on type "Mutation". after update docker images​

### ISSUE THREAD

**Issue by alissa-tung** [toeverything/AFFiNE#6901]
### What happened?

GraphQLError: Cannot query field "signUp" on type "Mutation". after update docker images​

Internal Server Error

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Anything else?

0.14.0-beta.5 is okay, 0.15.0-beta.4 and newer is not

**Comment by darkskygit** [comment]
please provide a screenshot or video of how you triggered the error

**Comment by agfianf** [comment]
using version 0.14.6
<img width="922" alt="Screenshot 2024-05-17 at 21 55 52" src="https://github.com/toeverything/AFFiNE/assets/43182086/de02a09e-fcc2-4353-bf25-8961b863b718">
<img width="1177" alt="Screenshot 2024-05-17 at 21 56 18" src="https://github.com/toeverything/AFFiNE/assets/43182086/d07cbab4-b09c-479c-a6b3-4af8ba27915d">
cc: @darkskygit

**Comment by darkskygit** [comment]
> using version 0.14.6 <img alt="屏幕截图 2024-05-17 at 21 55 52" width="922" src="https://private-user-images.githubusercontent.com/43182086/331639870-de02a09e-fcc2-4353-bf25-8961b863b718.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjEyMzMsIm5iZiI6MTcxNTk2MDkzMywicGF0aCI6Ii80MzE4MjA4Ni8zMzE2Mzk4NzAtZGUwMmEwOWUtZmNjMi00MzUzLWJmMjUtODk2MWI4NjNiNzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE1NDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNWE3MjdjZTRiZmE4NmJjYmQ1Y2I3MmVkMWFhMGZmZWUyMWNmZjFmZjU0MzQzNTMwYWRhODYwNDkwMTE2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x2mFbqC0aFx1ck6m6C4eT8JEIjOo8twX1gt9nvOlmUc"> <img alt="屏幕截图 2024-05-17 at 21 56 18" width="1177" src="https://private-user-images.githubusercontent.com/43182086/331640093-d07cbab4-b09c-479c-a6b3-4af8ba27915d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjEyMzMsIm5iZiI6MTcxNTk2MDkzMywicGF0aCI6Ii80MzE4MjA4Ni8zMzE2NDAwOTMtZDA3Y2JhYjQtYjA5Yy00NzljLWE2YjMtNGFmOGJhMjc5MTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE1NDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZTVjZmIwY2QwZmMwYWNkN2Y0YzJmMWRmYTRkMTNjMzI2ZTU5NTE2YjU2ZjZlZjE3MTY4ZTM5YWI1N2IzOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UTtZDpXU11JUx7tblwgsDmrFW91bYqXoETYvgGITbD8"> cc: @darkskygit

Previously, this API existed as an internal API and has been removed from the current stable version for security reasons.

**Comment by alissa-tung** [comment]
> > using version 0.14.6 <img alt="屏幕截图 2024-05-17 at 21 55 52" width="922" src="https://private-user-images.githubusercontent.com/43182086/331639870-de02a09e-fcc2-4353-bf25-8961b863b718.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjEyMzMsIm5iZiI6MTcxNTk2MDkzMywicGF0aCI6Ii80MzE4MjA4Ni8zMzE2Mzk4NzAtZGUwMmEwOWUtZmNjMi00MzUzLWJmMjUtODk2MWI4NjNiNzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE1NDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNWE3MjdjZTRiZmE4NmJjYmQ1Y2I3MmVkMWFhMGZmZWUyMWNmZjFmZjU0MzQzNTMwYWRhODYwNDkwMTE2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x2mFbqC0aFx1ck6m6C4eT8JEIjOo8twX1gt9nvOlmUc"> <img alt="屏幕截图 2024-05-17 at 21 56 18" width="1177" src="https://private-user-images.githubusercontent.com/43182086/331640093-d07cbab4-b09c-479c-a6b3-4af8ba27915d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjEyMzMsIm5iZiI6MTcxNTk2MDkzMywicGF0aCI6Ii80MzE4MjA4Ni8zMzE2NDAwOTMtZDA3Y2JhYjQtYjA5Yy00NzljLWE2YjMtNGFmOGJhMjc5MTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE1NDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZTVjZmIwY2QwZmMwYWNkN2Y0YzJmMWRmYTRkMTNjMzI2ZTU5NTE2YjU2ZjZlZjE3MTY4ZTM5YWI1N2IzOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UTtZDpXU11JUx7tblwgsDmrFW91bYqXoETYvgGITbD8"> cc: @darkskygit
> 
> Previously, this API existed as an internal API and has been removed from the current stable version for security reasons.

Thank you. And I am curious about is there any way to sign up an account without setting email provider?

**Comment by alissa-tung** [comment]
If you want to use Google Gmail as email provider

```
      - MAILER_HOST=smtp.gmail.com
      - MAILER_PORT=587
```

and `MAILER_USER` is you email, `MAILER_PASSWORD` is you Google password for app, 16 characters without space
