### ISSUE TITLE
​代码块中&符号展示有问题

### ISSUE THREAD

**Issue by imxw** [toeverything/AFFiNE#6923]
### What happened?

<img width="769" alt="image" src="https://github.com/toeverything/AFFiNE/assets/16207029/ea6ef683-08d6-47a1-8577-4dda5799071e">

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

**Comment by JimmFly** [comment]
This is the font [space-mono](https://www.colophon-foundry.org/custom-projects/space-mono) used in AFFiNE's code block.
