### ISSUE TITLE
​Text wipe on iOS Safari browser

### ISSUE THREAD

**Issue by houshasen** [toeverything/AFFiNE#6935]
### What happened?

Type a word with incorrect spelling and hit space will wipe the text on iOS Safari browser web app. 

Using correct spell won’t have issue. The same issue is not observed on other web app or web form filling.

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Safari

### Are you self-hosting?

- [ ] Yes

**Comment by CatsJuice** [comment]
If possible, please provide a screen recording to help us understand better. 
By the way, the current mobile support is not perfect. We plan to have mobile support in the future. For now, we strongly recommend that you use a desktop browser or client to visit.

**Comment by houshasen** [comment]
Thank you for following up. Here is video.

https://github.com/toeverything/AFFiNE/assets/48835895/2a07ee27-6a5e-464e-872c-5ebb22984d61
