### ISSUE TITLE
​Clicking on embedded pdf link doesn't redirect to default pdf app

### ISSUE THREAD

**Issue by Abdurrafey-Siddiqui** [toeverything/AFFiNE#6945]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/74437315/d2cb8b2c-ee1f-48bd-b793-64c955b2dd0e)

See image above. I have my default pdf app as microsoft edge, so thats what i expected it to open in.

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by pengx17** [comment]
Opening attachments such as PDF in client is not yet supported and blocked in https://github.com/toeverything/AFFiNE/blob/9a171502164132394e6864137689bd3a19b9d322/packages/frontend/electron/src/main/security-restrictions.ts#L39. In the long term we will support PDF viewer later.

For now I think maybe a workaround is to open a new electron window to serve the pdf contents.
