### ISSUE TITLE
[Question] Having issue load the official site.

### ISSUE THREAD

**Issue by Lantianyou** [toeverything/AFFiNE#697]
Hi everyone, I have met this issue currently using latest Chrome Browser. There is no warning or error in the console. I suppose the screenshot can illustrate the problem. It would be best if this issue be helpful for someone to solve the problem.
![image](https://user-images.githubusercontent.com/37259750/211257007-a74cc18f-9ac6-4f73-928e-583fc7f14a2e.png)

**Comment by Lantianyou** [comment]
BTW, I found the API all responded successfully. 
![image](https://user-images.githubusercontent.com/37259750/211257861-028f232b-8dd0-41ad-bf26-22460969b7d7.png)

**Comment by doodlewind** [comment]
Did not reproduce here. How about performing a force refresh with `cmd-shift-R`?

**Comment by Lantianyou** [comment]
I tried, still not working. But I found sometimes the image just flashed then the area fallback to blank.
![image](https://user-images.githubusercontent.com/37259750/211258519-61e0386c-55dd-4b5a-83de-dd44ae941367.png)

**Comment by Lantianyou** [comment]
I think we should expect this image display here.
![image](https://user-images.githubusercontent.com/37259750/211258758-8ce6642c-84c3-4d69-a891-ce5acd572f3e.png)

**Comment by Lantianyou** [comment]
Maybe this issue is related my browser extensions, since I can load the official site as expected in incognito mode. However, in that case, I think there might be warning or errors in the console.

**Comment by tzhangchi** [comment]
@Lantianyou Thank you for your feedback on the AFFiNE official website. We have launched a new official website https://affine.pro/. We will close this issue and look forward to your feedback on the new official website.

**Comment by Lantianyou** [comment]
Cool. As the issue is quite werid to re-produce and have little influence on others, I will close this issue. Your team is amazing. Keep making wonderful things!
