### ISSUE TITLE
​Zoom In - Not Working

### ISSUE THREAD

**Issue by johwconst** [toeverything/AFFiNE#6979]
### What happened?

When you press CTRL + "-" is possible out zoom, but CTRL + "+" is not working to zoom in.

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by johwconst** [comment]
Same problem in 0.14.9

**Comment by jesielviana** [comment]
Same problem in 0.14.9 in Linux Fedora.

**Comment by matthewbsparks** [comment]
Coming here to report that I am having this same issue. Ctrl + "-" works fine for zooming out, but I am not able to Zoom in. Asking the AI assistant simply resulting in the shortcut recommendations, but also mentioned using some "magnifying class" icons for zooming from the GUI, but either I am bordering on functionally blind (certainly not impossible), or these icons don't exist in the main UI.
