### ISSUE TITLE
Onboarding popup close button almost not visible​

### ISSUE THREAD

**Issue by jeferson-sb** [toeverything/AFFiNE#6980]
### What happened?

I was experimenting the app on Windows, could not find a option to remove the "Meet AFFiNE AI" dialog, then I logged into macOS and noticed that there is close button but is **white**, which makes it hard to see since the video is also white.

![image](https://github.com/toeverything/AFFiNE/assets/30840709/3b874f49-623f-4638-99e2-d937d8243ce3)

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

### Anything else?

I think it is related to props of this component

https://github.com/toeverything/AFFiNE/blob/4156b3ae890e040d3444d238374d6517e1c1fcd1/packages/frontend/core/src/components/affine/ai-onboarding/edgeless.dialog.tsx#L96-L118

**Comment by vikashsprem** [comment]
@jeferson-sb  I am not getting such a problem that you mentioned. I tested on Windows and Linux as well, the cross mark is visible clearly. see the attachment. Could you please specify where did you exactly get this problem?

![Screenshot from 2024-05-20 22-07-50](https://github.com/toeverything/AFFiNE/assets/106796672/75e7347d-e39e-43bf-be49-ac853c3edcb1)

**Comment by jeferson-sb** [comment]
@vikashsprem Just downloaded the app directly from the site and the dialog shows as soon as the apps starts. I think this issue happens only if you're system is on dark mode apparently.
