### ISSUE TITLE
​New Feature Request: Folder Mode

### ISSUE THREAD

**Issue by houshasen** [toeverything/AFFiNE#6981]
### Background
This concept is inspired by two main factors:

**Familiarity with Folder Structures**: We are accustomed to using folder structures on computers daily. This habitual use influences how we organize and conceptualize information, making folder structures a natural choice for many of us.

**Heptabase's Nested Whiteboard**: The second source of inspiration is Heptabase's nested whiteboard, which functions similarly to a hierarchical folder system. This approach effectively mirrors the organizational benefits of traditional folder structures.

### Request

Please consider creating a Folder mode like Page, Edgeless Mode. This gives true visual folder organization view, but in a AFFiNE way.

### Detail 
**Folder Pane**

- The primary purpose of this view is to facilitate easy navigation through linked documents, whether they are networked or hierarchical.
- Each linked document will be represented by a folder-equivalent entity.
- Notes at the current level will be displayed as note entities.
- Therefore, when switching to folder mode in any document, users can quickly see the number and types of notes present, as well as the documents being referenced on it.

**Folder entity**

- Instead of merely displaying a folder icon with the name of each linked document, we should provide additional information that helps user to navigate. For example, we could not only shows the linked document name but also includes notes, and linked doc names within the folder entity, similar to Heptabase.

**Note entity**

- Firstly, we can utilize the Grouping feature created on Edgeless to display grouped notes here as well.
- The amount and manner of displaying note content is an interesting design decision. For instance, we could include a description property and each look like index card (like Scrivener),  perhaps show the first couple of paragraphs or solely just Note title alone.

**Other files**
Other blocks can also be shown grouped here e.g. PDF block, Media block etc.

**Note View**

To complete the use case, we need a way to interact with the notes. Therefore, each note entity should have a "maximize" icon. Clicking on this icon will bring the note into full view or a part of the pane, allowing us to fully edit it.

### Use case

The real-world use case for this feature is akin to a desktop folder structure, enabling much quicker access to specific notes, especially when managing a large number of them.

For instance, I currently have over 10 notes in one document, each containing multiple paragraphs. Additionally, I may have some media files etc. In Edgeless mode, these elements are spread out. If I want to view all of them and set the screen to fit the size, I can't read anything. If I zoom in to a readable level, I have to scroll around. With Folder Mode, everything will be on one screen. I can simply choose a note I want and start editing.
It also offers those who want real folder structure to experience that.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
@hwangdev97 take a look
