### ISSUE TITLE
CAN'T Use Ctrl+C to COPY in ​self-host

### ISSUE THREAD

**Issue by rcqed** [toeverything/AFFiNE#6984]
### What happened?

COPY is not work, I CAN'T Use Ctrl+C or Ctrl+X to COPY, and I can't click the copy button to copy, but the Ctrl+V is work.

versions: stable-7e7a412

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:stable-7e7a412
    container_name: affine_selfhosted
    command:
      ['sh', '-c', 'node ./scripts/self-host-predeploy && node ./dist/index.js']
    ports:
      - '3010:3010'
      - '5555:5555'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      # custom configurations
      - /volume1/docker/affine/self-host/config:/root/.affine/config
      # blob storage
      - /volume1/docker/affine/self-host/storage:/root/.affine/storage
    logging:
      driver: 'json-file'
      options:
        max-size: '1000m'
    restart: always
    environment:
      - NODE_OPTIONS="--import=./scripts/register.js"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgres://affine:affine@postgres:5432/affine
      - NODE_ENV=production
      - AFFINE_ADMIN_EMAIL=test@affine.pro
      - AFFINE_ADMIN_PASSWORD=123456789
      - AFFINE_SERVER_HOST=0.0.0.0
  redis:
    image: redis:6.0.20-bookworm
    container_name: affine_redis
    restart: always
    volumes:
      - /volume1/docker/affine/self-host/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:16.2-bookworm
    container_name: affine_postgres
    restart: always
    volumes:
      - /volume1/docker/affine/self-host/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U affine']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: affine
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata

```

### Anything else?

![image](https://github.com/toeverything/AFFiNE/assets/40952828/8d3f41a1-6675-47f2-8e7b-80b63c5f44b4)

**Comment by rcqed** [comment]
stable-7e7a412

**Comment by Xyndra** [comment]
+1

**Comment by vjalmr** [comment]
I had this issue as well, and found out that certain features are disabled if you are not in an HTTPS environment.

My solution was to install this container: [Docker Reverse Proxy](https://github.com/luisaveiro/docker-reverse-proxy)
And followed the instructions. 

It's basically a [Caddy Server](https://caddyserver.com/), which has some sane defaults and is easy to set up. 

After I set that up, copy, paste, cut, and images were no longer a problem.

Note: This was running on a linux box, though I don't think that will make a difference besides the hosts setup. I am not familiar with that on Windows.

**Comment by rcqed** [comment]
> I had this issue as well, and found out that certain features are disabled if you are not in an HTTPS environment.
> 
> My solution was to install this container: [Docker Reverse Proxy](https://github.com/luisaveiro/docker-reverse-proxy) And followed the instructions.
> 
> It's basically a [Caddy Server](https://caddyserver.com/), which has some sane defaults and is easy to set up.
> 
> After I set that up, copy, paste, cut, and images were no longer a problem.
> 
> Note: This was running on a linux box, though I don't think that will make a difference besides the hosts setup. I am not familiar with that on Windows.

you are right, it works when i use the HTTPS

**Comment by rcqed** [comment]
> Status

it just cant use when we use the http, and you have review it on HTTP, not https maybe

**Comment by EYHN** [comment]
This is because the browser does not allow web pages to access your clipboard in http environment. There's nothing affine can do at this point

**Comment by Xyndra** [comment]
Yes it can! It can notify someone what is happening and why, and it can also hold a local clipboard on the page.
