### ISSUE TITLE
​Mac App Slow compared to Web App 

### ISSUE THREAD

**Issue by houshasen** [toeverything/AFFiNE#6986]
### What happened?

Mac App loads slow at times including image loading, new image uploading, and switching between workspace. The same process on Web App is instant. 

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
We have identified this issue and are working on a fix.

**Comment by EYHN** [comment]
should fixed by https://github.com/toeverything/AFFiNE/pull/6951

**Comment by EYHN** [comment]
the fix will be included in next release
