### ISSUE TITLE
[improvement]: Convenient installer packages - such as brew cask

### ISSUE THREAD

**Issue by MaxzMeng** [toeverything/AFFiNE#70]
### 1~3 main use cases of the proposed improvement

I want to try this software, but I can't find an obvious entry to install or download the installation package.
Generally speaking, I'm used to using `brew install pkgname --cask` to install the software I want, so I wonder if it's possible to provide a way to install it as well?

**Comment by darkskygit** [comment]
thank you for your attention, we will provide local executable files available for several common platforms in the near future
