### ISSUE TITLE
Vercel integration for forked repository

### ISSUE THREAD

**Issue by DiamondThree** [toeverything/AFFiNE#700]
Currently, the AFFiNE repository is nothing more than a Next app that can be statically hosted. Also, in our next major release targeting local-first capabilities, the AFFiNE app still won't require registering an account to use.

So, this enables the possibility to self-host AFFiNE on different platforms. This is something we *welcome*! For a static-deployable version, we thought Vercel may be a good candidate. For now, [BlockSuite](https://github.com/toeverything/blocksuite) has also added the official Vercel integration, so what we can do could be similar: making the AFFiNE bundle capable to be built on other platforms (Vercel, CloudFlare Page, .etc.), so that every forked repository could be deployed to these platforms as well.

Welcome to share your thought on this!

**Comment by teobler** [comment]
https://github.com/toeverything/AFFiNE-docs/pull/13 PR raised, kindly check.
@DiamondThree
