### ISSUE TITLE
Readwise Integration

### ISSUE THREAD

**Issue by houshasen** [toeverything/AFFiNE#7000]
### Description

I've read that Web Clipper is not the highest priority at the moment. I am uncertain if this involves more or less programming effort, but if it's less, I wonder if the team could consider integrating "Readwise."

### Use case

This would allow seamless workflow from web content integrated into AFFiNE.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RichardQian** [comment]
https://chromewebstore.google.com/detail/affine-web-clipper/mpbbkmbdpleomiogkbkkpfoljjpahmoi
It's released last week, if you are still interested, welcome to have a try


Readwise integration as well, you can now manually import stuff from readwise, it's in the integration section in settings
