### ISSUE TITLE
Issue : Hover Effect Missing on Logo in Footer​

### ISSUE THREAD

**Issue by bro-maanii** [toeverything/AFFiNE#7012]
## Summary
The hover effect is present on the logo in the navbar but is missing on the same logo in the footer.

## Details
When hovering over the logo in the navbar, a hover effect is correctly displayed. However, the same logo in the footer does not show the hover effect, leading to an inconsistent user experience.

## Steps to Reproduce

1- Navigate to any page with the navbar and footer.
2- Hover over the logo in the navbar and observe the hover effect.
3- Scroll down to the footer.
4- Hover over the logo in the footer and note the absence of the hover effect.
## Impact
The inconsistency in hover effects can lead to a disjointed user experience. Users may expect the same interactive feedback on similar elements throughout the site. Ensuring that the hover effect is applied to the logo in both the navbar and footer will provide a more cohesive and polished experience.

## Video Demo:
https://github.com/toeverything/AFFiNE/assets/125199246/4c709a58-3342-4a6c-88ef-f329d04976e8

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Hardik-Kumar20** [comment]
This issue has been fixed
