### ISSUE TITLE
Designate icons and covers for documents, with support for uploads.

### ISSUE THREAD

**Issue by EnterMan123** [toeverything/AFFiNE#7014]
### Description

Allows selection from preset emoticons and covers, and users can also upload their own images to use as icons and covers. Similar to the effect in Notion and Anytype

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by HeJiachen-PM** [comment]
The cover image and cover icon aren't yet supported because it would be hard to implement them in the edgeless mode. We are still thinking about the product design of cover blocks in edgeless so that such things can be available.
