### ISSUE TITLE
Ability to collapse the Favorites and Collections modules in the document list on the left side

### ISSUE THREAD

**Issue by EnterMan123** [toeverything/AFFiNE#7015]
### Description

When there are many documents on the left side, it becomes very cluttered and crowded. This small change allows us to manage them flexibly

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
@hwangdev97 Any thoughts?

**Comment by HeJiachen-PM** [comment]
It is confirmed that this feature will be added to Affine in later releases.
