### ISSUE TITLE
Custom arrangement of blocks

### ISSUE THREAD

**Issue by EnterMan123** [toeverything/AFFiNE#7016]
### Description

inspired by notion, satisfy personalized design needs
![1](https://github.com/toeverything/AFFiNE/assets/107846196/b2fa2c4a-f597-466e-93b9-9ad5c533e276)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houshasen** [comment]
I think it's same as [this](https://github.com/toeverything/blocksuite/issues/7114), isn't it? So yes, I agree. :)

**Comment by EYHN** [comment]
Let's discuss it in https://github.com/toeverything/blocksuite/issues/7114
