### ISSUE TITLE
Mouse pointer can only create a new line in a specific area of the document

### ISSUE THREAD

**Issue by EnterMan123** [toeverything/AFFiNE#7022]
### What happened?

Please pay attention to the position of my mouse pointer and the state of the mouse pointer.
I don't have a way to create a new line by clicking on the blank space under the last paragraph of text.
I have to click in a specific area, or press the Enter key.
Is this a bug?

![7](https://github.com/toeverything/AFFiNE/assets/107846196/9b19a3d0-68a5-4248-8e2a-5a094e312293)

gif 👇
![12-10-32](https://github.com/toeverything/AFFiNE/assets/107846196/c80d336f-084f-41f4-9baf-d38bd7a1f080)

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
Looks like a bug
