### ISSUE TITLE
Support third-party AI providers

### ISSUE THREAD

**Issue by OiAnthony** [toeverything/AFFiNE#7023]
### Description

Support third-party AI providers

- Support customizing those that conform to the OpenAI API specification, such as custom endpoint and APIKey.
- Provide an adapter to facilitate the access of third-party AI that does not conform to the OpenAI API specification.

### Use case

Users can choose local or third-party AI providers

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MingStudentSE** [comment]
I think that is a good idea.

**Comment by EYHN** [comment]
Thank you for your suggestion on supporting third-party AI providers.

We are currently focused on optimizing the user experience and will not be adding this feature in the short term. However, we plan to support custom AI providers in the future.

**Comment by EYHN** [comment]
Since this won't be achieved in the short term, I will convert this issue into a discussion so that we can continue to discuss it.
