### ISSUE TITLE
​How to move my docs? 

### ISSUE THREAD

**Issue by rcqed** [toeverything/AFFiNE#7051]
### Description

I want to move my docs from a workspace to another, but I can't find this function. I want it be added~ 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
There are currently two ways, one is to export the doc and then import it into another workspace, the other is to select all and copy, then paste it into another newly created doc.
However, you may need to pay attention to whether your attachments and images are imported or pasted correctly.

**Comment by rcqed** [comment]
> There are currently two ways, one is to export the doc and then import it into another workspace, the other is to select all and copy, then paste it into another newly created doc. However, you may need to pay attention to whether your attachments and images are imported or pasted correctly.

it's not a completely usable way, frequent formatting errors, markdown and database especially.
