### ISSUE TITLE
[FR]Page import​ing progress bar

### ISSUE THREAD

**Issue by wsrer** [toeverything/AFFiNE#7064]
### Description

add a progress bar for page importing

### Use case

![image](https://github.com/toeverything/AFFiNE/assets/69560752/60f5078e-a7c4-4d8a-a091-24153d7cf0cd)
add a progress bar to this 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
duplicated #6846
