### ISSUE TITLE
​Application Error

### ISSUE THREAD

**Issue by webmapLee** [toeverything/AFFiNE#7069]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/20334500/efbb48c7-129b-482d-96ae-a9da2f0e9baa)

Loading chunk 4225 failed. (error: https://prod.affineassets.com/js/chunk.4225-3527b328.js)
ChunkLoadError

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by JimmFly** [comment]
Could you please share how to reproduce this issue? This will help us better locate the problem.

**Comment by EYHN** [comment]
This is usually a network issue and can be restored after refreshing
