### ISSUE TITLE
[Self-Hosted] Ask AI Feature Not Working on Self-Hosted Instance of ghcr.io/toeverything/affine-graphql:stable

### ISSUE THREAD

**Issue by bulgarian-beast** [toeverything/AFFiNE#7098]
### What happened?

Hello,

I am currently using a self-hosted instance of ghcr.io/toeverything/affine-graphql:stable and have encountered an issue with the "Ask AI" feature, which does not seem to be functioning.

Steps to Reproduce:

Set up a self-hosted instance using the Docker image ghcr.io/toeverything/affine-graphql:stable.
Attempt to use the "Ask AI" feature.
Expected Behavior:
The "Ask AI" feature should be operational and respond appropriately.

Actual Behavior:
The "Ask AI" feature does not work. There are no responses or interactions when attempting to use it.

Suggestion:
It would be greatly beneficial to have documentation on how to set up the "Ask AI" feature for self-hosted instances using Docker environment variables. This would help users like myself ensure all necessary configurations are correctly implemented.

Thank you for your assistance and for providing a great tool.

Best regards,

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [X] Yes

**Comment by xiaoxuan220** [comment]
Me too

**Comment by emengweb** [comment]
same here, need some env for custem OpenAI URL :D

**Comment by zoverdoser** [comment]
> same here, need some env for custem OpenAI URL :D

+1

**Comment by 1992leiting** [comment]
> same here, need some env for custem OpenAI URL :D

+1

**Comment by mfortini** [comment]
+1

**Comment by SAnBlog** [comment]
+1

> same here, need some env for custem OpenAI URL :D同样在这里，需要一些 env 用于 custem OpenAI URL :D

**Comment by cloudsbird** [comment]
+1

**Comment by Macfee** [comment]
+1

**Comment by pespin123** [comment]
+1

**Comment by thearyadev** [comment]
+1

**Comment by ProfessorDey** [comment]
My issue #7497 covers how to set up the AI on local host for your own custom AI, to use your own OpenAI API key just do step 3 without adding baseURL and it should #justwork, lol.

If there's confusion as to why you can't use their own AI that they have on the cloud version, that's because they're specifically paying for their API key and you need to purchase your own from OpenAI to access their services. AFFiNE's decision to call their AI Copilot like microsoft's leads to some unnessicary confusion.

**Comment by emengweb** [comment]
> My issue #7497 covers how to set up the AI on local host for your own custom AI, to use your own OpenAI API key just do step 3 without adding baseURL and it should #justwork, lol.
> 
> If there's confusion as to why you can't use their own AI that they have on the cloud version, that's because they're specifically paying for their API key and you need to purchase your own from OpenAI to access their services. AFFiNE's decision to call their AI Copilot like microsoft's leads to some unnessicary confusion.

It worked! Amazon!!!! Thanks for help! :D
###
Awesome! will try today! Thanks!

**Comment by forehalo** [comment]
will track it in #7705
