### ISSUE TITLE
Can't create users via GraphQL requests​

### ISSUE THREAD

**Issue by YourDaniel** [toeverything/AFFiNE#7105]
### What happened?

I had to make a new issue since Affine Selfhost thread in Q&A seems to be dead.

I migrated to a new version of Affine and couldn't create new users with GraphQL. Previously I used signUp before my other API calls. Now it seems there's no such method. I tried using invite but it responded that I am not authorized. How do you authorize in a new version of GraphQL API?

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
see the answer in #7106
