### ISSUE TITLE
[urgent] GraphQL command for signUp is removed in current version stable

### ISSUE THREAD

**Issue by justagape** [toeverything/AFFiNE#7106]
### What happened?

There is no way to add user, or by invitation​, in current version stable after the recent update. What is the fastest way to add user, giving new email and password for new user? What is the fastest way? The graphQL command for signUp is removed.

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
it's removed for security consideration, and the latest stable version is coming with a brand new user management apis, please check the graphql schema for `createUser`(it requires administrator permission to do so)
