### ISSUE TITLE
Self hosted affine workspace created in web not showing ​in mac desktop app

### ISSUE THREAD

**Issue by superkashyap** [toeverything/AFFiNE#7126]
### What happened?

Self hosted affine workspace created in web not showing ​in mac desktop app

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [X] Yes

**Comment by EYHN** [comment]
Can you provide a screenshot ？

**Comment by forehalo** [comment]
we haven't implement the feature that allows user connecting to self hosted server from desktop client.
