### ISSUE TITLE
Selfhosted docker stable version still 14.0 nightly​

### ISSUE THREAD

**Issue by Zaschii** [toeverything/AFFiNE#7156]
### What happened?

Hi everybody. 

my selfhosted affine installation is working pretty well, thx for that awesome software.

But after fresh docker pull / update the version is still 0.14.0-nightly-202406040853-01fc1ea
How can i update to 0.14.9 on docker? 
Iam using image: ghcr.io/toeverything/affine-graphql:stable

Thx & BR,

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

**Comment by Zaschii** [comment]
any news / suggestions?

**Comment by oiqm4T** [comment]
per their documentation: -- change "stable" to beta or canary to update from 0.14 - 

In your compose.yaml , you can choose your target deploy version with image: ghcr.io/toeverything/affine-graphql:stable , it is suggested to deploy the stable version, but beta and canary are also available.

- Beta gets 0.15.0-beta.13 and Editor version 0.15.0-canary-202405300523-dfd9f0e
- Oddly Canary gets 0.14.0-nightly-202406190901-be36e03 and Editor 0.15.0-canary-202406190721-38a1716
with experimental feature

**Comment by eikaramba** [comment]
same problem here, it seems the stable builds are not pushed to the docker repo

**Comment by AndyPro720** [comment]
Hmm any workaround? The selfhosted version seems largely neglected.

**Comment by eikaramba** [comment]
it is, they are currently pushing every new release to the docker hub. i am quite happy with the release schedule for self hosted version. you will have the latest version as of today.

**Comment by AndyPro720** [comment]
Can you share link for docker hub area, couldn't find it

**Comment by eikaramba** [comment]
i'm just using what is stated in the docs:
image: ghcr.io/toeverything/affine-graphql:stable

**Comment by forehalo** [comment]
you should pull the image manually, docker compose won't do it for you
