### ISSUE TITLE
​[bug]- OIDC login url is wrong at selfhost

### ISSUE THREAD

**Issue by IamTaoChen** [toeverything/AFFiNE#7182]
### What happened?

When enable OIDC login at selfhost,  clik the the `OIDC Login` the URL is `https://app.affine.pro/oauth/login?provider=OIDC&redirect_uri=%2Fworkspace%2FScoLHKO1tGBTyncjVlMTL%2Fall`

<img width="1126" alt="image" src="https://github.com/toeverything/AFFiNE/assets/42793494/4eaf1db7-c24a-4075-85ed-a1681db506c4">

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by JourneyBean** [comment]
#6886 Same issue here.

**Comment by forehalo** [comment]
closed as https://github.com/toeverything/AFFiNE/issues/6886#issuecomment-2277341938
