### ISSUE TITLE
​ Why there can be only 3 users per Workspace in Affine self-hosted version?

### ISSUE THREAD

**Issue by YourDaniel** [toeverything/AFFiNE#7227]
### What happened?

I can't add more than 3 users to a Workspace. It seems to be limited by Free Cloud version limit. However, self-hosted version is advertised is to have unlimited features, otherwise why even have self-hosted version?

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Anything else?

![Снимок экрана 2024-06-14 в 18 20 35](https://github.com/toeverything/AFFiNE/assets/22484620/3a9e0fb7-2595-4fd6-a35c-f0afe0619193)

**Comment by marvint24** [comment]
Seams to be a known issue: https://github.com/toeverything/AFFiNE/issues/6641

**Comment by forehalo** [comment]
duplicated
