### ISSUE TITLE
markopolo top

### ISSUE THREAD

**Issue by vprivateperson** [toeverything/AFFiNE#7228]
.

**Comment by vprivateperson** [comment]
https://github.com/WasperAI/Wasper/compare/ac9bad9a92a473efb44764a81fd458af75e21469...main
![image](https://github.com/toeverything/AFFiNE/assets/170932348/c8e84955-e5e9-45fe-a80d-3e2995eb5b09)

**Comment by meik99** [comment]
You know Git histories exist for every project? Your was created only a month ago and has the Affine links in the second commit: https://github.com/WasperAI/Wasper/commit/a5ae37393af749ccce2010cef30c22cf6f35de75

**Comment by forehalo** [comment]
spam
