### ISSUE TITLE
​Can't login locally

### ISSUE THREAD

**Issue by edward-hong** [toeverything/AFFiNE#7275]
### What happened?

Hi so I can't login on my local app with email. It works on the website but not locally. When I use my password it says wrong password. When I try with magic link I don't get an email. Another thing is I can't find the option to export from the web. 

I'm on Ubuntu 22.04.4

And I'm using 0.14.9 version of Affine

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Other

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment]
You can send an email to support@toeverything.info and include your account email address, and we will help you solve the unable to sign in issue.
