### ISSUE TITLE
[bug]: New block can not be created in an empty group in safari

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#73]
### Describe the bug

New block can not be created/added in an empty group, at least not in the Text view.

### To Reproduce

1. Delete every blocks in a group. For the last one, use backspace/delete key.
2. An empty group is left.
3. There's no way of creating/adding new block in this empty group, unless changing the view from Text to Kanban and click one of the "plus" button, which is very clumsy.

### Screenshots

<img width="703" alt="image" src="https://user-images.githubusercontent.com/132558/182749257-657002c7-f2be-471c-8431-a2533a64594f.png">

### Expected behavior

Perhaps there should be a button in the menu of group handle since there's no room in an empty group for extra UI element.

### Browser

Safari 15.6

No problem in latest Chrome. It seems a browser compatibility issue.

**Comment by DiamondThree** [comment]
We are currently not considering safair compatibility
