### ISSUE TITLE
​dismissAiOnboarding modal always shown

### ISSUE THREAD

**Issue by eikaramba** [toeverything/AFFiNE#7306]
### What happened?

The modal for the AI onboarding is always shown no matter what buttons you click. esp. if you close. upon inspection i see that the wrong localStorage variable dismissAiOnboardingEdgless is saved, but it tries to read the value from dismissAiOnboarding. after i added the correct key/value to my localStorage the issue was gone and the modal was not displayed anymore

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [X] Yes

**Comment by EYHN** [comment]
This not a bug. You need to click `Next` until the fifth page of ai onboarding to trigger `dismissAiOnboarding`.
