### ISSUE TITLE
client sync to self-host server

### ISSUE THREAD

**Issue by LYUYork** [toeverything/AFFiNE#7382]
### Description

how to config the self-host sync sever in android or macos app client?
like [AppFlowy](https://github.com/AppFlowy-IO/AppFlowy)
![Screenshot_2024-06-29-17-10-22-516_io appflowy appflowy-edit](https://github.com/toeverything/AFFiNE/assets/45093086/738715f9-2b75-4dfa-9a66-20221b13c5d2)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
We are working on this

**Comment by forehalo** [comment]
duplicated #2646
