### ISSUE TITLE
Can't use slash or AI because of some unknown DOMException​ and graphql issue

### ISSUE THREAD

**Issue by ispjstfu** [toeverything/AFFiNE#7388]
### What happened?

Running self-hosted using Docker. Latest version. I have no idea what's wrong but typing slash does nothing, hitting space just says some error occured. Also something is sometimes up with Websocket but I haven't used the app enough to know what that means for an end user.

<img width="2120" alt="SCR-20240630-ssfz" src="https://github.com/toeverything/AFFiNE/assets/22611327/7d70aed8-6ead-49eb-b7e3-04d758f23cc5">
<img width="2124" alt="image" src="https://github.com/toeverything/AFFiNE/assets/22611327/ab3675a5-8edc-4ec8-aa43-7a83017f3263">

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Safari

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
ai is not available out of box on selfhost instance, we will make it optional or configurable later
