### ISSUE TITLE
Rotation Mechanism for Shapes/ Grouped Items

### ISSUE THREAD

**Issue by ACay047** [toeverything/AFFiNE#7394]
### Description

I'm very new to this software and it has everything I need, but get a bit frustrated that I can't rotate my objects or groups. I draw Cell Tower sketches multiple times a day and the more I can make it look accurate the easier my day goes. I understand this is more of a note taking and research type of software but know this small addition will go a long way. I'm not sure of the mechanisms you have in place for the conversion of page and edgeless mode but hope the rotation feature would not be too complicated. 

### Use case

More Accurate Drawings and Customizable Visuals

### Anything else?

45, 90, 180 degree flips even

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
Rotation is supported by dragging the corner of shapes, but we might need to make the indicator more obvious @hwangdev97
