### ISSUE TITLE
[improvement]: request for installation guide

### ISSUE THREAD

**Issue by zheng1** [toeverything/AFFiNE#74]
### 1~3 main use cases of the proposed improvement

As a user, I don't know how to install and run this software

### Ideas for solution

If it has very few dependencies, it is recommended to run it via docker or docker-compose

### what types of users can benefit from using your proposed improvement

all users

**Comment by alt1o** [comment]
We expect to go live with an online version next week, thanks for your attention. Currently it can only be previewed for use in this way: https://affine.gitbook.io/affine/basic-documentation/contribute-to-affine/quick-start

**Comment by reneManqueros** [comment]
I was trying to build a dockerfile for this as well but i am reaching dependency hell :(

**Comment by tzhangchi** [comment]
> I was trying to build a dockerfile for this as well but i am reaching dependency hell :(

Sorry to hear that. But it won't take long before we release a web demo

**Comment by darkskygit** [comment]
> I was trying to build a dockerfile for this as well but i am reaching dependency hell :(

currently the Dockerfile is placed here:
https://github.com/toeverything/AFFiNE/tree/master/.github/deployment

**Comment by tzhangchi** [comment]
> 


This link may meet your needs
[Ihttps://github.com/toeverything/AFFiNE/pkgs/container/affine](https://github.com/toeverything/AFFiNE/pkgs/container/affine)

**Comment by tzhangchi** [comment]
You can quickly experience AFFiNE through docker 
```bash
docker pull ghcr.io/toeverything/affine:nightly-latest 
docker run -d -p 4200:3000 --name affine -d   ghcr.io/toeverything/affine:nightly-latest  
open http://localhost:4200
```

**Comment by MohamedElashri** [comment]
> 

Thanks for the quick docker example. Just note that you are repeating detach flag `-d`

It should be 
```
docker pull ghcr.io/toeverything/affine:nightly-latest 
docker run -d -p 4200:3000 --name affine  ghcr.io/toeverything/affine:nightly-latest  
```

Also, It would be great if you can add minimal working `docker-compose.yml`. Here is a suggestion. 

```
version: '3.3'
services:
    affine:
        container_name: affine
        ports:
            - '4200:3000'
        image: 'ghcr.io/toeverything/affine:nightly-latest'
```

Another thing, you need to mount the volume using `-v` so that you don't lose the data. I'm not sure however how you store them inside the app (container).

**Comment by darkskygit** [comment]
> > 
> 
> Thanks for the quick docker example. Just note that you are repeating detach flag `-d`
> 
> It should be
> 
> ```
> docker pull ghcr.io/toeverything/affine:nightly-latest 
> docker run -d -p 4200:3000 --name affine  ghcr.io/toeverything/affine:nightly-latest  
> ```
> 
> Also, It would be great if you can add minimal working `docker-compose.yml`. Here is a suggestion.
> 
> ```
> version: '3.3'
> services:
>     affine:
>         container_name: affine
>         ports:
>             - '4200:3000'
>         image: 'ghcr.io/toeverything/affine:nightly-latest'
> ```
> 
> Another thing, you need to mount the volume using `-v` so that you don't lose the data. I'm not sure however how you store them inside the app (container).

the affine container just a frontend container, affine does not need backend now and it will storage the data in browser
in the near future, a new version with local data storage will be launch, that allow you to store the data in hard disk and sync to anywhere
