### ISSUE TITLE
copying a database with pages as titles leads to broken outgoing links

### ISSUE THREAD

**Issue by mximum** [toeverything/AFFiNE#7402]
### What happened?

If I create a database on a page and fill it with page links as titles, these are correctly added to the outgoing links.

If I then copy the database to another page, for example because I want to copy the structure, the links are also copied and added accordingly. If I then remove them from the database, the links unfortunately remain unchanged in the outgoing links and can no longer be deleted. Only deleting the page fixes the issue.

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge, Other

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
fixed in 0.16.0
