### ISSUE TITLE
update SHARE button layout when a document IS shared.

### ISSUE THREAD

**Issue by gordielachance** [toeverything/AFFiNE#7427]
### Description

It would be nice to visually know when a page is (or is not) shared by updating the button layout; eg. by another button with another color + icon.

![Capture](https://github.com/toeverything/AFFiNE/assets/4077261/20da2e4e-faf3-4682-bb8e-4f46f391eb66)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
@hwangdev97 take a look at it

**Comment by hwangdev97** [comment]
This should be a bug. The previous version would display "shared".

**Comment by forehalo** [comment]
fixed
