### ISSUE TITLE
​URL in table turns into Doc-Link

### ISSUE THREAD

**Issue by dingemann** [toeverything/AFFiNE#7437]
### What happened?

After a recent update some of my webpage-links turn into Doc-Links in a table.

https://github.com/toeverything/AFFiNE/assets/714974/9f3d8dff-5bc3-49a3-b2da-3efcb99b098c

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you self-hosting?

- [ ] Yes

**Comment by ProfessorDey** [comment]
I'm getting this as well running canary on self-hosting, was trying to work around the inability to link/associate pages with a table entry (The one key feature I feel is missing compared to Notion), but while it resolves the link's document name, it then means clicking it does nothing. Hoping this bug means that there'll be a solution to that missing feature soon, but for now it's confusing.

**Comment by tianstcht** [comment]
conversely I want to know how to insert a doc-link in a table, lol.

**Comment by forehalo** [comment]
fixed in 0.16.0
