### ISSUE TITLE
ai问答时滚动条会卡住无法滚动，并且单独使用chat-text组件时，外部滚动条会被一直重置到顶部

### ISSUE THREAD

**Issue by mazhenjie233** [toeverything/AFFiNE#7442]
ai问答时滚动条会卡住无法滚动，并且单独使用chat-text组件时，滚动条会被一直重置到顶部（或者组件在一直重置），一个月之前的版本没有这个问题
![image](https://github.com/toeverything/blocksuite/assets/76252062/eb7bfb3a-d154-4646-98b3-1e701be639fe)

**Comment by forehalo** [comment]
fixed in 0.16.0
