### ISSUE TITLE
添加自定义AI引擎的功能

### ISSUE THREAD

**Issue by CreatorZZY** [toeverything/AFFiNE#7461]
### Description

比如我能自己选择OpenAI、Gemini、Ollama来为我的笔记提供服务。

### Use case

适用于隐私、不适合上传的信息处理

### Anything else?

None～

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SAnBlog** [comment]
+1

**Comment by lixianwa** [comment]
+1

**Comment by Seblb44** [comment]
+1 - the possibility of using self hosted LLM model running locally on Ollama

**Comment by forehalo** [comment]
track in #7705

**Comment by William-715** [comment]
> +1

**Comment by pipuwong** [comment]
+1
