### ISSUE TITLE
​Change order in sidebar

### ISSUE THREAD

**Issue by yakolokol** [toeverything/AFFiNE#7499]
### Description

I have some files and subfiles in sidebar. BUT they are all sorted in creation order. WTF? :)
We need to have option to REORDER them just by dragging to other place: top or down, or another file even.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by JimmFly** [comment]
We will support this feature in the near future, so stay tuned.

**Comment by forehalo** [comment]
it's available now in 0.16.0

**Comment by yakolokol** [comment]
Well, looks like it's not working

**Comment by JimmFly** [comment]
Currently this feature works fine on both the web version and the client. Could you please provide a screen recording and specific information? This will help us better locate the problem.
 (operating system, client or web version, AFFiNE version, console error, etc.)

**Comment by yakolokol** [comment]
Win 10, client, 0.16.0
Short screencast:
https://github.com/user-attachments/assets/c3abfc2c-32c0-4ab9-92ee-ebd930688823

**Comment by JimmFly** [comment]
Thank you so much for providing the detailed information. Due to current technical limitations, it is indeed not possible to sort the linked docs. We are actively exploring solutions to this issue. I have created a new issue to address this problem, and any updates will be posted there.
#7822
