### ISSUE TITLE
[bug]: Undo/redo operations not functioning correctly

### ISSUE THREAD

**Issue by m1911star** [toeverything/AFFiNE#75]
### To Reproduce

1. pnpm start
2. delete any block
3. Cmd + z / Ctrl + z not working

**Comment by alt1o** [comment]
undo/redo does have some problems, is working on it, will synchronize with you when there is new progress

**Comment by ShortCipher5** [comment]
Undo & redo functionality  as well as operation history features have been significantly improved in the latest release.
