### ISSUE TITLE
Drag and drop to open an item from sidebar

### ISSUE THREAD

**Issue by xuzuodong** [toeverything/AFFiNE#7505]
### Description

It would be nice if we can open an item from App sidebar by dragging and dropping it into the main container. 

---

Currently, when a favorited item displayed at App sidebar being dragged and dropped into the main container, it will be removed from the favorite list. Any other entries at App sidebar (i.e. "All docs", "Journals", items in "Collections" and "Trash") don't have drag-and-drop behaviors yet. 

IMO, a more intuitive behavior is when these entries are dragged and dropped into the main container, they should be opened. 

In addition, now [SplitView feature](https://github.com/toeverything/AFFiNE/pull/5837) have been implemented, the dropped item can further be opened in either single or split view, depends on what specific place user's mouse is pointing at when the item is dropped.

Similar behavior can be found in VSCode: 

https://github.com/user-attachments/assets/34649e6a-e8ff-47ee-8ded-dedaad9c0119

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
@hwangdev97

**Comment by hwangdev97** [comment]
We need some time to design the interaction experience for this part.
 The drag behavior of the sidebar in a whiteboard-like document tool can have multiple semantics:

- Drag to open a new tab
- Drag to open split view
- Drag to insert the document into the content

Additionally, in terms of infra, we also need some time to prepare.
