### ISSUE TITLE
SHIFT + Tab does not work​

### ISSUE THREAD

**Issue by grand-lotus-iroh** [toeverything/AFFiNE#7510]
### What happened?

if I type a bullet or a to do and try to select PREVIOUS bullet, opposite of what you would think TAB does, it does not work.

please make it so when i press `SHIFT` + `TAB` it moves up one line and selects text or does not select text but at least moves up a line...

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by forehalo** [comment]
it works as expected in 0.16.0 now
