### ISSUE TITLE
disable AI / CoPilot … when?​

### ISSUE THREAD

**Issue by grand-lotus-iroh** [toeverything/AFFiNE#7511]
### Description

One year later... would be great to have a checkbox in the options and remove all traces of the plugin / module.

* https://community.affine.pro/c/questions-answers/q-will-i-be-able-to-disable-affine-copilot

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by tika** [comment]
I really hate AI products so this would be great, thanks.

**Comment by ghost** [comment]
agree, my client actually lags trying to load all the ai button garbage each open, and all the ai buttons i cant/wont use are first in every toolbar. **its necessary affine does not become nagware**... ...hopefully someone will fork for a nicer build, or devs get a grip, because its really _awesome_ being blasted with features i literally can not use

**Comment by hwangdev97** [comment]
The way of opt-out AI feature is still on going, along with a batch of feature flags that can let you control or customize the editor more. According to our roadmap, it will come with 0.17.

We are so sure that AI is a thing good to have but not must, and bringing you a good experience on note-taking and knowledge management is and will always be the most important thing.

**Comment by bn-9527** [comment]
really need this

**Comment by kryoqa** [comment]
> ## Issue Status: 🙋 Upvoting
> 
> ![](https://camo.githubusercontent.com/a949e205fae1a6a3eb01d495b1c23d328b530b8cbf6a20de8c0e852aa87122dd/68747470733a2f2f69737375652d626f742e746f65766572797468696e672e776f726b6572732e6465762f7374617469632f73746570732f322e737667)
> 
> **🙋 Upvoting**
> 
> We are currently evaluating demand for the issue and checking whether it requires complicated or risky changes. Please leave a vote or comment if you think it should be prioritized.
> 
> This is an automatic reply by the bot.

Please provide option to disable AI

**Comment by mocart2** [comment]
> Please provide option to disable AI

+1

**Comment by hwangdev97** [comment]
AFFiNE 0.17 already supports this feature. 👇

![shot-2024-10-10-15 42 23](https://github.com/user-attachments/assets/cc3ce1a4-95e6-44b9-8e45-bb8b716e5c54)

**Comment by Bottleface** [comment]
@hwangdev97, it appears that in version 0.18 this was removed.  Any idea if this was done on purpose?  The `dismissAiOnboarding*` localStorage entries are still respected, they just need to be added manually.

**Comment by Dorifor** [comment]
I also don't want AI to appear everywhere

**Comment by Bottleface** [comment]
@hwangdev97, can you comment on the removal of this setting?  It has been removed, even in the most recent release (19.5).
![image](https://github.com/user-attachments/assets/4937af9c-5e98-4a25-ac62-2b2799b9fc37)

![image](https://github.com/user-attachments/assets/9824fcc9-21b5-4f2c-87bd-18d0d75ac1ac)

**Comment by phantom943** [comment]
JFYI you can disable AI by executing the following command in your browser console:
```js
localStorage['global-state:affine-flag:enable_ai'] = false
```

**Comment by Bottleface** [comment]
> JFYI you can disable AI by executing the following command in your browser console:
> ```js
> localStorage['global-state:affine-flag:enable_ai'] = false
> ```

Yup, I'm aware that you can just manually add the local storage entry, I was partially hoping for some kind of confirmation that they weren't going to take away the ability to disable the AI.

Thanks though =]

**Comment by Nonolanlan1007** [comment]
> JFYI you can disable AI by executing the following command in your browser console:
> 
> localStorage['global-state:affine-flag:enable_ai'] = false

This fix does not work on 0.25.1
