### ISSUE TITLE
[Bug] Endless mode can't be interacted with when the '发现新动态' tag is closed

### ISSUE THREAD

**Issue by curlykay** [toeverything/AFFiNE#7516]
### What happened?

After updating Affine, the '发现新动态' tag will appear at the bottom left corner, at this time, open any one note, and switch the note to endless mode.
After that, close the '发现新动态' tag, then the notes in this endless mode will not be able to interact with each other.

https://github.com/user-attachments/assets/fd3d4002-ac72-4e08-9a0a-57e391eef61f

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

**Comment by forehalo** [comment]
the closing of what's new badge should not cause a page refresh. will fix it soon.

**Comment by forehalo** [comment]
fixed in 0.16.0
