### ISSUE TITLE
Pen mode unusable in 0.15.6

### ISSUE THREAD

**Issue by tgarul** [toeverything/AFFiNE#7555]
### What happened?

I updated to 0.15.6 on my windows pc using a Wacom tablet. The pen input kept getting stuck and when it came back, it made a bunch of squiggles on the screen. I have now reverted to 0.15.5

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by YaMoef** [comment]
I've noticed the same issue on (self-hosted) web (Chromium Version 126.0.6478.182 (Official Build) snap (64-bit) on Ubuntu 22.04). Drawing with mouse or touchpad works fine, but when using a drawing pen on my touchscreen I have a weird behavior: when I start drawing I get a small line (even when I keep drawing). When I lift my pen and touch again, I will get a straight line from the start (the small line) to the point where I touch again.

I do self-host my instance and this occurred on the update from:
ghcr.io/toeverything/affine-graphql:stable-01fc1ea to ghcr.io/toeverything/affine-graphql:stable-ccac7a8
I will roll back to have the correct behavior again

**Comment by L-Sun** [comment]
Thank you for reporting this issue! We have fixed it in our internal version and the fix will be included in the next release.

**Comment by L-Sun** [comment]
The fix has been released with stable v0.16.0
