### ISSUE TITLE
[bug]: when click the add button，the page error

### ISSUE THREAD

**Issue by snowyang2021** [toeverything/AFFiNE#76]
### Describe the bug

[bug]: when click the add button，the page run error

### Screenshots

![image](https://user-images.githubusercontent.com/1658018/182751378-aac75f77-35a7-43d5-80a2-14f4b0f3421b.png)

**Comment by mitsuhatu** [comment]
Sorry, I didn't reproduce this problem locally, and temporarily restore the original logic: activities shows the recently viewed articles.

**Comment by mitsuhatu** [comment]
the bug has been fixed，see: [PR94](https://github.com/toeverything/AFFiNE/pull/94)
