### ISSUE TITLE
​Cant Delete Tags

### ISSUE THREAD

**Issue by realsafen** [toeverything/AFFiNE#7685]
### What happened?

When I delete a tag it says it was deleted but it's still there. Even if I refresh I still see it there and won't delete for some reason.

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

**Comment by Anonymous961** [comment]
@JimmFly is this issue fixed? I'm able to delete tags.
![image](https://github.com/user-attachments/assets/a4c3fd52-da4d-40c5-984b-97f5517d5290)
after deleting a tag
![image](https://github.com/user-attachments/assets/4a7aca4d-ac9c-4109-888d-375a0917d006)

**Comment by adnan-usman** [comment]
Serously ? Dude look at Top side Go to Tags section, and there create or delete exicting tag.

pic 1 

![1](https://github.com/user-attachments/assets/ab5aee6a-a806-4f23-936e-33e268a668e8)

----------------------------------------------------------------------------------------
pic 2 
  
![2](https://github.com/user-attachments/assets/823cbe64-71f6-402a-91e8-b4534176369e)

**Comment by forehalo** [comment]
0.16.0 just got released. check whether the deleting behavior is working as expected, or reopen the issue
