### ISSUE TITLE
Winget version​

### ISSUE THREAD

**Issue by pomazanbohdan** [toeverything/AFFiNE#7709]
### What happened?

Pls upgrade PackageVersion
https://github.com/microsoft/winget-pkgs/blob/master/manifests/t/ToEverything/AFFiNE/0.15.0/ToEverything.AFFiNE.installer.yaml

Winget does not see that this is version 0.15.7

![image](https://github.com/user-attachments/assets/0e4eb8f8-8882-412f-a64d-816df240957b)
![image](https://github.com/user-attachments/assets/e75968bf-e78f-4443-81be-de9917a35fca)

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by forehalo** [comment]
the version signed on windows packages was wrong and it has been fixed in #7602 
everything will be cool after 0.16 get released
