### ISSUE TITLE
Pre-triage feedback for Alpha "Downhills"

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#773]
This issue is used for tracking quick feedback from Toeverything team and our early adopters during the integration phase of latest major version of AFFiNE and BlockSuite (202302). Members with permissions can directly edit and update existing issue content, and we hold regular communication to classify feedback here, converting issues when necessary.

**Comment by joebeijing** [comment]
The Block Hub portal should not appear on the non-document editing page

Steps to Reproduce
1. go to the document editing page
2. Go back to the non-document editing page

Then, the Block Hub portal will always appear in the bottom right corner

The expected result is that the Block Hub portal will only appear on the editable document page

![image](https://user-images.githubusercontent.com/22443345/216544096-c1cd2b7c-c3df-4463-bf48-2c17408e3ed3.png)

**Comment by joebeijing** [comment]
The activation method to open Help Center needs to be changed from hover to click
Need to be consistent with Block Hub, including editing and non-editing pages
![2023-02-03 4 03 17 pm](https://user-images.githubusercontent.com/22443345/216545339-219c9f7a-7964-41b6-93c3-41c26a347fc3.gif)

**Comment by joebeijing** [comment]
The font size of the home page does not meet the requirements
For example, the font of the list is too big.
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/22443345/216552589-84a1e66e-6888-4e4a-a238-5d17d7161fe4.png">

**Comment by joebeijing** [comment]
The default pre-created Workspace name should be AFFiNE Test.

**Comment by joebeijing** [comment]
Clicking the Drag Handle will select a single Block, this selected state should not disappear after scrolling the page
![2023-02-03 4 44 08 pm](https://user-images.githubusercontent.com/22443345/216553479-94aae6ad-4df4-42c6-b797-5dbc75aef01b.gif)

**Comment by joebeijing** [comment]
After expanding the Help Center, the Block Hub portal should not still be there
![2023-02-03 4 48 30 pm](https://user-images.githubusercontent.com/22443345/216554315-363016f9-ab71-4954-b40a-8d0a3990a205.gif)

**Comment by joebeijing** [comment]
The entry for switching languages does not match the design file
<img width="345" alt="image" src="https://user-images.githubusercontent.com/22443345/216554874-7184da84-734d-4c7a-97a9-998edfdbc965.png">

**Comment by darkskygit** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/25152247/216554869-d6643a70-5fae-4d53-8023-7141a2c8f4cd.png">
drag handle will display on non-eidtable pages

**Comment by darkskygit** [comment]
<img width="944" alt="image" src="https://user-images.githubusercontent.com/25152247/216555166-a43a784f-ace9-47f6-ad74-98b1b41e12bb.png">
some workspace doesn't has name

**Comment by zuoxiaodong0815** [comment]
![1675414704815](https://user-images.githubusercontent.com/53252747/216556929-ef4506a0-5cd5-4f4d-82c0-ec18367eff7f.jpg)
when click enter keyboard between title, the end content is missed.

**Comment by tzhangchi** [comment]
![Uploading image.png…]()
When I want to delete the workspace which name is empty， I  cant't delete

**Comment by zuoxiaodong0815** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/53252747/216557998-20db371e-9770-49d6-9bae-393a773f7860.png">
When workspace name has only one word, I can not delete it to write new name.

**Comment by tzhangchi** [comment]
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/5910926/216559411-13198ab0-e866-4772-9ef6-8da84fc30514.png">
When I open the page of public workspace， it show the words “it is still designed” @DiamondThree

**Comment by zuoxiaodong0815** [comment]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/53252747/216559825-b586ed24-0747-4857-98f4-0a5066aad40a.png">

I don't understand how to select and move these objects. Does this feature have not been developed?

**Comment by tzhangchi** [comment]
When I successfully open the public workspace, then I click one of the pages, I find that the blockhub is still visible in editor @thorseraq 
https://www.loom.com/share/163d7d8571c54873a1a03ef493796bac
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/5910926/216560069-ec4ca66e-b568-40c7-8b82-629def0bacdc.png">

**Comment by tzhangchi** [comment]
Edgeless mode could not be used in  public workspace page 
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/5910926/216561664-a686b9ac-bcb9-4a83-b5af-13da82a704b9.png">

**Comment by tzhangchi** [comment]
Default ui of search could be  better
<img width="1638" alt="image" src="https://user-images.githubusercontent.com/5910926/216562481-a0162f80-9c32-4f65-8bbd-1d5c8effc92b.png">

**Comment by tzhangchi** [comment]
BlockHub items  could not been hide when I click the icon 
https://www.loom.com/share/2f49544b428a46b1a6ce12f4710e6e96

**Comment by tzhangchi** [comment]
There are two different background and color in workspace and public workspace hub @DiamondThree 
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/5910926/216565641-f2ff73fe-3d78-4559-87a3-d2211e3ea4f4.png">
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/5910926/216565820-0088438c-6272-48c3-b235-7cd7ebb3a28f.png">

**Comment by tzhangchi** [comment]
The function for opening tab in all pages didn't work now 
https://www.loom.com/share/3db109f60c1c473bbe6c4b738318b3d9

**Comment by zuoxiaodong0815** [comment]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/53252747/216571862-c9193453-8057-4418-954a-fadb63785f08.png">
It should pop up a menu when I input '/' code at the beginning of block.

**Comment by tzhangchi** [comment]
Please record the workspace which last time opening, now it is always affine

https://www.loom.com/share/c6e7c61b9bf74653be3b6e8b915fb2af

**Comment by zuoxiaodong0815** [comment]
Enter the workspace, it is  always the first page. Opening the list page of all pages will be better.

**Comment by tzhangchi** [comment]
> 
> 
> <img width="1666" alt="image" src="https://user-images.githubusercontent.com/5910926/216557925-a36a8be4-d459-4251-8243-a5370527b4b9.png">
> 
> 
> 
> When I want to delete the workspace which name is empty， I  cant't delete

this feedback is invaild，sorry

**Comment by tzhangchi** [comment]
Devtool which including import/export workspace is needed，it would help me quickly restore the workspace state in any environments

**Comment by doodlewind** [comment]
Feedback converted to [GitHub project](https://github.com/orgs/toeverything/projects/8), please DO NOT add new feedback here. Thank you all for your participation!
