### ISSUE TITLE
Request for New Feature: Shortcut for Quick Navigation to All Docs / Collections / Tags

### ISSUE THREAD

**Issue by bttrung** [toeverything/AFFiNE#7797]
### Description

This feature request proposes the addition of a shortcut for quick navigation to the "All Docs," "Collections," and "Tags" sections within the platform. The aim is to streamline the user experience by providing immediate access to these essential areas, reducing the time and effort needed to locate and click through multiple menus. These shorcuts will enhance productivity, particularly for users who frequently manage and organize extensive content

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
@hwangdev97

**Comment by hwangdev97** [comment]
<img width="600" alt="image" src="https://github.com/user-attachments/assets/4da12e60-474b-43d0-8cc9-9d28da8fd331">
 
This is the sidebar for our upcoming new version(0.16), where you can directly access:

- Favourites: Your personal favorites
- Organize: Manually organized structures
- Collections: Structures organized through filters
- Tags: Structures that satisfy many-to-many relationships

Do you think this is sufficient?

**Comment by thecuvii** [comment]
Looking forward to it!

**Comment by bttrung** [comment]
Perfect! I think that's good enough, thank you!
