### ISSUE TITLE
​Implement Password Protection for Workspaces

### ISSUE THREAD

**Issue by cyberrab5050** [toeverything/AFFiNE#7829]
### Description

Request to add a feature that allows users to password-protect their workspaces, whether local or cloud based. 

### Use case

The user can create a workspace and optionally set a password. If a password is set, the system prompts for it when attempting to access the workspace. If the password is entered correctly, the user gains access to personal notes. If no password is set, access to the workspace is granted without a password prompt.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hwangdev97** [comment]
At this moment, we don't have a detailed plan to support this feature, but we're always looking for ways to improve!
