### ISSUE TITLE
​Docker deployment : Failed to send email. Please try again.

### ISSUE THREAD

**Issue by toohandsome** [toeverything/AFFiNE#7860]
### What happened?

![image](https://github.com/user-attachments/assets/539d0848-2aa7-42ba-a36f-0e5c5f0592cc)
![image](https://github.com/user-attachments/assets/a9b0cb1d-84ea-40dd-8661-2685cd5c99c8)

docker 部署提示未部署邮件服务
参考链接：https://docs.affine.pro/docs/self-host-affine

---------------------------------

Docker deployment prompt: Failed to send email. Please try again.
Reference link: https://docs.affine.pro/docs/self-host-affine

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
duplicated https://github.com/toeverything/AFFiNE/issues/7833
