### ISSUE TITLE
Capability to filer using multiple tags with OR, AND, and NOT options

### ISSUE THREAD

**Issue by bttrung** [toeverything/AFFiNE#7893]
### Description

In Apple Notes, I can click on a tag, say Tag 1, to filter for all documents associated with that tag. When I click on a 2nd Tag, it filters for documents that have both Tag 1 and Tag 2. If I click on the 2nd Tag again, it filters for documents that have Tag 1 but NOT Tag 2.

Could we implement a similar feature in this app?

Many thanks!

### Anything else?

See Apple Notes

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
you can use rule collections to achieve that

<img width="314" alt="image" src="https://github.com/user-attachments/assets/c584c805-d2a0-47d7-a147-be281a2a1095">
