### ISSUE TITLE
​Download status while update

### ISSUE THREAD

**Issue by SpaceFrrog** [toeverything/AFFiNE#7910]
### Description

First of all, thank you very much for this great program. My idea would be to display the download status during an update, maybe as a progress bar in the area, where the download button is.

### Use case

It would be helpful to see when the download is ready. Especialy if you have a poor internet connection, as the download can take a long time.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
there is a download progress indicator at bottom left corner
