### ISSUE TITLE
BUG: Export PDF file cannot copy content which in pdf file

### ISSUE THREAD

**Issue by floatval** [toeverything/AFFiNE#7912]
### What happened?

1. Write something in one page
2. click export to pdf
3. save pdf
4. then open exported pdf file
5. try to copy something from that exported pdf file
6. cannot copy anything from pdf file and it seems like a photo not a pdf file

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

### Anything else?

>    await BrowserWindow.getFocusedWindow()
      ?.webContents.printToPDF({
        pageSize: 'A4',
        margins: {
          bottom: 0.5,
        },
        printBackground: true,
        landscape: false,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: getFootTemple(),
      })
      .then(data => {
        fs.writeFile(filePath, data, error => {
          if (error) throw error;
          logger.log(`Wrote PDF successfully to ${filePath}`);
        });
      });
    return { filePath };
  } catch (err) {
    logger.error('savePDFFileAs', err);
    return {
      error: 'UNKNOWN_ERROR',
    };
  }
}

i see current the export function implemented by above code.
that sees like use the electron.js export to pdf
but when i open the pdf file,then look it properties, i was found this:

![屏幕截图 2024-08-18 105852](https://github.com/user-attachments/assets/28cbad37-362c-4824-9907-273f7e81fbb6)

**Comment by floatval** [comment]
this is the repo url https://github.com/Hopding/pdf-lib  which i have been saw in pdf properties

**Comment by forehalo** [comment]
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/5fc9c6cb-388f-4367-b40d-0b9cdbbf03ce">

cannot reproduce

**Comment by floatval** [comment]
> <img alt="image" width="1048" src="https://private-user-images.githubusercontent.com/8281226/361628137-5fc9c6cb-388f-4367-b40d-0b9cdbbf03ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Mjc1NzMsIm5iZiI6MTcyNDgyNzI3MywicGF0aCI6Ii84MjgxMjI2LzM2MTYyODEzNy01ZmM5YzZjYi0zODhmLTQzNjctYjQwZC0wYjljZGJiZjAzY2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDY0MTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg3YjU4ZGNlZTViNDIxNmM0M2E2NjgyYmFhYWEzMjlhNWNkMTQxYzQyZGIxYjMxYTA2OGMwZGM5MWQzMWJkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.94Ew_yV0mQi_03NkX10IiWJ9HA1wS7CTk3rsK3uyrQk">
> cannot reproduce

windows already have the problem.........
