### ISSUE TITLE
drag and drop switch not work in virtualbox guest environment

### ISSUE THREAD

**Issue by AlphaMTV** [toeverything/AFFiNE#7917]
### What happened?

my host system is windows 11 press space bar can drag and drop normally.

but in windows 10 virtualbox guet press space bar can not drag and drop normally.

![image](https://github.com/user-attachments/assets/2d2f32ce-eeaa-428c-b1c9-8056d422fd8e)

### Distribution version

Windows x64

**Comment by forehalo** [comment]
the drag are drop behaviors are built on top of web standards. if it doesn't work as expected, it must have been affected by virtualbox settings
