### ISSUE TITLE
Wrong workspace state after logging out

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#792]

**Comment by joebeijing** [comment]
After signing out, the Cloud Workspaces should hide for current device.

**Comment by DiamondThree** [comment]
Closed by #830

**Comment by ShortCipher5** [comment]
The workspace seems to be removed whether or not users choose to retain data. I would only expect the workspace to be removed if this is not ticked.

![Image](https://user-images.githubusercontent.com/4605025/218629421-587c31b4-8acf-460f-9db3-1b5a35d3b42d.png)

**Comment by joebeijing** [comment]
CC @ShortCipher5
