### ISSUE TITLE
​No way to exit out of settings upon creating account

### ISSUE THREAD

**Issue by InfamousUser** [toeverything/AFFiNE#7939]
### What happened?

After creating an account on a new node, it leaves me in /admin/config, and there's no way to get out of this that I can see, no X, no exit and no back, just dead-end settings.

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Firefox

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
Just visit the root
