### ISSUE TITLE
​code box mess up after upgrade to 0.16.3 (selfhosted)

### ISSUE THREAD

**Issue by cex-trader** [toeverything/AFFiNE#7964]
### What happened?

![QQ_1724461874379](https://github.com/user-attachments/assets/c3419cfd-c538-4e57-9176-61549b6d70db)

![QQ_1724461731077](https://github.com/user-attachments/assets/68d1347f-c78d-4bd1-a8a0-3c3204096958)

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
it has been fixed, please pull the latest image
