### ISSUE TITLE
​Release beta Android App

### ISSUE THREAD

**Issue by sai-anand-k** [toeverything/AFFiNE#7966]
### Description

Release android app faster please !!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
we are making an mobile browser compatible version and the native app for android is not yet considered

**Comment by andsofine** [comment]
@forehalo @EYHN Is this comment about mobile browser compatibility? 
https://github.com/toeverything/AFFiNE/issues/6517#issuecomment-2051227031

**Comment by andsofine** [comment]
?
