### ISSUE TITLE
​ ​Self-hosted: Sign in email has invalid button URL - reopening.

### ISSUE THREAD

**Issue by gcarrarom** [toeverything/AFFiNE#7978]
### What happened?

Reopening issue  #6024  since it has not been resolved.
> I managed to get the mailing service working on my self-hosted instance. I've tested that it can send verification emails, and password set emails for new users. However, for the verification emails, I found that it's got localhost for the origin, followed by my hostname that I set in my environment variable.
> 
> I've looked into the codebase, and it seems that the bug should be around here. I'm just not sure how this code works yet.
> 
> https://github.com/toeverything/AFFiNE/blob/c1afdb9bd6979dac2b5bbaf40b4b948adfe780f0/packages/backend/server/src/core/auth/utils/send-mail.ts#L15-L27
> 
> Screenshots of the emails below:
> Sign In 	Set Password
> ![Image 2](https://github.com/toeverything/AFFiNE/assets/25047551/5f15592e-592c-4222-b968-1a2963ab66f0) 	![Image 1](https://github.com/toeverything/AFFiNE/assets/25047551/d9fe6bbd-f8e8-40d5-975d-26b5acf8f82d)
> ### Distribution version

I still have this issue happening with version 0.16.0 and setting NEXTAUTH_URL and AFFINE_SERVER_HOST. 

### Distribution version

Linux

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
what do you get if you request your instance by 
```
fetch("https://${host}/graphql", {
  "headers": {
    "content-type": "application/json",
    "x-definition-name": "serverConfig",
    "x-operation-name": "serverConfig"
  },
  "body": "{\"query\":\"\\nquery serverConfig {\\n  serverConfig {\\n    version\\n    baseUrl\\n    name\\n    features\\n    type\\n    credentialsRequirement {\\n      ...CredentialsRequirement\\n    }\\n  }\\n}\\nfragment PasswordLimits on PasswordLimitsType {\\n  minLength\\n  maxLength\\n}\\n\\nfragment CredentialsRequirement on CredentialsRequirementType {\\n  password {\\n    ...PasswordLimits\\n  }\\n}\",\"operationName\":\"serverConfig\"}",
  "method": "POST",
});
```

**Comment by gcarrarom** [comment]
> what do you get if you request your instance by
> 
> ```
> fetch("https://affine.fail/graphql", {
>   "headers": {
>     "content-type": "application/json",
>     "x-definition-name": "serverConfig",
>     "x-operation-name": "serverConfig"
>   },
>   "body": "{\"query\":\"\\nquery serverConfig {\\n  serverConfig {\\n    version\\n    baseUrl\\n    name\\n    features\\n    type\\n    credentialsRequirement {\\n      ...CredentialsRequirement\\n    }\\n  }\\n}\\nfragment PasswordLimits on PasswordLimitsType {\\n  minLength\\n  maxLength\\n}\\n\\nfragment CredentialsRequirement on CredentialsRequirementType {\\n  password {\\n    ...PasswordLimits\\n  }\\n}\",\"operationName\":\"serverConfig\"}",
>   "method": "POST",
> });
> ```

Here's what I get: 
```json
{
  "version": "0.16.1",
  "baseUrl": "http://localhost:3010",
  "name": "Self-Host Cloud",
  "features": [],
  "type": "Selfhosted",
  "credentialsRequirement": {
    "password": {
      "minLength": 8,
      "maxLength": 32
    }
  }
}
```

**Comment by forehalo** [comment]
@gcarrarom can you pull the latest image and give it a try? the latest version should be 0.16.3, and we've fixed a issue regarding outdated config files and that may cause setting of `AFFIN_SERVER_HOST` not working as expected

**Comment by mochiruntime** [comment]
@forehalo @gcarrarom I am facing the same issue; I also tried to pull the latest image `canary-10a066a` but it seems the version is still 0.16.0?

```json
{
  "data": {
    "serverConfig": {
      "version": "0.16.0-nightly-10a066a",
      "baseUrl": "http://localhost:3010",
      "name": "Self-Host Cloud",
      "features": [],
      "type": "Selfhosted",
      "credentialsRequirement": {
        "password": { "minLength": 8, "maxLength": 32 }
      }
    }
  }
}
```

**Comment by gcarrarom** [comment]
Yep, same here. Just pulled stable and got:
```json
{
  "version": "0.16.0-nightly-eb0466e",
  "baseUrl": "http://localhost:3010",
  "name": "Self-Host Cloud",
  "features": [],
  "type": "Selfhosted",
  "credentialsRequirement": {
    "password": {
      "minLength": 8,
      "maxLength": 32
    }
  }
}
```

**Comment by forehalo** [comment]
<img width="801" alt="image" src="https://github.com/user-attachments/assets/9ee54fa8-7bd2-41fb-94f5-befceb625f60">

@gcarrarom  I run a brand new deploy with the same image version as yours and it works with ENV.

```
AFFINE_SERVER_HOST=affine.self.host
```

if it keep failing, you may delete the `~/.affine/self-host/config/affine.env.js` file on your host and restart the instance. an updated env mapping will be copied to the location, no worry

**Comment by gcarrarom** [comment]
That did work! The `AFFINE_SERVER_HOST` line in the `affine.env.js` was `host` and changed to AFFINE_SERVER_HOST: 'server.host'. Then the request resolves to the right baseUrl. Now the email is using the proper host. Thanks!
