### ISSUE TITLE
​Reference function, automatically displays alternative documents, does not support Chinese

### ISSUE THREAD

**Issue by tangyuancat** [toeverything/AFFiNE#7980]
### What happened?

​Reference function [[ or @, automatically displays alternative documents, does not support Chinese

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

**Comment by forehalo** [comment]
<img width="414" alt="image" src="https://github.com/user-attachments/assets/11c6843f-f8a1-4824-a244-d731e6bc8de3">

any information on the behavior
