### ISSUE TITLE
​ freely control the ratio of width and height

### ISSUE THREAD

**Issue by tangyuancat** [toeverything/AFFiNE#7981]
### Description

When inserting a document into the whiteboard, you cannot freely control the ratio of width and height, and can only select the percentage of scaling

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
what do you mean by "document"? the size of note block on edgeless can be freely adjusted

**Comment by tangyuancat** [comment]
document is card on the edgeless view。
Now it can only be scaled in the same proportion, and the length and width ratio cannot be adjusted freely.
![333](https://github.com/user-attachments/assets/ed09dad6-5583-4420-9177-e5bf0c19ec25)

**Comment by forehalo** [comment]
@hwangdev97 take a look

**Comment by hwangdev97** [comment]
https://github.com/user-attachments/assets/03b27025-4721-49d4-b91c-919be5f60cd2

You can use embed view to control the ref-doc's width and height
