### ISSUE TITLE
Incorrect line number alignment in code block affecting text indentation

### ISSUE THREAD

**Issue by emanuelfc** [toeverything/AFFiNE#7992]
### What happened?

The line numbers of the code block seem to be left-aligned instead of right-aligned, and therefore affect the indentation of the text of the code block.

This can be seen in the example below - lines 9 and 10:
![image](https://github.com/user-attachments/assets/41f30ddf-a33d-4f11-ba84-6bf7e9285522)

With correct alignment it would be:
![image](https://github.com/user-attachments/assets/4b2d3007-b635-4dff-87a8-03509e50b3a9)

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Chrome, Microsoft Edge, Firefox

### Are you self-hosting?

- [ ] Yes

**Comment by forehalo** [comment]
already fixed and will come with 0.16.4 today if everything goes well
