### ISSUE TITLE
subpages links not work when shared

### ISSUE THREAD

**Issue by Timtaran** [toeverything/AFFiNE#8015]
### What happened?

subpages links simply not work

https://github.com/user-attachments/assets/9a3ab4a6-72a8-4158-bba2-bbfa1fa7d605

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [ ] Yes

**Comment by Timtaran** [comment]
Update: subpages are not even shared recursively

**Comment by artwist-polyakov** [comment]
Hello, after last update attached files and images are also unavailable
![CleanShot 2024-09-10 at 01 08 22@2x](https://github.com/user-attachments/assets/a1e647d4-e6f1-436f-899b-bf1763facacb)

**Comment by 0-Vanes-0** [comment]
As mentioned in #8248, current workaround is to create public link for every subpage and write them near:
![image](https://github.com/user-attachments/assets/fef04a1a-b5b5-4205-913c-107d713baf4d)

**Comment by artwist-polyakov** [comment]
@0-Vanes-0 I think, that issue was created to show a bug for developers, not to explore workaround

**Comment by 0-Vanes-0** [comment]
> @0-Vanes-0 I think, that issue was created to show a bug for developers, not to explore workaround

Sure. I wrote that if someone needs this to work _right now_ (like me)

**Comment by forehalo** [comment]
closed by #8238, will be landed in 0.17.0 this week
