### ISSUE TITLE
Notion import - Subpages links works exclusively for the main exported page.

### ISSUE THREAD

**Issue by Timtaran** [toeverything/AFFiNE#8016]
### What happened?

notion 
![изображение](https://github.com/user-attachments/assets/f71a3b46-da7e-4a91-b4d6-9353587c3a7b)

affine
![изображение](https://github.com/user-attachments/assets/ff2fa7c5-794b-44c3-be5e-852ae6db705c)

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [ ] Yes

**Comment by fourdim** [comment]
Fixed by https://github.com/toeverything/blocksuite/pull/8097
