### ISSUE TITLE
​Notion import - Imported files overrides each other

### ISSUE THREAD

**Issue by Timtaran** [toeverything/AFFiNE#8017]
### What happened?

If you have files with exact same filename in different pages affine would override it with last imported (probably)
![import issue](https://github.com/user-attachments/assets/16974879-e2a4-44f4-a1b8-db2ce6ed63f9)

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [X] Yes

**Comment by fourdim** [comment]
Fixed by https://github.com/toeverything/blocksuite/pull/7979

For now you can use following config as a workaround:
![image](https://github.com/user-attachments/assets/5d4436f9-cc98-471e-baaa-a3b0fb2ae8cd)

The new release will come up soon.
