### ISSUE TITLE
​10M size limit for uploading files

### ISSUE THREAD

**Issue by jeron-lgy** [toeverything/AFFiNE#8057]
### Description

10M size limit for uploading files
![image](https://github.com/user-attachments/assets/799d3d98-23ce-44a7-ad69-439b13f1f668)

### Use case

Local project files
Some video clips

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
it's the limit of workspace created by free account. checkout the pricing page
