### ISSUE TITLE
Unable to login using gmail address with custom domain

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#807]

**Comment by tzhangchi** [comment]
@darkskygit Could we support non-gmail address?

**Comment by darkskygit** [comment]
> @darkskygit Could we support non-gmail address?

frontend logic needs some changes, and the backend basically does not need to be changed.

**Comment by tzhangchi** [comment]
@QiShaoXuan could you follow it？

**Comment by tzhangchi** [comment]
related to https://github.com/toeverything/AFFiNE/issues/2648
