### ISSUE TITLE
Links inside shared doc to another shared docs are broken

### ISSUE THREAD

**Issue by rodionovid** [toeverything/AFFiNE#8154]
### What happened?

Hello. I am using self-hosted affine app installed on my web server according official instruction. I also configured access to the app via domain name using nginx, obtain ssl certificate and that's all I did besides the instruction. 
Now I am trying to share a doc that includes links to another shared docs inside my affine workspace. In case of workspace itself those links work just fine. But in case of shared version of my document those links don't work and looks like these: 

`https://4qL2_pdfiq9-2_cnEdjNQ`

I expect that in shared version of my doc links to another shared docs should be valid.

### Distribution version

Web (app.affine.pro)

### Are you self-hosting?

- [X] Yes

### Anything else?

Here is a link to my test shared doc that links to another shared doc:
https://affine.vrchemlab.ru/share/108c165a-04af-41f3-8c45-33ef7c78fee5/GD0dlDF_Y0rK0-qP1GocW

**Comment by Timtaran** [comment]
duplicate #8015
