### ISSUE TITLE
Cloud icon does not provide any information

### ISSUE THREAD

**Issue by doodlewind** [toeverything/AFFiNE#821]
The upper right cloud icon does not seem to show any indication or further infomation (such as tooltip on mouse over).

This icon is always visible - local/loud workspace and doesn't seem to change or do anything.

![Image](https://user-images.githubusercontent.com/4605025/216877997-94c23465-3ff9-4cf2-9397-e77da6854082.png)

**Comment by joebeijing** [comment]
Missing hovertips.
