### ISSUE TITLE
Change "Wait for Sync" to "Not Now"

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#824]
Since there is no automatic process of signing out after the synchronization is completed after clicking "Wait for Sync", it should be  changed to the simpler copywriting "Not Now".

![Image](https://user-images.githubusercontent.com/22443345/216923935-043e3dba-922a-44bc-8393-7571b29b75d0.png)

**Comment by tzhangchi** [comment]
@DiamondThree could you get the improvement reason

**Comment by tzhangchi** [comment]
@joebeijing it's the same with #791

**Comment by DiamondThree** [comment]
Closed by #886
