### ISSUE TITLE
​Data Loss in PDFs/PNGs/Others

### ISSUE THREAD

**Issue by offensive-vk** [toeverything/AFFiNE#8256]
## Export Document is Malfunctioning.

Whenever I Creating or Updating any Document in AFFiNE this Happens. 
Whenever I export that or any Document in PDF/PNG/Markdown format there is always few ending string from heading and text goes missing. Like nothing was there lol. 

Idk why this is happening , but it got fixed earlier. 

*That's a problem in my regular workflow guys.*

![image](https://github.com/user-attachments/assets/0beee9cc-403f-48a6-8a50-cf3e5eb2d316)

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

### Anything else?

See image for Client Info.

![image](https://github.com/user-attachments/assets/fafc9b5a-d75c-4e5e-ae9a-599d125f4da6)

**Comment by offensive-vk** [comment]
Any updates here? or should I Close this?

**Comment by zetstream33** [comment]
I'm in same situation. In my cases, it occured when i use another devices like if i uploaded png or pdf file with desktop and disappear(or infinite time of loading) when i open it with laptop(or phone)
