### ISSUE TITLE
Change "Skip" to "Not now" in the Enable AFFiNE Cloud popup window

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#826]
Screenshot attached.

![Image](https://user-images.githubusercontent.com/22443345/216925168-8248a30d-1655-4c45-9d85-2b4c2c094438.png)

**Comment by joebeijing** [comment]
This is an optimization of the product copywriting, it is recommended to modify it. @tzhangchi

**Comment by tzhangchi** [comment]
Definitely it should be modified，@QiShaoXuan could make the button text easier to understand
