### ISSUE TITLE
Simple table block

### ISSUE THREAD

**Issue by beraza** [toeverything/AFFiNE#8265]
### Description

Please add simple table block (like in Notion).
![CleanShot 2024-09-16 at 15 16 36](https://github.com/user-attachments/assets/38b1c9b5-4604-4117-80a1-89e3f4204b24)
![CleanShot 2024-09-16 at 15 17 09](https://github.com/user-attachments/assets/4de50a47-1688-4d02-a513-f2b8c50c0648)

### Use case

It's useful when you don't need the capabilities of a table database, but just need to store information in a tabular format.

### Anything else?

Video preview: https://youtu.be/m_uo9sUvVGA?si=AT_bzDqar65nzAHe

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Flakky** [comment]
Yes, almost every note app has a table block. Very useful feature to have.

**Comment by Sciroccogti** [comment]
And the current Table View does not support copying multiple cells, which I believe is a necessary feature.

**Comment by jghaanstra** [comment]
Even though it's not even there yet I'd also like to see a merge cells feature ...
