### ISSUE TITLE
​User-Controlled Management and Switching of Local Data Paths

### ISSUE THREAD

**Issue by EnterMan123** [toeverything/AFFiNE#8342]
### Description

Local Data Path Management and Switching

1. Provide quick access to the local data path in the settings.
2. Allow users to set a default local storage path for convenience and ease of access.
3. Ensure that the interface for managing and switching paths is intuitive and easy to navigate.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
duplicated #8263
