### ISSUE TITLE
​Code Block buttons have incorrect position

### ISSUE THREAD

**Issue by medinnna** [toeverything/AFFiNE#8345]
### What happened?

The floating options buttons from the Code Block remains fixed on scroll, apparently the `blocksuite-portal` class have `position: fixed` instead of `position: absolute`.

https://github.com/user-attachments/assets/8028711c-a7ff-4606-bf26-dedfbd16d0f8

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by lawvs** [comment]
Fix in https://github.com/toeverything/blocksuite/pull/8430, thank you for your feedback.
