### ISSUE TITLE
Default avatar when inviting users is not right

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#836]
Maybe we can use letters as a default avatar image for Email invitation.

![Image](https://user-images.githubusercontent.com/4605025/216910927-25753149-22b6-4817-a304-483c4b4782f1.png)

**Comment by joebeijing** [comment]
From the design draft, if the avatar can be obtained, the avatar will be displayed, if not, the general mailbox icon will be displayed @tzhangchi 
<img width="339" alt="image" src="https://user-images.githubusercontent.com/22443345/217443866-81aa650d-e32f-42a7-a16e-02103c67dd5e.png">

**Comment by tzhangchi** [comment]
> From the design draft, if the avatar can be obtained, the avatar will be displayed, if not, the general mailbox icon will be displayed @tzhangchi <img alt="image" width="339" src="https://user-images.githubusercontent.com/22443345/217443866-81aa650d-e32f-42a7-a16e-02103c67dd5e.png">

Oh, Thank you , I get it , I will discuss with @zuoxiaodong0815 , now it it not high level requirement
