### ISSUE TITLE
​Self-hosted OIDC and /api/auth/sign-out

### ISSUE THREAD

**Issue by amravyan** [toeverything/AFFiNE#8380]
### What happened?

Hi!
I've noticed strange behavior in the login flow when OIDC is configured on self-hosted instance:

- In version 0.17.0-beta4, after logging in using OIDC, we see a request to /api/auth/sign-out that instantly returns a 401 error, and the flow proceeds as expected.
- In version 0.17.0-stable, we see the same request, but it hangs and eventually results in a 504 error due to a timeout configured in Nginx.

No configuration was changed after version upgrade.
<img width="1590" alt="401" src="https://github.com/user-attachments/assets/9a75d1c7-d069-4874-ac60-aa8414132fc1">
<img width="1585" alt="504" src="https://github.com/user-attachments/assets/9b37940f-69ad-4782-9272-d133d7f9bd91">

Could you investigate what changes may have caused this behavior?

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
fixed in 0.17.1
