### ISSUE TITLE
Desktop-client not changing size when using fullscreen

### ISSUE THREAD

**Issue by tristanRW** [toeverything/AFFiNE#8418]
### What happened?

When I change the size of the window manually, the desktop client fits the window.
When I drag the window to the top of the screen to set its size to fit the screen the desktopclient instead generates a white background to fill the window, but does not change size itself.

If I press a keyboard shortcut to set the window into "true fullscreen" (where it is above the taskbar as well) and out again, the size of the client correctly changes size to fit the window without the white fill.

### Distribution version

Linux

### Are you self-hosting?

- [ ] Yes

### Anything else?

![image](https://github.com/user-attachments/assets/3ee921af-7b59-45ea-856e-cdc51413f0b9)

**Comment by forehalo** [comment]
fixed in #8413
