### ISSUE TITLE
Miss test case about cloud features(user stories after login success)

### ISSUE THREAD

**Issue by DiamondThree** [toeverything/AFFiNE#842]

**Comment by DiamondThree** [comment]
Logout  #830
Invite member  #825

**Comment by tzhangchi** [comment]
Because the login service is waiting to be modified, we cannot immediately support the e2e test of the login function and inviting member function, but we will improve this issue before the next version is released @DiamondThree @darkskygit @doodlewind @zuoxiaodong0815

**Comment by tzhangchi** [comment]
The most ideal way is to cooperate with the backend, whether it supports login or advance a sandbox enterprise for testing

**Comment by JimmFly** [comment]
public-workspace #819
