### ISSUE TITLE
​Link to a document inside the table

### ISSUE THREAD

**Issue by psycholo-G** [toeverything/AFFiNE#8422]
### Description

Inside a Table I can add a link to a website, but I want to add a link to a block or site INSIDE Affine. This would be great.

### Use case

You can sort stuff in a table

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
currently doc or block link can be put in the `title` column.

**Comment by CptCurk** [comment]
@forehalo nevermind, with the @ option

**Comment by Cironic** [comment]
Is there an option by now to link an existing page within a table? I didn't find a way.
