### ISSUE TITLE
​Invalid Email and Password during Admin Account Creation

### ISSUE THREAD

**Issue by brentonmallen1** [toeverything/AFFiNE#8425]
### What happened?

When I try to create the Admin Account, when first starting the service, it says that both my email and password are invalid when they are.  I get a 500 error code and see the below in the container logs when I click the continue button.

I'm running in `unraid` and using the `ghcr.io/toeverything/affine-graphql:stable` image. I am using existing redis and postgres containers and have provided those connection env variables as required. I've tried both with and without a reverse proxy, with and without tls.

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Other

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
[Nest] 1  - 10/02/2024, 7:32:24 PM   ERROR [HTTP] Internal server error
PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation:


An operation failed because it depends on one or more records that were required but not found. No 'Feature' record(s) (needed to inline the relation on 'UserFeature' record(s)) was found for a nested connect on one-to-many relation 'FeatureToUserFeature'.
    at Ln.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7753)
    at Ln.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7061)
    at Ln.request (/app/node_modules/@prisma/client/runtime/library.js:121:6745)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async CustomSetupController.createAdmin (file:///app/dist/core/selfhost/controller.js:91:26)
```

### Anything else?

I'm usually in the Brave browser but I've tried Firefox as well but still saw the same behavior.  I've looked at the suggested docker-compose in the unraid app description: `https://github.com/toeverything/AFFiNE/blob/stable/.github/deployment/self-host/compose.yaml` but I didn't want to have to spin up other resources that I already have. I'm not sure what is specifically different about this besides the other resources, but I've even added the `--import=./scripts/register.js` part in NODE_OPTIONS

The (sanitized) command that was executed to create the container is:
```
docker run
  -d
  --name='AFFiNE'
  --net='bridge'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="abcd"
  -e HOST_CONTAINERNAME="AFFiNE"
  -e 'AFFINE_ADMIN_EMAIL'='abcd@abcd.com'
  -e 'AFFINE_ADMIN_PASSWORD'='abc'
  -e 'AFFINE_SERVER_HOST'='192.168.1.123'
  -e 'AFFINE_SERVER_PORT'='1234'
  -e 'AFFINE_SERVER_HTTPS'='false'
  -e 'MAILER_HOST'='smtp.gmail.com'
  -e 'MAILER_PORT'='587'
  -e 'MAILER_USER'='abc@gmail.com'
  -e 'MAILER_PASSWORD'='abc'
  -e 'MAILER_SENDER'='abcd@abcd.com'
  -e 'DATABASE_URL'='postgres://postgres:postgres@postgres:5432/affine'
  -e 'REDIS_SERVER_HOST'='192.168.1.123'
  -e 'REDIS_SERVER_PORT'='6375'
  -e 'NODE_ENV'='production'
  -e 'NODE_OPTIONS'='--import=./scripts/register.js'
  -e 'TELEMETRY_ENABLE'='false'
  -e 'REDIS_PASSWORD'='redis'
  -e 'logLevel'='Debug'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:3010]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/toeverything/AFFiNE/canary/packages/frontend/electron/resources/icons/icon.png'
  -p '3049:3010/tcp'
  -v '/mnt/user/appdata/affine':'/root/.affine':'rw' 'ghcr.io/toeverything/affine-graphql:stable'
```

**Comment by regulate-tions** [comment]
I encountered the same problem as you. The self-hosted system was deployed on DOCKER. The email address and password were correct. After logging out and logging in again, it kept saying that the password was wrong. I couldn't find any content inside. The official reply was also perfunctory. I advise all self-hosted users to think twice before using this for production activities.

**Comment by zetstream33** [comment]
Same problem here. In my case, i encountered error when trying to run docker after i updated to 1.7.2 stable. I guess the reason for this is postgres has been updated from 16 to 17. So i manually changed postgres image version 16 and error cleared! BUT, after i logout from my onw AFFiNE, I could not re login that it kept saying the password was wrong. 

I've checked through ' docker exec -it affine_postgres psql -U affine' , 'affine=# select * from users;' and checked all password has been saved as before. Currently, i could not login to my own selfhosted service 🤯

**Comment by zetstream33** [comment]
@regulate-tions @brentonmallen1 
> I encountered the same problem as you. The self-hosted system was deployed on DOCKER. The email address and password were correct. After logging out and logging in again, it kept saying that the password was wrong. I couldn't find any content inside. The official reply was also perfunctory. I advise all self-hosted users to think twice before using this for production activities.

Same problem here. In my case, i encountered error when trying to run docker after i updated to 1.7.2 stable. I guess the reason for this is postgres has been updated from 16 to 17. So i manually changed postgres image version 16 and error cleared! BUT, after i logout from my onw AFFiNE, I could not re login that it kept saying the password was wrong. 

I've checked through ' docker exec -it affine_postgres psql -U affine' , 'affine=# select * from users;' and checked all password has been saved as before. Currently, i could not login to my own selfhosted service 🤯

**Comment by brentonmallen1** [comment]
I tried upgrading postgres to 17 as well and still ran into the same issue.

**Comment by forehalo** [comment]
you should run every command listed in `compose.yaml` if you want to run a custom instance.

Specifically for your issue, you should run the following to start your app

```
# remember `NODE_OPTIONS="--import=./scripts/register.js"`
node ./scripts/self-host-predeploy.js
node ./dist/index.js
```

**Comment by brentonmallen1** [comment]
thanks @forehalo! That seems to have unblocked me.

For those who might find themselves here when trying to spin this up via Unraid, my steps to get it running are as follows:

1) install the app from the Unraid store, making sure to add the `NODE_OPTIONS` mentioned above.
2) It failed on intitial startup, with the `Invalid `prisma.runtimeConfig.findMany()` invocation: ` log mentioned in the app notes.
3) Restarted the container, which got it in a running state. In the container's console, I ran the following commands:
```
yarn prisma migrate deploy && node --import ./scripts/register.js ./dist/data/index.js
node ./scripts/self-host-predeploy.js
node ./dist/index.js
```
The last one gave me an error about a port or host being in use already but that didn't seem to cause any issues with moving forward. 
4) restarted the container just in case

I was then able to create an admin account and begin exploring the application.
