### ISSUE TITLE
​Full width layout

### ISSUE THREAD

**Issue by DawidRyba-1942** [toeverything/AFFiNE#8426]
### What happened?

Since the latest update, I’ve been unable to keep the app’s layout in full-width mode. It always reverts to the default setting when I close and reopen the app

### Distribution version

Windows x64

### Are you self-hosting?

- [X] Yes

**Comment by Idlehanker** [comment]
My windows 11 x64 with AFFiNE 0.17.2 reproduce too. The "Full width layout" turn on, but the switch is closed once reopen App. Why "Full width layout" toggle cannot stay open status?

**Comment by forehalo** [comment]
fixed by #8450
