### ISSUE TITLE
​Open in sidebar when sharing not works

### ISSUE THREAD

**Issue by Timtaran** [toeverything/AFFiNE#8430]
### What happened?

![изображение](https://github.com/user-attachments/assets/06867cb5-6df8-42d0-85f2-2b0c362f4d18)
If you click "Open in sidebar" nothing will happen

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
it shouldn't be there in shared page @L-Sun
