### ISSUE TITLE
Sharing improvements

### ISSUE THREAD

**Issue by Timtaran** [toeverything/AFFiNE#8432]
### Description

1. Currently, if you share a page, it will not include child pages, and you will need to share them all yourself
2. Add possibility to give access to users to single page/folder and not whole workspace

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
there is no "child pages" concept, they all exists as page links, it's not safe to  simply apply the same visible setting for all linked pages. 
let's say if users delete a page link from a shared page, what's the behavior supposed to be? make the linked page private? but they may not want such, instead they want to keep it public. 
it's quite not easy to make everyone happy but at least we can keep all user's data safe, by not sharing linked page by default.

**Comment by Timtaran** [comment]
that's makes sense 

you can make something like meta-tags of pages when creating a subpage so that affine understands that this is not just a link to some document, but to child, or other options, but it will probably require large changes in the code, so I think it's easier to close this issue

**Comment by Timtaran** [comment]
@forehalo oh, and also, I forgot
what about second idea? like not giving access to whole workspace, but for single pages and implement view-only setting
