### ISSUE TITLE
​If you follow the self-host upgrade instructions right now Affine will not work

### ISSUE THREAD

**Issue by Stuie** [toeverything/AFFiNE#8453]
### What happened?

I saw that there was an upgrade to Affine, so I followed [the instructions to upgrade](https://docs.affine.pro/docs/self-host-affine#upgrade-your-self-hosted-affine). The steps include a `docker-compose pull`. That pulls in postgres 17, which will not work if you set up Affine with a prior version (e.g. 16).

You can avoid the upgrade by modifying the `compose.yaml` file to specify the postgres version on the image line: `image: postgres:16` but that's not mentioned anywhere in the documentation.

I can't find a way to create a PR for the self-hosting documentation. I tried searching the toeverything org for phrases that are present.

Should the postgres version be hard-coded to avoid this issue? Perhaps until the latest postgres has been tested to be compatible, or there's a migration path, etc.?

### Distribution version

Web (app.affine.pro)

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
2024-10-08 07:49:30.936 UTC [1] FATAL:  database files are incompatible with server
2024-10-08 07:49:30.936 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).

PostgreSQL Database directory appears to contain a database; Skipping initialization
```

**Comment by forehalo** [comment]
you can pin postgres version like this https://github.com/toeverything/AFFiNE/pull/8420

**Comment by Stuie** [comment]
Ah, it's been merged already, that's great!

On a related note, are the self-hosting docs on GitHub somewhere so PRs can be created?
