### ISSUE TITLE
​Highlight the searched keywords in the opened page

### ISSUE THREAD

**Issue by chenxiccc** [toeverything/AFFiNE#8476]
### Description

Now only in the search bar, the keyword is highlighted.
But when you open the search results, the keyword is NOT highlighted.
It is not easy to find the keyword in the long pages.

It would be better if the keyword is highlighted in the opened page.

The following is a good case
<img width="1434" alt="image" src="https://github.com/user-attachments/assets/b473e26d-8bdc-4c7a-ae6c-e28a684db013">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
<img width="933" alt="image" src="https://github.com/user-attachments/assets/35e0dbd9-50de-447f-84a0-484af9ed967e">
we got block highlight after navigating to matched doc
