### ISSUE TITLE
​Mobile web - Drawer menu and text editing bugs

### ISSUE THREAD

**Issue by udany** [toeverything/AFFiNE#8481]
### What happened?

When using the web version on mobile there are two main bugs:

1. The menu can't be easily closed
2. When editing text, accepting the keyboard's predictive suggestions/corrections duplicates the text

https://github.com/user-attachments/assets/7f54dedd-de40-4c8e-885e-83207065c14b

https://github.com/user-attachments/assets/41177534-27cd-4332-a9fd-3ec412a34e3c

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

### Anything else?

Android chrome 129

**Comment by BadriVishalPadhy** [comment]
want to work on this issue

**Comment by forehalo** [comment]
fixed in #8475
