### ISSUE TITLE
​Cut/Split the Page in Edgeless Mode Missing?

### ISSUE THREAD

**Issue by Zuiluj** [toeverything/AFFiNE#8490]
### What happened?

I'm looking for the feature I used to use heavily in edgeless mode where I can cut/split the page from Page Mode and it'll have indexes. Then, I can use it to connect to others:

This is how I usually use it:
![image](https://github.com/user-attachments/assets/7470fed1-e3c9-4c4e-83ef-3b79826184d6)
The blocks that have images and text are in my page mode:
![image](https://github.com/user-attachments/assets/d664a972-1c1d-47a7-a549-d4a21199dfb5)

In edgeless mode,
there used to be a "scissor" icon when I hover my mouse on the sides of the page or a scissor icon when I select a page, which I can use to split/cut the page and place it wherever I like. Where is it now?

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by CatsJuice** [comment]
Please go to settings and enable this feature flag:
![CleanShot 2024-10-14 at 16 29 34@2x](https://github.com/user-attachments/assets/b5632dd0-151f-47c7-97ff-0bcc9fcbfa2d)

Then refresh page or reopen AFFiNE to make it work.

**Comment by CatsJuice** [comment]
Feel free to reopen this issue if the problem is not resolved.

**Comment by Zuiluj** [comment]
Solved. The scissor icon is now back. Thank you!
