### ISSUE TITLE
[bug]: After deleting the last group on a page, there's a leftover empty block.

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#85]
### Describe the bug

After deleting last group in a page, there's a leftover empty block.

### To Reproduce

1. make sure there is only one group in the current page.
2. delete this group by clicking the group handle and select "Delete" from the menu.
3. A block handle (3 dots) is leftover and cannot be delete or inserted contents.

### Screenshots

https://user-images.githubusercontent.com/132558/182771514-181de25e-7912-4c9c-b372-e4848d5fbf32.mov

### Expected behavior

There should not be any leftover block.

### Platform

macOS

### Browser

Chrome and Safari

**Comment by fyZheng07** [comment]
done
