### ISSUE TITLE
A white screen appears when opening website https://stage.affine.pro/

### ISSUE THREAD

**Issue by zuoxiaodong0815** [toeverything/AFFiNE#850]

**Comment by zuoxiaodong0815** [comment]
![Image](https://user-images.githubusercontent.com/53252747/217147075-55ab069d-658c-4326-b953-84319e5ff5c1.png)



![Image](https://user-images.githubusercontent.com/53252747/217147126-634eb4a4-77d6-4692-a9c4-d44f57ffd1f2.png)

**Comment by tzhangchi** [comment]
The latest version stop the behavior which is auto redirecting
