### ISSUE TITLE
​The account that has already been created needs to be created again.

### ISSUE THREAD

**Issue by TheShining** [toeverything/AFFiNE#8504]
### What happened?

I have already created an account and used it for a while, with the account being liangliang0311@live.com. However, when I try to log in on another computer, it prompts me to create an account again. Will this result in the loss of my notes?
![image](https://github.com/user-attachments/assets/58cb9403-7c5c-4bbb-a06b-2dedb0026236)

### Distribution version

Windows x64

### Are you self-hosting?

- [ ] Yes

**Comment by forehalo** [comment]
are you sure you are using the same email to login? I don't find any account information regarding this email

**Comment by TheShining** [comment]
> are you sure you are using the same email to login? I don't find any account information regarding this email
Yes, I registered an account on the website affine.fail using my email. My password manager Bitwarden shows this email, and I have logged in on my previous broken computer as well.

![image](https://github.com/user-attachments/assets/c76a384b-0002-4cfb-a374-9957c7604d55)

**Comment by ShortCipher5** [comment]
After investigation it seems this account is linked to the "Canary" environment, where this is no guarantee of data persistence.

If you wish to utilise the sync and backup features of AFFiNE Cloud we advise to use the Stable branch of AFFiNE - either through the desktop client (https://affine.pro/download) or web app (https://app.affine.pro/).
