### ISSUE TITLE
​Needs a way to unlink documents from the sidebar.

### ISSUE THREAD

**Issue by wakmail** [toeverything/AFFiNE#8523]
### Description

Should allow unlinking documents from sidebar.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
dnd to add doc link in sidebar is a shortcut for adding page link in doc content. it's impossible to decide what the behavior should be if it's possible to remove doc link in sidebar if a doc linked more then once in another doc.
