### ISSUE TITLE
​Self-hosted, full-width layout is used in edit mode, but the shared link is still not applied (anonymous viewing without logging in)

### ISSUE THREAD

**Issue by JamesWangccc23** [toeverything/AFFiNE#8534]
### What happened?

Edit mode:
![screenshot_2024-10-17_14-33-50](https://github.com/user-attachments/assets/ccb1c5d4-a5d2-467b-afbc-7ab84a6eb9ec)

Read only mode:
![screenshot_2024-10-17_14-34-33](https://github.com/user-attachments/assets/dc38bdd0-5cb2-4fbd-be2e-dfac92bb6e61)

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
`full-width` feature is only for editor not for doc content itself

**Comment by JamesWangccc23** [comment]
@forehalo Is there any plan to add this feature? I think it will be more user-friendly.
