### ISSUE TITLE
Missing valid browser titles in different pages

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#854]
![Image](https://user-images.githubusercontent.com/584378/217160305-a2114fd2-641f-46e9-b4ce-df4ff7f93ee2.png)

Right now it shows the current URL, but it should show something like "AFFiNE | xxx" etc.
Related routes
- all pages
- settings
- trash

@joebeijing

**Comment by joebeijing** [comment]
Agree with that, also for Favourites page.
