### ISSUE TITLE
​Synchronization error

### ISSUE THREAD

**Issue by Nikita-Rudakov** [toeverything/AFFiNE#8590]
### What happened?

Initially I wrote notes locally, but then decided to enable cloud synchronization. Files that were written before the transition stopped opening and were completely lost.
Help please

Account: dieze0375@gmail.com
![image](https://github.com/user-attachments/assets/3beaf49e-8f5e-4d44-b488-9fe6e3d6089e)

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

**Comment by forehalo** [comment]
we have reply you on the email. please check your mail box
