### ISSUE TITLE
​Table view rendering error after copy-and-paste

### ISSUE THREAD

**Issue by UNIDY2002** [toeverything/AFFiNE#8600]
### What happened?

**Steps to reproduce:**

- Create a sample table view
- Copy the table
- Paste it on another place

**What I see:**

All cells except for those in the last row cannot be seen in the newly pasted table view, until I refresh the page.

**What I expect to see:**

The data can be seen on the new table view immediately it is pasted.

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [ ] Yes

### Anything else?

![图片](https://github.com/user-attachments/assets/189748ff-a67c-47cb-ac08-a9898ce7181d)

**Comment by zanwei** [comment]
hi @UNIDY2002 could you please try again? I think the issue has been resolved

**Comment by UNIDY2002** [comment]
Thanks! It can be confirmed that this issue is fixed.
