### ISSUE TITLE
log in self-host

### ISSUE THREAD

**Issue by Clmnnt** [toeverything/AFFiNE#8624]
### What happened?

I can't log in admin panel and others

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
Failed to login: Cannot read properties of null (reading 'features')
```

**Comment by forehalo** [comment]
please make sure you've run every commands listed in the `compose.yml` provided if you custom deploy your instance without using it. there is a DB init script should  run before starting using selfhosted affine

**Comment by notify-bibi** [comment]
I also had this problem，Do not turn on # AFFINE_SERVER_HTTPS=true at .env config file

**Comment by phmazzoni** [comment]
Same here.
How can I enable https?

**Comment by aberenyi** [comment]
@phmazzoni you can give [traefik](https://traefik.io/traefik/) a try

**Comment by rbur0425** [comment]
> I also had this problem，Do not turn on # AFFINE_SERVER_HTTPS=true at .env config file

this!! ^^^
