### ISSUE TITLE
​[Bug Report] Zotero URL is disabled in the link option

### ISSUE THREAD

**Issue by Sereinme** [toeverything/AFFiNE#8669]
### What happened?

The zotero url is disabled in the link option while web links work.
![image](https://github.com/user-attachments/assets/a9f0f28e-1247-46e1-9ca4-5a80c082591a)

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Safari

### Are you self-hosting?

- [ ] Yes

**Comment by forehalo** [comment]
third party hyperlink is not supported yet
