### ISSUE TITLE
Email templates for inviting others are not implemented following the UI design

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#867]
Screenshot is attached

![Image](https://user-images.githubusercontent.com/22443345/217197484-850e4a0b-8570-472c-affe-2797b38e1c55.png)

**Comment by tzhangchi** [comment]
@DiamondThree  had the experience of improving email template

**Comment by tzhangchi** [comment]
it has been deal with  https://github.com/toeverything/OctoBase/pull/143

**Comment by joebeijing** [comment]
It seems that it is not fixed now.
![Image](https://user-images.githubusercontent.com/22443345/218675251-d018f4cd-837b-4cfa-bbd3-bb00757518f7.png)

**Comment by joebeijing** [comment]
Here is the screenshot of design draft.

![Image](https://user-images.githubusercontent.com/22443345/218675470-d1cf6591-befb-4f75-82be-1b6ae154df30.png)
