### ISSUE TITLE
[bug]: Several browser compatibility issues in Chrome and Safari

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#87]
## Describe the bug

Short version by a table:

Issues | Chrome | Safari
-- | -- | --
1 arrow keys | move to adjacent group with blue border | disappear in the border
2 two finger gesture in Board | mistakenly trigger “go back” | -
3 rotate in Board | - | mistakenly select extra content 

### No 1

1. locate insert cursor at the very beginning (or end) of a group.
2. move the cursor by pressing up (or down) arrow key.
3. In Chrome, the cursor moves to the above (or below) group. But in Safari, the cursor disappears and the group loses focus.

### No 2

1. In Board view, using two-finger gesture to left or right, to make a horizontal scroll.
2. If there's navigation history in the current tab, Chrome will mistakenly perform a "go back" action, making the scroll impossible. It's okay in Safari.

### No 3

1. In Board view, rotate an element by dragging the small circle.
2. In Safari, extra content will be selected incorrectly, resulting a ugly UI.

## Screenshots

No 3:

![Xnip2022-08-04_12-36-54](https://user-images.githubusercontent.com/132558/182792511-121dfc34-8f7f-4bf1-98e8-1a0b8cd392c8.jpg)

## Browser

Chrome and Safari.

**Comment by mitsuhatu** [comment]
2. hot contract
