### ISSUE TITLE
stage.affine.pro needs to have correct OpenGraph meta being added to the page

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#880]
stage.affine.pro shall have OpenGraph data configured in head/meta to attract more users.

Look at the three the embedded links in notion:
![Image](https://user-images.githubusercontent.com/584378/217215289-535e9595-5081-4b05-a1f2-dbd53279bbe4.png)

https://ogp.me/

**Comment by tzhangchi** [comment]
@JimmFly @Yipei-Operation  this issues will be beneficial for affine's seo and social network

**Comment by Yipei-Operation** [comment]
we plan to start the SEO optimization part after the downhills version is launched. And we have the budget for SEO optimization from Q2 of 2023, more details can be checked later with @HeJiachen-PM

**Comment by tzhangchi** [comment]
To stay on top of priorities, I will close this issue for now and keep an eye out for new suggestions in the future. Thank you for your contributions.
