### ISSUE TITLE
​Unable to Open App After Update: Compatibility Issue with macOS

### ISSUE THREAD

**Issue by ansenmaddock** [toeverything/AFFiNE#8831]
### What happened?

After downloading the latest update for the app (0.18.0), I attempted to open it, but received the following error message: "You can’t use this version of the application 'AFFiNE.app' with this version of macOS. You have macOS 10.15.7. The application requires macOS 11.0 or later." This issue prevents me from accessing the app entirely. I was looking forward to the new features in this update, but now I am unable to use the app. I'm unsure if this is a bug or if the developers have intentionally discontinued support for older versions of macOS.

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

**Comment by forehalo** [comment]
is your mac with intel x64 cpu but you downloaded a arm64 version of affine?
try this https://github.com/toeverything/AFFiNE/releases/download/v0.18.0/affine-0.18.0-stable-macos-x64.dmg

**Comment by Brooooooklyn** [comment]
@ansenmaddock We are unable to support macOS 10.15 because Electron has dropped support for older macOS versions, as detailed here: https://www.electronjs.org/blog/electron-33-0#breaking-changes.

**Comment by forehalo** [comment]
sry for that, but you may still be able to use AFFiNE by visiting https://app.affine.pro with latest Chrome that can be installed on your system.
