### ISSUE TITLE
self-hosted mobile sharing require login

### ISSUE THREAD

**Issue by ATPs** [toeverything/AFFiNE#8839]
### What happened?

What happened?
On mobile browsers, when attempting to open shared notes, a blank screen is displayed.

I used link from this issue https://github.com/toeverything/AFFiNE/issues/8338 
But for my own hosted version, it is the same problem.

Steps to Reproduce:

Open Chrome browser on a mobile device.
Go to [this link](https://docs.polyakov.marketing/workspace/8f799969-8391-40eb-a85e-722cd6146c06/2wXXc3IsiRkYXavczZcUA?mode=page). https://docs.polyakov.marketing/workspace/8f799969-8391-40eb-a85e-722cd6146c06/2wXXc3IsiRkYXavczZcUA?mode=page
Observe login required.

![image](https://github.com/user-attachments/assets/a6dc4294-c2d1-46b2-8f73-b2f42613b9ae)
I updated to 0.18.0

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Microsoft Edge

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
we improperly enabled the experimental mobile ui for self-host instances, which didn't handle share page correctly.

you may see the share page work as expected if you open it in desktop browser or choose to [Request desktop version] in your mobile browser.

we will soon fix it.

**Comment by artwist-polyakov** [comment]
@forehalo hello, i've just updated affine to last stable, but it doesn't show shared page if not logged in


https://github.com/user-attachments/assets/0b1a6907-5416-42cc-bbd8-cb3a1c7a3df0

**Comment by eikaramba** [comment]
can confirm this bug is still present in 18.2
shared links are not accessible on mobile view without login on self hosted version

**Comment by adan89lion** [comment]
this issue is still reproducible in stable version 0.19.5. @forehalo is it possible to reopen this issue?

**Comment by etty80** [comment]
I think this is intentional. The whole project tends to be scammy pointing user to their platform by any means.
