### ISSUE TITLE
When inputting English using the Chinese input method, pressing the Enter key will cause a line break

### ISSUE THREAD

**Issue by yuhr123** [toeverything/AFFiNE#8854]
### What happened?

As shown in the screenshot below, if I input English sentences using Chinese input method and confirm with Enter keypress, it will cause line break.

https://github.com/user-attachments/assets/b5e3f51e-5d9c-4098-b1e9-e142ac47775a

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [X] Yes

### Anything else?

<img width="289" alt="图片" src="https://github.com/user-attachments/assets/a6cac35e-3a3e-4546-b700-f5971bf287eb">

**Comment by forehalo** [comment]
I though it was fixed already. I didn't see it in nether app.affine.pro nor blocksuite  playground
