### ISSUE TITLE
​Sign in via email doesn't work in Firefox

### ISSUE THREAD

**Issue by automainint** [toeverything/AFFiNE#8890]
### What happened?

When I enter an email and click "Continue with email", the error "Failed to send email. Please try again." shows up in the bottom-right corner.

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [ ] Yes

**Comment by xoniq** [comment]
Means you dont have mail stuff setup. What I find the easiest, is to use [mailcatcher](https://github.com/dockage/mailcatcher). Which acts like a local mailserver, with a simple UI to receive the 'emails' in.

Can then be configured in the environment variables like this:

```
      - MAILER_HOST=192.168.1.10 # Docker host
      - MAILER_PORT=2025 # Port to mailcatcher docker
```

Then it instantly works, and all emails AFFiNE tries to send will end up in that simple webinterface.

**Comment by automainint** [comment]
> Means you dont have mail stuff setup.

I don't understand. I'm not self-hosting, I'm just trying to sign in on app.affine.pro

**Comment by forehalo** [comment]
it should recovered, right? there was a small downtime of the server days before

**Comment by automainint** [comment]
> it should recovered, right? there was a small downtime of the server days before

Yes, it works now.
