### ISSUE TITLE
The default page sentence in All pages is incorrect

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#891]
Should be changed to

-  "Tips: Use ⌘ + N to quickly create your first page“ for Mac
- "Tips: Use Ctrl + N to quickly create your first page“ for Win and Linux

![Image](https://user-images.githubusercontent.com/22443345/217257190-ad54fcc1-5976-4753-b35d-83507597e96b.png)

**Comment by QiShaoXuan** [comment]
This shortcut can not support temporary, so not use this tip yet

**Comment by joebeijing** [comment]
Can we change the tips to "This workspace is empty"? @QiShaoXuan
