### ISSUE TITLE
Unable to create new page with ⌘/Ctrl + N

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#892]

**Comment by JimmFly** [comment]
Any suggestions for more details? For example, which scenes are available and which scenes are not available.

**Comment by JimmFly** [comment]
It seems that Ctrl+N conflicts with the shortcut key of the browser, maybe it would be better to support it in the client?
cc @tzhangchi @linonetwo

**Comment by joebeijing** [comment]
Agree with that
