### ISSUE TITLE
​Properties (CLOSED- me dumb, it's in info)

### ISSUE THREAD

**Issue by A-Z-X-R** [toeverything/AFFiNE#8960]
### Description

It's free real estate baby! I want to add properties of my own like how I do in Anytype and Obsidian. To be honest I don't even know why the development choice of using some 'info' thing instead of YAML frontmatter was used but either ways... I want to add my own properties

### Use case

This is useful for indexing and organising, especially when we ZK users don't exactly put stuff into folders

### Anything else?

Look at either 
a) YAML frontmatter in Obsidian (might be difficult now, considering this is already pretty far in development) or
b) custom properties in Anytype.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
you can add custom properties in workspace settings
