### ISSUE TITLE
​Logo pixelated on iOS devices

### ISSUE THREAD

**Issue by OliverRM** [toeverything/AFFiNE#8971]
### What happened?

I’m using self-hosted AFFiNE on iPhone and iPad. Thanks to iOS’s inbuilt support for Progressive Web Apps it behaves mostly like a real app. I’ve notices that the AFFiNE logo on the home screen is rather pixelated, as to be seen on this screenshot:

<img src="https://github.com/user-attachments/assets/75b037e8-4aee-4bd3-b1c8-72925b851b5b" height="400">

I believe this to be due to the content of [apple-touch-icon.png](https://github.com/toeverything/AFFiNE/blob/v0.18.2/packages/frontend/core/public/apple-touch-icon.png) and other files in the same folder being in a significantly lower resolution than the file itself:

<img src="https://github.com/user-attachments/assets/20eb74d4-160c-4463-bedf-6d97d6ae8bb0" height="250">

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Safari

### Are you self-hosting?

- [X] Yes

### Anything else?

- Is there any specific reason for this or did this happen unintentionally?
- In the background there is a grid. Should this be there?

If of interest, I can happily prepare a pull request with updated files.

**Comment by CatsJuice** [comment]
Actually, that’s how it was designed. However, it might be replaced in the near future.
