### ISSUE TITLE
Global disable switch for AI

### ISSUE THREAD

**Issue by Tealk** [toeverything/AFFiNE#8989]
### Description

An option for the administration to disable AI completely, or that it is hidden if none is configured.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by bfcns** [comment]
This is one of the features needed desperately.

**Comment by Tealk** [comment]
I saw this in canary v3, but unfortunately it's stuck in a loop so I can't make a screen.

**Comment by missingfile** [comment]
Seems like this is a duplicate of #6920

**Comment by Tealk** [comment]
Yes sounds like the same
