### ISSUE TITLE
sentry.io connections despite telemetry switched off

### ISSUE THREAD

**Issue by Tealk** [toeverything/AFFiNE#8991]
### What happened?

Ich habe sowohl am server als auch über die Weboberfläche die telemetrie abeschaltet dennoch wird laut Netzwerkanalyse verbindungen zu sentry.io aufgebaut

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
sentry.io is used for error reporting, the data upload is only used to help us better diagnosing bugs and will not include any privacy regarding data.

**Comment by Tealk** [comment]
Nevertheless, a connection to the domain is established every x seconds, my log is full of connection attempts. Also, if I switch off telemetry, I assume that everything is switched off, at least that's what the GDPR requires.

**Comment by samyogdhital** [comment]
@forehalo, @Tealk any update on this? I am trying to have confidential stuffs here. So, want you make sure that we can turn off every telemetry data.
An environment variable that does this telemetry disabling will solve the problem.

For tracking issues, I think enterprise users give affine team enough data to see the error log. And I am also one of the users of pro version.
But for some separate document I choose to self-host it, so no data is out from there.
Would love to get this feature in self-host version @Affine team.
