### ISSUE TITLE
Login failed 

### ISSUE THREAD

**Issue by DiamondThree** [toeverything/AFFiNE#901]
Logon failed when use google

![image](https://user-images.githubusercontent.com/24630517/217419319-f29ca38c-bb9c-41ae-a934-201d4398bda0.png)

**Comment by tzhangchi** [comment]
@Yipei-Operation We track the login bug in this issue

**Comment by DiamondThree** [comment]
![image](https://user-images.githubusercontent.com/24630517/217421564-9cb8e4f1-5edf-4b9e-8a7a-10fe7ef23558.png)
