### ISSUE TITLE
​AFFiNE Client Sync CLOUD Always loading

### ISSUE THREAD

**Issue by EvoBread** [toeverything/AFFiNE#9048]
### What happened?

AFFiNE Client Sync CLOUD Always loading
<img width="232" alt="image" src="https://github.com/user-attachments/assets/902edf4f-c050-4bba-9de1-f185493ef903">
<img width="636" alt="image" src="https://github.com/user-attachments/assets/1aa41e14-15fe-433a-9279-81cc4e81d9b4">
<img width="709" alt="image" src="https://github.com/user-attachments/assets/cb33eeaa-8f51-4f8f-a4f6-058244c6169d">

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Other

### Are you self-hosting?

- [ ] Yes

**Comment by forehalo** [comment]
You must enabled the 'Offline Mode' in settings

**Comment by EvoBread** [comment]
It is open, Browser display is good, but client is always loading
<img width="638" alt="image" src="https://github.com/user-attachments/assets/c17ab0c4-5e32-4d78-929c-9cfe278c83f1">

**Comment by EvoBread** [comment]
disabled the 'Offline Mode' in settings, it's ok
