### ISSUE TITLE
​turn off sync

### ISSUE THREAD

**Issue by EvoBread** [toeverything/AFFiNE#9050]
### Description

After starting AFFiNE Cloud, can you turn off synchronization? It is best to sync at any time and turn off at any time?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
not yet supported

**Comment by EvoBread** [comment]
I want to ask if I can freely sync files or folders between different workspaces

**Comment by forehalo** [comment]
afaik, there won't be cross workspace functionality
