### ISSUE TITLE
when I open the home page, it redirect to 404 page , then click back home page, I can't restore the right home page

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#906]

**Comment by tzhangchi** [comment]
https://www.loom.com/share/0c3156f3dae54200bdadee9a578889b4 @alt1o

**Comment by zuoxiaodong0815** [comment]
https://stage.affine.pro/workspace. when visiting this link, browser show white screen.

**Comment by tzhangchi** [comment]
> https://stage.affine.pro/workspace. When visiting this link, browser show white screen.

I seems that the latest version make the /workspace not auto redirect
