### ISSUE TITLE
​Exported .affine file loses folder structure upon import

### ISSUE THREAD

**Issue by senan-sh** [toeverything/AFFiNE#9069]
### What happened?

I exported a .affine file from my PC and sent it to another PC. After importing the file on the second PC:

All pages were successfully imported.
However, the folder structure and organization were completely lost.
Steps to reproduce:

Export a project as a .affine file from PC 1.
Transfer the .affine file to another PC (PC 2).
Import the file into the application on PC 2.
Observe the imported content.
Expected behavior: The folder structure and organization of the project should remain intact after importing the file on the second PC.

Actual behavior: All pages were imported, but the folder structure and hierarchy were missing.

Environment:

PC 1:
Operating System: [Windows 11]
Affine version: [0.18.2]
PC 2:
Operating System: [Windows 11]
Affine version: [0.18.2]
Additional context:

Both PCs were using the same Affine version.
The exported file size and transfer process seemed normal.
Attachments:

Example .affine file demonstrating the issue (if possible).
Screenshots or a video showing the difference in structure before export and after import.

**Comment by forehalo** [comment]
duplicated #8559
