### ISSUE TITLE
The email account information for sending sharing invitations needs to be modified

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#908]
1. Set the email account name to AFFiNE, currently it is empty
2. Change the avatar to AFFiNE's Logo
3. The prefix of email address needs to be changed from ”noreply“ to ”invitation“

![Image](https://user-images.githubusercontent.com/22443345/217489774-3646a2ec-a93f-4420-881f-a72b35ab9441.png)

**Comment by tzhangchi** [comment]
Perhaps this bug should be followed by @darkskygit

**Comment by tzhangchi** [comment]
@JimmFly You could follow it
