### ISSUE TITLE
When cancel the implementation of delete doc, the "move to trash" just pops up

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#916]
![Image](https://user-images.githubusercontent.com/121489905/217713143-3e38c8e6-e811-4122-a66e-59ab23de75ad.png)
![Image](https://user-images.githubusercontent.com/121489905/217713144-db737d20-862f-4922-8c0d-7e01907a880c.png)

**Comment by tzhangchi** [comment]
@QiShaoXuan
