### ISSUE TITLE
Allow configuration via env variable

### ISSUE THREAD

**Issue by A2va** [toeverything/AFFiNE#9181]
### Description

At the moment all affine configuration is done via the `~/.affine/self-host/config/.env' file, it would be really great to be able to set it via an environment variable.

### Use case

I'd like to keep the amount of files for each service that I host to a minimum and try to put them all in the same place (i.e. compose file) because it's easier to maintain.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
you can set variables in 'environment' under service section in the compose.yml
