### ISSUE TITLE
Incorrect positions of workspace info and expand menu

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#922]
![Image](https://user-images.githubusercontent.com/110808979/217735020-f38a9cc9-a47c-43d6-b6f7-587a4651587e.png)

**Comment by Svaney-ssman** [comment]
missing the border-radius while hovering

**Comment by Svaney-ssman** [comment]
check figma link here: https://www.figma.com/file/DGWHxU8cZHGT1pksAbRZlZ/virgo-2-1.0-editor-area(AFFiNE)?node-id=10426%3A15592&t=XMHBdlqvqdr1WtOE-4

**Comment by doodlewind** [comment]
Closed by #1058
