### ISSUE TITLE
Text selection in edgeless mode not working

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#926]
https://user-images.githubusercontent.com/14026360/217740665-877ccd87-230e-4efc-b032-a50cd517a7df.mp4

/cc @fundon

**Comment by himself65** [comment]
if you wanna know how to develop affine in you local, let me know

**Comment by fundon** [comment]
I ran it locally, tested it, felt it was unstable, and there was a problem with the range of the text.

**Comment by fundon** [comment]
@Himself65 How to integrate blocksuite master branch in local.

**Comment by doodlewind** [comment]
> @Himself65 How to integrate blocksuite master branch in local.

Simply add `LOCAL_BLOCK_SUITE` env in `.env.local`. For example:

```
LOCAL_BLOCK_SUITE=/Users/ewind/code/blocksuite
```
