### ISSUE TITLE
Google avatar image cannot be loaded

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#930]
![Image](https://user-images.githubusercontent.com/584378/217757991-f9b1e5a7-2a6b-457e-9aa9-dc0703722515.png)

Looks like google does not allow resources like https://lh3.googleusercontent.com/a/AEdFTp6LXZS60HzyX5P1a7c4_g54zwG85csJ97NjubWOqG8=s96-c to be loaded cross-origin.

Maybe proxy the resource in the server side?

**Comment by tzhangchi** [comment]
@darkskygit Need some research

**Comment by doodlewind** [comment]
Not reproduced in latest stage



![Image](https://user-images.githubusercontent.com/7312949/219538975-f14f0b76-c00e-4ce9-9fd5-9cff6d265d2b.png)
