### ISSUE TITLE
​AFFiNE predeploy fails on stable-8de0679

### ISSUE THREAD

**Issue by Timtaran** [toeverything/AFFiNE#9379]
### What happened?

logs: https://pastebin.com/Kwt5Xg7n
migration from latest 0.18 stable

### Distribution version

Web (app.affine.pro)

### Are you self-hosting?

- [X] Yes

### Anything else?

For anyone who having problems, check this comments:
https://github.com/toeverything/AFFiNE/issues/9379#issuecomment-2563605431
https://github.com/toeverything/AFFiNE/issues/9379#issuecomment-2563481383
https://github.com/toeverything/AFFiNE/issues/9379#issuecomment-2563512405
https://github.com/toeverything/AFFiNE/issues/9379#issuecomment-2563521838 (both the docker and affine .envs)

**Comment by forehalo** [comment]
the old compose.yml is deprecated, you can try with the new one `https://github.com/toeverything/affine/releases/latest/download/docker-compose.yaml`

**Comment by forehalo** [comment]
and we are preparing the latest docs regarding this

**Comment by forehalo** [comment]
if the error continuously happen, you may need to delete the old .env file in your config folder, or only the `AFFINE_PRIVATE_KEY` in that file. it's safe and only used to sign the onetime token

**Comment by Timtaran** [comment]
> the old compose.yml is deprecated, you can try with the new one `https://github.com/toeverything/affine/releases/latest/download/docker-compose.yaml`

Did you know how I can use same db?
I having the `initdb: error: directory "/var/lib/postgresql/data" exists but is not empty` error with new compose

**Comment by forehalo** [comment]
try removing the line `POSTGRES_INITDB_ARGS: '--data-checksums'`

**Comment by Timtaran** [comment]
> try removing the line `POSTGRES_INITDB_ARGS: '--data-checksums'`

not helps
google says this is permission issues probably, but I'm not sure how to fix it

**Comment by Timtaran** [comment]
probably fixed it with adding `PGDATA: /var/lib/postgresql/data/pgdata` into environments

predeploy error is still here

**Comment by Timtaran** [comment]
my bad, wrong db data directory

**Comment by forehalo** [comment]
oh, it's quite a mistake, this one was totally forgotten

**Comment by Timtaran** [comment]
> oh, it's quite a mistake, this one was totally forgotten

yeah, you probably should mention that new path would be `~/.affine/self-host/postgres/data/pgdata` if user copying from old compose

**Comment by Timtaran** [comment]
> oh, it's quite a mistake, this one was totally forgotten

yeah, you probably should mention that new path would be `~/.affine/self-host/postgres/pgdata` when switching from old compose

migration is completes, but predeploy error is still here

**Comment by forehalo** [comment]
delete `AFFINE_PRIVATE_KEY` in your .env

**Comment by Timtaran** [comment]
not helps

**Comment by YummYume** [comment]
Same issue here, Redis and Postgres launch fine but the migration service fails with `ERR_OSSL_UNSUPPORTED` (I am using the new compose and adapted it to my existing configuration). I never had an `AFFINE_PRIVATE_KEY` variable set.

**Comment by jtmaveryk** [comment]
Same issue.

**Comment by forehalo** [comment]
this is strange. the crypto library only error with outdated key format.
I will do more research on that

**Comment by Timtaran** [comment]
> this is strange. the crypto library only error with outdated key format. I will do more research on that

maybe something wrong with this https://github.com/toeverything/AFFiNE/blob/canary/packages/backend/server/scripts/self-host-predeploy.js#L16 ?

**Comment by forehalo** [comment]
it might be related to #9389 as well. If you see some errors regarding redis connection, try add the following env to your affine and affine_migration service in `compose.yml`
```
- REDIS_SERVER_HOST=redis
```

**Comment by cethink** [comment]
Same issue.

**Comment by YummYume** [comment]
Update : it seems the Redis service had a volume on the old compose file. Deleting that volume fixed it for me.

**Comment by cethink** [comment]
fresh install and I got this:

```
> docker logs affine_server

[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

**Comment by Timtaran** [comment]
> fresh install and I got this:
> 
> ```
> > docker logs affine_server
> 
> [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
> [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
> Error: connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
>   errno: -111,
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 6379
> }
> Error: connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
>   errno: -111,
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 6379
> }
> ```

https://github.com/toeverything/AFFiNE/issues/9379#issuecomment-2563605431

**Comment by nimishchaudhari** [comment]
I happened to be trying Affine for the first time and my latest release has this issue. can you suggest which tag to use to try a stable release ? :)

**Comment by cethink** [comment]
> > fresh install and I got this:
> > ```
> > > docker logs affine_server
> > 
> > [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
> >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
> > [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
> >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
> > Error: connect ECONNREFUSED 127.0.0.1:6379
> >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
> >   errno: -111,
> >   code: 'ECONNREFUSED',
> >   syscall: 'connect',
> >   address: '127.0.0.1',
> >   port: 6379
> > }
> > Error: connect ECONNREFUSED 127.0.0.1:6379
> >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
> >   errno: -111,
> >   code: 'ECONNREFUSED',
> >   syscall: 'connect',
> >   address: '127.0.0.1',
> >   port: 6379
> > }
> > ```
> 
> [#9379 (comment)](https://github.com/toeverything/AFFiNE/issues/9379#issuecomment-2563605431)

thanks, worked

**Comment by nimishchaudhari** [comment]
> > > fresh install and I got this:
> > > ```
> > > > docker logs affine_server
> > > 
> > > [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
> > >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
> > > [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
> > >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
> > > Error: connect ECONNREFUSED 127.0.0.1:6379
> > >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
> > >   errno: -111,
> > >   code: 'ECONNREFUSED',
> > >   syscall: 'connect',
> > >   address: '127.0.0.1',
> > >   port: 6379
> > > }
> > > Error: connect ECONNREFUSED 127.0.0.1:6379
> > >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
> > >   errno: -111,
> > >   code: 'ECONNREFUSED',
> > >   syscall: 'connect',
> > >   address: '127.0.0.1',
> > >   port: 6379
> > > }
> > > ```
> > 
> > 
> > [#9379 (comment)](https://github.com/toeverything/AFFiNE/issues/9379#issuecomment-2563605431)
> 
> thanks, worked

I confirm it worked too, however the HTML page is not rendered correctly, will try a fresh install

**Comment by cethink** [comment]
> I happened to be trying Affine for the first time and my latest release has this issue. can you suggest which tag to use to try a stable release ? :)

see https://github.com/toeverything/AFFiNE/pkgs/container/affine-graphql

**Comment by cethink** [comment]
> > > > fresh install and I got this:
> > > > ```
> > > > > docker logs affine_server
> > > > 
> > > > [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
> > > >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
> > > > [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
> > > >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
> > > > Error: connect ECONNREFUSED 127.0.0.1:6379
> > > >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
> > > >   errno: -111,
> > > >   code: 'ECONNREFUSED',
> > > >   syscall: 'connect',
> > > >   address: '127.0.0.1',
> > > >   port: 6379
> > > > }
> > > > Error: connect ECONNREFUSED 127.0.0.1:6379
> > > >     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16) {
> > > >   errno: -111,
> > > >   code: 'ECONNREFUSED',
> > > >   syscall: 'connect',
> > > >   address: '127.0.0.1',
> > > >   port: 6379
> > > > }
> > > > ```
> > > 
> > > 
> > > [#9379 (comment)](https://github.com/toeverything/AFFiNE/issues/9379#issuecomment-2563605431)
> > 
> > 
> > thanks, worked
> 
> I confirm it worked too, however the HTML page is not rendered correctly, will try a fresh install

try this

![image](https://github.com/user-attachments/assets/39e5eb67-bb6c-4563-9b12-773a03d9e3ed)

**Comment by teynar** [comment]
HTML is not being rendered properly for me either, despite deleting all website data and clearing cookies

![imagen](https://github.com/user-attachments/assets/415e4e4b-e623-4e7d-a111-9ec26ce7a338)

**Comment by Brooooooklyn** [comment]
@teynar admin panel rendering issue was fixed in https://github.com/toeverything/AFFiNE/issues/9392

**Comment by alienbob** [comment]
I encountered that same "Error: error:1E08010C:DECODER routines::unsupported" from the screenshot as well, coming from a self-hosted 0.18. After I applied all of the changes between the 0.18 compose.yaml and the 0.19.1 docker-compose.yml the error was gone and my selfhosted AFFiNE 0.19.1 Docker stack is running nicely.

**Comment by Timtaran** [comment]
> delete `AFFINE_PRIVATE_KEY` in your .env

bruh, I thought you mean AFFiNE .env because it appeared there, I put `AFFINE_PRIVATE_KEY=./private.key` in docker .env when I tried to generate key myself and forgot lol
