### ISSUE TITLE
​broken admin page

### ISSUE THREAD

**Issue by Tealk** [toeverything/AFFiNE#9392]
### What happened?

Since the update to 0.19.0 the admin page is broken, it seems as if the css is not loaded, but I get no errors in the console.
![image](https://github.com/user-attachments/assets/6a592227-0dd4-4bce-afd3-5c7dc14bbc67)

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [X] Yes

**Comment by forehalo** [comment]
confirmed and will be fixed by #9391

**Comment by Tealk** [comment]
0.19.1 has fixed it
thank you
