### ISSUE TITLE
Unable to implement the publish, export and other functionalities as invitation step is done

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#959]
https://user-images.githubusercontent.com/121489905/218403388-d2abf871-9a7d-403a-a110-8e5abf7974c2.mp4

**Comment by tzhangchi** [comment]
@JackiePengp you could try stage environment, perhaps it had been fixed yesterday

**Comment by doodlewind** [comment]
Closed by #1064
