### ISSUE TITLE
Support page tree

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#972]

**Comment by QiShaoXuan** [comment]
## In AFFiNE

- [ ] Rewrite sidebar style(since the page tree insert sidebar, the UI need to modify)
- [ ] With AFFine style
- [ ] Support interaction in AFFiNE
    - [ ] Pivot need operation menu
    - [ ] Menu with Pivots
        - [ ] Supports search
        - [ ] Supports up and down direction keyboard key selection
        - [ ] Supports open on elsewhere, like all page list operation menu

**Comment by QiShaoXuan** [comment]
Close with last pr：https://github.com/toeverything/AFFiNE/pull/1871/
