### ISSUE TITLE
cannot provoke the numbered list through slash menu

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/AFFiNE#975]
https://user-images.githubusercontent.com/121489905/218634260-08bad709-c639-4f6a-927b-745028742e53.mp4

**Comment by ShortCipher5** [comment]
More details - lists only work from the "all" list and do not work form the "list" family from the left.

**Comment by ShortCipher5** [comment]
![Image](https://user-images.githubusercontent.com/4605025/218634804-b04b643a-04ef-422a-ab99-844326c3adcc.gif)

**Comment by lawvs** [comment]
Closing as the issue cannot be reproduced.
