### ISSUE TITLE
After logging in, try to enable the AFFiNE Cloud service for a local workspace, it keeps showing loading

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#978]
From observation, it should be successful.

![Image](https://user-images.githubusercontent.com/22443345/218663216-9f5b0eb0-debb-48a0-98e7-107fa220ee19.png)

**Comment by tzhangchi** [comment]
@pengx17 perhaps it is the same issue which I found yesterday

**Comment by pengx17** [comment]
Working on it.

**Comment by pengx17** [comment]
fixed by https://github.com/toeverything/AFFiNE/pull/999
