### ISSUE TITLE
Pages with long titles in Favorites should end with ...

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#980]
Actual effect
![Image](https://user-images.githubusercontent.com/22443345/218668334-d9765c28-4e98-45fa-b653-12cd46abbbdb.png)

Expected effect
Just like Notion's

![Image](https://user-images.githubusercontent.com/22443345/218668549-2df076da-a451-48cd-aca3-4251d4db627d.png)

**Comment by tzhangchi** [comment]
@QiShaoXuan
