### ISSUE TITLE
Returning to the Workspace homepage from a single document in a public workspace, there are problems with the UI

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#990]
1. You can see a default placeholder which should only be displayed while no pages
2. The Workspace icon will appear as A for a moment
Recorded video is attached

https://user-images.githubusercontent.com/22443345/218684969-5a861667-fc54-4782-9855-1fe2c70214f2.mov

**Comment by tzhangchi** [comment]
@QiShaoXuan
